"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AddSquare48Filled = exports.AddSquare48Regular = exports.AddSquare32Filled = exports.AddSquare32Regular = exports.AddSquare28Filled = exports.AddSquare28Regular = exports.AddSquare24Filled = exports.AddSquare24Regular = exports.AddSquare20Filled = exports.AddSquare20Regular = exports.AddSquare16Filled = exports.AddSquare16Regular = exports.AddSquareRegular = exports.AddSquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AddSquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquareFilled", "", 2, undefined));
exports.AddSquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquareRegular", "", 2, undefined));
exports.AddSquare16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare16Regular", "󰇢", 1, 16));
exports.AddSquare16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare16Filled", "󰇢", 0, 16));
exports.AddSquare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare20Regular", "", 1, 20));
exports.AddSquare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare20Filled", "", 0, 20));
exports.AddSquare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare24Regular", "", 1, 24));
exports.AddSquare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare24Filled", "", 0, 24));
exports.AddSquare28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare28Regular", "󰇣", 1, 28));
exports.AddSquare28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare28Filled", "󰇣", 0, 28));
exports.AddSquare32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare32Regular", "󰇤", 1, 32));
exports.AddSquare32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare32Filled", "󰇤", 0, 32));
exports.AddSquare48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare48Regular", "󰇥", 1, 48));
exports.AddSquare48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AddSquare48Filled", "󰇥", 0, 48));
