"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Airplane48Filled = exports.Airplane48Regular = exports.Airplane32Filled = exports.Airplane32Regular = exports.Airplane28Filled = exports.Airplane28Regular = exports.Airplane24Filled = exports.Airplane24Regular = exports.Airplane20Filled = exports.Airplane20Regular = exports.Airplane16Filled = exports.Airplane16Regular = exports.AirplaneRegular = exports.AirplaneFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AirplaneFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AirplaneFilled", "", 2, undefined));
exports.AirplaneRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AirplaneRegular", "", 2, undefined));
exports.Airplane16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane16Regular", "󰚍", 1, 16));
exports.Airplane16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane16Filled", "󰜈", 0, 16));
exports.Airplane20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane20Regular", "", 1, 20));
exports.Airplane20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane20Filled", "", 0, 20));
exports.Airplane24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane24Regular", "", 1, 24));
exports.Airplane24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane24Filled", "", 0, 24));
exports.Airplane28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane28Regular", "󰚎", 1, 28));
exports.Airplane28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane28Filled", "󰜉", 0, 28));
exports.Airplane32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane32Regular", "󰚏", 1, 32));
exports.Airplane32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane32Filled", "󰜊", 0, 32));
exports.Airplane48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane48Regular", "󰚐", 1, 48));
exports.Airplane48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Airplane48Filled", "󰜋", 0, 48));
