"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertUrgent24Filled = exports.AlertUrgent24Regular = exports.AlertUrgent20Filled = exports.AlertUrgent20Regular = exports.AlertUrgent16Filled = exports.AlertUrgent16Regular = exports.AlertUrgentRegular = exports.AlertUrgentFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AlertUrgentFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgentFilled", "", 2, undefined));
exports.AlertUrgentRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgentRegular", "", 2, undefined));
exports.AlertUrgent16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgent16Regular", "", 1, 16));
exports.AlertUrgent16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgent16Filled", "", 0, 16));
exports.AlertUrgent20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgent20Regular", "", 1, 20));
exports.AlertUrgent20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgent20Filled", "", 0, 20));
exports.AlertUrgent24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgent24Regular", "", 1, 24));
exports.AlertUrgent24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertUrgent24Filled", "", 0, 24));
