"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertOff28Filled = exports.AlertOff28Regular = exports.AlertOff24Filled = exports.AlertOff24Regular = exports.AlertOff20Filled = exports.AlertOff20Regular = exports.AlertOff16Filled = exports.AlertOff16Regular = exports.AlertOffRegular = exports.AlertOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AlertOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOffFilled", "", 2, undefined));
exports.AlertOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOffRegular", "", 2, undefined));
exports.AlertOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff16Regular", "", 1, 16));
exports.AlertOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff16Filled", "", 0, 16));
exports.AlertOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff20Regular", "", 1, 20));
exports.AlertOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff20Filled", "", 0, 20));
exports.AlertOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff24Regular", "", 1, 24));
exports.AlertOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff24Filled", "", 0, 24));
exports.AlertOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff28Regular", "", 1, 28));
exports.AlertOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlertOff28Filled", "", 0, 28));
