"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlignTop48Filled = exports.AlignTop48Regular = exports.AlignTop32Filled = exports.AlignTop32Regular = exports.AlignTop28Filled = exports.AlignTop28Regular = exports.AlignTop24Filled = exports.AlignTop24Regular = exports.AlignTop20Filled = exports.AlignTop20Regular = exports.AlignTop16Filled = exports.AlignTop16Regular = exports.AlignTopRegular = exports.AlignTopFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AlignTopFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTopFilled", "", 2, undefined));
exports.AlignTopRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTopRegular", "", 2, undefined));
exports.AlignTop16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop16Regular", "", 1, 16));
exports.AlignTop16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop16Filled", "", 0, 16));
exports.AlignTop20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop20Regular", "", 1, 20));
exports.AlignTop20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop20Filled", "", 0, 20));
exports.AlignTop24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop24Regular", "", 1, 24));
exports.AlignTop24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop24Filled", "", 0, 24));
exports.AlignTop28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop28Regular", "", 1, 28));
exports.AlignTop28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop28Filled", "", 0, 28));
exports.AlignTop32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop32Regular", "", 1, 32));
exports.AlignTop32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop32Filled", "", 0, 32));
exports.AlignTop48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop48Regular", "", 1, 48));
exports.AlignTop48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignTop48Filled", "", 0, 48));
