"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlignRight48Filled = exports.AlignRight48Regular = exports.AlignRight32Filled = exports.AlignRight32Regular = exports.AlignRight28Filled = exports.AlignRight28Regular = exports.AlignRight24Filled = exports.AlignRight24Regular = exports.AlignRight20Filled = exports.AlignRight20Regular = exports.AlignRight16Filled = exports.AlignRight16Regular = exports.AlignRightRegular = exports.AlignRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AlignRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRightFilled", "", 2, undefined));
exports.AlignRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRightRegular", "", 2, undefined));
exports.AlignRight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight16Regular", "", 1, 16));
exports.AlignRight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight16Filled", "", 0, 16));
exports.AlignRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight20Regular", "", 1, 20));
exports.AlignRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight20Filled", "", 0, 20));
exports.AlignRight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight24Regular", "", 1, 24));
exports.AlignRight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight24Filled", "", 0, 24));
exports.AlignRight28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight28Regular", "", 1, 28));
exports.AlignRight28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight28Filled", "", 0, 28));
exports.AlignRight32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight32Regular", "", 1, 32));
exports.AlignRight32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight32Filled", "", 0, 32));
exports.AlignRight48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight48Regular", "", 1, 48));
exports.AlignRight48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AlignRight48Filled", "", 0, 48));
