"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnimalCat28Filled = exports.AnimalCat28Regular = exports.AnimalCat24Filled = exports.AnimalCat24Regular = exports.AnimalCat20Filled = exports.AnimalCat20Regular = exports.AnimalCat16Filled = exports.AnimalCat16Regular = exports.AnimalCatRegular = exports.AnimalCatFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AnimalCatFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCatFilled", "", 2, undefined));
exports.AnimalCatRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCatRegular", "", 2, undefined));
exports.AnimalCat16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat16Regular", "", 1, 16));
exports.AnimalCat16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat16Filled", "", 0, 16));
exports.AnimalCat20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat20Regular", "", 1, 20));
exports.AnimalCat20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat20Filled", "", 0, 20));
exports.AnimalCat24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat24Regular", "", 1, 24));
exports.AnimalCat24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat24Filled", "", 0, 24));
exports.AnimalCat28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat28Regular", "", 1, 28));
exports.AnimalCat28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalCat28Filled", "", 0, 28));
