"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnimalRabbit32Filled = exports.AnimalRabbit32Regular = exports.AnimalRabbit28Filled = exports.AnimalRabbit28Regular = exports.AnimalRabbit24Filled = exports.AnimalRabbit24Regular = exports.AnimalRabbit20Filled = exports.AnimalRabbit20Regular = exports.AnimalRabbit16Filled = exports.AnimalRabbit16Regular = exports.AnimalRabbitRegular = exports.AnimalRabbitFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AnimalRabbitFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbitFilled", "", 2, undefined));
exports.AnimalRabbitRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbitRegular", "", 2, undefined));
exports.AnimalRabbit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit16Regular", "", 1, 16));
exports.AnimalRabbit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit16Filled", "", 0, 16));
exports.AnimalRabbit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit20Regular", "", 1, 20));
exports.AnimalRabbit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit20Filled", "", 0, 20));
exports.AnimalRabbit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit24Regular", "", 1, 24));
exports.AnimalRabbit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit24Filled", "", 0, 24));
exports.AnimalRabbit28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit28Regular", "", 1, 28));
exports.AnimalRabbit28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit28Filled", "", 0, 28));
exports.AnimalRabbit32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit32Regular", "", 1, 32));
exports.AnimalRabbit32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AnimalRabbit32Filled", "", 0, 32));
