"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppGeneric48Filled = exports.AppGeneric48Regular = exports.AppGeneric32Light = exports.AppGeneric32Filled = exports.AppGeneric32Regular = exports.AppGeneric24Filled = exports.AppGeneric24Regular = exports.AppGeneric20Filled = exports.AppGeneric20Regular = exports.AppGenericRegular = exports.AppGenericFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AppGenericFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGenericFilled", "", 2, undefined));
exports.AppGenericRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGenericRegular", "", 2, undefined));
exports.AppGeneric20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric20Regular", "", 1, 20));
exports.AppGeneric20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric20Filled", "", 0, 20));
exports.AppGeneric24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric24Regular", "", 1, 24));
exports.AppGeneric24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric24Filled", "", 0, 24));
exports.AppGeneric32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric32Regular", "", 1, 32));
exports.AppGeneric32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric32Filled", "", 0, 32));
exports.AppGeneric32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric32Light", "", 3, 32));
exports.AppGeneric48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric48Regular", "󰅞", 1, 48));
exports.AppGeneric48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppGeneric48Filled", "󰅝", 0, 48));
