"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppRecent24Filled = exports.AppRecent24Regular = exports.AppRecent20Filled = exports.AppRecent20Regular = exports.AppRecentRegular = exports.AppRecentFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AppRecentFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppRecentFilled", "", 2, undefined));
exports.AppRecentRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppRecentRegular", "", 2, undefined));
exports.AppRecent20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppRecent20Regular", "", 1, 20));
exports.AppRecent20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppRecent20Filled", "", 0, 20));
exports.AppRecent24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppRecent24Regular", "", 1, 24));
exports.AppRecent24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppRecent24Filled", "", 0, 24));
