"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppsList32Filled = exports.AppsList32Regular = exports.AppsList24Filled = exports.AppsList24Regular = exports.AppsList20Filled = exports.AppsList20Regular = exports.AppsListRegular = exports.AppsListFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AppsListFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsListFilled", "", 2, undefined));
exports.AppsListRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsListRegular", "", 2, undefined));
exports.AppsList20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsList20Regular", "", 1, 20));
exports.AppsList20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsList20Filled", "", 0, 20));
exports.AppsList24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsList24Regular", "", 1, 24));
exports.AppsList24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsList24Filled", "", 0, 24));
exports.AppsList32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsList32Regular", "󰟽", 1, 32));
exports.AppsList32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsList32Filled", "󰡺", 0, 32));
