"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppsShield20Filled = exports.AppsShield20Regular = exports.AppsShield16Filled = exports.AppsShield16Regular = exports.AppsShieldRegular = exports.AppsShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AppsShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsShieldFilled", "", 2, undefined));
exports.AppsShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsShieldRegular", "", 2, undefined));
exports.AppsShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsShield16Regular", "󰖞", 1, 16));
exports.AppsShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsShield16Filled", "󰘗", 0, 16));
exports.AppsShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsShield20Regular", "󰖟", 1, 20));
exports.AppsShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AppsShield20Filled", "󰘘", 0, 20));
