"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArchiveClock48Filled = exports.ArchiveClock48Regular = exports.ArchiveClock32Filled = exports.ArchiveClock32Regular = exports.ArchiveClock28Filled = exports.ArchiveClock28Regular = exports.ArchiveClock24Filled = exports.ArchiveClock24Regular = exports.ArchiveClock20Filled = exports.ArchiveClock20Regular = exports.ArchiveClock16Filled = exports.ArchiveClock16Regular = exports.ArchiveClockRegular = exports.ArchiveClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArchiveClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClockFilled", "", 2, undefined));
exports.ArchiveClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClockRegular", "", 2, undefined));
exports.ArchiveClock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock16Regular", "󰪍", 1, 16));
exports.ArchiveClock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock16Filled", "󰬉", 0, 16));
exports.ArchiveClock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock20Regular", "󰪎", 1, 20));
exports.ArchiveClock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock20Filled", "󰬊", 0, 20));
exports.ArchiveClock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock24Regular", "󰪏", 1, 24));
exports.ArchiveClock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock24Filled", "󰬋", 0, 24));
exports.ArchiveClock28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock28Regular", "󰪐", 1, 28));
exports.ArchiveClock28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock28Filled", "󰬌", 0, 28));
exports.ArchiveClock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock32Regular", "󰪑", 1, 32));
exports.ArchiveClock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock32Filled", "󰬍", 0, 32));
exports.ArchiveClock48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock48Regular", "󰪒", 1, 48));
exports.ArchiveClock48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArchiveClock48Filled", "󰬎", 0, 48));
