"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowRepeat124Filled = exports.ArrowRepeat124Regular = exports.ArrowRepeat120Filled = exports.ArrowRepeat120Regular = exports.ArrowRepeat116Filled = exports.ArrowRepeat116Regular = exports.ArrowRepeat1Filled = exports.ArrowRepeat1Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowRepeat1Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat1Regular", "", 2, undefined));
exports.ArrowRepeat1Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat1Filled", "", 2, undefined));
exports.ArrowRepeat116Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat116Regular", "", 1, 16));
exports.ArrowRepeat116Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat116Filled", "", 0, 16));
exports.ArrowRepeat120Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat120Regular", "", 1, 20));
exports.ArrowRepeat120Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat120Filled", "", 0, 20));
exports.ArrowRepeat124Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat124Regular", "", 1, 24));
exports.ArrowRepeat124Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRepeat124Filled", "", 0, 24));
