"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowSort28Filled = exports.ArrowSort28Regular = exports.ArrowSort24Filled = exports.ArrowSort24Regular = exports.ArrowSort20Filled = exports.ArrowSort20Regular = exports.ArrowSort16Filled = exports.ArrowSort16Regular = exports.ArrowSortRegular = exports.ArrowSortFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowSortFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSortFilled", "", 2, undefined));
exports.ArrowSortRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSortRegular", "", 2, undefined));
exports.ArrowSort16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort16Regular", "", 1, 16));
exports.ArrowSort16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort16Filled", "", 0, 16));
exports.ArrowSort20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort20Regular", "", 1, 20));
exports.ArrowSort20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort20Filled", "", 0, 20));
exports.ArrowSort24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort24Regular", "", 1, 24));
exports.ArrowSort24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort24Filled", "", 0, 24));
exports.ArrowSort28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort28Regular", "", 1, 28));
exports.ArrowSort28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowSort28Filled", "", 0, 28));
