"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowFit24Filled = exports.ArrowFit24Regular = exports.ArrowFit20Filled = exports.ArrowFit20Regular = exports.ArrowFit16Filled = exports.ArrowFit16Regular = exports.ArrowFitRegular = exports.ArrowFitFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowFitFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitFilled", "", 2, undefined));
exports.ArrowFitRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitRegular", "", 2, undefined));
exports.ArrowFit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFit16Regular", "", 1, 16));
exports.ArrowFit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFit16Filled", "", 0, 16));
exports.ArrowFit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFit20Regular", "", 1, 20));
exports.ArrowFit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFit20Filled", "", 0, 20));
exports.ArrowFit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFit24Regular", "󰏓", 1, 24));
exports.ArrowFit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFit24Filled", "󰏦", 0, 24));
