"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowExport24Filled = exports.ArrowExport24Regular = exports.ArrowExport20Filled = exports.ArrowExport20Regular = exports.ArrowExport16Filled = exports.ArrowExport16Regular = exports.ArrowExportRegular = exports.ArrowExportFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowExportFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExportFilled", "", 2, undefined, { flipInRtl: true }));
exports.ArrowExportRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExportRegular", "", 2, undefined, { flipInRtl: true }));
exports.ArrowExport16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExport16Regular", "󰉿", 1, 16, { flipInRtl: true }));
exports.ArrowExport16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExport16Filled", "󰊒", 0, 16, { flipInRtl: true }));
exports.ArrowExport20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExport20Regular", "󰊀", 1, 20, { flipInRtl: true }));
exports.ArrowExport20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExport20Filled", "󰊓", 0, 20, { flipInRtl: true }));
exports.ArrowExport24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExport24Regular", "󰊁", 1, 24, { flipInRtl: true }));
exports.ArrowExport24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowExport24Filled", "󰊔", 0, 24, { flipInRtl: true }));
