"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowRight48Filled = exports.ArrowRight48Regular = exports.ArrowRight32Filled = exports.ArrowRight32Regular = exports.ArrowRight28Filled = exports.ArrowRight28Regular = exports.ArrowRight24Filled = exports.ArrowRight24Regular = exports.ArrowRight20Filled = exports.ArrowRight20Regular = exports.ArrowRight16Filled = exports.ArrowRight16Regular = exports.ArrowRight12Filled = exports.ArrowRight12Regular = exports.ArrowRightRegular = exports.ArrowRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRightFilled", "", 2, undefined));
exports.ArrowRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRightRegular", "", 2, undefined));
exports.ArrowRight12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight12Regular", "", 1, 12));
exports.ArrowRight12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight12Filled", "", 0, 12));
exports.ArrowRight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight16Regular", "", 1, 16));
exports.ArrowRight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight16Filled", "", 0, 16));
exports.ArrowRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight20Regular", "", 1, 20));
exports.ArrowRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight20Filled", "", 0, 20));
exports.ArrowRight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight24Regular", "", 1, 24));
exports.ArrowRight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight24Filled", "", 0, 24));
exports.ArrowRight28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight28Regular", "", 1, 28));
exports.ArrowRight28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight28Filled", "", 0, 28));
exports.ArrowRight32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight32Regular", "", 1, 32));
exports.ArrowRight32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight32Filled", "", 0, 32));
exports.ArrowRight48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight48Regular", "", 1, 48));
exports.ArrowRight48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowRight48Filled", "", 0, 48));
