"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowUpLeft48Filled = exports.ArrowUpLeft48Regular = exports.ArrowUpLeft24Filled = exports.ArrowUpLeft24Regular = exports.ArrowUpLeft20Filled = exports.ArrowUpLeft20Regular = exports.ArrowUpLeft16Filled = exports.ArrowUpLeft16Regular = exports.ArrowUpLeftRegular = exports.ArrowUpLeftFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowUpLeftFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeftFilled", "", 2, undefined));
exports.ArrowUpLeftRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeftRegular", "", 2, undefined));
exports.ArrowUpLeft16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft16Regular", "", 1, 16));
exports.ArrowUpLeft16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft16Filled", "", 0, 16));
exports.ArrowUpLeft20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft20Regular", "", 1, 20));
exports.ArrowUpLeft20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft20Filled", "", 0, 20));
exports.ArrowUpLeft24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft24Regular", "", 1, 24));
exports.ArrowUpLeft24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft24Filled", "", 0, 24));
exports.ArrowUpLeft48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft48Regular", "", 1, 48));
exports.ArrowUpLeft48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpLeft48Filled", "", 0, 48));
