"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowImport24Filled = exports.ArrowImport24Regular = exports.ArrowImport20Filled = exports.ArrowImport20Regular = exports.ArrowImport16Filled = exports.ArrowImport16Regular = exports.ArrowImportRegular = exports.ArrowImportFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowImportFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImportFilled", "", 2, undefined, { flipInRtl: true }));
exports.ArrowImportRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImportRegular", "", 2, undefined, { flipInRtl: true }));
exports.ArrowImport16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImport16Regular", "󰎄", 1, 16, { flipInRtl: true }));
exports.ArrowImport16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImport16Filled", "󰎗", 0, 16, { flipInRtl: true }));
exports.ArrowImport20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImport20Regular", "", 1, 20, { flipInRtl: true }));
exports.ArrowImport20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImport20Filled", "", 0, 20, { flipInRtl: true }));
exports.ArrowImport24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImport24Regular", "", 1, 24, { flipInRtl: true }));
exports.ArrowImport24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowImport24Filled", "", 0, 24, { flipInRtl: true }));
