"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowFitIn24Filled = exports.ArrowFitIn24Regular = exports.ArrowFitIn20Filled = exports.ArrowFitIn20Regular = exports.ArrowFitIn16Filled = exports.ArrowFitIn16Regular = exports.ArrowFitInRegular = exports.ArrowFitInFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowFitInFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitInFilled", "", 2, undefined));
exports.ArrowFitInRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitInRegular", "", 2, undefined));
exports.ArrowFitIn16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitIn16Regular", "", 1, 16));
exports.ArrowFitIn16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitIn16Filled", "", 0, 16));
exports.ArrowFitIn20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitIn20Regular", "", 1, 20));
exports.ArrowFitIn20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitIn20Filled", "", 0, 20));
exports.ArrowFitIn24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitIn24Regular", "󰏔", 1, 24));
exports.ArrowFitIn24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowFitIn24Filled", "󰏧", 0, 24));
