"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowUp48Filled = exports.ArrowUp48Regular = exports.ArrowUp32Filled = exports.ArrowUp32Regular = exports.ArrowUp28Filled = exports.ArrowUp28Regular = exports.ArrowUp24Filled = exports.ArrowUp24Regular = exports.ArrowUp20Filled = exports.ArrowUp20Regular = exports.ArrowUp16Filled = exports.ArrowUp16Regular = exports.ArrowUp12Filled = exports.ArrowUp12Regular = exports.ArrowUpRegular = exports.ArrowUpFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowUpFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpFilled", "", 2, undefined, { flipInRtl: true }));
exports.ArrowUpRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpRegular", "", 2, undefined, { flipInRtl: true }));
exports.ArrowUp12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp12Regular", "", 1, 12, { flipInRtl: true }));
exports.ArrowUp12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp12Filled", "", 0, 12, { flipInRtl: true }));
exports.ArrowUp16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp16Regular", "", 1, 16, { flipInRtl: true }));
exports.ArrowUp16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp16Filled", "", 0, 16, { flipInRtl: true }));
exports.ArrowUp20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp20Regular", "", 1, 20, { flipInRtl: true }));
exports.ArrowUp20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp20Filled", "", 0, 20, { flipInRtl: true }));
exports.ArrowUp24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp24Regular", "", 1, 24, { flipInRtl: true }));
exports.ArrowUp24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp24Filled", "", 0, 24, { flipInRtl: true }));
exports.ArrowUp28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp28Regular", "", 1, 28, { flipInRtl: true }));
exports.ArrowUp28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp28Filled", "", 0, 28, { flipInRtl: true }));
exports.ArrowUp32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp32Regular", "", 1, 32, { flipInRtl: true }));
exports.ArrowUp32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp32Filled", "", 0, 32, { flipInRtl: true }));
exports.ArrowUp48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp48Regular", "", 1, 48, { flipInRtl: true }));
exports.ArrowUp48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUp48Filled", "", 0, 48, { flipInRtl: true }));
