"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowReply48Filled = exports.ArrowReply48Regular = exports.ArrowReply32Light = exports.ArrowReply32Filled = exports.ArrowReply32Regular = exports.ArrowReply28Filled = exports.ArrowReply28Regular = exports.ArrowReply24Filled = exports.ArrowReply24Regular = exports.ArrowReply20Filled = exports.ArrowReply20Regular = exports.ArrowReply16Filled = exports.ArrowReply16Regular = exports.ArrowReplyRegular = exports.ArrowReplyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowReplyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReplyFilled", "", 2, undefined, { flipInRtl: true }));
exports.ArrowReplyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReplyRegular", "", 2, undefined, { flipInRtl: true }));
exports.ArrowReply16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply16Regular", "", 1, 16, { flipInRtl: true }));
exports.ArrowReply16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply16Filled", "", 0, 16, { flipInRtl: true }));
exports.ArrowReply20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply20Regular", "", 1, 20, { flipInRtl: true }));
exports.ArrowReply20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply20Filled", "", 0, 20, { flipInRtl: true }));
exports.ArrowReply24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply24Regular", "", 1, 24, { flipInRtl: true }));
exports.ArrowReply24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply24Filled", "", 0, 24, { flipInRtl: true }));
exports.ArrowReply28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply28Regular", "", 1, 28, { flipInRtl: true }));
exports.ArrowReply28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply28Filled", "", 0, 28, { flipInRtl: true }));
exports.ArrowReply32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply32Regular", "󰐥", 1, 32, { flipInRtl: true }));
exports.ArrowReply32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply32Filled", "󰐸", 0, 32, { flipInRtl: true }));
exports.ArrowReply32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply32Light", "", 3, 32));
exports.ArrowReply48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply48Regular", "", 1, 48, { flipInRtl: true }));
exports.ArrowReply48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowReply48Filled", "", 0, 48, { flipInRtl: true }));
