"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowUpload32Filled = exports.ArrowUpload32Regular = exports.ArrowUpload24Filled = exports.ArrowUpload24Regular = exports.ArrowUpload20Filled = exports.ArrowUpload20Regular = exports.ArrowUpload16Filled = exports.ArrowUpload16Regular = exports.ArrowUploadRegular = exports.ArrowUploadFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowUploadFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUploadFilled", "", 2, undefined));
exports.ArrowUploadRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUploadRegular", "", 2, undefined));
exports.ArrowUpload16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload16Regular", "", 1, 16));
exports.ArrowUpload16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload16Filled", "", 0, 16));
exports.ArrowUpload20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload20Regular", "", 1, 20));
exports.ArrowUpload20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload20Filled", "", 0, 20));
exports.ArrowUpload24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload24Regular", "", 1, 24));
exports.ArrowUpload24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload24Filled", "", 0, 24));
exports.ArrowUpload32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload32Regular", "󰖠", 1, 32));
exports.ArrowUpload32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowUpload32Filled", "󰘙", 0, 32));
