"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArrowDown48Filled = exports.ArrowDown48Regular = exports.ArrowDown32Light = exports.ArrowDown32Filled = exports.ArrowDown32Regular = exports.ArrowDown28Filled = exports.ArrowDown28Regular = exports.ArrowDown24Filled = exports.ArrowDown24Regular = exports.ArrowDown20Filled = exports.ArrowDown20Regular = exports.ArrowDown16Filled = exports.ArrowDown16Regular = exports.ArrowDown12Filled = exports.ArrowDown12Regular = exports.ArrowDownRegular = exports.ArrowDownFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ArrowDownFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDownFilled", "", 2, undefined));
exports.ArrowDownRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDownRegular", "", 2, undefined));
exports.ArrowDown12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown12Regular", "", 1, 12));
exports.ArrowDown12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown12Filled", "", 0, 12));
exports.ArrowDown16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown16Regular", "", 1, 16));
exports.ArrowDown16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown16Filled", "", 0, 16));
exports.ArrowDown20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown20Regular", "", 1, 20));
exports.ArrowDown20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown20Filled", "", 0, 20));
exports.ArrowDown24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown24Regular", "", 1, 24));
exports.ArrowDown24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown24Filled", "", 0, 24));
exports.ArrowDown28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown28Regular", "", 1, 28));
exports.ArrowDown28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown28Filled", "", 0, 28));
exports.ArrowDown32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown32Regular", "", 1, 32));
exports.ArrowDown32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown32Filled", "", 0, 32));
exports.ArrowDown32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown32Light", "", 3, 32));
exports.ArrowDown48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown48Regular", "", 1, 48));
exports.ArrowDown48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ArrowDown48Filled", "", 0, 48));
