"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AttachText24Filled = exports.AttachText24Regular = exports.AttachText20Filled = exports.AttachText20Regular = exports.AttachTextRegular = exports.AttachTextFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AttachTextFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AttachTextFilled", "", 2, undefined));
exports.AttachTextRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AttachTextRegular", "", 2, undefined));
exports.AttachText20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AttachText20Regular", "", 1, 20));
exports.AttachText20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AttachText20Filled", "", 0, 20));
exports.AttachText24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AttachText24Regular", "", 1, 24));
exports.AttachText24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AttachText24Filled", "", 0, 24));
