"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Autosum24Filled = exports.Autosum24Regular = exports.Autosum20Filled = exports.Autosum20Regular = exports.Autosum16Filled = exports.Autosum16Regular = exports.AutosumRegular = exports.AutosumFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.AutosumFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AutosumFilled", "", 2, undefined));
exports.AutosumRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("AutosumRegular", "", 2, undefined));
exports.Autosum16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Autosum16Regular", "", 1, 16));
exports.Autosum16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Autosum16Filled", "", 0, 16));
exports.Autosum20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Autosum20Regular", "", 1, 20));
exports.Autosum20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Autosum20Filled", "", 0, 20));
exports.Autosum24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Autosum24Regular", "", 1, 24));
exports.Autosum24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Autosum24Filled", "", 0, 24));
