"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Badge24Filled = exports.Badge24Regular = exports.Badge20Filled = exports.Badge20Regular = exports.BadgeRegular = exports.BadgeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BadgeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BadgeFilled", "", 2, undefined));
exports.BadgeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BadgeRegular", "", 2, undefined));
exports.Badge20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Badge20Regular", "", 1, 20));
exports.Badge20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Badge20Filled", "", 0, 20));
exports.Badge24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Badge24Regular", "", 1, 24));
exports.Badge24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Badge24Filled", "", 0, 24));
