"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Balcony20Filled = exports.Balcony20Regular = exports.Balcony16Filled = exports.Balcony16Regular = exports.BalconyRegular = exports.BalconyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BalconyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BalconyFilled", "", 2, undefined));
exports.BalconyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BalconyRegular", "", 2, undefined));
exports.Balcony16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Balcony16Regular", "󰫰", 1, 16));
exports.Balcony16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Balcony16Filled", "󰭮", 0, 16));
exports.Balcony20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Balcony20Regular", "󰫱", 1, 20));
exports.Balcony20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Balcony20Filled", "󰭯", 0, 20));
