"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BarcodeScanner48Filled = exports.BarcodeScanner48Regular = exports.BarcodeScanner32Filled = exports.BarcodeScanner32Regular = exports.BarcodeScanner28Filled = exports.BarcodeScanner28Regular = exports.BarcodeScanner24Filled = exports.BarcodeScanner24Regular = exports.BarcodeScanner20Filled = exports.BarcodeScanner20Regular = exports.BarcodeScanner16Filled = exports.BarcodeScanner16Regular = exports.BarcodeScannerRegular = exports.BarcodeScannerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BarcodeScannerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScannerFilled", "", 2, undefined));
exports.BarcodeScannerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScannerRegular", "", 2, undefined));
exports.BarcodeScanner16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner16Regular", "󰥜", 1, 16));
exports.BarcodeScanner16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner16Filled", "󰧙", 0, 16));
exports.BarcodeScanner20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner20Regular", "", 1, 20));
exports.BarcodeScanner20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner20Filled", "", 0, 20));
exports.BarcodeScanner24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner24Regular", "", 1, 24));
exports.BarcodeScanner24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner24Filled", "", 0, 24));
exports.BarcodeScanner28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner28Regular", "󰥝", 1, 28));
exports.BarcodeScanner28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner28Filled", "󰧚", 0, 28));
exports.BarcodeScanner32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner32Regular", "󰥞", 1, 32));
exports.BarcodeScanner32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner32Filled", "󰧛", 0, 32));
exports.BarcodeScanner48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner48Regular", "󰥟", 1, 48));
exports.BarcodeScanner48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BarcodeScanner48Filled", "󰧜", 0, 48));
