"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Beach48Filled = exports.Beach48Regular = exports.Beach32Filled = exports.Beach32Regular = exports.Beach28Filled = exports.Beach28Regular = exports.Beach24Filled = exports.Beach24Regular = exports.Beach20Filled = exports.Beach20Regular = exports.Beach16Filled = exports.Beach16Regular = exports.BeachRegular = exports.BeachFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BeachFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeachFilled", "", 2, undefined));
exports.BeachRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeachRegular", "", 2, undefined));
exports.Beach16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach16Regular", "", 1, 16));
exports.Beach16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach16Filled", "", 0, 16));
exports.Beach20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach20Regular", "", 1, 20));
exports.Beach20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach20Filled", "", 0, 20));
exports.Beach24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach24Regular", "", 1, 24));
exports.Beach24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach24Filled", "", 0, 24));
exports.Beach28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach28Regular", "", 1, 28));
exports.Beach28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach28Filled", "", 0, 28));
exports.Beach32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach32Regular", "", 1, 32));
exports.Beach32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach32Filled", "", 0, 32));
exports.Beach48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach48Regular", "", 1, 48));
exports.Beach48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beach48Filled", "", 0, 48));
