"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Beaker32Filled = exports.Beaker32Regular = exports.Beaker24Filled = exports.Beaker24Regular = exports.Beaker20Filled = exports.Beaker20Regular = exports.Beaker16Filled = exports.Beaker16Regular = exports.BeakerRegular = exports.BeakerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BeakerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerFilled", "", 2, undefined));
exports.BeakerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerRegular", "", 2, undefined));
exports.Beaker16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker16Regular", "", 1, 16));
exports.Beaker16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker16Filled", "", 0, 16));
exports.Beaker20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker20Regular", "", 1, 20));
exports.Beaker20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker20Filled", "", 0, 20));
exports.Beaker24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker24Regular", "", 1, 24));
exports.Beaker24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker24Filled", "", 0, 24));
exports.Beaker32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker32Regular", "", 1, 32));
exports.Beaker32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Beaker32Filled", "", 0, 32));
