"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BeakerOff32Filled = exports.BeakerOff32Regular = exports.BeakerOff20Filled = exports.BeakerOff20Regular = exports.BeakerOffRegular = exports.BeakerOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BeakerOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerOffFilled", "", 2, undefined));
exports.BeakerOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerOffRegular", "", 2, undefined));
exports.BeakerOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerOff20Regular", "", 1, 20));
exports.BeakerOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerOff20Filled", "", 0, 20));
exports.BeakerOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerOff32Regular", "", 1, 32));
exports.BeakerOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BeakerOff32Filled", "", 0, 32));
