"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BinFull48Filled = exports.BinFull48Regular = exports.BinFull24Filled = exports.BinFull24Regular = exports.BinFull20Filled = exports.BinFull20Regular = exports.BinFullRegular = exports.BinFullFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BinFullFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFullFilled", "", 2, undefined));
exports.BinFullRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFullRegular", "", 2, undefined));
exports.BinFull20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFull20Regular", "", 1, 20));
exports.BinFull20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFull20Filled", "", 0, 20));
exports.BinFull24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFull24Regular", "", 1, 24));
exports.BinFull24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFull24Filled", "", 0, 24));
exports.BinFull48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFull48Regular", "󰚹", 1, 48));
exports.BinFull48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinFull48Filled", "󰜶", 0, 48));
