"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BinRecycle24Filled = exports.BinRecycle24Regular = exports.BinRecycle20Filled = exports.BinRecycle20Regular = exports.BinRecycleRegular = exports.BinRecycleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BinRecycleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinRecycleFilled", "", 2, undefined));
exports.BinRecycleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinRecycleRegular", "", 2, undefined));
exports.BinRecycle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinRecycle20Regular", "󰇄", 1, 20));
exports.BinRecycle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinRecycle20Filled", "󰇄", 0, 20));
exports.BinRecycle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinRecycle24Regular", "󰇅", 1, 24));
exports.BinRecycle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BinRecycle24Filled", "󰇅", 0, 24));
