"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BoardHeart24Filled = exports.BoardHeart24Regular = exports.BoardHeart20Filled = exports.BoardHeart20Regular = exports.BoardHeart16Filled = exports.BoardHeart16Regular = exports.BoardHeartRegular = exports.BoardHeartFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BoardHeartFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeartFilled", "", 2, undefined));
exports.BoardHeartRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeartRegular", "", 2, undefined));
exports.BoardHeart16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeart16Regular", "", 1, 16));
exports.BoardHeart16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeart16Filled", "", 0, 16));
exports.BoardHeart20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeart20Regular", "", 1, 20));
exports.BoardHeart20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeart20Filled", "", 0, 20));
exports.BoardHeart24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeart24Regular", "", 1, 24));
exports.BoardHeart24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardHeart24Filled", "", 0, 24));
