"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BoardSplit48Filled = exports.BoardSplit48Regular = exports.BoardSplit28Filled = exports.BoardSplit28Regular = exports.BoardSplit24Filled = exports.BoardSplit24Regular = exports.BoardSplit20Filled = exports.BoardSplit20Regular = exports.BoardSplit16Filled = exports.BoardSplit16Regular = exports.BoardSplitRegular = exports.BoardSplitFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BoardSplitFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplitFilled", "", 2, undefined));
exports.BoardSplitRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplitRegular", "", 2, undefined));
exports.BoardSplit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit16Regular", "", 1, 16));
exports.BoardSplit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit16Filled", "", 0, 16));
exports.BoardSplit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit20Regular", "", 1, 20));
exports.BoardSplit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit20Filled", "", 0, 20));
exports.BoardSplit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit24Regular", "", 1, 24));
exports.BoardSplit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit24Filled", "", 0, 24));
exports.BoardSplit28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit28Regular", "", 1, 28));
exports.BoardSplit28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit28Filled", "", 0, 28));
exports.BoardSplit48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit48Regular", "", 1, 48));
exports.BoardSplit48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoardSplit48Filled", "", 0, 48));
