"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookGlobe24Filled = exports.BookGlobe24Regular = exports.BookGlobe20Filled = exports.BookGlobe20Regular = exports.BookGlobeRegular = exports.BookGlobeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookGlobeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookGlobeFilled", "", 2, undefined));
exports.BookGlobeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookGlobeRegular", "", 2, undefined));
exports.BookGlobe20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookGlobe20Regular", "", 1, 20));
exports.BookGlobe20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookGlobe20Filled", "", 0, 20));
exports.BookGlobe24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookGlobe24Regular", "", 1, 24));
exports.BookGlobe24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookGlobe24Filled", "", 0, 24));
