"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookCompass24Filled = exports.BookCompass24Regular = exports.BookCompass20Filled = exports.BookCompass20Regular = exports.BookCompassRegular = exports.BookCompassFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookCompassFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookCompassFilled", "", 2, undefined));
exports.BookCompassRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookCompassRegular", "", 2, undefined));
exports.BookCompass20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookCompass20Regular", "", 1, 20));
exports.BookCompass20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookCompass20Filled", "", 0, 20));
exports.BookCompass24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookCompass24Regular", "", 1, 24));
exports.BookCompass24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookCompass24Filled", "", 0, 24));
