"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookOpen48Filled = exports.BookOpen48Regular = exports.BookOpen32Filled = exports.BookOpen32Regular = exports.BookOpen28Filled = exports.BookOpen28Regular = exports.BookOpen24Filled = exports.BookOpen24Regular = exports.BookOpen20Filled = exports.BookOpen20Regular = exports.BookOpen16Filled = exports.BookOpen16Regular = exports.BookOpenRegular = exports.BookOpenFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookOpenFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpenFilled", "", 2, undefined));
exports.BookOpenRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpenRegular", "", 2, undefined));
exports.BookOpen16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen16Regular", "", 1, 16));
exports.BookOpen16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen16Filled", "", 0, 16));
exports.BookOpen20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen20Regular", "", 1, 20));
exports.BookOpen20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen20Filled", "", 0, 20));
exports.BookOpen24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen24Regular", "", 1, 24));
exports.BookOpen24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen24Filled", "", 0, 24));
exports.BookOpen28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen28Regular", "", 1, 28));
exports.BookOpen28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen28Filled", "", 0, 28));
exports.BookOpen32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen32Regular", "", 1, 32));
exports.BookOpen32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen32Filled", "", 0, 32));
exports.BookOpen48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen48Regular", "", 1, 48));
exports.BookOpen48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookOpen48Filled", "", 0, 48));
