"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookmarkAdd24Filled = exports.BookmarkAdd24Regular = exports.BookmarkAdd20Filled = exports.BookmarkAdd20Regular = exports.BookmarkAddRegular = exports.BookmarkAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookmarkAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkAddFilled", "", 2, undefined));
exports.BookmarkAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkAddRegular", "", 2, undefined));
exports.BookmarkAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkAdd20Regular", "", 1, 20));
exports.BookmarkAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkAdd20Filled", "", 0, 20));
exports.BookmarkAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkAdd24Regular", "", 1, 24));
exports.BookmarkAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkAdd24Filled", "", 0, 24));
