"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookStar24Filled = exports.BookStar24Regular = exports.BookStar20Filled = exports.BookStar20Regular = exports.BookStarRegular = exports.BookStarFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookStarFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookStarFilled", "", 2, undefined));
exports.BookStarRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookStarRegular", "", 2, undefined));
exports.BookStar20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookStar20Regular", "", 1, 20));
exports.BookStar20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookStar20Filled", "", 0, 20));
exports.BookStar24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookStar24Regular", "", 1, 24));
exports.BookStar24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookStar24Filled", "", 0, 24));
