"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookmarkOff24Filled = exports.BookmarkOff24Regular = exports.BookmarkOff20Filled = exports.BookmarkOff20Regular = exports.BookmarkOffRegular = exports.BookmarkOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookmarkOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkOffFilled", "", 2, undefined));
exports.BookmarkOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkOffRegular", "", 2, undefined));
exports.BookmarkOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkOff20Regular", "", 1, 20));
exports.BookmarkOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkOff20Filled", "", 0, 20));
exports.BookmarkOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkOff24Regular", "", 1, 24));
exports.BookmarkOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookmarkOff24Filled", "", 0, 24));
