"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookDismiss20Filled = exports.BookDismiss20Regular = exports.BookDismiss16Filled = exports.BookDismiss16Regular = exports.BookDismissRegular = exports.BookDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BookDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookDismissFilled", "", 2, undefined));
exports.BookDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookDismissRegular", "", 2, undefined));
exports.BookDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookDismiss16Regular", "󰅥", 1, 16));
exports.BookDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookDismiss16Filled", "󰅥", 0, 16));
exports.BookDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookDismiss20Regular", "󰅦", 1, 20));
exports.BookDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BookDismiss20Filled", "󰅦", 0, 20));
