"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BorderInside24Filled = exports.BorderInside24Regular = exports.BorderInside20Filled = exports.BorderInside20Regular = exports.BorderInside16Filled = exports.BorderInside16Regular = exports.BorderInsideRegular = exports.BorderInsideFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BorderInsideFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInsideFilled", "", 2, undefined));
exports.BorderInsideRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInsideRegular", "", 2, undefined));
exports.BorderInside16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInside16Regular", "󰎮", 1, 16));
exports.BorderInside16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInside16Filled", "󰏁", 0, 16));
exports.BorderInside20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInside20Regular", "󰎯", 1, 20));
exports.BorderInside20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInside20Filled", "󰏂", 0, 20));
exports.BorderInside24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInside24Regular", "󰎰", 1, 24));
exports.BorderInside24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderInside24Filled", "󰏃", 0, 24));
