"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BorderRight24Filled = exports.BorderRight24Regular = exports.BorderRight20Filled = exports.BorderRight20Regular = exports.BorderRightRegular = exports.BorderRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BorderRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderRightFilled", "", 2, undefined));
exports.BorderRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderRightRegular", "", 2, undefined));
exports.BorderRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderRight20Regular", "", 1, 20));
exports.BorderRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderRight20Filled", "", 0, 20));
exports.BorderRight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderRight24Regular", "", 1, 24));
exports.BorderRight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderRight24Filled", "", 0, 24));
