"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BorderTop24Filled = exports.BorderTop24Regular = exports.BorderTop20Filled = exports.BorderTop20Regular = exports.BorderTopRegular = exports.BorderTopFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BorderTopFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderTopFilled", "", 2, undefined));
exports.BorderTopRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderTopRegular", "", 2, undefined));
exports.BorderTop20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderTop20Regular", "", 1, 20));
exports.BorderTop20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderTop20Filled", "", 0, 20));
exports.BorderTop24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderTop24Regular", "", 1, 24));
exports.BorderTop24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderTop24Filled", "", 0, 24));
