"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BorderOutside24Filled = exports.BorderOutside24Regular = exports.BorderOutside20Filled = exports.BorderOutside20Regular = exports.BorderOutsideRegular = exports.BorderOutsideFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BorderOutsideFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderOutsideFilled", "", 2, undefined));
exports.BorderOutsideRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderOutsideRegular", "", 2, undefined));
exports.BorderOutside20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderOutside20Regular", "", 1, 20));
exports.BorderOutside20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderOutside20Filled", "", 0, 20));
exports.BorderOutside24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderOutside24Regular", "", 1, 24));
exports.BorderOutside24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderOutside24Filled", "", 0, 24));
