"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BorderBottom24Filled = exports.BorderBottom24Regular = exports.BorderBottom20Filled = exports.BorderBottom20Regular = exports.BorderBottomRegular = exports.BorderBottomFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BorderBottomFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderBottomFilled", "", 2, undefined));
exports.BorderBottomRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderBottomRegular", "", 2, undefined));
exports.BorderBottom20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderBottom20Regular", "", 1, 20));
exports.BorderBottom20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderBottom20Filled", "", 0, 20));
exports.BorderBottom24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderBottom24Regular", "", 1, 24));
exports.BorderBottom24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BorderBottom24Filled", "", 0, 24));
