"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Bot48Filled = exports.Bot48Regular = exports.Bot32Filled = exports.Bot32Regular = exports.Bot28Filled = exports.Bot28Regular = exports.Bot24Filled = exports.Bot24Regular = exports.Bot20Filled = exports.Bot20Regular = exports.Bot16Filled = exports.Bot16Regular = exports.Bot12Filled = exports.Bot12Regular = exports.BotRegular = exports.BotFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BotFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BotFilled", "", 2, undefined));
exports.BotRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BotRegular", "", 2, undefined));
exports.Bot12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot12Regular", "󰨗", 1, 12));
exports.Bot12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot12Filled", "󰪓", 0, 12));
exports.Bot16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot16Regular", "󰞽", 1, 16));
exports.Bot16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot16Filled", "󰠺", 0, 16));
exports.Bot20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot20Regular", "", 1, 20));
exports.Bot20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot20Filled", "", 0, 20));
exports.Bot24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot24Regular", "", 1, 24));
exports.Bot24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot24Filled", "", 0, 24));
exports.Bot28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot28Regular", "󰞾", 1, 28));
exports.Bot28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot28Filled", "󰠻", 0, 28));
exports.Bot32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot32Regular", "󰞿", 1, 32));
exports.Bot32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot32Filled", "󰠼", 0, 32));
exports.Bot48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot48Regular", "󰟀", 1, 48));
exports.Bot48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Bot48Filled", "󰠽", 0, 48));
