"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BowTie24Filled = exports.BowTie24Regular = exports.BowTie20Filled = exports.BowTie20Regular = exports.BowTieRegular = exports.BowTieFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BowTieFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BowTieFilled", "", 2, undefined));
exports.BowTieRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BowTieRegular", "", 2, undefined));
exports.BowTie20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BowTie20Regular", "󰃔", 1, 20));
exports.BowTie20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BowTie20Filled", "󰃓", 0, 20));
exports.BowTie24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BowTie24Regular", "󰃕", 1, 24));
exports.BowTie24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BowTie24Filled", "󰃔", 0, 24));
