"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BoxToolbox24Filled = exports.BoxToolbox24Regular = exports.BoxToolbox20Filled = exports.BoxToolbox20Regular = exports.BoxToolboxRegular = exports.BoxToolboxFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BoxToolboxFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxToolboxFilled", "", 2, undefined));
exports.BoxToolboxRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxToolboxRegular", "", 2, undefined));
exports.BoxToolbox20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxToolbox20Regular", "", 1, 20));
exports.BoxToolbox20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxToolbox20Filled", "", 0, 20));
exports.BoxToolbox24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxToolbox24Regular", "", 1, 24));
exports.BoxToolbox24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxToolbox24Filled", "", 0, 24));
