"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BoxDismiss24Filled = exports.BoxDismiss24Regular = exports.BoxDismiss20Filled = exports.BoxDismiss20Regular = exports.BoxDismissRegular = exports.BoxDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BoxDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxDismissFilled", "", 2, undefined));
exports.BoxDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxDismissRegular", "", 2, undefined));
exports.BoxDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxDismiss20Regular", "", 1, 20));
exports.BoxDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxDismiss20Filled", "", 0, 20));
exports.BoxDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxDismiss24Regular", "", 1, 24));
exports.BoxDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BoxDismiss24Filled", "", 0, 24));
