"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Braces48Filled = exports.Braces48Regular = exports.Braces32Filled = exports.Braces32Regular = exports.Braces28Filled = exports.Braces28Regular = exports.Braces24Filled = exports.Braces24Regular = exports.Braces20Filled = exports.Braces20Regular = exports.Braces16Filled = exports.Braces16Regular = exports.BracesRegular = exports.BracesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BracesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BracesFilled", "", 2, undefined));
exports.BracesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BracesRegular", "", 2, undefined));
exports.Braces16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces16Regular", "", 1, 16));
exports.Braces16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces16Filled", "", 0, 16));
exports.Braces20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces20Regular", "", 1, 20));
exports.Braces20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces20Filled", "", 0, 20));
exports.Braces24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces24Regular", "", 1, 24));
exports.Braces24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces24Filled", "", 0, 24));
exports.Braces28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces28Regular", "", 1, 28));
exports.Braces28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces28Filled", "", 0, 28));
exports.Braces32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces32Regular", "", 1, 32));
exports.Braces32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces32Filled", "", 0, 32));
exports.Braces48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces48Regular", "", 1, 48));
exports.Braces48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Braces48Filled", "", 0, 48));
