"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrainCircuit48Filled = exports.BrainCircuit48Regular = exports.BrainCircuit32Filled = exports.BrainCircuit32Regular = exports.BrainCircuit28Filled = exports.BrainCircuit28Regular = exports.BrainCircuit24Filled = exports.BrainCircuit24Regular = exports.BrainCircuit20Filled = exports.BrainCircuit20Regular = exports.BrainCircuitRegular = exports.BrainCircuitFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BrainCircuitFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuitFilled", "", 2, undefined));
exports.BrainCircuitRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuitRegular", "", 2, undefined));
exports.BrainCircuit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit20Regular", "", 1, 20));
exports.BrainCircuit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit20Filled", "", 0, 20));
exports.BrainCircuit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit24Regular", "", 1, 24));
exports.BrainCircuit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit24Filled", "", 0, 24));
exports.BrainCircuit28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit28Regular", "󰦲", 1, 28));
exports.BrainCircuit28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit28Filled", "󰨯", 0, 28));
exports.BrainCircuit32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit32Regular", "󰦳", 1, 32));
exports.BrainCircuit32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit32Filled", "󰨰", 0, 32));
exports.BrainCircuit48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit48Regular", "󰦴", 1, 48));
exports.BrainCircuit48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BrainCircuit48Filled", "󰨱", 0, 48));
