"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BranchFork32Filled = exports.BranchFork32Regular = exports.BranchFork24Filled = exports.BranchFork24Regular = exports.BranchFork20Filled = exports.BranchFork20Regular = exports.BranchFork16Filled = exports.BranchFork16Regular = exports.BranchForkRegular = exports.BranchForkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BranchForkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchForkFilled", "", 2, undefined));
exports.BranchForkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchForkRegular", "", 2, undefined));
exports.BranchFork16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork16Regular", "", 1, 16));
exports.BranchFork16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork16Filled", "", 0, 16));
exports.BranchFork20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork20Regular", "", 1, 20));
exports.BranchFork20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork20Filled", "", 0, 20));
exports.BranchFork24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork24Regular", "", 1, 24));
exports.BranchFork24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork24Filled", "", 0, 24));
exports.BranchFork32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork32Regular", "", 1, 32));
exports.BranchFork32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFork32Filled", "", 0, 32));
