"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Branch24Filled = exports.Branch24Regular = exports.Branch20Filled = exports.Branch20Regular = exports.Branch16Filled = exports.Branch16Regular = exports.BranchRegular = exports.BranchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BranchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchFilled", "", 2, undefined));
exports.BranchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BranchRegular", "", 2, undefined));
exports.Branch16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Branch16Regular", "", 1, 16));
exports.Branch16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Branch16Filled", "", 0, 16));
exports.Branch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Branch20Regular", "", 1, 20));
exports.Branch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Branch20Filled", "", 0, 20));
exports.Branch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Branch24Regular", "", 1, 24));
exports.Branch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Branch24Filled", "", 0, 24));
