"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BreakoutRoom32Light = exports.BreakoutRoom32Filled = exports.BreakoutRoom32Regular = exports.BreakoutRoom28Filled = exports.BreakoutRoom28Regular = exports.BreakoutRoom24Filled = exports.BreakoutRoom24Regular = exports.BreakoutRoom20Filled = exports.BreakoutRoom20Regular = exports.BreakoutRoom16Filled = exports.BreakoutRoom16Regular = exports.BreakoutRoomRegular = exports.BreakoutRoomFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BreakoutRoomFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoomFilled", "", 2, undefined));
exports.BreakoutRoomRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoomRegular", "", 2, undefined));
exports.BreakoutRoom16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom16Regular", "󰦵", 1, 16));
exports.BreakoutRoom16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom16Filled", "󰨲", 0, 16));
exports.BreakoutRoom20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom20Regular", "", 1, 20));
exports.BreakoutRoom20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom20Filled", "", 0, 20));
exports.BreakoutRoom24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom24Regular", "", 1, 24));
exports.BreakoutRoom24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom24Filled", "", 0, 24));
exports.BreakoutRoom28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom28Regular", "", 1, 28));
exports.BreakoutRoom28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom28Filled", "", 0, 28));
exports.BreakoutRoom32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom32Regular", "󰗸", 1, 32));
exports.BreakoutRoom32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom32Filled", "󰙴", 0, 32));
exports.BreakoutRoom32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BreakoutRoom32Light", "", 3, 32));
