"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BriefcaseOff48Filled = exports.BriefcaseOff48Regular = exports.BriefcaseOff32Filled = exports.BriefcaseOff32Regular = exports.BriefcaseOff28Filled = exports.BriefcaseOff28Regular = exports.BriefcaseOff24Filled = exports.BriefcaseOff24Regular = exports.BriefcaseOff20Filled = exports.BriefcaseOff20Regular = exports.BriefcaseOff16Filled = exports.BriefcaseOff16Regular = exports.BriefcaseOffRegular = exports.BriefcaseOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BriefcaseOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOffFilled", "", 2, undefined));
exports.BriefcaseOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOffRegular", "", 2, undefined));
exports.BriefcaseOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff16Regular", "", 1, 16));
exports.BriefcaseOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff16Filled", "", 0, 16));
exports.BriefcaseOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff20Regular", "", 1, 20));
exports.BriefcaseOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff20Filled", "", 0, 20));
exports.BriefcaseOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff24Regular", "", 1, 24));
exports.BriefcaseOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff24Filled", "", 0, 24));
exports.BriefcaseOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff28Regular", "", 1, 28));
exports.BriefcaseOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff28Filled", "", 0, 28));
exports.BriefcaseOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff32Regular", "", 1, 32));
exports.BriefcaseOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff32Filled", "", 0, 32));
exports.BriefcaseOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff48Regular", "", 1, 48));
exports.BriefcaseOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseOff48Filled", "", 0, 48));
