"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BriefcaseMedical32Filled = exports.BriefcaseMedical32Regular = exports.BriefcaseMedical24Filled = exports.BriefcaseMedical24Regular = exports.BriefcaseMedical20Filled = exports.BriefcaseMedical20Regular = exports.BriefcaseMedical16Filled = exports.BriefcaseMedical16Regular = exports.BriefcaseMedicalRegular = exports.BriefcaseMedicalFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BriefcaseMedicalFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedicalFilled", "", 2, undefined));
exports.BriefcaseMedicalRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedicalRegular", "", 2, undefined));
exports.BriefcaseMedical16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical16Regular", "", 1, 16));
exports.BriefcaseMedical16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical16Filled", "", 0, 16));
exports.BriefcaseMedical20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical20Regular", "", 1, 20));
exports.BriefcaseMedical20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical20Filled", "", 0, 20));
exports.BriefcaseMedical24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical24Regular", "", 1, 24));
exports.BriefcaseMedical24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical24Filled", "", 0, 24));
exports.BriefcaseMedical32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical32Regular", "", 1, 32));
exports.BriefcaseMedical32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BriefcaseMedical32Filled", "", 0, 32));
