"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BuildingRetail24Filled = exports.BuildingRetail24Regular = exports.BuildingRetail20Filled = exports.BuildingRetail20Regular = exports.BuildingRetailRegular = exports.BuildingRetailFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BuildingRetailFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingRetailFilled", "", 2, undefined));
exports.BuildingRetailRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingRetailRegular", "", 2, undefined));
exports.BuildingRetail20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingRetail20Regular", "", 1, 20));
exports.BuildingRetail20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingRetail20Filled", "", 0, 20));
exports.BuildingRetail24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingRetail24Regular", "", 1, 24));
exports.BuildingRetail24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingRetail24Filled", "", 0, 24));
