"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BuildingBank48Filled = exports.BuildingBank48Regular = exports.BuildingBank28Filled = exports.BuildingBank28Regular = exports.BuildingBank24Filled = exports.BuildingBank24Regular = exports.BuildingBank20Filled = exports.BuildingBank20Regular = exports.BuildingBank16Filled = exports.BuildingBank16Regular = exports.BuildingBankRegular = exports.BuildingBankFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BuildingBankFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBankFilled", "", 2, undefined));
exports.BuildingBankRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBankRegular", "", 2, undefined));
exports.BuildingBank16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank16Regular", "", 1, 16));
exports.BuildingBank16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank16Filled", "", 0, 16));
exports.BuildingBank20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank20Regular", "", 1, 20));
exports.BuildingBank20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank20Filled", "", 0, 20));
exports.BuildingBank24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank24Regular", "", 1, 24));
exports.BuildingBank24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank24Filled", "", 0, 24));
exports.BuildingBank28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank28Regular", "", 1, 28));
exports.BuildingBank28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank28Filled", "", 0, 28));
exports.BuildingBank48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank48Regular", "", 1, 48));
exports.BuildingBank48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingBank48Filled", "", 0, 48));
