"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BuildingDesktop32Filled = exports.BuildingDesktop32Regular = exports.BuildingDesktop24Filled = exports.BuildingDesktop24Regular = exports.BuildingDesktop20Filled = exports.BuildingDesktop20Regular = exports.BuildingDesktop16Filled = exports.BuildingDesktop16Regular = exports.BuildingDesktopRegular = exports.BuildingDesktopFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.BuildingDesktopFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktopFilled", "", 2, undefined));
exports.BuildingDesktopRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktopRegular", "", 2, undefined));
exports.BuildingDesktop16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop16Regular", "", 1, 16));
exports.BuildingDesktop16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop16Filled", "", 0, 16));
exports.BuildingDesktop20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop20Regular", "", 1, 20));
exports.BuildingDesktop20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop20Filled", "", 0, 20));
exports.BuildingDesktop24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop24Regular", "", 1, 24));
exports.BuildingDesktop24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop24Filled", "", 0, 24));
exports.BuildingDesktop32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop32Regular", "󰏙", 1, 32));
exports.BuildingDesktop32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("BuildingDesktop32Filled", "󰏬", 0, 32));
