"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Button20Filled = exports.Button20Regular = exports.Button16Filled = exports.Button16Regular = exports.ButtonRegular = exports.ButtonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ButtonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ButtonFilled", "", 2, undefined));
exports.ButtonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ButtonRegular", "", 2, undefined));
exports.Button16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Button16Regular", "󰅧", 1, 16));
exports.Button16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Button16Filled", "󰅧", 0, 16));
exports.Button20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Button20Regular", "󰅨", 1, 20));
exports.Button20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Button20Filled", "󰅨", 0, 20));
