"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarVideo28Filled = exports.CalendarVideo28Regular = exports.CalendarVideo24Filled = exports.CalendarVideo24Regular = exports.CalendarVideo20Filled = exports.CalendarVideo20Regular = exports.CalendarVideoRegular = exports.CalendarVideoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarVideoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideoFilled", "", 2, undefined, { flipInRtl: true }));
exports.CalendarVideoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideoRegular", "", 2, undefined, { flipInRtl: true }));
exports.CalendarVideo20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideo20Regular", "󰕟", 1, 20, { flipInRtl: true }));
exports.CalendarVideo20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideo20Filled", "󰗘", 0, 20, { flipInRtl: true }));
exports.CalendarVideo24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideo24Regular", "󰓫", 1, 24, { flipInRtl: true }));
exports.CalendarVideo24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideo24Filled", "󰕤", 0, 24, { flipInRtl: true }));
exports.CalendarVideo28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideo28Regular", "󰓬", 1, 28, { flipInRtl: true }));
exports.CalendarVideo28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarVideo28Filled", "󰕥", 0, 28, { flipInRtl: true }));
