"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarAgenda28Filled = exports.CalendarAgenda28Regular = exports.CalendarAgenda24Filled = exports.CalendarAgenda24Regular = exports.CalendarAgenda20Filled = exports.CalendarAgenda20Regular = exports.CalendarAgendaRegular = exports.CalendarAgendaFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarAgendaFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgendaFilled", "", 2, undefined));
exports.CalendarAgendaRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgendaRegular", "", 2, undefined));
exports.CalendarAgenda20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgenda20Regular", "", 1, 20));
exports.CalendarAgenda20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgenda20Filled", "", 0, 20));
exports.CalendarAgenda24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgenda24Regular", "", 1, 24));
exports.CalendarAgenda24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgenda24Filled", "", 0, 24));
exports.CalendarAgenda28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgenda28Regular", "", 1, 28));
exports.CalendarAgenda28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarAgenda28Filled", "", 0, 28));
