"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarRtl48Filled = exports.CalendarRtl48Regular = exports.CalendarRtl32Filled = exports.CalendarRtl32Regular = exports.CalendarRtl28Filled = exports.CalendarRtl28Regular = exports.CalendarRtl24Filled = exports.CalendarRtl24Regular = exports.CalendarRtl20Filled = exports.CalendarRtl20Regular = exports.CalendarRtl16Filled = exports.CalendarRtl16Regular = exports.CalendarRtl12Filled = exports.CalendarRtl12Regular = exports.CalendarRtlRegular = exports.CalendarRtlFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarRtlFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtlFilled", "", 2, undefined));
exports.CalendarRtlRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtlRegular", "", 2, undefined));
exports.CalendarRtl12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl12Regular", "", 1, 12));
exports.CalendarRtl12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl12Filled", "", 0, 12));
exports.CalendarRtl16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl16Regular", "", 1, 16));
exports.CalendarRtl16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl16Filled", "", 0, 16));
exports.CalendarRtl20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl20Regular", "", 1, 20));
exports.CalendarRtl20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl20Filled", "", 0, 20));
exports.CalendarRtl24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl24Regular", "", 1, 24));
exports.CalendarRtl24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl24Filled", "", 0, 24));
exports.CalendarRtl28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl28Regular", "", 1, 28));
exports.CalendarRtl28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl28Filled", "", 0, 28));
exports.CalendarRtl32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl32Regular", "", 1, 32));
exports.CalendarRtl32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl32Filled", "", 0, 32));
exports.CalendarRtl48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl48Regular", "", 1, 48));
exports.CalendarRtl48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarRtl48Filled", "", 0, 48));
