"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarError24Filled = exports.CalendarError24Regular = exports.CalendarError20Filled = exports.CalendarError20Regular = exports.CalendarError16Filled = exports.CalendarError16Regular = exports.CalendarErrorRegular = exports.CalendarErrorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarErrorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarErrorFilled", "", 2, undefined));
exports.CalendarErrorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarErrorRegular", "", 2, undefined));
exports.CalendarError16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarError16Regular", "", 1, 16));
exports.CalendarError16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarError16Filled", "", 0, 16));
exports.CalendarError20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarError20Regular", "", 1, 20));
exports.CalendarError20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarError20Filled", "", 0, 20));
exports.CalendarError24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarError24Regular", "", 1, 24));
exports.CalendarError24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarError24Filled", "", 0, 24));
