"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarReply32Light = exports.CalendarReply28Filled = exports.CalendarReply28Regular = exports.CalendarReply24Filled = exports.CalendarReply24Regular = exports.CalendarReply20Filled = exports.CalendarReply20Regular = exports.CalendarReply16Filled = exports.CalendarReply16Regular = exports.CalendarReplyRegular = exports.CalendarReplyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarReplyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReplyFilled", "", 2, undefined));
exports.CalendarReplyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReplyRegular", "", 2, undefined));
exports.CalendarReply16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply16Regular", "", 1, 16));
exports.CalendarReply16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply16Filled", "", 0, 16));
exports.CalendarReply20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply20Regular", "", 1, 20));
exports.CalendarReply20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply20Filled", "", 0, 20));
exports.CalendarReply24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply24Regular", "", 1, 24));
exports.CalendarReply24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply24Filled", "", 0, 24));
exports.CalendarReply28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply28Regular", "", 1, 28));
exports.CalendarReply28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply28Filled", "", 0, 28));
exports.CalendarReply32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarReply32Light", "", 3, 32));
