"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarDay32Light = exports.CalendarDay32Filled = exports.CalendarDay32Regular = exports.CalendarDay28Filled = exports.CalendarDay28Regular = exports.CalendarDay24Filled = exports.CalendarDay24Regular = exports.CalendarDay20Filled = exports.CalendarDay20Regular = exports.CalendarDay16Filled = exports.CalendarDay16Regular = exports.CalendarDayRegular = exports.CalendarDayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarDayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDayFilled", "", 2, undefined));
exports.CalendarDayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDayRegular", "", 2, undefined));
exports.CalendarDay16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay16Regular", "", 1, 16));
exports.CalendarDay16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay16Filled", "", 0, 16));
exports.CalendarDay20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay20Regular", "", 1, 20));
exports.CalendarDay20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay20Filled", "", 0, 20));
exports.CalendarDay24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay24Regular", "", 1, 24));
exports.CalendarDay24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay24Filled", "", 0, 24));
exports.CalendarDay28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay28Regular", "", 1, 28));
exports.CalendarDay28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay28Filled", "", 0, 28));
exports.CalendarDay32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay32Regular", "󰧕", 1, 32));
exports.CalendarDay32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay32Filled", "󰩒", 0, 32));
exports.CalendarDay32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarDay32Light", "", 3, 32));
