"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarPattern32Light = exports.CalendarPattern20Filled = exports.CalendarPattern20Regular = exports.CalendarPattern16Filled = exports.CalendarPattern16Regular = exports.CalendarPatternRegular = exports.CalendarPatternFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarPatternFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPatternFilled", "", 2, undefined));
exports.CalendarPatternRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPatternRegular", "", 2, undefined));
exports.CalendarPattern16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPattern16Regular", "", 1, 16));
exports.CalendarPattern16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPattern16Filled", "", 0, 16));
exports.CalendarPattern20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPattern20Regular", "", 1, 20));
exports.CalendarPattern20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPattern20Filled", "", 0, 20));
exports.CalendarPattern32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarPattern32Light", "", 3, 32));
