"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarEdit32Light = exports.CalendarEdit32Filled = exports.CalendarEdit32Regular = exports.CalendarEdit24Filled = exports.CalendarEdit24Regular = exports.CalendarEdit20Filled = exports.CalendarEdit20Regular = exports.CalendarEdit16Filled = exports.CalendarEdit16Regular = exports.CalendarEditRegular = exports.CalendarEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEditFilled", "", 2, undefined));
exports.CalendarEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEditRegular", "", 2, undefined));
exports.CalendarEdit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit16Regular", "", 1, 16));
exports.CalendarEdit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit16Filled", "", 0, 16));
exports.CalendarEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit20Regular", "", 1, 20));
exports.CalendarEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit20Filled", "", 0, 20));
exports.CalendarEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit24Regular", "", 1, 24));
exports.CalendarEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit24Filled", "", 0, 24));
exports.CalendarEdit32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit32Regular", "󰖡", 1, 32));
exports.CalendarEdit32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit32Filled", "󰘚", 0, 32));
exports.CalendarEdit32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarEdit32Light", "", 3, 32));
