"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarShield48Filled = exports.CalendarShield48Regular = exports.CalendarShield32Filled = exports.CalendarShield32Regular = exports.CalendarShield28Filled = exports.CalendarShield28Regular = exports.CalendarShield24Filled = exports.CalendarShield24Regular = exports.CalendarShield20Filled = exports.CalendarShield20Regular = exports.CalendarShield16Filled = exports.CalendarShield16Regular = exports.CalendarShieldRegular = exports.CalendarShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShieldFilled", "", 2, undefined));
exports.CalendarShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShieldRegular", "", 2, undefined));
exports.CalendarShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield16Regular", "", 1, 16));
exports.CalendarShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield16Filled", "", 0, 16));
exports.CalendarShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield20Regular", "", 1, 20));
exports.CalendarShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield20Filled", "", 0, 20));
exports.CalendarShield24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield24Regular", "", 1, 24));
exports.CalendarShield24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield24Filled", "", 0, 24));
exports.CalendarShield28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield28Regular", "", 1, 28));
exports.CalendarShield28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield28Filled", "", 0, 28));
exports.CalendarShield32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield32Regular", "", 1, 32));
exports.CalendarShield32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield32Filled", "", 0, 32));
exports.CalendarShield48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield48Regular", "", 1, 48));
exports.CalendarShield48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarShield48Filled", "", 0, 48));
