"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarMail20Filled = exports.CalendarMail20Regular = exports.CalendarMail16Filled = exports.CalendarMail16Regular = exports.CalendarMailRegular = exports.CalendarMailFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarMailFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarMailFilled", "", 2, undefined));
exports.CalendarMailRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarMailRegular", "", 2, undefined));
exports.CalendarMail16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarMail16Regular", "", 1, 16));
exports.CalendarMail16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarMail16Filled", "", 0, 16));
exports.CalendarMail20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarMail20Regular", "", 1, 20));
exports.CalendarMail20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarMail20Filled", "", 0, 20));
