"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarSync24Filled = exports.CalendarSync24Regular = exports.CalendarSync20Filled = exports.CalendarSync20Regular = exports.CalendarSync16Filled = exports.CalendarSync16Regular = exports.CalendarSyncRegular = exports.CalendarSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSyncFilled", "", 2, undefined));
exports.CalendarSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSyncRegular", "", 2, undefined));
exports.CalendarSync16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSync16Regular", "", 1, 16));
exports.CalendarSync16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSync16Filled", "", 0, 16));
exports.CalendarSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSync20Regular", "", 1, 20));
exports.CalendarSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSync20Filled", "", 0, 20));
exports.CalendarSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSync24Regular", "", 1, 24));
exports.CalendarSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarSync24Filled", "", 0, 24));
