"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarStar24Filled = exports.CalendarStar24Regular = exports.CalendarStar20Filled = exports.CalendarStar20Regular = exports.CalendarStar16Filled = exports.CalendarStar16Regular = exports.CalendarStarRegular = exports.CalendarStarFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CalendarStarFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStarFilled", "", 2, undefined));
exports.CalendarStarRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStarRegular", "", 2, undefined));
exports.CalendarStar16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStar16Regular", "", 1, 16));
exports.CalendarStar16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStar16Filled", "", 0, 16));
exports.CalendarStar20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStar20Regular", "", 1, 20));
exports.CalendarStar20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStar20Filled", "", 0, 20));
exports.CalendarStar24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStar24Regular", "", 1, 24));
exports.CalendarStar24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CalendarStar24Filled", "", 0, 24));
