"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Calendar3Day32Light = exports.Calendar3Day32Filled = exports.Calendar3Day32Regular = exports.Calendar3Day28Filled = exports.Calendar3Day28Regular = exports.Calendar3Day24Filled = exports.Calendar3Day24Regular = exports.Calendar3Day20Filled = exports.Calendar3Day20Regular = exports.Calendar3Day16Filled = exports.Calendar3Day16Regular = exports.Calendar3DayRegular = exports.Calendar3DayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.Calendar3DayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3DayFilled", "", 2, undefined));
exports.Calendar3DayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3DayRegular", "", 2, undefined));
exports.Calendar3Day16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day16Regular", "", 1, 16));
exports.Calendar3Day16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day16Filled", "", 0, 16));
exports.Calendar3Day20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day20Regular", "", 1, 20));
exports.Calendar3Day20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day20Filled", "", 0, 20));
exports.Calendar3Day24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day24Regular", "", 1, 24));
exports.Calendar3Day24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day24Filled", "", 0, 24));
exports.Calendar3Day28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day28Regular", "", 1, 28));
exports.Calendar3Day28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day28Filled", "", 0, 28));
exports.Calendar3Day32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day32Regular", "󰩬", 1, 32));
exports.Calendar3Day32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day32Filled", "󰫨", 0, 32));
exports.Calendar3Day32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Calendar3Day32Light", "", 3, 32));
