"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CallWarning20Filled = exports.CallWarning20Regular = exports.CallWarning16Filled = exports.CallWarning16Regular = exports.CallWarningRegular = exports.CallWarningFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CallWarningFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CallWarningFilled", "", 2, undefined));
exports.CallWarningRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CallWarningRegular", "", 2, undefined));
exports.CallWarning16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CallWarning16Regular", "", 1, 16));
exports.CallWarning16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CallWarning16Filled", "", 0, 16));
exports.CallWarning20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CallWarning20Regular", "", 1, 20));
exports.CallWarning20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CallWarning20Filled", "", 0, 20));
