"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CameraDome48Filled = exports.CameraDome48Regular = exports.CameraDome28Filled = exports.CameraDome28Regular = exports.CameraDome24Filled = exports.CameraDome24Regular = exports.CameraDome20Filled = exports.CameraDome20Regular = exports.CameraDome16Filled = exports.CameraDome16Regular = exports.CameraDomeRegular = exports.CameraDomeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CameraDomeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDomeFilled", "", 2, undefined));
exports.CameraDomeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDomeRegular", "", 2, undefined));
exports.CameraDome16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome16Regular", "", 1, 16));
exports.CameraDome16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome16Filled", "", 0, 16));
exports.CameraDome20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome20Regular", "", 1, 20));
exports.CameraDome20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome20Filled", "", 0, 20));
exports.CameraDome24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome24Regular", "", 1, 24));
exports.CameraDome24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome24Filled", "", 0, 24));
exports.CameraDome28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome28Regular", "", 1, 28));
exports.CameraDome28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome28Filled", "", 0, 28));
exports.CameraDome48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome48Regular", "", 1, 48));
exports.CameraDome48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraDome48Filled", "", 0, 48));
