"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CameraSwitch24Filled = exports.CameraSwitch24Regular = exports.CameraSwitch20Filled = exports.CameraSwitch20Regular = exports.CameraSwitchRegular = exports.CameraSwitchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CameraSwitchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraSwitchFilled", "", 2, undefined));
exports.CameraSwitchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraSwitchRegular", "", 2, undefined));
exports.CameraSwitch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraSwitch20Regular", "", 1, 20));
exports.CameraSwitch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraSwitch20Filled", "", 0, 20));
exports.CameraSwitch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraSwitch24Regular", "", 1, 24));
exports.CameraSwitch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraSwitch24Filled", "", 0, 24));
