"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CameraOff24Filled = exports.CameraOff24Regular = exports.CameraOff20Filled = exports.CameraOff20Regular = exports.CameraOff16Filled = exports.CameraOff16Regular = exports.CameraOffRegular = exports.CameraOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CameraOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOffFilled", "", 2, undefined));
exports.CameraOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOffRegular", "", 2, undefined));
exports.CameraOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOff16Regular", "", 1, 16));
exports.CameraOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOff16Filled", "", 0, 16));
exports.CameraOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOff20Regular", "", 1, 20));
exports.CameraOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOff20Filled", "", 0, 20));
exports.CameraOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOff24Regular", "", 1, 24));
exports.CameraOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CameraOff24Filled", "", 0, 24));
