"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CaretRight24Filled = exports.CaretRight24Regular = exports.CaretRight20Filled = exports.CaretRight20Regular = exports.CaretRight16Filled = exports.CaretRight16Regular = exports.CaretRight12Filled = exports.CaretRight12Regular = exports.CaretRightRegular = exports.CaretRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CaretRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRightFilled", "", 2, undefined));
exports.CaretRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRightRegular", "", 2, undefined));
exports.CaretRight12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight12Regular", "", 1, 12));
exports.CaretRight12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight12Filled", "", 0, 12));
exports.CaretRight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight16Regular", "", 1, 16));
exports.CaretRight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight16Filled", "", 0, 16));
exports.CaretRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight20Regular", "", 1, 20));
exports.CaretRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight20Filled", "", 0, 20));
exports.CaretRight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight24Regular", "", 1, 24));
exports.CaretRight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CaretRight24Filled", "", 0, 24));
