"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CellularWarning24Filled = exports.CellularWarning24Regular = exports.CellularWarning20Filled = exports.CellularWarning20Regular = exports.CellularWarningRegular = exports.CellularWarningFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CellularWarningFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularWarningFilled", "", 2, undefined));
exports.CellularWarningRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularWarningRegular", "", 2, undefined));
exports.CellularWarning20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularWarning20Regular", "", 1, 20));
exports.CellularWarning20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularWarning20Filled", "", 0, 20));
exports.CellularWarning24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularWarning24Regular", "", 1, 24));
exports.CellularWarning24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularWarning24Filled", "", 0, 24));
