"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CellularData524Filled = exports.CellularData524Regular = exports.CellularData520Filled = exports.CellularData520Regular = exports.CellularData424Filled = exports.CellularData424Regular = exports.CellularData420Filled = exports.CellularData420Regular = exports.CellularData324Filled = exports.CellularData324Regular = exports.CellularData320Filled = exports.CellularData320Regular = exports.CellularData224Filled = exports.CellularData224Regular = exports.CellularData220Filled = exports.CellularData220Regular = exports.CellularData124Filled = exports.CellularData124Regular = exports.CellularData120Filled = exports.CellularData120Regular = exports.CellularData5Filled = exports.CellularData5Regular = exports.CellularData4Filled = exports.CellularData4Regular = exports.CellularData3Filled = exports.CellularData3Regular = exports.CellularData2Filled = exports.CellularData2Regular = exports.CellularData1Filled = exports.CellularData1Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CellularData1Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData1Regular", "", 2, undefined));
exports.CellularData1Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData1Filled", "", 2, undefined));
exports.CellularData2Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData2Regular", "", 2, undefined));
exports.CellularData2Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData2Filled", "", 2, undefined));
exports.CellularData3Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData3Regular", "", 2, undefined));
exports.CellularData3Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData3Filled", "", 2, undefined));
exports.CellularData4Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData4Regular", "", 2, undefined));
exports.CellularData4Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData4Filled", "", 2, undefined));
exports.CellularData5Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData5Regular", "", 2, undefined));
exports.CellularData5Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData5Filled", "", 2, undefined));
exports.CellularData120Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData120Regular", "", 1, 20));
exports.CellularData120Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData120Filled", "", 0, 20));
exports.CellularData124Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData124Regular", "", 1, 24));
exports.CellularData124Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData124Filled", "", 0, 24));
exports.CellularData220Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData220Regular", "", 1, 20));
exports.CellularData220Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData220Filled", "", 0, 20));
exports.CellularData224Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData224Regular", "", 1, 24));
exports.CellularData224Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData224Filled", "", 0, 24));
exports.CellularData320Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData320Regular", "", 1, 20));
exports.CellularData320Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData320Filled", "", 0, 20));
exports.CellularData324Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData324Regular", "", 1, 24));
exports.CellularData324Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData324Filled", "", 0, 24));
exports.CellularData420Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData420Regular", "", 1, 20));
exports.CellularData420Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData420Filled", "", 0, 20));
exports.CellularData424Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData424Regular", "", 1, 24));
exports.CellularData424Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData424Filled", "", 0, 24));
exports.CellularData520Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData520Regular", "", 1, 20));
exports.CellularData520Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData520Filled", "", 0, 20));
exports.CellularData524Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData524Regular", "", 1, 24));
exports.CellularData524Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CellularData524Filled", "", 0, 24));
