"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelAdd48Filled = exports.ChannelAdd48Regular = exports.ChannelAdd28Filled = exports.ChannelAdd28Regular = exports.ChannelAdd24Filled = exports.ChannelAdd24Regular = exports.ChannelAdd20Filled = exports.ChannelAdd20Regular = exports.ChannelAdd16Filled = exports.ChannelAdd16Regular = exports.ChannelAddRegular = exports.ChannelAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChannelAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAddFilled", "", 2, undefined));
exports.ChannelAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAddRegular", "", 2, undefined));
exports.ChannelAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd16Regular", "", 1, 16));
exports.ChannelAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd16Filled", "", 0, 16));
exports.ChannelAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd20Regular", "", 1, 20));
exports.ChannelAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd20Filled", "", 0, 20));
exports.ChannelAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd24Regular", "", 1, 24));
exports.ChannelAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd24Filled", "", 0, 24));
exports.ChannelAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd28Regular", "", 1, 28));
exports.ChannelAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd28Filled", "", 0, 28));
exports.ChannelAdd48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd48Regular", "", 1, 48));
exports.ChannelAdd48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAdd48Filled", "", 0, 48));
