"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Channel48Filled = exports.Channel48Regular = exports.Channel28Filled = exports.Channel28Regular = exports.Channel24Filled = exports.Channel24Regular = exports.Channel20Filled = exports.Channel20Regular = exports.Channel16Filled = exports.Channel16Regular = exports.ChannelRegular = exports.ChannelFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChannelFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelFilled", "", 2, undefined));
exports.ChannelRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelRegular", "", 2, undefined));
exports.Channel16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel16Regular", "", 1, 16));
exports.Channel16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel16Filled", "", 0, 16));
exports.Channel20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel20Regular", "", 1, 20));
exports.Channel20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel20Filled", "", 0, 20));
exports.Channel24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel24Regular", "", 1, 24));
exports.Channel24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel24Filled", "", 0, 24));
exports.Channel28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel28Regular", "", 1, 28));
exports.Channel28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel28Filled", "", 0, 28));
exports.Channel48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel48Regular", "", 1, 48));
exports.Channel48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Channel48Filled", "", 0, 48));
