"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelAlert48Filled = exports.ChannelAlert48Regular = exports.ChannelAlert28Filled = exports.ChannelAlert28Regular = exports.ChannelAlert24Filled = exports.ChannelAlert24Regular = exports.ChannelAlert20Filled = exports.ChannelAlert20Regular = exports.ChannelAlert16Filled = exports.ChannelAlert16Regular = exports.ChannelAlertRegular = exports.ChannelAlertFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChannelAlertFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlertFilled", "", 2, undefined));
exports.ChannelAlertRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlertRegular", "", 2, undefined));
exports.ChannelAlert16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert16Regular", "", 1, 16));
exports.ChannelAlert16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert16Filled", "", 0, 16));
exports.ChannelAlert20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert20Regular", "", 1, 20));
exports.ChannelAlert20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert20Filled", "", 0, 20));
exports.ChannelAlert24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert24Regular", "", 1, 24));
exports.ChannelAlert24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert24Filled", "", 0, 24));
exports.ChannelAlert28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert28Regular", "", 1, 28));
exports.ChannelAlert28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert28Filled", "", 0, 28));
exports.ChannelAlert48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert48Regular", "", 1, 48));
exports.ChannelAlert48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChannelAlert48Filled", "", 0, 48));
