"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatDismiss24Filled = exports.ChatDismiss24Regular = exports.ChatDismiss20Filled = exports.ChatDismiss20Regular = exports.ChatDismiss16Filled = exports.ChatDismiss16Regular = exports.ChatDismissRegular = exports.ChatDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChatDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismissFilled", "", 2, undefined));
exports.ChatDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismissRegular", "", 2, undefined));
exports.ChatDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismiss16Regular", "", 1, 16));
exports.ChatDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismiss16Filled", "", 0, 16));
exports.ChatDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismiss20Regular", "", 1, 20));
exports.ChatDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismiss20Filled", "", 0, 20));
exports.ChatDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismiss24Regular", "", 1, 24));
exports.ChatDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatDismiss24Filled", "", 0, 24));
