"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatCursor24Filled = exports.ChatCursor24Regular = exports.ChatCursor20Filled = exports.ChatCursor20Regular = exports.ChatCursor16Filled = exports.ChatCursor16Regular = exports.ChatCursorRegular = exports.ChatCursorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChatCursorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursorFilled", "", 2, undefined));
exports.ChatCursorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursorRegular", "", 2, undefined));
exports.ChatCursor16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursor16Regular", "", 1, 16));
exports.ChatCursor16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursor16Filled", "", 0, 16));
exports.ChatCursor20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursor20Regular", "", 1, 20));
exports.ChatCursor20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursor20Filled", "", 0, 20));
exports.ChatCursor24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursor24Regular", "", 1, 24));
exports.ChatCursor24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatCursor24Filled", "", 0, 24));
