"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatLock28Filled = exports.ChatLock28Regular = exports.ChatLock24Filled = exports.ChatLock24Regular = exports.ChatLock20Filled = exports.ChatLock20Regular = exports.ChatLock16Filled = exports.ChatLock16Regular = exports.ChatLockRegular = exports.ChatLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChatLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLockFilled", "", 2, undefined));
exports.ChatLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLockRegular", "", 2, undefined));
exports.ChatLock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock16Regular", "󰎱", 1, 16));
exports.ChatLock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock16Filled", "󰏄", 0, 16));
exports.ChatLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock20Regular", "󰎲", 1, 20));
exports.ChatLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock20Filled", "󰏅", 0, 20));
exports.ChatLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock24Regular", "󰎳", 1, 24));
exports.ChatLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock24Filled", "󰏆", 0, 24));
exports.ChatLock28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock28Regular", "󰎴", 1, 28));
exports.ChatLock28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatLock28Filled", "󰏇", 0, 28));
