"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatHistory28Filled = exports.ChatHistory28Regular = exports.ChatHistory24Filled = exports.ChatHistory24Regular = exports.ChatHistory20Filled = exports.ChatHistory20Regular = exports.ChatHistoryRegular = exports.ChatHistoryFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChatHistoryFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistoryFilled", "", 2, undefined));
exports.ChatHistoryRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistoryRegular", "", 2, undefined));
exports.ChatHistory20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistory20Regular", "󰟉", 1, 20));
exports.ChatHistory20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistory20Filled", "󰡆", 0, 20));
exports.ChatHistory24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistory24Regular", "󰟊", 1, 24));
exports.ChatHistory24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistory24Filled", "󰡇", 0, 24));
exports.ChatHistory28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistory28Regular", "󰟋", 1, 28));
exports.ChatHistory28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatHistory28Filled", "󰡈", 0, 28));
