"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatVideo24Filled = exports.ChatVideo24Regular = exports.ChatVideo20Filled = exports.ChatVideo20Regular = exports.ChatVideoRegular = exports.ChatVideoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChatVideoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatVideoFilled", "", 2, undefined));
exports.ChatVideoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatVideoRegular", "", 2, undefined));
exports.ChatVideo20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatVideo20Regular", "", 1, 20));
exports.ChatVideo20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatVideo20Filled", "", 0, 20));
exports.ChatVideo24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatVideo24Regular", "", 1, 24));
exports.ChatVideo24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChatVideo24Filled", "", 0, 24));
