"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Check24Filled = exports.Check24Regular = exports.Check20Filled = exports.Check20Regular = exports.CheckRegular = exports.CheckFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CheckFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckFilled", "", 2, undefined));
exports.CheckRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckRegular", "", 2, undefined));
exports.Check20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Check20Regular", "", 1, 20));
exports.Check20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Check20Filled", "", 0, 20));
exports.Check24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Check24Regular", "", 1, 24));
exports.Check24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Check24Filled", "", 0, 24));
