"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Checkbox224Filled = exports.Checkbox224Regular = exports.Checkbox220Filled = exports.Checkbox220Regular = exports.Checkbox124Filled = exports.Checkbox124Regular = exports.Checkbox120Filled = exports.Checkbox120Regular = exports.Checkbox2Filled = exports.Checkbox2Regular = exports.Checkbox1Filled = exports.Checkbox1Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.Checkbox1Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox1Regular", "", 2, undefined));
exports.Checkbox1Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox1Filled", "", 2, undefined));
exports.Checkbox2Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox2Regular", "", 2, undefined));
exports.Checkbox2Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox2Filled", "", 2, undefined));
exports.Checkbox120Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox120Regular", "", 1, 20));
exports.Checkbox120Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox120Filled", "", 0, 20));
exports.Checkbox124Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox124Regular", "", 1, 24));
exports.Checkbox124Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox124Filled", "", 0, 24));
exports.Checkbox220Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox220Regular", "", 1, 20));
exports.Checkbox220Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox220Filled", "", 0, 20));
exports.Checkbox224Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox224Regular", "", 1, 24));
exports.Checkbox224Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Checkbox224Filled", "", 0, 24));
