"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckboxPerson24Filled = exports.CheckboxPerson24Regular = exports.CheckboxPerson20Filled = exports.CheckboxPerson20Regular = exports.CheckboxPerson16Filled = exports.CheckboxPerson16Regular = exports.CheckboxPersonRegular = exports.CheckboxPersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CheckboxPersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPersonFilled", "", 2, undefined));
exports.CheckboxPersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPersonRegular", "", 2, undefined));
exports.CheckboxPerson16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPerson16Regular", "", 1, 16));
exports.CheckboxPerson16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPerson16Filled", "", 0, 16));
exports.CheckboxPerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPerson20Regular", "", 1, 20));
exports.CheckboxPerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPerson20Filled", "", 0, 20));
exports.CheckboxPerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPerson24Regular", "", 1, 24));
exports.CheckboxPerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxPerson24Filled", "", 0, 24));
