"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckboxWarning24Filled = exports.CheckboxWarning24Regular = exports.CheckboxWarning20Filled = exports.CheckboxWarning20Regular = exports.CheckboxWarningRegular = exports.CheckboxWarningFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CheckboxWarningFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxWarningFilled", "", 2, undefined));
exports.CheckboxWarningRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxWarningRegular", "", 2, undefined));
exports.CheckboxWarning20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxWarning20Regular", "", 1, 20));
exports.CheckboxWarning20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxWarning20Filled", "", 0, 20));
exports.CheckboxWarning24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxWarning24Regular", "", 1, 24));
exports.CheckboxWarning24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CheckboxWarning24Filled", "", 0, 24));
