"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChevronUp48Filled = exports.ChevronUp48Regular = exports.ChevronUp32Filled = exports.ChevronUp32Regular = exports.ChevronUp28Filled = exports.ChevronUp28Regular = exports.ChevronUp24Filled = exports.ChevronUp24Regular = exports.ChevronUp20Filled = exports.ChevronUp20Regular = exports.ChevronUp16Filled = exports.ChevronUp16Regular = exports.ChevronUp12Filled = exports.ChevronUp12Regular = exports.ChevronUpRegular = exports.ChevronUpFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ChevronUpFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUpFilled", "", 2, undefined));
exports.ChevronUpRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUpRegular", "", 2, undefined));
exports.ChevronUp12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp12Regular", "", 1, 12));
exports.ChevronUp12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp12Filled", "", 0, 12));
exports.ChevronUp16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp16Regular", "", 1, 16));
exports.ChevronUp16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp16Filled", "", 0, 16));
exports.ChevronUp20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp20Regular", "", 1, 20));
exports.ChevronUp20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp20Filled", "", 0, 20));
exports.ChevronUp24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp24Regular", "", 1, 24));
exports.ChevronUp24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp24Filled", "", 0, 24));
exports.ChevronUp28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp28Regular", "", 1, 28));
exports.ChevronUp28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp28Filled", "", 0, 28));
exports.ChevronUp32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp32Regular", "󰌣", 1, 32));
exports.ChevronUp32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp32Filled", "󰌶", 0, 32));
exports.ChevronUp48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp48Regular", "", 1, 48));
exports.ChevronUp48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ChevronUp48Filled", "", 0, 48));
