"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CircleImage28Filled = exports.CircleImage28Regular = exports.CircleImage24Filled = exports.CircleImage24Regular = exports.CircleImage20Filled = exports.CircleImage20Regular = exports.CircleImage16Filled = exports.CircleImage16Regular = exports.CircleImageRegular = exports.CircleImageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CircleImageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImageFilled", "", 2, undefined));
exports.CircleImageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImageRegular", "", 2, undefined));
exports.CircleImage16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage16Regular", "", 1, 16));
exports.CircleImage16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage16Filled", "", 0, 16));
exports.CircleImage20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage20Regular", "", 1, 20));
exports.CircleImage20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage20Filled", "", 0, 20));
exports.CircleImage24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage24Regular", "", 1, 24));
exports.CircleImage24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage24Filled", "", 0, 24));
exports.CircleImage28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage28Regular", "", 1, 28));
exports.CircleImage28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleImage28Filled", "", 0, 28));
