"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CircleEdit24Filled = exports.CircleEdit24Regular = exports.CircleEdit20Filled = exports.CircleEdit20Regular = exports.CircleEditRegular = exports.CircleEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CircleEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleEditFilled", "", 2, undefined));
exports.CircleEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleEditRegular", "", 2, undefined));
exports.CircleEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleEdit20Regular", "", 1, 20));
exports.CircleEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleEdit20Filled", "", 0, 20));
exports.CircleEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleEdit24Regular", "", 1, 24));
exports.CircleEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleEdit24Filled", "", 0, 24));
