"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CircleSparkle48Filled = exports.CircleSparkle48Regular = exports.CircleSparkle32Filled = exports.CircleSparkle32Regular = exports.CircleSparkle28Filled = exports.CircleSparkle28Regular = exports.CircleSparkle24Filled = exports.CircleSparkle24Regular = exports.CircleSparkle20Filled = exports.CircleSparkle20Regular = exports.CircleSparkle16Filled = exports.CircleSparkle16Regular = exports.CircleSparkleRegular = exports.CircleSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CircleSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkleFilled", "", 2, undefined));
exports.CircleSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkleRegular", "", 2, undefined));
exports.CircleSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle16Regular", "󰟏", 1, 16));
exports.CircleSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle16Filled", "󰡌", 0, 16));
exports.CircleSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle20Regular", "󰟐", 1, 20));
exports.CircleSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle20Filled", "󰡍", 0, 20));
exports.CircleSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle24Regular", "󰟑", 1, 24));
exports.CircleSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle24Filled", "󰡎", 0, 24));
exports.CircleSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle28Regular", "󰟒", 1, 28));
exports.CircleSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle28Filled", "󰡏", 0, 28));
exports.CircleSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle32Regular", "󰟓", 1, 32));
exports.CircleSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle32Filled", "󰡐", 0, 32));
exports.CircleSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle48Regular", "󰟔", 1, 48));
exports.CircleSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleSparkle48Filled", "󰡑", 0, 48));
