"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CircleLine24Filled = exports.CircleLine24Regular = exports.CircleLine20Filled = exports.CircleLine20Regular = exports.CircleLine16Filled = exports.CircleLine16Regular = exports.CircleLine12Filled = exports.CircleLine12Regular = exports.CircleLineRegular = exports.CircleLineFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CircleLineFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLineFilled", "", 2, undefined));
exports.CircleLineRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLineRegular", "", 2, undefined));
exports.CircleLine12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine12Regular", "", 1, 12));
exports.CircleLine12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine12Filled", "", 0, 12));
exports.CircleLine16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine16Regular", "󰇊", 1, 16));
exports.CircleLine16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine16Filled", "󰇊", 0, 16));
exports.CircleLine20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine20Regular", "", 1, 20));
exports.CircleLine20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine20Filled", "", 0, 20));
exports.CircleLine24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine24Regular", "", 1, 24));
exports.CircleLine24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CircleLine24Filled", "", 0, 24));
