"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardCode24Filled = exports.ClipboardCode24Regular = exports.ClipboardCode20Filled = exports.ClipboardCode20Regular = exports.ClipboardCode16Filled = exports.ClipboardCode16Regular = exports.ClipboardCodeRegular = exports.ClipboardCodeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardCodeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCodeFilled", "", 2, undefined));
exports.ClipboardCodeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCodeRegular", "", 2, undefined));
exports.ClipboardCode16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCode16Regular", "", 1, 16));
exports.ClipboardCode16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCode16Filled", "", 0, 16));
exports.ClipboardCode20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCode20Regular", "", 1, 20));
exports.ClipboardCode20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCode20Filled", "", 0, 20));
exports.ClipboardCode24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCode24Regular", "", 1, 24));
exports.ClipboardCode24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardCode24Filled", "", 0, 24));
