"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardBrush32Filled = exports.ClipboardBrush32Regular = exports.ClipboardBrush28Filled = exports.ClipboardBrush28Regular = exports.ClipboardBrush24Filled = exports.ClipboardBrush24Regular = exports.ClipboardBrush20Filled = exports.ClipboardBrush20Regular = exports.ClipboardBrush16Filled = exports.ClipboardBrush16Regular = exports.ClipboardBrushRegular = exports.ClipboardBrushFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardBrushFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrushFilled", "", 2, undefined));
exports.ClipboardBrushRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrushRegular", "", 2, undefined));
exports.ClipboardBrush16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush16Regular", "󰑪", 1, 16));
exports.ClipboardBrush16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush16Filled", "󰑽", 0, 16));
exports.ClipboardBrush20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush20Regular", "󰑫", 1, 20));
exports.ClipboardBrush20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush20Filled", "󰑾", 0, 20));
exports.ClipboardBrush24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush24Regular", "󰑬", 1, 24));
exports.ClipboardBrush24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush24Filled", "󰑿", 0, 24));
exports.ClipboardBrush28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush28Regular", "󰑭", 1, 28));
exports.ClipboardBrush28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush28Filled", "󰒀", 0, 28));
exports.ClipboardBrush32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush32Regular", "󰑮", 1, 32));
exports.ClipboardBrush32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardBrush32Filled", "󰒁", 0, 32));
