"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardMore24Filled = exports.ClipboardMore24Regular = exports.ClipboardMore20Filled = exports.ClipboardMore20Regular = exports.ClipboardMoreRegular = exports.ClipboardMoreFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardMoreFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardMoreFilled", "", 2, undefined));
exports.ClipboardMoreRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardMoreRegular", "", 2, undefined));
exports.ClipboardMore20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardMore20Regular", "", 1, 20));
exports.ClipboardMore20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardMore20Filled", "", 0, 20));
exports.ClipboardMore24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardMore24Regular", "", 1, 24));
exports.ClipboardMore24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardMore24Filled", "", 0, 24));
