"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Clipboard48Filled = exports.Clipboard48Regular = exports.Clipboard32Filled = exports.Clipboard32Regular = exports.Clipboard28Filled = exports.Clipboard28Regular = exports.Clipboard24Filled = exports.Clipboard24Regular = exports.Clipboard20Filled = exports.Clipboard20Regular = exports.Clipboard16Filled = exports.Clipboard16Regular = exports.Clipboard12Filled = exports.Clipboard12Regular = exports.ClipboardRegular = exports.ClipboardFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardFilled", "", 2, undefined));
exports.ClipboardRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardRegular", "", 2, undefined));
exports.Clipboard12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard12Regular", "󰔈", 1, 12));
exports.Clipboard12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard12Filled", "󰖁", 0, 12));
exports.Clipboard16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard16Regular", "", 1, 16));
exports.Clipboard16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard16Filled", "", 0, 16));
exports.Clipboard20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard20Regular", "", 1, 20));
exports.Clipboard20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard20Filled", "", 0, 20));
exports.Clipboard24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard24Regular", "", 1, 24));
exports.Clipboard24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard24Filled", "", 0, 24));
exports.Clipboard28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard28Regular", "󰏥", 1, 28));
exports.Clipboard28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard28Filled", "󰏸", 0, 28));
exports.Clipboard32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard32Regular", "", 1, 32));
exports.Clipboard32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard32Filled", "", 0, 32));
exports.Clipboard48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard48Regular", "󰔉", 1, 48));
exports.Clipboard48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clipboard48Filled", "󰖂", 0, 48));
