"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardImage24Filled = exports.ClipboardImage24Regular = exports.ClipboardImage20Filled = exports.ClipboardImage20Regular = exports.ClipboardImageRegular = exports.ClipboardImageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardImageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardImageFilled", "", 2, undefined));
exports.ClipboardImageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardImageRegular", "", 2, undefined));
exports.ClipboardImage20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardImage20Regular", "", 1, 20));
exports.ClipboardImage20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardImage20Filled", "", 0, 20));
exports.ClipboardImage24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardImage24Regular", "", 1, 24));
exports.ClipboardImage24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardImage24Filled", "", 0, 24));
