"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardNumber12332Filled = exports.ClipboardNumber12332Regular = exports.ClipboardNumber12328Filled = exports.ClipboardNumber12328Regular = exports.ClipboardNumber12324Filled = exports.ClipboardNumber12324Regular = exports.ClipboardNumber12320Filled = exports.ClipboardNumber12320Regular = exports.ClipboardNumber12316Filled = exports.ClipboardNumber12316Regular = exports.ClipboardNumber123Filled = exports.ClipboardNumber123Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardNumber123Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber123Regular", "", 2, undefined));
exports.ClipboardNumber123Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber123Filled", "", 2, undefined));
exports.ClipboardNumber12316Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12316Regular", "󰏫", 1, 16));
exports.ClipboardNumber12316Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12316Filled", "󰏾", 0, 16));
exports.ClipboardNumber12320Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12320Regular", "󰏬", 1, 20));
exports.ClipboardNumber12320Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12320Filled", "󰏿", 0, 20));
exports.ClipboardNumber12324Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12324Regular", "󰏭", 1, 24));
exports.ClipboardNumber12324Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12324Filled", "󰐀", 0, 24));
exports.ClipboardNumber12328Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12328Regular", "󰏮", 1, 28));
exports.ClipboardNumber12328Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12328Filled", "󰐁", 0, 28));
exports.ClipboardNumber12332Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12332Regular", "󰏯", 1, 32));
exports.ClipboardNumber12332Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardNumber12332Filled", "󰐂", 0, 32));
