"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardClock24Filled = exports.ClipboardClock24Regular = exports.ClipboardClock20Filled = exports.ClipboardClock20Regular = exports.ClipboardClockRegular = exports.ClipboardClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardClockFilled", "", 2, undefined));
exports.ClipboardClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardClockRegular", "", 2, undefined));
exports.ClipboardClock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardClock20Regular", "", 1, 20));
exports.ClipboardClock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardClock20Filled", "", 0, 20));
exports.ClipboardClock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardClock24Regular", "", 1, 24));
exports.ClipboardClock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardClock24Filled", "", 0, 24));
