"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardLink24Filled = exports.ClipboardLink24Regular = exports.ClipboardLink20Filled = exports.ClipboardLink20Regular = exports.ClipboardLink16Filled = exports.ClipboardLink16Regular = exports.ClipboardLinkRegular = exports.ClipboardLinkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardLinkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLinkFilled", "", 2, undefined));
exports.ClipboardLinkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLinkRegular", "", 2, undefined));
exports.ClipboardLink16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLink16Regular", "", 1, 16));
exports.ClipboardLink16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLink16Filled", "", 0, 16));
exports.ClipboardLink20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLink20Regular", "", 1, 20));
exports.ClipboardLink20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLink20Filled", "", 0, 20));
exports.ClipboardLink24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLink24Regular", "", 1, 24));
exports.ClipboardLink24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLink24Filled", "", 0, 24));
