"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClipboardLetter24Filled = exports.ClipboardLetter24Regular = exports.ClipboardLetter20Filled = exports.ClipboardLetter20Regular = exports.ClipboardLetter16Filled = exports.ClipboardLetter16Regular = exports.ClipboardLetterRegular = exports.ClipboardLetterFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClipboardLetterFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetterFilled", "", 2, undefined));
exports.ClipboardLetterRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetterRegular", "", 2, undefined));
exports.ClipboardLetter16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetter16Regular", "", 1, 16));
exports.ClipboardLetter16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetter16Filled", "", 0, 16));
exports.ClipboardLetter20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetter20Regular", "", 1, 20));
exports.ClipboardLetter20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetter20Filled", "", 0, 20));
exports.ClipboardLetter24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetter24Regular", "", 1, 24));
exports.ClipboardLetter24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClipboardLetter24Filled", "", 0, 24));
