"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClockDismiss24Filled = exports.ClockDismiss24Regular = exports.ClockDismiss20Filled = exports.ClockDismiss20Regular = exports.ClockDismissRegular = exports.ClockDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClockDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockDismissFilled", "", 2, undefined));
exports.ClockDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockDismissRegular", "", 2, undefined));
exports.ClockDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockDismiss20Regular", "", 1, 20));
exports.ClockDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockDismiss20Filled", "", 0, 20));
exports.ClockDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockDismiss24Regular", "", 1, 24));
exports.ClockDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockDismiss24Filled", "", 0, 24));
