"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClockSparkle32Filled = exports.ClockSparkle32Regular = exports.ClockSparkle24Filled = exports.ClockSparkle24Regular = exports.ClockSparkle20Filled = exports.ClockSparkle20Regular = exports.ClockSparkle16Filled = exports.ClockSparkle16Regular = exports.ClockSparkleRegular = exports.ClockSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClockSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkleFilled", "", 2, undefined));
exports.ClockSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkleRegular", "", 2, undefined));
exports.ClockSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle16Regular", "󰠡", 1, 16));
exports.ClockSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle16Filled", "󰢞", 0, 16));
exports.ClockSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle20Regular", "󰠢", 1, 20));
exports.ClockSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle20Filled", "󰢟", 0, 20));
exports.ClockSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle24Regular", "󰠣", 1, 24));
exports.ClockSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle24Filled", "󰢠", 0, 24));
exports.ClockSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle32Regular", "󰠤", 1, 32));
exports.ClockSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockSparkle32Filled", "󰢡", 0, 32));
