"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Clock48Filled = exports.Clock48Regular = exports.Clock32Light = exports.Clock32Filled = exports.Clock32Regular = exports.Clock28Filled = exports.Clock28Regular = exports.Clock24Filled = exports.Clock24Regular = exports.Clock20Filled = exports.Clock20Regular = exports.Clock16Filled = exports.Clock16Regular = exports.Clock12Filled = exports.Clock12Regular = exports.ClockRegular = exports.ClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockFilled", "", 2, undefined));
exports.ClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClockRegular", "", 2, undefined));
exports.Clock12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock12Regular", "", 1, 12));
exports.Clock12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock12Filled", "", 0, 12));
exports.Clock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock16Regular", "", 1, 16));
exports.Clock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock16Filled", "", 0, 16));
exports.Clock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock20Regular", "", 1, 20));
exports.Clock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock20Filled", "", 0, 20));
exports.Clock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock24Regular", "", 1, 24));
exports.Clock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock24Filled", "", 0, 24));
exports.Clock28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock28Regular", "", 1, 28));
exports.Clock28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock28Filled", "", 0, 28));
exports.Clock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock32Regular", "", 1, 32));
exports.Clock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock32Filled", "", 0, 32));
exports.Clock32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock32Light", "", 3, 32));
exports.Clock48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock48Regular", "", 1, 48));
exports.Clock48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Clock48Filled", "", 0, 48));
