"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClosedCaption48Filled = exports.ClosedCaption48Regular = exports.ClosedCaption32Filled = exports.ClosedCaption32Regular = exports.ClosedCaption28Filled = exports.ClosedCaption28Regular = exports.ClosedCaption24Filled = exports.ClosedCaption24Regular = exports.ClosedCaption20Filled = exports.ClosedCaption20Regular = exports.ClosedCaption16Filled = exports.ClosedCaption16Regular = exports.ClosedCaptionRegular = exports.ClosedCaptionFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ClosedCaptionFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaptionFilled", "", 2, undefined));
exports.ClosedCaptionRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaptionRegular", "", 2, undefined));
exports.ClosedCaption16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption16Regular", "", 1, 16));
exports.ClosedCaption16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption16Filled", "", 0, 16));
exports.ClosedCaption20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption20Regular", "", 1, 20));
exports.ClosedCaption20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption20Filled", "", 0, 20));
exports.ClosedCaption24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption24Regular", "", 1, 24));
exports.ClosedCaption24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption24Filled", "", 0, 24));
exports.ClosedCaption28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption28Regular", "", 1, 28));
exports.ClosedCaption28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption28Filled", "", 0, 28));
exports.ClosedCaption32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption32Regular", "", 1, 32));
exports.ClosedCaption32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption32Filled", "", 0, 32));
exports.ClosedCaption48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption48Regular", "", 1, 48));
exports.ClosedCaption48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ClosedCaption48Filled", "", 0, 48));
