"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudArchive48Filled = exports.CloudArchive48Regular = exports.CloudArchive32Filled = exports.CloudArchive32Regular = exports.CloudArchive28Filled = exports.CloudArchive28Regular = exports.CloudArchive24Filled = exports.CloudArchive24Regular = exports.CloudArchive20Filled = exports.CloudArchive20Regular = exports.CloudArchive16Filled = exports.CloudArchive16Regular = exports.CloudArchiveRegular = exports.CloudArchiveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudArchiveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchiveFilled", "", 2, undefined));
exports.CloudArchiveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchiveRegular", "", 2, undefined));
exports.CloudArchive16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive16Regular", "", 1, 16));
exports.CloudArchive16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive16Filled", "", 0, 16));
exports.CloudArchive20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive20Regular", "", 1, 20));
exports.CloudArchive20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive20Filled", "", 0, 20));
exports.CloudArchive24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive24Regular", "", 1, 24));
exports.CloudArchive24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive24Filled", "", 0, 24));
exports.CloudArchive28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive28Regular", "", 1, 28));
exports.CloudArchive28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive28Filled", "", 0, 28));
exports.CloudArchive32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive32Regular", "", 1, 32));
exports.CloudArchive32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive32Filled", "", 0, 32));
exports.CloudArchive48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive48Regular", "", 1, 48));
exports.CloudArchive48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudArchive48Filled", "", 0, 48));
