"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudLink24Filled = exports.CloudLink24Regular = exports.CloudLink20Filled = exports.CloudLink20Regular = exports.CloudLink16Filled = exports.CloudLink16Regular = exports.CloudLinkRegular = exports.CloudLinkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudLinkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLinkFilled", "", 2, undefined));
exports.CloudLinkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLinkRegular", "", 2, undefined));
exports.CloudLink16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLink16Regular", "", 1, 16));
exports.CloudLink16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLink16Filled", "", 0, 16));
exports.CloudLink20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLink20Regular", "", 1, 20));
exports.CloudLink20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLink20Filled", "", 0, 20));
exports.CloudLink24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLink24Regular", "", 1, 24));
exports.CloudLink24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudLink24Filled", "", 0, 24));
