"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudSwap24Filled = exports.CloudSwap24Regular = exports.CloudSwap20Filled = exports.CloudSwap20Regular = exports.CloudSwapRegular = exports.CloudSwapFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudSwapFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudSwapFilled", "", 2, undefined));
exports.CloudSwapRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudSwapRegular", "", 2, undefined));
exports.CloudSwap20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudSwap20Regular", "", 1, 20));
exports.CloudSwap20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudSwap20Filled", "", 0, 20));
exports.CloudSwap24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudSwap24Regular", "", 1, 24));
exports.CloudSwap24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudSwap24Filled", "", 0, 24));
