"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudBeaker48Filled = exports.CloudBeaker48Regular = exports.CloudBeaker32Filled = exports.CloudBeaker32Regular = exports.CloudBeaker28Filled = exports.CloudBeaker28Regular = exports.CloudBeaker24Filled = exports.CloudBeaker24Regular = exports.CloudBeaker20Filled = exports.CloudBeaker20Regular = exports.CloudBeaker16Filled = exports.CloudBeaker16Regular = exports.CloudBeakerRegular = exports.CloudBeakerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudBeakerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeakerFilled", "", 2, undefined));
exports.CloudBeakerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeakerRegular", "", 2, undefined));
exports.CloudBeaker16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker16Regular", "󰑯", 1, 16));
exports.CloudBeaker16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker16Filled", "󰒂", 0, 16));
exports.CloudBeaker20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker20Regular", "󰑰", 1, 20));
exports.CloudBeaker20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker20Filled", "󰒃", 0, 20));
exports.CloudBeaker24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker24Regular", "󰑱", 1, 24));
exports.CloudBeaker24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker24Filled", "󰒄", 0, 24));
exports.CloudBeaker28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker28Regular", "󰑲", 1, 28));
exports.CloudBeaker28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker28Filled", "󰒅", 0, 28));
exports.CloudBeaker32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker32Regular", "󰑳", 1, 32));
exports.CloudBeaker32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker32Filled", "󰒆", 0, 32));
exports.CloudBeaker48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker48Regular", "󰑴", 1, 48));
exports.CloudBeaker48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudBeaker48Filled", "󰒇", 0, 48));
