"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudWords48Filled = exports.CloudWords48Regular = exports.CloudWords32Filled = exports.CloudWords32Regular = exports.CloudWords28Filled = exports.CloudWords28Regular = exports.CloudWords24Filled = exports.CloudWords24Regular = exports.CloudWords20Filled = exports.CloudWords20Regular = exports.CloudWords16Filled = exports.CloudWords16Regular = exports.CloudWordsRegular = exports.CloudWordsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudWordsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWordsFilled", "", 2, undefined));
exports.CloudWordsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWordsRegular", "", 2, undefined));
exports.CloudWords16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords16Regular", "", 1, 16));
exports.CloudWords16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords16Filled", "", 0, 16));
exports.CloudWords20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords20Regular", "", 1, 20));
exports.CloudWords20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords20Filled", "", 0, 20));
exports.CloudWords24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords24Regular", "", 1, 24));
exports.CloudWords24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords24Filled", "", 0, 24));
exports.CloudWords28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords28Regular", "", 1, 28));
exports.CloudWords28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords28Filled", "", 0, 28));
exports.CloudWords32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords32Regular", "", 1, 32));
exports.CloudWords32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords32Filled", "", 0, 32));
exports.CloudWords48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords48Regular", "", 1, 48));
exports.CloudWords48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudWords48Filled", "", 0, 48));
