"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudFlow24Filled = exports.CloudFlow24Regular = exports.CloudFlow20Filled = exports.CloudFlow20Regular = exports.CloudFlowRegular = exports.CloudFlowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudFlowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudFlowFilled", "", 2, undefined));
exports.CloudFlowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudFlowRegular", "", 2, undefined));
exports.CloudFlow20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudFlow20Regular", "", 1, 20));
exports.CloudFlow20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudFlow20Filled", "", 0, 20));
exports.CloudFlow24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudFlow24Regular", "", 1, 24));
exports.CloudFlow24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudFlow24Filled", "", 0, 24));
