"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CloudError48Filled = exports.CloudError48Regular = exports.CloudError32Filled = exports.CloudError32Regular = exports.CloudError28Filled = exports.CloudError28Regular = exports.CloudError24Filled = exports.CloudError24Regular = exports.CloudError20Filled = exports.CloudError20Regular = exports.CloudError16Filled = exports.CloudError16Regular = exports.CloudErrorRegular = exports.CloudErrorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CloudErrorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudErrorFilled", "", 2, undefined));
exports.CloudErrorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudErrorRegular", "", 2, undefined));
exports.CloudError16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError16Regular", "", 1, 16));
exports.CloudError16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError16Filled", "", 0, 16));
exports.CloudError20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError20Regular", "", 1, 20));
exports.CloudError20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError20Filled", "", 0, 20));
exports.CloudError24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError24Regular", "", 1, 24));
exports.CloudError24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError24Filled", "", 0, 24));
exports.CloudError28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError28Regular", "", 1, 28));
exports.CloudError28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError28Filled", "", 0, 28));
exports.CloudError32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError32Regular", "", 1, 32));
exports.CloudError32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError32Filled", "", 0, 32));
exports.CloudError48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError48Regular", "", 1, 48));
exports.CloudError48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CloudError48Filled", "", 0, 48));
