"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CodeText20Filled = exports.CodeText20Regular = exports.CodeText16Filled = exports.CodeText16Regular = exports.CodeTextRegular = exports.CodeTextFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CodeTextFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeTextFilled", "", 2, undefined));
exports.CodeTextRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeTextRegular", "", 2, undefined));
exports.CodeText16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeText16Regular", "", 1, 16));
exports.CodeText16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeText16Filled", "", 0, 16));
exports.CodeText20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeText20Regular", "", 1, 20));
exports.CodeText20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeText20Filled", "", 0, 20));
