"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Code24Filled = exports.Code24Regular = exports.Code20Filled = exports.Code20Regular = exports.Code16Filled = exports.Code16Regular = exports.CodeRegular = exports.CodeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CodeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeFilled", "", 2, undefined));
exports.CodeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CodeRegular", "", 2, undefined));
exports.Code16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Code16Regular", "", 1, 16));
exports.Code16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Code16Filled", "", 0, 16));
exports.Code20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Code20Regular", "", 1, 20));
exports.Code20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Code20Filled", "", 0, 20));
exports.Code24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Code24Regular", "", 1, 24));
exports.Code24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Code24Filled", "", 0, 24));
