"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CollectionsEmpty24Filled = exports.CollectionsEmpty24Regular = exports.CollectionsEmpty20Filled = exports.CollectionsEmpty20Regular = exports.CollectionsEmpty16Filled = exports.CollectionsEmpty16Regular = exports.CollectionsEmptyRegular = exports.CollectionsEmptyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CollectionsEmptyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmptyFilled", "", 2, undefined));
exports.CollectionsEmptyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmptyRegular", "", 2, undefined));
exports.CollectionsEmpty16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmpty16Regular", "󰠨", 1, 16));
exports.CollectionsEmpty16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmpty16Filled", "󰢥", 0, 16));
exports.CollectionsEmpty20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmpty20Regular", "󰠩", 1, 20));
exports.CollectionsEmpty20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmpty20Filled", "󰢦", 0, 20));
exports.CollectionsEmpty24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmpty24Regular", "󰠪", 1, 24));
exports.CollectionsEmpty24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CollectionsEmpty24Filled", "󰢧", 0, 24));
