"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ColorFill32Light = exports.ColorFill28Filled = exports.ColorFill28Regular = exports.ColorFill24Filled = exports.ColorFill24Regular = exports.ColorFill20Filled = exports.ColorFill20Regular = exports.ColorFill16Filled = exports.ColorFill16Regular = exports.ColorFillRegular = exports.ColorFillFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ColorFillFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFillFilled", "", 2, undefined));
exports.ColorFillRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFillRegular", "", 2, undefined));
exports.ColorFill16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill16Regular", "", 1, 16));
exports.ColorFill16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill16Filled", "", 0, 16));
exports.ColorFill20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill20Regular", "", 1, 20));
exports.ColorFill20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill20Filled", "", 0, 20));
exports.ColorFill24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill24Regular", "", 1, 24));
exports.ColorFill24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill24Filled", "", 0, 24));
exports.ColorFill28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill28Regular", "", 1, 28));
exports.ColorFill28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill28Filled", "", 0, 28));
exports.ColorFill32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColorFill32Light", "", 3, 32));
