"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ColumnEdit24Filled = exports.ColumnEdit24Regular = exports.ColumnEdit20Filled = exports.ColumnEdit20Regular = exports.ColumnEditRegular = exports.ColumnEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ColumnEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColumnEditFilled", "", 2, undefined));
exports.ColumnEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColumnEditRegular", "", 2, undefined));
exports.ColumnEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColumnEdit20Regular", "", 1, 20));
exports.ColumnEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColumnEdit20Filled", "", 0, 20));
exports.ColumnEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColumnEdit24Regular", "", 1, 24));
exports.ColumnEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ColumnEdit24Filled", "", 0, 24));
