"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommentMention24Filled = exports.CommentMention24Regular = exports.CommentMention20Filled = exports.CommentMention20Regular = exports.CommentMention16Filled = exports.CommentMention16Regular = exports.CommentMentionRegular = exports.CommentMentionFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommentMentionFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMentionFilled", "", 2, undefined, { flipInRtl: true }));
exports.CommentMentionRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMentionRegular", "", 2, undefined, { flipInRtl: true }));
exports.CommentMention16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMention16Regular", "", 1, 16, { flipInRtl: true }));
exports.CommentMention16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMention16Filled", "", 0, 16, { flipInRtl: true }));
exports.CommentMention20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMention20Regular", "", 1, 20, { flipInRtl: true }));
exports.CommentMention20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMention20Filled", "", 0, 20, { flipInRtl: true }));
exports.CommentMention24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMention24Regular", "", 1, 24, { flipInRtl: true }));
exports.CommentMention24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentMention24Filled", "", 0, 24, { flipInRtl: true }));
