"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommentNote24Filled = exports.CommentNote24Regular = exports.CommentNote20Filled = exports.CommentNote20Regular = exports.CommentNoteRegular = exports.CommentNoteFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommentNoteFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentNoteFilled", "", 2, undefined, { flipInRtl: true }));
exports.CommentNoteRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentNoteRegular", "", 2, undefined, { flipInRtl: true }));
exports.CommentNote20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentNote20Regular", "", 1, 20, { flipInRtl: true }));
exports.CommentNote20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentNote20Filled", "", 0, 20, { flipInRtl: true }));
exports.CommentNote24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentNote24Regular", "", 1, 24, { flipInRtl: true }));
exports.CommentNote24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentNote24Filled", "", 0, 24, { flipInRtl: true }));
