"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommunicationShield24Filled = exports.CommunicationShield24Regular = exports.CommunicationShield20Filled = exports.CommunicationShield20Regular = exports.CommunicationShield16Filled = exports.CommunicationShield16Regular = exports.CommunicationShieldRegular = exports.CommunicationShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommunicationShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShieldFilled", "", 2, undefined));
exports.CommunicationShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShieldRegular", "", 2, undefined));
exports.CommunicationShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShield16Regular", "󰏱", 1, 16));
exports.CommunicationShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShield16Filled", "󰐄", 0, 16));
exports.CommunicationShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShield20Regular", "󰏲", 1, 20));
exports.CommunicationShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShield20Filled", "󰐅", 0, 20));
exports.CommunicationShield24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShield24Regular", "󰏳", 1, 24));
exports.CommunicationShield24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationShield24Filled", "󰐆", 0, 24));
