"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Comment48Filled = exports.Comment48Regular = exports.Comment32Light = exports.Comment32Filled = exports.Comment32Regular = exports.Comment28Filled = exports.Comment28Regular = exports.Comment24Filled = exports.Comment24Regular = exports.Comment20Filled = exports.Comment20Regular = exports.Comment16Filled = exports.Comment16Regular = exports.Comment12Filled = exports.Comment12Regular = exports.CommentRegular = exports.CommentFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommentFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentFilled", "", 2, undefined, { flipInRtl: true }));
exports.CommentRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentRegular", "", 2, undefined, { flipInRtl: true }));
exports.Comment12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment12Regular", "", 1, 12, { flipInRtl: true }));
exports.Comment12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment12Filled", "", 0, 12, { flipInRtl: true }));
exports.Comment16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment16Regular", "", 1, 16, { flipInRtl: true }));
exports.Comment16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment16Filled", "", 0, 16, { flipInRtl: true }));
exports.Comment20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment20Regular", "", 1, 20, { flipInRtl: true }));
exports.Comment20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment20Filled", "", 0, 20, { flipInRtl: true }));
exports.Comment24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment24Regular", "", 1, 24, { flipInRtl: true }));
exports.Comment24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment24Filled", "", 0, 24, { flipInRtl: true }));
exports.Comment28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment28Regular", "", 1, 28, { flipInRtl: true }));
exports.Comment28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment28Filled", "", 0, 28, { flipInRtl: true }));
exports.Comment32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment32Regular", "󰗦", 1, 32, { flipInRtl: true }));
exports.Comment32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment32Filled", "󰙢", 0, 32, { flipInRtl: true }));
exports.Comment32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment32Light", "", 3, 32));
exports.Comment48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment48Regular", "", 1, 48, { flipInRtl: true }));
exports.Comment48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comment48Filled", "", 0, 48, { flipInRtl: true }));
