"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Communication24Filled = exports.Communication24Regular = exports.Communication20Filled = exports.Communication20Regular = exports.Communication16Filled = exports.Communication16Regular = exports.CommunicationRegular = exports.CommunicationFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommunicationFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationFilled", "", 2, undefined));
exports.CommunicationRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommunicationRegular", "", 2, undefined));
exports.Communication16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Communication16Regular", "", 1, 16));
exports.Communication16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Communication16Filled", "", 0, 16));
exports.Communication20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Communication20Regular", "", 1, 20));
exports.Communication20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Communication20Filled", "", 0, 20));
exports.Communication24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Communication24Regular", "", 1, 24));
exports.Communication24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Communication24Filled", "", 0, 24));
