"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Comma24Filled = exports.Comma24Regular = exports.Comma20Filled = exports.Comma20Regular = exports.CommaRegular = exports.CommaFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommaFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommaFilled", "", 2, undefined));
exports.CommaRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommaRegular", "", 2, undefined));
exports.Comma20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comma20Regular", "", 1, 20));
exports.Comma20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comma20Filled", "", 0, 20));
exports.Comma24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comma24Regular", "", 1, 24));
exports.Comma24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Comma24Filled", "", 0, 24));
