"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommentDismiss24Filled = exports.CommentDismiss24Regular = exports.CommentDismiss20Filled = exports.CommentDismiss20Regular = exports.CommentDismissRegular = exports.CommentDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CommentDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentDismissFilled", "", 2, undefined, { flipInRtl: true }));
exports.CommentDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentDismissRegular", "", 2, undefined, { flipInRtl: true }));
exports.CommentDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentDismiss20Regular", "", 1, 20, { flipInRtl: true }));
exports.CommentDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentDismiss20Filled", "", 0, 20, { flipInRtl: true }));
exports.CommentDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentDismiss24Regular", "", 1, 24, { flipInRtl: true }));
exports.CommentDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CommentDismiss24Filled", "", 0, 24, { flipInRtl: true }));
