"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Compose48Filled = exports.Compose48Regular = exports.Compose32Light = exports.Compose32Filled = exports.Compose32Regular = exports.Compose28Filled = exports.Compose28Regular = exports.Compose24Filled = exports.Compose24Regular = exports.Compose20Filled = exports.Compose20Regular = exports.Compose16Filled = exports.Compose16Regular = exports.Compose12Filled = exports.Compose12Regular = exports.ComposeRegular = exports.ComposeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ComposeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ComposeFilled", "", 2, undefined));
exports.ComposeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ComposeRegular", "", 2, undefined));
exports.Compose12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose12Regular", "󰔊", 1, 12));
exports.Compose12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose12Filled", "󰖃", 0, 12));
exports.Compose16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose16Regular", "", 1, 16));
exports.Compose16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose16Filled", "", 0, 16));
exports.Compose20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose20Regular", "", 1, 20));
exports.Compose20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose20Filled", "", 0, 20));
exports.Compose24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose24Regular", "", 1, 24));
exports.Compose24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose24Filled", "", 0, 24));
exports.Compose28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose28Regular", "", 1, 28));
exports.Compose28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose28Filled", "", 0, 28));
exports.Compose32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose32Regular", "󰔋", 1, 32));
exports.Compose32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose32Filled", "󰖄", 0, 32));
exports.Compose32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose32Light", "", 3, 32));
exports.Compose48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose48Regular", "󰔌", 1, 48));
exports.Compose48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Compose48Filled", "󰖅", 0, 48));
