"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConferenceRoom48Filled = exports.ConferenceRoom48Regular = exports.ConferenceRoom28Filled = exports.ConferenceRoom28Regular = exports.ConferenceRoom24Filled = exports.ConferenceRoom24Regular = exports.ConferenceRoom20Filled = exports.ConferenceRoom20Regular = exports.ConferenceRoom16Filled = exports.ConferenceRoom16Regular = exports.ConferenceRoomRegular = exports.ConferenceRoomFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ConferenceRoomFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoomFilled", "", 2, undefined));
exports.ConferenceRoomRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoomRegular", "", 2, undefined));
exports.ConferenceRoom16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom16Regular", "", 1, 16));
exports.ConferenceRoom16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom16Filled", "", 0, 16));
exports.ConferenceRoom20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom20Regular", "", 1, 20));
exports.ConferenceRoom20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom20Filled", "", 0, 20));
exports.ConferenceRoom24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom24Regular", "", 1, 24));
exports.ConferenceRoom24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom24Filled", "", 0, 24));
exports.ConferenceRoom28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom28Regular", "", 1, 28));
exports.ConferenceRoom28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom28Filled", "", 0, 28));
exports.ConferenceRoom48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom48Regular", "", 1, 48));
exports.ConferenceRoom48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConferenceRoom48Filled", "", 0, 48));
