"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Connected48Filled = exports.Connected48Regular = exports.Connected32Filled = exports.Connected32Regular = exports.Connected28Filled = exports.Connected28Regular = exports.Connected24Filled = exports.Connected24Regular = exports.Connected20Filled = exports.Connected20Regular = exports.Connected16Filled = exports.Connected16Regular = exports.ConnectedRegular = exports.ConnectedFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ConnectedFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConnectedFilled", "", 2, undefined));
exports.ConnectedRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ConnectedRegular", "", 2, undefined));
exports.Connected16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected16Regular", "", 1, 16));
exports.Connected16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected16Filled", "", 0, 16));
exports.Connected20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected20Regular", "", 1, 20));
exports.Connected20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected20Filled", "", 0, 20));
exports.Connected24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected24Regular", "󰞑", 1, 24));
exports.Connected24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected24Filled", "󰠎", 0, 24));
exports.Connected28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected28Regular", "󰥃", 1, 28));
exports.Connected28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected28Filled", "󰧀", 0, 28));
exports.Connected32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected32Regular", "󰞒", 1, 32));
exports.Connected32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected32Filled", "󰠏", 0, 32));
exports.Connected48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected48Regular", "󰥄", 1, 48));
exports.Connected48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Connected48Filled", "󰧁", 0, 48));
