"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ControlButton24Filled = exports.ControlButton24Regular = exports.ControlButton20Filled = exports.ControlButton20Regular = exports.ControlButtonRegular = exports.ControlButtonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ControlButtonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ControlButtonFilled", "", 2, undefined));
exports.ControlButtonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ControlButtonRegular", "", 2, undefined));
exports.ControlButton20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ControlButton20Regular", "", 1, 20));
exports.ControlButton20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ControlButton20Filled", "", 0, 20));
exports.ControlButton24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ControlButton24Regular", "", 1, 24));
exports.ControlButton24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ControlButton24Filled", "", 0, 24));
