"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ContactCard48Filled = exports.ContactCard48Regular = exports.ContactCard32Filled = exports.ContactCard32Regular = exports.ContactCard28Filled = exports.ContactCard28Regular = exports.ContactCard24Filled = exports.ContactCard24Regular = exports.ContactCard20Filled = exports.ContactCard20Regular = exports.ContactCard16Filled = exports.ContactCard16Regular = exports.ContactCardRegular = exports.ContactCardFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ContactCardFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCardFilled", "", 2, undefined));
exports.ContactCardRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCardRegular", "", 2, undefined));
exports.ContactCard16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard16Regular", "", 1, 16));
exports.ContactCard16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard16Filled", "", 0, 16));
exports.ContactCard20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard20Regular", "", 1, 20));
exports.ContactCard20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard20Filled", "", 0, 20));
exports.ContactCard24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard24Regular", "", 1, 24));
exports.ContactCard24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard24Filled", "", 0, 24));
exports.ContactCard28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard28Regular", "", 1, 28));
exports.ContactCard28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard28Filled", "", 0, 28));
exports.ContactCard32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard32Regular", "", 1, 32));
exports.ContactCard32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard32Filled", "", 0, 32));
exports.ContactCard48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard48Regular", "", 1, 48));
exports.ContactCard48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ContactCard48Filled", "", 0, 48));
