"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Cookies48Filled = exports.Cookies48Regular = exports.Cookies32Filled = exports.Cookies32Regular = exports.Cookies28Filled = exports.Cookies28Regular = exports.Cookies24Filled = exports.Cookies24Regular = exports.Cookies20Filled = exports.Cookies20Regular = exports.Cookies16Filled = exports.Cookies16Regular = exports.CookiesRegular = exports.CookiesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CookiesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CookiesFilled", "", 2, undefined));
exports.CookiesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CookiesRegular", "", 2, undefined));
exports.Cookies16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies16Regular", "󰓭", 1, 16));
exports.Cookies16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies16Filled", "󰕦", 0, 16));
exports.Cookies20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies20Regular", "", 1, 20));
exports.Cookies20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies20Filled", "", 0, 20));
exports.Cookies24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies24Regular", "", 1, 24));
exports.Cookies24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies24Filled", "", 0, 24));
exports.Cookies28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies28Regular", "󰓮", 1, 28));
exports.Cookies28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies28Filled", "󰕧", 0, 28));
exports.Cookies32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies32Regular", "󰓯", 1, 32));
exports.Cookies32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies32Filled", "󰕨", 0, 32));
exports.Cookies48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies48Regular", "󰓰", 1, 48));
exports.Cookies48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Cookies48Filled", "󰕩", 0, 48));
