"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CopyAdd24Filled = exports.CopyAdd24Regular = exports.CopyAdd20Filled = exports.CopyAdd20Regular = exports.CopyAddRegular = exports.CopyAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CopyAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyAddFilled", "", 2, undefined));
exports.CopyAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyAddRegular", "", 2, undefined));
exports.CopyAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyAdd20Regular", "", 1, 20));
exports.CopyAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyAdd20Filled", "", 0, 20));
exports.CopyAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyAdd24Regular", "", 1, 24));
exports.CopyAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyAdd24Filled", "", 0, 24));
