"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Copy32Light = exports.Copy32Filled = exports.Copy32Regular = exports.Copy28Filled = exports.Copy28Regular = exports.Copy24Filled = exports.Copy24Regular = exports.Copy20Filled = exports.Copy20Regular = exports.Copy16Filled = exports.Copy16Regular = exports.CopyRegular = exports.CopyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.CopyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyFilled", "", 2, undefined));
exports.CopyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("CopyRegular", "", 2, undefined));
exports.Copy16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy16Regular", "", 1, 16));
exports.Copy16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy16Filled", "", 0, 16));
exports.Copy20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy20Regular", "", 1, 20));
exports.Copy20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy20Filled", "", 0, 20));
exports.Copy24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy24Regular", "", 1, 24));
exports.Copy24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy24Filled", "", 0, 24));
exports.Copy28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy28Regular", "󰟕", 1, 28));
exports.Copy28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy28Filled", "󰡒", 0, 28));
exports.Copy32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy32Regular", "󰀆", 1, 32));
exports.Copy32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy32Filled", "󰀊", 0, 32));
exports.Copy32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Copy32Light", "", 3, 32));
