"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataArea32Filled = exports.DataArea32Regular = exports.DataArea24Filled = exports.DataArea24Regular = exports.DataArea20Filled = exports.DataArea20Regular = exports.DataAreaRegular = exports.DataAreaFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DataAreaFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataAreaFilled", "", 2, undefined));
exports.DataAreaRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataAreaRegular", "", 2, undefined));
exports.DataArea20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataArea20Regular", "", 1, 20));
exports.DataArea20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataArea20Filled", "", 0, 20));
exports.DataArea24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataArea24Regular", "", 1, 24));
exports.DataArea24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataArea24Filled", "", 0, 24));
exports.DataArea32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataArea32Regular", "󰠳", 1, 32));
exports.DataArea32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataArea32Filled", "󰢰", 0, 32));
