"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DatabaseSwitch24Filled = exports.DatabaseSwitch24Regular = exports.DatabaseSwitch20Filled = exports.DatabaseSwitch20Regular = exports.DatabaseSwitchRegular = exports.DatabaseSwitchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DatabaseSwitchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSwitchFilled", "", 2, undefined));
exports.DatabaseSwitchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSwitchRegular", "", 2, undefined));
exports.DatabaseSwitch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSwitch20Regular", "", 1, 20));
exports.DatabaseSwitch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSwitch20Filled", "", 0, 20));
exports.DatabaseSwitch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSwitch24Regular", "󰠺", 1, 24));
exports.DatabaseSwitch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSwitch24Filled", "󰢷", 0, 24));
