"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataPie32Filled = exports.DataPie32Regular = exports.DataPie24Filled = exports.DataPie24Regular = exports.DataPie20Filled = exports.DataPie20Regular = exports.DataPie16Filled = exports.DataPie16Regular = exports.DataPieRegular = exports.DataPieFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DataPieFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPieFilled", "", 2, undefined));
exports.DataPieRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPieRegular", "", 2, undefined));
exports.DataPie16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie16Regular", "󰗖", 1, 16));
exports.DataPie16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie16Filled", "󰙏", 0, 16));
exports.DataPie20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie20Regular", "", 1, 20));
exports.DataPie20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie20Filled", "", 0, 20));
exports.DataPie24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie24Regular", "", 1, 24));
exports.DataPie24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie24Filled", "", 0, 24));
exports.DataPie32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie32Regular", "󰠵", 1, 32));
exports.DataPie32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DataPie32Filled", "󰢲", 0, 32));
