"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Database48Filled = exports.Database48Regular = exports.Database32Filled = exports.Database32Regular = exports.Database24Filled = exports.Database24Regular = exports.Database20Filled = exports.Database20Regular = exports.Database16Filled = exports.Database16Regular = exports.DatabaseRegular = exports.DatabaseFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DatabaseFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseFilled", "", 2, undefined));
exports.DatabaseRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseRegular", "", 2, undefined));
exports.Database16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database16Regular", "", 1, 16));
exports.Database16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database16Filled", "", 0, 16));
exports.Database20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database20Regular", "", 1, 20));
exports.Database20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database20Filled", "", 0, 20));
exports.Database24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database24Regular", "", 1, 24));
exports.Database24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database24Filled", "", 0, 24));
exports.Database32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database32Regular", "", 1, 32));
exports.Database32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database32Filled", "", 0, 32));
exports.Database48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database48Regular", "󰀈", 1, 48));
exports.Database48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Database48Filled", "󰀌", 0, 48));
