"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DatabaseSearch32Filled = exports.DatabaseSearch32Regular = exports.DatabaseSearch24Filled = exports.DatabaseSearch24Regular = exports.DatabaseSearch20Filled = exports.DatabaseSearch20Regular = exports.DatabaseSearchRegular = exports.DatabaseSearchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DatabaseSearchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearchFilled", "", 2, undefined));
exports.DatabaseSearchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearchRegular", "", 2, undefined));
exports.DatabaseSearch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearch20Regular", "", 1, 20));
exports.DatabaseSearch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearch20Filled", "", 0, 20));
exports.DatabaseSearch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearch24Regular", "", 1, 24));
exports.DatabaseSearch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearch24Filled", "", 0, 24));
exports.DatabaseSearch32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearch32Regular", "󰚻", 1, 32));
exports.DatabaseSearch32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabaseSearch32Filled", "󰜸", 0, 32));
