"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DatabasePerson24Filled = exports.DatabasePerson24Regular = exports.DatabasePerson20Filled = exports.DatabasePerson20Regular = exports.DatabasePersonRegular = exports.DatabasePersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DatabasePersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabasePersonFilled", "", 2, undefined));
exports.DatabasePersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabasePersonRegular", "", 2, undefined));
exports.DatabasePerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabasePerson20Regular", "", 1, 20));
exports.DatabasePerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabasePerson20Filled", "", 0, 20));
exports.DatabasePerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabasePerson24Regular", "", 1, 24));
exports.DatabasePerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DatabasePerson24Filled", "", 0, 24));
