"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Delete48Filled = exports.Delete48Regular = exports.Delete32Light = exports.Delete32Filled = exports.Delete32Regular = exports.Delete28Filled = exports.Delete28Regular = exports.Delete24Filled = exports.Delete24Regular = exports.Delete20Filled = exports.Delete20Regular = exports.Delete16Filled = exports.Delete16Regular = exports.Delete12Filled = exports.Delete12Regular = exports.DeleteRegular = exports.DeleteFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DeleteFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteFilled", "", 2, undefined));
exports.DeleteRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteRegular", "", 2, undefined));
exports.Delete12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete12Regular", "", 1, 12));
exports.Delete12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete12Filled", "", 0, 12));
exports.Delete16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete16Regular", "", 1, 16));
exports.Delete16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete16Filled", "", 0, 16));
exports.Delete20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete20Regular", "", 1, 20));
exports.Delete20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete20Filled", "", 0, 20));
exports.Delete24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete24Regular", "", 1, 24));
exports.Delete24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete24Filled", "", 0, 24));
exports.Delete28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete28Regular", "", 1, 28));
exports.Delete28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete28Filled", "", 0, 28));
exports.Delete32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete32Regular", "", 1, 32));
exports.Delete32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete32Filled", "", 0, 32));
exports.Delete32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete32Light", "", 3, 32));
exports.Delete48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete48Regular", "", 1, 48));
exports.Delete48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Delete48Filled", "", 0, 48));
