"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeleteDismiss28Filled = exports.DeleteDismiss28Regular = exports.DeleteDismiss24Filled = exports.DeleteDismiss24Regular = exports.DeleteDismiss20Filled = exports.DeleteDismiss20Regular = exports.DeleteDismissRegular = exports.DeleteDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DeleteDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismissFilled", "", 2, undefined));
exports.DeleteDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismissRegular", "", 2, undefined));
exports.DeleteDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismiss20Regular", "", 1, 20));
exports.DeleteDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismiss20Filled", "", 0, 20));
exports.DeleteDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismiss24Regular", "", 1, 24));
exports.DeleteDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismiss24Filled", "", 0, 24));
exports.DeleteDismiss28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismiss28Regular", "", 1, 28));
exports.DeleteDismiss28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeleteDismiss28Filled", "", 0, 28));
