"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DesktopCursor28Filled = exports.DesktopCursor28Regular = exports.DesktopCursor24Filled = exports.DesktopCursor24Regular = exports.DesktopCursor20Filled = exports.DesktopCursor20Regular = exports.DesktopCursor16Filled = exports.DesktopCursor16Regular = exports.DesktopCursorRegular = exports.DesktopCursorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DesktopCursorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursorFilled", "", 2, undefined));
exports.DesktopCursorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursorRegular", "", 2, undefined));
exports.DesktopCursor16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor16Regular", "", 1, 16));
exports.DesktopCursor16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor16Filled", "", 0, 16));
exports.DesktopCursor20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor20Regular", "", 1, 20));
exports.DesktopCursor20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor20Filled", "", 0, 20));
exports.DesktopCursor24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor24Regular", "", 1, 24));
exports.DesktopCursor24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor24Filled", "", 0, 24));
exports.DesktopCursor28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor28Regular", "", 1, 28));
exports.DesktopCursor28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopCursor28Filled", "", 0, 28));
