"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Desktop48Filled = exports.Desktop48Regular = exports.Desktop32Filled = exports.Desktop32Regular = exports.Desktop28Filled = exports.Desktop28Regular = exports.Desktop24Filled = exports.Desktop24Regular = exports.Desktop20Filled = exports.Desktop20Regular = exports.Desktop16Filled = exports.Desktop16Regular = exports.DesktopRegular = exports.DesktopFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DesktopFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopFilled", "", 2, undefined));
exports.DesktopRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DesktopRegular", "", 2, undefined));
exports.Desktop16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop16Regular", "", 1, 16));
exports.Desktop16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop16Filled", "", 0, 16));
exports.Desktop20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop20Regular", "", 1, 20));
exports.Desktop20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop20Filled", "", 0, 20));
exports.Desktop24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop24Regular", "", 1, 24));
exports.Desktop24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop24Filled", "", 0, 24));
exports.Desktop28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop28Regular", "", 1, 28));
exports.Desktop28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop28Filled", "", 0, 28));
exports.Desktop32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop32Regular", "", 1, 32));
exports.Desktop32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop32Filled", "", 0, 32));
exports.Desktop48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop48Regular", "󰠽", 1, 48));
exports.Desktop48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Desktop48Filled", "󰢺", 0, 48));
