"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeskSparkle24Filled = exports.DeskSparkle24Regular = exports.DeskSparkle20Filled = exports.DeskSparkle20Regular = exports.DeskSparkle16Filled = exports.DeskSparkle16Regular = exports.DeskSparkleRegular = exports.DeskSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DeskSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkleFilled", "", 2, undefined));
exports.DeskSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkleRegular", "", 2, undefined));
exports.DeskSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkle16Regular", "󰧳", 1, 16));
exports.DeskSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkle16Filled", "󰩰", 0, 16));
exports.DeskSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkle20Regular", "󰧗", 1, 20));
exports.DeskSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkle20Filled", "󰩔", 0, 20));
exports.DeskSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkle24Regular", "󰧘", 1, 24));
exports.DeskSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DeskSparkle24Filled", "󰩕", 0, 24));
