"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Dialpad48Filled = exports.Dialpad48Regular = exports.Dialpad32Filled = exports.Dialpad32Regular = exports.Dialpad28Filled = exports.Dialpad28Regular = exports.Dialpad24Filled = exports.Dialpad24Regular = exports.Dialpad20Filled = exports.Dialpad20Regular = exports.DialpadRegular = exports.DialpadFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DialpadFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadFilled", "", 2, undefined));
exports.DialpadRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadRegular", "", 2, undefined));
exports.Dialpad20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad20Regular", "", 1, 20));
exports.Dialpad20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad20Filled", "", 0, 20));
exports.Dialpad24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad24Regular", "", 1, 24));
exports.Dialpad24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad24Filled", "", 0, 24));
exports.Dialpad28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad28Regular", "", 1, 28));
exports.Dialpad28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad28Filled", "", 0, 28));
exports.Dialpad32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad32Regular", "", 1, 32));
exports.Dialpad32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad32Filled", "", 0, 32));
exports.Dialpad48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad48Regular", "", 1, 48));
exports.Dialpad48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dialpad48Filled", "", 0, 48));
