"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DialpadOff24Filled = exports.DialpadOff24Regular = exports.DialpadOff20Filled = exports.DialpadOff20Regular = exports.DialpadOffRegular = exports.DialpadOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DialpadOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadOffFilled", "", 2, undefined));
exports.DialpadOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadOffRegular", "", 2, undefined));
exports.DialpadOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadOff20Regular", "", 1, 20));
exports.DialpadOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadOff20Filled", "", 0, 20));
exports.DialpadOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadOff24Regular", "", 1, 24));
exports.DialpadOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DialpadOff24Filled", "", 0, 24));
