"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Diamond48Filled = exports.Diamond48Regular = exports.Diamond32Filled = exports.Diamond32Regular = exports.Diamond28Filled = exports.Diamond28Regular = exports.Diamond24Filled = exports.Diamond24Regular = exports.Diamond20Filled = exports.Diamond20Regular = exports.Diamond16Filled = exports.Diamond16Regular = exports.DiamondRegular = exports.DiamondFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DiamondFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DiamondFilled", "", 2, undefined));
exports.DiamondRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DiamondRegular", "", 2, undefined));
exports.Diamond16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond16Regular", "", 1, 16));
exports.Diamond16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond16Filled", "", 0, 16));
exports.Diamond20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond20Regular", "", 1, 20));
exports.Diamond20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond20Filled", "", 0, 20));
exports.Diamond24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond24Regular", "", 1, 24));
exports.Diamond24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond24Filled", "", 0, 24));
exports.Diamond28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond28Regular", "", 1, 28));
exports.Diamond28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond28Filled", "", 0, 28));
exports.Diamond32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond32Regular", "", 1, 32));
exports.Diamond32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond32Filled", "", 0, 32));
exports.Diamond48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond48Regular", "", 1, 48));
exports.Diamond48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diamond48Filled", "", 0, 48));
