"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Dishwasher48Filled = exports.Dishwasher48Regular = exports.Dishwasher32Filled = exports.Dishwasher32Regular = exports.Dishwasher24Filled = exports.Dishwasher24Regular = exports.Dishwasher20Filled = exports.Dishwasher20Regular = exports.DishwasherRegular = exports.DishwasherFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DishwasherFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DishwasherFilled", "", 2, undefined));
exports.DishwasherRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DishwasherRegular", "", 2, undefined));
exports.Dishwasher20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher20Regular", "", 1, 20));
exports.Dishwasher20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher20Filled", "", 0, 20));
exports.Dishwasher24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher24Regular", "", 1, 24));
exports.Dishwasher24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher24Filled", "", 0, 24));
exports.Dishwasher32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher32Regular", "", 1, 32));
exports.Dishwasher32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher32Filled", "", 0, 32));
exports.Dishwasher48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher48Regular", "", 1, 48));
exports.Dishwasher48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Dishwasher48Filled", "", 0, 48));
