"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DismissCircle48Filled = exports.DismissCircle48Regular = exports.DismissCircle32Light = exports.DismissCircle32Filled = exports.DismissCircle32Regular = exports.DismissCircle28Filled = exports.DismissCircle28Regular = exports.DismissCircle24Filled = exports.DismissCircle24Regular = exports.DismissCircle20Filled = exports.DismissCircle20Regular = exports.DismissCircle16Filled = exports.DismissCircle16Regular = exports.DismissCircle12Filled = exports.DismissCircle12Regular = exports.DismissCircleRegular = exports.DismissCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DismissCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircleFilled", "", 2, undefined));
exports.DismissCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircleRegular", "", 2, undefined));
exports.DismissCircle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle12Regular", "", 1, 12));
exports.DismissCircle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle12Filled", "", 0, 12));
exports.DismissCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle16Regular", "", 1, 16));
exports.DismissCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle16Filled", "", 0, 16));
exports.DismissCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle20Regular", "", 1, 20));
exports.DismissCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle20Filled", "", 0, 20));
exports.DismissCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle24Regular", "", 1, 24));
exports.DismissCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle24Filled", "", 0, 24));
exports.DismissCircle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle28Regular", "", 1, 28));
exports.DismissCircle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle28Filled", "", 0, 28));
exports.DismissCircle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle32Regular", "", 1, 32));
exports.DismissCircle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle32Filled", "", 0, 32));
exports.DismissCircle32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle32Light", "", 3, 32));
exports.DismissCircle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle48Regular", "", 1, 48));
exports.DismissCircle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissCircle48Filled", "", 0, 48));
