"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DismissSquare48Filled = exports.DismissSquare48Regular = exports.DismissSquare32Light = exports.DismissSquare32Filled = exports.DismissSquare32Regular = exports.DismissSquare28Filled = exports.DismissSquare28Regular = exports.DismissSquare24Filled = exports.DismissSquare24Regular = exports.DismissSquare20Filled = exports.DismissSquare20Regular = exports.DismissSquareRegular = exports.DismissSquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DismissSquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquareFilled", "", 2, undefined));
exports.DismissSquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquareRegular", "", 2, undefined));
exports.DismissSquare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare20Regular", "", 1, 20));
exports.DismissSquare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare20Filled", "", 0, 20));
exports.DismissSquare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare24Regular", "", 1, 24));
exports.DismissSquare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare24Filled", "", 0, 24));
exports.DismissSquare28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare28Regular", "󰫛", 1, 28));
exports.DismissSquare28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare28Filled", "󰭙", 0, 28));
exports.DismissSquare32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare32Regular", "󰫜", 1, 32));
exports.DismissSquare32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare32Filled", "󰭚", 0, 32));
exports.DismissSquare32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare32Light", "", 3, 32));
exports.DismissSquare48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare48Regular", "󰫝", 1, 48));
exports.DismissSquare48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DismissSquare48Filled", "󰭛", 0, 48));
