"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Diversity48Filled = exports.Diversity48Regular = exports.Diversity28Filled = exports.Diversity28Regular = exports.Diversity24Filled = exports.Diversity24Regular = exports.Diversity20Filled = exports.Diversity20Regular = exports.Diversity16Filled = exports.Diversity16Regular = exports.DiversityRegular = exports.DiversityFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DiversityFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DiversityFilled", "", 2, undefined));
exports.DiversityRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DiversityRegular", "", 2, undefined));
exports.Diversity16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity16Regular", "󰐱", 1, 16));
exports.Diversity16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity16Filled", "󰑄", 0, 16));
exports.Diversity20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity20Regular", "", 1, 20));
exports.Diversity20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity20Filled", "", 0, 20));
exports.Diversity24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity24Regular", "", 1, 24));
exports.Diversity24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity24Filled", "", 0, 24));
exports.Diversity28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity28Regular", "", 1, 28));
exports.Diversity28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity28Filled", "", 0, 28));
exports.Diversity48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity48Regular", "", 1, 48));
exports.Diversity48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Diversity48Filled", "", 0, 48));
