"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DividerShort24Filled = exports.DividerShort24Regular = exports.DividerShort20Filled = exports.DividerShort20Regular = exports.DividerShort16Filled = exports.DividerShort16Regular = exports.DividerShortRegular = exports.DividerShortFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DividerShortFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShortFilled", "", 2, undefined));
exports.DividerShortRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShortRegular", "", 2, undefined));
exports.DividerShort16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShort16Regular", "", 1, 16));
exports.DividerShort16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShort16Filled", "", 0, 16));
exports.DividerShort20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShort20Regular", "", 1, 20));
exports.DividerShort20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShort20Filled", "", 0, 20));
exports.DividerShort24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShort24Regular", "", 1, 24));
exports.DividerShort24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DividerShort24Filled", "", 0, 24));
