"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DockRow24Filled = exports.DockRow24Regular = exports.DockRow20Filled = exports.DockRow20Regular = exports.DockRowRegular = exports.DockRowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DockRowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DockRowFilled", "", 2, undefined));
exports.DockRowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DockRowRegular", "", 2, undefined));
exports.DockRow20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DockRow20Regular", "", 1, 20));
exports.DockRow20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DockRow20Filled", "", 0, 20));
exports.DockRow24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DockRow24Regular", "", 1, 24));
exports.DockRow24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DockRow24Filled", "", 0, 24));
