"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Doctor48Filled = exports.Doctor48Regular = exports.Doctor28Filled = exports.Doctor28Regular = exports.Doctor24Filled = exports.Doctor24Regular = exports.Doctor20Filled = exports.Doctor20Regular = exports.Doctor16Filled = exports.Doctor16Regular = exports.Doctor12Filled = exports.Doctor12Regular = exports.DoctorRegular = exports.DoctorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DoctorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DoctorFilled", "", 2, undefined));
exports.DoctorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DoctorRegular", "", 2, undefined));
exports.Doctor12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor12Regular", "", 1, 12));
exports.Doctor12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor12Filled", "", 0, 12));
exports.Doctor16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor16Regular", "", 1, 16));
exports.Doctor16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor16Filled", "", 0, 16));
exports.Doctor20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor20Regular", "", 1, 20));
exports.Doctor20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor20Filled", "", 0, 20));
exports.Doctor24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor24Regular", "", 1, 24));
exports.Doctor24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor24Filled", "", 0, 24));
exports.Doctor28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor28Regular", "", 1, 28));
exports.Doctor28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor28Filled", "", 0, 28));
exports.Doctor48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor48Regular", "", 1, 48));
exports.Doctor48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Doctor48Filled", "", 0, 48));
