"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentPercent24Filled = exports.DocumentPercent24Regular = exports.DocumentPercent20Filled = exports.DocumentPercent20Regular = exports.DocumentPercentRegular = exports.DocumentPercentFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentPercentFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPercentFilled", "", 2, undefined));
exports.DocumentPercentRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPercentRegular", "", 2, undefined));
exports.DocumentPercent20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPercent20Regular", "", 1, 20));
exports.DocumentPercent20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPercent20Filled", "", 0, 20));
exports.DocumentPercent24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPercent24Regular", "", 1, 24));
exports.DocumentPercent24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPercent24Filled", "", 0, 24));
