"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentDismiss24Filled = exports.DocumentDismiss24Regular = exports.DocumentDismiss20Filled = exports.DocumentDismiss20Regular = exports.DocumentDismiss16Filled = exports.DocumentDismiss16Regular = exports.DocumentDismissRegular = exports.DocumentDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismissFilled", "", 2, undefined));
exports.DocumentDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismissRegular", "", 2, undefined));
exports.DocumentDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismiss16Regular", "", 1, 16));
exports.DocumentDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismiss16Filled", "", 0, 16));
exports.DocumentDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismiss20Regular", "", 1, 20));
exports.DocumentDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismiss20Filled", "", 0, 20));
exports.DocumentDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismiss24Regular", "", 1, 24));
exports.DocumentDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDismiss24Filled", "", 0, 24));
