"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentPrint48Filled = exports.DocumentPrint48Regular = exports.DocumentPrint32Filled = exports.DocumentPrint32Regular = exports.DocumentPrint28Filled = exports.DocumentPrint28Regular = exports.DocumentPrint24Filled = exports.DocumentPrint24Regular = exports.DocumentPrint20Filled = exports.DocumentPrint20Regular = exports.DocumentPrintRegular = exports.DocumentPrintFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentPrintFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrintFilled", "", 2, undefined));
exports.DocumentPrintRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrintRegular", "", 2, undefined));
exports.DocumentPrint20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint20Regular", "󰀮", 1, 20));
exports.DocumentPrint20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint20Filled", "󰀲", 0, 20));
exports.DocumentPrint24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint24Regular", "󰀯", 1, 24));
exports.DocumentPrint24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint24Filled", "󰀳", 0, 24));
exports.DocumentPrint28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint28Regular", "󰀰", 1, 28));
exports.DocumentPrint28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint28Filled", "󰀴", 0, 28));
exports.DocumentPrint32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint32Regular", "󰀱", 1, 32));
exports.DocumentPrint32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint32Filled", "󰀵", 0, 32));
exports.DocumentPrint48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint48Regular", "󰀲", 1, 48));
exports.DocumentPrint48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentPrint48Filled", "󰀶", 0, 48));
