"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentMargins24Filled = exports.DocumentMargins24Regular = exports.DocumentMargins20Filled = exports.DocumentMargins20Regular = exports.DocumentMarginsRegular = exports.DocumentMarginsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentMarginsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMarginsFilled", "", 2, undefined));
exports.DocumentMarginsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMarginsRegular", "", 2, undefined));
exports.DocumentMargins20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMargins20Regular", "", 1, 20));
exports.DocumentMargins20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMargins20Filled", "", 0, 20));
exports.DocumentMargins24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMargins24Regular", "", 1, 24));
exports.DocumentMargins24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMargins24Filled", "", 0, 24));
