"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentSass20Filled = exports.DocumentSass20Regular = exports.DocumentSass16Filled = exports.DocumentSass16Regular = exports.DocumentSassRegular = exports.DocumentSassFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentSassFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSassFilled", "", 2, undefined));
exports.DocumentSassRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSassRegular", "", 2, undefined));
exports.DocumentSass16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSass16Regular", "󰅽", 1, 16));
exports.DocumentSass16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSass16Filled", "󰅽", 0, 16));
exports.DocumentSass20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSass20Regular", "󰅾", 1, 20));
exports.DocumentSass20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSass20Filled", "󰅾", 0, 20));
