"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentWidth24Filled = exports.DocumentWidth24Regular = exports.DocumentWidth20Filled = exports.DocumentWidth20Regular = exports.DocumentWidthRegular = exports.DocumentWidthFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentWidthFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentWidthFilled", "", 2, undefined));
exports.DocumentWidthRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentWidthRegular", "", 2, undefined));
exports.DocumentWidth20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentWidth20Regular", "", 1, 20));
exports.DocumentWidth20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentWidth20Filled", "", 0, 20));
exports.DocumentWidth24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentWidth24Regular", "", 1, 24));
exports.DocumentWidth24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentWidth24Filled", "", 0, 24));
