"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentError24Filled = exports.DocumentError24Regular = exports.DocumentError20Filled = exports.DocumentError20Regular = exports.DocumentError16Filled = exports.DocumentError16Regular = exports.DocumentErrorRegular = exports.DocumentErrorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentErrorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentErrorFilled", "", 2, undefined));
exports.DocumentErrorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentErrorRegular", "", 2, undefined));
exports.DocumentError16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentError16Regular", "", 1, 16));
exports.DocumentError16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentError16Filled", "", 0, 16));
exports.DocumentError20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentError20Regular", "", 1, 20));
exports.DocumentError20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentError20Filled", "", 0, 20));
exports.DocumentError24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentError24Regular", "", 1, 24));
exports.DocumentError24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentError24Filled", "", 0, 24));
