"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentTable24Filled = exports.DocumentTable24Regular = exports.DocumentTable20Filled = exports.DocumentTable20Regular = exports.DocumentTable16Filled = exports.DocumentTable16Regular = exports.DocumentTableRegular = exports.DocumentTableFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentTableFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTableFilled", "", 2, undefined));
exports.DocumentTableRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTableRegular", "", 2, undefined));
exports.DocumentTable16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTable16Regular", "", 1, 16));
exports.DocumentTable16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTable16Filled", "", 0, 16));
exports.DocumentTable20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTable20Regular", "", 1, 20));
exports.DocumentTable20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTable20Filled", "", 0, 20));
exports.DocumentTable24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTable24Regular", "", 1, 24));
exports.DocumentTable24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTable24Filled", "", 0, 24));
