"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentMention48Filled = exports.DocumentMention48Regular = exports.DocumentMention28Filled = exports.DocumentMention28Regular = exports.DocumentMention24Filled = exports.DocumentMention24Regular = exports.DocumentMention20Filled = exports.DocumentMention20Regular = exports.DocumentMention16Filled = exports.DocumentMention16Regular = exports.DocumentMentionRegular = exports.DocumentMentionFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentMentionFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMentionFilled", "", 2, undefined));
exports.DocumentMentionRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMentionRegular", "", 2, undefined));
exports.DocumentMention16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention16Regular", "", 1, 16));
exports.DocumentMention16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention16Filled", "", 0, 16));
exports.DocumentMention20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention20Regular", "", 1, 20));
exports.DocumentMention20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention20Filled", "", 0, 20));
exports.DocumentMention24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention24Regular", "", 1, 24));
exports.DocumentMention24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention24Filled", "", 0, 24));
exports.DocumentMention28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention28Regular", "", 1, 28));
exports.DocumentMention28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention28Filled", "", 0, 28));
exports.DocumentMention48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention48Regular", "", 1, 48));
exports.DocumentMention48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentMention48Filled", "", 0, 48));
