"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentCopy48Filled = exports.DocumentCopy48Regular = exports.DocumentCopy24Filled = exports.DocumentCopy24Regular = exports.DocumentCopy20Filled = exports.DocumentCopy20Regular = exports.DocumentCopy16Filled = exports.DocumentCopy16Regular = exports.DocumentCopyRegular = exports.DocumentCopyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentCopyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopyFilled", "", 2, undefined));
exports.DocumentCopyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopyRegular", "", 2, undefined));
exports.DocumentCopy16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy16Regular", "", 1, 16));
exports.DocumentCopy16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy16Filled", "", 0, 16));
exports.DocumentCopy20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy20Regular", "", 1, 20));
exports.DocumentCopy20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy20Filled", "", 0, 20));
exports.DocumentCopy24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy24Regular", "", 1, 24));
exports.DocumentCopy24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy24Filled", "", 0, 24));
exports.DocumentCopy48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy48Regular", "", 1, 48));
exports.DocumentCopy48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentCopy48Filled", "", 0, 48));
