"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentData32Filled = exports.DocumentData32Regular = exports.DocumentData24Filled = exports.DocumentData24Regular = exports.DocumentData20Filled = exports.DocumentData20Regular = exports.DocumentData16Filled = exports.DocumentData16Regular = exports.DocumentDataRegular = exports.DocumentDataFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentDataFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDataFilled", "", 2, undefined));
exports.DocumentDataRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentDataRegular", "", 2, undefined));
exports.DocumentData16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData16Regular", "", 1, 16));
exports.DocumentData16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData16Filled", "", 0, 16));
exports.DocumentData20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData20Regular", "", 1, 20));
exports.DocumentData20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData20Filled", "", 0, 20));
exports.DocumentData24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData24Regular", "", 1, 24));
exports.DocumentData24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData24Filled", "", 0, 24));
exports.DocumentData32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData32Regular", "", 1, 32));
exports.DocumentData32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentData32Filled", "", 0, 32));
