"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentSync32Filled = exports.DocumentSync32Regular = exports.DocumentSync24Filled = exports.DocumentSync24Regular = exports.DocumentSync20Filled = exports.DocumentSync20Regular = exports.DocumentSync16Filled = exports.DocumentSync16Regular = exports.DocumentSyncRegular = exports.DocumentSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSyncFilled", "", 2, undefined));
exports.DocumentSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSyncRegular", "", 2, undefined));
exports.DocumentSync16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync16Regular", "", 1, 16));
exports.DocumentSync16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync16Filled", "", 0, 16));
exports.DocumentSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync20Regular", "", 1, 20));
exports.DocumentSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync20Filled", "", 0, 20));
exports.DocumentSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync24Regular", "", 1, 24));
exports.DocumentSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync24Filled", "", 0, 24));
exports.DocumentSync32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync32Regular", "", 1, 32));
exports.DocumentSync32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSync32Filled", "", 0, 32));
