"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentSearch32Filled = exports.DocumentSearch32Regular = exports.DocumentSearch24Filled = exports.DocumentSearch24Regular = exports.DocumentSearch20Filled = exports.DocumentSearch20Regular = exports.DocumentSearch16Filled = exports.DocumentSearch16Regular = exports.DocumentSearchRegular = exports.DocumentSearchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentSearchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearchFilled", "", 2, undefined));
exports.DocumentSearchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearchRegular", "", 2, undefined));
exports.DocumentSearch16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch16Regular", "", 1, 16));
exports.DocumentSearch16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch16Filled", "", 0, 16));
exports.DocumentSearch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch20Regular", "", 1, 20));
exports.DocumentSearch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch20Filled", "", 0, 20));
exports.DocumentSearch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch24Regular", "", 1, 24));
exports.DocumentSearch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch24Filled", "", 0, 24));
exports.DocumentSearch32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch32Regular", "󰏸", 1, 32));
exports.DocumentSearch32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSearch32Filled", "󰐋", 0, 32));
