"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentRibbon48Filled = exports.DocumentRibbon48Regular = exports.DocumentRibbon32Filled = exports.DocumentRibbon32Regular = exports.DocumentRibbon28Filled = exports.DocumentRibbon28Regular = exports.DocumentRibbon24Filled = exports.DocumentRibbon24Regular = exports.DocumentRibbon20Filled = exports.DocumentRibbon20Regular = exports.DocumentRibbon16Filled = exports.DocumentRibbon16Regular = exports.DocumentRibbonRegular = exports.DocumentRibbonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentRibbonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbonFilled", "", 2, undefined));
exports.DocumentRibbonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbonRegular", "", 2, undefined));
exports.DocumentRibbon16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon16Regular", "", 1, 16));
exports.DocumentRibbon16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon16Filled", "", 0, 16));
exports.DocumentRibbon20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon20Regular", "", 1, 20));
exports.DocumentRibbon20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon20Filled", "", 0, 20));
exports.DocumentRibbon24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon24Regular", "", 1, 24));
exports.DocumentRibbon24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon24Filled", "", 0, 24));
exports.DocumentRibbon28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon28Regular", "", 1, 28));
exports.DocumentRibbon28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon28Filled", "", 0, 28));
exports.DocumentRibbon32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon32Regular", "", 1, 32));
exports.DocumentRibbon32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon32Filled", "", 0, 32));
exports.DocumentRibbon48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon48Regular", "", 1, 48));
exports.DocumentRibbon48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentRibbon48Filled", "", 0, 48));
