"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentImage20Filled = exports.DocumentImage20Regular = exports.DocumentImage16Filled = exports.DocumentImage16Regular = exports.DocumentImageRegular = exports.DocumentImageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentImageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentImageFilled", "", 2, undefined));
exports.DocumentImageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentImageRegular", "", 2, undefined));
exports.DocumentImage16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentImage16Regular", "󰅵", 1, 16));
exports.DocumentImage16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentImage16Filled", "󰅵", 0, 16));
exports.DocumentImage20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentImage20Regular", "󰅶", 1, 20));
exports.DocumentImage20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentImage20Filled", "󰅶", 0, 20));
