"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentText48Filled = exports.DocumentText48Regular = exports.DocumentText32Filled = exports.DocumentText32Regular = exports.DocumentText28Filled = exports.DocumentText28Regular = exports.DocumentText24Filled = exports.DocumentText24Regular = exports.DocumentText20Filled = exports.DocumentText20Regular = exports.DocumentText16Filled = exports.DocumentText16Regular = exports.DocumentTextRegular = exports.DocumentTextFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentTextFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTextFilled", "", 2, undefined));
exports.DocumentTextRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentTextRegular", "", 2, undefined));
exports.DocumentText16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText16Regular", "", 1, 16));
exports.DocumentText16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText16Filled", "", 0, 16));
exports.DocumentText20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText20Regular", "", 1, 20));
exports.DocumentText20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText20Filled", "", 0, 20));
exports.DocumentText24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText24Regular", "", 1, 24));
exports.DocumentText24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText24Filled", "", 0, 24));
exports.DocumentText28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText28Regular", "󰜱", 1, 28));
exports.DocumentText28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText28Filled", "󰞮", 0, 28));
exports.DocumentText32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText32Regular", "󰜲", 1, 32));
exports.DocumentText32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText32Filled", "󰞯", 0, 32));
exports.DocumentText48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText48Regular", "󰜳", 1, 48));
exports.DocumentText48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentText48Filled", "󰞰", 0, 48));
