"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentToolbox24Filled = exports.DocumentToolbox24Regular = exports.DocumentToolbox20Filled = exports.DocumentToolbox20Regular = exports.DocumentToolboxRegular = exports.DocumentToolboxFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentToolboxFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentToolboxFilled", "", 2, undefined));
exports.DocumentToolboxRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentToolboxRegular", "", 2, undefined));
exports.DocumentToolbox20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentToolbox20Regular", "", 1, 20));
exports.DocumentToolbox20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentToolbox20Filled", "", 0, 20));
exports.DocumentToolbox24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentToolbox24Regular", "", 1, 24));
exports.DocumentToolbox24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentToolbox24Filled", "", 0, 24));
