"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentSparkle48Light = exports.DocumentSparkle48Filled = exports.DocumentSparkle48Regular = exports.DocumentSparkle32Light = exports.DocumentSparkle32Filled = exports.DocumentSparkle32Regular = exports.DocumentSparkle28Light = exports.DocumentSparkle28Filled = exports.DocumentSparkle28Regular = exports.DocumentSparkle24Light = exports.DocumentSparkle24Filled = exports.DocumentSparkle24Regular = exports.DocumentSparkle20Filled = exports.DocumentSparkle20Regular = exports.DocumentSparkle16Filled = exports.DocumentSparkle16Regular = exports.DocumentSparkleRegular = exports.DocumentSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkleFilled", "", 2, undefined));
exports.DocumentSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkleRegular", "", 2, undefined));
exports.DocumentSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle16Regular", "󰟖", 1, 16));
exports.DocumentSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle16Filled", "󰡓", 0, 16));
exports.DocumentSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle20Regular", "󰟗", 1, 20));
exports.DocumentSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle20Filled", "󰡔", 0, 20));
exports.DocumentSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle24Regular", "󰟘", 1, 24));
exports.DocumentSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle24Filled", "󰡕", 0, 24));
exports.DocumentSparkle24Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle24Light", "", 3, 24));
exports.DocumentSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle28Regular", "󰟙", 1, 28));
exports.DocumentSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle28Filled", "󰡖", 0, 28));
exports.DocumentSparkle28Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle28Light", "", 3, 28));
exports.DocumentSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle32Regular", "󰟚", 1, 32));
exports.DocumentSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle32Filled", "󰡗", 0, 32));
exports.DocumentSparkle32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle32Light", "", 3, 32));
exports.DocumentSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle48Regular", "󰟛", 1, 48));
exports.DocumentSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle48Filled", "󰡘", 0, 48));
exports.DocumentSparkle48Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSparkle48Light", "", 3, 48));
