"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentSave24Filled = exports.DocumentSave24Regular = exports.DocumentSave20Filled = exports.DocumentSave20Regular = exports.DocumentSaveRegular = exports.DocumentSaveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentSaveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSaveFilled", "", 2, undefined));
exports.DocumentSaveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSaveRegular", "", 2, undefined));
exports.DocumentSave20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSave20Regular", "", 1, 20));
exports.DocumentSave20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSave20Filled", "", 0, 20));
exports.DocumentSave24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSave24Regular", "", 1, 24));
exports.DocumentSave24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentSave24Filled", "", 0, 24));
