"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentFit24Filled = exports.DocumentFit24Regular = exports.DocumentFit20Filled = exports.DocumentFit20Regular = exports.DocumentFit16Filled = exports.DocumentFit16Regular = exports.DocumentFitRegular = exports.DocumentFitFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentFitFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFitFilled", "", 2, undefined));
exports.DocumentFitRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFitRegular", "", 2, undefined));
exports.DocumentFit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFit16Regular", "󰀟", 1, 16));
exports.DocumentFit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFit16Filled", "󰀣", 0, 16));
exports.DocumentFit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFit20Regular", "󰀠", 1, 20));
exports.DocumentFit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFit20Filled", "󰀤", 0, 20));
exports.DocumentFit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFit24Regular", "󰀡", 1, 24));
exports.DocumentFit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentFit24Filled", "󰀥", 0, 24));
