"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentYml20Filled = exports.DocumentYml20Regular = exports.DocumentYml16Filled = exports.DocumentYml16Regular = exports.DocumentYmlRegular = exports.DocumentYmlFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentYmlFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentYmlFilled", "", 2, undefined));
exports.DocumentYmlRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentYmlRegular", "", 2, undefined));
exports.DocumentYml16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentYml16Regular", "󰅿", 1, 16));
exports.DocumentYml16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentYml16Filled", "󰅿", 0, 16));
exports.DocumentYml20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentYml20Regular", "󰆀", 1, 20));
exports.DocumentYml20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentYml20Filled", "󰆀", 0, 20));
