"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentEndnote24Filled = exports.DocumentEndnote24Regular = exports.DocumentEndnote20Filled = exports.DocumentEndnote20Regular = exports.DocumentEndnoteRegular = exports.DocumentEndnoteFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DocumentEndnoteFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentEndnoteFilled", "", 2, undefined));
exports.DocumentEndnoteRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentEndnoteRegular", "", 2, undefined));
exports.DocumentEndnote20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentEndnote20Regular", "", 1, 20));
exports.DocumentEndnote20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentEndnote20Filled", "", 0, 20));
exports.DocumentEndnote24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentEndnote24Regular", "", 1, 24));
exports.DocumentEndnote24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DocumentEndnote24Filled", "", 0, 24));
