"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Door32Filled = exports.Door32Regular = exports.Door28Filled = exports.Door28Regular = exports.Door24Filled = exports.Door24Regular = exports.Door20Filled = exports.Door20Regular = exports.Door16Filled = exports.Door16Regular = exports.DoorRegular = exports.DoorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DoorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DoorFilled", "", 2, undefined));
exports.DoorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DoorRegular", "", 2, undefined));
exports.Door16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door16Regular", "", 1, 16));
exports.Door16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door16Filled", "", 0, 16));
exports.Door20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door20Regular", "", 1, 20));
exports.Door20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door20Filled", "", 0, 20));
exports.Door24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door24Regular", "󰦺", 1, 24));
exports.Door24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door24Filled", "󰨷", 0, 24));
exports.Door28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door28Regular", "", 1, 28));
exports.Door28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door28Filled", "", 0, 28));
exports.Door32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door32Regular", "󰦻", 1, 32));
exports.Door32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Door32Filled", "󰨸", 0, 32));
