"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Drag24Filled = exports.Drag24Regular = exports.Drag20Filled = exports.Drag20Regular = exports.DragRegular = exports.DragFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DragFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DragFilled", "", 2, undefined));
exports.DragRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DragRegular", "", 2, undefined));
exports.Drag20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Drag20Regular", "", 1, 20));
exports.Drag20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Drag20Filled", "", 0, 20));
exports.Drag24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Drag24Regular", "", 1, 24));
exports.Drag24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Drag24Filled", "", 0, 24));
