"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrawerAdd24Filled = exports.DrawerAdd24Regular = exports.DrawerAdd20Filled = exports.DrawerAdd20Regular = exports.DrawerAddRegular = exports.DrawerAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrawerAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerAddFilled", "", 2, undefined));
exports.DrawerAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerAddRegular", "", 2, undefined));
exports.DrawerAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerAdd20Regular", "", 1, 20));
exports.DrawerAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerAdd20Filled", "", 0, 20));
exports.DrawerAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerAdd24Regular", "", 1, 24));
exports.DrawerAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerAdd24Filled", "", 0, 24));
