"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrawerDismiss24Filled = exports.DrawerDismiss24Regular = exports.DrawerDismiss20Filled = exports.DrawerDismiss20Regular = exports.DrawerDismissRegular = exports.DrawerDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrawerDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerDismissFilled", "", 2, undefined));
exports.DrawerDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerDismissRegular", "", 2, undefined));
exports.DrawerDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerDismiss20Regular", "", 1, 20));
exports.DrawerDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerDismiss20Filled", "", 0, 20));
exports.DrawerDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerDismiss24Regular", "", 1, 24));
exports.DrawerDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerDismiss24Filled", "", 0, 24));
