"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrawerPlay24Filled = exports.DrawerPlay24Regular = exports.DrawerPlay20Filled = exports.DrawerPlay20Regular = exports.DrawerPlayRegular = exports.DrawerPlayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrawerPlayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerPlayFilled", "", 2, undefined));
exports.DrawerPlayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerPlayRegular", "", 2, undefined));
exports.DrawerPlay20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerPlay20Regular", "", 1, 20));
exports.DrawerPlay20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerPlay20Filled", "", 0, 20));
exports.DrawerPlay24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerPlay24Regular", "", 1, 24));
exports.DrawerPlay24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrawerPlay24Filled", "", 0, 24));
