"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrinkWine24Filled = exports.DrinkWine24Regular = exports.DrinkWine20Filled = exports.DrinkWine20Regular = exports.DrinkWine16Filled = exports.DrinkWine16Regular = exports.DrinkWineRegular = exports.DrinkWineFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrinkWineFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWineFilled", "", 2, undefined));
exports.DrinkWineRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWineRegular", "", 2, undefined));
exports.DrinkWine16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWine16Regular", "", 1, 16));
exports.DrinkWine16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWine16Filled", "", 0, 16));
exports.DrinkWine20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWine20Regular", "", 1, 20));
exports.DrinkWine20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWine20Filled", "", 0, 20));
exports.DrinkWine24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWine24Regular", "", 1, 24));
exports.DrinkWine24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkWine24Filled", "", 0, 24));
