"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrinkToGo24Filled = exports.DrinkToGo24Regular = exports.DrinkToGo20Filled = exports.DrinkToGo20Regular = exports.DrinkToGoRegular = exports.DrinkToGoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrinkToGoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkToGoFilled", "", 2, undefined));
exports.DrinkToGoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkToGoRegular", "", 2, undefined));
exports.DrinkToGo20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkToGo20Regular", "", 1, 20));
exports.DrinkToGo20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkToGo20Filled", "", 0, 20));
exports.DrinkToGo24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkToGo24Regular", "", 1, 24));
exports.DrinkToGo24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkToGo24Filled", "", 0, 24));
