"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrinkBottle32Filled = exports.DrinkBottle32Regular = exports.DrinkBottle20Filled = exports.DrinkBottle20Regular = exports.DrinkBottleRegular = exports.DrinkBottleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrinkBottleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBottleFilled", "", 2, undefined));
exports.DrinkBottleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBottleRegular", "", 2, undefined));
exports.DrinkBottle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBottle20Regular", "", 1, 20));
exports.DrinkBottle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBottle20Filled", "", 0, 20));
exports.DrinkBottle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBottle32Regular", "", 1, 32));
exports.DrinkBottle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBottle32Filled", "", 0, 32));
