"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrinkBeer24Filled = exports.DrinkBeer24Regular = exports.DrinkBeer20Filled = exports.DrinkBeer20Regular = exports.DrinkBeer16Filled = exports.DrinkBeer16Regular = exports.DrinkBeerRegular = exports.DrinkBeerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrinkBeerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeerFilled", "", 2, undefined));
exports.DrinkBeerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeerRegular", "", 2, undefined));
exports.DrinkBeer16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeer16Regular", "", 1, 16));
exports.DrinkBeer16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeer16Filled", "", 0, 16));
exports.DrinkBeer20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeer20Regular", "", 1, 20));
exports.DrinkBeer20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeer20Filled", "", 0, 20));
exports.DrinkBeer24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeer24Regular", "", 1, 24));
exports.DrinkBeer24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkBeer24Filled", "", 0, 24));
