"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DrinkCoffee24Filled = exports.DrinkCoffee24Regular = exports.DrinkCoffee20Filled = exports.DrinkCoffee20Regular = exports.DrinkCoffee16Filled = exports.DrinkCoffee16Regular = exports.DrinkCoffeeRegular = exports.DrinkCoffeeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DrinkCoffeeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffeeFilled", "", 2, undefined));
exports.DrinkCoffeeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffeeRegular", "", 2, undefined));
exports.DrinkCoffee16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffee16Regular", "", 1, 16));
exports.DrinkCoffee16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffee16Filled", "", 0, 16));
exports.DrinkCoffee20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffee20Regular", "", 1, 20));
exports.DrinkCoffee20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffee20Filled", "", 0, 20));
exports.DrinkCoffee24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffee24Regular", "", 1, 24));
exports.DrinkCoffee24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DrinkCoffee24Filled", "", 0, 24));
