"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DriveTrain24Filled = exports.DriveTrain24Regular = exports.DriveTrain20Filled = exports.DriveTrain20Regular = exports.DriveTrainRegular = exports.DriveTrainFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DriveTrainFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DriveTrainFilled", "", 2, undefined));
exports.DriveTrainRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DriveTrainRegular", "", 2, undefined));
exports.DriveTrain20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DriveTrain20Regular", "", 1, 20));
exports.DriveTrain20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DriveTrain20Filled", "", 0, 20));
exports.DriveTrain24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DriveTrain24Regular", "", 1, 24));
exports.DriveTrain24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DriveTrain24Filled", "", 0, 24));
