"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DualScreen24Filled = exports.DualScreen24Regular = exports.DualScreen20Filled = exports.DualScreen20Regular = exports.DualScreenRegular = exports.DualScreenFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.DualScreenFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DualScreenFilled", "", 2, undefined));
exports.DualScreenRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DualScreenRegular", "", 2, undefined));
exports.DualScreen20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DualScreen20Regular", "", 1, 20));
exports.DualScreen20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DualScreen20Filled", "", 0, 20));
exports.DualScreen24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DualScreen24Regular", "", 1, 24));
exports.DualScreen24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("DualScreen24Filled", "", 0, 24));
