"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EarthLeaf48Filled = exports.EarthLeaf48Regular = exports.EarthLeaf32Filled = exports.EarthLeaf32Regular = exports.EarthLeaf24Filled = exports.EarthLeaf24Regular = exports.EarthLeaf20Filled = exports.EarthLeaf20Regular = exports.EarthLeaf16Filled = exports.EarthLeaf16Regular = exports.EarthLeafRegular = exports.EarthLeafFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EarthLeafFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeafFilled", "", 2, undefined));
exports.EarthLeafRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeafRegular", "", 2, undefined));
exports.EarthLeaf16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf16Regular", "", 1, 16));
exports.EarthLeaf16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf16Filled", "", 0, 16));
exports.EarthLeaf20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf20Regular", "", 1, 20));
exports.EarthLeaf20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf20Filled", "", 0, 20));
exports.EarthLeaf24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf24Regular", "", 1, 24));
exports.EarthLeaf24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf24Filled", "", 0, 24));
exports.EarthLeaf32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf32Regular", "", 1, 32));
exports.EarthLeaf32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf32Filled", "", 0, 32));
exports.EarthLeaf48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf48Regular", "", 1, 48));
exports.EarthLeaf48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EarthLeaf48Filled", "", 0, 48));
