"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EditPerson24Filled = exports.EditPerson24Regular = exports.EditPerson20Filled = exports.EditPerson20Regular = exports.EditPerson16Filled = exports.EditPerson16Regular = exports.EditPersonRegular = exports.EditPersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EditPersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPersonFilled", "", 2, undefined));
exports.EditPersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPersonRegular", "", 2, undefined));
exports.EditPerson16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPerson16Regular", "󰡌", 1, 16));
exports.EditPerson16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPerson16Filled", "󰣉", 0, 16));
exports.EditPerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPerson20Regular", "󰕧", 1, 20));
exports.EditPerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPerson20Filled", "󰗠", 0, 20));
exports.EditPerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPerson24Regular", "󰕨", 1, 24));
exports.EditPerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditPerson24Filled", "󰗡", 0, 24));
