"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EditOff48Filled = exports.EditOff48Regular = exports.EditOff32Filled = exports.EditOff32Regular = exports.EditOff28Filled = exports.EditOff28Regular = exports.EditOff24Filled = exports.EditOff24Regular = exports.EditOff20Filled = exports.EditOff20Regular = exports.EditOff16Filled = exports.EditOff16Regular = exports.EditOffRegular = exports.EditOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EditOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOffFilled", "", 2, undefined));
exports.EditOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOffRegular", "", 2, undefined));
exports.EditOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff16Regular", "", 1, 16));
exports.EditOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff16Filled", "", 0, 16));
exports.EditOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff20Regular", "", 1, 20));
exports.EditOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff20Filled", "", 0, 20));
exports.EditOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff24Regular", "", 1, 24));
exports.EditOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff24Filled", "", 0, 24));
exports.EditOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff28Regular", "", 1, 28));
exports.EditOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff28Filled", "", 0, 28));
exports.EditOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff32Regular", "", 1, 32));
exports.EditOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff32Filled", "", 0, 32));
exports.EditOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff48Regular", "", 1, 48));
exports.EditOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EditOff48Filled", "", 0, 48));
