"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Elevator48Filled = exports.Elevator48Regular = exports.Elevator32Filled = exports.Elevator32Regular = exports.Elevator24Filled = exports.Elevator24Regular = exports.Elevator20Filled = exports.Elevator20Regular = exports.ElevatorRegular = exports.ElevatorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ElevatorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ElevatorFilled", "", 2, undefined));
exports.ElevatorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ElevatorRegular", "", 2, undefined));
exports.Elevator20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator20Regular", "", 1, 20));
exports.Elevator20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator20Filled", "", 0, 20));
exports.Elevator24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator24Regular", "", 1, 24));
exports.Elevator24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator24Filled", "", 0, 24));
exports.Elevator32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator32Regular", "", 1, 32));
exports.Elevator32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator32Filled", "", 0, 32));
exports.Elevator48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator48Regular", "", 1, 48));
exports.Elevator48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Elevator48Filled", "", 0, 48));
