"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmojiLaugh24Filled = exports.EmojiLaugh24Regular = exports.EmojiLaugh20Filled = exports.EmojiLaugh20Regular = exports.EmojiLaugh16Filled = exports.EmojiLaugh16Regular = exports.EmojiLaughRegular = exports.EmojiLaughFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EmojiLaughFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaughFilled", "", 2, undefined));
exports.EmojiLaughRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaughRegular", "", 2, undefined));
exports.EmojiLaugh16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaugh16Regular", "", 1, 16));
exports.EmojiLaugh16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaugh16Filled", "", 0, 16));
exports.EmojiLaugh20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaugh20Regular", "", 1, 20));
exports.EmojiLaugh20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaugh20Filled", "", 0, 20));
exports.EmojiLaugh24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaugh24Regular", "", 1, 24));
exports.EmojiLaugh24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiLaugh24Filled", "", 0, 24));
