"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Emoji48Filled = exports.Emoji48Regular = exports.Emoji32Light = exports.Emoji32Filled = exports.Emoji32Regular = exports.Emoji28Filled = exports.Emoji28Regular = exports.Emoji24Filled = exports.Emoji24Regular = exports.Emoji20Filled = exports.Emoji20Regular = exports.Emoji16Filled = exports.Emoji16Regular = exports.EmojiRegular = exports.EmojiFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EmojiFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiFilled", "", 2, undefined));
exports.EmojiRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiRegular", "", 2, undefined));
exports.Emoji16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji16Regular", "", 1, 16));
exports.Emoji16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji16Filled", "", 0, 16));
exports.Emoji20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji20Regular", "", 1, 20));
exports.Emoji20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji20Filled", "", 0, 20));
exports.Emoji24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji24Regular", "", 1, 24));
exports.Emoji24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji24Filled", "", 0, 24));
exports.Emoji28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji28Regular", "", 1, 28));
exports.Emoji28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji28Filled", "", 0, 28));
exports.Emoji32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji32Regular", "", 1, 32));
exports.Emoji32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji32Filled", "", 0, 32));
exports.Emoji32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji32Light", "", 3, 32));
exports.Emoji48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji48Regular", "", 1, 48));
exports.Emoji48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Emoji48Filled", "", 0, 48));
