"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmojiHint48Filled = exports.EmojiHint48Regular = exports.EmojiHint32Filled = exports.EmojiHint32Regular = exports.EmojiHint28Filled = exports.EmojiHint28Regular = exports.EmojiHint24Filled = exports.EmojiHint24Regular = exports.EmojiHint20Filled = exports.EmojiHint20Regular = exports.EmojiHint16Filled = exports.EmojiHint16Regular = exports.EmojiHintRegular = exports.EmojiHintFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EmojiHintFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHintFilled", "", 2, undefined));
exports.EmojiHintRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHintRegular", "", 2, undefined));
exports.EmojiHint16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint16Regular", "󰄢", 1, 16));
exports.EmojiHint16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint16Filled", "󰄡", 0, 16));
exports.EmojiHint20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint20Regular", "󰄣", 1, 20));
exports.EmojiHint20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint20Filled", "󰄢", 0, 20));
exports.EmojiHint24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint24Regular", "󰄤", 1, 24));
exports.EmojiHint24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint24Filled", "󰄣", 0, 24));
exports.EmojiHint28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint28Regular", "󰄥", 1, 28));
exports.EmojiHint28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint28Filled", "󰄤", 0, 28));
exports.EmojiHint32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint32Regular", "󰄦", 1, 32));
exports.EmojiHint32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint32Filled", "󰄥", 0, 32));
exports.EmojiHint48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint48Regular", "󰄧", 1, 48));
exports.EmojiHint48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiHint48Filled", "󰄦", 0, 48));
