"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmojiSparkle48Filled = exports.EmojiSparkle48Regular = exports.EmojiSparkle32Filled = exports.EmojiSparkle32Regular = exports.EmojiSparkle28Filled = exports.EmojiSparkle28Regular = exports.EmojiSparkle24Filled = exports.EmojiSparkle24Regular = exports.EmojiSparkle20Filled = exports.EmojiSparkle20Regular = exports.EmojiSparkle16Filled = exports.EmojiSparkle16Regular = exports.EmojiSparkleRegular = exports.EmojiSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EmojiSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkleFilled", "", 2, undefined));
exports.EmojiSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkleRegular", "", 2, undefined));
exports.EmojiSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle16Regular", "", 1, 16));
exports.EmojiSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle16Filled", "", 0, 16));
exports.EmojiSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle20Regular", "", 1, 20));
exports.EmojiSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle20Filled", "", 0, 20));
exports.EmojiSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle24Regular", "", 1, 24));
exports.EmojiSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle24Filled", "", 0, 24));
exports.EmojiSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle28Regular", "", 1, 28));
exports.EmojiSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle28Filled", "", 0, 28));
exports.EmojiSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle32Regular", "", 1, 32));
exports.EmojiSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle32Filled", "", 0, 32));
exports.EmojiSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle48Regular", "", 1, 48));
exports.EmojiSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiSparkle48Filled", "", 0, 48));
