"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmojiMeh24Filled = exports.EmojiMeh24Regular = exports.EmojiMeh20Filled = exports.EmojiMeh20Regular = exports.EmojiMeh16Filled = exports.EmojiMeh16Regular = exports.EmojiMehRegular = exports.EmojiMehFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EmojiMehFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMehFilled", "", 2, undefined));
exports.EmojiMehRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMehRegular", "", 2, undefined));
exports.EmojiMeh16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeh16Regular", "󰀵", 1, 16));
exports.EmojiMeh16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeh16Filled", "󰀹", 0, 16));
exports.EmojiMeh20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeh20Regular", "", 1, 20));
exports.EmojiMeh20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeh20Filled", "", 0, 20));
exports.EmojiMeh24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeh24Regular", "", 1, 24));
exports.EmojiMeh24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeh24Filled", "", 0, 24));
