"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmojiMeme24Filled = exports.EmojiMeme24Regular = exports.EmojiMeme20Filled = exports.EmojiMeme20Regular = exports.EmojiMeme16Filled = exports.EmojiMeme16Regular = exports.EmojiMemeRegular = exports.EmojiMemeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EmojiMemeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMemeFilled", "", 2, undefined));
exports.EmojiMemeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMemeRegular", "", 2, undefined));
exports.EmojiMeme16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeme16Regular", "󰖄", 1, 16));
exports.EmojiMeme16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeme16Filled", "󰗽", 0, 16));
exports.EmojiMeme20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeme20Regular", "󰖅", 1, 20));
exports.EmojiMeme20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeme20Filled", "󰗾", 0, 20));
exports.EmojiMeme24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeme24Regular", "󰖆", 1, 24));
exports.EmojiMeme24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EmojiMeme24Filled", "󰗿", 0, 24));
