"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Engine24Filled = exports.Engine24Regular = exports.Engine20Filled = exports.Engine20Regular = exports.EngineRegular = exports.EngineFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EngineFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EngineFilled", "", 2, undefined));
exports.EngineRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EngineRegular", "", 2, undefined));
exports.Engine20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Engine20Regular", "", 1, 20));
exports.Engine20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Engine20Filled", "", 0, 20));
exports.Engine24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Engine24Regular", "", 1, 24));
exports.Engine24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Engine24Filled", "", 0, 24));
