"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EraserTool24Filled = exports.EraserTool24Regular = exports.EraserTool20Filled = exports.EraserTool20Regular = exports.EraserToolRegular = exports.EraserToolFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EraserToolFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EraserToolFilled", "", 2, undefined));
exports.EraserToolRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EraserToolRegular", "", 2, undefined));
exports.EraserTool20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EraserTool20Regular", "", 1, 20));
exports.EraserTool20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EraserTool20Filled", "", 0, 20));
exports.EraserTool24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EraserTool24Regular", "", 1, 24));
exports.EraserTool24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EraserTool24Filled", "", 0, 24));
