"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCircle48Filled = exports.ErrorCircle48Regular = exports.ErrorCircle24Filled = exports.ErrorCircle24Regular = exports.ErrorCircle20Filled = exports.ErrorCircle20Regular = exports.ErrorCircle16Filled = exports.ErrorCircle16Regular = exports.ErrorCircle12Filled = exports.ErrorCircle12Regular = exports.ErrorCircleRegular = exports.ErrorCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ErrorCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircleFilled", "", 2, undefined));
exports.ErrorCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircleRegular", "", 2, undefined));
exports.ErrorCircle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle12Regular", "", 1, 12));
exports.ErrorCircle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle12Filled", "", 0, 12));
exports.ErrorCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle16Regular", "", 1, 16));
exports.ErrorCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle16Filled", "", 0, 16));
exports.ErrorCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle20Regular", "", 1, 20));
exports.ErrorCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle20Filled", "", 0, 20));
exports.ErrorCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle24Regular", "", 1, 24));
exports.ErrorCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle24Filled", "", 0, 24));
exports.ErrorCircle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle48Regular", "󰎵", 1, 48));
exports.ErrorCircle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ErrorCircle48Filled", "󰏈", 0, 48));
