"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExpandUpLeft48Filled = exports.ExpandUpLeft48Regular = exports.ExpandUpLeft32Filled = exports.ExpandUpLeft32Regular = exports.ExpandUpLeft28Filled = exports.ExpandUpLeft28Regular = exports.ExpandUpLeft24Filled = exports.ExpandUpLeft24Regular = exports.ExpandUpLeft20Filled = exports.ExpandUpLeft20Regular = exports.ExpandUpLeft16Filled = exports.ExpandUpLeft16Regular = exports.ExpandUpLeftRegular = exports.ExpandUpLeftFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ExpandUpLeftFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeftFilled", "", 2, undefined));
exports.ExpandUpLeftRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeftRegular", "", 2, undefined));
exports.ExpandUpLeft16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft16Regular", "", 1, 16));
exports.ExpandUpLeft16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft16Filled", "", 0, 16));
exports.ExpandUpLeft20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft20Regular", "", 1, 20));
exports.ExpandUpLeft20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft20Filled", "", 0, 20));
exports.ExpandUpLeft24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft24Regular", "", 1, 24));
exports.ExpandUpLeft24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft24Filled", "", 0, 24));
exports.ExpandUpLeft28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft28Regular", "", 1, 28));
exports.ExpandUpLeft28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft28Filled", "", 0, 28));
exports.ExpandUpLeft32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft32Regular", "", 1, 32));
exports.ExpandUpLeft32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft32Filled", "", 0, 32));
exports.ExpandUpLeft48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft48Regular", "", 1, 48));
exports.ExpandUpLeft48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ExpandUpLeft48Filled", "", 0, 48));
