"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EyeCircle24Filled = exports.EyeCircle24Regular = exports.EyeCircle20Filled = exports.EyeCircle20Regular = exports.EyeCircle16Filled = exports.EyeCircle16Regular = exports.EyeCircleRegular = exports.EyeCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EyeCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircleFilled", "", 2, undefined));
exports.EyeCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircleRegular", "", 2, undefined));
exports.EyeCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircle16Regular", "󰩵", 1, 16));
exports.EyeCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircle16Filled", "󰫱", 0, 16));
exports.EyeCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircle20Regular", "󰩶", 1, 20));
exports.EyeCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircle20Filled", "󰫲", 0, 20));
exports.EyeCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircle24Regular", "󰩷", 1, 24));
exports.EyeCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeCircle24Filled", "󰫳", 0, 24));
