"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Eye48Filled = exports.Eye48Regular = exports.Eye32Light = exports.Eye32Filled = exports.Eye32Regular = exports.Eye28Filled = exports.Eye28Regular = exports.Eye24Filled = exports.Eye24Regular = exports.Eye20Filled = exports.Eye20Regular = exports.Eye16Filled = exports.Eye16Regular = exports.Eye12Filled = exports.Eye12Regular = exports.EyeRegular = exports.EyeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EyeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeFilled", "", 2, undefined));
exports.EyeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyeRegular", "", 2, undefined));
exports.Eye12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye12Regular", "", 1, 12));
exports.Eye12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye12Filled", "", 0, 12));
exports.Eye16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye16Regular", "", 1, 16));
exports.Eye16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye16Filled", "", 0, 16));
exports.Eye20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye20Regular", "", 1, 20));
exports.Eye20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye20Filled", "", 0, 20));
exports.Eye24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye24Regular", "", 1, 24));
exports.Eye24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye24Filled", "", 0, 24));
exports.Eye28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye28Regular", "", 1, 28));
exports.Eye28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye28Filled", "", 0, 28));
exports.Eye32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye32Regular", "", 1, 32));
exports.Eye32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye32Filled", "", 0, 32));
exports.Eye32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye32Light", "", 3, 32));
exports.Eye48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye48Regular", "", 1, 48));
exports.Eye48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Eye48Filled", "", 0, 48));
