"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EyedropperOff24Filled = exports.EyedropperOff24Regular = exports.EyedropperOff20Filled = exports.EyedropperOff20Regular = exports.EyedropperOffRegular = exports.EyedropperOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.EyedropperOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyedropperOffFilled", "", 2, undefined));
exports.EyedropperOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyedropperOffRegular", "", 2, undefined));
exports.EyedropperOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyedropperOff20Regular", "", 1, 20));
exports.EyedropperOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyedropperOff20Filled", "", 0, 20));
exports.EyedropperOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyedropperOff24Regular", "", 1, 24));
exports.EyedropperOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("EyedropperOff24Filled", "", 0, 24));
