"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fax20Filled = exports.Fax20Regular = exports.Fax16Filled = exports.Fax16Regular = exports.FaxRegular = exports.FaxFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FaxFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FaxFilled", "", 2, undefined));
exports.FaxRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FaxRegular", "", 2, undefined));
exports.Fax16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fax16Regular", "", 1, 16));
exports.Fax16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fax16Filled", "", 0, 16));
exports.Fax20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fax20Regular", "", 1, 20));
exports.Fax20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fax20Filled", "", 0, 20));
