"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Filter32Light = exports.Filter32Filled = exports.Filter32Regular = exports.Filter28Filled = exports.Filter28Regular = exports.Filter24Filled = exports.Filter24Regular = exports.Filter20Filled = exports.Filter20Regular = exports.Filter16Filled = exports.Filter16Regular = exports.Filter12Filled = exports.Filter12Regular = exports.FilterRegular = exports.FilterFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FilterFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterFilled", "", 2, undefined));
exports.FilterRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterRegular", "", 2, undefined));
exports.Filter12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter12Regular", "", 1, 12));
exports.Filter12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter12Filled", "", 0, 12));
exports.Filter16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter16Regular", "", 1, 16));
exports.Filter16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter16Filled", "", 0, 16));
exports.Filter20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter20Regular", "", 1, 20));
exports.Filter20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter20Filled", "", 0, 20));
exports.Filter24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter24Regular", "", 1, 24));
exports.Filter24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter24Filled", "", 0, 24));
exports.Filter28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter28Regular", "", 1, 28));
exports.Filter28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter28Filled", "", 0, 28));
exports.Filter32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter32Regular", "󰐲", 1, 32));
exports.Filter32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter32Filled", "󰑅", 0, 32));
exports.Filter32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Filter32Light", "", 3, 32));
