"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterDismiss24Filled = exports.FilterDismiss24Regular = exports.FilterDismiss20Filled = exports.FilterDismiss20Regular = exports.FilterDismiss16Filled = exports.FilterDismiss16Regular = exports.FilterDismissRegular = exports.FilterDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FilterDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismissFilled", "", 2, undefined));
exports.FilterDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismissRegular", "", 2, undefined));
exports.FilterDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismiss16Regular", "", 1, 16));
exports.FilterDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismiss16Filled", "", 0, 16));
exports.FilterDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismiss20Regular", "", 1, 20));
exports.FilterDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismiss20Filled", "", 0, 20));
exports.FilterDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismiss24Regular", "", 1, 24));
exports.FilterDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterDismiss24Filled", "", 0, 24));
