"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterSync24Filled = exports.FilterSync24Regular = exports.FilterSync20Filled = exports.FilterSync20Regular = exports.FilterSyncRegular = exports.FilterSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FilterSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterSyncFilled", "", 2, undefined));
exports.FilterSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterSyncRegular", "", 2, undefined));
exports.FilterSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterSync20Regular", "", 1, 20));
exports.FilterSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterSync20Filled", "", 0, 20));
exports.FilterSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterSync24Regular", "", 1, 24));
exports.FilterSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FilterSync24Filled", "", 0, 24));
