"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FixedWidth24Filled = exports.FixedWidth24Regular = exports.FixedWidth20Filled = exports.FixedWidth20Regular = exports.FixedWidthRegular = exports.FixedWidthFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FixedWidthFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FixedWidthFilled", "", 2, undefined));
exports.FixedWidthRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FixedWidthRegular", "", 2, undefined));
exports.FixedWidth20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FixedWidth20Regular", "", 1, 20));
exports.FixedWidth20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FixedWidth20Filled", "", 0, 20));
exports.FixedWidth24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FixedWidth24Regular", "", 1, 24));
exports.FixedWidth24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FixedWidth24Filled", "", 0, 24));
