"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Flag48Filled = exports.Flag48Regular = exports.Flag32Light = exports.Flag32Filled = exports.Flag32Regular = exports.Flag28Filled = exports.Flag28Regular = exports.Flag24Filled = exports.Flag24Regular = exports.Flag20Filled = exports.Flag20Regular = exports.Flag16Filled = exports.Flag16Regular = exports.FlagRegular = exports.FlagFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlagFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagFilled", "", 2, undefined));
exports.FlagRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagRegular", "", 2, undefined));
exports.Flag16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag16Regular", "", 1, 16));
exports.Flag16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag16Filled", "", 0, 16));
exports.Flag20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag20Regular", "", 1, 20));
exports.Flag20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag20Filled", "", 0, 20));
exports.Flag24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag24Regular", "", 1, 24));
exports.Flag24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag24Filled", "", 0, 24));
exports.Flag28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag28Regular", "", 1, 28));
exports.Flag28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag28Filled", "", 0, 28));
exports.Flag32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag32Regular", "󰀼", 1, 32));
exports.Flag32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag32Filled", "󰁀", 0, 32));
exports.Flag32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag32Light", "", 3, 32));
exports.Flag48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag48Regular", "", 1, 48));
exports.Flag48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flag48Filled", "", 0, 48));
