"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FlagClock48Filled = exports.FlagClock48Regular = exports.FlagClock32Filled = exports.FlagClock32Regular = exports.FlagClock28Filled = exports.FlagClock28Regular = exports.FlagClock24Filled = exports.FlagClock24Regular = exports.FlagClock20Filled = exports.FlagClock20Regular = exports.FlagClock16Filled = exports.FlagClock16Regular = exports.FlagClockRegular = exports.FlagClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlagClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClockFilled", "", 2, undefined));
exports.FlagClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClockRegular", "", 2, undefined));
exports.FlagClock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock16Regular", "󰀽", 1, 16));
exports.FlagClock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock16Filled", "󰁁", 0, 16));
exports.FlagClock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock20Regular", "󰀾", 1, 20));
exports.FlagClock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock20Filled", "󰁂", 0, 20));
exports.FlagClock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock24Regular", "󰀿", 1, 24));
exports.FlagClock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock24Filled", "󰁃", 0, 24));
exports.FlagClock28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock28Regular", "󰁀", 1, 28));
exports.FlagClock28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock28Filled", "󰁄", 0, 28));
exports.FlagClock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock32Regular", "󰁁", 1, 32));
exports.FlagClock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock32Filled", "󰁅", 0, 32));
exports.FlagClock48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock48Regular", "󰁂", 1, 48));
exports.FlagClock48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlagClock48Filled", "󰁆", 0, 48));
