"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FlashOff24Filled = exports.FlashOff24Regular = exports.FlashOff20Filled = exports.FlashOff20Regular = exports.FlashOffRegular = exports.FlashOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlashOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashOffFilled", "", 2, undefined));
exports.FlashOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashOffRegular", "", 2, undefined));
exports.FlashOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashOff20Regular", "", 1, 20));
exports.FlashOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashOff20Filled", "", 0, 20));
exports.FlashOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashOff24Regular", "", 1, 24));
exports.FlashOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashOff24Filled", "", 0, 24));
