"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Flashlight24Filled = exports.Flashlight24Regular = exports.Flashlight20Filled = exports.Flashlight20Regular = exports.Flashlight16Filled = exports.Flashlight16Regular = exports.FlashlightRegular = exports.FlashlightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlashlightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashlightFilled", "", 2, undefined));
exports.FlashlightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashlightRegular", "", 2, undefined));
exports.Flashlight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flashlight16Regular", "", 1, 16));
exports.Flashlight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flashlight16Filled", "", 0, 16));
exports.Flashlight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flashlight20Regular", "", 1, 20));
exports.Flashlight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flashlight20Filled", "", 0, 20));
exports.Flashlight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flashlight24Regular", "", 1, 24));
exports.Flashlight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flashlight24Filled", "", 0, 24));
