"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FlashPlay32Filled = exports.FlashPlay32Regular = exports.FlashPlay20Filled = exports.FlashPlay20Regular = exports.FlashPlayRegular = exports.FlashPlayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlashPlayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashPlayFilled", "", 2, undefined));
exports.FlashPlayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashPlayRegular", "", 2, undefined));
exports.FlashPlay20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashPlay20Regular", "", 1, 20));
exports.FlashPlay20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashPlay20Filled", "", 0, 20));
exports.FlashPlay32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashPlay32Regular", "󰣲", 1, 32));
exports.FlashPlay32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlashPlay32Filled", "󰥯", 0, 32));
