"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FlowSparkle24Filled = exports.FlowSparkle24Regular = exports.FlowSparkle20Filled = exports.FlowSparkle20Regular = exports.FlowSparkle16Filled = exports.FlowSparkle16Regular = exports.FlowSparkleRegular = exports.FlowSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlowSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkleFilled", "", 2, undefined));
exports.FlowSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkleRegular", "", 2, undefined));
exports.FlowSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkle16Regular", "󰡍", 1, 16));
exports.FlowSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkle16Filled", "󰣊", 0, 16));
exports.FlowSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkle20Regular", "󰡎", 1, 20));
exports.FlowSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkle20Filled", "󰣋", 0, 20));
exports.FlowSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkle24Regular", "󰦕", 1, 24));
exports.FlowSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowSparkle24Filled", "󰨒", 0, 24));
