"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Flowchart32Filled = exports.Flowchart32Regular = exports.Flowchart24Filled = exports.Flowchart24Regular = exports.Flowchart20Filled = exports.Flowchart20Regular = exports.Flowchart16Filled = exports.Flowchart16Regular = exports.FlowchartRegular = exports.FlowchartFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlowchartFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartFilled", "", 2, undefined));
exports.FlowchartRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartRegular", "", 2, undefined));
exports.Flowchart16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart16Regular", "󰓈", 1, 16));
exports.Flowchart16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart16Filled", "󰕁", 0, 16));
exports.Flowchart20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart20Regular", "", 1, 20));
exports.Flowchart20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart20Filled", "", 0, 20));
exports.Flowchart24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart24Regular", "", 1, 24));
exports.Flowchart24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart24Filled", "", 0, 24));
exports.Flowchart32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart32Regular", "󰓉", 1, 32));
exports.Flowchart32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Flowchart32Filled", "󰕂", 0, 32));
