"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FlowchartCircle24Filled = exports.FlowchartCircle24Regular = exports.FlowchartCircle20Filled = exports.FlowchartCircle20Regular = exports.FlowchartCircleRegular = exports.FlowchartCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FlowchartCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartCircleFilled", "", 2, undefined));
exports.FlowchartCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartCircleRegular", "", 2, undefined));
exports.FlowchartCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartCircle20Regular", "", 1, 20));
exports.FlowchartCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartCircle20Filled", "", 0, 20));
exports.FlowchartCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartCircle24Regular", "", 1, 24));
exports.FlowchartCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FlowchartCircle24Filled", "", 0, 24));
