"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fluent48Filled = exports.Fluent48Regular = exports.Fluent32Filled = exports.Fluent32Regular = exports.Fluent24Filled = exports.Fluent24Regular = exports.Fluent20Filled = exports.Fluent20Regular = exports.FluentRegular = exports.FluentFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FluentFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FluentFilled", "", 2, undefined));
exports.FluentRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FluentRegular", "", 2, undefined));
exports.Fluent20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent20Regular", "", 1, 20));
exports.Fluent20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent20Filled", "", 0, 20));
exports.Fluent24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent24Regular", "", 1, 24));
exports.Fluent24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent24Filled", "", 0, 24));
exports.Fluent32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent32Regular", "", 1, 32));
exports.Fluent32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent32Filled", "", 0, 32));
exports.Fluent48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent48Regular", "", 1, 48));
exports.Fluent48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Fluent48Filled", "", 0, 48));
