"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderSync24Filled = exports.FolderSync24Regular = exports.FolderSync20Filled = exports.FolderSync20Regular = exports.FolderSync16Filled = exports.FolderSync16Regular = exports.FolderSyncRegular = exports.FolderSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSyncFilled", "", 2, undefined));
exports.FolderSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSyncRegular", "", 2, undefined));
exports.FolderSync16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSync16Regular", "", 1, 16));
exports.FolderSync16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSync16Filled", "", 0, 16));
exports.FolderSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSync20Regular", "", 1, 20));
exports.FolderSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSync20Filled", "", 0, 20));
exports.FolderSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSync24Regular", "", 1, 24));
exports.FolderSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSync24Filled", "", 0, 24));
