"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderPerson48Filled = exports.FolderPerson48Regular = exports.FolderPerson32Filled = exports.FolderPerson32Regular = exports.FolderPerson28Filled = exports.FolderPerson28Regular = exports.FolderPerson24Filled = exports.FolderPerson24Regular = exports.FolderPerson20Filled = exports.FolderPerson20Regular = exports.FolderPerson16Filled = exports.FolderPerson16Regular = exports.FolderPersonRegular = exports.FolderPersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderPersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPersonFilled", "", 2, undefined));
exports.FolderPersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPersonRegular", "", 2, undefined));
exports.FolderPerson16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson16Regular", "", 1, 16));
exports.FolderPerson16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson16Filled", "", 0, 16));
exports.FolderPerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson20Regular", "", 1, 20));
exports.FolderPerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson20Filled", "", 0, 20));
exports.FolderPerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson24Regular", "󰏻", 1, 24));
exports.FolderPerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson24Filled", "󰐎", 0, 24));
exports.FolderPerson28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson28Regular", "󰏼", 1, 28));
exports.FolderPerson28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson28Filled", "󰐏", 0, 28));
exports.FolderPerson32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson32Regular", "󰏽", 1, 32));
exports.FolderPerson32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson32Filled", "󰐐", 0, 32));
exports.FolderPerson48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson48Regular", "󰏾", 1, 48));
exports.FolderPerson48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderPerson48Filled", "󰐑", 0, 48));
