"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderList20Filled = exports.FolderList20Regular = exports.FolderList16Filled = exports.FolderList16Regular = exports.FolderListRegular = exports.FolderListFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderListFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderListFilled", "", 2, undefined));
exports.FolderListRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderListRegular", "", 2, undefined));
exports.FolderList16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderList16Regular", "󰄨", 1, 16));
exports.FolderList16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderList16Filled", "󰄧", 0, 16));
exports.FolderList20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderList20Regular", "󰄩", 1, 20));
exports.FolderList20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderList20Filled", "󰄨", 0, 20));
