"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderLink48Filled = exports.FolderLink48Regular = exports.FolderLink32Filled = exports.FolderLink32Regular = exports.FolderLink28Filled = exports.FolderLink28Regular = exports.FolderLink24Filled = exports.FolderLink24Regular = exports.FolderLink20Filled = exports.FolderLink20Regular = exports.FolderLink16Filled = exports.FolderLink16Regular = exports.FolderLinkRegular = exports.FolderLinkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderLinkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLinkFilled", "", 2, undefined));
exports.FolderLinkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLinkRegular", "", 2, undefined));
exports.FolderLink16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink16Regular", "󰈕", 1, 16));
exports.FolderLink16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink16Filled", "󰈨", 0, 16));
exports.FolderLink20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink20Regular", "", 1, 20));
exports.FolderLink20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink20Filled", "", 0, 20));
exports.FolderLink24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink24Regular", "", 1, 24));
exports.FolderLink24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink24Filled", "", 0, 24));
exports.FolderLink28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink28Regular", "", 1, 28));
exports.FolderLink28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink28Filled", "", 0, 28));
exports.FolderLink32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink32Regular", "󰈖", 1, 32));
exports.FolderLink32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink32Filled", "󰈩", 0, 32));
exports.FolderLink48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink48Regular", "", 1, 48));
exports.FolderLink48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderLink48Filled", "", 0, 48));
