"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderAdd48Filled = exports.FolderAdd48Regular = exports.FolderAdd32Filled = exports.FolderAdd32Regular = exports.FolderAdd28Filled = exports.FolderAdd28Regular = exports.FolderAdd24Filled = exports.FolderAdd24Regular = exports.FolderAdd20Filled = exports.FolderAdd20Regular = exports.FolderAdd16Filled = exports.FolderAdd16Regular = exports.FolderAddRegular = exports.FolderAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAddFilled", "", 2, undefined));
exports.FolderAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAddRegular", "", 2, undefined));
exports.FolderAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd16Regular", "", 1, 16));
exports.FolderAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd16Filled", "", 0, 16));
exports.FolderAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd20Regular", "", 1, 20));
exports.FolderAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd20Filled", "", 0, 20));
exports.FolderAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd24Regular", "", 1, 24));
exports.FolderAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd24Filled", "", 0, 24));
exports.FolderAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd28Regular", "", 1, 28));
exports.FolderAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd28Filled", "", 0, 28));
exports.FolderAdd32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd32Regular", "󰈑", 1, 32));
exports.FolderAdd32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd32Filled", "󰈤", 0, 32));
exports.FolderAdd48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd48Regular", "", 1, 48));
exports.FolderAdd48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderAdd48Filled", "", 0, 48));
