"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderSearch24Filled = exports.FolderSearch24Regular = exports.FolderSearch20Filled = exports.FolderSearch20Regular = exports.FolderSearch16Filled = exports.FolderSearch16Regular = exports.FolderSearchRegular = exports.FolderSearchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderSearchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearchFilled", "", 2, undefined));
exports.FolderSearchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearchRegular", "", 2, undefined));
exports.FolderSearch16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearch16Regular", "󰎍", 1, 16));
exports.FolderSearch16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearch16Filled", "󰎠", 0, 16));
exports.FolderSearch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearch20Regular", "󰎎", 1, 20));
exports.FolderSearch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearch20Filled", "󰎡", 0, 20));
exports.FolderSearch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearch24Regular", "󰎏", 1, 24));
exports.FolderSearch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderSearch24Filled", "󰎢", 0, 24));
