"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Folder48Filled = exports.Folder48Regular = exports.Folder32Filled = exports.Folder32Regular = exports.Folder28Filled = exports.Folder28Regular = exports.Folder24Filled = exports.Folder24Regular = exports.Folder20Filled = exports.Folder20Regular = exports.Folder16Filled = exports.Folder16Regular = exports.FolderRegular = exports.FolderFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderFilled", "", 2, undefined));
exports.FolderRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderRegular", "", 2, undefined));
exports.Folder16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder16Regular", "", 1, 16));
exports.Folder16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder16Filled", "", 0, 16));
exports.Folder20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder20Regular", "", 1, 20));
exports.Folder20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder20Filled", "", 0, 20));
exports.Folder24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder24Regular", "", 1, 24));
exports.Folder24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder24Filled", "", 0, 24));
exports.Folder28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder28Regular", "", 1, 28));
exports.Folder28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder28Filled", "", 0, 28));
exports.Folder32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder32Regular", "", 1, 32));
exports.Folder32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder32Filled", "", 0, 32));
exports.Folder48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder48Regular", "", 1, 48));
exports.Folder48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Folder48Filled", "", 0, 48));
