"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FolderZip24Filled = exports.FolderZip24Regular = exports.FolderZip20Filled = exports.FolderZip20Regular = exports.FolderZip16Filled = exports.FolderZip16Regular = exports.FolderZipRegular = exports.FolderZipFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FolderZipFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZipFilled", "", 2, undefined));
exports.FolderZipRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZipRegular", "", 2, undefined));
exports.FolderZip16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZip16Regular", "", 1, 16));
exports.FolderZip16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZip16Filled", "", 0, 16));
exports.FolderZip20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZip20Regular", "", 1, 20));
exports.FolderZip20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZip20Filled", "", 0, 20));
exports.FolderZip24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZip24Regular", "", 1, 24));
exports.FolderZip24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FolderZip24Filled", "", 0, 24));
