"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FoodToast24Filled = exports.FoodToast24Regular = exports.FoodToast20Filled = exports.FoodToast20Regular = exports.FoodToast16Filled = exports.FoodToast16Regular = exports.FoodToastRegular = exports.FoodToastFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FoodToastFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToastFilled", "", 2, undefined));
exports.FoodToastRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToastRegular", "", 2, undefined));
exports.FoodToast16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToast16Regular", "", 1, 16));
exports.FoodToast16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToast16Filled", "", 0, 16));
exports.FoodToast20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToast20Regular", "", 1, 20));
exports.FoodToast20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToast20Filled", "", 0, 20));
exports.FoodToast24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToast24Regular", "", 1, 24));
exports.FoodToast24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodToast24Filled", "", 0, 24));
