"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FoodEgg24Filled = exports.FoodEgg24Regular = exports.FoodEgg20Filled = exports.FoodEgg20Regular = exports.FoodEgg16Filled = exports.FoodEgg16Regular = exports.FoodEggRegular = exports.FoodEggFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FoodEggFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEggFilled", "", 2, undefined));
exports.FoodEggRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEggRegular", "", 2, undefined));
exports.FoodEgg16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEgg16Regular", "", 1, 16));
exports.FoodEgg16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEgg16Filled", "", 0, 16));
exports.FoodEgg20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEgg20Regular", "", 1, 20));
exports.FoodEgg20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEgg20Filled", "", 0, 20));
exports.FoodEgg24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEgg24Regular", "", 1, 24));
exports.FoodEgg24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodEgg24Filled", "", 0, 24));
