"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FoodApple24Filled = exports.FoodApple24Regular = exports.FoodApple20Filled = exports.FoodApple20Regular = exports.FoodAppleRegular = exports.FoodAppleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FoodAppleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodAppleFilled", "", 2, undefined));
exports.FoodAppleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodAppleRegular", "", 2, undefined));
exports.FoodApple20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodApple20Regular", "", 1, 20));
exports.FoodApple20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodApple20Filled", "", 0, 20));
exports.FoodApple24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodApple24Regular", "", 1, 24));
exports.FoodApple24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FoodApple24Filled", "", 0, 24));
