"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Frame24Filled = exports.Frame24Regular = exports.Frame20Filled = exports.Frame20Regular = exports.Frame16Filled = exports.Frame16Regular = exports.FrameRegular = exports.FrameFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.FrameFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FrameFilled", "", 2, undefined));
exports.FrameRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("FrameRegular", "", 2, undefined));
exports.Frame16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Frame16Regular", "󰃜", 1, 16));
exports.Frame16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Frame16Filled", "󰃛", 0, 16));
exports.Frame20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Frame20Regular", "󰃝", 1, 20));
exports.Frame20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Frame20Filled", "󰃜", 0, 20));
exports.Frame24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Frame24Regular", "󰃞", 1, 24));
exports.Frame24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Frame24Filled", "󰃝", 0, 24));
