"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GasPropane20Filled = exports.GasPropane20Regular = exports.GasPropane16Filled = exports.GasPropane16Regular = exports.GasPropaneRegular = exports.GasPropaneFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GasPropaneFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GasPropaneFilled", "", 2, undefined));
exports.GasPropaneRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GasPropaneRegular", "", 2, undefined));
exports.GasPropane16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GasPropane16Regular", "󰬇", 1, 16));
exports.GasPropane16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GasPropane16Filled", "󰮅", 0, 16));
exports.GasPropane20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GasPropane20Regular", "󰬈", 1, 20));
exports.GasPropane20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GasPropane20Filled", "󰮆", 0, 20));
