"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Gesture24Filled = exports.Gesture24Regular = exports.Gesture20Filled = exports.Gesture20Regular = exports.GestureRegular = exports.GestureFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GestureFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GestureFilled", "", 2, undefined));
exports.GestureRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GestureRegular", "", 2, undefined));
exports.Gesture20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gesture20Regular", "", 1, 20));
exports.Gesture20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gesture20Filled", "", 0, 20));
exports.Gesture24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gesture24Regular", "", 1, 24));
exports.Gesture24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gesture24Filled", "", 0, 24));
