"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Gif24Filled = exports.Gif24Regular = exports.Gif20Filled = exports.Gif20Regular = exports.Gif16Filled = exports.Gif16Regular = exports.GifRegular = exports.GifFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GifFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GifFilled", "", 2, undefined));
exports.GifRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GifRegular", "", 2, undefined));
exports.Gif16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gif16Regular", "", 1, 16));
exports.Gif16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gif16Filled", "", 0, 16));
exports.Gif20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gif20Regular", "", 1, 20));
exports.Gif20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gif20Filled", "", 0, 20));
exports.Gif24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gif24Regular", "", 1, 24));
exports.Gif24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Gif24Filled", "", 0, 24));
