"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Glance48Filled = exports.Glance48Regular = exports.Glance32Filled = exports.Glance32Regular = exports.Glance28Filled = exports.Glance28Regular = exports.Glance24Filled = exports.Glance24Regular = exports.Glance20Filled = exports.Glance20Regular = exports.Glance16Filled = exports.Glance16Regular = exports.Glance12Filled = exports.Glance12Regular = exports.GlanceRegular = exports.GlanceFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlanceFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlanceFilled", "", 2, undefined));
exports.GlanceRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlanceRegular", "", 2, undefined));
exports.Glance12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance12Regular", "", 1, 12));
exports.Glance12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance12Filled", "", 0, 12));
exports.Glance16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance16Regular", "󰛵", 1, 16));
exports.Glance16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance16Filled", "󰝲", 0, 16));
exports.Glance20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance20Regular", "", 1, 20));
exports.Glance20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance20Filled", "", 0, 20));
exports.Glance24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance24Regular", "", 1, 24));
exports.Glance24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance24Filled", "", 0, 24));
exports.Glance28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance28Regular", "󰛶", 1, 28));
exports.Glance28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance28Filled", "󰝳", 0, 28));
exports.Glance32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance32Regular", "󰛷", 1, 32));
exports.Glance32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance32Filled", "󰝴", 0, 32));
exports.Glance48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance48Regular", "󰛸", 1, 48));
exports.Glance48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glance48Filled", "󰝵", 0, 48));
