"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Glasses48Filled = exports.Glasses48Regular = exports.Glasses32Filled = exports.Glasses32Regular = exports.Glasses28Filled = exports.Glasses28Regular = exports.Glasses24Filled = exports.Glasses24Regular = exports.Glasses20Filled = exports.Glasses20Regular = exports.Glasses16Filled = exports.Glasses16Regular = exports.GlassesRegular = exports.GlassesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlassesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlassesFilled", "", 2, undefined));
exports.GlassesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlassesRegular", "", 2, undefined));
exports.Glasses16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses16Regular", "", 1, 16));
exports.Glasses16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses16Filled", "", 0, 16));
exports.Glasses20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses20Regular", "", 1, 20));
exports.Glasses20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses20Filled", "", 0, 20));
exports.Glasses24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses24Regular", "", 1, 24));
exports.Glasses24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses24Filled", "", 0, 24));
exports.Glasses28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses28Regular", "", 1, 28));
exports.Glasses28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses28Filled", "", 0, 28));
exports.Glasses32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses32Regular", "󰁃", 1, 32));
exports.Glasses32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses32Filled", "󰁇", 0, 32));
exports.Glasses48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses48Regular", "", 1, 48));
exports.Glasses48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Glasses48Filled", "", 0, 48));
