"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobePerson24Filled = exports.GlobePerson24Regular = exports.GlobePerson20Filled = exports.GlobePerson20Regular = exports.GlobePersonRegular = exports.GlobePersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobePersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobePersonFilled", "", 2, undefined));
exports.GlobePersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobePersonRegular", "", 2, undefined));
exports.GlobePerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobePerson20Regular", "", 1, 20));
exports.GlobePerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobePerson20Filled", "", 0, 20));
exports.GlobePerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobePerson24Regular", "", 1, 24));
exports.GlobePerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobePerson24Filled", "", 0, 24));
