"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobeWarning24Filled = exports.GlobeWarning24Regular = exports.GlobeWarning20Filled = exports.GlobeWarning20Regular = exports.GlobeWarning16Filled = exports.GlobeWarning16Regular = exports.GlobeWarningRegular = exports.GlobeWarningFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeWarningFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarningFilled", "", 2, undefined));
exports.GlobeWarningRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarningRegular", "", 2, undefined));
exports.GlobeWarning16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarning16Regular", "󰑁", 1, 16));
exports.GlobeWarning16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarning16Filled", "󰑔", 0, 16));
exports.GlobeWarning20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarning20Regular", "󰑂", 1, 20));
exports.GlobeWarning20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarning20Filled", "󰑕", 0, 20));
exports.GlobeWarning24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarning24Regular", "󰑃", 1, 24));
exports.GlobeWarning24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeWarning24Filled", "󰑖", 0, 24));
