"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Globe48Filled = exports.Globe48Regular = exports.Globe32Light = exports.Globe32Filled = exports.Globe32Regular = exports.Globe28Filled = exports.Globe28Regular = exports.Globe24Filled = exports.Globe24Regular = exports.Globe20Filled = exports.Globe20Regular = exports.Globe16Filled = exports.Globe16Regular = exports.Globe12Filled = exports.Globe12Regular = exports.GlobeRegular = exports.GlobeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeFilled", "", 2, undefined));
exports.GlobeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeRegular", "", 2, undefined));
exports.Globe12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe12Regular", "󰆋", 1, 12));
exports.Globe12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe12Filled", "󰆋", 0, 12));
exports.Globe16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe16Regular", "", 1, 16));
exports.Globe16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe16Filled", "", 0, 16));
exports.Globe20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe20Regular", "", 1, 20));
exports.Globe20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe20Filled", "", 0, 20));
exports.Globe24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe24Regular", "", 1, 24));
exports.Globe24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe24Filled", "", 0, 24));
exports.Globe28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe28Regular", "󰔍", 1, 28));
exports.Globe28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe28Filled", "󰖆", 0, 28));
exports.Globe32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe32Regular", "", 1, 32));
exports.Globe32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe32Filled", "", 0, 32));
exports.Globe32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe32Light", "", 3, 32));
exports.Globe48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe48Regular", "󰉮", 1, 48));
exports.Globe48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Globe48Filled", "󰊁", 0, 48));
