"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobeSurface32Filled = exports.GlobeSurface32Regular = exports.GlobeSurface24Filled = exports.GlobeSurface24Regular = exports.GlobeSurface20Filled = exports.GlobeSurface20Regular = exports.GlobeSurfaceRegular = exports.GlobeSurfaceFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeSurfaceFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurfaceFilled", "", 2, undefined));
exports.GlobeSurfaceRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurfaceRegular", "", 2, undefined));
exports.GlobeSurface20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurface20Regular", "", 1, 20));
exports.GlobeSurface20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurface20Filled", "", 0, 20));
exports.GlobeSurface24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurface24Regular", "", 1, 24));
exports.GlobeSurface24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurface24Filled", "", 0, 24));
exports.GlobeSurface32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurface32Regular", "󰁅", 1, 32));
exports.GlobeSurface32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSurface32Filled", "󰁉", 0, 32));
