"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobeSync24Filled = exports.GlobeSync24Regular = exports.GlobeSync20Filled = exports.GlobeSync20Regular = exports.GlobeSync16Filled = exports.GlobeSync16Regular = exports.GlobeSyncRegular = exports.GlobeSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSyncFilled", "", 2, undefined));
exports.GlobeSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSyncRegular", "", 2, undefined));
exports.GlobeSync16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSync16Regular", "󰐾", 1, 16));
exports.GlobeSync16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSync16Filled", "󰑑", 0, 16));
exports.GlobeSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSync20Regular", "󰐿", 1, 20));
exports.GlobeSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSync20Filled", "󰑒", 0, 20));
exports.GlobeSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSync24Regular", "󰑀", 1, 24));
exports.GlobeSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSync24Filled", "󰑓", 0, 24));
