"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobeClock24Filled = exports.GlobeClock24Regular = exports.GlobeClock20Filled = exports.GlobeClock20Regular = exports.GlobeClock16Filled = exports.GlobeClock16Regular = exports.GlobeClockRegular = exports.GlobeClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClockFilled", "", 2, undefined));
exports.GlobeClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClockRegular", "", 2, undefined));
exports.GlobeClock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClock16Regular", "", 1, 16));
exports.GlobeClock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClock16Filled", "", 0, 16));
exports.GlobeClock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClock20Regular", "", 1, 20));
exports.GlobeClock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClock20Filled", "", 0, 20));
exports.GlobeClock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClock24Regular", "", 1, 24));
exports.GlobeClock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeClock24Filled", "", 0, 24));
