"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobeStar20Filled = exports.GlobeStar20Regular = exports.GlobeStar16Filled = exports.GlobeStar16Regular = exports.GlobeStarRegular = exports.GlobeStarFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeStarFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeStarFilled", "", 2, undefined));
exports.GlobeStarRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeStarRegular", "", 2, undefined));
exports.GlobeStar16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeStar16Regular", "", 1, 16));
exports.GlobeStar16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeStar16Filled", "", 0, 16));
exports.GlobeStar20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeStar20Regular", "", 1, 20));
exports.GlobeStar20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeStar20Filled", "", 0, 20));
