"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GlobeSearch24Filled = exports.GlobeSearch24Regular = exports.GlobeSearch20Filled = exports.GlobeSearch20Regular = exports.GlobeSearchRegular = exports.GlobeSearchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GlobeSearchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSearchFilled", "", 2, undefined));
exports.GlobeSearchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSearchRegular", "", 2, undefined));
exports.GlobeSearch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSearch20Regular", "", 1, 20));
exports.GlobeSearch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSearch20Filled", "", 0, 20));
exports.GlobeSearch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSearch24Regular", "", 1, 24));
exports.GlobeSearch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GlobeSearch24Filled", "", 0, 24));
