"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridDots28Filled = exports.GridDots28Regular = exports.GridDots24Filled = exports.GridDots24Regular = exports.GridDots20Filled = exports.GridDots20Regular = exports.GridDotsRegular = exports.GridDotsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GridDotsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDotsFilled", "", 2, undefined));
exports.GridDotsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDotsRegular", "", 2, undefined));
exports.GridDots20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDots20Regular", "", 1, 20));
exports.GridDots20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDots20Filled", "", 0, 20));
exports.GridDots24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDots24Regular", "", 1, 24));
exports.GridDots24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDots24Filled", "", 0, 24));
exports.GridDots28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDots28Regular", "", 1, 28));
exports.GridDots28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GridDots28Filled", "", 0, 28));
