"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupDismiss24Filled = exports.GroupDismiss24Regular = exports.GroupDismiss20Filled = exports.GroupDismiss20Regular = exports.GroupDismissRegular = exports.GroupDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GroupDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupDismissFilled", "", 2, undefined));
exports.GroupDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupDismissRegular", "", 2, undefined));
exports.GroupDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupDismiss20Regular", "", 1, 20));
exports.GroupDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupDismiss20Filled", "", 0, 20));
exports.GroupDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupDismiss24Regular", "", 1, 24));
exports.GroupDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupDismiss24Filled", "", 0, 24));
