"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupReturn24Filled = exports.GroupReturn24Regular = exports.GroupReturn20Filled = exports.GroupReturn20Regular = exports.GroupReturnRegular = exports.GroupReturnFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GroupReturnFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupReturnFilled", "", 2, undefined));
exports.GroupReturnRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupReturnRegular", "", 2, undefined));
exports.GroupReturn20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupReturn20Regular", "", 1, 20));
exports.GroupReturn20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupReturn20Filled", "", 0, 20));
exports.GroupReturn24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupReturn24Regular", "", 1, 24));
exports.GroupReturn24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupReturn24Filled", "", 0, 24));
