"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupList24Filled = exports.GroupList24Regular = exports.GroupList20Filled = exports.GroupList20Regular = exports.GroupListRegular = exports.GroupListFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GroupListFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupListFilled", "", 2, undefined));
exports.GroupListRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupListRegular", "", 2, undefined));
exports.GroupList20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupList20Regular", "", 1, 20));
exports.GroupList20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupList20Filled", "", 0, 20));
exports.GroupList24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupList24Regular", "", 1, 24));
exports.GroupList24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GroupList24Filled", "", 0, 24));
