"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GuestAdd24Filled = exports.GuestAdd24Regular = exports.GuestAdd20Filled = exports.GuestAdd20Regular = exports.GuestAddRegular = exports.GuestAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.GuestAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GuestAddFilled", "", 2, undefined));
exports.GuestAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GuestAddRegular", "", 2, undefined));
exports.GuestAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GuestAdd20Regular", "", 1, 20));
exports.GuestAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GuestAdd20Filled", "", 0, 20));
exports.GuestAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GuestAdd24Regular", "", 1, 24));
exports.GuestAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("GuestAdd24Filled", "", 0, 24));
