"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HandWave24Filled = exports.HandWave24Regular = exports.HandWave20Filled = exports.HandWave20Regular = exports.HandWave16Filled = exports.HandWave16Regular = exports.HandWaveRegular = exports.HandWaveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HandWaveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWaveFilled", "", 2, undefined));
exports.HandWaveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWaveRegular", "", 2, undefined));
exports.HandWave16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWave16Regular", "", 1, 16));
exports.HandWave16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWave16Filled", "", 0, 16));
exports.HandWave20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWave20Regular", "", 1, 20));
exports.HandWave20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWave20Filled", "", 0, 20));
exports.HandWave24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWave24Regular", "", 1, 24));
exports.HandWave24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandWave24Filled", "", 0, 24));
