"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HandRight28Filled = exports.HandRight28Regular = exports.HandRight24Filled = exports.HandRight24Regular = exports.HandRight20Filled = exports.HandRight20Regular = exports.HandRight16Filled = exports.HandRight16Regular = exports.HandRightRegular = exports.HandRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HandRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRightFilled", "", 2, undefined));
exports.HandRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRightRegular", "", 2, undefined));
exports.HandRight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight16Regular", "", 1, 16));
exports.HandRight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight16Filled", "", 0, 16));
exports.HandRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight20Regular", "", 1, 20));
exports.HandRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight20Filled", "", 0, 20));
exports.HandRight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight24Regular", "", 1, 24));
exports.HandRight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight24Filled", "", 0, 24));
exports.HandRight28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight28Regular", "", 1, 28));
exports.HandRight28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandRight28Filled", "", 0, 28));
