"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Handshake32Filled = exports.Handshake32Regular = exports.Handshake24Filled = exports.Handshake24Regular = exports.Handshake20Filled = exports.Handshake20Regular = exports.Handshake16Filled = exports.Handshake16Regular = exports.HandshakeRegular = exports.HandshakeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HandshakeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandshakeFilled", "", 2, undefined));
exports.HandshakeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandshakeRegular", "", 2, undefined));
exports.Handshake16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake16Regular", "", 1, 16));
exports.Handshake16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake16Filled", "", 0, 16));
exports.Handshake20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake20Regular", "", 1, 20));
exports.Handshake20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake20Filled", "", 0, 20));
exports.Handshake24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake24Regular", "", 1, 24));
exports.Handshake24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake24Filled", "", 0, 24));
exports.Handshake32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake32Regular", "", 1, 32));
exports.Handshake32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Handshake32Filled", "", 0, 32));
