"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HandLeft28Filled = exports.HandLeft28Regular = exports.HandLeft24Filled = exports.HandLeft24Regular = exports.HandLeft20Filled = exports.HandLeft20Regular = exports.HandLeft16Filled = exports.HandLeft16Regular = exports.HandLeftRegular = exports.HandLeftFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HandLeftFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeftFilled", "", 2, undefined));
exports.HandLeftRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeftRegular", "", 2, undefined));
exports.HandLeft16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft16Regular", "", 1, 16));
exports.HandLeft16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft16Filled", "", 0, 16));
exports.HandLeft20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft20Regular", "", 1, 20));
exports.HandLeft20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft20Filled", "", 0, 20));
exports.HandLeft24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft24Regular", "", 1, 24));
exports.HandLeft24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft24Filled", "", 0, 24));
exports.HandLeft28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft28Regular", "", 1, 28));
exports.HandLeft28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandLeft28Filled", "", 0, 28));
