"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HandPoint48Filled = exports.HandPoint48Regular = exports.HandPoint32Filled = exports.HandPoint32Regular = exports.HandPoint28Filled = exports.HandPoint28Regular = exports.HandPoint24Filled = exports.HandPoint24Regular = exports.HandPoint20Filled = exports.HandPoint20Regular = exports.HandPoint16Filled = exports.HandPoint16Regular = exports.HandPointRegular = exports.HandPointFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HandPointFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPointFilled", "", 2, undefined));
exports.HandPointRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPointRegular", "", 2, undefined));
exports.HandPoint16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint16Regular", "󰖇", 1, 16));
exports.HandPoint16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint16Filled", "󰘀", 0, 16));
exports.HandPoint20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint20Regular", "󰖈", 1, 20));
exports.HandPoint20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint20Filled", "󰘁", 0, 20));
exports.HandPoint24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint24Regular", "󰖉", 1, 24));
exports.HandPoint24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint24Filled", "󰘂", 0, 24));
exports.HandPoint28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint28Regular", "󰖊", 1, 28));
exports.HandPoint28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint28Filled", "󰘃", 0, 28));
exports.HandPoint32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint32Regular", "󰖋", 1, 32));
exports.HandPoint32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint32Filled", "󰘄", 0, 32));
exports.HandPoint48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint48Regular", "󰖌", 1, 48));
exports.HandPoint48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HandPoint48Filled", "󰘅", 0, 48));
