"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HapticStrong24Filled = exports.HapticStrong24Regular = exports.HapticStrong20Filled = exports.HapticStrong20Regular = exports.HapticStrong16Filled = exports.HapticStrong16Regular = exports.HapticStrongRegular = exports.HapticStrongFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HapticStrongFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrongFilled", "", 2, undefined));
exports.HapticStrongRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrongRegular", "", 2, undefined));
exports.HapticStrong16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrong16Regular", "󰖥", 1, 16));
exports.HapticStrong16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrong16Filled", "󰘞", 0, 16));
exports.HapticStrong20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrong20Regular", "󰖦", 1, 20));
exports.HapticStrong20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrong20Filled", "󰘟", 0, 20));
exports.HapticStrong24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrong24Regular", "󰖧", 1, 24));
exports.HapticStrong24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticStrong24Filled", "󰘠", 0, 24));
