"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HapticWeak24Filled = exports.HapticWeak24Regular = exports.HapticWeak20Filled = exports.HapticWeak20Regular = exports.HapticWeak16Filled = exports.HapticWeak16Regular = exports.HapticWeakRegular = exports.HapticWeakFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HapticWeakFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeakFilled", "", 2, undefined));
exports.HapticWeakRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeakRegular", "", 2, undefined));
exports.HapticWeak16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeak16Regular", "󰖨", 1, 16));
exports.HapticWeak16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeak16Filled", "󰘡", 0, 16));
exports.HapticWeak20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeak20Regular", "󰖩", 1, 20));
exports.HapticWeak20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeak20Filled", "󰘢", 0, 20));
exports.HapticWeak24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeak24Regular", "󰖪", 1, 24));
exports.HapticWeak24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HapticWeak24Filled", "󰘣", 0, 24));
