"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HardDrive48Filled = exports.HardDrive48Regular = exports.HardDrive32Filled = exports.HardDrive32Regular = exports.HardDrive28Filled = exports.HardDrive28Regular = exports.HardDrive24Filled = exports.HardDrive24Regular = exports.HardDrive20Filled = exports.HardDrive20Regular = exports.HardDrive16Filled = exports.HardDrive16Regular = exports.HardDriveRegular = exports.HardDriveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HardDriveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDriveFilled", "", 2, undefined));
exports.HardDriveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDriveRegular", "", 2, undefined));
exports.HardDrive16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive16Regular", "", 1, 16));
exports.HardDrive16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive16Filled", "", 0, 16));
exports.HardDrive20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive20Regular", "", 1, 20));
exports.HardDrive20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive20Filled", "", 0, 20));
exports.HardDrive24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive24Regular", "󰌆", 1, 24));
exports.HardDrive24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive24Filled", "󰌙", 0, 24));
exports.HardDrive28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive28Regular", "󰓱", 1, 28));
exports.HardDrive28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive28Filled", "󰕪", 0, 28));
exports.HardDrive32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive32Regular", "󰌇", 1, 32));
exports.HardDrive32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive32Filled", "󰌚", 0, 32));
exports.HardDrive48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive48Regular", "󰓲", 1, 48));
exports.HardDrive48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HardDrive48Filled", "󰕫", 0, 48));
