"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HdOff24Filled = exports.HdOff24Regular = exports.HdOff20Filled = exports.HdOff20Regular = exports.HdOff16Filled = exports.HdOff16Regular = exports.HdOffRegular = exports.HdOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HdOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOffFilled", "", 2, undefined));
exports.HdOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOffRegular", "", 2, undefined));
exports.HdOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOff16Regular", "󰞱", 1, 16));
exports.HdOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOff16Filled", "󰠮", 0, 16));
exports.HdOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOff20Regular", "󰞲", 1, 20));
exports.HdOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOff20Filled", "󰠯", 0, 20));
exports.HdOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOff24Regular", "󰞳", 1, 24));
exports.HdOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdOff24Filled", "󰠰", 0, 24));
