"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HdrOff24Filled = exports.HdrOff24Regular = exports.HdrOff20Filled = exports.HdrOff20Regular = exports.HdrOffRegular = exports.HdrOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HdrOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdrOffFilled", "", 2, undefined));
exports.HdrOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdrOffRegular", "", 2, undefined));
exports.HdrOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdrOff20Regular", "", 1, 20));
exports.HdrOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdrOff20Filled", "", 0, 20));
exports.HdrOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdrOff24Regular", "", 1, 24));
exports.HdrOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HdrOff24Filled", "", 0, 24));
