"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Headset48Filled = exports.Headset48Regular = exports.Headset32Filled = exports.Headset32Regular = exports.Headset28Filled = exports.Headset28Regular = exports.Headset24Filled = exports.Headset24Regular = exports.Headset20Filled = exports.Headset20Regular = exports.Headset16Filled = exports.Headset16Regular = exports.HeadsetRegular = exports.HeadsetFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HeadsetFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeadsetFilled", "", 2, undefined));
exports.HeadsetRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeadsetRegular", "", 2, undefined));
exports.Headset16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset16Regular", "", 1, 16));
exports.Headset16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset16Filled", "", 0, 16));
exports.Headset20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset20Regular", "", 1, 20));
exports.Headset20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset20Filled", "", 0, 20));
exports.Headset24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset24Regular", "", 1, 24));
exports.Headset24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset24Filled", "", 0, 24));
exports.Headset28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset28Regular", "", 1, 28));
exports.Headset28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset28Filled", "", 0, 28));
exports.Headset32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset32Regular", "", 1, 32));
exports.Headset32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset32Filled", "", 0, 32));
exports.Headset48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset48Regular", "", 1, 48));
exports.Headset48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headset48Filled", "", 0, 48));
