"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Headphones48Filled = exports.Headphones48Regular = exports.Headphones32Filled = exports.Headphones32Regular = exports.Headphones28Filled = exports.Headphones28Regular = exports.Headphones24Filled = exports.Headphones24Regular = exports.Headphones20Filled = exports.Headphones20Regular = exports.Headphones16Filled = exports.Headphones16Regular = exports.Headphones12Filled = exports.Headphones12Regular = exports.HeadphonesRegular = exports.HeadphonesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HeadphonesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeadphonesFilled", "", 2, undefined));
exports.HeadphonesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeadphonesRegular", "", 2, undefined));
exports.Headphones12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones12Regular", "󰩹", 1, 12));
exports.Headphones12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones12Filled", "󰫵", 0, 12));
exports.Headphones16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones16Regular", "󰩺", 1, 16));
exports.Headphones16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones16Filled", "󰫶", 0, 16));
exports.Headphones20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones20Regular", "", 1, 20));
exports.Headphones20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones20Filled", "", 0, 20));
exports.Headphones24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones24Regular", "", 1, 24));
exports.Headphones24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones24Filled", "", 0, 24));
exports.Headphones28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones28Regular", "", 1, 28));
exports.Headphones28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones28Filled", "", 0, 28));
exports.Headphones32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones32Regular", "", 1, 32));
exports.Headphones32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones32Filled", "", 0, 32));
exports.Headphones48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones48Regular", "", 1, 48));
exports.Headphones48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Headphones48Filled", "", 0, 48));
