"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HeartOff24Filled = exports.HeartOff24Regular = exports.HeartOff20Filled = exports.HeartOff20Regular = exports.HeartOff16Filled = exports.HeartOff16Regular = exports.HeartOffRegular = exports.HeartOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HeartOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOffFilled", "", 2, undefined));
exports.HeartOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOffRegular", "", 2, undefined));
exports.HeartOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOff16Regular", "󰊰", 1, 16));
exports.HeartOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOff16Filled", "󰋃", 0, 16));
exports.HeartOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOff20Regular", "󰊱", 1, 20));
exports.HeartOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOff20Filled", "󰋄", 0, 20));
exports.HeartOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOff24Regular", "󰊲", 1, 24));
exports.HeartOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HeartOff24Filled", "󰋅", 0, 24));
