"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HexagonThree24Filled = exports.HexagonThree24Regular = exports.HexagonThree20Filled = exports.HexagonThree20Regular = exports.HexagonThree16Filled = exports.HexagonThree16Regular = exports.HexagonThree12Filled = exports.HexagonThree12Regular = exports.HexagonThreeRegular = exports.HexagonThreeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HexagonThreeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThreeFilled", "", 2, undefined));
exports.HexagonThreeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThreeRegular", "", 2, undefined));
exports.HexagonThree12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree12Regular", "󰋚", 1, 12));
exports.HexagonThree12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree12Filled", "󰋭", 0, 12));
exports.HexagonThree16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree16Regular", "󰊵", 1, 16));
exports.HexagonThree16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree16Filled", "󰋈", 0, 16));
exports.HexagonThree20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree20Regular", "󰊶", 1, 20));
exports.HexagonThree20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree20Filled", "󰋉", 0, 20));
exports.HexagonThree24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree24Regular", "󰋛", 1, 24));
exports.HexagonThree24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HexagonThree24Filled", "󰋮", 0, 24));
