"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Highway24Filled = exports.Highway24Regular = exports.Highway20Filled = exports.Highway20Regular = exports.HighwayRegular = exports.HighwayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HighwayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HighwayFilled", "", 2, undefined));
exports.HighwayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HighwayRegular", "", 2, undefined));
exports.Highway20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Highway20Regular", "󰕩", 1, 20));
exports.Highway20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Highway20Filled", "󰗢", 0, 20));
exports.Highway24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Highway24Regular", "󰕪", 1, 24));
exports.Highway24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Highway24Filled", "󰗣", 0, 24));
