"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HistoryDismiss48Filled = exports.HistoryDismiss48Regular = exports.HistoryDismiss32Filled = exports.HistoryDismiss32Regular = exports.HistoryDismiss28Filled = exports.HistoryDismiss28Regular = exports.HistoryDismiss24Filled = exports.HistoryDismiss24Regular = exports.HistoryDismiss20Filled = exports.HistoryDismiss20Regular = exports.HistoryDismissRegular = exports.HistoryDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HistoryDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismissFilled", "", 2, undefined));
exports.HistoryDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismissRegular", "", 2, undefined));
exports.HistoryDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss20Regular", "", 1, 20));
exports.HistoryDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss20Filled", "", 0, 20));
exports.HistoryDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss24Regular", "", 1, 24));
exports.HistoryDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss24Filled", "", 0, 24));
exports.HistoryDismiss28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss28Regular", "", 1, 28));
exports.HistoryDismiss28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss28Filled", "", 0, 28));
exports.HistoryDismiss32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss32Regular", "", 1, 32));
exports.HistoryDismiss32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss32Filled", "", 0, 32));
exports.HistoryDismiss48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss48Regular", "", 1, 48));
exports.HistoryDismiss48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HistoryDismiss48Filled", "", 0, 48));
