"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Home48Filled = exports.Home48Regular = exports.Home32Filled = exports.Home32Regular = exports.Home28Filled = exports.Home28Regular = exports.Home24Filled = exports.Home24Regular = exports.Home20Filled = exports.Home20Regular = exports.Home16Filled = exports.Home16Regular = exports.Home12Filled = exports.Home12Regular = exports.HomeRegular = exports.HomeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HomeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HomeFilled", "", 2, undefined));
exports.HomeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HomeRegular", "", 2, undefined));
exports.Home12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home12Regular", "", 1, 12));
exports.Home12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home12Filled", "", 0, 12));
exports.Home16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home16Regular", "", 1, 16));
exports.Home16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home16Filled", "", 0, 16));
exports.Home20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home20Regular", "", 1, 20));
exports.Home20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home20Filled", "", 0, 20));
exports.Home24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home24Regular", "", 1, 24));
exports.Home24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home24Filled", "", 0, 24));
exports.Home28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home28Regular", "", 1, 28));
exports.Home28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home28Filled", "", 0, 28));
exports.Home32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home32Regular", "", 1, 32));
exports.Home32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home32Filled", "", 0, 32));
exports.Home48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home48Regular", "", 1, 48));
exports.Home48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Home48Filled", "", 0, 48));
