"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Hourglass24Filled = exports.Hourglass24Regular = exports.Hourglass20Filled = exports.Hourglass20Regular = exports.Hourglass16Filled = exports.Hourglass16Regular = exports.HourglassRegular = exports.HourglassFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HourglassFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassFilled", "", 2, undefined));
exports.HourglassRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassRegular", "", 2, undefined));
exports.Hourglass16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Hourglass16Regular", "", 1, 16));
exports.Hourglass16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Hourglass16Filled", "", 0, 16));
exports.Hourglass20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Hourglass20Regular", "", 1, 20));
exports.Hourglass20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Hourglass20Filled", "", 0, 20));
exports.Hourglass24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Hourglass24Regular", "", 1, 24));
exports.Hourglass24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Hourglass24Filled", "", 0, 24));
