"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HourglassHalf24Filled = exports.HourglassHalf24Regular = exports.HourglassHalf20Filled = exports.HourglassHalf20Regular = exports.HourglassHalf16Filled = exports.HourglassHalf16Regular = exports.HourglassHalfRegular = exports.HourglassHalfFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.HourglassHalfFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalfFilled", "", 2, undefined));
exports.HourglassHalfRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalfRegular", "", 2, undefined));
exports.HourglassHalf16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalf16Regular", "", 1, 16));
exports.HourglassHalf16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalf16Filled", "", 0, 16));
exports.HourglassHalf20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalf20Regular", "", 1, 20));
exports.HourglassHalf20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalf20Filled", "", 0, 20));
exports.HourglassHalf24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalf24Regular", "", 1, 24));
exports.HourglassHalf24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("HourglassHalf24Filled", "", 0, 24));
