"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Icons24Filled = exports.Icons24Regular = exports.Icons20Filled = exports.Icons20Regular = exports.IconsRegular = exports.IconsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.IconsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IconsFilled", "", 2, undefined));
exports.IconsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IconsRegular", "", 2, undefined));
exports.Icons20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Icons20Regular", "", 1, 20));
exports.Icons20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Icons20Filled", "", 0, 20));
exports.Icons24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Icons24Regular", "", 1, 24));
exports.Icons24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Icons24Filled", "", 0, 24));
