"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImageAdd48Filled = exports.ImageAdd48Regular = exports.ImageAdd32Light = exports.ImageAdd32Filled = exports.ImageAdd32Regular = exports.ImageAdd28Filled = exports.ImageAdd28Regular = exports.ImageAdd24Filled = exports.ImageAdd24Regular = exports.ImageAdd20Filled = exports.ImageAdd20Regular = exports.ImageAddRegular = exports.ImageAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ImageAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAddFilled", "", 2, undefined));
exports.ImageAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAddRegular", "", 2, undefined));
exports.ImageAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd20Regular", "", 1, 20));
exports.ImageAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd20Filled", "", 0, 20));
exports.ImageAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd24Regular", "", 1, 24));
exports.ImageAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd24Filled", "", 0, 24));
exports.ImageAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd28Regular", "󰡓", 1, 28));
exports.ImageAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd28Filled", "󰣐", 0, 28));
exports.ImageAdd32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd32Regular", "󰡔", 1, 32));
exports.ImageAdd32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd32Filled", "󰣑", 0, 32));
exports.ImageAdd32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd32Light", "", 3, 32));
exports.ImageAdd48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd48Regular", "󰡕", 1, 48));
exports.ImageAdd48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageAdd48Filled", "󰣒", 0, 48));
