"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImageEdit24Filled = exports.ImageEdit24Regular = exports.ImageEdit20Filled = exports.ImageEdit20Regular = exports.ImageEdit16Filled = exports.ImageEdit16Regular = exports.ImageEditRegular = exports.ImageEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ImageEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEditFilled", "", 2, undefined));
exports.ImageEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEditRegular", "", 2, undefined));
exports.ImageEdit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEdit16Regular", "", 1, 16));
exports.ImageEdit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEdit16Filled", "", 0, 16));
exports.ImageEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEdit20Regular", "", 1, 20));
exports.ImageEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEdit20Filled", "", 0, 20));
exports.ImageEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEdit24Regular", "", 1, 24));
exports.ImageEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageEdit24Filled", "", 0, 24));
