"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Image48Filled = exports.Image48Regular = exports.Image32Filled = exports.Image32Regular = exports.Image28Filled = exports.Image28Regular = exports.Image24Filled = exports.Image24Regular = exports.Image20Filled = exports.Image20Regular = exports.Image16Filled = exports.Image16Regular = exports.ImageRegular = exports.ImageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ImageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageFilled", "", 2, undefined));
exports.ImageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImageRegular", "", 2, undefined));
exports.Image16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image16Regular", "", 1, 16));
exports.Image16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image16Filled", "", 0, 16));
exports.Image20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image20Regular", "", 1, 20));
exports.Image20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image20Filled", "", 0, 20));
exports.Image24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image24Regular", "", 1, 24));
exports.Image24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image24Filled", "", 0, 24));
exports.Image28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image28Regular", "", 1, 28));
exports.Image28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image28Filled", "", 0, 28));
exports.Image32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image32Regular", "", 1, 32));
exports.Image32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image32Filled", "", 0, 32));
exports.Image48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image48Regular", "", 1, 48));
exports.Image48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Image48Filled", "", 0, 48));
