"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImmersiveReader48Filled = exports.ImmersiveReader48Regular = exports.ImmersiveReader32Light = exports.ImmersiveReader32Filled = exports.ImmersiveReader32Regular = exports.ImmersiveReader28Filled = exports.ImmersiveReader28Regular = exports.ImmersiveReader24Filled = exports.ImmersiveReader24Regular = exports.ImmersiveReader20Filled = exports.ImmersiveReader20Regular = exports.ImmersiveReader16Filled = exports.ImmersiveReader16Regular = exports.ImmersiveReaderRegular = exports.ImmersiveReaderFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ImmersiveReaderFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReaderFilled", "", 2, undefined));
exports.ImmersiveReaderRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReaderRegular", "", 2, undefined));
exports.ImmersiveReader16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader16Regular", "", 1, 16));
exports.ImmersiveReader16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader16Filled", "", 0, 16));
exports.ImmersiveReader20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader20Regular", "", 1, 20));
exports.ImmersiveReader20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader20Filled", "", 0, 20));
exports.ImmersiveReader24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader24Regular", "", 1, 24));
exports.ImmersiveReader24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader24Filled", "", 0, 24));
exports.ImmersiveReader28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader28Regular", "", 1, 28));
exports.ImmersiveReader28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader28Filled", "", 0, 28));
exports.ImmersiveReader32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader32Regular", "󰦽", 1, 32));
exports.ImmersiveReader32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader32Filled", "󰨺", 0, 32));
exports.ImmersiveReader32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader32Light", "", 3, 32));
exports.ImmersiveReader48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader48Regular", "󰦾", 1, 48));
exports.ImmersiveReader48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImmersiveReader48Filled", "󰨻", 0, 48));
