"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Important32Light = exports.Important32Filled = exports.Important32Regular = exports.Important28Filled = exports.Important28Regular = exports.Important24Filled = exports.Important24Regular = exports.Important20Filled = exports.Important20Regular = exports.Important16Filled = exports.Important16Regular = exports.Important12Filled = exports.Important12Regular = exports.ImportantRegular = exports.ImportantFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ImportantFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImportantFilled", "", 2, undefined));
exports.ImportantRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ImportantRegular", "", 2, undefined));
exports.Important12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important12Regular", "", 1, 12));
exports.Important12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important12Filled", "", 0, 12));
exports.Important16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important16Regular", "", 1, 16));
exports.Important16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important16Filled", "", 0, 16));
exports.Important20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important20Regular", "", 1, 20));
exports.Important20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important20Filled", "", 0, 20));
exports.Important24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important24Regular", "", 1, 24));
exports.Important24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important24Filled", "", 0, 24));
exports.Important28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important28Regular", "󰩽", 1, 28));
exports.Important28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important28Filled", "󰫹", 0, 28));
exports.Important32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important32Regular", "󰑄", 1, 32));
exports.Important32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important32Filled", "󰑗", 0, 32));
exports.Important32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Important32Light", "", 3, 32));
