"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Incognito48Filled = exports.Incognito48Regular = exports.Incognito32Filled = exports.Incognito32Regular = exports.Incognito24Filled = exports.Incognito24Regular = exports.Incognito20Filled = exports.Incognito20Regular = exports.IncognitoRegular = exports.IncognitoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.IncognitoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IncognitoFilled", "", 2, undefined));
exports.IncognitoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IncognitoRegular", "", 2, undefined));
exports.Incognito20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito20Regular", "", 1, 20));
exports.Incognito20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito20Filled", "", 0, 20));
exports.Incognito24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito24Regular", "", 1, 24));
exports.Incognito24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito24Filled", "", 0, 24));
exports.Incognito32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito32Regular", "󰦖", 1, 32));
exports.Incognito32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito32Filled", "󰨓", 0, 32));
exports.Incognito48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito48Regular", "󰦗", 1, 48));
exports.Incognito48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Incognito48Filled", "󰨔", 0, 48));
