"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Info48Filled = exports.Info48Regular = exports.Info32Filled = exports.Info32Regular = exports.Info28Filled = exports.Info28Regular = exports.Info24Filled = exports.Info24Regular = exports.Info20Filled = exports.Info20Regular = exports.Info16Filled = exports.Info16Regular = exports.Info12Filled = exports.Info12Regular = exports.InfoRegular = exports.InfoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.InfoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InfoFilled", "", 2, undefined));
exports.InfoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InfoRegular", "", 2, undefined));
exports.Info12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info12Regular", "", 1, 12));
exports.Info12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info12Filled", "", 0, 12));
exports.Info16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info16Regular", "", 1, 16));
exports.Info16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info16Filled", "", 0, 16));
exports.Info20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info20Regular", "", 1, 20));
exports.Info20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info20Filled", "", 0, 20));
exports.Info24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info24Regular", "", 1, 24));
exports.Info24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info24Filled", "", 0, 24));
exports.Info28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info28Regular", "", 1, 28));
exports.Info28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info28Filled", "", 0, 28));
exports.Info32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info32Regular", "󰁙", 1, 32));
exports.Info32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info32Filled", "󰁝", 0, 32));
exports.Info48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info48Regular", "󰁚", 1, 48));
exports.Info48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Info48Filled", "󰁞", 0, 48));
