"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InkStroke24Filled = exports.InkStroke24Regular = exports.InkStroke20Filled = exports.InkStroke20Regular = exports.InkStrokeRegular = exports.InkStrokeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.InkStrokeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkStrokeFilled", "", 2, undefined));
exports.InkStrokeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkStrokeRegular", "", 2, undefined));
exports.InkStroke20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkStroke20Regular", "", 1, 20));
exports.InkStroke20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkStroke20Filled", "", 0, 20));
exports.InkStroke24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkStroke24Regular", "", 1, 24));
exports.InkStroke24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkStroke24Filled", "", 0, 24));
