"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InkingTool32Filled = exports.InkingTool32Regular = exports.InkingTool24Filled = exports.InkingTool24Regular = exports.InkingTool20Filled = exports.InkingTool20Regular = exports.InkingTool16Filled = exports.InkingTool16Regular = exports.InkingToolRegular = exports.InkingToolFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.InkingToolFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingToolFilled", "", 2, undefined));
exports.InkingToolRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingToolRegular", "", 2, undefined));
exports.InkingTool16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool16Regular", "", 1, 16));
exports.InkingTool16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool16Filled", "", 0, 16));
exports.InkingTool20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool20Regular", "", 1, 20));
exports.InkingTool20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool20Filled", "", 0, 20));
exports.InkingTool24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool24Regular", "", 1, 24));
exports.InkingTool24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool24Filled", "", 0, 24));
exports.InkingTool32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool32Regular", "", 1, 32));
exports.InkingTool32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InkingTool32Filled", "", 0, 32));
