"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InprivateAccount28Filled = exports.InprivateAccount28Regular = exports.InprivateAccount24Filled = exports.InprivateAccount24Regular = exports.InprivateAccount20Filled = exports.InprivateAccount20Regular = exports.InprivateAccount16Filled = exports.InprivateAccount16Regular = exports.InprivateAccountRegular = exports.InprivateAccountFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.InprivateAccountFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccountFilled", "", 2, undefined));
exports.InprivateAccountRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccountRegular", "", 2, undefined));
exports.InprivateAccount16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount16Regular", "", 1, 16));
exports.InprivateAccount16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount16Filled", "", 0, 16));
exports.InprivateAccount20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount20Regular", "", 1, 20));
exports.InprivateAccount20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount20Filled", "", 0, 20));
exports.InprivateAccount24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount24Regular", "", 1, 24));
exports.InprivateAccount24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount24Filled", "", 0, 24));
exports.InprivateAccount28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount28Regular", "", 1, 28));
exports.InprivateAccount28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("InprivateAccount28Filled", "", 0, 28));
