"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IotAlert24Filled = exports.IotAlert24Regular = exports.IotAlert20Filled = exports.IotAlert20Regular = exports.IotAlert16Filled = exports.IotAlert16Regular = exports.IotAlertRegular = exports.IotAlertFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.IotAlertFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlertFilled", "", 2, undefined));
exports.IotAlertRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlertRegular", "", 2, undefined));
exports.IotAlert16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlert16Regular", "󰁜", 1, 16));
exports.IotAlert16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlert16Filled", "󰁠", 0, 16));
exports.IotAlert20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlert20Regular", "󰁝", 1, 20));
exports.IotAlert20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlert20Filled", "󰁡", 0, 20));
exports.IotAlert24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlert24Regular", "󰁞", 1, 24));
exports.IotAlert24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotAlert24Filled", "󰁢", 0, 24));
