"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Iot24Filled = exports.Iot24Regular = exports.Iot20Filled = exports.Iot20Regular = exports.Iot16Filled = exports.Iot16Regular = exports.IotRegular = exports.IotFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.IotFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotFilled", "", 2, undefined));
exports.IotRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("IotRegular", "", 2, undefined));
exports.Iot16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Iot16Regular", "󰁛", 1, 16));
exports.Iot16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Iot16Filled", "󰁟", 0, 16));
exports.Iot20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Iot20Regular", "", 1, 20));
exports.Iot20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Iot20Filled", "", 0, 20));
exports.Iot24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Iot24Regular", "", 1, 24));
exports.Iot24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Iot24Filled", "", 0, 24));
