"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ItemCompare48Filled = exports.ItemCompare48Regular = exports.ItemCompare32Filled = exports.ItemCompare32Regular = exports.ItemCompare28Filled = exports.ItemCompare28Regular = exports.ItemCompare24Filled = exports.ItemCompare24Regular = exports.ItemCompare20Filled = exports.ItemCompare20Regular = exports.ItemCompare16Filled = exports.ItemCompare16Regular = exports.ItemCompareRegular = exports.ItemCompareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ItemCompareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompareFilled", "", 2, undefined));
exports.ItemCompareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompareRegular", "", 2, undefined));
exports.ItemCompare16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare16Regular", "󰫃", 1, 16));
exports.ItemCompare16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare16Filled", "󰭁", 0, 16));
exports.ItemCompare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare20Regular", "󰫄", 1, 20));
exports.ItemCompare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare20Filled", "󰭂", 0, 20));
exports.ItemCompare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare24Regular", "󰫅", 1, 24));
exports.ItemCompare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare24Filled", "󰭃", 0, 24));
exports.ItemCompare28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare28Regular", "󰫆", 1, 28));
exports.ItemCompare28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare28Filled", "󰭄", 0, 28));
exports.ItemCompare32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare32Regular", "󰫇", 1, 32));
exports.ItemCompare32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare32Filled", "󰭅", 0, 32));
exports.ItemCompare48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare48Regular", "󰫈", 1, 48));
exports.ItemCompare48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ItemCompare48Filled", "󰭆", 0, 48));
