"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Javascript24Filled = exports.Javascript24Regular = exports.Javascript20Filled = exports.Javascript20Regular = exports.Javascript16Filled = exports.Javascript16Regular = exports.JavascriptRegular = exports.JavascriptFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.JavascriptFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("JavascriptFilled", "", 2, undefined));
exports.JavascriptRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("JavascriptRegular", "", 2, undefined));
exports.Javascript16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Javascript16Regular", "", 1, 16));
exports.Javascript16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Javascript16Filled", "", 0, 16));
exports.Javascript20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Javascript20Regular", "", 1, 20));
exports.Javascript20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Javascript20Filled", "", 0, 20));
exports.Javascript24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Javascript24Regular", "", 1, 24));
exports.Javascript24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Javascript24Filled", "", 0, 24));
