"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Key32Filled = exports.Key32Regular = exports.Key24Filled = exports.Key24Regular = exports.Key20Filled = exports.Key20Regular = exports.Key16Filled = exports.Key16Regular = exports.KeyRegular = exports.KeyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.KeyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyFilled", "", 2, undefined));
exports.KeyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyRegular", "", 2, undefined));
exports.Key16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key16Regular", "", 1, 16));
exports.Key16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key16Filled", "", 0, 16));
exports.Key20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key20Regular", "", 1, 20));
exports.Key20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key20Filled", "", 0, 20));
exports.Key24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key24Regular", "", 1, 24));
exports.Key24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key24Filled", "", 0, 24));
exports.Key32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key32Regular", "", 1, 32));
exports.Key32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Key32Filled", "", 0, 32));
