"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyboardShift24Filled = exports.KeyboardShift24Regular = exports.KeyboardShift20Filled = exports.KeyboardShift20Regular = exports.KeyboardShift16Filled = exports.KeyboardShift16Regular = exports.KeyboardShiftRegular = exports.KeyboardShiftFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.KeyboardShiftFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShiftFilled", "", 2, undefined));
exports.KeyboardShiftRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShiftRegular", "", 2, undefined));
exports.KeyboardShift16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShift16Regular", "", 1, 16));
exports.KeyboardShift16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShift16Filled", "", 0, 16));
exports.KeyboardShift20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShift20Regular", "", 1, 20));
exports.KeyboardShift20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShift20Filled", "", 0, 20));
exports.KeyboardShift24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShift24Regular", "", 1, 24));
exports.KeyboardShift24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardShift24Filled", "", 0, 24));
