"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyboardDock24Filled = exports.KeyboardDock24Regular = exports.KeyboardDock20Filled = exports.KeyboardDock20Regular = exports.KeyboardDockRegular = exports.KeyboardDockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.KeyboardDockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardDockFilled", "", 2, undefined));
exports.KeyboardDockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardDockRegular", "", 2, undefined));
exports.KeyboardDock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardDock20Regular", "", 1, 20));
exports.KeyboardDock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardDock20Filled", "", 0, 20));
exports.KeyboardDock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardDock24Regular", "", 1, 24));
exports.KeyboardDock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("KeyboardDock24Filled", "", 0, 24));
