"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LaptopShield20Filled = exports.LaptopShield20Regular = exports.LaptopShield16Filled = exports.LaptopShield16Regular = exports.LaptopShieldRegular = exports.LaptopShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LaptopShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopShieldFilled", "", 2, undefined));
exports.LaptopShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopShieldRegular", "", 2, undefined));
exports.LaptopShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopShield16Regular", "󰆏", 1, 16));
exports.LaptopShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopShield16Filled", "󰆏", 0, 16));
exports.LaptopShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopShield20Regular", "󰆐", 1, 20));
exports.LaptopShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopShield20Filled", "󰆐", 0, 20));
