"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LaptopDismiss20Filled = exports.LaptopDismiss20Regular = exports.LaptopDismiss16Filled = exports.LaptopDismiss16Regular = exports.LaptopDismissRegular = exports.LaptopDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LaptopDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopDismissFilled", "", 2, undefined));
exports.LaptopDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopDismissRegular", "", 2, undefined));
exports.LaptopDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopDismiss16Regular", "", 1, 16));
exports.LaptopDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopDismiss16Filled", "", 0, 16));
exports.LaptopDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopDismiss20Regular", "", 1, 20));
exports.LaptopDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LaptopDismiss20Filled", "", 0, 20));
