"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Layer24Filled = exports.Layer24Regular = exports.Layer20Filled = exports.Layer20Regular = exports.LayerRegular = exports.LayerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LayerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayerFilled", "", 2, undefined));
exports.LayerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayerRegular", "", 2, undefined));
exports.Layer20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Layer20Regular", "", 1, 20));
exports.Layer20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Layer20Filled", "", 0, 20));
exports.Layer24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Layer24Regular", "", 1, 24));
exports.Layer24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Layer24Filled", "", 0, 24));
