"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LayoutRowTwo48Filled = exports.LayoutRowTwo48Regular = exports.LayoutRowTwo32Light = exports.LayoutRowTwo32Filled = exports.LayoutRowTwo32Regular = exports.LayoutRowTwo28Filled = exports.LayoutRowTwo28Regular = exports.LayoutRowTwo24Filled = exports.LayoutRowTwo24Regular = exports.LayoutRowTwo20Filled = exports.LayoutRowTwo20Regular = exports.LayoutRowTwo16Filled = exports.LayoutRowTwo16Regular = exports.LayoutRowTwoRegular = exports.LayoutRowTwoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LayoutRowTwoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwoFilled", "", 2, undefined));
exports.LayoutRowTwoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwoRegular", "", 2, undefined));
exports.LayoutRowTwo16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo16Regular", "󰒧", 1, 16));
exports.LayoutRowTwo16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo16Filled", "󰔈", 0, 16));
exports.LayoutRowTwo20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo20Regular", "󰒨", 1, 20));
exports.LayoutRowTwo20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo20Filled", "󰔉", 0, 20));
exports.LayoutRowTwo24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo24Regular", "󰒩", 1, 24));
exports.LayoutRowTwo24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo24Filled", "󰔊", 0, 24));
exports.LayoutRowTwo28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo28Regular", "󰗾", 1, 28));
exports.LayoutRowTwo28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo28Filled", "󰙺", 0, 28));
exports.LayoutRowTwo32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo32Regular", "󰗘", 1, 32));
exports.LayoutRowTwo32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo32Filled", "󰙓", 0, 32));
exports.LayoutRowTwo32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo32Light", "", 3, 32));
exports.LayoutRowTwo48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo48Regular", "󰗿", 1, 48));
exports.LayoutRowTwo48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LayoutRowTwo48Filled", "󰙻", 0, 48));
