"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LightbulbCircle24Filled = exports.LightbulbCircle24Regular = exports.LightbulbCircle20Filled = exports.LightbulbCircle20Regular = exports.LightbulbCircleRegular = exports.LightbulbCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LightbulbCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbCircleFilled", "", 2, undefined));
exports.LightbulbCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbCircleRegular", "", 2, undefined));
exports.LightbulbCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbCircle20Regular", "", 1, 20));
exports.LightbulbCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbCircle20Filled", "", 0, 20));
exports.LightbulbCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbCircle24Regular", "", 1, 24));
exports.LightbulbCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbCircle24Filled", "", 0, 24));
