"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Lightbulb48Filled = exports.Lightbulb48Regular = exports.Lightbulb32Light = exports.Lightbulb32Filled = exports.Lightbulb32Regular = exports.Lightbulb28Filled = exports.Lightbulb28Regular = exports.Lightbulb24Filled = exports.Lightbulb24Regular = exports.Lightbulb20Filled = exports.Lightbulb20Regular = exports.Lightbulb16Filled = exports.Lightbulb16Regular = exports.LightbulbRegular = exports.LightbulbFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LightbulbFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbFilled", "", 2, undefined));
exports.LightbulbRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LightbulbRegular", "", 2, undefined));
exports.Lightbulb16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb16Regular", "", 1, 16));
exports.Lightbulb16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb16Filled", "", 0, 16));
exports.Lightbulb20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb20Regular", "", 1, 20));
exports.Lightbulb20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb20Filled", "", 0, 20));
exports.Lightbulb24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb24Regular", "", 1, 24));
exports.Lightbulb24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb24Filled", "", 0, 24));
exports.Lightbulb28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb28Regular", "", 1, 28));
exports.Lightbulb28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb28Filled", "", 0, 28));
exports.Lightbulb32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb32Regular", "", 1, 32));
exports.Lightbulb32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb32Filled", "", 0, 32));
exports.Lightbulb32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb32Light", "", 3, 32));
exports.Lightbulb48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb48Regular", "", 1, 48));
exports.Lightbulb48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lightbulb48Filled", "", 0, 48));
