"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinkSquare24Filled = exports.LinkSquare24Regular = exports.LinkSquare20Filled = exports.LinkSquare20Regular = exports.LinkSquare16Filled = exports.LinkSquare16Regular = exports.LinkSquare12Filled = exports.LinkSquare12Regular = exports.LinkSquareRegular = exports.LinkSquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LinkSquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquareFilled", "", 2, undefined));
exports.LinkSquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquareRegular", "", 2, undefined));
exports.LinkSquare12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare12Regular", "", 1, 12));
exports.LinkSquare12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare12Filled", "", 0, 12));
exports.LinkSquare16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare16Regular", "", 1, 16));
exports.LinkSquare16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare16Filled", "", 0, 16));
exports.LinkSquare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare20Regular", "", 1, 20));
exports.LinkSquare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare20Filled", "", 0, 20));
exports.LinkSquare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare24Regular", "", 1, 24));
exports.LinkSquare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkSquare24Filled", "", 0, 24));
