"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinkDismiss24Filled = exports.LinkDismiss24Regular = exports.LinkDismiss20Filled = exports.LinkDismiss20Regular = exports.LinkDismiss16Filled = exports.LinkDismiss16Regular = exports.LinkDismissRegular = exports.LinkDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LinkDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismissFilled", "", 2, undefined));
exports.LinkDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismissRegular", "", 2, undefined));
exports.LinkDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismiss16Regular", "", 1, 16));
exports.LinkDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismiss16Filled", "", 0, 16));
exports.LinkDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismiss20Regular", "", 1, 20));
exports.LinkDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismiss20Filled", "", 0, 20));
exports.LinkDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismiss24Regular", "", 1, 24));
exports.LinkDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkDismiss24Filled", "", 0, 24));
