"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Link48Filled = exports.Link48Regular = exports.Link32Light = exports.Link32Filled = exports.Link32Regular = exports.Link28Filled = exports.Link28Regular = exports.Link24Filled = exports.Link24Regular = exports.Link20Filled = exports.Link20Regular = exports.Link16Filled = exports.Link16Regular = exports.Link12Filled = exports.Link12Regular = exports.LinkRegular = exports.LinkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LinkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkFilled", "", 2, undefined));
exports.LinkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LinkRegular", "", 2, undefined));
exports.Link12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link12Regular", "", 1, 12));
exports.Link12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link12Filled", "", 0, 12));
exports.Link16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link16Regular", "", 1, 16));
exports.Link16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link16Filled", "", 0, 16));
exports.Link20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link20Regular", "", 1, 20));
exports.Link20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link20Filled", "", 0, 20));
exports.Link24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link24Regular", "", 1, 24));
exports.Link24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link24Filled", "", 0, 24));
exports.Link28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link28Regular", "", 1, 28));
exports.Link28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link28Filled", "", 0, 28));
exports.Link32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link32Regular", "", 1, 32));
exports.Link32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link32Filled", "", 0, 32));
exports.Link32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link32Light", "", 3, 32));
exports.Link48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link48Regular", "", 1, 48));
exports.Link48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Link48Filled", "", 0, 48));
