"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListRtl20Filled = exports.ListRtl20Regular = exports.ListRtl16Filled = exports.ListRtl16Regular = exports.ListRtlRegular = exports.ListRtlFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ListRtlFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ListRtlFilled", "", 2, undefined));
exports.ListRtlRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ListRtlRegular", "", 2, undefined));
exports.ListRtl16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ListRtl16Regular", "󰆗", 1, 16));
exports.ListRtl16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ListRtl16Filled", "󰆗", 0, 16));
exports.ListRtl20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ListRtl20Regular", "󰆘", 1, 20));
exports.ListRtl20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ListRtl20Filled", "󰆘", 0, 20));
