"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Live24Filled = exports.Live24Regular = exports.Live20Filled = exports.Live20Regular = exports.LiveRegular = exports.LiveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LiveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LiveFilled", "", 2, undefined));
exports.LiveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LiveRegular", "", 2, undefined));
exports.Live20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Live20Regular", "", 1, 20));
exports.Live20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Live20Filled", "", 0, 20));
exports.Live24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Live24Regular", "", 1, 24));
exports.Live24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Live24Filled", "", 0, 24));
