"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocationArrow48Filled = exports.LocationArrow48Regular = exports.LocationArrow32Filled = exports.LocationArrow32Regular = exports.LocationArrow28Filled = exports.LocationArrow28Regular = exports.LocationArrow24Filled = exports.LocationArrow24Regular = exports.LocationArrow20Filled = exports.LocationArrow20Regular = exports.LocationArrow16Filled = exports.LocationArrow16Regular = exports.LocationArrow12Filled = exports.LocationArrow12Regular = exports.LocationArrowRegular = exports.LocationArrowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LocationArrowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrowFilled", "", 2, undefined));
exports.LocationArrowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrowRegular", "", 2, undefined));
exports.LocationArrow12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow12Regular", "󰁣", 1, 12));
exports.LocationArrow12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow12Filled", "󰁧", 0, 12));
exports.LocationArrow16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow16Regular", "󰁤", 1, 16));
exports.LocationArrow16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow16Filled", "󰁨", 0, 16));
exports.LocationArrow20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow20Regular", "󰁥", 1, 20));
exports.LocationArrow20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow20Filled", "󰁩", 0, 20));
exports.LocationArrow24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow24Regular", "󰁦", 1, 24));
exports.LocationArrow24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow24Filled", "󰁪", 0, 24));
exports.LocationArrow28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow28Regular", "󰁧", 1, 28));
exports.LocationArrow28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow28Filled", "󰁫", 0, 28));
exports.LocationArrow32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow32Regular", "󰁨", 1, 32));
exports.LocationArrow32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow32Filled", "󰁬", 0, 32));
exports.LocationArrow48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow48Regular", "󰁩", 1, 48));
exports.LocationArrow48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LocationArrow48Filled", "󰁭", 0, 48));
