"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LockClosed48Filled = exports.LockClosed48Regular = exports.LockClosed32Light = exports.LockClosed32Filled = exports.LockClosed32Regular = exports.LockClosed28Filled = exports.LockClosed28Regular = exports.LockClosed24Filled = exports.LockClosed24Regular = exports.LockClosed20Filled = exports.LockClosed20Regular = exports.LockClosed16Filled = exports.LockClosed16Regular = exports.LockClosed12Filled = exports.LockClosed12Regular = exports.LockClosedRegular = exports.LockClosedFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LockClosedFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosedFilled", "", 2, undefined));
exports.LockClosedRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosedRegular", "", 2, undefined));
exports.LockClosed12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed12Regular", "", 1, 12));
exports.LockClosed12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed12Filled", "", 0, 12));
exports.LockClosed16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed16Regular", "", 1, 16));
exports.LockClosed16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed16Filled", "", 0, 16));
exports.LockClosed20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed20Regular", "", 1, 20));
exports.LockClosed20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed20Filled", "", 0, 20));
exports.LockClosed24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed24Regular", "", 1, 24));
exports.LockClosed24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed24Filled", "", 0, 24));
exports.LockClosed28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed28Regular", "󰈟", 1, 28));
exports.LockClosed28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed28Filled", "󰈲", 0, 28));
exports.LockClosed32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed32Regular", "", 1, 32));
exports.LockClosed32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed32Filled", "", 0, 32));
exports.LockClosed32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed32Light", "", 3, 32));
exports.LockClosed48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed48Regular", "󰈠", 1, 48));
exports.LockClosed48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockClosed48Filled", "󰈳", 0, 48));
