"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LockOpen48Filled = exports.LockOpen48Regular = exports.LockOpen32Light = exports.LockOpen32Filled = exports.LockOpen32Regular = exports.LockOpen28Filled = exports.LockOpen28Regular = exports.LockOpen24Filled = exports.LockOpen24Regular = exports.LockOpen20Filled = exports.LockOpen20Regular = exports.LockOpen16Filled = exports.LockOpen16Regular = exports.LockOpen12Filled = exports.LockOpen12Regular = exports.LockOpenRegular = exports.LockOpenFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LockOpenFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpenFilled", "", 2, undefined));
exports.LockOpenRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpenRegular", "", 2, undefined));
exports.LockOpen12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen12Regular", "󰈡", 1, 12));
exports.LockOpen12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen12Filled", "󰈴", 0, 12));
exports.LockOpen16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen16Regular", "", 1, 16));
exports.LockOpen16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen16Filled", "", 0, 16));
exports.LockOpen20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen20Regular", "", 1, 20));
exports.LockOpen20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen20Filled", "", 0, 20));
exports.LockOpen24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen24Regular", "", 1, 24));
exports.LockOpen24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen24Filled", "", 0, 24));
exports.LockOpen28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen28Regular", "", 1, 28));
exports.LockOpen28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen28Filled", "", 0, 28));
exports.LockOpen32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen32Regular", "󰈢", 1, 32));
exports.LockOpen32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen32Filled", "󰈵", 0, 32));
exports.LockOpen32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen32Light", "", 3, 32));
exports.LockOpen48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen48Regular", "󰈣", 1, 48));
exports.LockOpen48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockOpen48Filled", "󰈶", 0, 48));
