"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LockShield48Filled = exports.LockShield48Regular = exports.LockShield32Filled = exports.LockShield32Regular = exports.LockShield28Filled = exports.LockShield28Regular = exports.LockShield24Filled = exports.LockShield24Regular = exports.LockShield20Filled = exports.LockShield20Regular = exports.LockShield16Filled = exports.LockShield16Regular = exports.LockShieldRegular = exports.LockShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LockShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShieldFilled", "", 2, undefined));
exports.LockShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShieldRegular", "", 2, undefined));
exports.LockShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield16Regular", "󰐇", 1, 16));
exports.LockShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield16Filled", "󰐚", 0, 16));
exports.LockShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield20Regular", "", 1, 20));
exports.LockShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield20Filled", "", 0, 20));
exports.LockShield24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield24Regular", "", 1, 24));
exports.LockShield24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield24Filled", "", 0, 24));
exports.LockShield28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield28Regular", "󰐈", 1, 28));
exports.LockShield28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield28Filled", "󰐛", 0, 28));
exports.LockShield32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield32Regular", "󰐉", 1, 32));
exports.LockShield32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield32Filled", "󰐜", 0, 32));
exports.LockShield48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield48Regular", "", 1, 48));
exports.LockShield48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LockShield48Filled", "", 0, 48));
