"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Lottery24Filled = exports.Lottery24Regular = exports.Lottery20Filled = exports.Lottery20Regular = exports.LotteryRegular = exports.LotteryFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LotteryFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LotteryFilled", "", 2, undefined));
exports.LotteryRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LotteryRegular", "", 2, undefined));
exports.Lottery20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lottery20Regular", "", 1, 20));
exports.Lottery20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lottery20Filled", "", 0, 20));
exports.Lottery24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lottery24Regular", "", 1, 24));
exports.Lottery24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Lottery24Filled", "", 0, 24));
