"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Luggage48Filled = exports.Luggage48Regular = exports.Luggage32Filled = exports.Luggage32Regular = exports.Luggage28Filled = exports.Luggage28Regular = exports.Luggage24Filled = exports.Luggage24Regular = exports.Luggage20Filled = exports.Luggage20Regular = exports.Luggage16Filled = exports.Luggage16Regular = exports.LuggageRegular = exports.LuggageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.LuggageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LuggageFilled", "", 2, undefined));
exports.LuggageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("LuggageRegular", "", 2, undefined));
exports.Luggage16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage16Regular", "", 1, 16));
exports.Luggage16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage16Filled", "", 0, 16));
exports.Luggage20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage20Regular", "", 1, 20));
exports.Luggage20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage20Filled", "", 0, 20));
exports.Luggage24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage24Regular", "", 1, 24));
exports.Luggage24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage24Filled", "", 0, 24));
exports.Luggage28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage28Regular", "", 1, 28));
exports.Luggage28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage28Filled", "", 0, 28));
exports.Luggage32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage32Regular", "", 1, 32));
exports.Luggage32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage32Filled", "", 0, 32));
exports.Luggage48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage48Regular", "", 1, 48));
exports.Luggage48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Luggage48Filled", "", 0, 48));
