"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MailLink24Filled = exports.MailLink24Regular = exports.MailLink20Filled = exports.MailLink20Regular = exports.MailLinkRegular = exports.MailLinkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MailLinkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailLinkFilled", "", 2, undefined));
exports.MailLinkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailLinkRegular", "", 2, undefined));
exports.MailLink20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailLink20Regular", "", 1, 20));
exports.MailLink20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailLink20Filled", "", 0, 20));
exports.MailLink24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailLink24Regular", "", 1, 24));
exports.MailLink24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailLink24Filled", "", 0, 24));
