"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MailAlert32Light = exports.MailAlert32Filled = exports.MailAlert32Regular = exports.MailAlert28Filled = exports.MailAlert28Regular = exports.MailAlert24Filled = exports.MailAlert24Regular = exports.MailAlert20Filled = exports.MailAlert20Regular = exports.MailAlert16Filled = exports.MailAlert16Regular = exports.MailAlertRegular = exports.MailAlertFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MailAlertFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlertFilled", "", 2, undefined));
exports.MailAlertRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlertRegular", "", 2, undefined));
exports.MailAlert16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert16Regular", "", 1, 16));
exports.MailAlert16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert16Filled", "", 0, 16));
exports.MailAlert20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert20Regular", "", 1, 20));
exports.MailAlert20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert20Filled", "", 0, 20));
exports.MailAlert24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert24Regular", "", 1, 24));
exports.MailAlert24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert24Filled", "", 0, 24));
exports.MailAlert28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert28Regular", "", 1, 28));
exports.MailAlert28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert28Filled", "", 0, 28));
exports.MailAlert32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert32Regular", "󰗱", 1, 32));
exports.MailAlert32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert32Filled", "󰙭", 0, 32));
exports.MailAlert32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAlert32Light", "", 3, 32));
