"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MailClock32Filled = exports.MailClock32Regular = exports.MailClock24Filled = exports.MailClock24Regular = exports.MailClock20Filled = exports.MailClock20Regular = exports.MailClock16Filled = exports.MailClock16Regular = exports.MailClockRegular = exports.MailClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MailClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClockFilled", "", 2, undefined));
exports.MailClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClockRegular", "", 2, undefined));
exports.MailClock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock16Regular", "", 1, 16));
exports.MailClock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock16Filled", "", 0, 16));
exports.MailClock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock20Regular", "", 1, 20));
exports.MailClock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock20Filled", "", 0, 20));
exports.MailClock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock24Regular", "", 1, 24));
exports.MailClock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock24Filled", "", 0, 24));
exports.MailClock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock32Regular", "󰡪", 1, 32));
exports.MailClock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailClock32Filled", "󰣧", 0, 32));
