"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MailAttach28Filled = exports.MailAttach28Regular = exports.MailAttach24Filled = exports.MailAttach24Regular = exports.MailAttach20Filled = exports.MailAttach20Regular = exports.MailAttach16Filled = exports.MailAttach16Regular = exports.MailAttachRegular = exports.MailAttachFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MailAttachFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttachFilled", "", 2, undefined));
exports.MailAttachRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttachRegular", "", 2, undefined));
exports.MailAttach16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach16Regular", "", 1, 16));
exports.MailAttach16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach16Filled", "", 0, 16));
exports.MailAttach20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach20Regular", "", 1, 20));
exports.MailAttach20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach20Filled", "", 0, 20));
exports.MailAttach24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach24Regular", "", 1, 24));
exports.MailAttach24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach24Filled", "", 0, 24));
exports.MailAttach28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach28Regular", "", 1, 28));
exports.MailAttach28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailAttach28Filled", "", 0, 28));
