"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MailEdit32Light = exports.MailEdit32Filled = exports.MailEdit32Regular = exports.MailEdit24Filled = exports.MailEdit24Regular = exports.MailEdit20Filled = exports.MailEdit20Regular = exports.MailEditRegular = exports.MailEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MailEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEditFilled", "", 2, undefined));
exports.MailEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEditRegular", "", 2, undefined));
exports.MailEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit20Regular", "", 1, 20));
exports.MailEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit20Filled", "", 0, 20));
exports.MailEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit24Regular", "", 1, 24));
exports.MailEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit24Filled", "", 0, 24));
exports.MailEdit32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit32Regular", "󰖭", 1, 32));
exports.MailEdit32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit32Filled", "󰘦", 0, 32));
exports.MailEdit32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MailEdit32Light", "", 3, 32));
