"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MathFormula32Filled = exports.MathFormula32Regular = exports.MathFormula24Filled = exports.MathFormula24Regular = exports.MathFormula20Filled = exports.MathFormula20Regular = exports.MathFormula16Filled = exports.MathFormula16Regular = exports.MathFormulaRegular = exports.MathFormulaFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MathFormulaFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormulaFilled", "", 2, undefined));
exports.MathFormulaRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormulaRegular", "", 2, undefined));
exports.MathFormula16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula16Regular", "", 1, 16));
exports.MathFormula16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula16Filled", "", 0, 16));
exports.MathFormula20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula20Regular", "", 1, 20));
exports.MathFormula20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula20Filled", "", 0, 20));
exports.MathFormula24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula24Regular", "", 1, 24));
exports.MathFormula24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula24Filled", "", 0, 24));
exports.MathFormula32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula32Regular", "", 1, 32));
exports.MathFormula32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MathFormula32Filled", "", 0, 32));
