"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MegaphoneLoud48Filled = exports.MegaphoneLoud48Regular = exports.MegaphoneLoud32Filled = exports.MegaphoneLoud32Regular = exports.MegaphoneLoud28Filled = exports.MegaphoneLoud28Regular = exports.MegaphoneLoud24Filled = exports.MegaphoneLoud24Regular = exports.MegaphoneLoud20Filled = exports.MegaphoneLoud20Regular = exports.MegaphoneLoud16Filled = exports.MegaphoneLoud16Regular = exports.MegaphoneLoudRegular = exports.MegaphoneLoudFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MegaphoneLoudFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoudFilled", "", 2, undefined));
exports.MegaphoneLoudRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoudRegular", "", 2, undefined));
exports.MegaphoneLoud16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud16Regular", "", 1, 16));
exports.MegaphoneLoud16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud16Filled", "", 0, 16));
exports.MegaphoneLoud20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud20Regular", "", 1, 20));
exports.MegaphoneLoud20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud20Filled", "", 0, 20));
exports.MegaphoneLoud24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud24Regular", "", 1, 24));
exports.MegaphoneLoud24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud24Filled", "", 0, 24));
exports.MegaphoneLoud28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud28Regular", "", 1, 28));
exports.MegaphoneLoud28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud28Filled", "", 0, 28));
exports.MegaphoneLoud32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud32Regular", "", 1, 32));
exports.MegaphoneLoud32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud32Filled", "", 0, 32));
exports.MegaphoneLoud48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud48Regular", "󰧚", 1, 48));
exports.MegaphoneLoud48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneLoud48Filled", "󰩗", 0, 48));
