"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MegaphoneCircle24Filled = exports.MegaphoneCircle24Regular = exports.MegaphoneCircle20Filled = exports.MegaphoneCircle20Regular = exports.MegaphoneCircleRegular = exports.MegaphoneCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MegaphoneCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneCircleFilled", "", 2, undefined));
exports.MegaphoneCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneCircleRegular", "", 2, undefined));
exports.MegaphoneCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneCircle20Regular", "", 1, 20));
exports.MegaphoneCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneCircle20Filled", "", 0, 20));
exports.MegaphoneCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneCircle24Regular", "", 1, 24));
exports.MegaphoneCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MegaphoneCircle24Filled", "", 0, 24));
