"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MicSparkle24Filled = exports.MicSparkle24Regular = exports.MicSparkle20Filled = exports.MicSparkle20Regular = exports.MicSparkle16Filled = exports.MicSparkle16Regular = exports.MicSparkleRegular = exports.MicSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MicSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkleFilled", "", 2, undefined));
exports.MicSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkleRegular", "", 2, undefined));
exports.MicSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkle16Regular", "", 1, 16));
exports.MicSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkle16Filled", "", 0, 16));
exports.MicSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkle20Regular", "", 1, 20));
exports.MicSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkle20Filled", "", 0, 20));
exports.MicSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkle24Regular", "", 1, 24));
exports.MicSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicSparkle24Filled", "", 0, 24));
