"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MicRecord28Filled = exports.MicRecord28Regular = exports.MicRecord24Filled = exports.MicRecord24Regular = exports.MicRecord20Filled = exports.MicRecord20Regular = exports.MicRecord16Filled = exports.MicRecord16Regular = exports.MicRecordRegular = exports.MicRecordFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MicRecordFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecordFilled", "", 2, undefined));
exports.MicRecordRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecordRegular", "", 2, undefined));
exports.MicRecord16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord16Regular", "󰨫", 1, 16));
exports.MicRecord16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord16Filled", "󰪧", 0, 16));
exports.MicRecord20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord20Regular", "󰋂", 1, 20));
exports.MicRecord20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord20Filled", "󰋕", 0, 20));
exports.MicRecord24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord24Regular", "󰋃", 1, 24));
exports.MicRecord24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord24Filled", "󰋖", 0, 24));
exports.MicRecord28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord28Regular", "󰋄", 1, 28));
exports.MicRecord28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRecord28Filled", "󰋗", 0, 28));
