"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MicOff48Filled = exports.MicOff48Regular = exports.MicOff32Filled = exports.MicOff32Regular = exports.MicOff28Filled = exports.MicOff28Regular = exports.MicOff24Filled = exports.MicOff24Regular = exports.MicOff20Filled = exports.MicOff20Regular = exports.MicOff16Filled = exports.MicOff16Regular = exports.MicOff12Filled = exports.MicOff12Regular = exports.MicOffRegular = exports.MicOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MicOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOffFilled", "", 2, undefined));
exports.MicOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOffRegular", "", 2, undefined));
exports.MicOff12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff12Regular", "", 1, 12));
exports.MicOff12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff12Filled", "", 0, 12));
exports.MicOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff16Regular", "", 1, 16));
exports.MicOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff16Filled", "", 0, 16));
exports.MicOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff20Regular", "", 1, 20));
exports.MicOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff20Filled", "", 0, 20));
exports.MicOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff24Regular", "", 1, 24));
exports.MicOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff24Filled", "", 0, 24));
exports.MicOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff28Regular", "", 1, 28));
exports.MicOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff28Filled", "", 0, 28));
exports.MicOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff32Regular", "", 1, 32));
exports.MicOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff32Filled", "", 0, 32));
exports.MicOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff48Regular", "", 1, 48));
exports.MicOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicOff48Filled", "", 0, 48));
