"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mic48Filled = exports.Mic48Regular = exports.Mic32Light = exports.Mic32Filled = exports.Mic32Regular = exports.Mic28Filled = exports.Mic28Regular = exports.Mic24Filled = exports.Mic24Regular = exports.Mic20Filled = exports.Mic20Regular = exports.Mic16Filled = exports.Mic16Regular = exports.MicRegular = exports.MicFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MicFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicFilled", "", 2, undefined));
exports.MicRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicRegular", "", 2, undefined));
exports.Mic16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic16Regular", "", 1, 16));
exports.Mic16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic16Filled", "", 0, 16));
exports.Mic20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic20Regular", "", 1, 20));
exports.Mic20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic20Filled", "", 0, 20));
exports.Mic24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic24Regular", "", 1, 24));
exports.Mic24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic24Filled", "", 0, 24));
exports.Mic28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic28Regular", "", 1, 28));
exports.Mic28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic28Filled", "", 0, 28));
exports.Mic32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic32Regular", "", 1, 32));
exports.Mic32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic32Filled", "", 0, 32));
exports.Mic32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic32Light", "", 3, 32));
exports.Mic48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic48Regular", "", 1, 48));
exports.Mic48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mic48Filled", "", 0, 48));
