"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Microwave20Filled = exports.Microwave20Regular = exports.Microwave16Filled = exports.Microwave16Regular = exports.MicrowaveRegular = exports.MicrowaveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MicrowaveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicrowaveFilled", "", 2, undefined));
exports.MicrowaveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicrowaveRegular", "", 2, undefined));
exports.Microwave16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microwave16Regular", "󰬉", 1, 16));
exports.Microwave16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microwave16Filled", "󰮇", 0, 16));
exports.Microwave20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microwave20Regular", "󰬊", 1, 20));
exports.Microwave20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microwave20Filled", "󰮈", 0, 20));
