"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Microscope32Filled = exports.Microscope32Regular = exports.Microscope24Filled = exports.Microscope24Regular = exports.Microscope20Filled = exports.Microscope20Regular = exports.MicroscopeRegular = exports.MicroscopeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MicroscopeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicroscopeFilled", "", 2, undefined));
exports.MicroscopeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MicroscopeRegular", "", 2, undefined));
exports.Microscope20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microscope20Regular", "", 1, 20));
exports.Microscope20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microscope20Filled", "", 0, 20));
exports.Microscope24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microscope24Regular", "", 1, 24));
exports.Microscope24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microscope24Filled", "", 0, 24));
exports.Microscope32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microscope32Regular", "󰛄", 1, 32));
exports.Microscope32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Microscope32Filled", "󰝁", 0, 32));
