"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mold28Filled = exports.Mold28Regular = exports.Mold24Filled = exports.Mold24Regular = exports.Mold20Filled = exports.Mold20Regular = exports.MoldRegular = exports.MoldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MoldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoldFilled", "", 2, undefined));
exports.MoldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoldRegular", "", 2, undefined));
exports.Mold20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mold20Regular", "󰄮", 1, 20));
exports.Mold20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mold20Filled", "󰄭", 0, 20));
exports.Mold24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mold24Regular", "󰄯", 1, 24));
exports.Mold24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mold24Filled", "󰄮", 0, 24));
exports.Mold28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mold28Regular", "󰄰", 1, 28));
exports.Mold28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Mold28Filled", "󰄯", 0, 28));
