"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MoneyDismiss24Filled = exports.MoneyDismiss24Regular = exports.MoneyDismiss20Filled = exports.MoneyDismiss20Regular = exports.MoneyDismissRegular = exports.MoneyDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MoneyDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoneyDismissFilled", "", 2, undefined));
exports.MoneyDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoneyDismissRegular", "", 2, undefined));
exports.MoneyDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoneyDismiss20Regular", "", 1, 20));
exports.MoneyDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoneyDismiss20Filled", "", 0, 20));
exports.MoneyDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoneyDismiss24Regular", "", 1, 24));
exports.MoneyDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoneyDismiss24Filled", "", 0, 24));
