"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MoreCircle48Filled = exports.MoreCircle48Regular = exports.MoreCircle32Filled = exports.MoreCircle32Regular = exports.MoreCircle28Filled = exports.MoreCircle28Regular = exports.MoreCircle24Filled = exports.MoreCircle24Regular = exports.MoreCircle20Filled = exports.MoreCircle20Regular = exports.MoreCircle16Filled = exports.MoreCircle16Regular = exports.MoreCircleRegular = exports.MoreCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MoreCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircleFilled", "", 2, undefined));
exports.MoreCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircleRegular", "", 2, undefined));
exports.MoreCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle16Regular", "", 1, 16));
exports.MoreCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle16Filled", "", 0, 16));
exports.MoreCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle20Regular", "", 1, 20));
exports.MoreCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle20Filled", "", 0, 20));
exports.MoreCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle24Regular", "", 1, 24));
exports.MoreCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle24Filled", "", 0, 24));
exports.MoreCircle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle28Regular", "", 1, 28));
exports.MoreCircle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle28Filled", "", 0, 28));
exports.MoreCircle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle32Regular", "", 1, 32));
exports.MoreCircle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle32Filled", "", 0, 32));
exports.MoreCircle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle48Regular", "", 1, 48));
exports.MoreCircle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MoreCircle48Filled", "", 0, 48));
