"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Multiplier2X48Filled = exports.Multiplier2X48Regular = exports.Multiplier2X32Filled = exports.Multiplier2X32Regular = exports.Multiplier2X28Filled = exports.Multiplier2X28Regular = exports.Multiplier2X24Filled = exports.Multiplier2X24Regular = exports.Multiplier2X20Filled = exports.Multiplier2X20Regular = exports.Multiplier2XRegular = exports.Multiplier2XFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.Multiplier2XFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2XFilled", "", 2, undefined));
exports.Multiplier2XRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2XRegular", "", 2, undefined));
exports.Multiplier2X20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X20Regular", "", 1, 20));
exports.Multiplier2X20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X20Filled", "", 0, 20));
exports.Multiplier2X24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X24Regular", "", 1, 24));
exports.Multiplier2X24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X24Filled", "", 0, 24));
exports.Multiplier2X28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X28Regular", "", 1, 28));
exports.Multiplier2X28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X28Filled", "", 0, 28));
exports.Multiplier2X32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X32Regular", "", 1, 32));
exports.Multiplier2X32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X32Filled", "", 0, 32));
exports.Multiplier2X48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X48Regular", "", 1, 48));
exports.Multiplier2X48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier2X48Filled", "", 0, 48));
