"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Multiplier5X48Filled = exports.Multiplier5X48Regular = exports.Multiplier5X32Filled = exports.Multiplier5X32Regular = exports.Multiplier5X28Filled = exports.Multiplier5X28Regular = exports.Multiplier5X24Filled = exports.Multiplier5X24Regular = exports.Multiplier5X20Filled = exports.Multiplier5X20Regular = exports.Multiplier5XRegular = exports.Multiplier5XFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.Multiplier5XFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5XFilled", "", 2, undefined));
exports.Multiplier5XRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5XRegular", "", 2, undefined));
exports.Multiplier5X20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X20Regular", "", 1, 20));
exports.Multiplier5X20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X20Filled", "", 0, 20));
exports.Multiplier5X24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X24Regular", "", 1, 24));
exports.Multiplier5X24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X24Filled", "", 0, 24));
exports.Multiplier5X28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X28Regular", "", 1, 28));
exports.Multiplier5X28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X28Filled", "", 0, 28));
exports.Multiplier5X32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X32Regular", "", 1, 32));
exports.Multiplier5X32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X32Filled", "", 0, 32));
exports.Multiplier5X48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X48Regular", "", 1, 48));
exports.Multiplier5X48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Multiplier5X48Filled", "", 0, 48));
