"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MusicNote224Filled = exports.MusicNote224Regular = exports.MusicNote220Filled = exports.MusicNote220Regular = exports.MusicNote216Filled = exports.MusicNote216Regular = exports.MusicNote124Filled = exports.MusicNote124Regular = exports.MusicNote120Filled = exports.MusicNote120Regular = exports.MusicNote2Filled = exports.MusicNote2Regular = exports.MusicNote1Filled = exports.MusicNote1Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.MusicNote1Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote1Regular", "", 2, undefined));
exports.MusicNote1Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote1Filled", "", 2, undefined));
exports.MusicNote2Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote2Regular", "", 2, undefined));
exports.MusicNote2Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote2Filled", "", 2, undefined));
exports.MusicNote120Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote120Regular", "", 1, 20));
exports.MusicNote120Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote120Filled", "", 0, 20));
exports.MusicNote124Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote124Regular", "", 1, 24));
exports.MusicNote124Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote124Filled", "", 0, 24));
exports.MusicNote216Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote216Regular", "", 1, 16));
exports.MusicNote216Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote216Filled", "", 0, 16));
exports.MusicNote220Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote220Regular", "", 1, 20));
exports.MusicNote220Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote220Filled", "", 0, 20));
exports.MusicNote224Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote224Regular", "", 1, 24));
exports.MusicNote224Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("MusicNote224Filled", "", 0, 24));
