"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NavigationUnread24Filled = exports.NavigationUnread24Regular = exports.NavigationUnread20Filled = exports.NavigationUnread20Regular = exports.NavigationUnreadRegular = exports.NavigationUnreadFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NavigationUnreadFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationUnreadFilled", "", 2, undefined));
exports.NavigationUnreadRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationUnreadRegular", "", 2, undefined));
exports.NavigationUnread20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationUnread20Regular", "", 1, 20));
exports.NavigationUnread20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationUnread20Filled", "", 0, 20));
exports.NavigationUnread24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationUnread24Regular", "", 1, 24));
exports.NavigationUnread24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationUnread24Filled", "", 0, 24));
