"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Navigation48Filled = exports.Navigation48Regular = exports.Navigation32Filled = exports.Navigation32Regular = exports.Navigation28Filled = exports.Navigation28Regular = exports.Navigation24Filled = exports.Navigation24Regular = exports.Navigation20Filled = exports.Navigation20Regular = exports.Navigation16Filled = exports.Navigation16Regular = exports.NavigationRegular = exports.NavigationFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NavigationFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationFilled", "", 2, undefined));
exports.NavigationRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationRegular", "", 2, undefined));
exports.Navigation16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation16Regular", "", 1, 16));
exports.Navigation16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation16Filled", "", 0, 16));
exports.Navigation20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation20Regular", "", 1, 20));
exports.Navigation20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation20Filled", "", 0, 20));
exports.Navigation24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation24Regular", "", 1, 24));
exports.Navigation24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation24Filled", "", 0, 24));
exports.Navigation28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation28Regular", "󰝩", 1, 28));
exports.Navigation28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation28Filled", "󰟦", 0, 28));
exports.Navigation32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation32Regular", "󰝪", 1, 32));
exports.Navigation32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation32Filled", "󰟧", 0, 32));
exports.Navigation48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation48Regular", "󰝫", 1, 48));
exports.Navigation48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Navigation48Filled", "󰟨", 0, 48));
