"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NavigationPerson28Filled = exports.NavigationPerson28Regular = exports.NavigationPerson24Filled = exports.NavigationPerson24Regular = exports.NavigationPerson20Filled = exports.NavigationPerson20Regular = exports.NavigationPersonRegular = exports.NavigationPersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NavigationPersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPersonFilled", "", 2, undefined));
exports.NavigationPersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPersonRegular", "", 2, undefined));
exports.NavigationPerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPerson20Regular", "󰡺", 1, 20));
exports.NavigationPerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPerson20Filled", "󰣷", 0, 20));
exports.NavigationPerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPerson24Regular", "󰡻", 1, 24));
exports.NavigationPerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPerson24Filled", "󰣸", 0, 24));
exports.NavigationPerson28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPerson28Regular", "󰡼", 1, 28));
exports.NavigationPerson28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NavigationPerson28Filled", "󰣹", 0, 28));
