"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.News28Filled = exports.News28Regular = exports.News24Filled = exports.News24Regular = exports.News20Filled = exports.News20Regular = exports.News16Filled = exports.News16Regular = exports.NewsRegular = exports.NewsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NewsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NewsFilled", "", 2, undefined));
exports.NewsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NewsRegular", "", 2, undefined));
exports.News16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News16Regular", "", 1, 16));
exports.News16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News16Filled", "", 0, 16));
exports.News20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News20Regular", "", 1, 20));
exports.News20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News20Filled", "", 0, 20));
exports.News24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News24Regular", "", 1, 24));
exports.News24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News24Filled", "", 0, 24));
exports.News28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News28Regular", "", 1, 28));
exports.News28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("News28Filled", "", 0, 28));
