"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NextFrame24Filled = exports.NextFrame24Regular = exports.NextFrame20Filled = exports.NextFrame20Regular = exports.NextFrameRegular = exports.NextFrameFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NextFrameFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NextFrameFilled", "", 2, undefined));
exports.NextFrameRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NextFrameRegular", "", 2, undefined));
exports.NextFrame20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NextFrame20Regular", "󰋜", 1, 20));
exports.NextFrame20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NextFrame20Filled", "󰋯", 0, 20));
exports.NextFrame24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NextFrame24Regular", "󰋝", 1, 24));
exports.NextFrame24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NextFrame24Filled", "󰋰", 0, 24));
