"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotebookAdd24Filled = exports.NotebookAdd24Regular = exports.NotebookAdd20Filled = exports.NotebookAdd20Regular = exports.NotebookAddRegular = exports.NotebookAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NotebookAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookAddFilled", "", 2, undefined));
exports.NotebookAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookAddRegular", "", 2, undefined));
exports.NotebookAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookAdd20Regular", "", 1, 20));
exports.NotebookAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookAdd20Filled", "", 0, 20));
exports.NotebookAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookAdd24Regular", "", 1, 24));
exports.NotebookAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookAdd24Filled", "", 0, 24));
