"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Notepad48Filled = exports.Notepad48Regular = exports.Notepad32Filled = exports.Notepad32Regular = exports.Notepad28Filled = exports.Notepad28Regular = exports.Notepad24Filled = exports.Notepad24Regular = exports.Notepad20Filled = exports.Notepad20Regular = exports.Notepad16Filled = exports.Notepad16Regular = exports.Notepad12Filled = exports.Notepad12Regular = exports.NotepadRegular = exports.NotepadFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NotepadFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotepadFilled", "", 2, undefined));
exports.NotepadRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotepadRegular", "", 2, undefined));
exports.Notepad12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad12Regular", "", 1, 12));
exports.Notepad12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad12Filled", "", 0, 12));
exports.Notepad16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad16Regular", "", 1, 16));
exports.Notepad16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad16Filled", "", 0, 16));
exports.Notepad20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad20Regular", "", 1, 20));
exports.Notepad20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad20Filled", "", 0, 20));
exports.Notepad24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad24Regular", "", 1, 24));
exports.Notepad24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad24Filled", "", 0, 24));
exports.Notepad28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad28Regular", "", 1, 28));
exports.Notepad28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad28Filled", "", 0, 28));
exports.Notepad32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad32Regular", "", 1, 32));
exports.Notepad32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad32Filled", "", 0, 32));
exports.Notepad48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad48Regular", "󰥯", 1, 48));
exports.Notepad48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notepad48Filled", "󰧬", 0, 48));
