"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Notebook32Filled = exports.Notebook32Regular = exports.Notebook24Filled = exports.Notebook24Regular = exports.Notebook20Filled = exports.Notebook20Regular = exports.Notebook16Filled = exports.Notebook16Regular = exports.NotebookRegular = exports.NotebookFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NotebookFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookFilled", "", 2, undefined));
exports.NotebookRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookRegular", "", 2, undefined));
exports.Notebook16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook16Regular", "", 1, 16));
exports.Notebook16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook16Filled", "", 0, 16));
exports.Notebook20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook20Regular", "", 1, 20));
exports.Notebook20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook20Filled", "", 0, 20));
exports.Notebook24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook24Regular", "", 1, 24));
exports.Notebook24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook24Filled", "", 0, 24));
exports.Notebook32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook32Regular", "", 1, 32));
exports.Notebook32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Notebook32Filled", "", 0, 32));
