"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotebookSync24Filled = exports.NotebookSync24Regular = exports.NotebookSync20Filled = exports.NotebookSync20Regular = exports.NotebookSyncRegular = exports.NotebookSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NotebookSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookSyncFilled", "", 2, undefined));
exports.NotebookSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookSyncRegular", "", 2, undefined));
exports.NotebookSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookSync20Regular", "", 1, 20));
exports.NotebookSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookSync20Filled", "", 0, 20));
exports.NotebookSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookSync24Regular", "", 1, 24));
exports.NotebookSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NotebookSync24Filled", "", 0, 24));
