"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NoteAdd48Filled = exports.NoteAdd48Regular = exports.NoteAdd28Filled = exports.NoteAdd28Regular = exports.NoteAdd24Filled = exports.NoteAdd24Regular = exports.NoteAdd20Filled = exports.NoteAdd20Regular = exports.NoteAdd16Filled = exports.NoteAdd16Regular = exports.NoteAddRegular = exports.NoteAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.NoteAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAddFilled", "", 2, undefined));
exports.NoteAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAddRegular", "", 2, undefined));
exports.NoteAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd16Regular", "", 1, 16));
exports.NoteAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd16Filled", "", 0, 16));
exports.NoteAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd20Regular", "", 1, 20));
exports.NoteAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd20Filled", "", 0, 20));
exports.NoteAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd24Regular", "", 1, 24));
exports.NoteAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd24Filled", "", 0, 24));
exports.NoteAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd28Regular", "", 1, 28));
exports.NoteAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd28Filled", "", 0, 28));
exports.NoteAdd48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd48Regular", "", 1, 48));
exports.NoteAdd48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("NoteAdd48Filled", "", 0, 48));
