"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenOff48Filled = exports.OpenOff48Regular = exports.OpenOff28Filled = exports.OpenOff28Regular = exports.OpenOff24Filled = exports.OpenOff24Regular = exports.OpenOff20Filled = exports.OpenOff20Regular = exports.OpenOff16Filled = exports.OpenOff16Regular = exports.OpenOffRegular = exports.OpenOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.OpenOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOffFilled", "", 2, undefined));
exports.OpenOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOffRegular", "", 2, undefined));
exports.OpenOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff16Regular", "", 1, 16));
exports.OpenOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff16Filled", "", 0, 16));
exports.OpenOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff20Regular", "", 1, 20));
exports.OpenOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff20Filled", "", 0, 20));
exports.OpenOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff24Regular", "", 1, 24));
exports.OpenOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff24Filled", "", 0, 24));
exports.OpenOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff28Regular", "", 1, 28));
exports.OpenOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff28Filled", "", 0, 28));
exports.OpenOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff48Regular", "", 1, 48));
exports.OpenOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OpenOff48Filled", "", 0, 48));
