"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Oval48Filled = exports.Oval48Regular = exports.Oval32Filled = exports.Oval32Regular = exports.Oval28Filled = exports.Oval28Regular = exports.Oval24Filled = exports.Oval24Regular = exports.Oval20Filled = exports.Oval20Regular = exports.Oval16Filled = exports.Oval16Regular = exports.OvalRegular = exports.OvalFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.OvalFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OvalFilled", "", 2, undefined));
exports.OvalRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OvalRegular", "", 2, undefined));
exports.Oval16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval16Regular", "", 1, 16));
exports.Oval16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval16Filled", "", 0, 16));
exports.Oval20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval20Regular", "", 1, 20));
exports.Oval20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval20Filled", "", 0, 20));
exports.Oval24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval24Regular", "", 1, 24));
exports.Oval24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval24Filled", "", 0, 24));
exports.Oval28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval28Regular", "", 1, 28));
exports.Oval28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval28Filled", "", 0, 28));
exports.Oval32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval32Regular", "", 1, 32));
exports.Oval32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval32Filled", "", 0, 32));
exports.Oval48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval48Regular", "", 1, 48));
exports.Oval48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oval48Filled", "", 0, 48));
