"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Oven48Filled = exports.Oven48Regular = exports.Oven32Filled = exports.Oven32Regular = exports.Oven24Filled = exports.Oven24Regular = exports.Oven20Filled = exports.Oven20Regular = exports.OvenRegular = exports.OvenFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.OvenFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OvenFilled", "", 2, undefined));
exports.OvenRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("OvenRegular", "", 2, undefined));
exports.Oven20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven20Regular", "", 1, 20));
exports.Oven20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven20Filled", "", 0, 20));
exports.Oven24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven24Regular", "", 1, 24));
exports.Oven24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven24Filled", "", 0, 24));
exports.Oven32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven32Regular", "", 1, 32));
exports.Oven32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven32Filled", "", 0, 32));
exports.Oven48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven48Regular", "", 1, 48));
exports.Oven48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Oven48Filled", "", 0, 48));
