"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaddingDown24Filled = exports.PaddingDown24Regular = exports.PaddingDown20Filled = exports.PaddingDown20Regular = exports.PaddingDownRegular = exports.PaddingDownFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PaddingDownFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingDownFilled", "", 2, undefined));
exports.PaddingDownRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingDownRegular", "", 2, undefined));
exports.PaddingDown20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingDown20Regular", "", 1, 20));
exports.PaddingDown20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingDown20Filled", "", 0, 20));
exports.PaddingDown24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingDown24Regular", "", 1, 24));
exports.PaddingDown24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingDown24Filled", "", 0, 24));
