"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaddingLeft24Filled = exports.PaddingLeft24Regular = exports.PaddingLeft20Filled = exports.PaddingLeft20Regular = exports.PaddingLeftRegular = exports.PaddingLeftFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PaddingLeftFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingLeftFilled", "", 2, undefined));
exports.PaddingLeftRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingLeftRegular", "", 2, undefined));
exports.PaddingLeft20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingLeft20Regular", "", 1, 20));
exports.PaddingLeft20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingLeft20Filled", "", 0, 20));
exports.PaddingLeft24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingLeft24Regular", "", 1, 24));
exports.PaddingLeft24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaddingLeft24Filled", "", 0, 24));
