"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaintBrush32Light = exports.PaintBrush32Filled = exports.PaintBrush32Regular = exports.PaintBrush28Filled = exports.PaintBrush28Regular = exports.PaintBrush24Filled = exports.PaintBrush24Regular = exports.PaintBrush20Filled = exports.PaintBrush20Regular = exports.PaintBrush16Filled = exports.PaintBrush16Regular = exports.PaintBrush12Filled = exports.PaintBrush12Regular = exports.PaintBrushRegular = exports.PaintBrushFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PaintBrushFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrushFilled", "", 2, undefined));
exports.PaintBrushRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrushRegular", "", 2, undefined));
exports.PaintBrush12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush12Regular", "󰙧", 1, 12));
exports.PaintBrush12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush12Filled", "󰛧", 0, 12));
exports.PaintBrush16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush16Regular", "", 1, 16));
exports.PaintBrush16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush16Filled", "", 0, 16));
exports.PaintBrush20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush20Regular", "", 1, 20));
exports.PaintBrush20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush20Filled", "", 0, 20));
exports.PaintBrush24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush24Regular", "", 1, 24));
exports.PaintBrush24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush24Filled", "", 0, 24));
exports.PaintBrush28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush28Regular", "󰘅", 1, 28));
exports.PaintBrush28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush28Filled", "󰚁", 0, 28));
exports.PaintBrush32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush32Regular", "󰈤", 1, 32));
exports.PaintBrush32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush32Filled", "󰈷", 0, 32));
exports.PaintBrush32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PaintBrush32Light", "", 3, 32));
