"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PanelLeft48Filled = exports.PanelLeft48Regular = exports.PanelLeft32Filled = exports.PanelLeft32Regular = exports.PanelLeft28Filled = exports.PanelLeft28Regular = exports.PanelLeft24Filled = exports.PanelLeft24Regular = exports.PanelLeft20Filled = exports.PanelLeft20Regular = exports.PanelLeft16Filled = exports.PanelLeft16Regular = exports.PanelLeftRegular = exports.PanelLeftFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PanelLeftFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeftFilled", "", 2, undefined));
exports.PanelLeftRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeftRegular", "", 2, undefined));
exports.PanelLeft16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft16Regular", "", 1, 16));
exports.PanelLeft16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft16Filled", "", 0, 16));
exports.PanelLeft20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft20Regular", "", 1, 20));
exports.PanelLeft20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft20Filled", "", 0, 20));
exports.PanelLeft24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft24Regular", "", 1, 24));
exports.PanelLeft24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft24Filled", "", 0, 24));
exports.PanelLeft28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft28Regular", "", 1, 28));
exports.PanelLeft28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft28Filled", "", 0, 28));
exports.PanelLeft32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft32Regular", "", 1, 32));
exports.PanelLeft32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft32Filled", "", 0, 32));
exports.PanelLeft48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft48Regular", "", 1, 48));
exports.PanelLeft48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PanelLeft48Filled", "", 0, 48));
