"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PasswordClock48Filled = exports.PasswordClock48Regular = exports.PasswordClock24Filled = exports.PasswordClock24Regular = exports.PasswordClock20Filled = exports.PasswordClock20Regular = exports.PasswordClock16Filled = exports.PasswordClock16Regular = exports.PasswordClockRegular = exports.PasswordClockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PasswordClockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClockFilled", "", 2, undefined));
exports.PasswordClockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClockRegular", "", 2, undefined));
exports.PasswordClock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock16Regular", "󰧛", 1, 16));
exports.PasswordClock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock16Filled", "󰩘", 0, 16));
exports.PasswordClock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock20Regular", "󰧜", 1, 20));
exports.PasswordClock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock20Filled", "󰩙", 0, 20));
exports.PasswordClock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock24Regular", "󰧝", 1, 24));
exports.PasswordClock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock24Filled", "󰩚", 0, 24));
exports.PasswordClock48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock48Regular", "󰖰", 1, 48));
exports.PasswordClock48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PasswordClock48Filled", "󰘩", 0, 48));
