"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Patch24Filled = exports.Patch24Regular = exports.Patch20Filled = exports.Patch20Regular = exports.PatchRegular = exports.PatchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PatchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PatchFilled", "", 2, undefined));
exports.PatchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PatchRegular", "", 2, undefined));
exports.Patch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Patch20Regular", "", 1, 20));
exports.Patch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Patch20Filled", "", 0, 20));
exports.Patch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Patch24Regular", "", 1, 24));
exports.Patch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Patch24Filled", "", 0, 24));
