"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PauseOff20Filled = exports.PauseOff20Regular = exports.PauseOff16Filled = exports.PauseOff16Regular = exports.PauseOffRegular = exports.PauseOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PauseOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseOffFilled", "", 2, undefined));
exports.PauseOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseOffRegular", "", 2, undefined));
exports.PauseOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseOff16Regular", "", 1, 16));
exports.PauseOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseOff16Filled", "", 0, 16));
exports.PauseOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseOff20Regular", "", 1, 20));
exports.PauseOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseOff20Filled", "", 0, 20));
