"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PauseCircle48Filled = exports.PauseCircle48Regular = exports.PauseCircle32Filled = exports.PauseCircle32Regular = exports.PauseCircle24Filled = exports.PauseCircle24Regular = exports.PauseCircle20Filled = exports.PauseCircle20Regular = exports.PauseCircle16Filled = exports.PauseCircle16Regular = exports.PauseCircle12Filled = exports.PauseCircle12Regular = exports.PauseCircleRegular = exports.PauseCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PauseCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircleFilled", "", 2, undefined));
exports.PauseCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircleRegular", "", 2, undefined));
exports.PauseCircle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle12Regular", "󰦙", 1, 12));
exports.PauseCircle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle12Filled", "󰨖", 0, 12));
exports.PauseCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle16Regular", "󰝬", 1, 16));
exports.PauseCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle16Filled", "󰟩", 0, 16));
exports.PauseCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle20Regular", "", 1, 20));
exports.PauseCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle20Filled", "", 0, 20));
exports.PauseCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle24Regular", "", 1, 24));
exports.PauseCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle24Filled", "", 0, 24));
exports.PauseCircle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle32Regular", "󰈥", 1, 32));
exports.PauseCircle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle32Filled", "󰈸", 0, 32));
exports.PauseCircle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle48Regular", "󰈦", 1, 48));
exports.PauseCircle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PauseCircle48Filled", "󰈹", 0, 48));
