"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PenSparkle48Filled = exports.PenSparkle48Regular = exports.PenSparkle32Light = exports.PenSparkle32Filled = exports.PenSparkle32Regular = exports.PenSparkle28Filled = exports.PenSparkle28Regular = exports.PenSparkle24Filled = exports.PenSparkle24Regular = exports.PenSparkle20Filled = exports.PenSparkle20Regular = exports.PenSparkle16Filled = exports.PenSparkle16Regular = exports.PenSparkleRegular = exports.PenSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PenSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkleFilled", "", 2, undefined));
exports.PenSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkleRegular", "", 2, undefined));
exports.PenSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle16Regular", "󰈧", 1, 16));
exports.PenSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle16Filled", "󰈺", 0, 16));
exports.PenSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle20Regular", "󰈨", 1, 20));
exports.PenSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle20Filled", "󰈻", 0, 20));
exports.PenSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle24Regular", "󰈩", 1, 24));
exports.PenSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle24Filled", "󰈼", 0, 24));
exports.PenSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle28Regular", "󰈪", 1, 28));
exports.PenSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle28Filled", "󰈽", 0, 28));
exports.PenSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle32Regular", "󰈫", 1, 32));
exports.PenSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle32Filled", "󰈾", 0, 32));
exports.PenSparkle32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle32Light", "", 3, 32));
exports.PenSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle48Regular", "󰈬", 1, 48));
exports.PenSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PenSparkle48Filled", "󰈿", 0, 48));
