"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pentagon48Filled = exports.Pentagon48Regular = exports.Pentagon32Filled = exports.Pentagon32Regular = exports.Pentagon20Filled = exports.Pentagon20Regular = exports.PentagonRegular = exports.PentagonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PentagonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PentagonFilled", "", 2, undefined));
exports.PentagonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PentagonRegular", "", 2, undefined));
exports.Pentagon20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pentagon20Regular", "", 1, 20));
exports.Pentagon20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pentagon20Filled", "", 0, 20));
exports.Pentagon32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pentagon32Regular", "", 1, 32));
exports.Pentagon32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pentagon32Filled", "", 0, 32));
exports.Pentagon48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pentagon48Regular", "", 1, 48));
exports.Pentagon48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pentagon48Filled", "", 0, 48));
