"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleSync32Light = exports.PeopleSync32Filled = exports.PeopleSync32Regular = exports.PeopleSync28Filled = exports.PeopleSync28Regular = exports.PeopleSync24Filled = exports.PeopleSync24Regular = exports.PeopleSync20Filled = exports.PeopleSync20Regular = exports.PeopleSync16Filled = exports.PeopleSync16Regular = exports.PeopleSyncRegular = exports.PeopleSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSyncFilled", "", 2, undefined));
exports.PeopleSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSyncRegular", "", 2, undefined));
exports.PeopleSync16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync16Regular", "", 1, 16));
exports.PeopleSync16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync16Filled", "", 0, 16));
exports.PeopleSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync20Regular", "", 1, 20));
exports.PeopleSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync20Filled", "", 0, 20));
exports.PeopleSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync24Regular", "󰡾", 1, 24));
exports.PeopleSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync24Filled", "󰣻", 0, 24));
exports.PeopleSync28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync28Regular", "", 1, 28));
exports.PeopleSync28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync28Filled", "", 0, 28));
exports.PeopleSync32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync32Regular", "󰡿", 1, 32));
exports.PeopleSync32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync32Filled", "󰣼", 0, 32));
exports.PeopleSync32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSync32Light", "", 3, 32));
