"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleToolbox20Filled = exports.PeopleToolbox20Regular = exports.PeopleToolbox16Filled = exports.PeopleToolbox16Regular = exports.PeopleToolboxRegular = exports.PeopleToolboxFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleToolboxFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleToolboxFilled", "", 2, undefined));
exports.PeopleToolboxRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleToolboxRegular", "", 2, undefined));
exports.PeopleToolbox16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleToolbox16Regular", "", 1, 16));
exports.PeopleToolbox16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleToolbox16Filled", "", 0, 16));
exports.PeopleToolbox20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleToolbox20Regular", "", 1, 20));
exports.PeopleToolbox20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleToolbox20Filled", "", 0, 20));
