"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleQueue48Filled = exports.PeopleQueue48Regular = exports.PeopleQueue32Filled = exports.PeopleQueue32Regular = exports.PeopleQueue28Filled = exports.PeopleQueue28Regular = exports.PeopleQueue24Filled = exports.PeopleQueue24Regular = exports.PeopleQueue20Filled = exports.PeopleQueue20Regular = exports.PeopleQueueRegular = exports.PeopleQueueFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleQueueFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueueFilled", "", 2, undefined));
exports.PeopleQueueRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueueRegular", "", 2, undefined));
exports.PeopleQueue20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue20Regular", "", 1, 20));
exports.PeopleQueue20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue20Filled", "", 0, 20));
exports.PeopleQueue24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue24Regular", "", 1, 24));
exports.PeopleQueue24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue24Filled", "", 0, 24));
exports.PeopleQueue28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue28Regular", "󰜎", 1, 28));
exports.PeopleQueue28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue28Filled", "󰞋", 0, 28));
exports.PeopleQueue32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue32Regular", "󰜏", 1, 32));
exports.PeopleQueue32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue32Filled", "󰞌", 0, 32));
exports.PeopleQueue48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue48Regular", "󰜐", 1, 48));
exports.PeopleQueue48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleQueue48Filled", "󰞍", 0, 48));
