"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleSwap28Filled = exports.PeopleSwap28Regular = exports.PeopleSwap24Filled = exports.PeopleSwap24Regular = exports.PeopleSwap20Filled = exports.PeopleSwap20Regular = exports.PeopleSwap16Filled = exports.PeopleSwap16Regular = exports.PeopleSwapRegular = exports.PeopleSwapFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleSwapFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwapFilled", "", 2, undefined));
exports.PeopleSwapRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwapRegular", "", 2, undefined));
exports.PeopleSwap16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap16Regular", "", 1, 16));
exports.PeopleSwap16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap16Filled", "", 0, 16));
exports.PeopleSwap20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap20Regular", "", 1, 20));
exports.PeopleSwap20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap20Filled", "", 0, 20));
exports.PeopleSwap24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap24Regular", "", 1, 24));
exports.PeopleSwap24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap24Filled", "", 0, 24));
exports.PeopleSwap28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap28Regular", "", 1, 28));
exports.PeopleSwap28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleSwap28Filled", "", 0, 28));
