"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleError24Filled = exports.PeopleError24Regular = exports.PeopleError20Filled = exports.PeopleError20Regular = exports.PeopleError16Filled = exports.PeopleError16Regular = exports.PeopleErrorRegular = exports.PeopleErrorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleErrorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleErrorFilled", "", 2, undefined));
exports.PeopleErrorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleErrorRegular", "", 2, undefined));
exports.PeopleError16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleError16Regular", "", 1, 16));
exports.PeopleError16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleError16Filled", "", 0, 16));
exports.PeopleError20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleError20Regular", "", 1, 20));
exports.PeopleError20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleError20Filled", "", 0, 20));
exports.PeopleError24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleError24Regular", "", 1, 24));
exports.PeopleError24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleError24Filled", "", 0, 24));
