"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleCall24Filled = exports.PeopleCall24Regular = exports.PeopleCall20Filled = exports.PeopleCall20Regular = exports.PeopleCall16Filled = exports.PeopleCall16Regular = exports.PeopleCallRegular = exports.PeopleCallFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleCallFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCallFilled", "", 2, undefined));
exports.PeopleCallRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCallRegular", "", 2, undefined));
exports.PeopleCall16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCall16Regular", "", 1, 16));
exports.PeopleCall16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCall16Filled", "", 0, 16));
exports.PeopleCall20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCall20Regular", "", 1, 20));
exports.PeopleCall20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCall20Filled", "", 0, 20));
exports.PeopleCall24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCall24Regular", "󰂂", 1, 24));
exports.PeopleCall24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleCall24Filled", "󰂆", 0, 24));
