"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleEye20Filled = exports.PeopleEye20Regular = exports.PeopleEye16Filled = exports.PeopleEye16Regular = exports.PeopleEyeRegular = exports.PeopleEyeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleEyeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleEyeFilled", "", 2, undefined));
exports.PeopleEyeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleEyeRegular", "", 2, undefined));
exports.PeopleEye16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleEye16Regular", "󰖲", 1, 16));
exports.PeopleEye16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleEye16Filled", "󰘫", 0, 16));
exports.PeopleEye20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleEye20Regular", "󰖳", 1, 20));
exports.PeopleEye20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleEye20Filled", "󰘬", 0, 20));
