"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PeopleStar48Filled = exports.PeopleStar48Regular = exports.PeopleStar32Filled = exports.PeopleStar32Regular = exports.PeopleStar28Filled = exports.PeopleStar28Regular = exports.PeopleStar24Filled = exports.PeopleStar24Regular = exports.PeopleStar20Filled = exports.PeopleStar20Regular = exports.PeopleStar16Filled = exports.PeopleStar16Regular = exports.PeopleStarRegular = exports.PeopleStarFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PeopleStarFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStarFilled", "", 2, undefined));
exports.PeopleStarRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStarRegular", "", 2, undefined));
exports.PeopleStar16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar16Regular", "", 1, 16));
exports.PeopleStar16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar16Filled", "", 0, 16));
exports.PeopleStar20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar20Regular", "", 1, 20));
exports.PeopleStar20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar20Filled", "", 0, 20));
exports.PeopleStar24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar24Regular", "", 1, 24));
exports.PeopleStar24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar24Filled", "", 0, 24));
exports.PeopleStar28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar28Regular", "", 1, 28));
exports.PeopleStar28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar28Filled", "", 0, 28));
exports.PeopleStar32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar32Regular", "", 1, 32));
exports.PeopleStar32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar32Filled", "", 0, 32));
exports.PeopleStar48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar48Regular", "", 1, 48));
exports.PeopleStar48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PeopleStar48Filled", "", 0, 48));
