"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonSync48Filled = exports.PersonSync48Regular = exports.PersonSync32Filled = exports.PersonSync32Regular = exports.PersonSync28Filled = exports.PersonSync28Regular = exports.PersonSync24Filled = exports.PersonSync24Regular = exports.PersonSync20Filled = exports.PersonSync20Regular = exports.PersonSync16Filled = exports.PersonSync16Regular = exports.PersonSyncRegular = exports.PersonSyncFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonSyncFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSyncFilled", "", 2, undefined));
exports.PersonSyncRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSyncRegular", "", 2, undefined));
exports.PersonSync16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync16Regular", "", 1, 16));
exports.PersonSync16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync16Filled", "", 0, 16));
exports.PersonSync20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync20Regular", "", 1, 20));
exports.PersonSync20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync20Filled", "", 0, 20));
exports.PersonSync24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync24Regular", "", 1, 24));
exports.PersonSync24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync24Filled", "", 0, 24));
exports.PersonSync28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync28Regular", "", 1, 28));
exports.PersonSync28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync28Filled", "", 0, 28));
exports.PersonSync32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync32Regular", "", 1, 32));
exports.PersonSync32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync32Filled", "", 0, 32));
exports.PersonSync48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync48Regular", "", 1, 48));
exports.PersonSync48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSync48Filled", "", 0, 48));
