"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonLock24Filled = exports.PersonLock24Regular = exports.PersonLock20Filled = exports.PersonLock20Regular = exports.PersonLock16Filled = exports.PersonLock16Regular = exports.PersonLockRegular = exports.PersonLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLockFilled", "", 2, undefined));
exports.PersonLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLockRegular", "", 2, undefined));
exports.PersonLock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLock16Regular", "", 1, 16));
exports.PersonLock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLock16Filled", "", 0, 16));
exports.PersonLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLock20Regular", "", 1, 20));
exports.PersonLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLock20Filled", "", 0, 20));
exports.PersonLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLock24Regular", "", 1, 24));
exports.PersonLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLock24Filled", "", 0, 24));
