"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonLink48Filled = exports.PersonLink48Regular = exports.PersonLink32Filled = exports.PersonLink32Regular = exports.PersonLink28Filled = exports.PersonLink28Regular = exports.PersonLink24Filled = exports.PersonLink24Regular = exports.PersonLink20Filled = exports.PersonLink20Regular = exports.PersonLink16Filled = exports.PersonLink16Regular = exports.PersonLinkRegular = exports.PersonLinkFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonLinkFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLinkFilled", "", 2, undefined));
exports.PersonLinkRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLinkRegular", "", 2, undefined));
exports.PersonLink16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink16Regular", "", 1, 16));
exports.PersonLink16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink16Filled", "", 0, 16));
exports.PersonLink20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink20Regular", "", 1, 20));
exports.PersonLink20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink20Filled", "", 0, 20));
exports.PersonLink24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink24Regular", "", 1, 24));
exports.PersonLink24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink24Filled", "", 0, 24));
exports.PersonLink28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink28Regular", "", 1, 28));
exports.PersonLink28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink28Filled", "", 0, 28));
exports.PersonLink32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink32Regular", "", 1, 32));
exports.PersonLink32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink32Filled", "", 0, 32));
exports.PersonLink48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink48Regular", "", 1, 48));
exports.PersonLink48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonLink48Filled", "", 0, 48));
