"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonCircle32Filled = exports.PersonCircle32Regular = exports.PersonCircle28Filled = exports.PersonCircle28Regular = exports.PersonCircle24Filled = exports.PersonCircle24Regular = exports.PersonCircle20Filled = exports.PersonCircle20Regular = exports.PersonCircle12Filled = exports.PersonCircle12Regular = exports.PersonCircleRegular = exports.PersonCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircleFilled", "", 2, undefined));
exports.PersonCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircleRegular", "", 2, undefined));
exports.PersonCircle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle12Regular", "", 1, 12));
exports.PersonCircle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle12Filled", "", 0, 12));
exports.PersonCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle20Regular", "", 1, 20));
exports.PersonCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle20Filled", "", 0, 20));
exports.PersonCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle24Regular", "", 1, 24));
exports.PersonCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle24Filled", "", 0, 24));
exports.PersonCircle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle28Regular", "", 1, 28));
exports.PersonCircle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle28Filled", "", 0, 28));
exports.PersonCircle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle32Regular", "", 1, 32));
exports.PersonCircle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonCircle32Filled", "", 0, 32));
