"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonSquare32Filled = exports.PersonSquare32Regular = exports.PersonSquare24Filled = exports.PersonSquare24Regular = exports.PersonSquare20Filled = exports.PersonSquare20Regular = exports.PersonSquare16Filled = exports.PersonSquare16Regular = exports.PersonSquareRegular = exports.PersonSquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonSquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquareFilled", "", 2, undefined));
exports.PersonSquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquareRegular", "", 2, undefined));
exports.PersonSquare16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare16Regular", "󰑐", 1, 16));
exports.PersonSquare16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare16Filled", "󰑣", 0, 16));
exports.PersonSquare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare20Regular", "", 1, 20));
exports.PersonSquare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare20Filled", "", 0, 20));
exports.PersonSquare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare24Regular", "", 1, 24));
exports.PersonSquare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare24Filled", "", 0, 24));
exports.PersonSquare32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare32Regular", "󰑑", 1, 32));
exports.PersonSquare32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSquare32Filled", "󰑤", 0, 32));
