"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonAlert32Filled = exports.PersonAlert32Regular = exports.PersonAlert24Filled = exports.PersonAlert24Regular = exports.PersonAlert20Filled = exports.PersonAlert20Regular = exports.PersonAlert16Filled = exports.PersonAlert16Regular = exports.PersonAlertRegular = exports.PersonAlertFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonAlertFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlertFilled", "", 2, undefined));
exports.PersonAlertRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlertRegular", "", 2, undefined));
exports.PersonAlert16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert16Regular", "", 1, 16));
exports.PersonAlert16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert16Filled", "", 0, 16));
exports.PersonAlert20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert20Regular", "", 1, 20));
exports.PersonAlert20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert20Filled", "", 0, 20));
exports.PersonAlert24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert24Regular", "", 1, 24));
exports.PersonAlert24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert24Filled", "", 0, 24));
exports.PersonAlert32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert32Regular", "󰕶", 1, 32));
exports.PersonAlert32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonAlert32Filled", "󰗯", 0, 32));
