"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonEdit48Filled = exports.PersonEdit48Regular = exports.PersonEdit32Filled = exports.PersonEdit32Regular = exports.PersonEdit24Filled = exports.PersonEdit24Regular = exports.PersonEdit20Filled = exports.PersonEdit20Regular = exports.PersonEdit16Filled = exports.PersonEdit16Regular = exports.PersonEditRegular = exports.PersonEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEditFilled", "", 2, undefined));
exports.PersonEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEditRegular", "", 2, undefined));
exports.PersonEdit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit16Regular", "󰢀", 1, 16));
exports.PersonEdit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit16Filled", "󰣽", 0, 16));
exports.PersonEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit20Regular", "", 1, 20));
exports.PersonEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit20Filled", "", 0, 20));
exports.PersonEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit24Regular", "", 1, 24));
exports.PersonEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit24Filled", "", 0, 24));
exports.PersonEdit32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit32Regular", "󰦚", 1, 32));
exports.PersonEdit32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit32Filled", "󰨗", 0, 32));
exports.PersonEdit48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit48Regular", "󰉺", 1, 48));
exports.PersonEdit48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonEdit48Filled", "󰊍", 0, 48));
