"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonRibbon24Filled = exports.PersonRibbon24Regular = exports.PersonRibbon20Filled = exports.PersonRibbon20Regular = exports.PersonRibbon16Filled = exports.PersonRibbon16Regular = exports.PersonRibbonRegular = exports.PersonRibbonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonRibbonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbonFilled", "", 2, undefined));
exports.PersonRibbonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbonRegular", "", 2, undefined));
exports.PersonRibbon16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbon16Regular", "󰄳", 1, 16));
exports.PersonRibbon16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbon16Filled", "󰄲", 0, 16));
exports.PersonRibbon20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbon20Regular", "󰄴", 1, 20));
exports.PersonRibbon20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbon20Filled", "󰄳", 0, 20));
exports.PersonRibbon24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbon24Regular", "󰕁", 1, 24));
exports.PersonRibbon24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonRibbon24Filled", "󰖺", 0, 24));
