"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonBoard32Filled = exports.PersonBoard32Regular = exports.PersonBoard28Filled = exports.PersonBoard28Regular = exports.PersonBoard24Filled = exports.PersonBoard24Regular = exports.PersonBoard20Filled = exports.PersonBoard20Regular = exports.PersonBoard16Filled = exports.PersonBoard16Regular = exports.PersonBoard12Filled = exports.PersonBoard12Regular = exports.PersonBoardRegular = exports.PersonBoardFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonBoardFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoardFilled", "", 2, undefined));
exports.PersonBoardRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoardRegular", "", 2, undefined));
exports.PersonBoard12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard12Regular", "󰗝", 1, 12));
exports.PersonBoard12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard12Filled", "󰙙", 0, 12));
exports.PersonBoard16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard16Regular", "", 1, 16));
exports.PersonBoard16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard16Filled", "", 0, 16));
exports.PersonBoard20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard20Regular", "", 1, 20));
exports.PersonBoard20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard20Filled", "", 0, 20));
exports.PersonBoard24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard24Regular", "", 1, 24));
exports.PersonBoard24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard24Filled", "", 0, 24));
exports.PersonBoard28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard28Regular", "", 1, 28));
exports.PersonBoard28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard28Filled", "", 0, 28));
exports.PersonBoard32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard32Regular", "", 1, 32));
exports.PersonBoard32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonBoard32Filled", "", 0, 32));
