"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonKey32Filled = exports.PersonKey32Regular = exports.PersonKey24Filled = exports.PersonKey24Regular = exports.PersonKey20Filled = exports.PersonKey20Regular = exports.PersonKey16Filled = exports.PersonKey16Regular = exports.PersonKeyRegular = exports.PersonKeyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonKeyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKeyFilled", "", 2, undefined));
exports.PersonKeyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKeyRegular", "", 2, undefined));
exports.PersonKey16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey16Regular", "󰫥", 1, 16));
exports.PersonKey16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey16Filled", "󰭣", 0, 16));
exports.PersonKey20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey20Regular", "", 1, 20));
exports.PersonKey20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey20Filled", "", 0, 20));
exports.PersonKey24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey24Regular", "󰢂", 1, 24));
exports.PersonKey24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey24Filled", "󰣿", 0, 24));
exports.PersonKey32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey32Regular", "󰢃", 1, 32));
exports.PersonKey32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonKey32Filled", "󰤀", 0, 32));
