"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonTag48Filled = exports.PersonTag48Regular = exports.PersonTag32Filled = exports.PersonTag32Regular = exports.PersonTag28Filled = exports.PersonTag28Regular = exports.PersonTag24Filled = exports.PersonTag24Regular = exports.PersonTag20Filled = exports.PersonTag20Regular = exports.PersonTagRegular = exports.PersonTagFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonTagFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTagFilled", "", 2, undefined));
exports.PersonTagRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTagRegular", "", 2, undefined));
exports.PersonTag20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag20Regular", "", 1, 20));
exports.PersonTag20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag20Filled", "", 0, 20));
exports.PersonTag24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag24Regular", "", 1, 24));
exports.PersonTag24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag24Filled", "", 0, 24));
exports.PersonTag28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag28Regular", "", 1, 28));
exports.PersonTag28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag28Filled", "", 0, 28));
exports.PersonTag32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag32Regular", "", 1, 32));
exports.PersonTag32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag32Filled", "", 0, 32));
exports.PersonTag48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag48Regular", "", 1, 48));
exports.PersonTag48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonTag48Filled", "", 0, 48));
