"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonShield48Filled = exports.PersonShield48Regular = exports.PersonShield32Filled = exports.PersonShield32Regular = exports.PersonShield28Filled = exports.PersonShield28Regular = exports.PersonShield24Filled = exports.PersonShield24Regular = exports.PersonShield20Filled = exports.PersonShield20Regular = exports.PersonShield16Filled = exports.PersonShield16Regular = exports.PersonShieldRegular = exports.PersonShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShieldFilled", "", 2, undefined));
exports.PersonShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShieldRegular", "", 2, undefined));
exports.PersonShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield16Regular", "󰧞", 1, 16));
exports.PersonShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield16Filled", "󰩛", 0, 16));
exports.PersonShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield20Regular", "󰧟", 1, 20));
exports.PersonShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield20Filled", "󰩜", 0, 20));
exports.PersonShield24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield24Regular", "󰧠", 1, 24));
exports.PersonShield24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield24Filled", "󰩝", 0, 24));
exports.PersonShield28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield28Regular", "󰧡", 1, 28));
exports.PersonShield28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield28Filled", "󰩞", 0, 28));
exports.PersonShield32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield32Regular", "󰧢", 1, 32));
exports.PersonShield32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield32Filled", "󰩟", 0, 32));
exports.PersonShield48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield48Regular", "󰧣", 1, 48));
exports.PersonShield48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonShield48Filled", "󰩠", 0, 48));
