"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonSupport32Filled = exports.PersonSupport32Regular = exports.PersonSupport28Filled = exports.PersonSupport28Regular = exports.PersonSupport24Filled = exports.PersonSupport24Regular = exports.PersonSupport20Filled = exports.PersonSupport20Regular = exports.PersonSupport16Filled = exports.PersonSupport16Regular = exports.PersonSupportRegular = exports.PersonSupportFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonSupportFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupportFilled", "", 2, undefined));
exports.PersonSupportRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupportRegular", "", 2, undefined));
exports.PersonSupport16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport16Regular", "", 1, 16));
exports.PersonSupport16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport16Filled", "", 0, 16));
exports.PersonSupport20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport20Regular", "", 1, 20));
exports.PersonSupport20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport20Filled", "", 0, 20));
exports.PersonSupport24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport24Regular", "", 1, 24));
exports.PersonSupport24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport24Filled", "", 0, 24));
exports.PersonSupport28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport28Regular", "󰏂", 1, 28));
exports.PersonSupport28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport28Filled", "󰏕", 0, 28));
exports.PersonSupport32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport32Regular", "󰗳", 1, 32));
exports.PersonSupport32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonSupport32Filled", "󰙯", 0, 32));
