"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PersonInfo24Filled = exports.PersonInfo24Regular = exports.PersonInfo20Filled = exports.PersonInfo20Regular = exports.PersonInfo16Filled = exports.PersonInfo16Regular = exports.PersonInfoRegular = exports.PersonInfoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PersonInfoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfoFilled", "", 2, undefined));
exports.PersonInfoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfoRegular", "", 2, undefined));
exports.PersonInfo16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfo16Regular", "", 1, 16));
exports.PersonInfo16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfo16Filled", "", 0, 16));
exports.PersonInfo20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfo20Regular", "", 1, 20));
exports.PersonInfo20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfo20Filled", "", 0, 20));
exports.PersonInfo24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfo24Regular", "󰇴", 1, 24));
exports.PersonInfo24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PersonInfo24Filled", "󰇴", 0, 24));
