"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneKey24Filled = exports.PhoneKey24Regular = exports.PhoneKey20Filled = exports.PhoneKey20Regular = exports.PhoneKeyRegular = exports.PhoneKeyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneKeyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneKeyFilled", "", 2, undefined));
exports.PhoneKeyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneKeyRegular", "", 2, undefined));
exports.PhoneKey20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneKey20Regular", "", 1, 20));
exports.PhoneKey20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneKey20Filled", "", 0, 20));
exports.PhoneKey24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneKey24Regular", "", 1, 24));
exports.PhoneKey24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneKey24Filled", "", 0, 24));
