"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneChat28Filled = exports.PhoneChat28Regular = exports.PhoneChat24Filled = exports.PhoneChat24Regular = exports.PhoneChat20Filled = exports.PhoneChat20Regular = exports.PhoneChat16Filled = exports.PhoneChat16Regular = exports.PhoneChatRegular = exports.PhoneChatFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneChatFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChatFilled", "", 2, undefined));
exports.PhoneChatRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChatRegular", "", 2, undefined));
exports.PhoneChat16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat16Regular", "", 1, 16));
exports.PhoneChat16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat16Filled", "", 0, 16));
exports.PhoneChat20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat20Regular", "", 1, 20));
exports.PhoneChat20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat20Filled", "", 0, 20));
exports.PhoneChat24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat24Regular", "", 1, 24));
exports.PhoneChat24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat24Filled", "", 0, 24));
exports.PhoneChat28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat28Regular", "", 1, 28));
exports.PhoneChat28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneChat28Filled", "", 0, 28));
