"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneSpeaker24Filled = exports.PhoneSpeaker24Regular = exports.PhoneSpeaker20Filled = exports.PhoneSpeaker20Regular = exports.PhoneSpeakerRegular = exports.PhoneSpeakerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneSpeakerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpeakerFilled", "", 2, undefined));
exports.PhoneSpeakerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpeakerRegular", "", 2, undefined));
exports.PhoneSpeaker20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpeaker20Regular", "", 1, 20));
exports.PhoneSpeaker20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpeaker20Filled", "", 0, 20));
exports.PhoneSpeaker24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpeaker24Regular", "", 1, 24));
exports.PhoneSpeaker24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpeaker24Filled", "", 0, 24));
