"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneSpanIn28Filled = exports.PhoneSpanIn28Regular = exports.PhoneSpanIn24Filled = exports.PhoneSpanIn24Regular = exports.PhoneSpanIn20Filled = exports.PhoneSpanIn20Regular = exports.PhoneSpanIn16Filled = exports.PhoneSpanIn16Regular = exports.PhoneSpanInRegular = exports.PhoneSpanInFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneSpanInFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanInFilled", "", 2, undefined));
exports.PhoneSpanInRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanInRegular", "", 2, undefined));
exports.PhoneSpanIn16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn16Regular", "", 1, 16));
exports.PhoneSpanIn16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn16Filled", "", 0, 16));
exports.PhoneSpanIn20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn20Regular", "", 1, 20));
exports.PhoneSpanIn20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn20Filled", "", 0, 20));
exports.PhoneSpanIn24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn24Regular", "", 1, 24));
exports.PhoneSpanIn24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn24Filled", "", 0, 24));
exports.PhoneSpanIn28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn28Regular", "", 1, 28));
exports.PhoneSpanIn28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneSpanIn28Filled", "", 0, 28));
