"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneLaptop32Filled = exports.PhoneLaptop32Regular = exports.PhoneLaptop24Filled = exports.PhoneLaptop24Regular = exports.PhoneLaptop20Filled = exports.PhoneLaptop20Regular = exports.PhoneLaptop16Filled = exports.PhoneLaptop16Regular = exports.PhoneLaptopRegular = exports.PhoneLaptopFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneLaptopFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptopFilled", "", 2, undefined));
exports.PhoneLaptopRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptopRegular", "", 2, undefined));
exports.PhoneLaptop16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop16Regular", "", 1, 16));
exports.PhoneLaptop16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop16Filled", "", 0, 16));
exports.PhoneLaptop20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop20Regular", "", 1, 20));
exports.PhoneLaptop20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop20Filled", "", 0, 20));
exports.PhoneLaptop24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop24Regular", "", 1, 24));
exports.PhoneLaptop24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop24Filled", "", 0, 24));
exports.PhoneLaptop32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop32Regular", "", 1, 32));
exports.PhoneLaptop32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLaptop32Filled", "", 0, 32));
