"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneTablet24Filled = exports.PhoneTablet24Regular = exports.PhoneTablet20Filled = exports.PhoneTablet20Regular = exports.PhoneTabletRegular = exports.PhoneTabletFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneTabletFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneTabletFilled", "", 2, undefined));
exports.PhoneTabletRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneTabletRegular", "", 2, undefined));
exports.PhoneTablet20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneTablet20Regular", "", 1, 20));
exports.PhoneTablet20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneTablet20Filled", "", 0, 20));
exports.PhoneTablet24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneTablet24Regular", "", 1, 24));
exports.PhoneTablet24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneTablet24Filled", "", 0, 24));
