"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Phone48Filled = exports.Phone48Regular = exports.Phone32Light = exports.Phone32Filled = exports.Phone32Regular = exports.Phone28Filled = exports.Phone28Regular = exports.Phone24Filled = exports.Phone24Regular = exports.Phone20Filled = exports.Phone20Regular = exports.Phone16Filled = exports.Phone16Regular = exports.Phone12Filled = exports.Phone12Regular = exports.PhoneRegular = exports.PhoneFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneFilled", "", 2, undefined));
exports.PhoneRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneRegular", "", 2, undefined));
exports.Phone12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone12Regular", "", 1, 12));
exports.Phone12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone12Filled", "", 0, 12));
exports.Phone16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone16Regular", "", 1, 16));
exports.Phone16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone16Filled", "", 0, 16));
exports.Phone20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone20Regular", "", 1, 20));
exports.Phone20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone20Filled", "", 0, 20));
exports.Phone24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone24Regular", "", 1, 24));
exports.Phone24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone24Filled", "", 0, 24));
exports.Phone28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone28Regular", "", 1, 28));
exports.Phone28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone28Filled", "", 0, 28));
exports.Phone32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone32Regular", "", 1, 32));
exports.Phone32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone32Filled", "", 0, 32));
exports.Phone32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone32Light", "", 3, 32));
exports.Phone48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone48Regular", "", 1, 48));
exports.Phone48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Phone48Filled", "", 0, 48));
