"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneDismiss24Filled = exports.PhoneDismiss24Regular = exports.PhoneDismiss20Filled = exports.PhoneDismiss20Regular = exports.PhoneDismissRegular = exports.PhoneDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneDismissFilled", "", 2, undefined));
exports.PhoneDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneDismissRegular", "", 2, undefined));
exports.PhoneDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneDismiss20Regular", "", 1, 20));
exports.PhoneDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneDismiss20Filled", "", 0, 20));
exports.PhoneDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneDismiss24Regular", "", 1, 24));
exports.PhoneDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneDismiss24Filled", "", 0, 24));
