"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneUpdate24Filled = exports.PhoneUpdate24Regular = exports.PhoneUpdate20Filled = exports.PhoneUpdate20Regular = exports.PhoneUpdateRegular = exports.PhoneUpdateFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneUpdateFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneUpdateFilled", "", 2, undefined));
exports.PhoneUpdateRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneUpdateRegular", "", 2, undefined));
exports.PhoneUpdate20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneUpdate20Regular", "", 1, 20));
exports.PhoneUpdate20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneUpdate20Filled", "", 0, 20));
exports.PhoneUpdate24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneUpdate24Regular", "", 1, 24));
exports.PhoneUpdate24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneUpdate24Filled", "", 0, 24));
