"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PhoneLock24Filled = exports.PhoneLock24Regular = exports.PhoneLock20Filled = exports.PhoneLock20Regular = exports.PhoneLockRegular = exports.PhoneLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PhoneLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLockFilled", "", 2, undefined));
exports.PhoneLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLockRegular", "", 2, undefined));
exports.PhoneLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLock20Regular", "", 1, 20));
exports.PhoneLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLock20Filled", "", 0, 20));
exports.PhoneLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLock24Regular", "", 1, 24));
exports.PhoneLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PhoneLock24Filled", "", 0, 24));
