"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pill28Filled = exports.Pill28Regular = exports.Pill24Filled = exports.Pill24Regular = exports.Pill20Filled = exports.Pill20Regular = exports.Pill16Filled = exports.Pill16Regular = exports.PillRegular = exports.PillFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PillFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PillFilled", "", 2, undefined));
exports.PillRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PillRegular", "", 2, undefined));
exports.Pill16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill16Regular", "", 1, 16));
exports.Pill16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill16Filled", "", 0, 16));
exports.Pill20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill20Regular", "", 1, 20));
exports.Pill20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill20Filled", "", 0, 20));
exports.Pill24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill24Regular", "", 1, 24));
exports.Pill24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill24Filled", "", 0, 24));
exports.Pill28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill28Regular", "", 1, 28));
exports.Pill28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pill28Filled", "", 0, 28));
