"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PinOff48Filled = exports.PinOff48Regular = exports.PinOff32Light = exports.PinOff32Filled = exports.PinOff32Regular = exports.PinOff28Filled = exports.PinOff28Regular = exports.PinOff24Filled = exports.PinOff24Regular = exports.PinOff20Filled = exports.PinOff20Regular = exports.PinOff16Filled = exports.PinOff16Regular = exports.PinOffRegular = exports.PinOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PinOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOffFilled", "", 2, undefined));
exports.PinOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOffRegular", "", 2, undefined));
exports.PinOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff16Regular", "", 1, 16));
exports.PinOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff16Filled", "", 0, 16));
exports.PinOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff20Regular", "", 1, 20));
exports.PinOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff20Filled", "", 0, 20));
exports.PinOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff24Regular", "", 1, 24));
exports.PinOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff24Filled", "", 0, 24));
exports.PinOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff28Regular", "", 1, 28));
exports.PinOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff28Filled", "", 0, 28));
exports.PinOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff32Regular", "", 1, 32));
exports.PinOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff32Filled", "", 0, 32));
exports.PinOff32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff32Light", "", 3, 32));
exports.PinOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff48Regular", "", 1, 48));
exports.PinOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinOff48Filled", "", 0, 48));
