"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PinGlobe20Filled = exports.PinGlobe20Regular = exports.PinGlobe16Filled = exports.PinGlobe16Regular = exports.PinGlobeRegular = exports.PinGlobeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PinGlobeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinGlobeFilled", "", 2, undefined));
exports.PinGlobeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinGlobeRegular", "", 2, undefined));
exports.PinGlobe16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinGlobe16Regular", "󰖴", 1, 16));
exports.PinGlobe16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinGlobe16Filled", "󰘭", 0, 16));
exports.PinGlobe20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinGlobe20Regular", "󰖵", 1, 20));
exports.PinGlobe20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinGlobe20Filled", "󰘮", 0, 20));
