"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pin48Filled = exports.Pin48Regular = exports.Pin32Light = exports.Pin32Filled = exports.Pin32Regular = exports.Pin28Filled = exports.Pin28Regular = exports.Pin24Filled = exports.Pin24Regular = exports.Pin20Filled = exports.Pin20Regular = exports.Pin16Filled = exports.Pin16Regular = exports.Pin12Filled = exports.Pin12Regular = exports.PinRegular = exports.PinFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PinFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinFilled", "", 2, undefined));
exports.PinRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PinRegular", "", 2, undefined));
exports.Pin12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin12Regular", "", 1, 12));
exports.Pin12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin12Filled", "", 0, 12));
exports.Pin16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin16Regular", "", 1, 16));
exports.Pin16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin16Filled", "", 0, 16));
exports.Pin20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin20Regular", "", 1, 20));
exports.Pin20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin20Filled", "", 0, 20));
exports.Pin24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin24Regular", "", 1, 24));
exports.Pin24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin24Filled", "", 0, 24));
exports.Pin28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin28Regular", "", 1, 28));
exports.Pin28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin28Filled", "", 0, 28));
exports.Pin32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin32Regular", "", 1, 32));
exports.Pin32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin32Filled", "", 0, 32));
exports.Pin32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin32Light", "", 3, 32));
exports.Pin48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin48Regular", "", 1, 48));
exports.Pin48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pin48Filled", "", 0, 48));
