"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pipeline32Filled = exports.Pipeline32Regular = exports.Pipeline24Filled = exports.Pipeline24Regular = exports.Pipeline20Filled = exports.Pipeline20Regular = exports.PipelineRegular = exports.PipelineFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PipelineFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PipelineFilled", "", 2, undefined));
exports.PipelineRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PipelineRegular", "", 2, undefined));
exports.Pipeline20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pipeline20Regular", "", 1, 20));
exports.Pipeline20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pipeline20Filled", "", 0, 20));
exports.Pipeline24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pipeline24Regular", "", 1, 24));
exports.Pipeline24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pipeline24Filled", "", 0, 24));
exports.Pipeline32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pipeline32Regular", "", 1, 32));
exports.Pipeline32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pipeline32Filled", "", 0, 32));
