"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Play48Filled = exports.Play48Regular = exports.Play32Filled = exports.Play32Regular = exports.Play28Filled = exports.Play28Regular = exports.Play24Filled = exports.Play24Regular = exports.Play20Filled = exports.Play20Regular = exports.Play16Filled = exports.Play16Regular = exports.Play12Filled = exports.Play12Regular = exports.PlayRegular = exports.PlayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PlayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PlayFilled", "", 2, undefined));
exports.PlayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PlayRegular", "", 2, undefined));
exports.Play12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play12Regular", "", 1, 12));
exports.Play12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play12Filled", "", 0, 12));
exports.Play16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play16Regular", "", 1, 16));
exports.Play16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play16Filled", "", 0, 16));
exports.Play20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play20Regular", "", 1, 20));
exports.Play20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play20Filled", "", 0, 20));
exports.Play24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play24Regular", "", 1, 24));
exports.Play24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play24Filled", "", 0, 24));
exports.Play28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play28Regular", "", 1, 28));
exports.Play28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play28Filled", "", 0, 28));
exports.Play32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play32Regular", "", 1, 32));
exports.Play32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play32Filled", "", 0, 32));
exports.Play48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play48Regular", "", 1, 48));
exports.Play48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Play48Filled", "", 0, 48));
