"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Poll32Light = exports.Poll32Filled = exports.Poll32Regular = exports.Poll28Filled = exports.Poll28Regular = exports.Poll24Filled = exports.Poll24Regular = exports.Poll20Filled = exports.Poll20Regular = exports.Poll16Filled = exports.Poll16Regular = exports.PollRegular = exports.PollFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PollFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollFilled", "", 2, undefined));
exports.PollRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollRegular", "", 2, undefined));
exports.Poll16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll16Regular", "", 1, 16));
exports.Poll16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll16Filled", "", 0, 16));
exports.Poll20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll20Regular", "", 1, 20));
exports.Poll20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll20Filled", "", 0, 20));
exports.Poll24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll24Regular", "", 1, 24));
exports.Poll24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll24Filled", "", 0, 24));
exports.Poll28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll28Regular", "󰪁", 1, 28));
exports.Poll28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll28Filled", "󰫽", 0, 28));
exports.Poll32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll32Regular", "󰑚", 1, 32));
exports.Poll32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll32Filled", "󰑭", 0, 32));
exports.Poll32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Poll32Light", "", 3, 32));
