"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PollOff32Filled = exports.PollOff32Regular = exports.PollOff24Filled = exports.PollOff24Regular = exports.PollOff20Filled = exports.PollOff20Regular = exports.PollOff16Filled = exports.PollOff16Regular = exports.PollOffRegular = exports.PollOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PollOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOffFilled", "", 2, undefined));
exports.PollOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOffRegular", "", 2, undefined));
exports.PollOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff16Regular", "󰓌", 1, 16));
exports.PollOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff16Filled", "󰕅", 0, 16));
exports.PollOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff20Regular", "󰓍", 1, 20));
exports.PollOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff20Filled", "󰕆", 0, 20));
exports.PollOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff24Regular", "󰓎", 1, 24));
exports.PollOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff24Filled", "󰕇", 0, 24));
exports.PollOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff32Regular", "󰓏", 1, 32));
exports.PollOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PollOff32Filled", "󰕈", 0, 32));
