"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PositionToBack24Filled = exports.PositionToBack24Regular = exports.PositionToBack20Filled = exports.PositionToBack20Regular = exports.PositionToBackRegular = exports.PositionToBackFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PositionToBackFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionToBackFilled", "", 2, undefined));
exports.PositionToBackRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionToBackRegular", "", 2, undefined));
exports.PositionToBack20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionToBack20Regular", "", 1, 20));
exports.PositionToBack20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionToBack20Filled", "", 0, 20));
exports.PositionToBack24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionToBack24Regular", "", 1, 24));
exports.PositionToBack24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionToBack24Filled", "", 0, 24));
