"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PositionForward24Filled = exports.PositionForward24Regular = exports.PositionForward20Filled = exports.PositionForward20Regular = exports.PositionForwardRegular = exports.PositionForwardFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PositionForwardFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionForwardFilled", "", 2, undefined));
exports.PositionForwardRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionForwardRegular", "", 2, undefined));
exports.PositionForward20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionForward20Regular", "", 1, 20));
exports.PositionForward20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionForward20Filled", "", 0, 20));
exports.PositionForward24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionForward24Regular", "", 1, 24));
exports.PositionForward24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PositionForward24Filled", "", 0, 24));
