"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PresenceDnd24Filled = exports.PresenceDnd24Regular = exports.PresenceDnd20Filled = exports.PresenceDnd20Regular = exports.PresenceDnd16Filled = exports.PresenceDnd16Regular = exports.PresenceDnd12Filled = exports.PresenceDnd12Regular = exports.PresenceDnd10Filled = exports.PresenceDnd10Regular = exports.PresenceDndRegular = exports.PresenceDndFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PresenceDndFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDndFilled", "", 2, undefined));
exports.PresenceDndRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDndRegular", "", 2, undefined));
exports.PresenceDnd10Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd10Regular", "", 1, 10));
exports.PresenceDnd10Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd10Filled", "", 0, 10));
exports.PresenceDnd12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd12Regular", "", 1, 12));
exports.PresenceDnd12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd12Filled", "", 0, 12));
exports.PresenceDnd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd16Regular", "", 1, 16));
exports.PresenceDnd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd16Filled", "", 0, 16));
exports.PresenceDnd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd20Regular", "", 1, 20));
exports.PresenceDnd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd20Filled", "", 0, 20));
exports.PresenceDnd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd24Regular", "", 1, 24));
exports.PresenceDnd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceDnd24Filled", "", 0, 24));
