"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PresenceBlocked24Regular = exports.PresenceBlocked20Regular = exports.PresenceBlocked16Regular = exports.PresenceBlocked12Regular = exports.PresenceBlocked10Regular = exports.PresenceBlockedRegular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PresenceBlockedRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceBlockedRegular", "", 2, undefined));
exports.PresenceBlocked10Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceBlocked10Regular", "", 1, 10));
exports.PresenceBlocked12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceBlocked12Regular", "", 1, 12));
exports.PresenceBlocked16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceBlocked16Regular", "", 1, 16));
exports.PresenceBlocked20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceBlocked20Regular", "", 1, 20));
exports.PresenceBlocked24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceBlocked24Regular", "", 1, 24));
