"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PresenceAway24Filled = exports.PresenceAway24Regular = exports.PresenceAway20Filled = exports.PresenceAway20Regular = exports.PresenceAway16Filled = exports.PresenceAway16Regular = exports.PresenceAway12Filled = exports.PresenceAway12Regular = exports.PresenceAway10Filled = exports.PresenceAway10Regular = exports.PresenceAwayRegular = exports.PresenceAwayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PresenceAwayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAwayFilled", "", 2, undefined));
exports.PresenceAwayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAwayRegular", "", 2, undefined));
exports.PresenceAway10Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway10Regular", "󰂐", 1, 10));
exports.PresenceAway10Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway10Filled", "", 0, 10));
exports.PresenceAway12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway12Regular", "󰂑", 1, 12));
exports.PresenceAway12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway12Filled", "", 0, 12));
exports.PresenceAway16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway16Regular", "󰂒", 1, 16));
exports.PresenceAway16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway16Filled", "", 0, 16));
exports.PresenceAway20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway20Regular", "󰂓", 1, 20));
exports.PresenceAway20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway20Filled", "", 0, 20));
exports.PresenceAway24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway24Regular", "󰂔", 1, 24));
exports.PresenceAway24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceAway24Filled", "", 0, 24));
