"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PresenceUnknown24Regular = exports.PresenceUnknown20Regular = exports.PresenceUnknown16Regular = exports.PresenceUnknown12Regular = exports.PresenceUnknown10Regular = exports.PresenceUnknownRegular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PresenceUnknownRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceUnknownRegular", "", 2, undefined));
exports.PresenceUnknown10Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceUnknown10Regular", "", 1, 10));
exports.PresenceUnknown12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceUnknown12Regular", "", 1, 12));
exports.PresenceUnknown16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceUnknown16Regular", "", 1, 16));
exports.PresenceUnknown20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceUnknown20Regular", "", 1, 20));
exports.PresenceUnknown24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenceUnknown24Regular", "", 1, 24));
