"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PresenterOff24Filled = exports.PresenterOff24Regular = exports.PresenterOff20Filled = exports.PresenterOff20Regular = exports.PresenterOffRegular = exports.PresenterOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PresenterOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenterOffFilled", "", 2, undefined));
exports.PresenterOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenterOffRegular", "", 2, undefined));
exports.PresenterOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenterOff20Regular", "", 1, 20));
exports.PresenterOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenterOff20Filled", "", 0, 20));
exports.PresenterOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenterOff24Regular", "", 1, 24));
exports.PresenterOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PresenterOff24Filled", "", 0, 24));
