"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrintAdd24Filled = exports.PrintAdd24Regular = exports.PrintAdd20Filled = exports.PrintAdd20Regular = exports.PrintAddRegular = exports.PrintAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PrintAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PrintAddFilled", "", 2, undefined));
exports.PrintAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PrintAddRegular", "", 2, undefined));
exports.PrintAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PrintAdd20Regular", "", 1, 20));
exports.PrintAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PrintAdd20Filled", "", 0, 20));
exports.PrintAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PrintAdd24Regular", "", 1, 24));
exports.PrintAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PrintAdd24Filled", "", 0, 24));
