"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProjectionScreen28Filled = exports.ProjectionScreen28Regular = exports.ProjectionScreen24Filled = exports.ProjectionScreen24Regular = exports.ProjectionScreen20Filled = exports.ProjectionScreen20Regular = exports.ProjectionScreen16Filled = exports.ProjectionScreen16Regular = exports.ProjectionScreenRegular = exports.ProjectionScreenFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ProjectionScreenFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreenFilled", "", 2, undefined));
exports.ProjectionScreenRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreenRegular", "", 2, undefined));
exports.ProjectionScreen16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen16Regular", "", 1, 16));
exports.ProjectionScreen16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen16Filled", "", 0, 16));
exports.ProjectionScreen20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen20Regular", "", 1, 20));
exports.ProjectionScreen20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen20Filled", "", 0, 20));
exports.ProjectionScreen24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen24Regular", "", 1, 24));
exports.ProjectionScreen24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen24Filled", "", 0, 24));
exports.ProjectionScreen28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen28Regular", "", 1, 28));
exports.ProjectionScreen28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ProjectionScreen28Filled", "", 0, 28));
