"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Prompt48Filled = exports.Prompt48Regular = exports.Prompt32Filled = exports.Prompt32Regular = exports.Prompt28Filled = exports.Prompt28Regular = exports.Prompt24Filled = exports.Prompt24Regular = exports.Prompt20Filled = exports.Prompt20Regular = exports.Prompt16Filled = exports.Prompt16Regular = exports.PromptRegular = exports.PromptFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PromptFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PromptFilled", "", 2, undefined));
exports.PromptRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PromptRegular", "", 2, undefined));
exports.Prompt16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt16Regular", "󰘯", 1, 16));
exports.Prompt16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt16Filled", "󰚫", 0, 16));
exports.Prompt20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt20Regular", "󰘰", 1, 20));
exports.Prompt20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt20Filled", "󰚬", 0, 20));
exports.Prompt24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt24Regular", "󰘱", 1, 24));
exports.Prompt24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt24Filled", "󰚭", 0, 24));
exports.Prompt28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt28Regular", "󰘲", 1, 28));
exports.Prompt28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt28Filled", "󰚮", 0, 28));
exports.Prompt32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt32Regular", "󰘳", 1, 32));
exports.Prompt32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt32Filled", "󰚯", 0, 32));
exports.Prompt48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt48Regular", "󰘴", 1, 48));
exports.Prompt48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Prompt48Filled", "󰚰", 0, 48));
