"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PulseSquare24Filled = exports.PulseSquare24Regular = exports.PulseSquare20Filled = exports.PulseSquare20Regular = exports.PulseSquareRegular = exports.PulseSquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PulseSquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseSquareFilled", "", 2, undefined));
exports.PulseSquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseSquareRegular", "", 2, undefined));
exports.PulseSquare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseSquare20Regular", "", 1, 20));
exports.PulseSquare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseSquare20Filled", "", 0, 20));
exports.PulseSquare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseSquare24Regular", "", 1, 24));
exports.PulseSquare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseSquare24Filled", "", 0, 24));
