"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pulse32Filled = exports.Pulse32Regular = exports.Pulse28Filled = exports.Pulse28Regular = exports.Pulse24Filled = exports.Pulse24Regular = exports.Pulse20Filled = exports.Pulse20Regular = exports.PulseRegular = exports.PulseFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PulseFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseFilled", "", 2, undefined));
exports.PulseRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PulseRegular", "", 2, undefined));
exports.Pulse20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse20Regular", "", 1, 20));
exports.Pulse20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse20Filled", "", 0, 20));
exports.Pulse24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse24Regular", "", 1, 24));
exports.Pulse24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse24Filled", "", 0, 24));
exports.Pulse28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse28Regular", "", 1, 28));
exports.Pulse28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse28Filled", "", 0, 28));
exports.Pulse32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse32Regular", "", 1, 32));
exports.Pulse32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Pulse32Filled", "", 0, 32));
