"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PuzzleCube48Filled = exports.PuzzleCube48Regular = exports.PuzzleCube32Filled = exports.PuzzleCube32Regular = exports.PuzzleCube28Filled = exports.PuzzleCube28Regular = exports.PuzzleCube24Filled = exports.PuzzleCube24Regular = exports.PuzzleCube20Filled = exports.PuzzleCube20Regular = exports.PuzzleCube16Filled = exports.PuzzleCube16Regular = exports.PuzzleCubeRegular = exports.PuzzleCubeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.PuzzleCubeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCubeFilled", "", 2, undefined));
exports.PuzzleCubeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCubeRegular", "", 2, undefined));
exports.PuzzleCube16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube16Regular", "", 1, 16));
exports.PuzzleCube16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube16Filled", "", 0, 16));
exports.PuzzleCube20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube20Regular", "", 1, 20));
exports.PuzzleCube20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube20Filled", "", 0, 20));
exports.PuzzleCube24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube24Regular", "", 1, 24));
exports.PuzzleCube24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube24Filled", "", 0, 24));
exports.PuzzleCube28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube28Regular", "", 1, 28));
exports.PuzzleCube28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube28Filled", "", 0, 28));
exports.PuzzleCube32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube32Regular", "󰪂", 1, 32));
exports.PuzzleCube32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube32Filled", "󰫾", 0, 32));
exports.PuzzleCube48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube48Regular", "", 1, 48));
exports.PuzzleCube48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("PuzzleCube48Filled", "", 0, 48));
