"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QuestionCircle48Filled = exports.QuestionCircle48Regular = exports.QuestionCircle32Filled = exports.QuestionCircle32Regular = exports.QuestionCircle28Filled = exports.QuestionCircle28Regular = exports.QuestionCircle24Filled = exports.QuestionCircle24Regular = exports.QuestionCircle20Filled = exports.QuestionCircle20Regular = exports.QuestionCircle16Filled = exports.QuestionCircle16Regular = exports.QuestionCircle12Filled = exports.QuestionCircle12Regular = exports.QuestionCircleRegular = exports.QuestionCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.QuestionCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircleFilled", "", 2, undefined));
exports.QuestionCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircleRegular", "", 2, undefined));
exports.QuestionCircle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle12Regular", "", 1, 12));
exports.QuestionCircle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle12Filled", "", 0, 12));
exports.QuestionCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle16Regular", "", 1, 16));
exports.QuestionCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle16Filled", "", 0, 16));
exports.QuestionCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle20Regular", "", 1, 20));
exports.QuestionCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle20Filled", "", 0, 20));
exports.QuestionCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle24Regular", "", 1, 24));
exports.QuestionCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle24Filled", "", 0, 24));
exports.QuestionCircle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle28Regular", "", 1, 28));
exports.QuestionCircle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle28Filled", "", 0, 28));
exports.QuestionCircle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle32Regular", "", 1, 32));
exports.QuestionCircle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle32Filled", "", 0, 32));
exports.QuestionCircle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle48Regular", "", 1, 48));
exports.QuestionCircle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionCircle48Filled", "", 0, 48));
