"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Question48Filled = exports.Question48Regular = exports.Question32Light = exports.Question32Filled = exports.Question32Regular = exports.Question28Filled = exports.Question28Regular = exports.Question24Filled = exports.Question24Regular = exports.Question20Filled = exports.Question20Regular = exports.Question16Filled = exports.Question16Regular = exports.QuestionRegular = exports.QuestionFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.QuestionFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionFilled", "", 2, undefined));
exports.QuestionRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("QuestionRegular", "", 2, undefined));
exports.Question16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question16Regular", "", 1, 16));
exports.Question16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question16Filled", "", 0, 16));
exports.Question20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question20Regular", "", 1, 20));
exports.Question20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question20Filled", "", 0, 20));
exports.Question24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question24Regular", "", 1, 24));
exports.Question24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question24Filled", "", 0, 24));
exports.Question28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question28Regular", "", 1, 28));
exports.Question28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question28Filled", "", 0, 28));
exports.Question32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question32Regular", "󰑛", 1, 32));
exports.Question32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question32Filled", "󰑮", 0, 32));
exports.Question32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question32Light", "", 3, 32));
exports.Question48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question48Regular", "", 1, 48));
exports.Question48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Question48Filled", "", 0, 48));
