"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RadioButton24Filled = exports.RadioButton24Regular = exports.RadioButton20Filled = exports.RadioButton20Regular = exports.RadioButton16Filled = exports.RadioButton16Regular = exports.RadioButtonRegular = exports.RadioButtonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RadioButtonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButtonFilled", "", 2, undefined));
exports.RadioButtonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButtonRegular", "", 2, undefined));
exports.RadioButton16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButton16Regular", "", 1, 16));
exports.RadioButton16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButton16Filled", "", 0, 16));
exports.RadioButton20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButton20Regular", "", 1, 20));
exports.RadioButton20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButton20Filled", "", 0, 20));
exports.RadioButton24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButton24Regular", "", 1, 24));
exports.RadioButton24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RadioButton24Filled", "", 0, 24));
