"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RatingMature24Filled = exports.RatingMature24Regular = exports.RatingMature20Filled = exports.RatingMature20Regular = exports.RatingMature16Filled = exports.RatingMature16Regular = exports.RatingMatureRegular = exports.RatingMatureFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RatingMatureFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMatureFilled", "", 2, undefined));
exports.RatingMatureRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMatureRegular", "", 2, undefined));
exports.RatingMature16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMature16Regular", "", 1, 16));
exports.RatingMature16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMature16Filled", "", 0, 16));
exports.RatingMature20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMature20Regular", "", 1, 20));
exports.RatingMature20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMature20Filled", "", 0, 20));
exports.RatingMature24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMature24Regular", "", 1, 24));
exports.RatingMature24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RatingMature24Filled", "", 0, 24));
