"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReadingList28Filled = exports.ReadingList28Regular = exports.ReadingList24Filled = exports.ReadingList24Regular = exports.ReadingList20Filled = exports.ReadingList20Regular = exports.ReadingList16Filled = exports.ReadingList16Regular = exports.ReadingListRegular = exports.ReadingListFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ReadingListFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingListFilled", "", 2, undefined));
exports.ReadingListRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingListRegular", "", 2, undefined));
exports.ReadingList16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList16Regular", "", 1, 16));
exports.ReadingList16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList16Filled", "", 0, 16));
exports.ReadingList20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList20Regular", "", 1, 20));
exports.ReadingList20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList20Filled", "", 0, 20));
exports.ReadingList24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList24Regular", "", 1, 24));
exports.ReadingList24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList24Filled", "", 0, 24));
exports.ReadingList28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList28Regular", "", 1, 28));
exports.ReadingList28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReadingList28Filled", "", 0, 28));
