"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReceiptMoney24Filled = exports.ReceiptMoney24Regular = exports.ReceiptMoney20Filled = exports.ReceiptMoney20Regular = exports.ReceiptMoney16Filled = exports.ReceiptMoney16Regular = exports.ReceiptMoneyRegular = exports.ReceiptMoneyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ReceiptMoneyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoneyFilled", "", 2, undefined));
exports.ReceiptMoneyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoneyRegular", "", 2, undefined));
exports.ReceiptMoney16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoney16Regular", "󰂗", 1, 16));
exports.ReceiptMoney16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoney16Filled", "󰂖", 0, 16));
exports.ReceiptMoney20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoney20Regular", "", 1, 20));
exports.ReceiptMoney20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoney20Filled", "", 0, 20));
exports.ReceiptMoney24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoney24Regular", "", 1, 24));
exports.ReceiptMoney24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptMoney24Filled", "", 0, 24));
