"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReceiptPlay24Filled = exports.ReceiptPlay24Regular = exports.ReceiptPlay20Filled = exports.ReceiptPlay20Regular = exports.ReceiptPlayRegular = exports.ReceiptPlayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ReceiptPlayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptPlayFilled", "", 2, undefined));
exports.ReceiptPlayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptPlayRegular", "", 2, undefined));
exports.ReceiptPlay20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptPlay20Regular", "", 1, 20));
exports.ReceiptPlay20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptPlay20Filled", "", 0, 20));
exports.ReceiptPlay24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptPlay24Regular", "", 1, 24));
exports.ReceiptPlay24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ReceiptPlay24Filled", "", 0, 24));
