"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Record48Filled = exports.Record48Regular = exports.Record32Filled = exports.Record32Regular = exports.Record28Filled = exports.Record28Regular = exports.Record24Filled = exports.Record24Regular = exports.Record20Filled = exports.Record20Regular = exports.Record16Filled = exports.Record16Regular = exports.Record12Filled = exports.Record12Regular = exports.RecordRegular = exports.RecordFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RecordFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RecordFilled", "", 2, undefined));
exports.RecordRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RecordRegular", "", 2, undefined));
exports.Record12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record12Regular", "", 1, 12));
exports.Record12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record12Filled", "", 0, 12));
exports.Record16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record16Regular", "", 1, 16));
exports.Record16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record16Filled", "", 0, 16));
exports.Record20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record20Regular", "", 1, 20));
exports.Record20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record20Filled", "", 0, 20));
exports.Record24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record24Regular", "", 1, 24));
exports.Record24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record24Filled", "", 0, 24));
exports.Record28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record28Regular", "", 1, 28));
exports.Record28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record28Filled", "", 0, 28));
exports.Record32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record32Regular", "", 1, 32));
exports.Record32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record32Filled", "", 0, 32));
exports.Record48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record48Regular", "", 1, 48));
exports.Record48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Record48Filled", "", 0, 48));
