"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Recycle32Filled = exports.Recycle32Regular = exports.Recycle20Filled = exports.Recycle20Regular = exports.RecycleRegular = exports.RecycleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RecycleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RecycleFilled", "", 2, undefined));
exports.RecycleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RecycleRegular", "", 2, undefined));
exports.Recycle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Recycle20Regular", "", 1, 20));
exports.Recycle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Recycle20Filled", "", 0, 20));
exports.Recycle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Recycle32Regular", "", 1, 32));
exports.Recycle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Recycle32Filled", "", 0, 32));
