"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RemixAdd32Filled = exports.RemixAdd32Regular = exports.RemixAdd24Filled = exports.RemixAdd24Regular = exports.RemixAdd20Filled = exports.RemixAdd20Regular = exports.RemixAdd16Filled = exports.RemixAdd16Regular = exports.RemixAddRegular = exports.RemixAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RemixAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAddFilled", "", 2, undefined));
exports.RemixAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAddRegular", "", 2, undefined));
exports.RemixAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd16Regular", "󰋆", 1, 16));
exports.RemixAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd16Filled", "󰋙", 0, 16));
exports.RemixAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd20Regular", "󰋇", 1, 20));
exports.RemixAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd20Filled", "󰋚", 0, 20));
exports.RemixAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd24Regular", "󰋈", 1, 24));
exports.RemixAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd24Filled", "󰋛", 0, 24));
exports.RemixAdd32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd32Regular", "󰋉", 1, 32));
exports.RemixAdd32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemixAdd32Filled", "󰋜", 0, 32));
