"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Remote20Filled = exports.Remote20Regular = exports.Remote16Filled = exports.Remote16Regular = exports.RemoteRegular = exports.RemoteFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RemoteFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemoteFilled", "", 2, undefined));
exports.RemoteRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RemoteRegular", "", 2, undefined));
exports.Remote16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Remote16Regular", "", 1, 16));
exports.Remote16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Remote16Filled", "", 0, 16));
exports.Remote20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Remote20Regular", "", 1, 20));
exports.Remote20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Remote20Filled", "", 0, 20));
