"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResizeVideo24Filled = exports.ResizeVideo24Regular = exports.ResizeVideo20Filled = exports.ResizeVideo20Regular = exports.ResizeVideoRegular = exports.ResizeVideoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ResizeVideoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeVideoFilled", "", 2, undefined));
exports.ResizeVideoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeVideoRegular", "", 2, undefined));
exports.ResizeVideo20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeVideo20Regular", "", 1, 20));
exports.ResizeVideo20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeVideo20Filled", "", 0, 20));
exports.ResizeVideo24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeVideo24Regular", "", 1, 24));
exports.ResizeVideo24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeVideo24Filled", "", 0, 24));
