"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResizeImage24Filled = exports.ResizeImage24Regular = exports.ResizeImage20Filled = exports.ResizeImage20Regular = exports.ResizeImageRegular = exports.ResizeImageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ResizeImageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeImageFilled", "", 2, undefined));
exports.ResizeImageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeImageRegular", "", 2, undefined));
exports.ResizeImage20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeImage20Regular", "", 1, 20));
exports.ResizeImage20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeImage20Filled", "", 0, 20));
exports.ResizeImage24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeImage24Regular", "", 1, 24));
exports.ResizeImage24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeImage24Filled", "", 0, 24));
