"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResizeTable24Filled = exports.ResizeTable24Regular = exports.ResizeTable20Filled = exports.ResizeTable20Regular = exports.ResizeTableRegular = exports.ResizeTableFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ResizeTableFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeTableFilled", "", 2, undefined));
exports.ResizeTableRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeTableRegular", "", 2, undefined));
exports.ResizeTable20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeTable20Regular", "", 1, 20));
exports.ResizeTable20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeTable20Filled", "", 0, 20));
exports.ResizeTable24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeTable24Regular", "", 1, 24));
exports.ResizeTable24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeTable24Filled", "", 0, 24));
