"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResizeLarge24Filled = exports.ResizeLarge24Regular = exports.ResizeLarge20Filled = exports.ResizeLarge20Regular = exports.ResizeLarge16Filled = exports.ResizeLarge16Regular = exports.ResizeLargeRegular = exports.ResizeLargeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ResizeLargeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLargeFilled", "", 2, undefined));
exports.ResizeLargeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLargeRegular", "", 2, undefined));
exports.ResizeLarge16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLarge16Regular", "", 1, 16));
exports.ResizeLarge16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLarge16Filled", "", 0, 16));
exports.ResizeLarge20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLarge20Regular", "", 1, 20));
exports.ResizeLarge20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLarge20Filled", "", 0, 20));
exports.ResizeLarge24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLarge24Regular", "", 1, 24));
exports.ResizeLarge24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ResizeLarge24Filled", "", 0, 24));
