"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Road24Filled = exports.Road24Regular = exports.Road20Filled = exports.Road20Regular = exports.RoadRegular = exports.RoadFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RoadFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RoadFilled", "", 2, undefined));
exports.RoadRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RoadRegular", "", 2, undefined));
exports.Road20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Road20Regular", "󰕷", 1, 20));
exports.Road20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Road20Filled", "󰗰", 0, 20));
exports.Road24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Road24Regular", "󰕸", 1, 24));
exports.Road24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Road24Filled", "󰗱", 0, 24));
