"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Rocket24Filled = exports.Rocket24Regular = exports.Rocket20Filled = exports.Rocket20Regular = exports.Rocket16Filled = exports.Rocket16Regular = exports.RocketRegular = exports.RocketFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RocketFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RocketFilled", "", 2, undefined));
exports.RocketRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RocketRegular", "", 2, undefined));
exports.Rocket16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Rocket16Regular", "", 1, 16));
exports.Rocket16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Rocket16Filled", "", 0, 16));
exports.Rocket20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Rocket20Regular", "", 1, 20));
exports.Rocket20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Rocket20Filled", "", 0, 20));
exports.Rocket24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Rocket24Regular", "", 1, 24));
exports.Rocket24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Rocket24Filled", "", 0, 24));
