"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Router24Filled = exports.Router24Regular = exports.Router20Filled = exports.Router20Regular = exports.RouterRegular = exports.RouterFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RouterFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RouterFilled", "", 2, undefined));
exports.RouterRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RouterRegular", "", 2, undefined));
exports.Router20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Router20Regular", "", 1, 20));
exports.Router20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Router20Filled", "", 0, 20));
exports.Router24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Router24Regular", "", 1, 24));
exports.Router24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Router24Filled", "", 0, 24));
