"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RowTriple24Filled = exports.RowTriple24Regular = exports.RowTriple20Filled = exports.RowTriple20Regular = exports.RowTripleRegular = exports.RowTripleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RowTripleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RowTripleFilled", "", 2, undefined));
exports.RowTripleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RowTripleRegular", "", 2, undefined));
exports.RowTriple20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RowTriple20Regular", "", 1, 20));
exports.RowTriple20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RowTriple20Filled", "", 0, 20));
exports.RowTriple24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RowTriple24Regular", "", 1, 24));
exports.RowTriple24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RowTriple24Filled", "", 0, 24));
