"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ruler48Filled = exports.Ruler48Regular = exports.Ruler32Filled = exports.Ruler32Regular = exports.Ruler28Filled = exports.Ruler28Regular = exports.Ruler24Filled = exports.Ruler24Regular = exports.Ruler20Filled = exports.Ruler20Regular = exports.Ruler16Filled = exports.Ruler16Regular = exports.RulerRegular = exports.RulerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.RulerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RulerFilled", "", 2, undefined));
exports.RulerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("RulerRegular", "", 2, undefined));
exports.Ruler16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler16Regular", "", 1, 16));
exports.Ruler16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler16Filled", "", 0, 16));
exports.Ruler20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler20Regular", "", 1, 20));
exports.Ruler20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler20Filled", "", 0, 20));
exports.Ruler24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler24Regular", "", 1, 24));
exports.Ruler24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler24Filled", "", 0, 24));
exports.Ruler28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler28Regular", "", 1, 28));
exports.Ruler28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler28Filled", "", 0, 28));
exports.Ruler32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler32Regular", "", 1, 32));
exports.Ruler32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler32Filled", "", 0, 32));
exports.Ruler48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler48Regular", "", 1, 48));
exports.Ruler48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Ruler48Filled", "", 0, 48));
