"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Sanitize24Filled = exports.Sanitize24Regular = exports.Sanitize20Filled = exports.Sanitize20Regular = exports.SanitizeRegular = exports.SanitizeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SanitizeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SanitizeFilled", "", 2, undefined));
exports.SanitizeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SanitizeRegular", "", 2, undefined));
exports.Sanitize20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sanitize20Regular", "", 1, 20));
exports.Sanitize20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sanitize20Filled", "", 0, 20));
exports.Sanitize24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sanitize24Regular", "", 1, 24));
exports.Sanitize24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sanitize24Filled", "", 0, 24));
