"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Save32Light = exports.Save32Filled = exports.Save32Regular = exports.Save28Filled = exports.Save28Regular = exports.Save24Filled = exports.Save24Regular = exports.Save20Filled = exports.Save20Regular = exports.Save16Filled = exports.Save16Regular = exports.SaveRegular = exports.SaveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SaveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SaveFilled", "", 2, undefined));
exports.SaveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SaveRegular", "", 2, undefined));
exports.Save16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save16Regular", "", 1, 16));
exports.Save16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save16Filled", "", 0, 16));
exports.Save20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save20Regular", "", 1, 20));
exports.Save20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save20Filled", "", 0, 20));
exports.Save24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save24Regular", "", 1, 24));
exports.Save24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save24Filled", "", 0, 24));
exports.Save28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save28Regular", "", 1, 28));
exports.Save28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save28Filled", "", 0, 28));
exports.Save32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save32Regular", "󰕹", 1, 32));
exports.Save32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save32Filled", "󰗲", 0, 32));
exports.Save32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Save32Light", "", 3, 32));
