"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Savings32Filled = exports.Savings32Regular = exports.Savings24Filled = exports.Savings24Regular = exports.Savings20Filled = exports.Savings20Regular = exports.Savings16Filled = exports.Savings16Regular = exports.SavingsRegular = exports.SavingsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SavingsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SavingsFilled", "", 2, undefined));
exports.SavingsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SavingsRegular", "", 2, undefined));
exports.Savings16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings16Regular", "", 1, 16));
exports.Savings16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings16Filled", "", 0, 16));
exports.Savings20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings20Regular", "", 1, 20));
exports.Savings20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings20Filled", "", 0, 20));
exports.Savings24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings24Regular", "", 1, 24));
exports.Savings24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings24Filled", "", 0, 24));
exports.Savings32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings32Regular", "󰟦", 1, 32));
exports.Savings32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Savings32Filled", "󰡣", 0, 32));
