"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Scales32Filled = exports.Scales32Regular = exports.Scales24Filled = exports.Scales24Regular = exports.Scales20Filled = exports.Scales20Regular = exports.ScalesRegular = exports.ScalesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ScalesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScalesFilled", "", 2, undefined));
exports.ScalesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScalesRegular", "", 2, undefined));
exports.Scales20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Scales20Regular", "", 1, 20));
exports.Scales20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Scales20Filled", "", 0, 20));
exports.Scales24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Scales24Regular", "", 1, 24));
exports.Scales24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Scales24Filled", "", 0, 24));
exports.Scales32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Scales32Regular", "", 1, 32));
exports.Scales32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Scales32Filled", "", 0, 32));
