"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScaleFill24Filled = exports.ScaleFill24Regular = exports.ScaleFill20Filled = exports.ScaleFill20Regular = exports.ScaleFillRegular = exports.ScaleFillFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ScaleFillFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScaleFillFilled", "", 2, undefined));
exports.ScaleFillRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScaleFillRegular", "", 2, undefined));
exports.ScaleFill20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScaleFill20Regular", "", 1, 20));
exports.ScaleFill20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScaleFill20Filled", "", 0, 20));
exports.ScaleFill24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScaleFill24Regular", "", 1, 24));
exports.ScaleFill24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScaleFill24Filled", "", 0, 24));
