"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScanPerson48Filled = exports.ScanPerson48Regular = exports.ScanPerson28Filled = exports.ScanPerson28Regular = exports.ScanPerson24Filled = exports.ScanPerson24Regular = exports.ScanPerson20Filled = exports.ScanPerson20Regular = exports.ScanPerson16Filled = exports.ScanPerson16Regular = exports.ScanPersonRegular = exports.ScanPersonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ScanPersonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPersonFilled", "", 2, undefined));
exports.ScanPersonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPersonRegular", "", 2, undefined));
exports.ScanPerson16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson16Regular", "󰌚", 1, 16));
exports.ScanPerson16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson16Filled", "󰌭", 0, 16));
exports.ScanPerson20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson20Regular", "󰌛", 1, 20));
exports.ScanPerson20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson20Filled", "󰌮", 0, 20));
exports.ScanPerson24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson24Regular", "󰌜", 1, 24));
exports.ScanPerson24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson24Filled", "󰌯", 0, 24));
exports.ScanPerson28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson28Regular", "󰌝", 1, 28));
exports.ScanPerson28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson28Filled", "󰌰", 0, 28));
exports.ScanPerson48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson48Regular", "󰌞", 1, 48));
exports.ScanPerson48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanPerson48Filled", "󰌱", 0, 48));
