"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScanText48Filled = exports.ScanText48Regular = exports.ScanText32Filled = exports.ScanText32Regular = exports.ScanText28Filled = exports.ScanText28Regular = exports.ScanText24Filled = exports.ScanText24Regular = exports.ScanText20Filled = exports.ScanText20Regular = exports.ScanText16Filled = exports.ScanText16Regular = exports.ScanTextRegular = exports.ScanTextFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ScanTextFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanTextFilled", "", 2, undefined));
exports.ScanTextRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanTextRegular", "", 2, undefined));
exports.ScanText16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText16Regular", "", 1, 16));
exports.ScanText16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText16Filled", "", 0, 16));
exports.ScanText20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText20Regular", "", 1, 20));
exports.ScanText20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText20Filled", "", 0, 20));
exports.ScanText24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText24Regular", "", 1, 24));
exports.ScanText24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText24Filled", "", 0, 24));
exports.ScanText28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText28Regular", "", 1, 28));
exports.ScanText28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText28Filled", "", 0, 28));
exports.ScanText32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText32Regular", "󰫦", 1, 32));
exports.ScanText32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText32Filled", "󰭤", 0, 32));
exports.ScanText48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText48Regular", "󰫧", 1, 48));
exports.ScanText48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ScanText48Filled", "󰭥", 0, 48));
