"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchSquare24Filled = exports.SearchSquare24Regular = exports.SearchSquare20Filled = exports.SearchSquare20Regular = exports.SearchSquare16Filled = exports.SearchSquare16Regular = exports.SearchSquareRegular = exports.SearchSquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SearchSquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquareFilled", "", 2, undefined));
exports.SearchSquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquareRegular", "", 2, undefined));
exports.SearchSquare16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquare16Regular", "󰗌", 1, 16));
exports.SearchSquare16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquare16Filled", "󰙅", 0, 16));
exports.SearchSquare20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquare20Regular", "", 1, 20));
exports.SearchSquare20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquare20Filled", "", 0, 20));
exports.SearchSquare24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquare24Regular", "", 1, 24));
exports.SearchSquare24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SearchSquare24Filled", "", 0, 24));
