"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SelectAllOn24Filled = exports.SelectAllOn24Regular = exports.SelectAllOn20Filled = exports.SelectAllOn20Regular = exports.SelectAllOn16Filled = exports.SelectAllOn16Regular = exports.SelectAllOnRegular = exports.SelectAllOnFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SelectAllOnFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOnFilled", "", 2, undefined));
exports.SelectAllOnRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOnRegular", "", 2, undefined));
exports.SelectAllOn16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOn16Regular", "󰒹", 1, 16));
exports.SelectAllOn16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOn16Filled", "󰔲", 0, 16));
exports.SelectAllOn20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOn20Regular", "", 1, 20));
exports.SelectAllOn20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOn20Filled", "", 0, 20));
exports.SelectAllOn24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOn24Regular", "", 1, 24));
exports.SelectAllOn24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SelectAllOn24Filled", "", 0, 24));
