"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Send48Filled = exports.Send48Regular = exports.Send32Filled = exports.Send32Regular = exports.Send28Filled = exports.Send28Regular = exports.Send24Filled = exports.Send24Regular = exports.Send20Filled = exports.Send20Regular = exports.Send16Filled = exports.Send16Regular = exports.SendRegular = exports.SendFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SendFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SendFilled", "", 2, undefined, { flipInRtl: true }));
exports.SendRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SendRegular", "", 2, undefined, { flipInRtl: true }));
exports.Send16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send16Regular", "", 1, 16, { flipInRtl: true }));
exports.Send16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send16Filled", "", 0, 16, { flipInRtl: true }));
exports.Send20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send20Regular", "", 1, 20, { flipInRtl: true }));
exports.Send20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send20Filled", "", 0, 20, { flipInRtl: true }));
exports.Send24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send24Regular", "", 1, 24, { flipInRtl: true }));
exports.Send24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send24Filled", "", 0, 24, { flipInRtl: true }));
exports.Send28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send28Regular", "", 1, 28, { flipInRtl: true }));
exports.Send28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send28Filled", "", 0, 28, { flipInRtl: true }));
exports.Send32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send32Regular", "󰂘", 1, 32, { flipInRtl: true }));
exports.Send32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send32Filled", "󰂗", 0, 32, { flipInRtl: true }));
exports.Send48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send48Regular", "󰂙", 1, 48, { flipInRtl: true }));
exports.Send48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Send48Filled", "󰂘", 0, 48, { flipInRtl: true }));
