"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shapes48Filled = exports.Shapes48Regular = exports.Shapes32Filled = exports.Shapes32Regular = exports.Shapes28Filled = exports.Shapes28Regular = exports.Shapes24Filled = exports.Shapes24Regular = exports.Shapes20Filled = exports.Shapes20Regular = exports.Shapes16Filled = exports.Shapes16Regular = exports.ShapesRegular = exports.ShapesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShapesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapesFilled", "", 2, undefined));
exports.ShapesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapesRegular", "", 2, undefined));
exports.Shapes16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes16Regular", "", 1, 16));
exports.Shapes16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes16Filled", "", 0, 16));
exports.Shapes20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes20Regular", "", 1, 20));
exports.Shapes20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes20Filled", "", 0, 20));
exports.Shapes24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes24Regular", "", 1, 24));
exports.Shapes24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes24Filled", "", 0, 24));
exports.Shapes28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes28Regular", "", 1, 28));
exports.Shapes28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes28Filled", "", 0, 28));
exports.Shapes32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes32Regular", "󰏃", 1, 32));
exports.Shapes32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes32Filled", "󰏖", 0, 32));
exports.Shapes48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes48Regular", "", 1, 48));
exports.Shapes48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shapes48Filled", "", 0, 48));
