"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeUnion24Filled = exports.ShapeUnion24Regular = exports.ShapeUnion20Filled = exports.ShapeUnion20Regular = exports.ShapeUnion16Filled = exports.ShapeUnion16Regular = exports.ShapeUnionRegular = exports.ShapeUnionFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShapeUnionFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnionFilled", "", 2, undefined));
exports.ShapeUnionRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnionRegular", "", 2, undefined));
exports.ShapeUnion16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnion16Regular", "", 1, 16));
exports.ShapeUnion16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnion16Filled", "", 0, 16));
exports.ShapeUnion20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnion20Regular", "", 1, 20));
exports.ShapeUnion20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnion20Filled", "", 0, 20));
exports.ShapeUnion24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnion24Regular", "", 1, 24));
exports.ShapeUnion24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeUnion24Filled", "", 0, 24));
