"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeOrganic48Filled = exports.ShapeOrganic48Regular = exports.ShapeOrganic32Filled = exports.ShapeOrganic32Regular = exports.ShapeOrganic28Filled = exports.ShapeOrganic28Regular = exports.ShapeOrganic24Filled = exports.ShapeOrganic24Regular = exports.ShapeOrganic20Filled = exports.ShapeOrganic20Regular = exports.ShapeOrganic16Filled = exports.ShapeOrganic16Regular = exports.ShapeOrganicRegular = exports.ShapeOrganicFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShapeOrganicFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganicFilled", "", 2, undefined));
exports.ShapeOrganicRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganicRegular", "", 2, undefined));
exports.ShapeOrganic16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic16Regular", "󰎗", 1, 16));
exports.ShapeOrganic16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic16Filled", "󰎪", 0, 16));
exports.ShapeOrganic20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic20Regular", "󰎘", 1, 20));
exports.ShapeOrganic20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic20Filled", "󰎫", 0, 20));
exports.ShapeOrganic24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic24Regular", "󰎙", 1, 24));
exports.ShapeOrganic24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic24Filled", "󰎬", 0, 24));
exports.ShapeOrganic28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic28Regular", "󰎚", 1, 28));
exports.ShapeOrganic28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic28Filled", "󰎭", 0, 28));
exports.ShapeOrganic32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic32Regular", "󰎛", 1, 32));
exports.ShapeOrganic32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic32Filled", "󰎮", 0, 32));
exports.ShapeOrganic48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic48Regular", "󰎜", 1, 48));
exports.ShapeOrganic48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShapeOrganic48Filled", "󰎯", 0, 48));
