"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShareAndroid32Filled = exports.ShareAndroid32Regular = exports.ShareAndroid24Filled = exports.ShareAndroid24Regular = exports.ShareAndroid20Filled = exports.ShareAndroid20Regular = exports.ShareAndroid16Filled = exports.ShareAndroid16Regular = exports.ShareAndroidRegular = exports.ShareAndroidFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShareAndroidFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroidFilled", "", 2, undefined));
exports.ShareAndroidRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroidRegular", "", 2, undefined));
exports.ShareAndroid16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid16Regular", "󰒺", 1, 16));
exports.ShareAndroid16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid16Filled", "󰔳", 0, 16));
exports.ShareAndroid20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid20Regular", "", 1, 20));
exports.ShareAndroid20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid20Filled", "", 0, 20));
exports.ShareAndroid24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid24Regular", "", 1, 24));
exports.ShareAndroid24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid24Filled", "", 0, 24));
exports.ShareAndroid32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid32Regular", "󰒻", 1, 32));
exports.ShareAndroid32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShareAndroid32Filled", "󰔴", 0, 32));
