"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShieldError48Filled = exports.ShieldError48Regular = exports.ShieldError32Light = exports.ShieldError32Filled = exports.ShieldError32Regular = exports.ShieldError28Filled = exports.ShieldError28Regular = exports.ShieldError24Filled = exports.ShieldError24Regular = exports.ShieldError20Filled = exports.ShieldError20Regular = exports.ShieldError16Filled = exports.ShieldError16Regular = exports.ShieldErrorRegular = exports.ShieldErrorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShieldErrorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldErrorFilled", "", 2, undefined));
exports.ShieldErrorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldErrorRegular", "", 2, undefined));
exports.ShieldError16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError16Regular", "", 1, 16));
exports.ShieldError16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError16Filled", "", 0, 16));
exports.ShieldError20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError20Regular", "", 1, 20));
exports.ShieldError20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError20Filled", "", 0, 20));
exports.ShieldError24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError24Regular", "", 1, 24));
exports.ShieldError24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError24Filled", "", 0, 24));
exports.ShieldError28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError28Regular", "󰧦", 1, 28));
exports.ShieldError28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError28Filled", "󰩣", 0, 28));
exports.ShieldError32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError32Regular", "󰧧", 1, 32));
exports.ShieldError32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError32Filled", "󰩤", 0, 32));
exports.ShieldError32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError32Light", "", 3, 32));
exports.ShieldError48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError48Regular", "󰧨", 1, 48));
exports.ShieldError48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldError48Filled", "󰩥", 0, 48));
