"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShieldGlobe24Filled = exports.ShieldGlobe24Regular = exports.ShieldGlobe20Filled = exports.ShieldGlobe20Regular = exports.ShieldGlobe16Filled = exports.ShieldGlobe16Regular = exports.ShieldGlobeRegular = exports.ShieldGlobeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShieldGlobeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobeFilled", "", 2, undefined));
exports.ShieldGlobeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobeRegular", "", 2, undefined));
exports.ShieldGlobe16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobe16Regular", "", 1, 16));
exports.ShieldGlobe16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobe16Filled", "", 0, 16));
exports.ShieldGlobe20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobe20Regular", "", 1, 20));
exports.ShieldGlobe20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobe20Filled", "", 0, 20));
exports.ShieldGlobe24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobe24Regular", "", 1, 24));
exports.ShieldGlobe24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldGlobe24Filled", "", 0, 24));
