"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShieldKeyhole24Filled = exports.ShieldKeyhole24Regular = exports.ShieldKeyhole20Filled = exports.ShieldKeyhole20Regular = exports.ShieldKeyhole16Filled = exports.ShieldKeyhole16Regular = exports.ShieldKeyholeRegular = exports.ShieldKeyholeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShieldKeyholeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyholeFilled", "", 2, undefined));
exports.ShieldKeyholeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyholeRegular", "", 2, undefined));
exports.ShieldKeyhole16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyhole16Regular", "", 1, 16));
exports.ShieldKeyhole16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyhole16Filled", "", 0, 16));
exports.ShieldKeyhole20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyhole20Regular", "", 1, 20));
exports.ShieldKeyhole20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyhole20Filled", "", 0, 20));
exports.ShieldKeyhole24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyhole24Regular", "", 1, 24));
exports.ShieldKeyhole24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShieldKeyhole24Filled", "", 0, 24));
