"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShiftsDay24Filled = exports.ShiftsDay24Regular = exports.ShiftsDay20Filled = exports.ShiftsDay20Regular = exports.ShiftsDayRegular = exports.ShiftsDayFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShiftsDayFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsDayFilled", "", 2, undefined));
exports.ShiftsDayRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsDayRegular", "", 2, undefined));
exports.ShiftsDay20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsDay20Regular", "", 1, 20));
exports.ShiftsDay20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsDay20Filled", "", 0, 20));
exports.ShiftsDay24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsDay24Regular", "", 1, 24));
exports.ShiftsDay24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsDay24Filled", "", 0, 24));
