"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shifts32Filled = exports.Shifts32Regular = exports.Shifts28Filled = exports.Shifts28Regular = exports.Shifts24Filled = exports.Shifts24Regular = exports.Shifts20Filled = exports.Shifts20Regular = exports.Shifts16Filled = exports.Shifts16Regular = exports.ShiftsRegular = exports.ShiftsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShiftsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsFilled", "", 2, undefined));
exports.ShiftsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsRegular", "", 2, undefined));
exports.Shifts16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts16Regular", "", 1, 16));
exports.Shifts16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts16Filled", "", 0, 16));
exports.Shifts20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts20Regular", "", 1, 20));
exports.Shifts20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts20Filled", "", 0, 20));
exports.Shifts24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts24Regular", "", 1, 24));
exports.Shifts24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts24Filled", "", 0, 24));
exports.Shifts28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts28Regular", "", 1, 28));
exports.Shifts28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts28Filled", "", 0, 28));
exports.Shifts32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts32Regular", "", 1, 32));
exports.Shifts32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shifts32Filled", "", 0, 32));
