"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShiftsTeam24Filled = exports.ShiftsTeam24Regular = exports.ShiftsTeam20Filled = exports.ShiftsTeam20Regular = exports.ShiftsTeamRegular = exports.ShiftsTeamFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShiftsTeamFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsTeamFilled", "", 2, undefined));
exports.ShiftsTeamRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsTeamRegular", "", 2, undefined));
exports.ShiftsTeam20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsTeam20Regular", "", 1, 20));
exports.ShiftsTeam20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsTeam20Filled", "", 0, 20));
exports.ShiftsTeam24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsTeam24Regular", "", 1, 24));
exports.ShiftsTeam24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsTeam24Filled", "", 0, 24));
