"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShiftsAdd24Filled = exports.ShiftsAdd24Regular = exports.ShiftsAdd20Filled = exports.ShiftsAdd20Regular = exports.ShiftsAddRegular = exports.ShiftsAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShiftsAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsAddFilled", "", 2, undefined));
exports.ShiftsAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsAddRegular", "", 2, undefined));
exports.ShiftsAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsAdd20Regular", "", 1, 20));
exports.ShiftsAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsAdd20Filled", "", 0, 20));
exports.ShiftsAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsAdd24Regular", "", 1, 24));
exports.ShiftsAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShiftsAdd24Filled", "", 0, 24));
