"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShoppingBagAdd24Filled = exports.ShoppingBagAdd24Regular = exports.ShoppingBagAdd20Filled = exports.ShoppingBagAdd20Regular = exports.ShoppingBagAdd16Filled = exports.ShoppingBagAdd16Regular = exports.ShoppingBagAddRegular = exports.ShoppingBagAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShoppingBagAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAddFilled", "", 2, undefined));
exports.ShoppingBagAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAddRegular", "", 2, undefined));
exports.ShoppingBagAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAdd16Regular", "󰖕", 1, 16));
exports.ShoppingBagAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAdd16Filled", "󰘎", 0, 16));
exports.ShoppingBagAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAdd20Regular", "󰓸", 1, 20));
exports.ShoppingBagAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAdd20Filled", "󰕱", 0, 20));
exports.ShoppingBagAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAdd24Regular", "󰓹", 1, 24));
exports.ShoppingBagAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagAdd24Filled", "󰕲", 0, 24));
