"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShoppingBag48Filled = exports.ShoppingBag48Regular = exports.ShoppingBag32Filled = exports.ShoppingBag32Regular = exports.ShoppingBag28Filled = exports.ShoppingBag28Regular = exports.ShoppingBag24Filled = exports.ShoppingBag24Regular = exports.ShoppingBag20Filled = exports.ShoppingBag20Regular = exports.ShoppingBag16Filled = exports.ShoppingBag16Regular = exports.ShoppingBagRegular = exports.ShoppingBagFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShoppingBagFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagFilled", "", 2, undefined));
exports.ShoppingBagRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBagRegular", "", 2, undefined));
exports.ShoppingBag16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag16Regular", "", 1, 16));
exports.ShoppingBag16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag16Filled", "", 0, 16));
exports.ShoppingBag20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag20Regular", "", 1, 20));
exports.ShoppingBag20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag20Filled", "", 0, 20));
exports.ShoppingBag24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag24Regular", "", 1, 24));
exports.ShoppingBag24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag24Filled", "", 0, 24));
exports.ShoppingBag28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag28Regular", "󰚞", 1, 28));
exports.ShoppingBag28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag28Filled", "󰜙", 0, 28));
exports.ShoppingBag32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag32Regular", "󰚟", 1, 32));
exports.ShoppingBag32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag32Filled", "󰜚", 0, 32));
exports.ShoppingBag48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag48Regular", "󰚠", 1, 48));
exports.ShoppingBag48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShoppingBag48Filled", "󰜛", 0, 48));
