"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shortpick24Filled = exports.Shortpick24Regular = exports.Shortpick20Filled = exports.Shortpick20Regular = exports.ShortpickRegular = exports.ShortpickFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShortpickFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShortpickFilled", "", 2, undefined));
exports.ShortpickRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShortpickRegular", "", 2, undefined));
exports.Shortpick20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shortpick20Regular", "", 1, 20));
exports.Shortpick20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shortpick20Filled", "", 0, 20));
exports.Shortpick24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shortpick24Regular", "", 1, 24));
exports.Shortpick24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Shortpick24Filled", "", 0, 24));
