"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Showerhead32Filled = exports.Showerhead32Regular = exports.Showerhead24Filled = exports.Showerhead24Regular = exports.Showerhead20Filled = exports.Showerhead20Regular = exports.ShowerheadRegular = exports.ShowerheadFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ShowerheadFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShowerheadFilled", "", 2, undefined));
exports.ShowerheadRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ShowerheadRegular", "", 2, undefined));
exports.Showerhead20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Showerhead20Regular", "", 1, 20));
exports.Showerhead20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Showerhead20Filled", "", 0, 20));
exports.Showerhead24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Showerhead24Regular", "", 1, 24));
exports.Showerhead24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Showerhead24Filled", "", 0, 24));
exports.Showerhead32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Showerhead32Regular", "", 1, 32));
exports.Showerhead32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Showerhead32Filled", "", 0, 32));
