"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Signature32Light = exports.Signature32Filled = exports.Signature32Regular = exports.Signature28Filled = exports.Signature28Regular = exports.Signature24Filled = exports.Signature24Regular = exports.Signature20Filled = exports.Signature20Regular = exports.Signature16Filled = exports.Signature16Regular = exports.SignatureRegular = exports.SignatureFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SignatureFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SignatureFilled", "", 2, undefined));
exports.SignatureRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SignatureRegular", "", 2, undefined));
exports.Signature16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature16Regular", "", 1, 16));
exports.Signature16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature16Filled", "", 0, 16));
exports.Signature20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature20Regular", "", 1, 20));
exports.Signature20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature20Filled", "", 0, 20));
exports.Signature24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature24Regular", "", 1, 24));
exports.Signature24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature24Filled", "", 0, 24));
exports.Signature28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature28Regular", "", 1, 28));
exports.Signature28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature28Filled", "", 0, 28));
exports.Signature32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature32Regular", "󰈽", 1, 32));
exports.Signature32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature32Filled", "󰉐", 0, 32));
exports.Signature32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Signature32Light", "", 3, 32));
