"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SlideAdd48Filled = exports.SlideAdd48Regular = exports.SlideAdd32Filled = exports.SlideAdd32Regular = exports.SlideAdd28Filled = exports.SlideAdd28Regular = exports.SlideAdd24Filled = exports.SlideAdd24Regular = exports.SlideAdd20Filled = exports.SlideAdd20Regular = exports.SlideAdd16Filled = exports.SlideAdd16Regular = exports.SlideAddRegular = exports.SlideAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SlideAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAddFilled", "", 2, undefined));
exports.SlideAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAddRegular", "", 2, undefined));
exports.SlideAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd16Regular", "", 1, 16));
exports.SlideAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd16Filled", "", 0, 16));
exports.SlideAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd20Regular", "", 1, 20));
exports.SlideAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd20Filled", "", 0, 20));
exports.SlideAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd24Regular", "", 1, 24));
exports.SlideAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd24Filled", "", 0, 24));
exports.SlideAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd28Regular", "", 1, 28));
exports.SlideAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd28Filled", "", 0, 28));
exports.SlideAdd32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd32Regular", "", 1, 32));
exports.SlideAdd32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd32Filled", "", 0, 32));
exports.SlideAdd48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd48Regular", "", 1, 48));
exports.SlideAdd48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideAdd48Filled", "", 0, 48));
