"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SlideSearch32Filled = exports.SlideSearch32Regular = exports.SlideSearch28Filled = exports.SlideSearch28Regular = exports.SlideSearch24Filled = exports.SlideSearch24Regular = exports.SlideSearch20Filled = exports.SlideSearch20Regular = exports.SlideSearch16Filled = exports.SlideSearch16Regular = exports.SlideSearchRegular = exports.SlideSearchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SlideSearchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearchFilled", "", 2, undefined));
exports.SlideSearchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearchRegular", "", 2, undefined));
exports.SlideSearch16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch16Regular", "󰐖", 1, 16));
exports.SlideSearch16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch16Filled", "󰐩", 0, 16));
exports.SlideSearch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch20Regular", "", 1, 20));
exports.SlideSearch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch20Filled", "", 0, 20));
exports.SlideSearch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch24Regular", "", 1, 24));
exports.SlideSearch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch24Filled", "", 0, 24));
exports.SlideSearch28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch28Regular", "", 1, 28));
exports.SlideSearch28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch28Filled", "", 0, 28));
exports.SlideSearch32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch32Regular", "󰐗", 1, 32));
exports.SlideSearch32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideSearch32Filled", "󰐪", 0, 32));
