"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SlideEraser24Filled = exports.SlideEraser24Regular = exports.SlideEraser20Filled = exports.SlideEraser20Regular = exports.SlideEraser16Filled = exports.SlideEraser16Regular = exports.SlideEraserRegular = exports.SlideEraserFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SlideEraserFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraserFilled", "", 2, undefined));
exports.SlideEraserRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraserRegular", "", 2, undefined));
exports.SlideEraser16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraser16Regular", "", 1, 16));
exports.SlideEraser16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraser16Filled", "", 0, 16));
exports.SlideEraser20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraser20Regular", "", 1, 20));
exports.SlideEraser20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraser20Filled", "", 0, 20));
exports.SlideEraser24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraser24Regular", "", 1, 24));
exports.SlideEraser24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideEraser24Filled", "", 0, 24));
