"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SlideGrid24Filled = exports.SlideGrid24Regular = exports.SlideGrid20Filled = exports.SlideGrid20Regular = exports.SlideGridRegular = exports.SlideGridFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SlideGridFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideGridFilled", "", 2, undefined));
exports.SlideGridRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideGridRegular", "", 2, undefined));
exports.SlideGrid20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideGrid20Regular", "", 1, 20));
exports.SlideGrid20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideGrid20Filled", "", 0, 20));
exports.SlideGrid24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideGrid24Regular", "", 1, 24));
exports.SlideGrid24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SlideGrid24Filled", "", 0, 24));
