"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Smartwatch24Filled = exports.Smartwatch24Regular = exports.Smartwatch20Filled = exports.Smartwatch20Regular = exports.SmartwatchRegular = exports.SmartwatchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SmartwatchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SmartwatchFilled", "", 2, undefined));
exports.SmartwatchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SmartwatchRegular", "", 2, undefined));
exports.Smartwatch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Smartwatch20Regular", "", 1, 20));
exports.Smartwatch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Smartwatch20Filled", "", 0, 20));
exports.Smartwatch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Smartwatch24Regular", "", 1, 24));
exports.Smartwatch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Smartwatch24Filled", "", 0, 24));
