"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SoundSource28Filled = exports.SoundSource28Regular = exports.SoundSource24Filled = exports.SoundSource24Regular = exports.SoundSource20Filled = exports.SoundSource20Regular = exports.SoundSourceRegular = exports.SoundSourceFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SoundSourceFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSourceFilled", "", 2, undefined));
exports.SoundSourceRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSourceRegular", "", 2, undefined));
exports.SoundSource20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSource20Regular", "", 1, 20));
exports.SoundSource20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSource20Filled", "", 0, 20));
exports.SoundSource24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSource24Regular", "", 1, 24));
exports.SoundSource24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSource24Filled", "", 0, 24));
exports.SoundSource28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSource28Regular", "", 1, 28));
exports.SoundSource28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SoundSource28Filled", "", 0, 28));
