"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Space3D48Filled = exports.Space3D48Regular = exports.Space3D32Filled = exports.Space3D32Regular = exports.Space3D28Filled = exports.Space3D28Regular = exports.Space3D24Filled = exports.Space3D24Regular = exports.Space3D20Filled = exports.Space3D20Regular = exports.Space3D16Filled = exports.Space3D16Regular = exports.Space3DRegular = exports.Space3DFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.Space3DFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3DFilled", "", 2, undefined));
exports.Space3DRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3DRegular", "", 2, undefined));
exports.Space3D16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D16Regular", "󰂠", 1, 16));
exports.Space3D16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D16Filled", "󰂟", 0, 16));
exports.Space3D20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D20Regular", "󰂡", 1, 20));
exports.Space3D20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D20Filled", "󰂠", 0, 20));
exports.Space3D24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D24Regular", "󰂢", 1, 24));
exports.Space3D24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D24Filled", "󰂡", 0, 24));
exports.Space3D28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D28Regular", "󰂣", 1, 28));
exports.Space3D28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D28Filled", "󰂢", 0, 28));
exports.Space3D32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D32Regular", "󰂤", 1, 32));
exports.Space3D32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D32Filled", "󰂣", 0, 32));
exports.Space3D48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D48Regular", "󰂥", 1, 48));
exports.Space3D48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Space3D48Filled", "󰂤", 0, 48));
