"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Spacebar24Filled = exports.Spacebar24Regular = exports.Spacebar20Filled = exports.Spacebar20Regular = exports.SpacebarRegular = exports.SpacebarFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SpacebarFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SpacebarFilled", "", 2, undefined));
exports.SpacebarRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SpacebarRegular", "", 2, undefined));
exports.Spacebar20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Spacebar20Regular", "", 1, 20));
exports.Spacebar20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Spacebar20Filled", "", 0, 20));
exports.Spacebar24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Spacebar24Regular", "", 1, 24));
exports.Spacebar24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Spacebar24Filled", "", 0, 24));
