"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SparkleAction24Filled = exports.SparkleAction24Regular = exports.SparkleAction20Filled = exports.SparkleAction20Regular = exports.SparkleAction16Filled = exports.SparkleAction16Regular = exports.SparkleActionRegular = exports.SparkleActionFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SparkleActionFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleActionFilled", "", 2, undefined));
exports.SparkleActionRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleActionRegular", "", 2, undefined));
exports.SparkleAction16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleAction16Regular", "󰦡", 1, 16));
exports.SparkleAction16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleAction16Filled", "󰨞", 0, 16));
exports.SparkleAction20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleAction20Regular", "󰦌", 1, 20));
exports.SparkleAction20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleAction20Filled", "󰨉", 0, 20));
exports.SparkleAction24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleAction24Regular", "󰧹", 1, 24));
exports.SparkleAction24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SparkleAction24Filled", "󰩶", 0, 24));
