"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Sport24Filled = exports.Sport24Regular = exports.Sport20Filled = exports.Sport20Regular = exports.Sport16Filled = exports.Sport16Regular = exports.SportRegular = exports.SportFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SportFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportFilled", "", 2, undefined));
exports.SportRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportRegular", "", 2, undefined));
exports.Sport16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sport16Regular", "", 1, 16));
exports.Sport16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sport16Filled", "", 0, 16));
exports.Sport20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sport20Regular", "", 1, 20));
exports.Sport20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sport20Filled", "", 0, 20));
exports.Sport24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sport24Regular", "", 1, 24));
exports.Sport24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sport24Filled", "", 0, 24));
