"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SportHockey24Filled = exports.SportHockey24Regular = exports.SportHockey20Filled = exports.SportHockey20Regular = exports.SportHockeyRegular = exports.SportHockeyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SportHockeyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportHockeyFilled", "", 2, undefined));
exports.SportHockeyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportHockeyRegular", "", 2, undefined));
exports.SportHockey20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportHockey20Regular", "", 1, 20));
exports.SportHockey20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportHockey20Filled", "", 0, 20));
exports.SportHockey24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportHockey24Regular", "", 1, 24));
exports.SportHockey24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SportHockey24Filled", "", 0, 24));
