"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SquareDismiss20Filled = exports.SquareDismiss20Regular = exports.SquareDismiss16Filled = exports.SquareDismiss16Regular = exports.SquareDismissRegular = exports.SquareDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SquareDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareDismissFilled", "", 2, undefined));
exports.SquareDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareDismissRegular", "", 2, undefined));
exports.SquareDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareDismiss16Regular", "", 1, 16));
exports.SquareDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareDismiss16Filled", "", 0, 16));
exports.SquareDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareDismiss20Regular", "", 1, 20));
exports.SquareDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareDismiss20Filled", "", 0, 20));
