"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SquareShadow24Filled = exports.SquareShadow24Regular = exports.SquareShadow20Filled = exports.SquareShadow20Regular = exports.SquareShadow16Filled = exports.SquareShadow16Regular = exports.SquareShadow12Filled = exports.SquareShadow12Regular = exports.SquareShadowRegular = exports.SquareShadowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SquareShadowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadowFilled", "", 2, undefined));
exports.SquareShadowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadowRegular", "", 2, undefined));
exports.SquareShadow12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow12Regular", "", 1, 12));
exports.SquareShadow12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow12Filled", "", 0, 12));
exports.SquareShadow16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow16Regular", "󰪈", 1, 16));
exports.SquareShadow16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow16Filled", "󰬄", 0, 16));
exports.SquareShadow20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow20Regular", "", 1, 20));
exports.SquareShadow20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow20Filled", "", 0, 20));
exports.SquareShadow24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow24Regular", "󰪉", 1, 24));
exports.SquareShadow24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareShadow24Filled", "󰬅", 0, 24));
