"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Square48Filled = exports.Square48Regular = exports.Square32Filled = exports.Square32Regular = exports.Square28Filled = exports.Square28Regular = exports.Square24Filled = exports.Square24Regular = exports.Square20Filled = exports.Square20Regular = exports.Square16Filled = exports.Square16Regular = exports.Square12Filled = exports.Square12Regular = exports.SquareRegular = exports.SquareFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SquareFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareFilled", "", 2, undefined));
exports.SquareRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareRegular", "", 2, undefined));
exports.Square12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square12Regular", "", 1, 12));
exports.Square12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square12Filled", "", 0, 12));
exports.Square16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square16Regular", "", 1, 16));
exports.Square16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square16Filled", "", 0, 16));
exports.Square20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square20Regular", "", 1, 20));
exports.Square20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square20Filled", "", 0, 20));
exports.Square24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square24Regular", "", 1, 24));
exports.Square24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square24Filled", "", 0, 24));
exports.Square28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square28Regular", "", 1, 28));
exports.Square28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square28Filled", "", 0, 28));
exports.Square32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square32Regular", "", 1, 32));
exports.Square32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square32Filled", "", 0, 32));
exports.Square48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square48Regular", "", 1, 48));
exports.Square48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Square48Filled", "", 0, 48));
