"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SquareHint48Filled = exports.SquareHint48Regular = exports.SquareHint32Filled = exports.SquareHint32Regular = exports.SquareHint28Filled = exports.SquareHint28Regular = exports.SquareHint24Filled = exports.SquareHint24Regular = exports.SquareHint20Filled = exports.SquareHint20Regular = exports.SquareHint16Filled = exports.SquareHint16Regular = exports.SquareHintRegular = exports.SquareHintFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SquareHintFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHintFilled", "", 2, undefined));
exports.SquareHintRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHintRegular", "", 2, undefined));
exports.SquareHint16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint16Regular", "", 1, 16));
exports.SquareHint16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint16Filled", "", 0, 16));
exports.SquareHint20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint20Regular", "", 1, 20));
exports.SquareHint20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint20Filled", "", 0, 20));
exports.SquareHint24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint24Regular", "", 1, 24));
exports.SquareHint24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint24Filled", "", 0, 24));
exports.SquareHint28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint28Regular", "", 1, 28));
exports.SquareHint28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint28Filled", "", 0, 28));
exports.SquareHint32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint32Regular", "", 1, 32));
exports.SquareHint32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint32Filled", "", 0, 32));
exports.SquareHint48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint48Regular", "", 1, 48));
exports.SquareHint48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SquareHint48Filled", "", 0, 48));
