"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StackOff48Filled = exports.StackOff48Regular = exports.StackOff32Filled = exports.StackOff32Regular = exports.StackOff28Filled = exports.StackOff28Regular = exports.StackOff24Filled = exports.StackOff24Regular = exports.StackOff20Filled = exports.StackOff20Regular = exports.StackOff16Filled = exports.StackOff16Regular = exports.StackOffRegular = exports.StackOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StackOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOffFilled", "", 2, undefined));
exports.StackOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOffRegular", "", 2, undefined));
exports.StackOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff16Regular", "󰝯", 1, 16));
exports.StackOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff16Filled", "󰟬", 0, 16));
exports.StackOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff20Regular", "󰝰", 1, 20));
exports.StackOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff20Filled", "󰟭", 0, 20));
exports.StackOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff24Regular", "󰝱", 1, 24));
exports.StackOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff24Filled", "󰟮", 0, 24));
exports.StackOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff28Regular", "󰝲", 1, 28));
exports.StackOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff28Filled", "󰟯", 0, 28));
exports.StackOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff32Regular", "󰝳", 1, 32));
exports.StackOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff32Filled", "󰟰", 0, 32));
exports.StackOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff48Regular", "󰝴", 1, 48));
exports.StackOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackOff48Filled", "󰟱", 0, 48));
