"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Stack48Filled = exports.Stack48Regular = exports.Stack32Filled = exports.Stack32Regular = exports.Stack28Filled = exports.Stack28Regular = exports.Stack24Filled = exports.Stack24Regular = exports.Stack20Filled = exports.Stack20Regular = exports.Stack16Filled = exports.Stack16Regular = exports.StackRegular = exports.StackFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StackFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackFilled", "", 2, undefined));
exports.StackRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StackRegular", "", 2, undefined));
exports.Stack16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack16Regular", "", 1, 16));
exports.Stack16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack16Filled", "", 0, 16));
exports.Stack20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack20Regular", "", 1, 20));
exports.Stack20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack20Filled", "", 0, 20));
exports.Stack24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack24Regular", "", 1, 24));
exports.Stack24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack24Filled", "", 0, 24));
exports.Stack28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack28Regular", "󰝭", 1, 28));
exports.Stack28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack28Filled", "󰟪", 0, 28));
exports.Stack32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack32Regular", "", 1, 32));
exports.Stack32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack32Filled", "", 0, 32));
exports.Stack48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack48Regular", "󰝮", 1, 48));
exports.Stack48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stack48Filled", "󰟫", 0, 48));
