"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Star48Filled = exports.Star48Regular = exports.Star32Filled = exports.Star32Regular = exports.Star28Filled = exports.Star28Regular = exports.Star24Filled = exports.Star24Regular = exports.Star20Filled = exports.Star20Regular = exports.Star16Filled = exports.Star16Regular = exports.Star12Filled = exports.Star12Regular = exports.StarRegular = exports.StarFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StarFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarFilled", "", 2, undefined));
exports.StarRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarRegular", "", 2, undefined));
exports.Star12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star12Regular", "", 1, 12));
exports.Star12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star12Filled", "", 0, 12));
exports.Star16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star16Regular", "", 1, 16));
exports.Star16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star16Filled", "", 0, 16));
exports.Star20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star20Regular", "", 1, 20));
exports.Star20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star20Filled", "", 0, 20));
exports.Star24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star24Regular", "", 1, 24));
exports.Star24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star24Filled", "", 0, 24));
exports.Star28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star28Regular", "", 1, 28));
exports.Star28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star28Filled", "", 0, 28));
exports.Star32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star32Regular", "󰑞", 1, 32));
exports.Star32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star32Filled", "󰑱", 0, 32));
exports.Star48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star48Regular", "", 1, 48));
exports.Star48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Star48Filled", "", 0, 48));
