"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StarHalf28Filled = exports.StarHalf28Regular = exports.StarHalf24Filled = exports.StarHalf24Regular = exports.StarHalf20Filled = exports.StarHalf20Regular = exports.StarHalf16Filled = exports.StarHalf16Regular = exports.StarHalf12Filled = exports.StarHalf12Regular = exports.StarHalfRegular = exports.StarHalfFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StarHalfFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalfFilled", "", 2, undefined));
exports.StarHalfRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalfRegular", "", 2, undefined));
exports.StarHalf12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf12Regular", "", 1, 12));
exports.StarHalf12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf12Filled", "", 0, 12));
exports.StarHalf16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf16Regular", "", 1, 16));
exports.StarHalf16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf16Filled", "", 0, 16));
exports.StarHalf20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf20Regular", "", 1, 20));
exports.StarHalf20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf20Filled", "", 0, 20));
exports.StarHalf24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf24Regular", "", 1, 24));
exports.StarHalf24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf24Filled", "", 0, 24));
exports.StarHalf28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf28Regular", "", 1, 28));
exports.StarHalf28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarHalf28Filled", "", 0, 28));
