"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StarOff28Filled = exports.StarOff28Regular = exports.StarOff24Filled = exports.StarOff24Regular = exports.StarOff20Filled = exports.StarOff20Regular = exports.StarOff16Filled = exports.StarOff16Regular = exports.StarOff12Filled = exports.StarOff12Regular = exports.StarOffRegular = exports.StarOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StarOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOffFilled", "", 2, undefined));
exports.StarOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOffRegular", "", 2, undefined));
exports.StarOff12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff12Regular", "", 1, 12));
exports.StarOff12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff12Filled", "", 0, 12));
exports.StarOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff16Regular", "", 1, 16));
exports.StarOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff16Filled", "", 0, 16));
exports.StarOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff20Regular", "", 1, 20));
exports.StarOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff20Filled", "", 0, 20));
exports.StarOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff24Regular", "", 1, 24));
exports.StarOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff24Filled", "", 0, 24));
exports.StarOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff28Regular", "", 1, 28));
exports.StarOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StarOff28Filled", "", 0, 28));
