"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Status48Filled = exports.Status48Regular = exports.Status32Filled = exports.Status32Regular = exports.Status28Filled = exports.Status28Regular = exports.Status24Filled = exports.Status24Regular = exports.Status20Filled = exports.Status20Regular = exports.Status16Filled = exports.Status16Regular = exports.Status12Filled = exports.Status12Regular = exports.StatusRegular = exports.StatusFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StatusFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StatusFilled", "", 2, undefined));
exports.StatusRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StatusRegular", "", 2, undefined));
exports.Status12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status12Regular", "", 1, 12));
exports.Status12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status12Filled", "", 0, 12));
exports.Status16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status16Regular", "", 1, 16));
exports.Status16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status16Filled", "", 0, 16));
exports.Status20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status20Regular", "", 1, 20));
exports.Status20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status20Filled", "", 0, 20));
exports.Status24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status24Regular", "", 1, 24));
exports.Status24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status24Filled", "", 0, 24));
exports.Status28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status28Regular", "󰔝", 1, 28));
exports.Status28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status28Filled", "󰖖", 0, 28));
exports.Status32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status32Regular", "󰔞", 1, 32));
exports.Status32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status32Filled", "󰖗", 0, 32));
exports.Status48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status48Regular", "󰔟", 1, 48));
exports.Status48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Status48Filled", "󰖘", 0, 48));
