"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Sticker32Light = exports.Sticker32Filled = exports.Sticker32Regular = exports.Sticker28Filled = exports.Sticker28Regular = exports.Sticker24Filled = exports.Sticker24Regular = exports.Sticker20Filled = exports.Sticker20Regular = exports.Sticker16Filled = exports.Sticker16Regular = exports.Sticker12Filled = exports.Sticker12Regular = exports.StickerRegular = exports.StickerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StickerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerFilled", "", 2, undefined));
exports.StickerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerRegular", "", 2, undefined));
exports.Sticker12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker12Regular", "", 1, 12));
exports.Sticker12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker12Filled", "", 0, 12));
exports.Sticker16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker16Regular", "󰧩", 1, 16));
exports.Sticker16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker16Filled", "󰩦", 0, 16));
exports.Sticker20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker20Regular", "", 1, 20));
exports.Sticker20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker20Filled", "", 0, 20));
exports.Sticker24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker24Regular", "", 1, 24));
exports.Sticker24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker24Filled", "", 0, 24));
exports.Sticker28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker28Regular", "󰧪", 1, 28));
exports.Sticker28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker28Filled", "󰩧", 0, 28));
exports.Sticker32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker32Regular", "󰧫", 1, 32));
exports.Sticker32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker32Filled", "󰩨", 0, 32));
exports.Sticker32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Sticker32Light", "", 3, 32));
