"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StickerAdd24Filled = exports.StickerAdd24Regular = exports.StickerAdd20Filled = exports.StickerAdd20Regular = exports.StickerAddRegular = exports.StickerAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StickerAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerAddFilled", "", 2, undefined));
exports.StickerAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerAddRegular", "", 2, undefined));
exports.StickerAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerAdd20Regular", "", 1, 20));
exports.StickerAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerAdd20Filled", "", 0, 20));
exports.StickerAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerAdd24Regular", "", 1, 24));
exports.StickerAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StickerAdd24Filled", "", 0, 24));
