"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Storage48Filled = exports.Storage48Regular = exports.Storage32Filled = exports.Storage32Regular = exports.Storage28Filled = exports.Storage28Regular = exports.Storage24Filled = exports.Storage24Regular = exports.Storage20Filled = exports.Storage20Regular = exports.Storage16Filled = exports.Storage16Regular = exports.StorageRegular = exports.StorageFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StorageFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StorageFilled", "", 2, undefined));
exports.StorageRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StorageRegular", "", 2, undefined));
exports.Storage16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage16Regular", "󰕄", 1, 16));
exports.Storage16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage16Filled", "󰖽", 0, 16));
exports.Storage20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage20Regular", "", 1, 20));
exports.Storage20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage20Filled", "", 0, 20));
exports.Storage24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage24Regular", "", 1, 24));
exports.Storage24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage24Filled", "", 0, 24));
exports.Storage28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage28Regular", "󰕅", 1, 28));
exports.Storage28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage28Filled", "󰖾", 0, 28));
exports.Storage32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage32Regular", "󰕆", 1, 32));
exports.Storage32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage32Filled", "󰖿", 0, 32));
exports.Storage48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage48Regular", "󰕇", 1, 48));
exports.Storage48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Storage48Filled", "󰗀", 0, 48));
