"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Stove20Filled = exports.Stove20Regular = exports.Stove16Filled = exports.Stove16Regular = exports.StoveRegular = exports.StoveFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StoveFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StoveFilled", "", 2, undefined));
exports.StoveRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StoveRegular", "", 2, undefined));
exports.Stove16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stove16Regular", "󰬛", 1, 16));
exports.Stove16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stove16Filled", "󰮙", 0, 16));
exports.Stove20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stove20Regular", "󰬜", 1, 20));
exports.Stove20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stove20Filled", "󰮚", 0, 20));
