"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Stream48Filled = exports.Stream48Regular = exports.Stream32Filled = exports.Stream32Regular = exports.Stream24Filled = exports.Stream24Regular = exports.Stream20Filled = exports.Stream20Regular = exports.StreamRegular = exports.StreamFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.StreamFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StreamFilled", "", 2, undefined));
exports.StreamRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("StreamRegular", "", 2, undefined));
exports.Stream20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream20Regular", "", 1, 20));
exports.Stream20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream20Filled", "", 0, 20));
exports.Stream24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream24Regular", "", 1, 24));
exports.Stream24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream24Filled", "", 0, 24));
exports.Stream32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream32Regular", "󰅊", 1, 32));
exports.Stream32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream32Filled", "󰅉", 0, 32));
exports.Stream48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream48Regular", "󰉼", 1, 48));
exports.Stream48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Stream48Filled", "󰊏", 0, 48));
