"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubGrid24Filled = exports.SubGrid24Regular = exports.SubGrid20Filled = exports.SubGrid20Regular = exports.SubGridRegular = exports.SubGridFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SubGridFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubGridFilled", "", 2, undefined));
exports.SubGridRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubGridRegular", "", 2, undefined));
exports.SubGrid20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubGrid20Regular", "", 1, 20));
exports.SubGrid20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubGrid20Filled", "", 0, 20));
exports.SubGrid24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubGrid24Regular", "", 1, 24));
exports.SubGrid24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubGrid24Filled", "", 0, 24));
