"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubtractCircle48Filled = exports.SubtractCircle48Regular = exports.SubtractCircle32Filled = exports.SubtractCircle32Regular = exports.SubtractCircle28Filled = exports.SubtractCircle28Regular = exports.SubtractCircle24Filled = exports.SubtractCircle24Regular = exports.SubtractCircle20Filled = exports.SubtractCircle20Regular = exports.SubtractCircle16Filled = exports.SubtractCircle16Regular = exports.SubtractCircle12Filled = exports.SubtractCircle12Regular = exports.SubtractCircleRegular = exports.SubtractCircleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SubtractCircleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircleFilled", "", 2, undefined));
exports.SubtractCircleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircleRegular", "", 2, undefined));
exports.SubtractCircle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle12Regular", "", 1, 12));
exports.SubtractCircle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle12Filled", "", 0, 12));
exports.SubtractCircle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle16Regular", "", 1, 16));
exports.SubtractCircle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle16Filled", "", 0, 16));
exports.SubtractCircle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle20Regular", "", 1, 20));
exports.SubtractCircle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle20Filled", "", 0, 20));
exports.SubtractCircle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle24Regular", "", 1, 24));
exports.SubtractCircle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle24Filled", "", 0, 24));
exports.SubtractCircle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle28Regular", "", 1, 28));
exports.SubtractCircle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle28Filled", "", 0, 28));
exports.SubtractCircle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle32Regular", "", 1, 32));
exports.SubtractCircle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle32Filled", "", 0, 32));
exports.SubtractCircle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle48Regular", "󰏈", 1, 48));
exports.SubtractCircle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtractCircle48Filled", "󰏛", 0, 48));
