"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Subtitles24Filled = exports.Subtitles24Regular = exports.Subtitles20Filled = exports.Subtitles20Regular = exports.Subtitles16Filled = exports.Subtitles16Regular = exports.SubtitlesRegular = exports.SubtitlesFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SubtitlesFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtitlesFilled", "", 2, undefined));
exports.SubtitlesRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SubtitlesRegular", "", 2, undefined));
exports.Subtitles16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Subtitles16Regular", "", 1, 16));
exports.Subtitles16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Subtitles16Filled", "", 0, 16));
exports.Subtitles20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Subtitles20Regular", "", 1, 20));
exports.Subtitles20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Subtitles20Filled", "", 0, 20));
exports.Subtitles24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Subtitles24Regular", "", 1, 24));
exports.Subtitles24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Subtitles24Filled", "", 0, 24));
