"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SurfaceEarbuds24Filled = exports.SurfaceEarbuds24Regular = exports.SurfaceEarbuds20Filled = exports.SurfaceEarbuds20Regular = exports.SurfaceEarbudsRegular = exports.SurfaceEarbudsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SurfaceEarbudsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceEarbudsFilled", "", 2, undefined));
exports.SurfaceEarbudsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceEarbudsRegular", "", 2, undefined));
exports.SurfaceEarbuds20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceEarbuds20Regular", "", 1, 20));
exports.SurfaceEarbuds20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceEarbuds20Filled", "", 0, 20));
exports.SurfaceEarbuds24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceEarbuds24Regular", "", 1, 24));
exports.SurfaceEarbuds24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceEarbuds24Filled", "", 0, 24));
