"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SurfaceHub24Filled = exports.SurfaceHub24Regular = exports.SurfaceHub20Filled = exports.SurfaceHub20Regular = exports.SurfaceHubRegular = exports.SurfaceHubFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SurfaceHubFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceHubFilled", "", 2, undefined));
exports.SurfaceHubRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceHubRegular", "", 2, undefined));
exports.SurfaceHub20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceHub20Regular", "", 1, 20));
exports.SurfaceHub20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceHub20Filled", "", 0, 20));
exports.SurfaceHub24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceHub24Regular", "", 1, 24));
exports.SurfaceHub24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SurfaceHub24Filled", "", 0, 24));
