"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SwimmingPool48Filled = exports.SwimmingPool48Regular = exports.SwimmingPool32Filled = exports.SwimmingPool32Regular = exports.SwimmingPool24Filled = exports.SwimmingPool24Regular = exports.SwimmingPool20Filled = exports.SwimmingPool20Regular = exports.SwimmingPoolRegular = exports.SwimmingPoolFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SwimmingPoolFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPoolFilled", "", 2, undefined));
exports.SwimmingPoolRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPoolRegular", "", 2, undefined));
exports.SwimmingPool20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool20Regular", "", 1, 20));
exports.SwimmingPool20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool20Filled", "", 0, 20));
exports.SwimmingPool24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool24Regular", "", 1, 24));
exports.SwimmingPool24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool24Filled", "", 0, 24));
exports.SwimmingPool32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool32Regular", "", 1, 32));
exports.SwimmingPool32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool32Filled", "", 0, 32));
exports.SwimmingPool48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool48Regular", "", 1, 48));
exports.SwimmingPool48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SwimmingPool48Filled", "", 0, 48));
