"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Syringe24Filled = exports.Syringe24Regular = exports.Syringe20Filled = exports.Syringe20Regular = exports.SyringeRegular = exports.SyringeFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.SyringeFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SyringeFilled", "", 2, undefined));
exports.SyringeRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("SyringeRegular", "", 2, undefined));
exports.Syringe20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Syringe20Regular", "", 1, 20));
exports.Syringe20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Syringe20Filled", "", 0, 20));
exports.Syringe24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Syringe24Regular", "", 1, 24));
exports.Syringe24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Syringe24Filled", "", 0, 24));
