"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tab28Filled = exports.Tab28Regular = exports.Tab24Filled = exports.Tab24Regular = exports.Tab20Filled = exports.Tab20Regular = exports.Tab16Filled = exports.Tab16Regular = exports.TabRegular = exports.TabFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TabFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TabFilled", "", 2, undefined));
exports.TabRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TabRegular", "", 2, undefined));
exports.Tab16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab16Regular", "", 1, 16));
exports.Tab16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab16Filled", "", 0, 16));
exports.Tab20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab20Regular", "", 1, 20));
exports.Tab20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab20Filled", "", 0, 20));
exports.Tab24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab24Regular", "", 1, 24));
exports.Tab24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab24Filled", "", 0, 24));
exports.Tab28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab28Regular", "", 1, 28));
exports.Tab28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tab28Filled", "", 0, 28));
