"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableSparkle24Filled = exports.TableSparkle24Regular = exports.TableSparkle20Filled = exports.TableSparkle20Regular = exports.TableSparkleRegular = exports.TableSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TableSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSparkleFilled", "", 2, undefined));
exports.TableSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSparkleRegular", "", 2, undefined));
exports.TableSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSparkle20Regular", "󰗤", 1, 20));
exports.TableSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSparkle20Filled", "󰙠", 0, 20));
exports.TableSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSparkle24Regular", "󰗥", 1, 24));
exports.TableSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSparkle24Filled", "󰙡", 0, 24));
