"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableEdit28Filled = exports.TableEdit28Regular = exports.TableEdit24Filled = exports.TableEdit24Regular = exports.TableEdit20Filled = exports.TableEdit20Regular = exports.TableEdit16Filled = exports.TableEdit16Regular = exports.TableEditRegular = exports.TableEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TableEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEditFilled", "", 2, undefined));
exports.TableEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEditRegular", "", 2, undefined));
exports.TableEdit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit16Regular", "", 1, 16));
exports.TableEdit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit16Filled", "", 0, 16));
exports.TableEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit20Regular", "", 1, 20));
exports.TableEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit20Filled", "", 0, 20));
exports.TableEdit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit24Regular", "", 1, 24));
exports.TableEdit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit24Filled", "", 0, 24));
exports.TableEdit28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit28Regular", "", 1, 28));
exports.TableEdit28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableEdit28Filled", "", 0, 28));
