"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableAdd28Filled = exports.TableAdd28Regular = exports.TableAdd24Filled = exports.TableAdd24Regular = exports.TableAdd20Filled = exports.TableAdd20Regular = exports.TableAdd16Filled = exports.TableAdd16Regular = exports.TableAddRegular = exports.TableAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TableAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAddFilled", "", 2, undefined));
exports.TableAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAddRegular", "", 2, undefined));
exports.TableAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd16Regular", "", 1, 16));
exports.TableAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd16Filled", "", 0, 16));
exports.TableAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd20Regular", "", 1, 20));
exports.TableAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd20Filled", "", 0, 20));
exports.TableAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd24Regular", "", 1, 24));
exports.TableAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd24Filled", "", 0, 24));
exports.TableAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd28Regular", "", 1, 28));
exports.TableAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableAdd28Filled", "", 0, 28));
