"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableSwitch28Filled = exports.TableSwitch28Regular = exports.TableSwitch24Filled = exports.TableSwitch24Regular = exports.TableSwitch20Filled = exports.TableSwitch20Regular = exports.TableSwitch16Filled = exports.TableSwitch16Regular = exports.TableSwitchRegular = exports.TableSwitchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TableSwitchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitchFilled", "", 2, undefined));
exports.TableSwitchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitchRegular", "", 2, undefined));
exports.TableSwitch16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch16Regular", "", 1, 16));
exports.TableSwitch16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch16Filled", "", 0, 16));
exports.TableSwitch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch20Regular", "", 1, 20));
exports.TableSwitch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch20Filled", "", 0, 20));
exports.TableSwitch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch24Regular", "", 1, 24));
exports.TableSwitch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch24Filled", "", 0, 24));
exports.TableSwitch28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch28Regular", "", 1, 28));
exports.TableSwitch28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableSwitch28Filled", "", 0, 28));
