"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableLock48Filled = exports.TableLock48Regular = exports.TableLock32Filled = exports.TableLock32Regular = exports.TableLock28Filled = exports.TableLock28Regular = exports.TableLock24Filled = exports.TableLock24Regular = exports.TableLock20Filled = exports.TableLock20Regular = exports.TableLock16Filled = exports.TableLock16Regular = exports.TableLockRegular = exports.TableLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TableLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLockFilled", "", 2, undefined));
exports.TableLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLockRegular", "", 2, undefined));
exports.TableLock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock16Regular", "", 1, 16));
exports.TableLock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock16Filled", "", 0, 16));
exports.TableLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock20Regular", "", 1, 20));
exports.TableLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock20Filled", "", 0, 20));
exports.TableLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock24Regular", "", 1, 24));
exports.TableLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock24Filled", "", 0, 24));
exports.TableLock28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock28Regular", "", 1, 28));
exports.TableLock28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock28Filled", "", 0, 28));
exports.TableLock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock32Regular", "", 1, 32));
exports.TableLock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock32Filled", "", 0, 32));
exports.TableLock48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock48Regular", "", 1, 48));
exports.TableLock48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TableLock48Filled", "", 0, 48));
