"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tabs24Filled = exports.Tabs24Regular = exports.Tabs20Filled = exports.Tabs20Regular = exports.Tabs16Filled = exports.Tabs16Regular = exports.TabsRegular = exports.TabsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TabsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TabsFilled", "", 2, undefined));
exports.TabsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TabsRegular", "", 2, undefined));
exports.Tabs16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tabs16Regular", "", 1, 16));
exports.Tabs16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tabs16Filled", "", 0, 16));
exports.Tabs20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tabs20Regular", "", 1, 20));
exports.Tabs20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tabs20Filled", "", 0, 20));
exports.Tabs24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tabs24Regular", "", 1, 24));
exports.Tabs24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tabs24Filled", "", 0, 24));
