"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TagOff24Filled = exports.TagOff24Regular = exports.TagOff20Filled = exports.TagOff20Regular = exports.TagOff16Filled = exports.TagOff16Regular = exports.TagOffRegular = exports.TagOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TagOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOffFilled", "", 2, undefined));
exports.TagOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOffRegular", "", 2, undefined));
exports.TagOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOff16Regular", "󰗴", 1, 16));
exports.TagOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOff16Filled", "󰙰", 0, 16));
exports.TagOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOff20Regular", "", 1, 20));
exports.TagOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOff20Filled", "", 0, 20));
exports.TagOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOff24Regular", "", 1, 24));
exports.TagOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagOff24Filled", "", 0, 24));
