"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TagDismiss24Filled = exports.TagDismiss24Regular = exports.TagDismiss20Filled = exports.TagDismiss20Regular = exports.TagDismiss16Filled = exports.TagDismiss16Regular = exports.TagDismissRegular = exports.TagDismissFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TagDismissFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismissFilled", "", 2, undefined));
exports.TagDismissRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismissRegular", "", 2, undefined));
exports.TagDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismiss16Regular", "", 1, 16));
exports.TagDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismiss16Filled", "", 0, 16));
exports.TagDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismiss20Regular", "", 1, 20));
exports.TagDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismiss20Filled", "", 0, 20));
exports.TagDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismiss24Regular", "", 1, 24));
exports.TagDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagDismiss24Filled", "", 0, 24));
