"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TagAdd48Filled = exports.TagAdd48Regular = exports.TagAdd32Filled = exports.TagAdd32Regular = exports.TagAdd28Filled = exports.TagAdd28Regular = exports.TagAdd24Filled = exports.TagAdd24Regular = exports.TagAdd20Filled = exports.TagAdd20Regular = exports.TagAdd16Filled = exports.TagAdd16Regular = exports.TagAddRegular = exports.TagAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TagAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAddFilled", "", 2, undefined));
exports.TagAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAddRegular", "", 2, undefined));
exports.TagAdd16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd16Regular", "󰤫", 1, 16));
exports.TagAdd16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd16Filled", "󰦨", 0, 16));
exports.TagAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd20Regular", "󰤬", 1, 20));
exports.TagAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd20Filled", "󰦩", 0, 20));
exports.TagAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd24Regular", "󰤭", 1, 24));
exports.TagAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd24Filled", "󰦪", 0, 24));
exports.TagAdd28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd28Regular", "󰤮", 1, 28));
exports.TagAdd28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd28Filled", "󰦫", 0, 28));
exports.TagAdd32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd32Regular", "󰤯", 1, 32));
exports.TagAdd32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd32Filled", "󰦬", 0, 32));
exports.TagAdd48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd48Regular", "󰤰", 1, 48));
exports.TagAdd48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagAdd48Filled", "󰦭", 0, 48));
