"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TagLock32Filled = exports.TagLock32Regular = exports.TagLock24Filled = exports.TagLock24Regular = exports.TagLock20Filled = exports.TagLock20Regular = exports.TagLock16Filled = exports.TagLock16Regular = exports.TagLockRegular = exports.TagLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TagLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLockFilled", "", 2, undefined));
exports.TagLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLockRegular", "", 2, undefined));
exports.TagLock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock16Regular", "", 1, 16));
exports.TagLock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock16Filled", "", 0, 16));
exports.TagLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock20Regular", "", 1, 20));
exports.TagLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock20Filled", "", 0, 20));
exports.TagLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock24Regular", "", 1, 24));
exports.TagLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock24Filled", "", 0, 24));
exports.TagLock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock32Regular", "", 1, 32));
exports.TagLock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TagLock32Filled", "", 0, 32));
