"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TapDouble48Filled = exports.TapDouble48Regular = exports.TapDouble32Filled = exports.TapDouble32Regular = exports.TapDouble24Filled = exports.TapDouble24Regular = exports.TapDouble20Filled = exports.TapDouble20Regular = exports.TapDoubleRegular = exports.TapDoubleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TapDoubleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDoubleFilled", "", 2, undefined));
exports.TapDoubleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDoubleRegular", "", 2, undefined));
exports.TapDouble20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble20Regular", "", 1, 20));
exports.TapDouble20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble20Filled", "", 0, 20));
exports.TapDouble24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble24Regular", "", 1, 24));
exports.TapDouble24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble24Filled", "", 0, 24));
exports.TapDouble32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble32Regular", "", 1, 32));
exports.TapDouble32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble32Filled", "", 0, 32));
exports.TapDouble48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble48Regular", "", 1, 48));
exports.TapDouble48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TapDouble48Filled", "", 0, 48));
