"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TargetAdd24Filled = exports.TargetAdd24Regular = exports.TargetAdd20Filled = exports.TargetAdd20Regular = exports.TargetAddRegular = exports.TargetAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TargetAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetAddFilled", "", 2, undefined));
exports.TargetAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetAddRegular", "", 2, undefined));
exports.TargetAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetAdd20Regular", "󰍪", 1, 20));
exports.TargetAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetAdd20Filled", "󰍽", 0, 20));
exports.TargetAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetAdd24Regular", "󰍫", 1, 24));
exports.TargetAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetAdd24Filled", "󰍾", 0, 24));
