"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TargetSparkle24Filled = exports.TargetSparkle24Regular = exports.TargetSparkle20Filled = exports.TargetSparkle20Regular = exports.TargetSparkle16Filled = exports.TargetSparkle16Regular = exports.TargetSparkleRegular = exports.TargetSparkleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TargetSparkleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkleFilled", "", 2, undefined));
exports.TargetSparkleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkleRegular", "", 2, undefined));
exports.TargetSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkle16Regular", "󰧬", 1, 16));
exports.TargetSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkle16Filled", "󰩩", 0, 16));
exports.TargetSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkle20Regular", "󰧭", 1, 20));
exports.TargetSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkle20Filled", "󰩪", 0, 20));
exports.TargetSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkle24Regular", "󰧮", 1, 24));
exports.TargetSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetSparkle24Filled", "󰩫", 0, 24));
