"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TargetArrow24Filled = exports.TargetArrow24Regular = exports.TargetArrow20Filled = exports.TargetArrow20Regular = exports.TargetArrow16Filled = exports.TargetArrow16Regular = exports.TargetArrowRegular = exports.TargetArrowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TargetArrowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrowFilled", "", 2, undefined));
exports.TargetArrowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrowRegular", "", 2, undefined));
exports.TargetArrow16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrow16Regular", "", 1, 16));
exports.TargetArrow16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrow16Filled", "", 0, 16));
exports.TargetArrow20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrow20Regular", "", 1, 20));
exports.TargetArrow20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrow20Filled", "", 0, 20));
exports.TargetArrow24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrow24Regular", "", 1, 24));
exports.TargetArrow24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TargetArrow24Filled", "", 0, 24));
