"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TasksApp28Filled = exports.TasksApp28Regular = exports.TasksApp24Filled = exports.TasksApp24Regular = exports.TasksApp20Filled = exports.TasksApp20Regular = exports.TasksAppRegular = exports.TasksAppFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TasksAppFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksAppFilled", "", 2, undefined));
exports.TasksAppRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksAppRegular", "", 2, undefined));
exports.TasksApp20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksApp20Regular", "", 1, 20));
exports.TasksApp20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksApp20Filled", "", 0, 20));
exports.TasksApp24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksApp24Regular", "", 1, 24));
exports.TasksApp24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksApp24Filled", "", 0, 24));
exports.TasksApp28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksApp28Regular", "", 1, 28));
exports.TasksApp28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TasksApp28Filled", "", 0, 28));
