"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Teaching48Filled = exports.Teaching48Regular = exports.Teaching32Filled = exports.Teaching32Regular = exports.Teaching28Filled = exports.Teaching28Regular = exports.Teaching24Filled = exports.Teaching24Regular = exports.Teaching20Filled = exports.Teaching20Regular = exports.Teaching16Filled = exports.Teaching16Regular = exports.TeachingRegular = exports.TeachingFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TeachingFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TeachingFilled", "", 2, undefined));
exports.TeachingRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TeachingRegular", "", 2, undefined));
exports.Teaching16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching16Regular", "󰚥", 1, 16));
exports.Teaching16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching16Filled", "󰜠", 0, 16));
exports.Teaching20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching20Regular", "󰙳", 1, 20));
exports.Teaching20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching20Filled", "󰛳", 0, 20));
exports.Teaching24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching24Regular", "󰚦", 1, 24));
exports.Teaching24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching24Filled", "󰜡", 0, 24));
exports.Teaching28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching28Regular", "󰚧", 1, 28));
exports.Teaching28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching28Filled", "󰜢", 0, 28));
exports.Teaching32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching32Regular", "󰚨", 1, 32));
exports.Teaching32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching32Filled", "󰜣", 0, 32));
exports.Teaching48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching48Regular", "󰚩", 1, 48));
exports.Teaching48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Teaching48Filled", "󰜤", 0, 48));
