"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Temperature48Filled = exports.Temperature48Regular = exports.Temperature32Filled = exports.Temperature32Regular = exports.Temperature24Filled = exports.Temperature24Regular = exports.Temperature20Filled = exports.Temperature20Regular = exports.Temperature16Filled = exports.Temperature16Regular = exports.TemperatureRegular = exports.TemperatureFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TemperatureFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TemperatureFilled", "", 2, undefined));
exports.TemperatureRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TemperatureRegular", "", 2, undefined));
exports.Temperature16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature16Regular", "", 1, 16));
exports.Temperature16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature16Filled", "", 0, 16));
exports.Temperature20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature20Regular", "", 1, 20));
exports.Temperature20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature20Filled", "", 0, 20));
exports.Temperature24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature24Regular", "", 1, 24));
exports.Temperature24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature24Filled", "", 0, 24));
exports.Temperature32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature32Regular", "", 1, 32));
exports.Temperature32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature32Filled", "", 0, 32));
exports.Temperature48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature48Regular", "", 1, 48));
exports.Temperature48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Temperature48Filled", "", 0, 48));
