"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tent48Filled = exports.Tent48Regular = exports.Tent28Filled = exports.Tent28Regular = exports.Tent24Filled = exports.Tent24Regular = exports.Tent20Filled = exports.Tent20Regular = exports.Tent16Filled = exports.Tent16Regular = exports.Tent12Filled = exports.Tent12Regular = exports.TentRegular = exports.TentFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TentFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TentFilled", "", 2, undefined));
exports.TentRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TentRegular", "", 2, undefined));
exports.Tent12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent12Regular", "", 1, 12));
exports.Tent12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent12Filled", "", 0, 12));
exports.Tent16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent16Regular", "", 1, 16));
exports.Tent16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent16Filled", "", 0, 16));
exports.Tent20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent20Regular", "", 1, 20));
exports.Tent20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent20Filled", "", 0, 20));
exports.Tent24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent24Regular", "", 1, 24));
exports.Tent24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent24Filled", "", 0, 24));
exports.Tent28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent28Regular", "", 1, 28));
exports.Tent28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent28Filled", "", 0, 28));
exports.Tent48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent48Regular", "", 1, 48));
exports.Tent48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Tent48Filled", "", 0, 48));
