"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Text32Light = exports.Text32Filled = exports.Text32Regular = exports.TextColor24Filled = exports.TextColor24Regular = exports.TextColor20Filled = exports.TextColor20Regular = exports.TextColor16Filled = exports.Text16Filled = exports.TextColor16Regular = exports.Text16Regular = exports.Text12Filled = exports.Text12Regular = exports.TextColorRegular = exports.TextColorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextColorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColorFilled", "", 2, undefined));
exports.TextColorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColorRegular", "", 2, undefined));
exports.Text12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text12Regular", "", 1, 12));
exports.Text12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text12Filled", "", 0, 12));
exports.Text16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text16Regular", "", 1, 16));
exports.TextColor16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColor16Regular", "", 1, 16));
exports.Text16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text16Filled", "", 0, 16));
exports.TextColor16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColor16Filled", "", 0, 16));
exports.TextColor20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColor20Regular", "", 1, 20));
exports.TextColor20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColor20Filled", "", 0, 20));
exports.TextColor24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColor24Regular", "", 1, 24));
exports.TextColor24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextColor24Filled", "", 0, 24));
exports.Text32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text32Regular", "", 1, 32));
exports.Text32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text32Filled", "", 0, 32));
exports.Text32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Text32Light", "", 3, 32));
