"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextDensity32Light = exports.TextDensity32Filled = exports.TextDensity32Regular = exports.TextDensity28Filled = exports.TextDensity28Regular = exports.TextDensity24Filled = exports.TextDensity24Regular = exports.TextDensity20Filled = exports.TextDensity20Regular = exports.TextDensity16Filled = exports.TextDensity16Regular = exports.TextDensityRegular = exports.TextDensityFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextDensityFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensityFilled", "", 2, undefined));
exports.TextDensityRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensityRegular", "", 2, undefined));
exports.TextDensity16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity16Regular", "", 1, 16));
exports.TextDensity16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity16Filled", "", 0, 16));
exports.TextDensity20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity20Regular", "", 1, 20));
exports.TextDensity20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity20Filled", "", 0, 20));
exports.TextDensity24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity24Regular", "", 1, 24));
exports.TextDensity24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity24Filled", "", 0, 24));
exports.TextDensity28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity28Regular", "", 1, 28));
exports.TextDensity28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity28Filled", "", 0, 28));
exports.TextDensity32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity32Regular", "󰑟", 1, 32));
exports.TextDensity32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity32Filled", "󰑲", 0, 32));
exports.TextDensity32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextDensity32Light", "", 3, 32));
