"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextHeader624Filled = exports.TextHeader624Regular = exports.TextHeader620Filled = exports.TextHeader620Regular = exports.TextHeader524Filled = exports.TextHeader524Regular = exports.TextHeader520Filled = exports.TextHeader520Regular = exports.TextHeader424Filled = exports.TextHeader424Regular = exports.TextHeader420Filled = exports.TextHeader420Regular = exports.TextHeader324Filled = exports.TextHeader324Regular = exports.TextHeader320Filled = exports.TextHeader320Regular = exports.TextHeader224Filled = exports.TextHeader224Regular = exports.TextHeader220Filled = exports.TextHeader220Regular = exports.TextHeader124Filled = exports.TextHeader124Regular = exports.TextHeader120Filled = exports.TextHeader120Regular = exports.TextHeader6Filled = exports.TextHeader6Regular = exports.TextHeader5Filled = exports.TextHeader5Regular = exports.TextHeader4Filled = exports.TextHeader4Regular = exports.TextHeader3Filled = exports.TextHeader3Regular = exports.TextHeader2Filled = exports.TextHeader2Regular = exports.TextHeader1Filled = exports.TextHeader1Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextHeader1Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader1Regular", "", 2, undefined));
exports.TextHeader1Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader1Filled", "", 2, undefined));
exports.TextHeader2Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader2Regular", "", 2, undefined));
exports.TextHeader2Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader2Filled", "", 2, undefined));
exports.TextHeader3Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader3Regular", "", 2, undefined));
exports.TextHeader3Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader3Filled", "", 2, undefined));
exports.TextHeader4Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader4Regular", "", 2, undefined));
exports.TextHeader4Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader4Filled", "", 2, undefined));
exports.TextHeader5Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader5Regular", "", 2, undefined));
exports.TextHeader5Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader5Filled", "", 2, undefined));
exports.TextHeader6Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader6Regular", "", 2, undefined));
exports.TextHeader6Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader6Filled", "", 2, undefined));
exports.TextHeader120Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader120Regular", "", 1, 20));
exports.TextHeader120Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader120Filled", "", 0, 20));
exports.TextHeader124Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader124Regular", "", 1, 24));
exports.TextHeader124Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader124Filled", "", 0, 24));
exports.TextHeader220Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader220Regular", "", 1, 20));
exports.TextHeader220Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader220Filled", "", 0, 20));
exports.TextHeader224Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader224Regular", "", 1, 24));
exports.TextHeader224Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader224Filled", "", 0, 24));
exports.TextHeader320Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader320Regular", "", 1, 20));
exports.TextHeader320Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader320Filled", "", 0, 20));
exports.TextHeader324Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader324Regular", "", 1, 24));
exports.TextHeader324Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader324Filled", "", 0, 24));
exports.TextHeader420Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader420Regular", "󰥖", 1, 20));
exports.TextHeader420Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader420Filled", "󰧓", 0, 20));
exports.TextHeader424Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader424Regular", "󰥗", 1, 24));
exports.TextHeader424Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader424Filled", "󰧔", 0, 24));
exports.TextHeader520Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader520Regular", "󰥘", 1, 20));
exports.TextHeader520Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader520Filled", "󰧕", 0, 20));
exports.TextHeader524Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader524Regular", "󰥙", 1, 24));
exports.TextHeader524Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader524Filled", "󰧖", 0, 24));
exports.TextHeader620Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader620Regular", "󰥚", 1, 20));
exports.TextHeader620Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader620Filled", "󰧗", 0, 20));
exports.TextHeader624Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader624Regular", "󰥛", 1, 24));
exports.TextHeader624Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextHeader624Filled", "󰧘", 0, 24));
