"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextEffects24Filled = exports.TextEffects24Regular = exports.TextEffects20Filled = exports.TextEffects20Regular = exports.TextEffectsRegular = exports.TextEffectsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextEffectsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextEffectsFilled", "", 2, undefined));
exports.TextEffectsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextEffectsRegular", "", 2, undefined));
exports.TextEffects20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextEffects20Regular", "", 1, 20));
exports.TextEffects20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextEffects20Filled", "", 0, 20));
exports.TextEffects24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextEffects24Regular", "", 1, 24));
exports.TextEffects24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextEffects24Filled", "", 0, 24));
