"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextItalic24Filled = exports.TextItalic24Regular = exports.TextItalic20Filled = exports.TextItalic20Regular = exports.TextItalic16Filled = exports.TextItalic16Regular = exports.TextItalicRegular = exports.TextItalicFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextItalicFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalicFilled", "", 2, undefined));
exports.TextItalicRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalicRegular", "", 2, undefined));
exports.TextItalic16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalic16Regular", "", 1, 16));
exports.TextItalic16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalic16Filled", "", 0, 16));
exports.TextItalic20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalic20Regular", "", 1, 20));
exports.TextItalic20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalic20Filled", "", 0, 20));
exports.TextItalic24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalic24Regular", "", 1, 24));
exports.TextItalic24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextItalic24Filled", "", 0, 24));
