"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextT48Filled = exports.TextT48Regular = exports.TextT32Filled = exports.TextT32Regular = exports.TextT28Filled = exports.TextT28Regular = exports.TextT24Filled = exports.TextT24Regular = exports.TextT20Filled = exports.TextT20Regular = exports.TextT16Filled = exports.TextT16Regular = exports.TextT12Filled = exports.TextT12Regular = exports.TextTRegular = exports.TextTFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextTFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextTFilled", "", 2, undefined));
exports.TextTRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextTRegular", "", 2, undefined));
exports.TextT12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT12Regular", "", 1, 12));
exports.TextT12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT12Filled", "", 0, 12));
exports.TextT16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT16Regular", "", 1, 16));
exports.TextT16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT16Filled", "", 0, 16));
exports.TextT20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT20Regular", "", 1, 20));
exports.TextT20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT20Filled", "", 0, 20));
exports.TextT24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT24Regular", "", 1, 24));
exports.TextT24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT24Filled", "", 0, 24));
exports.TextT28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT28Regular", "", 1, 28));
exports.TextT28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT28Filled", "", 0, 28));
exports.TextT32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT32Regular", "", 1, 32));
exports.TextT32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT32Filled", "", 0, 32));
exports.TextT48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT48Regular", "", 1, 48));
exports.TextT48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextT48Filled", "", 0, 48));
