"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextBold24Filled = exports.TextBold24Regular = exports.TextBold20Filled = exports.TextBold20Regular = exports.TextBold16Filled = exports.TextBold16Regular = exports.TextBoldRegular = exports.TextBoldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TextBoldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBoldFilled", "", 2, undefined));
exports.TextBoldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBoldRegular", "", 2, undefined));
exports.TextBold16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBold16Regular", "", 1, 16));
exports.TextBold16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBold16Filled", "", 0, 16));
exports.TextBold20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBold20Regular", "", 1, 20));
exports.TextBold20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBold20Filled", "", 0, 20));
exports.TextBold24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBold24Regular", "", 1, 24));
exports.TextBold24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TextBold24Filled", "", 0, 24));
