"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimePicker24Filled = exports.TimePicker24Regular = exports.TimePicker20Filled = exports.TimePicker20Regular = exports.TimePickerRegular = exports.TimePickerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TimePickerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimePickerFilled", "", 2, undefined));
exports.TimePickerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimePickerRegular", "", 2, undefined));
exports.TimePicker20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimePicker20Regular", "", 1, 20));
exports.TimePicker20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimePicker20Filled", "", 0, 20));
exports.TimePicker24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimePicker24Regular", "", 1, 24));
exports.TimePicker24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimePicker24Filled", "", 0, 24));
