"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Timer1024Filled = exports.Timer1024Regular = exports.Timer1020Filled = exports.Timer1020Regular = exports.Timer324Filled = exports.Timer324Regular = exports.Timer320Filled = exports.Timer320Regular = exports.Timer224Filled = exports.Timer224Regular = exports.Timer220Filled = exports.Timer220Regular = exports.Timer48Filled = exports.Timer48Regular = exports.Timer32Filled = exports.Timer32Regular = exports.Timer28Filled = exports.Timer28Regular = exports.Timer24Filled = exports.Timer24Regular = exports.Timer20Filled = exports.Timer20Regular = exports.Timer16Filled = exports.Timer16Regular = exports.Timer12Filled = exports.Timer12Regular = exports.Timer10Filled = exports.Timer10Regular = exports.Timer3Filled = exports.Timer3Regular = exports.Timer2Filled = exports.Timer2Regular = exports.TimerRegular = exports.TimerFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TimerFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimerFilled", "", 2, undefined));
exports.TimerRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TimerRegular", "", 2, undefined));
exports.Timer2Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer2Regular", "", 2, undefined));
exports.Timer2Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer2Filled", "", 2, undefined));
exports.Timer3Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer3Regular", "", 2, undefined));
exports.Timer3Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer3Filled", "", 2, undefined));
exports.Timer10Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer10Regular", "", 2, undefined));
exports.Timer10Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer10Filled", "", 2, undefined));
exports.Timer12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer12Regular", "", 1, 12));
exports.Timer12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer12Filled", "", 0, 12));
exports.Timer16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer16Regular", "", 1, 16));
exports.Timer16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer16Filled", "", 0, 16));
exports.Timer20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer20Regular", "", 1, 20));
exports.Timer20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer20Filled", "", 0, 20));
exports.Timer24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer24Regular", "", 1, 24));
exports.Timer24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer24Filled", "", 0, 24));
exports.Timer28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer28Regular", "", 1, 28));
exports.Timer28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer28Filled", "", 0, 28));
exports.Timer32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer32Regular", "", 1, 32));
exports.Timer32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer32Filled", "", 0, 32));
exports.Timer48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer48Regular", "", 1, 48));
exports.Timer48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer48Filled", "", 0, 48));
exports.Timer220Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer220Regular", "", 1, 20));
exports.Timer220Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer220Filled", "", 0, 20));
exports.Timer224Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer224Regular", "", 1, 24));
exports.Timer224Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer224Filled", "", 0, 24));
exports.Timer320Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer320Regular", "", 1, 20));
exports.Timer320Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer320Filled", "", 0, 20));
exports.Timer324Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer324Regular", "", 1, 24));
exports.Timer324Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer324Filled", "", 0, 24));
exports.Timer1020Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer1020Regular", "", 1, 20));
exports.Timer1020Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer1020Filled", "", 0, 20));
exports.Timer1024Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer1024Regular", "", 1, 24));
exports.Timer1024Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Timer1024Filled", "", 0, 24));
