"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToggleRight48Filled = exports.ToggleRight48Regular = exports.ToggleRight28Filled = exports.ToggleRight28Regular = exports.ToggleRight24Filled = exports.ToggleRight24Regular = exports.ToggleRight20Filled = exports.ToggleRight20Regular = exports.ToggleRight16Filled = exports.ToggleRight16Regular = exports.ToggleRightRegular = exports.ToggleRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ToggleRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRightFilled", "", 2, undefined));
exports.ToggleRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRightRegular", "", 2, undefined));
exports.ToggleRight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight16Regular", "", 1, 16));
exports.ToggleRight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight16Filled", "", 0, 16));
exports.ToggleRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight20Regular", "", 1, 20));
exports.ToggleRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight20Filled", "", 0, 20));
exports.ToggleRight24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight24Regular", "", 1, 24));
exports.ToggleRight24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight24Filled", "", 0, 24));
exports.ToggleRight28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight28Regular", "", 1, 28));
exports.ToggleRight28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight28Filled", "", 0, 28));
exports.ToggleRight48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight48Regular", "", 1, 48));
exports.ToggleRight48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ToggleRight48Filled", "", 0, 48));
