"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TopSpeed24Filled = exports.TopSpeed24Regular = exports.TopSpeed20Filled = exports.TopSpeed20Regular = exports.TopSpeed16Regular = exports.TopSpeedRegular = exports.TopSpeedFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TopSpeedFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeedFilled", "", 2, undefined));
exports.TopSpeedRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeedRegular", "", 2, undefined));
exports.TopSpeed16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeed16Regular", "󰨕", 1, 16));
exports.TopSpeed20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeed20Regular", "", 1, 20));
exports.TopSpeed20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeed20Filled", "", 0, 20));
exports.TopSpeed24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeed24Regular", "", 1, 24));
exports.TopSpeed24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TopSpeed24Filled", "", 0, 24));
