"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TranslateOff24Filled = exports.TranslateOff24Regular = exports.TranslateOff20Filled = exports.TranslateOff20Regular = exports.TranslateOff16Filled = exports.TranslateOff16Regular = exports.TranslateOffRegular = exports.TranslateOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TranslateOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOffFilled", "", 2, undefined));
exports.TranslateOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOffRegular", "", 2, undefined));
exports.TranslateOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOff16Regular", "󰂽", 1, 16));
exports.TranslateOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOff16Filled", "󰂼", 0, 16));
exports.TranslateOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOff20Regular", "󰂾", 1, 20));
exports.TranslateOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOff20Filled", "󰂽", 0, 20));
exports.TranslateOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOff24Regular", "󰂿", 1, 24));
exports.TranslateOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TranslateOff24Filled", "󰂾", 0, 24));
