"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Triangle48Filled = exports.Triangle48Regular = exports.Triangle32Filled = exports.Triangle32Regular = exports.Triangle28Filled = exports.Triangle28Regular = exports.Triangle24Filled = exports.Triangle24Regular = exports.Triangle20Filled = exports.Triangle20Regular = exports.Triangle16Filled = exports.Triangle16Regular = exports.Triangle12Filled = exports.Triangle12Regular = exports.TriangleRegular = exports.TriangleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TriangleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleFilled", "", 2, undefined));
exports.TriangleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRegular", "", 2, undefined));
exports.Triangle12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle12Regular", "", 1, 12));
exports.Triangle12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle12Filled", "", 0, 12));
exports.Triangle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle16Regular", "", 1, 16));
exports.Triangle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle16Filled", "", 0, 16));
exports.Triangle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle20Regular", "", 1, 20));
exports.Triangle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle20Filled", "", 0, 20));
exports.Triangle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle24Regular", "󰎥", 1, 24));
exports.Triangle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle24Filled", "󰎸", 0, 24));
exports.Triangle28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle28Regular", "󰎦", 1, 28));
exports.Triangle28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle28Filled", "󰎹", 0, 28));
exports.Triangle32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle32Regular", "", 1, 32));
exports.Triangle32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle32Filled", "", 0, 32));
exports.Triangle48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle48Regular", "", 1, 48));
exports.Triangle48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Triangle48Filled", "", 0, 48));
