"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TriangleRight48Filled = exports.TriangleRight48Regular = exports.TriangleRight32Filled = exports.TriangleRight32Regular = exports.TriangleRight20Filled = exports.TriangleRight20Regular = exports.TriangleRight16Filled = exports.TriangleRight16Regular = exports.TriangleRight12Filled = exports.TriangleRight12Regular = exports.TriangleRightRegular = exports.TriangleRightFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TriangleRightFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRightFilled", "", 2, undefined));
exports.TriangleRightRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRightRegular", "", 2, undefined));
exports.TriangleRight12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight12Regular", "", 1, 12));
exports.TriangleRight12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight12Filled", "", 0, 12));
exports.TriangleRight16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight16Regular", "", 1, 16));
exports.TriangleRight16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight16Filled", "", 0, 16));
exports.TriangleRight20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight20Regular", "", 1, 20));
exports.TriangleRight20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight20Filled", "", 0, 20));
exports.TriangleRight32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight32Regular", "", 1, 32));
exports.TriangleRight32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight32Filled", "", 0, 32));
exports.TriangleRight48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight48Regular", "", 1, 48));
exports.TriangleRight48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TriangleRight48Filled", "", 0, 48));
