"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrophyOff48Filled = exports.TrophyOff48Regular = exports.TrophyOff32Filled = exports.TrophyOff32Regular = exports.TrophyOff28Filled = exports.TrophyOff28Regular = exports.TrophyOff24Filled = exports.TrophyOff24Regular = exports.TrophyOff20Filled = exports.TrophyOff20Regular = exports.TrophyOff16Filled = exports.TrophyOff16Regular = exports.TrophyOffRegular = exports.TrophyOffFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TrophyOffFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOffFilled", "", 2, undefined));
exports.TrophyOffRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOffRegular", "", 2, undefined));
exports.TrophyOff16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff16Regular", "", 1, 16));
exports.TrophyOff16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff16Filled", "", 0, 16));
exports.TrophyOff20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff20Regular", "", 1, 20));
exports.TrophyOff20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff20Filled", "", 0, 20));
exports.TrophyOff24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff24Regular", "", 1, 24));
exports.TrophyOff24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff24Filled", "", 0, 24));
exports.TrophyOff28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff28Regular", "", 1, 28));
exports.TrophyOff28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff28Filled", "", 0, 28));
exports.TrophyOff32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff32Regular", "", 1, 32));
exports.TrophyOff32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff32Filled", "", 0, 32));
exports.TrophyOff48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff48Regular", "", 1, 48));
exports.TrophyOff48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyOff48Filled", "", 0, 48));
