"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrophyLock48Filled = exports.TrophyLock48Regular = exports.TrophyLock32Filled = exports.TrophyLock32Regular = exports.TrophyLock28Filled = exports.TrophyLock28Regular = exports.TrophyLock24Filled = exports.TrophyLock24Regular = exports.TrophyLock20Filled = exports.TrophyLock20Regular = exports.TrophyLock16Filled = exports.TrophyLock16Regular = exports.TrophyLockRegular = exports.TrophyLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.TrophyLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLockFilled", "", 2, undefined));
exports.TrophyLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLockRegular", "", 2, undefined));
exports.TrophyLock16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock16Regular", "", 1, 16));
exports.TrophyLock16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock16Filled", "", 0, 16));
exports.TrophyLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock20Regular", "", 1, 20));
exports.TrophyLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock20Filled", "", 0, 20));
exports.TrophyLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock24Regular", "", 1, 24));
exports.TrophyLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock24Filled", "", 0, 24));
exports.TrophyLock28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock28Regular", "", 1, 28));
exports.TrophyLock28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock28Filled", "", 0, 28));
exports.TrophyLock32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock32Regular", "", 1, 32));
exports.TrophyLock32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock32Filled", "", 0, 32));
exports.TrophyLock48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock48Regular", "", 1, 48));
exports.TrophyLock48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("TrophyLock48Filled", "", 0, 48));
