"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Umbrella24Filled = exports.Umbrella24Regular = exports.Umbrella20Filled = exports.Umbrella20Regular = exports.UmbrellaRegular = exports.UmbrellaFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.UmbrellaFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UmbrellaFilled", "", 2, undefined));
exports.UmbrellaRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UmbrellaRegular", "", 2, undefined));
exports.Umbrella20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Umbrella20Regular", "", 1, 20));
exports.Umbrella20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Umbrella20Filled", "", 0, 20));
exports.Umbrella24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Umbrella24Regular", "", 1, 24));
exports.Umbrella24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Umbrella24Filled", "", 0, 24));
