"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UninstallApp24Filled = exports.UninstallApp24Regular = exports.UninstallApp20Filled = exports.UninstallApp20Regular = exports.UninstallAppRegular = exports.UninstallAppFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.UninstallAppFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UninstallAppFilled", "", 2, undefined));
exports.UninstallAppRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UninstallAppRegular", "", 2, undefined));
exports.UninstallApp20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UninstallApp20Regular", "", 1, 20));
exports.UninstallApp20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UninstallApp20Filled", "", 0, 20));
exports.UninstallApp24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UninstallApp24Regular", "", 1, 24));
exports.UninstallApp24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("UninstallApp24Filled", "", 0, 24));
