"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleBicycle24Filled = exports.VehicleBicycle24Regular = exports.VehicleBicycle20Filled = exports.VehicleBicycle20Regular = exports.VehicleBicycle16Filled = exports.VehicleBicycle16Regular = exports.VehicleBicycleRegular = exports.VehicleBicycleFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VehicleBicycleFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycleFilled", "", 2, undefined));
exports.VehicleBicycleRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycleRegular", "", 2, undefined));
exports.VehicleBicycle16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycle16Regular", "", 1, 16));
exports.VehicleBicycle16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycle16Filled", "", 0, 16));
exports.VehicleBicycle20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycle20Regular", "", 1, 20));
exports.VehicleBicycle20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycle20Filled", "", 0, 20));
exports.VehicleBicycle24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycle24Regular", "", 1, 24));
exports.VehicleBicycle24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleBicycle24Filled", "", 0, 24));
