"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleTractor24Filled = exports.VehicleTractor24Regular = exports.VehicleTractor20Filled = exports.VehicleTractor20Regular = exports.VehicleTractorRegular = exports.VehicleTractorFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VehicleTractorFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleTractorFilled", "", 2, undefined));
exports.VehicleTractorRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleTractorRegular", "", 2, undefined));
exports.VehicleTractor20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleTractor20Regular", "󰕾", 1, 20));
exports.VehicleTractor20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleTractor20Filled", "󰗷", 0, 20));
exports.VehicleTractor24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleTractor24Regular", "󰕿", 1, 24));
exports.VehicleTractor24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleTractor24Filled", "󰗸", 0, 24));
