"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleRv20Filled = exports.VehicleRv20Regular = exports.VehicleRv16Filled = exports.VehicleRv16Regular = exports.VehicleRvRegular = exports.VehicleRvFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VehicleRvFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleRvFilled", "", 2, undefined));
exports.VehicleRvRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleRvRegular", "", 2, undefined));
exports.VehicleRv16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleRv16Regular", "󰬣", 1, 16));
exports.VehicleRv16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleRv16Filled", "󰮡", 0, 16));
exports.VehicleRv20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleRv20Regular", "󰬤", 1, 20));
exports.VehicleRv20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VehicleRv20Filled", "󰮢", 0, 20));
