"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VideoAdd24Filled = exports.VideoAdd24Regular = exports.VideoAdd20Filled = exports.VideoAdd20Regular = exports.VideoAddRegular = exports.VideoAddFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VideoAddFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoAddFilled", "", 2, undefined));
exports.VideoAddRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoAddRegular", "", 2, undefined));
exports.VideoAdd20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoAdd20Regular", "", 1, 20));
exports.VideoAdd20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoAdd20Filled", "", 0, 20));
exports.VideoAdd24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoAdd24Regular", "", 1, 24));
exports.VideoAdd24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoAdd24Filled", "", 0, 24));
