"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VideoUsb48Filled = exports.VideoUsb48Regular = exports.VideoUsb32Filled = exports.VideoUsb32Regular = exports.VideoUsb28Filled = exports.VideoUsb28Regular = exports.VideoUsb24Filled = exports.VideoUsb24Regular = exports.VideoUsb20Filled = exports.VideoUsb20Regular = exports.VideoUsb16Filled = exports.VideoUsb16Regular = exports.VideoUsbRegular = exports.VideoUsbFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VideoUsbFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsbFilled", "", 2, undefined));
exports.VideoUsbRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsbRegular", "", 2, undefined));
exports.VideoUsb16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb16Regular", "󰛜", 1, 16));
exports.VideoUsb16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb16Filled", "󰝙", 0, 16));
exports.VideoUsb20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb20Regular", "󰛝", 1, 20));
exports.VideoUsb20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb20Filled", "󰝚", 0, 20));
exports.VideoUsb24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb24Regular", "󰛞", 1, 24));
exports.VideoUsb24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb24Filled", "󰝛", 0, 24));
exports.VideoUsb28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb28Regular", "󰛟", 1, 28));
exports.VideoUsb28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb28Filled", "󰝜", 0, 28));
exports.VideoUsb32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb32Regular", "󰛠", 1, 32));
exports.VideoUsb32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb32Filled", "󰝝", 0, 32));
exports.VideoUsb48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb48Regular", "󰛡", 1, 48));
exports.VideoUsb48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoUsb48Filled", "󰝞", 0, 48));
