"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VideoChat48Filled = exports.VideoChat48Regular = exports.VideoChat32Filled = exports.VideoChat32Regular = exports.VideoChat28Filled = exports.VideoChat28Regular = exports.VideoChat24Filled = exports.VideoChat24Regular = exports.VideoChat20Filled = exports.VideoChat20Regular = exports.VideoChat16Filled = exports.VideoChat16Regular = exports.VideoChatRegular = exports.VideoChatFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VideoChatFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChatFilled", "", 2, undefined));
exports.VideoChatRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChatRegular", "", 2, undefined));
exports.VideoChat16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat16Regular", "", 1, 16));
exports.VideoChat16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat16Filled", "", 0, 16));
exports.VideoChat20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat20Regular", "", 1, 20));
exports.VideoChat20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat20Filled", "", 0, 20));
exports.VideoChat24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat24Regular", "", 1, 24));
exports.VideoChat24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat24Filled", "", 0, 24));
exports.VideoChat28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat28Regular", "", 1, 28));
exports.VideoChat28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat28Filled", "", 0, 28));
exports.VideoChat32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat32Regular", "", 1, 32));
exports.VideoChat32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat32Filled", "", 0, 32));
exports.VideoChat48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat48Regular", "", 1, 48));
exports.VideoChat48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoChat48Filled", "", 0, 48));
