"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VideoShort48Filled = exports.VideoShort48Regular = exports.VideoShort32Filled = exports.VideoShort32Regular = exports.VideoShort28Filled = exports.VideoShort28Regular = exports.VideoShort24Filled = exports.VideoShort24Regular = exports.VideoShort20Filled = exports.VideoShort20Regular = exports.VideoShort16Filled = exports.VideoShort16Regular = exports.VideoShortRegular = exports.VideoShortFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VideoShortFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShortFilled", "", 2, undefined));
exports.VideoShortRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShortRegular", "", 2, undefined));
exports.VideoShort16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort16Regular", "󰬩", 1, 16));
exports.VideoShort16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort16Filled", "󰮧", 0, 16));
exports.VideoShort20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort20Regular", "󰬪", 1, 20));
exports.VideoShort20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort20Filled", "󰮨", 0, 20));
exports.VideoShort24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort24Regular", "󰬫", 1, 24));
exports.VideoShort24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort24Filled", "󰮩", 0, 24));
exports.VideoShort28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort28Regular", "󰬬", 1, 28));
exports.VideoShort28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort28Filled", "󰮪", 0, 28));
exports.VideoShort32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort32Regular", "󰬭", 1, 32));
exports.VideoShort32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort32Filled", "󰮫", 0, 32));
exports.VideoShort48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort48Regular", "󰬮", 1, 48));
exports.VideoShort48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoShort48Filled", "󰮬", 0, 48));
