"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VideoSwitch24Filled = exports.VideoSwitch24Regular = exports.VideoSwitch20Filled = exports.VideoSwitch20Regular = exports.VideoSwitchRegular = exports.VideoSwitchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VideoSwitchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoSwitchFilled", "", 2, undefined));
exports.VideoSwitchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoSwitchRegular", "", 2, undefined));
exports.VideoSwitch20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoSwitch20Regular", "", 1, 20));
exports.VideoSwitch20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoSwitch20Filled", "", 0, 20));
exports.VideoSwitch24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoSwitch24Regular", "", 1, 24));
exports.VideoSwitch24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoSwitch24Filled", "", 0, 24));
