"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Video36024Filled = exports.Video36024Regular = exports.Video36020Filled = exports.Video36020Regular = exports.Video48Filled = exports.Video48Regular = exports.Video32Light = exports.Video32Filled = exports.Video32Regular = exports.Video28Filled = exports.Video28Regular = exports.Video24Filled = exports.Video24Regular = exports.Video20Filled = exports.Video20Regular = exports.Video16Filled = exports.Video16Regular = exports.Video360Filled = exports.Video360Regular = exports.VideoRegular = exports.VideoFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VideoFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoFilled", "", 2, undefined));
exports.VideoRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VideoRegular", "", 2, undefined));
exports.Video360Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video360Regular", "", 2, undefined));
exports.Video360Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video360Filled", "", 2, undefined));
exports.Video16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video16Regular", "", 1, 16));
exports.Video16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video16Filled", "", 0, 16));
exports.Video20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video20Regular", "", 1, 20));
exports.Video20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video20Filled", "", 0, 20));
exports.Video24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video24Regular", "", 1, 24));
exports.Video24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video24Filled", "", 0, 24));
exports.Video28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video28Regular", "", 1, 28));
exports.Video28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video28Filled", "", 0, 28));
exports.Video32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video32Regular", "", 1, 32));
exports.Video32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video32Filled", "", 0, 32));
exports.Video32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video32Light", "", 3, 32));
exports.Video48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video48Regular", "", 1, 48));
exports.Video48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video48Filled", "", 0, 48));
exports.Video36020Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video36020Regular", "", 1, 20));
exports.Video36020Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video36020Filled", "", 0, 20));
exports.Video36024Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video36024Regular", "", 1, 24));
exports.Video36024Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Video36024Filled", "", 0, 24));
