"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ViewDesktop24Filled = exports.ViewDesktop24Regular = exports.ViewDesktop20Filled = exports.ViewDesktop20Regular = exports.ViewDesktopRegular = exports.ViewDesktopFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ViewDesktopFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ViewDesktopFilled", "", 2, undefined));
exports.ViewDesktopRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ViewDesktopRegular", "", 2, undefined));
exports.ViewDesktop20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ViewDesktop20Regular", "", 1, 20));
exports.ViewDesktop20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ViewDesktop20Filled", "", 0, 20));
exports.ViewDesktop24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ViewDesktop24Regular", "", 1, 24));
exports.ViewDesktop24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ViewDesktop24Filled", "", 0, 24));
