"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Vote24Filled = exports.Vote24Regular = exports.Vote20Filled = exports.Vote20Regular = exports.Vote16Filled = exports.Vote16Regular = exports.VoteRegular = exports.VoteFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.VoteFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VoteFilled", "", 2, undefined));
exports.VoteRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("VoteRegular", "", 2, undefined));
exports.Vote16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Vote16Regular", "󰣚", 1, 16));
exports.Vote16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Vote16Filled", "󰥗", 0, 16));
exports.Vote20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Vote20Regular", "", 1, 20));
exports.Vote20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Vote20Filled", "", 0, 20));
exports.Vote24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Vote24Regular", "", 1, 24));
exports.Vote24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Vote24Filled", "", 0, 24));
