"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WalkieTalkie28Filled = exports.WalkieTalkie28Regular = exports.WalkieTalkie24Filled = exports.WalkieTalkie24Regular = exports.WalkieTalkie20Filled = exports.WalkieTalkie20Regular = exports.WalkieTalkieRegular = exports.WalkieTalkieFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WalkieTalkieFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkieFilled", "", 2, undefined));
exports.WalkieTalkieRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkieRegular", "", 2, undefined));
exports.WalkieTalkie20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkie20Regular", "", 1, 20));
exports.WalkieTalkie20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkie20Filled", "", 0, 20));
exports.WalkieTalkie24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkie24Regular", "", 1, 24));
exports.WalkieTalkie24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkie24Filled", "", 0, 24));
exports.WalkieTalkie28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkie28Regular", "", 1, 28));
exports.WalkieTalkie28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WalkieTalkie28Filled", "", 0, 28));
