"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wallpaper24Filled = exports.Wallpaper24Regular = exports.Wallpaper20Filled = exports.Wallpaper20Regular = exports.WallpaperRegular = exports.WallpaperFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WallpaperFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WallpaperFilled", "", 2, undefined));
exports.WallpaperRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WallpaperRegular", "", 2, undefined));
exports.Wallpaper20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wallpaper20Regular", "", 1, 20));
exports.Wallpaper20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wallpaper20Filled", "", 0, 20));
exports.Wallpaper24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wallpaper24Regular", "", 1, 24));
exports.Wallpaper24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wallpaper24Filled", "", 0, 24));
