"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Warning48Filled = exports.Warning48Regular = exports.Warning32Filled = exports.Warning32Regular = exports.Warning28Filled = exports.Warning28Regular = exports.Warning24Filled = exports.Warning24Regular = exports.Warning20Filled = exports.Warning20Regular = exports.Warning16Filled = exports.Warning16Regular = exports.Warning12Filled = exports.Warning12Regular = exports.WarningRegular = exports.WarningFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WarningFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WarningFilled", "", 2, undefined));
exports.WarningRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WarningRegular", "", 2, undefined));
exports.Warning12Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning12Regular", "", 1, 12));
exports.Warning12Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning12Filled", "", 0, 12));
exports.Warning16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning16Regular", "", 1, 16));
exports.Warning16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning16Filled", "", 0, 16));
exports.Warning20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning20Regular", "", 1, 20));
exports.Warning20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning20Filled", "", 0, 20));
exports.Warning24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning24Regular", "", 1, 24));
exports.Warning24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning24Filled", "", 0, 24));
exports.Warning28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning28Regular", "", 1, 28));
exports.Warning28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning28Filled", "", 0, 28));
exports.Warning32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning32Regular", "󰉊", 1, 32));
exports.Warning32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning32Filled", "󰉝", 0, 32));
exports.Warning48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning48Regular", "󰏏", 1, 48));
exports.Warning48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Warning48Filled", "󰏢", 0, 48));
