"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherSnow48Filled = exports.WeatherSnow48Regular = exports.WeatherSnow24Filled = exports.WeatherSnow24Regular = exports.WeatherSnow20Filled = exports.WeatherSnow20Regular = exports.WeatherSnowRegular = exports.WeatherSnowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WeatherSnowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnowFilled", "", 2, undefined));
exports.WeatherSnowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnowRegular", "", 2, undefined));
exports.WeatherSnow20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnow20Regular", "", 1, 20));
exports.WeatherSnow20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnow20Filled", "", 0, 20));
exports.WeatherSnow24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnow24Regular", "", 1, 24));
exports.WeatherSnow24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnow24Filled", "", 0, 24));
exports.WeatherSnow48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnow48Regular", "", 1, 48));
exports.WeatherSnow48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSnow48Filled", "", 0, 48));
