"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherSunny48Filled = exports.WeatherSunny48Regular = exports.WeatherSunny32Light = exports.WeatherSunny32Filled = exports.WeatherSunny32Regular = exports.WeatherSunny28Filled = exports.WeatherSunny28Regular = exports.WeatherSunny24Filled = exports.WeatherSunny24Regular = exports.WeatherSunny20Filled = exports.WeatherSunny20Regular = exports.WeatherSunny16Filled = exports.WeatherSunny16Regular = exports.WeatherSunnyRegular = exports.WeatherSunnyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WeatherSunnyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunnyFilled", "", 2, undefined));
exports.WeatherSunnyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunnyRegular", "", 2, undefined));
exports.WeatherSunny16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny16Regular", "", 1, 16));
exports.WeatherSunny16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny16Filled", "", 0, 16));
exports.WeatherSunny20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny20Regular", "", 1, 20));
exports.WeatherSunny20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny20Filled", "", 0, 20));
exports.WeatherSunny24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny24Regular", "", 1, 24));
exports.WeatherSunny24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny24Filled", "", 0, 24));
exports.WeatherSunny28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny28Regular", "", 1, 28));
exports.WeatherSunny28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny28Filled", "", 0, 28));
exports.WeatherSunny32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny32Regular", "", 1, 32));
exports.WeatherSunny32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny32Filled", "", 0, 32));
exports.WeatherSunny32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny32Light", "", 3, 32));
exports.WeatherSunny48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny48Regular", "", 1, 48));
exports.WeatherSunny48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSunny48Filled", "", 0, 48));
