"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherMoon48Filled = exports.WeatherMoon48Regular = exports.WeatherMoon32Light = exports.WeatherMoon32Filled = exports.WeatherMoon32Regular = exports.WeatherMoon28Filled = exports.WeatherMoon28Regular = exports.WeatherMoon24Filled = exports.WeatherMoon24Regular = exports.WeatherMoon20Filled = exports.WeatherMoon20Regular = exports.WeatherMoon16Filled = exports.WeatherMoon16Regular = exports.WeatherMoonRegular = exports.WeatherMoonFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WeatherMoonFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoonFilled", "", 2, undefined));
exports.WeatherMoonRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoonRegular", "", 2, undefined));
exports.WeatherMoon16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon16Regular", "", 1, 16));
exports.WeatherMoon16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon16Filled", "", 0, 16));
exports.WeatherMoon20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon20Regular", "", 1, 20));
exports.WeatherMoon20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon20Filled", "", 0, 20));
exports.WeatherMoon24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon24Regular", "", 1, 24));
exports.WeatherMoon24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon24Filled", "", 0, 24));
exports.WeatherMoon28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon28Regular", "", 1, 28));
exports.WeatherMoon28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon28Filled", "", 0, 28));
exports.WeatherMoon32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon32Regular", "󰟨", 1, 32));
exports.WeatherMoon32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon32Filled", "󰡥", 0, 32));
exports.WeatherMoon32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon32Light", "", 3, 32));
exports.WeatherMoon48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon48Regular", "", 1, 48));
exports.WeatherMoon48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherMoon48Filled", "", 0, 48));
