"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherRain48Filled = exports.WeatherRain48Regular = exports.WeatherRain24Filled = exports.WeatherRain24Regular = exports.WeatherRain20Filled = exports.WeatherRain20Regular = exports.WeatherRainRegular = exports.WeatherRainFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WeatherRainFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRainFilled", "", 2, undefined));
exports.WeatherRainRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRainRegular", "", 2, undefined));
exports.WeatherRain20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRain20Regular", "", 1, 20));
exports.WeatherRain20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRain20Filled", "", 0, 20));
exports.WeatherRain24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRain24Regular", "", 1, 24));
exports.WeatherRain24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRain24Filled", "", 0, 24));
exports.WeatherRain48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRain48Regular", "", 1, 48));
exports.WeatherRain48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherRain48Filled", "", 0, 48));
