"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherSqualls48Filled = exports.WeatherSqualls48Regular = exports.WeatherSqualls24Filled = exports.WeatherSqualls24Regular = exports.WeatherSqualls20Filled = exports.WeatherSqualls20Regular = exports.WeatherSquallsRegular = exports.WeatherSquallsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WeatherSquallsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSquallsFilled", "", 2, undefined));
exports.WeatherSquallsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSquallsRegular", "", 2, undefined));
exports.WeatherSqualls20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSqualls20Regular", "", 1, 20));
exports.WeatherSqualls20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSqualls20Filled", "", 0, 20));
exports.WeatherSqualls24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSqualls24Regular", "", 1, 24));
exports.WeatherSqualls24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSqualls24Filled", "", 0, 24));
exports.WeatherSqualls48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSqualls48Regular", "", 1, 48));
exports.WeatherSqualls48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherSqualls48Filled", "", 0, 48));
