"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherCloudy48Filled = exports.WeatherCloudy48Regular = exports.WeatherCloudy24Filled = exports.WeatherCloudy24Regular = exports.WeatherCloudy20Filled = exports.WeatherCloudy20Regular = exports.WeatherCloudyRegular = exports.WeatherCloudyFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WeatherCloudyFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudyFilled", "", 2, undefined));
exports.WeatherCloudyRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudyRegular", "", 2, undefined));
exports.WeatherCloudy20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudy20Regular", "", 1, 20));
exports.WeatherCloudy20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudy20Filled", "", 0, 20));
exports.WeatherCloudy24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudy24Regular", "", 1, 24));
exports.WeatherCloudy24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudy24Filled", "", 0, 24));
exports.WeatherCloudy48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudy48Regular", "", 1, 48));
exports.WeatherCloudy48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WeatherCloudy48Filled", "", 0, 48));
