"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Whiteboard48Filled = exports.Whiteboard48Regular = exports.Whiteboard24Filled = exports.Whiteboard24Regular = exports.Whiteboard20Filled = exports.Whiteboard20Regular = exports.Whiteboard16Filled = exports.Whiteboard16Regular = exports.WhiteboardRegular = exports.WhiteboardFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WhiteboardFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WhiteboardFilled", "", 2, undefined));
exports.WhiteboardRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WhiteboardRegular", "", 2, undefined));
exports.Whiteboard16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard16Regular", "󰓄", 1, 16));
exports.Whiteboard16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard16Filled", "󰔽", 0, 16));
exports.Whiteboard20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard20Regular", "", 1, 20));
exports.Whiteboard20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard20Filled", "", 0, 20));
exports.Whiteboard24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard24Regular", "", 1, 24));
exports.Whiteboard24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard24Filled", "", 0, 24));
exports.Whiteboard48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard48Regular", "", 1, 48));
exports.Whiteboard48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Whiteboard48Filled", "", 0, 48));
