"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WifiWarning24Filled = exports.WifiWarning24Regular = exports.WifiWarning20Filled = exports.WifiWarning20Regular = exports.WifiWarningRegular = exports.WifiWarningFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WifiWarningFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiWarningFilled", "", 2, undefined));
exports.WifiWarningRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiWarningRegular", "", 2, undefined));
exports.WifiWarning20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiWarning20Regular", "", 1, 20));
exports.WifiWarning20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiWarning20Filled", "", 0, 20));
exports.WifiWarning24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiWarning24Regular", "", 1, 24));
exports.WifiWarning24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiWarning24Filled", "", 0, 24));
