"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wifi424Filled = exports.Wifi424Regular = exports.Wifi420Filled = exports.Wifi420Regular = exports.Wifi324Filled = exports.Wifi324Regular = exports.Wifi320Filled = exports.Wifi320Regular = exports.Wifi224Filled = exports.Wifi224Regular = exports.Wifi220Filled = exports.Wifi220Regular = exports.Wifi124Filled = exports.Wifi124Regular = exports.Wifi120Filled = exports.Wifi120Regular = exports.Wifi4Filled = exports.Wifi4Regular = exports.Wifi3Filled = exports.Wifi3Regular = exports.Wifi2Filled = exports.Wifi2Regular = exports.Wifi1Filled = exports.Wifi1Regular = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.Wifi1Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi1Regular", "", 2, undefined));
exports.Wifi1Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi1Filled", "", 2, undefined));
exports.Wifi2Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi2Regular", "", 2, undefined));
exports.Wifi2Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi2Filled", "", 2, undefined));
exports.Wifi3Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi3Regular", "", 2, undefined));
exports.Wifi3Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi3Filled", "", 2, undefined));
exports.Wifi4Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi4Regular", "", 2, undefined));
exports.Wifi4Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi4Filled", "", 2, undefined));
exports.Wifi120Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi120Regular", "", 1, 20));
exports.Wifi120Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi120Filled", "", 0, 20));
exports.Wifi124Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi124Regular", "", 1, 24));
exports.Wifi124Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi124Filled", "", 0, 24));
exports.Wifi220Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi220Regular", "", 1, 20));
exports.Wifi220Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi220Filled", "", 0, 20));
exports.Wifi224Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi224Regular", "", 1, 24));
exports.Wifi224Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi224Filled", "", 0, 24));
exports.Wifi320Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi320Regular", "", 1, 20));
exports.Wifi320Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi320Filled", "", 0, 20));
exports.Wifi324Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi324Regular", "", 1, 24));
exports.Wifi324Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi324Filled", "", 0, 24));
exports.Wifi420Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi420Regular", "", 1, 20));
exports.Wifi420Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi420Filled", "", 0, 20));
exports.Wifi424Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi424Regular", "", 1, 24));
exports.Wifi424Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wifi424Filled", "", 0, 24));
