"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WifiLock24Filled = exports.WifiLock24Regular = exports.WifiLock20Filled = exports.WifiLock20Regular = exports.WifiLockRegular = exports.WifiLockFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WifiLockFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiLockFilled", "", 2, undefined));
exports.WifiLockRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiLockRegular", "", 2, undefined));
exports.WifiLock20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiLock20Regular", "", 1, 20));
exports.WifiLock20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiLock20Filled", "", 0, 20));
exports.WifiLock24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiLock24Regular", "", 1, 24));
exports.WifiLock24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WifiLock24Filled", "", 0, 24));
