"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Window48Filled = exports.Window48Regular = exports.Window32Light = exports.Window32Filled = exports.Window32Regular = exports.Window28Filled = exports.Window28Regular = exports.Window24Filled = exports.Window24Regular = exports.Window20Filled = exports.Window20Regular = exports.Window16Filled = exports.Window16Regular = exports.WindowRegular = exports.WindowFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WindowFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowFilled", "", 2, undefined));
exports.WindowRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowRegular", "", 2, undefined));
exports.Window16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window16Regular", "", 1, 16));
exports.Window16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window16Filled", "", 0, 16));
exports.Window20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window20Regular", "", 1, 20));
exports.Window20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window20Filled", "", 0, 20));
exports.Window24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window24Regular", "", 1, 24));
exports.Window24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window24Filled", "", 0, 24));
exports.Window28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window28Regular", "", 1, 28));
exports.Window28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window28Filled", "", 0, 28));
exports.Window32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window32Regular", "", 1, 32));
exports.Window32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window32Filled", "", 0, 32));
exports.Window32Light = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window32Light", "", 3, 32));
exports.Window48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window48Regular", "", 1, 48));
exports.Window48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Window48Filled", "", 0, 48));
