"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowApps48Filled = exports.WindowApps48Regular = exports.WindowApps32Filled = exports.WindowApps32Regular = exports.WindowApps28Filled = exports.WindowApps28Regular = exports.WindowApps24Filled = exports.WindowApps24Regular = exports.WindowApps20Filled = exports.WindowApps20Regular = exports.WindowApps16Filled = exports.WindowApps16Regular = exports.WindowAppsRegular = exports.WindowAppsFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WindowAppsFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowAppsFilled", "", 2, undefined));
exports.WindowAppsRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowAppsRegular", "", 2, undefined));
exports.WindowApps16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps16Regular", "", 1, 16));
exports.WindowApps16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps16Filled", "", 0, 16));
exports.WindowApps20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps20Regular", "", 1, 20));
exports.WindowApps20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps20Filled", "", 0, 20));
exports.WindowApps24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps24Regular", "", 1, 24));
exports.WindowApps24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps24Filled", "", 0, 24));
exports.WindowApps28Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps28Regular", "", 1, 28));
exports.WindowApps28Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps28Filled", "", 0, 28));
exports.WindowApps32Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps32Regular", "", 1, 32));
exports.WindowApps32Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps32Filled", "", 0, 32));
exports.WindowApps48Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps48Regular", "", 1, 48));
exports.WindowApps48Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowApps48Filled", "", 0, 48));
