"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowShield24Filled = exports.WindowShield24Regular = exports.WindowShield20Filled = exports.WindowShield20Regular = exports.WindowShield16Filled = exports.WindowShield16Regular = exports.WindowShieldRegular = exports.WindowShieldFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WindowShieldFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShieldFilled", "", 2, undefined));
exports.WindowShieldRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShieldRegular", "", 2, undefined));
exports.WindowShield16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShield16Regular", "", 1, 16));
exports.WindowShield16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShield16Filled", "", 0, 16));
exports.WindowShield20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShield20Regular", "", 1, 20));
exports.WindowShield20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShield20Filled", "", 0, 20));
exports.WindowShield24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShield24Regular", "", 1, 24));
exports.WindowShield24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowShield24Filled", "", 0, 24));
