"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowEdit20Filled = exports.WindowEdit20Regular = exports.WindowEdit16Filled = exports.WindowEdit16Regular = exports.WindowEditRegular = exports.WindowEditFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WindowEditFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowEditFilled", "", 2, undefined));
exports.WindowEditRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowEditRegular", "", 2, undefined));
exports.WindowEdit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowEdit16Regular", "", 1, 16));
exports.WindowEdit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowEdit16Filled", "", 0, 16));
exports.WindowEdit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowEdit20Regular", "", 1, 20));
exports.WindowEdit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WindowEdit20Filled", "", 0, 20));
