"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wrench24Filled = exports.Wrench24Regular = exports.Wrench20Filled = exports.Wrench20Regular = exports.Wrench16Filled = exports.Wrench16Regular = exports.WrenchRegular = exports.WrenchFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.WrenchFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WrenchFilled", "", 2, undefined));
exports.WrenchRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("WrenchRegular", "", 2, undefined));
exports.Wrench16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wrench16Regular", "", 1, 16));
exports.Wrench16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wrench16Filled", "", 0, 16));
exports.Wrench20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wrench20Regular", "", 1, 20));
exports.Wrench20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wrench20Filled", "", 0, 20));
exports.Wrench24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wrench24Regular", "", 1, 24));
exports.Wrench24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("Wrench24Filled", "", 0, 24));
