"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ZoomFit24Filled = exports.ZoomFit24Regular = exports.ZoomFit20Filled = exports.ZoomFit20Regular = exports.ZoomFit16Filled = exports.ZoomFit16Regular = exports.ZoomFitRegular = exports.ZoomFitFilled = void 0;
const createFluentFontIcon_1 = require("../../utils/fonts/createFluentFontIcon");
exports.ZoomFitFilled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFitFilled", "", 2, undefined));
exports.ZoomFitRegular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFitRegular", "", 2, undefined));
exports.ZoomFit16Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFit16Regular", "", 1, 16));
exports.ZoomFit16Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFit16Filled", "", 0, 16));
exports.ZoomFit20Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFit20Regular", "", 1, 20));
exports.ZoomFit20Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFit20Filled", "", 0, 20));
exports.ZoomFit24Regular = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFit24Regular", "", 1, 24));
exports.ZoomFit24Filled = ( /*#__PURE__*/createFluentFontIcon_1.createFluentFontIcon("ZoomFit24Filled", "", 0, 24));
