import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const ArrowSquareDownColor: FluentIcon;
export declare const ArrowSquareDownFilled: FluentIcon;
export declare const ArrowSquareDownRegular: FluentIcon;
export declare const ArrowSquareDown20Regular: FluentIcon;
export declare const ArrowSquareDown20Filled: FluentIcon;
export declare const ArrowSquareDown20Color: FluentIcon;
export declare const ArrowSquareDown24Regular: FluentIcon;
export declare const ArrowSquareDown24Filled: FluentIcon;
export declare const ArrowSquareDown24Color: FluentIcon;
export declare const ArrowSquareDown32Regular: FluentIcon;
export declare const ArrowSquareDown32Filled: FluentIcon;
export declare const ArrowSquareDown32Color: FluentIcon;
