import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const CalendarSyncColor: FluentIcon;
export declare const CalendarSyncFilled: FluentIcon;
export declare const CalendarSyncRegular: FluentIcon;
export declare const CalendarSync16Regular: FluentIcon;
export declare const CalendarSync16Filled: FluentIcon;
export declare const CalendarSync16Color: FluentIcon;
export declare const CalendarSync20Regular: FluentIcon;
export declare const CalendarSync20Filled: FluentIcon;
export declare const CalendarSync20Color: FluentIcon;
export declare const CalendarSync24Regular: FluentIcon;
export declare const CalendarSync24Filled: FluentIcon;
export declare const CalendarSync24Color: FluentIcon;
