import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const CalendarCheckmarkColor: FluentIcon;
export declare const CalendarCheckmarkFilled: FluentIcon;
export declare const CalendarCheckmarkRegular: FluentIcon;
export declare const CalendarCheckmark16Regular: FluentIcon;
export declare const CalendarCheckmark16Filled: FluentIcon;
export declare const CalendarCheckmark16Color: FluentIcon;
export declare const CalendarCheckmark20Regular: FluentIcon;
export declare const CalendarCheckmark20Filled: FluentIcon;
export declare const CalendarCheckmark20Color: FluentIcon;
export declare const CalendarCheckmark24Regular: FluentIcon;
export declare const CalendarCheckmark24Filled: FluentIcon;
export declare const CalendarCheckmark24Color: FluentIcon;
export declare const CalendarCheckmark28Regular: FluentIcon;
export declare const CalendarCheckmark28Filled: FluentIcon;
export declare const CalendarCheckmark32Regular: FluentIcon;
export declare const CalendarCheckmark32Filled: FluentIcon;
export declare const CalendarCheckmark32Light: FluentIcon;
