import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const CheckboxColor: FluentIcon;
export declare const Checkbox1Regular: FluentIcon;
export declare const Checkbox1Filled: FluentIcon;
export declare const Checkbox2Regular: FluentIcon;
export declare const Checkbox2Filled: FluentIcon;
export declare const Checkbox16Color: FluentIcon;
export declare const Checkbox20Color: FluentIcon;
export declare const Checkbox24Color: FluentIcon;
export declare const Checkbox120Regular: FluentIcon;
export declare const Checkbox120Filled: FluentIcon;
export declare const Checkbox124Regular: FluentIcon;
export declare const Checkbox124Filled: FluentIcon;
export declare const Checkbox220Regular: FluentIcon;
export declare const Checkbox220Filled: FluentIcon;
export declare const Checkbox224Regular: FluentIcon;
export declare const Checkbox224Filled: FluentIcon;
