import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const ErrorCircleColor: FluentIcon;
export declare const ErrorCircleFilled: FluentIcon;
export declare const ErrorCircleRegular: FluentIcon;
export declare const ErrorCircle12Regular: FluentIcon;
export declare const ErrorCircle12Filled: FluentIcon;
export declare const ErrorCircle16Regular: FluentIcon;
export declare const ErrorCircle16Filled: FluentIcon;
export declare const ErrorCircle16Color: FluentIcon;
export declare const ErrorCircle20Regular: FluentIcon;
export declare const ErrorCircle20Filled: FluentIcon;
export declare const ErrorCircle20Color: FluentIcon;
export declare const ErrorCircle24Regular: FluentIcon;
export declare const ErrorCircle24Filled: FluentIcon;
export declare const ErrorCircle24Color: FluentIcon;
export declare const ErrorCircle48Regular: FluentIcon;
export declare const ErrorCircle48Filled: FluentIcon;
export declare const ErrorCircle48Color: FluentIcon;
