import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const FormColor: FluentIcon;
export declare const FormFilled: FluentIcon;
export declare const FormRegular: FluentIcon;
export declare const Form20Regular: FluentIcon;
export declare const Form20Filled: FluentIcon;
export declare const Form20Color: FluentIcon;
export declare const Form24Regular: FluentIcon;
export declare const Form24Filled: FluentIcon;
export declare const Form24Color: FluentIcon;
export declare const Form28Regular: FluentIcon;
export declare const Form28Filled: FluentIcon;
export declare const Form28Color: FluentIcon;
export declare const Form48Regular: FluentIcon;
export declare const Form48Filled: FluentIcon;
export declare const Form48Color: FluentIcon;
