import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const GiftColor: FluentIcon;
export declare const GiftFilled: FluentIcon;
export declare const GiftRegular: FluentIcon;
export declare const Gift16Regular: FluentIcon;
export declare const Gift16Filled: FluentIcon;
export declare const Gift16Color: FluentIcon;
export declare const Gift20Regular: FluentIcon;
export declare const Gift20Filled: FluentIcon;
export declare const Gift20Color: FluentIcon;
export declare const Gift24Regular: FluentIcon;
export declare const Gift24Filled: FluentIcon;
export declare const Gift24Color: FluentIcon;
