import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const LinkMultipleColor: FluentIcon;
export declare const LinkMultipleFilled: FluentIcon;
export declare const LinkMultipleRegular: FluentIcon;
export declare const LinkMultiple16Regular: FluentIcon;
export declare const LinkMultiple16Filled: FluentIcon;
export declare const LinkMultiple16Color: FluentIcon;
export declare const LinkMultiple20Regular: FluentIcon;
export declare const LinkMultiple20Filled: FluentIcon;
export declare const LinkMultiple20Color: FluentIcon;
export declare const LinkMultiple24Regular: FluentIcon;
export declare const LinkMultiple24Filled: FluentIcon;
export declare const LinkMultiple24Color: FluentIcon;
