import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const PlanetColor: FluentIcon;
export declare const PlanetFilled: FluentIcon;
export declare const PlanetRegular: FluentIcon;
export declare const Planet16Regular: FluentIcon;
export declare const Planet16Filled: FluentIcon;
export declare const Planet16Color: FluentIcon;
export declare const Planet20Regular: FluentIcon;
export declare const Planet20Filled: FluentIcon;
export declare const Planet20Color: FluentIcon;
export declare const Planet24Regular: FluentIcon;
export declare const Planet24Filled: FluentIcon;
export declare const Planet24Color: FluentIcon;
export declare const Planet32Regular: FluentIcon;
export declare const Planet32Filled: FluentIcon;
export declare const Planet32Color: FluentIcon;
