import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const RibbonColor: FluentIcon;
export declare const RibbonFilled: FluentIcon;
export declare const RibbonRegular: FluentIcon;
export declare const Ribbon12Regular: FluentIcon;
export declare const Ribbon12Filled: FluentIcon;
export declare const Ribbon16Regular: FluentIcon;
export declare const Ribbon16Filled: FluentIcon;
export declare const Ribbon16Color: FluentIcon;
export declare const Ribbon20Regular: FluentIcon;
export declare const Ribbon20Filled: FluentIcon;
export declare const Ribbon20Color: FluentIcon;
export declare const Ribbon24Regular: FluentIcon;
export declare const Ribbon24Filled: FluentIcon;
export declare const Ribbon24Color: FluentIcon;
export declare const Ribbon32Regular: FluentIcon;
export declare const Ribbon32Filled: FluentIcon;
export declare const Ribbon32Color: FluentIcon;
