import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const SendClockColor: FluentIcon;
export declare const SendClockFilled: FluentIcon;
export declare const SendClockRegular: FluentIcon;
export declare const SendClock20Regular: FluentIcon;
export declare const SendClock20Filled: FluentIcon;
export declare const SendClock20Color: FluentIcon;
export declare const SendClock24Regular: FluentIcon;
export declare const SendClock24Filled: FluentIcon;
export declare const SendClock24Color: FluentIcon;
export declare const SendClock28Regular: FluentIcon;
export declare const SendClock28Filled: FluentIcon;
export declare const SendClock32Regular: FluentIcon;
export declare const SendClock32Filled: FluentIcon;
export declare const SendClock32Light: FluentIcon;
export declare const SendClock32Color: FluentIcon;
