import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const ShareAndroidColor: FluentIcon;
export declare const ShareAndroidFilled: FluentIcon;
export declare const ShareAndroidRegular: FluentIcon;
export declare const ShareAndroid16Regular: FluentIcon;
export declare const ShareAndroid16Filled: FluentIcon;
export declare const ShareAndroid16Color: FluentIcon;
export declare const ShareAndroid20Regular: FluentIcon;
export declare const ShareAndroid20Filled: FluentIcon;
export declare const ShareAndroid20Color: FluentIcon;
export declare const ShareAndroid24Regular: FluentIcon;
export declare const ShareAndroid24Filled: FluentIcon;
export declare const ShareAndroid24Color: FluentIcon;
export declare const ShareAndroid32Regular: FluentIcon;
export declare const ShareAndroid32Filled: FluentIcon;
export declare const ShareAndroid32Color: FluentIcon;
