import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const TextColorFilled: FluentIcon;
export declare const TextColorRegular: FluentIcon;
export declare const Text12Regular: FluentIcon;
export declare const Text12Filled: FluentIcon;
export declare const Text16Regular: FluentIcon;
export declare const TextColor16Regular: FluentIcon;
export declare const Text16Filled: FluentIcon;
export declare const TextColor16Filled: FluentIcon;
export declare const TextColor20Regular: FluentIcon;
export declare const TextColor20Filled: FluentIcon;
export declare const TextColor24Regular: FluentIcon;
export declare const TextColor24Filled: FluentIcon;
export declare const Text32Regular: FluentIcon;
export declare const Text32Filled: FluentIcon;
export declare const Text32Light: FluentIcon;
