import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const BoardColor: FluentIcon;
export declare const BoardFilled: FluentIcon;
export declare const BoardRegular: FluentIcon;
export declare const Board16Regular: FluentIcon;
export declare const Board16Filled: FluentIcon;
export declare const Board16Color: FluentIcon;
export declare const Board20Regular: FluentIcon;
export declare const Board20Filled: FluentIcon;
export declare const Board20Color: FluentIcon;
export declare const Board24Regular: FluentIcon;
export declare const Board24Filled: FluentIcon;
export declare const Board24Color: FluentIcon;
export declare const Board28Regular: FluentIcon;
export declare const Board28Filled: FluentIcon;
export declare const Board28Color: FluentIcon;
