import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const CalendarClockColor: FluentIcon;
export declare const CalendarClockFilled: FluentIcon;
export declare const CalendarClockRegular: FluentIcon;
export declare const CalendarClock16Regular: FluentIcon;
export declare const CalendarClock16Filled: FluentIcon;
export declare const CalendarClock16Color: FluentIcon;
export declare const CalendarClock20Regular: FluentIcon;
export declare const CalendarClock20Filled: FluentIcon;
export declare const CalendarClock20Color: FluentIcon;
export declare const CalendarClock24Regular: FluentIcon;
export declare const CalendarClock24Filled: FluentIcon;
export declare const CalendarClock24Color: FluentIcon;
export declare const CalendarClock32Regular: FluentIcon;
export declare const CalendarClock32Filled: FluentIcon;
export declare const CalendarClock32Light: FluentIcon;
