import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const CalendarCancelColor: FluentIcon;
export declare const CalendarCancelFilled: FluentIcon;
export declare const CalendarCancelRegular: FluentIcon;
export declare const CalendarCancel16Regular: FluentIcon;
export declare const CalendarCancel16Filled: FluentIcon;
export declare const CalendarCancel16Color: FluentIcon;
export declare const CalendarCancel20Regular: FluentIcon;
export declare const CalendarCancel20Filled: FluentIcon;
export declare const CalendarCancel20Color: FluentIcon;
export declare const CalendarCancel24Regular: FluentIcon;
export declare const CalendarCancel24Filled: FluentIcon;
export declare const CalendarCancel24Color: FluentIcon;
