import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const ChatMultipleColor: FluentIcon;
export declare const ChatMultipleFilled: FluentIcon;
export declare const ChatMultipleRegular: FluentIcon;
export declare const ChatMultiple16Regular: FluentIcon;
export declare const ChatMultiple16Filled: FluentIcon;
export declare const ChatMultiple16Color: FluentIcon;
export declare const ChatMultiple20Regular: FluentIcon;
export declare const ChatMultiple20Filled: FluentIcon;
export declare const ChatMultiple20Color: FluentIcon;
export declare const ChatMultiple24Regular: FluentIcon;
export declare const ChatMultiple24Filled: FluentIcon;
export declare const ChatMultiple24Color: FluentIcon;
export declare const ChatMultiple28Regular: FluentIcon;
export declare const ChatMultiple28Filled: FluentIcon;
export declare const ChatMultiple32Regular: FluentIcon;
export declare const ChatMultiple32Filled: FluentIcon;
