import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const GiftCardColor: FluentIcon;
export declare const GiftCardFilled: FluentIcon;
export declare const GiftCardRegular: FluentIcon;
export declare const GiftCard16Regular: FluentIcon;
export declare const GiftCard16Filled: FluentIcon;
export declare const GiftCard16Color: FluentIcon;
export declare const GiftCard20Regular: FluentIcon;
export declare const GiftCard20Filled: FluentIcon;
export declare const GiftCard20Color: FluentIcon;
export declare const GiftCard24Regular: FluentIcon;
export declare const GiftCard24Filled: FluentIcon;
export declare const GiftCard24Color: FluentIcon;
