import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const ListBarColor: FluentIcon;
export declare const ListBarFilled: FluentIcon;
export declare const ListBarRegular: FluentIcon;
export declare const ListBar16Regular: FluentIcon;
export declare const ListBar16Filled: FluentIcon;
export declare const ListBar16Color: FluentIcon;
export declare const ListBar20Regular: FluentIcon;
export declare const ListBar20Filled: FluentIcon;
export declare const ListBar20Color: FluentIcon;
export declare const ListBar24Regular: FluentIcon;
export declare const ListBar24Filled: FluentIcon;
export declare const ListBar24Color: FluentIcon;
export declare const ListBar32Regular: FluentIcon;
export declare const ListBar32Filled: FluentIcon;
export declare const ListBar32Color: FluentIcon;
