import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const MailReadFilled: FluentIcon;
export declare const MailReadRegular: FluentIcon;
export declare const MailRead16Regular: FluentIcon;
export declare const MailRead16Filled: FluentIcon;
export declare const MailRead20Regular: FluentIcon;
export declare const MailRead20Filled: FluentIcon;
export declare const MailRead24Regular: FluentIcon;
export declare const MailRead24Filled: FluentIcon;
export declare const MailRead28Regular: FluentIcon;
export declare const MailRead28Filled: FluentIcon;
export declare const MailRead32Regular: FluentIcon;
export declare const MailRead32Filled: FluentIcon;
export declare const MailRead32Light: FluentIcon;
export declare const MailRead48Regular: FluentIcon;
export declare const MailRead48Filled: FluentIcon;
