import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const PersonAvailableColor: FluentIcon;
export declare const PersonAvailableFilled: FluentIcon;
export declare const PersonAvailableRegular: FluentIcon;
export declare const PersonAvailable16Regular: FluentIcon;
export declare const PersonAvailable16Filled: FluentIcon;
export declare const PersonAvailable16Color: FluentIcon;
export declare const PersonAvailable20Regular: FluentIcon;
export declare const PersonAvailable20Filled: FluentIcon;
export declare const PersonAvailable20Color: FluentIcon;
export declare const PersonAvailable24Regular: FluentIcon;
export declare const PersonAvailable24Filled: FluentIcon;
export declare const PersonAvailable24Color: FluentIcon;
export declare const PersonAvailable32Light: FluentIcon;
