import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const SlideAddFilled: FluentIcon;
export declare const SlideAddRegular: FluentIcon;
export declare const SlideAdd16Regular: FluentIcon;
export declare const SlideAdd16Filled: FluentIcon;
export declare const SlideAdd20Regular: FluentIcon;
export declare const SlideAdd20Filled: FluentIcon;
export declare const SlideAdd24Regular: FluentIcon;
export declare const SlideAdd24Filled: FluentIcon;
export declare const SlideAdd28Regular: FluentIcon;
export declare const SlideAdd28Filled: FluentIcon;
export declare const SlideAdd32Regular: FluentIcon;
export declare const SlideAdd32Filled: FluentIcon;
export declare const SlideAdd48Regular: FluentIcon;
export declare const SlideAdd48Filled: FluentIcon;
