import type { FluentIcon } from '../../utils/createFluentIcon';
export declare const WrenchScrewdriverColor: FluentIcon;
export declare const WrenchScrewdriverFilled: FluentIcon;
export declare const WrenchScrewdriverRegular: FluentIcon;
export declare const WrenchScrewdriver20Regular: FluentIcon;
export declare const WrenchScrewdriver20Filled: FluentIcon;
export declare const WrenchScrewdriver20Color: FluentIcon;
export declare const WrenchScrewdriver24Regular: FluentIcon;
export declare const WrenchScrewdriver24Filled: FluentIcon;
export declare const WrenchScrewdriver24Color: FluentIcon;
export declare const WrenchScrewdriver28Regular: FluentIcon;
export declare const WrenchScrewdriver28Filled: FluentIcon;
export declare const WrenchScrewdriver32Regular: FluentIcon;
export declare const WrenchScrewdriver32Filled: FluentIcon;
export declare const WrenchScrewdriver32Light: FluentIcon;
export declare const WrenchScrewdriver32Color: FluentIcon;
