"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AlertFilled = ( /*#__PURE__*/createFluentFontIcon("AlertFilled", "", 2, undefined));
export const AlertRegular = ( /*#__PURE__*/createFluentFontIcon("AlertRegular", "", 2, undefined));
export const Alert12Regular = ( /*#__PURE__*/createFluentFontIcon("Alert12Regular", "", 1, 12));
export const Alert12Filled = ( /*#__PURE__*/createFluentFontIcon("Alert12Filled", "", 0, 12));
export const Alert16Regular = ( /*#__PURE__*/createFluentFontIcon("Alert16Regular", "", 1, 16));
export const Alert16Filled = ( /*#__PURE__*/createFluentFontIcon("Alert16Filled", "", 0, 16));
export const Alert20Regular = ( /*#__PURE__*/createFluentFontIcon("Alert20Regular", "", 1, 20));
export const Alert20Filled = ( /*#__PURE__*/createFluentFontIcon("Alert20Filled", "", 0, 20));
export const Alert24Regular = ( /*#__PURE__*/createFluentFontIcon("Alert24Regular", "", 1, 24));
export const Alert24Filled = ( /*#__PURE__*/createFluentFontIcon("Alert24Filled", "", 0, 24));
export const Alert28Regular = ( /*#__PURE__*/createFluentFontIcon("Alert28Regular", "", 1, 28));
export const Alert28Filled = ( /*#__PURE__*/createFluentFontIcon("Alert28Filled", "", 0, 28));
export const Alert32Regular = ( /*#__PURE__*/createFluentFontIcon("Alert32Regular", "", 1, 32));
export const Alert32Filled = ( /*#__PURE__*/createFluentFontIcon("Alert32Filled", "", 0, 32));
export const Alert32Light = ( /*#__PURE__*/createFluentFontIcon("Alert32Light", "", 3, 32));
export const Alert48Regular = ( /*#__PURE__*/createFluentFontIcon("Alert48Regular", "", 1, 48));
export const Alert48Filled = ( /*#__PURE__*/createFluentFontIcon("Alert48Filled", "", 0, 48));
