"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AlertBadgeFilled = ( /*#__PURE__*/createFluentFontIcon("AlertBadgeFilled", "", 2, undefined));
export const AlertBadgeRegular = ( /*#__PURE__*/createFluentFontIcon("AlertBadgeRegular", "", 2, undefined));
export const AlertBadge16Regular = ( /*#__PURE__*/createFluentFontIcon("AlertBadge16Regular", "", 1, 16));
export const AlertBadge16Filled = ( /*#__PURE__*/createFluentFontIcon("AlertBadge16Filled", "", 0, 16));
export const AlertBadge20Regular = ( /*#__PURE__*/createFluentFontIcon("AlertBadge20Regular", "", 1, 20));
export const AlertBadge20Filled = ( /*#__PURE__*/createFluentFontIcon("AlertBadge20Filled", "", 0, 20));
export const AlertBadge24Regular = ( /*#__PURE__*/createFluentFontIcon("AlertBadge24Regular", "", 1, 24));
export const AlertBadge24Filled = ( /*#__PURE__*/createFluentFontIcon("AlertBadge24Filled", "", 0, 24));
export const AlertBadge32Regular = ( /*#__PURE__*/createFluentFontIcon("AlertBadge32Regular", "󰟴", 1, 32));
export const AlertBadge32Filled = ( /*#__PURE__*/createFluentFontIcon("AlertBadge32Filled", "󰡱", 0, 32));
