"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AlertOffFilled = ( /*#__PURE__*/createFluentFontIcon("AlertOffFilled", "", 2, undefined));
export const AlertOffRegular = ( /*#__PURE__*/createFluentFontIcon("AlertOffRegular", "", 2, undefined));
export const AlertOff16Regular = ( /*#__PURE__*/createFluentFontIcon("AlertOff16Regular", "", 1, 16));
export const AlertOff16Filled = ( /*#__PURE__*/createFluentFontIcon("AlertOff16Filled", "", 0, 16));
export const AlertOff20Regular = ( /*#__PURE__*/createFluentFontIcon("AlertOff20Regular", "", 1, 20));
export const AlertOff20Filled = ( /*#__PURE__*/createFluentFontIcon("AlertOff20Filled", "", 0, 20));
export const AlertOff24Regular = ( /*#__PURE__*/createFluentFontIcon("AlertOff24Regular", "", 1, 24));
export const AlertOff24Filled = ( /*#__PURE__*/createFluentFontIcon("AlertOff24Filled", "", 0, 24));
export const AlertOff28Regular = ( /*#__PURE__*/createFluentFontIcon("AlertOff28Regular", "", 1, 28));
export const AlertOff28Filled = ( /*#__PURE__*/createFluentFontIcon("AlertOff28Filled", "", 0, 28));
