"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AlignLeftFilled = ( /*#__PURE__*/createFluentFontIcon("AlignLeftFilled", "", 2, undefined));
export const AlignLeftRegular = ( /*#__PURE__*/createFluentFontIcon("AlignLeftRegular", "", 2, undefined));
export const AlignLeft16Regular = ( /*#__PURE__*/createFluentFontIcon("AlignLeft16Regular", "", 1, 16));
export const AlignLeft16Filled = ( /*#__PURE__*/createFluentFontIcon("AlignLeft16Filled", "", 0, 16));
export const AlignLeft20Regular = ( /*#__PURE__*/createFluentFontIcon("AlignLeft20Regular", "", 1, 20));
export const AlignLeft20Filled = ( /*#__PURE__*/createFluentFontIcon("AlignLeft20Filled", "", 0, 20));
export const AlignLeft24Regular = ( /*#__PURE__*/createFluentFontIcon("AlignLeft24Regular", "", 1, 24));
export const AlignLeft24Filled = ( /*#__PURE__*/createFluentFontIcon("AlignLeft24Filled", "", 0, 24));
export const AlignLeft28Regular = ( /*#__PURE__*/createFluentFontIcon("AlignLeft28Regular", "", 1, 28));
export const AlignLeft28Filled = ( /*#__PURE__*/createFluentFontIcon("AlignLeft28Filled", "", 0, 28));
export const AlignLeft32Regular = ( /*#__PURE__*/createFluentFontIcon("AlignLeft32Regular", "", 1, 32));
export const AlignLeft32Filled = ( /*#__PURE__*/createFluentFontIcon("AlignLeft32Filled", "", 0, 32));
export const AlignLeft48Regular = ( /*#__PURE__*/createFluentFontIcon("AlignLeft48Regular", "", 1, 48));
export const AlignLeft48Filled = ( /*#__PURE__*/createFluentFontIcon("AlignLeft48Filled", "", 0, 48));
