"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AnimalCatFilled = ( /*#__PURE__*/createFluentFontIcon("AnimalCatFilled", "", 2, undefined));
export const AnimalCatRegular = ( /*#__PURE__*/createFluentFontIcon("AnimalCatRegular", "", 2, undefined));
export const AnimalCat16Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalCat16Regular", "", 1, 16));
export const AnimalCat16Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalCat16Filled", "", 0, 16));
export const AnimalCat20Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalCat20Regular", "", 1, 20));
export const AnimalCat20Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalCat20Filled", "", 0, 20));
export const AnimalCat24Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalCat24Regular", "", 1, 24));
export const AnimalCat24Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalCat24Filled", "", 0, 24));
export const AnimalCat28Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalCat28Regular", "", 1, 28));
export const AnimalCat28Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalCat28Filled", "", 0, 28));
