"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AnimalTurtleFilled = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtleFilled", "", 2, undefined));
export const AnimalTurtleRegular = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtleRegular", "", 2, undefined));
export const AnimalTurtle16Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle16Regular", "", 1, 16));
export const AnimalTurtle16Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle16Filled", "", 0, 16));
export const AnimalTurtle20Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle20Regular", "", 1, 20));
export const AnimalTurtle20Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle20Filled", "", 0, 20));
export const AnimalTurtle24Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle24Regular", "", 1, 24));
export const AnimalTurtle24Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle24Filled", "", 0, 24));
export const AnimalTurtle28Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle28Regular", "", 1, 28));
export const AnimalTurtle28Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalTurtle28Filled", "", 0, 28));
