"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AnimalRabbitFilled = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbitFilled", "", 2, undefined));
export const AnimalRabbitRegular = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbitRegular", "", 2, undefined));
export const AnimalRabbit16Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit16Regular", "", 1, 16));
export const AnimalRabbit16Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit16Filled", "", 0, 16));
export const AnimalRabbit20Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit20Regular", "", 1, 20));
export const AnimalRabbit20Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit20Filled", "", 0, 20));
export const AnimalRabbit24Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit24Regular", "", 1, 24));
export const AnimalRabbit24Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit24Filled", "", 0, 24));
export const AnimalRabbit28Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit28Regular", "", 1, 28));
export const AnimalRabbit28Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit28Filled", "", 0, 28));
export const AnimalRabbit32Regular = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit32Regular", "", 1, 32));
export const AnimalRabbit32Filled = ( /*#__PURE__*/createFluentFontIcon("AnimalRabbit32Filled", "", 0, 32));
