"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const AppFolderFilled = ( /*#__PURE__*/createFluentFontIcon("AppFolderFilled", "", 2, undefined));
export const AppFolderRegular = ( /*#__PURE__*/createFluentFontIcon("AppFolderRegular", "", 2, undefined));
export const AppFolder16Regular = ( /*#__PURE__*/createFluentFontIcon("AppFolder16Regular", "", 1, 16));
export const AppFolder16Filled = ( /*#__PURE__*/createFluentFontIcon("AppFolder16Filled", "", 0, 16));
export const AppFolder20Regular = ( /*#__PURE__*/createFluentFontIcon("AppFolder20Regular", "", 1, 20));
export const AppFolder20Filled = ( /*#__PURE__*/createFluentFontIcon("AppFolder20Filled", "", 0, 20));
export const AppFolder24Regular = ( /*#__PURE__*/createFluentFontIcon("AppFolder24Regular", "", 1, 24));
export const AppFolder24Filled = ( /*#__PURE__*/createFluentFontIcon("AppFolder24Filled", "", 0, 24));
export const AppFolder28Regular = ( /*#__PURE__*/createFluentFontIcon("AppFolder28Regular", "", 1, 28));
export const AppFolder28Filled = ( /*#__PURE__*/createFluentFontIcon("AppFolder28Filled", "", 0, 28));
export const AppFolder32Regular = ( /*#__PURE__*/createFluentFontIcon("AppFolder32Regular", "", 1, 32));
export const AppFolder32Filled = ( /*#__PURE__*/createFluentFontIcon("AppFolder32Filled", "", 0, 32));
export const AppFolder32Light = ( /*#__PURE__*/createFluentFontIcon("AppFolder32Light", "", 3, 32));
export const AppFolder48Regular = ( /*#__PURE__*/createFluentFontIcon("AppFolder48Regular", "", 1, 48));
export const AppFolder48Filled = ( /*#__PURE__*/createFluentFontIcon("AppFolder48Filled", "", 0, 48));
