"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArchiveFilled = ( /*#__PURE__*/createFluentFontIcon("ArchiveFilled", "", 2, undefined));
export const ArchiveRegular = ( /*#__PURE__*/createFluentFontIcon("ArchiveRegular", "", 2, undefined));
export const Archive16Regular = ( /*#__PURE__*/createFluentFontIcon("Archive16Regular", "", 1, 16));
export const Archive16Filled = ( /*#__PURE__*/createFluentFontIcon("Archive16Filled", "", 0, 16));
export const Archive20Regular = ( /*#__PURE__*/createFluentFontIcon("Archive20Regular", "", 1, 20));
export const Archive20Filled = ( /*#__PURE__*/createFluentFontIcon("Archive20Filled", "", 0, 20));
export const Archive24Regular = ( /*#__PURE__*/createFluentFontIcon("Archive24Regular", "", 1, 24));
export const Archive24Filled = ( /*#__PURE__*/createFluentFontIcon("Archive24Filled", "", 0, 24));
export const Archive28Regular = ( /*#__PURE__*/createFluentFontIcon("Archive28Regular", "", 1, 28));
export const Archive28Filled = ( /*#__PURE__*/createFluentFontIcon("Archive28Filled", "", 0, 28));
export const Archive32Regular = ( /*#__PURE__*/createFluentFontIcon("Archive32Regular", "", 1, 32));
export const Archive32Filled = ( /*#__PURE__*/createFluentFontIcon("Archive32Filled", "", 0, 32));
export const Archive32Light = ( /*#__PURE__*/createFluentFontIcon("Archive32Light", "", 3, 32));
export const Archive48Regular = ( /*#__PURE__*/createFluentFontIcon("Archive48Regular", "", 1, 48));
export const Archive48Filled = ( /*#__PURE__*/createFluentFontIcon("Archive48Filled", "", 0, 48));
