"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowStepInFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowStepInFilled", "", 2, undefined));
export const ArrowStepInRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowStepInRegular", "", 2, undefined));
export const ArrowStepIn12Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn12Regular", "", 1, 12));
export const ArrowStepIn12Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn12Filled", "", 0, 12));
export const ArrowStepIn16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn16Regular", "", 1, 16));
export const ArrowStepIn16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn16Filled", "", 0, 16));
export const ArrowStepIn20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn20Regular", "", 1, 20));
export const ArrowStepIn20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn20Filled", "", 0, 20));
export const ArrowStepIn24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn24Regular", "", 1, 24));
export const ArrowStepIn24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn24Filled", "", 0, 24));
export const ArrowStepIn28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn28Regular", "", 1, 28));
export const ArrowStepIn28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowStepIn28Filled", "", 0, 28));
