"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowImportFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowImportFilled", "", 2, undefined, { flipInRtl: true }));
export const ArrowImportRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowImportRegular", "", 2, undefined, { flipInRtl: true }));
export const ArrowImport16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowImport16Regular", "󰎄", 1, 16, { flipInRtl: true }));
export const ArrowImport16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowImport16Filled", "󰎗", 0, 16, { flipInRtl: true }));
export const ArrowImport20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowImport20Regular", "", 1, 20, { flipInRtl: true }));
export const ArrowImport20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowImport20Filled", "", 0, 20, { flipInRtl: true }));
export const ArrowImport24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowImport24Regular", "", 1, 24, { flipInRtl: true }));
export const ArrowImport24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowImport24Filled", "", 0, 24, { flipInRtl: true }));
