"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowBounceFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounceFilled", "", 2, undefined));
export const ArrowBounceRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounceRegular", "", 2, undefined));
export const ArrowBounce12Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce12Regular", "󰝀", 1, 12));
export const ArrowBounce12Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce12Filled", "󰞽", 0, 12));
export const ArrowBounce16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce16Regular", "", 1, 16));
export const ArrowBounce16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce16Filled", "", 0, 16));
export const ArrowBounce20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce20Regular", "", 1, 20));
export const ArrowBounce20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce20Filled", "", 0, 20));
export const ArrowBounce24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce24Regular", "", 1, 24));
export const ArrowBounce24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce24Filled", "", 0, 24));
export const ArrowBounce28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce28Regular", "󰝁", 1, 28));
export const ArrowBounce28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce28Filled", "󰞾", 0, 28));
export const ArrowBounce48Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce48Regular", "󰝂", 1, 48));
export const ArrowBounce48Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowBounce48Filled", "󰞿", 0, 48));
