"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowSwapFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowSwapFilled", "", 2, undefined, { flipInRtl: true }));
export const ArrowSwapRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowSwapRegular", "", 2, undefined, { flipInRtl: true }));
export const ArrowSwap16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap16Regular", "󰊤", 1, 16, { flipInRtl: true }));
export const ArrowSwap16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap16Filled", "󰊷", 0, 16, { flipInRtl: true }));
export const ArrowSwap20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap20Regular", "", 1, 20, { flipInRtl: true }));
export const ArrowSwap20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap20Filled", "", 0, 20, { flipInRtl: true }));
export const ArrowSwap24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap24Regular", "", 1, 24, { flipInRtl: true }));
export const ArrowSwap24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap24Filled", "", 0, 24, { flipInRtl: true }));
export const ArrowSwap28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap28Regular", "󰊥", 1, 28, { flipInRtl: true }));
export const ArrowSwap28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowSwap28Filled", "󰊸", 0, 28, { flipInRtl: true }));
