"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowExpandFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowExpandFilled", "", 2, undefined));
export const ArrowExpandRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowExpandRegular", "", 2, undefined));
export const ArrowExpand16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand16Regular", "󰎂", 1, 16));
export const ArrowExpand16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand16Filled", "󰎕", 0, 16));
export const ArrowExpand20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand20Regular", "", 1, 20));
export const ArrowExpand20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand20Filled", "", 0, 20));
export const ArrowExpand24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand24Regular", "", 1, 24));
export const ArrowExpand24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand24Filled", "", 0, 24));
export const ArrowExpand28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand28Regular", "󰧔", 1, 28));
export const ArrowExpand28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowExpand28Filled", "󰩑", 0, 28));
