"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowUpFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowUpFilled", "", 2, undefined, { flipInRtl: true }));
export const ArrowUpRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowUpRegular", "", 2, undefined, { flipInRtl: true }));
export const ArrowUp12Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp12Regular", "", 1, 12, { flipInRtl: true }));
export const ArrowUp12Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp12Filled", "", 0, 12, { flipInRtl: true }));
export const ArrowUp16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp16Regular", "", 1, 16, { flipInRtl: true }));
export const ArrowUp16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp16Filled", "", 0, 16, { flipInRtl: true }));
export const ArrowUp20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp20Regular", "", 1, 20, { flipInRtl: true }));
export const ArrowUp20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp20Filled", "", 0, 20, { flipInRtl: true }));
export const ArrowUp24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp24Regular", "", 1, 24, { flipInRtl: true }));
export const ArrowUp24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp24Filled", "", 0, 24, { flipInRtl: true }));
export const ArrowUp28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp28Regular", "", 1, 28, { flipInRtl: true }));
export const ArrowUp28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp28Filled", "", 0, 28, { flipInRtl: true }));
export const ArrowUp32Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp32Regular", "", 1, 32, { flipInRtl: true }));
export const ArrowUp32Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp32Filled", "", 0, 32, { flipInRtl: true }));
export const ArrowUp48Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUp48Regular", "", 1, 48, { flipInRtl: true }));
export const ArrowUp48Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUp48Filled", "", 0, 48, { flipInRtl: true }));
