"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowUpLeftFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeftFilled", "", 2, undefined));
export const ArrowUpLeftRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeftRegular", "", 2, undefined));
export const ArrowUpLeft16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft16Regular", "", 1, 16));
export const ArrowUpLeft16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft16Filled", "", 0, 16));
export const ArrowUpLeft20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft20Regular", "", 1, 20));
export const ArrowUpLeft20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft20Filled", "", 0, 20));
export const ArrowUpLeft24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft24Regular", "", 1, 24));
export const ArrowUpLeft24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft24Filled", "", 0, 24));
export const ArrowUpLeft48Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft48Regular", "", 1, 48));
export const ArrowUpLeft48Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUpLeft48Filled", "", 0, 48));
