"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowUndoFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndoFilled", "", 2, undefined, { flipInRtl: true }));
export const ArrowUndoRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndoRegular", "", 2, undefined, { flipInRtl: true }));
export const ArrowUndo16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo16Regular", "", 1, 16, { flipInRtl: true }));
export const ArrowUndo16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo16Filled", "", 0, 16, { flipInRtl: true }));
export const ArrowUndo20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo20Regular", "", 1, 20, { flipInRtl: true }));
export const ArrowUndo20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo20Filled", "", 0, 20, { flipInRtl: true }));
export const ArrowUndo24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo24Regular", "", 1, 24, { flipInRtl: true }));
export const ArrowUndo24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo24Filled", "", 0, 24, { flipInRtl: true }));
export const ArrowUndo28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo28Regular", "", 1, 28, { flipInRtl: true }));
export const ArrowUndo28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo28Filled", "", 0, 28, { flipInRtl: true }));
export const ArrowUndo32Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo32Regular", "", 1, 32, { flipInRtl: true }));
export const ArrowUndo32Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo32Filled", "", 0, 32, { flipInRtl: true }));
export const ArrowUndo32Light = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo32Light", "", 3, 32));
export const ArrowUndo48Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo48Regular", "", 1, 48, { flipInRtl: true }));
export const ArrowUndo48Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowUndo48Filled", "", 0, 48, { flipInRtl: true }));
