"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ArrowShuffleFilled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffleFilled", "", 2, undefined));
export const ArrowShuffleRegular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffleRegular", "", 2, undefined));
export const ArrowShuffle16Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle16Regular", "", 1, 16));
export const ArrowShuffle16Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle16Filled", "", 0, 16));
export const ArrowShuffle20Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle20Regular", "", 1, 20));
export const ArrowShuffle20Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle20Filled", "", 0, 20));
export const ArrowShuffle24Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle24Regular", "", 1, 24));
export const ArrowShuffle24Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle24Filled", "", 0, 24));
export const ArrowShuffle28Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle28Regular", "", 1, 28));
export const ArrowShuffle28Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle28Filled", "", 0, 28));
export const ArrowShuffle32Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle32Regular", "", 1, 32));
export const ArrowShuffle32Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle32Filled", "", 0, 32));
export const ArrowShuffle48Regular = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle48Regular", "", 1, 48));
export const ArrowShuffle48Filled = ( /*#__PURE__*/createFluentFontIcon("ArrowShuffle48Filled", "", 0, 48));
