"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BackpackFilled = ( /*#__PURE__*/createFluentFontIcon("BackpackFilled", "", 2, undefined));
export const BackpackRegular = ( /*#__PURE__*/createFluentFontIcon("BackpackRegular", "", 2, undefined));
export const Backpack12Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack12Regular", "", 1, 12));
export const Backpack12Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack12Filled", "", 0, 12));
export const Backpack16Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack16Regular", "", 1, 16));
export const Backpack16Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack16Filled", "", 0, 16));
export const Backpack20Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack20Regular", "", 1, 20));
export const Backpack20Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack20Filled", "", 0, 20));
export const Backpack24Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack24Regular", "", 1, 24));
export const Backpack24Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack24Filled", "", 0, 24));
export const Backpack28Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack28Regular", "", 1, 28));
export const Backpack28Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack28Filled", "", 0, 28));
export const Backpack32Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack32Regular", "", 1, 32));
export const Backpack32Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack32Filled", "", 0, 32));
export const Backpack48Regular = ( /*#__PURE__*/createFluentFontIcon("Backpack48Regular", "", 1, 48));
export const Backpack48Filled = ( /*#__PURE__*/createFluentFontIcon("Backpack48Filled", "", 0, 48));
