"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BackpackAddFilled = ( /*#__PURE__*/createFluentFontIcon("BackpackAddFilled", "", 2, undefined));
export const BackpackAddRegular = ( /*#__PURE__*/createFluentFontIcon("BackpackAddRegular", "", 2, undefined));
export const BackpackAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd20Regular", "", 1, 20));
export const BackpackAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd20Filled", "", 0, 20));
export const BackpackAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd24Regular", "", 1, 24));
export const BackpackAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd24Filled", "", 0, 24));
export const BackpackAdd28Regular = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd28Regular", "", 1, 28));
export const BackpackAdd28Filled = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd28Filled", "", 0, 28));
export const BackpackAdd48Regular = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd48Regular", "", 1, 48));
export const BackpackAdd48Filled = ( /*#__PURE__*/createFluentFontIcon("BackpackAdd48Filled", "", 0, 48));
