"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BarcodeScannerFilled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScannerFilled", "", 2, undefined));
export const BarcodeScannerRegular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScannerRegular", "", 2, undefined));
export const BarcodeScanner16Regular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner16Regular", "󰥜", 1, 16));
export const BarcodeScanner16Filled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner16Filled", "󰧙", 0, 16));
export const BarcodeScanner20Regular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner20Regular", "", 1, 20));
export const BarcodeScanner20Filled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner20Filled", "", 0, 20));
export const BarcodeScanner24Regular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner24Regular", "", 1, 24));
export const BarcodeScanner24Filled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner24Filled", "", 0, 24));
export const BarcodeScanner28Regular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner28Regular", "󰥝", 1, 28));
export const BarcodeScanner28Filled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner28Filled", "󰧚", 0, 28));
export const BarcodeScanner32Regular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner32Regular", "󰥞", 1, 32));
export const BarcodeScanner32Filled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner32Filled", "󰧛", 0, 32));
export const BarcodeScanner48Regular = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner48Regular", "󰥟", 1, 48));
export const BarcodeScanner48Filled = ( /*#__PURE__*/createFluentFontIcon("BarcodeScanner48Filled", "󰧜", 0, 48));
