"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BinFullFilled = ( /*#__PURE__*/createFluentFontIcon("BinFullFilled", "", 2, undefined));
export const BinFullRegular = ( /*#__PURE__*/createFluentFontIcon("BinFullRegular", "", 2, undefined));
export const BinFull20Regular = ( /*#__PURE__*/createFluentFontIcon("BinFull20Regular", "", 1, 20));
export const BinFull20Filled = ( /*#__PURE__*/createFluentFontIcon("BinFull20Filled", "", 0, 20));
export const BinFull24Regular = ( /*#__PURE__*/createFluentFontIcon("BinFull24Regular", "", 1, 24));
export const BinFull24Filled = ( /*#__PURE__*/createFluentFontIcon("BinFull24Filled", "", 0, 24));
export const BinFull48Regular = ( /*#__PURE__*/createFluentFontIcon("BinFull48Regular", "󰚹", 1, 48));
export const BinFull48Filled = ( /*#__PURE__*/createFluentFontIcon("BinFull48Filled", "󰜶", 0, 48));
