"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BlurFilled = ( /*#__PURE__*/createFluentFontIcon("BlurFilled", "", 2, undefined));
export const BlurRegular = ( /*#__PURE__*/createFluentFontIcon("BlurRegular", "", 2, undefined));
export const Blur16Regular = ( /*#__PURE__*/createFluentFontIcon("Blur16Regular", "", 1, 16));
export const Blur16Filled = ( /*#__PURE__*/createFluentFontIcon("Blur16Filled", "", 0, 16));
export const Blur20Regular = ( /*#__PURE__*/createFluentFontIcon("Blur20Regular", "", 1, 20));
export const Blur20Filled = ( /*#__PURE__*/createFluentFontIcon("Blur20Filled", "", 0, 20));
export const Blur24Regular = ( /*#__PURE__*/createFluentFontIcon("Blur24Regular", "", 1, 24));
export const Blur24Filled = ( /*#__PURE__*/createFluentFontIcon("Blur24Filled", "", 0, 24));
export const Blur28Regular = ( /*#__PURE__*/createFluentFontIcon("Blur28Regular", "", 1, 28));
export const Blur28Filled = ( /*#__PURE__*/createFluentFontIcon("Blur28Filled", "", 0, 28));
