"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BoardFilled = ( /*#__PURE__*/createFluentFontIcon("BoardFilled", "", 2, undefined));
export const BoardRegular = ( /*#__PURE__*/createFluentFontIcon("BoardRegular", "", 2, undefined));
export const Board16Regular = ( /*#__PURE__*/createFluentFontIcon("Board16Regular", "", 1, 16));
export const Board16Filled = ( /*#__PURE__*/createFluentFontIcon("Board16Filled", "", 0, 16));
export const Board20Regular = ( /*#__PURE__*/createFluentFontIcon("Board20Regular", "", 1, 20));
export const Board20Filled = ( /*#__PURE__*/createFluentFontIcon("Board20Filled", "", 0, 20));
export const Board24Regular = ( /*#__PURE__*/createFluentFontIcon("Board24Regular", "", 1, 24));
export const Board24Filled = ( /*#__PURE__*/createFluentFontIcon("Board24Filled", "", 0, 24));
export const Board28Regular = ( /*#__PURE__*/createFluentFontIcon("Board28Regular", "", 1, 28));
export const Board28Filled = ( /*#__PURE__*/createFluentFontIcon("Board28Filled", "", 0, 28));
