"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BoardHeartFilled = ( /*#__PURE__*/createFluentFontIcon("BoardHeartFilled", "", 2, undefined));
export const BoardHeartRegular = ( /*#__PURE__*/createFluentFontIcon("BoardHeartRegular", "", 2, undefined));
export const BoardHeart16Regular = ( /*#__PURE__*/createFluentFontIcon("BoardHeart16Regular", "", 1, 16));
export const BoardHeart16Filled = ( /*#__PURE__*/createFluentFontIcon("BoardHeart16Filled", "", 0, 16));
export const BoardHeart20Regular = ( /*#__PURE__*/createFluentFontIcon("BoardHeart20Regular", "", 1, 20));
export const BoardHeart20Filled = ( /*#__PURE__*/createFluentFontIcon("BoardHeart20Filled", "", 0, 20));
export const BoardHeart24Regular = ( /*#__PURE__*/createFluentFontIcon("BoardHeart24Regular", "", 1, 24));
export const BoardHeart24Filled = ( /*#__PURE__*/createFluentFontIcon("BoardHeart24Filled", "", 0, 24));
