"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BookOpenFilled = ( /*#__PURE__*/createFluentFontIcon("BookOpenFilled", "", 2, undefined));
export const BookOpenRegular = ( /*#__PURE__*/createFluentFontIcon("BookOpenRegular", "", 2, undefined));
export const BookOpen16Regular = ( /*#__PURE__*/createFluentFontIcon("BookOpen16Regular", "", 1, 16));
export const BookOpen16Filled = ( /*#__PURE__*/createFluentFontIcon("BookOpen16Filled", "", 0, 16));
export const BookOpen20Regular = ( /*#__PURE__*/createFluentFontIcon("BookOpen20Regular", "", 1, 20));
export const BookOpen20Filled = ( /*#__PURE__*/createFluentFontIcon("BookOpen20Filled", "", 0, 20));
export const BookOpen24Regular = ( /*#__PURE__*/createFluentFontIcon("BookOpen24Regular", "", 1, 24));
export const BookOpen24Filled = ( /*#__PURE__*/createFluentFontIcon("BookOpen24Filled", "", 0, 24));
export const BookOpen28Regular = ( /*#__PURE__*/createFluentFontIcon("BookOpen28Regular", "", 1, 28));
export const BookOpen28Filled = ( /*#__PURE__*/createFluentFontIcon("BookOpen28Filled", "", 0, 28));
export const BookOpen32Regular = ( /*#__PURE__*/createFluentFontIcon("BookOpen32Regular", "", 1, 32));
export const BookOpen32Filled = ( /*#__PURE__*/createFluentFontIcon("BookOpen32Filled", "", 0, 32));
export const BookOpen48Regular = ( /*#__PURE__*/createFluentFontIcon("BookOpen48Regular", "", 1, 48));
export const BookOpen48Filled = ( /*#__PURE__*/createFluentFontIcon("BookOpen48Filled", "", 0, 48));
