"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BookToolboxFilled = ( /*#__PURE__*/createFluentFontIcon("BookToolboxFilled", "", 2, undefined));
export const BookToolboxRegular = ( /*#__PURE__*/createFluentFontIcon("BookToolboxRegular", "", 2, undefined));
export const BookToolbox16Regular = ( /*#__PURE__*/createFluentFontIcon("BookToolbox16Regular", "󰏘", 1, 16));
export const BookToolbox16Filled = ( /*#__PURE__*/createFluentFontIcon("BookToolbox16Filled", "󰏫", 0, 16));
export const BookToolbox20Regular = ( /*#__PURE__*/createFluentFontIcon("BookToolbox20Regular", "", 1, 20));
export const BookToolbox20Filled = ( /*#__PURE__*/createFluentFontIcon("BookToolbox20Filled", "", 0, 20));
export const BookToolbox24Regular = ( /*#__PURE__*/createFluentFontIcon("BookToolbox24Regular", "", 1, 24));
export const BookToolbox24Filled = ( /*#__PURE__*/createFluentFontIcon("BookToolbox24Filled", "", 0, 24));
