"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BookFilled = ( /*#__PURE__*/createFluentFontIcon("BookFilled", "", 2, undefined));
export const BookRegular = ( /*#__PURE__*/createFluentFontIcon("BookRegular", "", 2, undefined));
export const Book16Regular = ( /*#__PURE__*/createFluentFontIcon("Book16Regular", "󰎈", 1, 16));
export const Book16Filled = ( /*#__PURE__*/createFluentFontIcon("Book16Filled", "󰎛", 0, 16));
export const Book20Regular = ( /*#__PURE__*/createFluentFontIcon("Book20Regular", "", 1, 20));
export const Book20Filled = ( /*#__PURE__*/createFluentFontIcon("Book20Filled", "", 0, 20));
export const Book24Regular = ( /*#__PURE__*/createFluentFontIcon("Book24Regular", "", 1, 24));
export const Book24Filled = ( /*#__PURE__*/createFluentFontIcon("Book24Filled", "", 0, 24));
export const Book28Regular = ( /*#__PURE__*/createFluentFontIcon("Book28Regular", "󰖼", 1, 28));
export const Book28Filled = ( /*#__PURE__*/createFluentFontIcon("Book28Filled", "󰘵", 0, 28));
export const Book32Regular = ( /*#__PURE__*/createFluentFontIcon("Book32Regular", "󰏕", 1, 32));
export const Book32Filled = ( /*#__PURE__*/createFluentFontIcon("Book32Filled", "󰏨", 0, 32));
export const Book48Regular = ( /*#__PURE__*/createFluentFontIcon("Book48Regular", "󰖽", 1, 48));
export const Book48Filled = ( /*#__PURE__*/createFluentFontIcon("Book48Filled", "󰘶", 0, 48));
