"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BorderInsideFilled = ( /*#__PURE__*/createFluentFontIcon("BorderInsideFilled", "", 2, undefined));
export const BorderInsideRegular = ( /*#__PURE__*/createFluentFontIcon("BorderInsideRegular", "", 2, undefined));
export const BorderInside16Regular = ( /*#__PURE__*/createFluentFontIcon("BorderInside16Regular", "󰎮", 1, 16));
export const BorderInside16Filled = ( /*#__PURE__*/createFluentFontIcon("BorderInside16Filled", "󰏁", 0, 16));
export const BorderInside20Regular = ( /*#__PURE__*/createFluentFontIcon("BorderInside20Regular", "󰎯", 1, 20));
export const BorderInside20Filled = ( /*#__PURE__*/createFluentFontIcon("BorderInside20Filled", "󰏂", 0, 20));
export const BorderInside24Regular = ( /*#__PURE__*/createFluentFontIcon("BorderInside24Regular", "󰎰", 1, 24));
export const BorderInside24Filled = ( /*#__PURE__*/createFluentFontIcon("BorderInside24Filled", "󰏃", 0, 24));
