"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BotSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("BotSparkleFilled", "", 2, undefined));
export const BotSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("BotSparkleRegular", "", 2, undefined));
export const BotSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("BotSparkle16Regular", "󰟅", 1, 16));
export const BotSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("BotSparkle16Filled", "󰡂", 0, 16));
export const BotSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("BotSparkle20Regular", "", 1, 20));
export const BotSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("BotSparkle20Filled", "", 0, 20));
export const BotSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("BotSparkle24Regular", "", 1, 24));
export const BotSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("BotSparkle24Filled", "", 0, 24));
export const BotSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon("BotSparkle28Regular", "󰟆", 1, 28));
export const BotSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon("BotSparkle28Filled", "󰡃", 0, 28));
export const BotSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("BotSparkle32Regular", "󰟇", 1, 32));
export const BotSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("BotSparkle32Filled", "󰡄", 0, 32));
export const BotSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon("BotSparkle48Regular", "󰟈", 1, 48));
export const BotSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon("BotSparkle48Filled", "󰡅", 0, 48));
