"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BotFilled = ( /*#__PURE__*/createFluentFontIcon("BotFilled", "", 2, undefined));
export const BotRegular = ( /*#__PURE__*/createFluentFontIcon("BotRegular", "", 2, undefined));
export const Bot12Regular = ( /*#__PURE__*/createFluentFontIcon("Bot12Regular", "󰨗", 1, 12));
export const Bot12Filled = ( /*#__PURE__*/createFluentFontIcon("Bot12Filled", "󰪓", 0, 12));
export const Bot16Regular = ( /*#__PURE__*/createFluentFontIcon("Bot16Regular", "󰞽", 1, 16));
export const Bot16Filled = ( /*#__PURE__*/createFluentFontIcon("Bot16Filled", "󰠺", 0, 16));
export const Bot20Regular = ( /*#__PURE__*/createFluentFontIcon("Bot20Regular", "", 1, 20));
export const Bot20Filled = ( /*#__PURE__*/createFluentFontIcon("Bot20Filled", "", 0, 20));
export const Bot24Regular = ( /*#__PURE__*/createFluentFontIcon("Bot24Regular", "", 1, 24));
export const Bot24Filled = ( /*#__PURE__*/createFluentFontIcon("Bot24Filled", "", 0, 24));
export const Bot28Regular = ( /*#__PURE__*/createFluentFontIcon("Bot28Regular", "󰞾", 1, 28));
export const Bot28Filled = ( /*#__PURE__*/createFluentFontIcon("Bot28Filled", "󰠻", 0, 28));
export const Bot32Regular = ( /*#__PURE__*/createFluentFontIcon("Bot32Regular", "󰞿", 1, 32));
export const Bot32Filled = ( /*#__PURE__*/createFluentFontIcon("Bot32Filled", "󰠼", 0, 32));
export const Bot48Regular = ( /*#__PURE__*/createFluentFontIcon("Bot48Regular", "󰟀", 1, 48));
export const Bot48Filled = ( /*#__PURE__*/createFluentFontIcon("Bot48Filled", "󰠽", 0, 48));
