"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BoxSearchFilled = ( /*#__PURE__*/createFluentFontIcon("BoxSearchFilled", "", 2, undefined));
export const BoxSearchRegular = ( /*#__PURE__*/createFluentFontIcon("BoxSearchRegular", "", 2, undefined));
export const BoxSearch16Regular = ( /*#__PURE__*/createFluentFontIcon("BoxSearch16Regular", "", 1, 16));
export const BoxSearch16Filled = ( /*#__PURE__*/createFluentFontIcon("BoxSearch16Filled", "", 0, 16));
export const BoxSearch20Regular = ( /*#__PURE__*/createFluentFontIcon("BoxSearch20Regular", "", 1, 20));
export const BoxSearch20Filled = ( /*#__PURE__*/createFluentFontIcon("BoxSearch20Filled", "", 0, 20));
export const BoxSearch24Regular = ( /*#__PURE__*/createFluentFontIcon("BoxSearch24Regular", "", 1, 24));
export const BoxSearch24Filled = ( /*#__PURE__*/createFluentFontIcon("BoxSearch24Filled", "", 0, 24));
