"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BoxFilled = ( /*#__PURE__*/createFluentFontIcon("BoxFilled", "", 2, undefined));
export const BoxRegular = ( /*#__PURE__*/createFluentFontIcon("BoxRegular", "", 2, undefined));
export const Box16Regular = ( /*#__PURE__*/createFluentFontIcon("Box16Regular", "", 1, 16));
export const Box16Filled = ( /*#__PURE__*/createFluentFontIcon("Box16Filled", "", 0, 16));
export const Box20Regular = ( /*#__PURE__*/createFluentFontIcon("Box20Regular", "", 1, 20));
export const Box20Filled = ( /*#__PURE__*/createFluentFontIcon("Box20Filled", "", 0, 20));
export const Box24Regular = ( /*#__PURE__*/createFluentFontIcon("Box24Regular", "", 1, 24));
export const Box24Filled = ( /*#__PURE__*/createFluentFontIcon("Box24Filled", "", 0, 24));
export const Box28Regular = ( /*#__PURE__*/createFluentFontIcon("Box28Regular", "󰣪", 1, 28));
export const Box28Filled = ( /*#__PURE__*/createFluentFontIcon("Box28Filled", "󰥧", 0, 28));
export const Box32Regular = ( /*#__PURE__*/createFluentFontIcon("Box32Regular", "󰣫", 1, 32));
export const Box32Filled = ( /*#__PURE__*/createFluentFontIcon("Box32Filled", "󰥨", 0, 32));
export const Box48Regular = ( /*#__PURE__*/createFluentFontIcon("Box48Regular", "󰣬", 1, 48));
export const Box48Filled = ( /*#__PURE__*/createFluentFontIcon("Box48Filled", "󰥩", 0, 48));
