"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BranchFilled = ( /*#__PURE__*/createFluentFontIcon("BranchFilled", "", 2, undefined));
export const BranchRegular = ( /*#__PURE__*/createFluentFontIcon("BranchRegular", "", 2, undefined));
export const Branch16Regular = ( /*#__PURE__*/createFluentFontIcon("Branch16Regular", "", 1, 16));
export const Branch16Filled = ( /*#__PURE__*/createFluentFontIcon("Branch16Filled", "", 0, 16));
export const Branch20Regular = ( /*#__PURE__*/createFluentFontIcon("Branch20Regular", "", 1, 20));
export const Branch20Filled = ( /*#__PURE__*/createFluentFontIcon("Branch20Filled", "", 0, 20));
export const Branch24Regular = ( /*#__PURE__*/createFluentFontIcon("Branch24Regular", "", 1, 24));
export const Branch24Filled = ( /*#__PURE__*/createFluentFontIcon("Branch24Filled", "", 0, 24));
