"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BranchCompareFilled = ( /*#__PURE__*/createFluentFontIcon("BranchCompareFilled", "", 2, undefined));
export const BranchCompareRegular = ( /*#__PURE__*/createFluentFontIcon("BranchCompareRegular", "", 2, undefined));
export const BranchCompare16Regular = ( /*#__PURE__*/createFluentFontIcon("BranchCompare16Regular", "", 1, 16));
export const BranchCompare16Filled = ( /*#__PURE__*/createFluentFontIcon("BranchCompare16Filled", "", 0, 16));
export const BranchCompare20Regular = ( /*#__PURE__*/createFluentFontIcon("BranchCompare20Regular", "", 1, 20));
export const BranchCompare20Filled = ( /*#__PURE__*/createFluentFontIcon("BranchCompare20Filled", "", 0, 20));
export const BranchCompare24Regular = ( /*#__PURE__*/createFluentFontIcon("BranchCompare24Regular", "", 1, 24));
export const BranchCompare24Filled = ( /*#__PURE__*/createFluentFontIcon("BranchCompare24Filled", "", 0, 24));
