"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BriefcaseOffFilled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOffFilled", "", 2, undefined));
export const BriefcaseOffRegular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOffRegular", "", 2, undefined));
export const BriefcaseOff16Regular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff16Regular", "", 1, 16));
export const BriefcaseOff16Filled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff16Filled", "", 0, 16));
export const BriefcaseOff20Regular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff20Regular", "", 1, 20));
export const BriefcaseOff20Filled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff20Filled", "", 0, 20));
export const BriefcaseOff24Regular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff24Regular", "", 1, 24));
export const BriefcaseOff24Filled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff24Filled", "", 0, 24));
export const BriefcaseOff28Regular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff28Regular", "", 1, 28));
export const BriefcaseOff28Filled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff28Filled", "", 0, 28));
export const BriefcaseOff32Regular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff32Regular", "", 1, 32));
export const BriefcaseOff32Filled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff32Filled", "", 0, 32));
export const BriefcaseOff48Regular = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff48Regular", "", 1, 48));
export const BriefcaseOff48Filled = ( /*#__PURE__*/createFluentFontIcon("BriefcaseOff48Filled", "", 0, 48));
