"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BrightnessHighFilled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHighFilled", "", 2, undefined));
export const BrightnessHighRegular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHighRegular", "", 2, undefined));
export const BrightnessHigh16Regular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh16Regular", "", 1, 16));
export const BrightnessHigh16Filled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh16Filled", "", 0, 16));
export const BrightnessHigh20Regular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh20Regular", "", 1, 20));
export const BrightnessHigh20Filled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh20Filled", "", 0, 20));
export const BrightnessHigh24Regular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh24Regular", "", 1, 24));
export const BrightnessHigh24Filled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh24Filled", "", 0, 24));
export const BrightnessHigh28Regular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh28Regular", "", 1, 28));
export const BrightnessHigh28Filled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh28Filled", "", 0, 28));
export const BrightnessHigh32Regular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh32Regular", "", 1, 32));
export const BrightnessHigh32Filled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh32Filled", "", 0, 32));
export const BrightnessHigh48Regular = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh48Regular", "", 1, 48));
export const BrightnessHigh48Filled = ( /*#__PURE__*/createFluentFontIcon("BrightnessHigh48Filled", "", 0, 48));
