"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BroomFilled = ( /*#__PURE__*/createFluentFontIcon("BroomFilled", "", 2, undefined));
export const BroomRegular = ( /*#__PURE__*/createFluentFontIcon("BroomRegular", "", 2, undefined));
export const Broom16Regular = ( /*#__PURE__*/createFluentFontIcon("Broom16Regular", "", 1, 16));
export const Broom16Filled = ( /*#__PURE__*/createFluentFontIcon("Broom16Filled", "", 0, 16));
export const Broom20Regular = ( /*#__PURE__*/createFluentFontIcon("Broom20Regular", "", 1, 20));
export const Broom20Filled = ( /*#__PURE__*/createFluentFontIcon("Broom20Filled", "", 0, 20));
export const Broom24Regular = ( /*#__PURE__*/createFluentFontIcon("Broom24Regular", "", 1, 24));
export const Broom24Filled = ( /*#__PURE__*/createFluentFontIcon("Broom24Filled", "", 0, 24));
export const Broom28Regular = ( /*#__PURE__*/createFluentFontIcon("Broom28Regular", "", 1, 28));
export const Broom28Filled = ( /*#__PURE__*/createFluentFontIcon("Broom28Filled", "", 0, 28));
export const Broom32Regular = ( /*#__PURE__*/createFluentFontIcon("Broom32Regular", "󰐩", 1, 32));
export const Broom32Filled = ( /*#__PURE__*/createFluentFontIcon("Broom32Filled", "󰐼", 0, 32));
export const Broom32Light = ( /*#__PURE__*/createFluentFontIcon("Broom32Light", "", 3, 32));
