"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BuildingDesktopFilled = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktopFilled", "", 2, undefined));
export const BuildingDesktopRegular = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktopRegular", "", 2, undefined));
export const BuildingDesktop16Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop16Regular", "", 1, 16));
export const BuildingDesktop16Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop16Filled", "", 0, 16));
export const BuildingDesktop20Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop20Regular", "", 1, 20));
export const BuildingDesktop20Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop20Filled", "", 0, 20));
export const BuildingDesktop24Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop24Regular", "", 1, 24));
export const BuildingDesktop24Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop24Filled", "", 0, 24));
export const BuildingDesktop32Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop32Regular", "󰏙", 1, 32));
export const BuildingDesktop32Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingDesktop32Filled", "󰏬", 0, 32));
