"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BuildingHomeFilled = ( /*#__PURE__*/createFluentFontIcon("BuildingHomeFilled", "", 2, undefined));
export const BuildingHomeRegular = ( /*#__PURE__*/createFluentFontIcon("BuildingHomeRegular", "", 2, undefined));
export const BuildingHome16Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingHome16Regular", "", 1, 16));
export const BuildingHome16Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingHome16Filled", "", 0, 16));
export const BuildingHome20Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingHome20Regular", "", 1, 20));
export const BuildingHome20Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingHome20Filled", "", 0, 20));
export const BuildingHome24Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingHome24Regular", "", 1, 24));
export const BuildingHome24Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingHome24Filled", "", 0, 24));
export const BuildingHome32Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingHome32Regular", "󰠌", 1, 32));
export const BuildingHome32Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingHome32Filled", "󰢉", 0, 32));
