"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BuildingSwapFilled = ( /*#__PURE__*/createFluentFontIcon("BuildingSwapFilled", "", 2, undefined));
export const BuildingSwapRegular = ( /*#__PURE__*/createFluentFontIcon("BuildingSwapRegular", "", 2, undefined));
export const BuildingSwap16Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap16Regular", "󰑤", 1, 16));
export const BuildingSwap16Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap16Filled", "󰑷", 0, 16));
export const BuildingSwap20Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap20Regular", "󰑥", 1, 20));
export const BuildingSwap20Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap20Filled", "󰑸", 0, 20));
export const BuildingSwap24Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap24Regular", "󰑦", 1, 24));
export const BuildingSwap24Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap24Filled", "󰑹", 0, 24));
export const BuildingSwap32Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap32Regular", "󰑧", 1, 32));
export const BuildingSwap32Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap32Filled", "󰑺", 0, 32));
export const BuildingSwap48Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap48Regular", "󰑨", 1, 48));
export const BuildingSwap48Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingSwap48Filled", "󰑻", 0, 48));
