"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const BuildingBankFilled = ( /*#__PURE__*/createFluentFontIcon("BuildingBankFilled", "", 2, undefined));
export const BuildingBankRegular = ( /*#__PURE__*/createFluentFontIcon("BuildingBankRegular", "", 2, undefined));
export const BuildingBank16Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingBank16Regular", "", 1, 16));
export const BuildingBank16Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingBank16Filled", "", 0, 16));
export const BuildingBank20Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingBank20Regular", "", 1, 20));
export const BuildingBank20Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingBank20Filled", "", 0, 20));
export const BuildingBank24Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingBank24Regular", "", 1, 24));
export const BuildingBank24Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingBank24Filled", "", 0, 24));
export const BuildingBank28Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingBank28Regular", "", 1, 28));
export const BuildingBank28Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingBank28Filled", "", 0, 28));
export const BuildingBank48Regular = ( /*#__PURE__*/createFluentFontIcon("BuildingBank48Regular", "", 1, 48));
export const BuildingBank48Filled = ( /*#__PURE__*/createFluentFontIcon("BuildingBank48Filled", "", 0, 48));
