"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const Calendar3DayFilled = ( /*#__PURE__*/createFluentFontIcon("Calendar3DayFilled", "", 2, undefined));
export const Calendar3DayRegular = ( /*#__PURE__*/createFluentFontIcon("Calendar3DayRegular", "", 2, undefined));
export const Calendar3Day16Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day16Regular", "", 1, 16));
export const Calendar3Day16Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day16Filled", "", 0, 16));
export const Calendar3Day20Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day20Regular", "", 1, 20));
export const Calendar3Day20Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day20Filled", "", 0, 20));
export const Calendar3Day24Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day24Regular", "", 1, 24));
export const Calendar3Day24Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day24Filled", "", 0, 24));
export const Calendar3Day28Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day28Regular", "", 1, 28));
export const Calendar3Day28Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day28Filled", "", 0, 28));
export const Calendar3Day32Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day32Regular", "󰩬", 1, 32));
export const Calendar3Day32Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day32Filled", "󰫨", 0, 32));
export const Calendar3Day32Light = ( /*#__PURE__*/createFluentFontIcon("Calendar3Day32Light", "", 3, 32));
