"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarEditFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarEditFilled", "", 2, undefined));
export const CalendarEditRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarEditRegular", "", 2, undefined));
export const CalendarEdit16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit16Regular", "", 1, 16));
export const CalendarEdit16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit16Filled", "", 0, 16));
export const CalendarEdit20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit20Regular", "", 1, 20));
export const CalendarEdit20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit20Filled", "", 0, 20));
export const CalendarEdit24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit24Regular", "", 1, 24));
export const CalendarEdit24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit24Filled", "", 0, 24));
export const CalendarEdit32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit32Regular", "󰖡", 1, 32));
export const CalendarEdit32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit32Filled", "󰘚", 0, 32));
export const CalendarEdit32Light = ( /*#__PURE__*/createFluentFontIcon("CalendarEdit32Light", "", 3, 32));
