"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarPlayFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarPlayFilled", "", 2, undefined));
export const CalendarPlayRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarPlayRegular", "", 2, undefined));
export const CalendarPlay16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay16Regular", "", 1, 16));
export const CalendarPlay16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay16Filled", "", 0, 16));
export const CalendarPlay20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay20Regular", "", 1, 20));
export const CalendarPlay20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay20Filled", "", 0, 20));
export const CalendarPlay24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay24Regular", "", 1, 24));
export const CalendarPlay24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay24Filled", "", 0, 24));
export const CalendarPlay28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay28Regular", "", 1, 28));
export const CalendarPlay28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPlay28Filled", "", 0, 28));
