"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarEyeFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarEyeFilled", "", 2, undefined));
export const CalendarEyeRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarEyeRegular", "", 2, undefined));
export const CalendarEye16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEye16Regular", "󰪶", 1, 16));
export const CalendarEye16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEye16Filled", "󰬴", 0, 16));
export const CalendarEye20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEye20Regular", "󰈊", 1, 20));
export const CalendarEye20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEye20Filled", "󰈊", 0, 20));
export const CalendarEye24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEye24Regular", "󰪷", 1, 24));
export const CalendarEye24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEye24Filled", "󰬵", 0, 24));
export const CalendarEye28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEye28Regular", "󰪸", 1, 28));
export const CalendarEye28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEye28Filled", "󰬶", 0, 28));
export const CalendarEye32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarEye32Regular", "󰪹", 1, 32));
export const CalendarEye32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarEye32Filled", "󰬷", 0, 32));
