"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarFilled", "", 2, undefined, { flipInRtl: true }));
export const CalendarRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarRegular", "", 2, undefined, { flipInRtl: true }));
export const Calendar12Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar12Regular", "󰊂", 1, 12, { flipInRtl: true }));
export const Calendar12Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar12Filled", "󰊕", 0, 12, { flipInRtl: true }));
export const Calendar16Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar16Regular", "󰊃", 1, 16, { flipInRtl: true }));
export const Calendar16Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar16Filled", "󰊖", 0, 16, { flipInRtl: true }));
export const Calendar20Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar20Regular", "󰊄", 1, 20, { flipInRtl: true }));
export const Calendar20Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar20Filled", "󰊗", 0, 20, { flipInRtl: true }));
export const Calendar24Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar24Regular", "󰊅", 1, 24, { flipInRtl: true }));
export const Calendar24Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar24Filled", "󰊘", 0, 24, { flipInRtl: true }));
export const Calendar28Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar28Regular", "󰊆", 1, 28, { flipInRtl: true }));
export const Calendar28Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar28Filled", "󰊙", 0, 28, { flipInRtl: true }));
export const Calendar32Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar32Regular", "󰊇", 1, 32, { flipInRtl: true }));
export const Calendar32Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar32Filled", "󰊚", 0, 32, { flipInRtl: true }));
export const Calendar48Regular = ( /*#__PURE__*/createFluentFontIcon("Calendar48Regular", "󰊈", 1, 48, { flipInRtl: true }));
export const Calendar48Filled = ( /*#__PURE__*/createFluentFontIcon("Calendar48Filled", "󰊛", 0, 48, { flipInRtl: true }));
