"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarNoteFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarNoteFilled", "", 2, undefined));
export const CalendarNoteRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarNoteRegular", "", 2, undefined));
export const CalendarNote16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarNote16Regular", "󰐪", 1, 16));
export const CalendarNote16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarNote16Filled", "󰐽", 0, 16));
export const CalendarNote20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarNote20Regular", "󰐫", 1, 20));
export const CalendarNote20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarNote20Filled", "󰐾", 0, 20));
export const CalendarNote24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarNote24Regular", "󰐬", 1, 24));
export const CalendarNote24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarNote24Filled", "󰐿", 0, 24));
export const CalendarNote32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarNote32Regular", "󰐭", 1, 32));
export const CalendarNote32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarNote32Filled", "󰑀", 0, 32));
