"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarClockFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarClockFilled", "", 2, undefined));
export const CalendarClockRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarClockRegular", "", 2, undefined));
export const CalendarClock16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarClock16Regular", "", 1, 16));
export const CalendarClock16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarClock16Filled", "", 0, 16));
export const CalendarClock20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarClock20Regular", "", 1, 20));
export const CalendarClock20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarClock20Filled", "", 0, 20));
export const CalendarClock24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarClock24Regular", "", 1, 24));
export const CalendarClock24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarClock24Filled", "", 0, 24));
export const CalendarClock32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarClock32Regular", "󰠍", 1, 32));
export const CalendarClock32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarClock32Filled", "󰢊", 0, 32));
export const CalendarClock32Light = ( /*#__PURE__*/createFluentFontIcon("CalendarClock32Light", "", 3, 32));
