"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarDayFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarDayFilled", "", 2, undefined));
export const CalendarDayRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarDayRegular", "", 2, undefined));
export const CalendarDay16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDay16Regular", "", 1, 16));
export const CalendarDay16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDay16Filled", "", 0, 16));
export const CalendarDay20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDay20Regular", "", 1, 20));
export const CalendarDay20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDay20Filled", "", 0, 20));
export const CalendarDay24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDay24Regular", "", 1, 24));
export const CalendarDay24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDay24Filled", "", 0, 24));
export const CalendarDay28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDay28Regular", "", 1, 28));
export const CalendarDay28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDay28Filled", "", 0, 28));
export const CalendarDay32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDay32Regular", "󰧕", 1, 32));
export const CalendarDay32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDay32Filled", "󰩒", 0, 32));
export const CalendarDay32Light = ( /*#__PURE__*/createFluentFontIcon("CalendarDay32Light", "", 3, 32));
