"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarDateFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarDateFilled", "", 2, undefined));
export const CalendarDateRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarDateRegular", "", 2, undefined));
export const CalendarDate20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDate20Regular", "󰊉", 1, 20));
export const CalendarDate20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDate20Filled", "󰊜", 0, 20));
export const CalendarDate24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDate24Regular", "󰊊", 1, 24));
export const CalendarDate24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDate24Filled", "󰊝", 0, 24));
export const CalendarDate28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarDate28Regular", "󰊋", 1, 28));
export const CalendarDate28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarDate28Filled", "󰊞", 0, 28));
