"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarPersonFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarPersonFilled", "", 2, undefined));
export const CalendarPersonRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarPersonRegular", "", 2, undefined));
export const CalendarPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson16Regular", "", 1, 16));
export const CalendarPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson16Filled", "", 0, 16));
export const CalendarPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson20Regular", "", 1, 20));
export const CalendarPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson20Filled", "", 0, 20));
export const CalendarPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson24Regular", "", 1, 24));
export const CalendarPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson24Filled", "", 0, 24));
export const CalendarPerson32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson32Regular", "󰜮", 1, 32));
export const CalendarPerson32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarPerson32Filled", "󰞫", 0, 32));
