"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarLtrFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtrFilled", "", 2, undefined));
export const CalendarLtrRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtrRegular", "", 2, undefined));
export const CalendarLtr12Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr12Regular", "", 1, 12));
export const CalendarLtr12Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr12Filled", "", 0, 12));
export const CalendarLtr16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr16Regular", "", 1, 16));
export const CalendarLtr16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr16Filled", "", 0, 16));
export const CalendarLtr20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr20Regular", "", 1, 20));
export const CalendarLtr20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr20Filled", "", 0, 20));
export const CalendarLtr24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr24Regular", "", 1, 24));
export const CalendarLtr24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr24Filled", "", 0, 24));
export const CalendarLtr28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr28Regular", "", 1, 28));
export const CalendarLtr28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr28Filled", "", 0, 28));
export const CalendarLtr32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr32Regular", "", 1, 32));
export const CalendarLtr32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr32Filled", "", 0, 32));
export const CalendarLtr32Light = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr32Light", "", 3, 32));
export const CalendarLtr48Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr48Regular", "", 1, 48));
export const CalendarLtr48Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarLtr48Filled", "", 0, 48));
