"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarVideoFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarVideoFilled", "", 2, undefined, { flipInRtl: true }));
export const CalendarVideoRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarVideoRegular", "", 2, undefined, { flipInRtl: true }));
export const CalendarVideo20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarVideo20Regular", "󰕟", 1, 20, { flipInRtl: true }));
export const CalendarVideo20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarVideo20Filled", "󰗘", 0, 20, { flipInRtl: true }));
export const CalendarVideo24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarVideo24Regular", "󰓫", 1, 24, { flipInRtl: true }));
export const CalendarVideo24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarVideo24Filled", "󰕤", 0, 24, { flipInRtl: true }));
export const CalendarVideo28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarVideo28Regular", "󰓬", 1, 28, { flipInRtl: true }));
export const CalendarVideo28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarVideo28Filled", "󰕥", 0, 28, { flipInRtl: true }));
