"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CalendarRtlFilled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtlFilled", "", 2, undefined));
export const CalendarRtlRegular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtlRegular", "", 2, undefined));
export const CalendarRtl12Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl12Regular", "", 1, 12));
export const CalendarRtl12Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl12Filled", "", 0, 12));
export const CalendarRtl16Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl16Regular", "", 1, 16));
export const CalendarRtl16Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl16Filled", "", 0, 16));
export const CalendarRtl20Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl20Regular", "", 1, 20));
export const CalendarRtl20Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl20Filled", "", 0, 20));
export const CalendarRtl24Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl24Regular", "", 1, 24));
export const CalendarRtl24Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl24Filled", "", 0, 24));
export const CalendarRtl28Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl28Regular", "", 1, 28));
export const CalendarRtl28Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl28Filled", "", 0, 28));
export const CalendarRtl32Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl32Regular", "", 1, 32));
export const CalendarRtl32Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl32Filled", "", 0, 32));
export const CalendarRtl48Regular = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl48Regular", "", 1, 48));
export const CalendarRtl48Filled = ( /*#__PURE__*/createFluentFontIcon("CalendarRtl48Filled", "", 0, 48));
