"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CallSquareFilled = ( /*#__PURE__*/createFluentFontIcon("CallSquareFilled", "", 2, undefined));
export const CallSquareRegular = ( /*#__PURE__*/createFluentFontIcon("CallSquareRegular", "", 2, undefined));
export const CallSquare16Regular = ( /*#__PURE__*/createFluentFontIcon("CallSquare16Regular", "󰠒", 1, 16));
export const CallSquare16Filled = ( /*#__PURE__*/createFluentFontIcon("CallSquare16Filled", "󰢏", 0, 16));
export const CallSquare20Regular = ( /*#__PURE__*/createFluentFontIcon("CallSquare20Regular", "󰠓", 1, 20));
export const CallSquare20Filled = ( /*#__PURE__*/createFluentFontIcon("CallSquare20Filled", "󰢐", 0, 20));
export const CallSquare24Regular = ( /*#__PURE__*/createFluentFontIcon("CallSquare24Regular", "󰠔", 1, 24));
export const CallSquare24Filled = ( /*#__PURE__*/createFluentFontIcon("CallSquare24Filled", "󰢑", 0, 24));
export const CallSquare28Regular = ( /*#__PURE__*/createFluentFontIcon("CallSquare28Regular", "󰠕", 1, 28));
export const CallSquare28Filled = ( /*#__PURE__*/createFluentFontIcon("CallSquare28Filled", "󰢒", 0, 28));
