"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CallMissedFilled = ( /*#__PURE__*/createFluentFontIcon("CallMissedFilled", "", 2, undefined));
export const CallMissedRegular = ( /*#__PURE__*/createFluentFontIcon("CallMissedRegular", "", 2, undefined));
export const CallMissed12Regular = ( /*#__PURE__*/createFluentFontIcon("CallMissed12Regular", "", 1, 12));
export const CallMissed12Filled = ( /*#__PURE__*/createFluentFontIcon("CallMissed12Filled", "", 0, 12));
export const CallMissed16Regular = ( /*#__PURE__*/createFluentFontIcon("CallMissed16Regular", "", 1, 16));
export const CallMissed16Filled = ( /*#__PURE__*/createFluentFontIcon("CallMissed16Filled", "", 0, 16));
export const CallMissed20Regular = ( /*#__PURE__*/createFluentFontIcon("CallMissed20Regular", "", 1, 20));
export const CallMissed20Filled = ( /*#__PURE__*/createFluentFontIcon("CallMissed20Filled", "", 0, 20));
export const CallMissed24Regular = ( /*#__PURE__*/createFluentFontIcon("CallMissed24Regular", "", 1, 24));
export const CallMissed24Filled = ( /*#__PURE__*/createFluentFontIcon("CallMissed24Filled", "", 0, 24));
export const CallMissed28Regular = ( /*#__PURE__*/createFluentFontIcon("CallMissed28Regular", "", 1, 28));
export const CallMissed28Filled = ( /*#__PURE__*/createFluentFontIcon("CallMissed28Filled", "", 0, 28));
export const CallMissed48Regular = ( /*#__PURE__*/createFluentFontIcon("CallMissed48Regular", "", 1, 48));
export const CallMissed48Filled = ( /*#__PURE__*/createFluentFontIcon("CallMissed48Filled", "", 0, 48));
