"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CallInboundFilled = ( /*#__PURE__*/createFluentFontIcon("CallInboundFilled", "", 2, undefined));
export const CallInboundRegular = ( /*#__PURE__*/createFluentFontIcon("CallInboundRegular", "", 2, undefined));
export const CallInbound16Regular = ( /*#__PURE__*/createFluentFontIcon("CallInbound16Regular", "", 1, 16));
export const CallInbound16Filled = ( /*#__PURE__*/createFluentFontIcon("CallInbound16Filled", "", 0, 16));
export const CallInbound20Regular = ( /*#__PURE__*/createFluentFontIcon("CallInbound20Regular", "", 1, 20));
export const CallInbound20Filled = ( /*#__PURE__*/createFluentFontIcon("CallInbound20Filled", "", 0, 20));
export const CallInbound24Regular = ( /*#__PURE__*/createFluentFontIcon("CallInbound24Regular", "", 1, 24));
export const CallInbound24Filled = ( /*#__PURE__*/createFluentFontIcon("CallInbound24Filled", "", 0, 24));
export const CallInbound28Regular = ( /*#__PURE__*/createFluentFontIcon("CallInbound28Regular", "", 1, 28));
export const CallInbound28Filled = ( /*#__PURE__*/createFluentFontIcon("CallInbound28Filled", "", 0, 28));
export const CallInbound48Regular = ( /*#__PURE__*/createFluentFontIcon("CallInbound48Regular", "", 1, 48));
export const CallInbound48Filled = ( /*#__PURE__*/createFluentFontIcon("CallInbound48Filled", "", 0, 48));
