"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CameraOffFilled = ( /*#__PURE__*/createFluentFontIcon("CameraOffFilled", "", 2, undefined));
export const CameraOffRegular = ( /*#__PURE__*/createFluentFontIcon("CameraOffRegular", "", 2, undefined));
export const CameraOff16Regular = ( /*#__PURE__*/createFluentFontIcon("CameraOff16Regular", "", 1, 16));
export const CameraOff16Filled = ( /*#__PURE__*/createFluentFontIcon("CameraOff16Filled", "", 0, 16));
export const CameraOff20Regular = ( /*#__PURE__*/createFluentFontIcon("CameraOff20Regular", "", 1, 20));
export const CameraOff20Filled = ( /*#__PURE__*/createFluentFontIcon("CameraOff20Filled", "", 0, 20));
export const CameraOff24Regular = ( /*#__PURE__*/createFluentFontIcon("CameraOff24Regular", "", 1, 24));
export const CameraOff24Filled = ( /*#__PURE__*/createFluentFontIcon("CameraOff24Filled", "", 0, 24));
