"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CaretDownFilled = ( /*#__PURE__*/createFluentFontIcon("CaretDownFilled", "", 2, undefined));
export const CaretDownRegular = ( /*#__PURE__*/createFluentFontIcon("CaretDownRegular", "", 2, undefined));
export const CaretDown12Regular = ( /*#__PURE__*/createFluentFontIcon("CaretDown12Regular", "", 1, 12));
export const CaretDown12Filled = ( /*#__PURE__*/createFluentFontIcon("CaretDown12Filled", "", 0, 12));
export const CaretDown16Regular = ( /*#__PURE__*/createFluentFontIcon("CaretDown16Regular", "", 1, 16));
export const CaretDown16Filled = ( /*#__PURE__*/createFluentFontIcon("CaretDown16Filled", "", 0, 16));
export const CaretDown20Regular = ( /*#__PURE__*/createFluentFontIcon("CaretDown20Regular", "", 1, 20));
export const CaretDown20Filled = ( /*#__PURE__*/createFluentFontIcon("CaretDown20Filled", "", 0, 20));
export const CaretDown24Regular = ( /*#__PURE__*/createFluentFontIcon("CaretDown24Regular", "", 1, 24));
export const CaretDown24Filled = ( /*#__PURE__*/createFluentFontIcon("CaretDown24Filled", "", 0, 24));
