"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CatchUpFilled = ( /*#__PURE__*/createFluentFontIcon("CatchUpFilled", "", 2, undefined));
export const CatchUpRegular = ( /*#__PURE__*/createFluentFontIcon("CatchUpRegular", "", 2, undefined));
export const CatchUp16Regular = ( /*#__PURE__*/createFluentFontIcon("CatchUp16Regular", "", 1, 16));
export const CatchUp16Filled = ( /*#__PURE__*/createFluentFontIcon("CatchUp16Filled", "", 0, 16));
export const CatchUp20Regular = ( /*#__PURE__*/createFluentFontIcon("CatchUp20Regular", "", 1, 20));
export const CatchUp20Filled = ( /*#__PURE__*/createFluentFontIcon("CatchUp20Filled", "", 0, 20));
export const CatchUp24Regular = ( /*#__PURE__*/createFluentFontIcon("CatchUp24Regular", "", 1, 24));
export const CatchUp24Filled = ( /*#__PURE__*/createFluentFontIcon("CatchUp24Filled", "", 0, 24));
