"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChannelDismissFilled = ( /*#__PURE__*/createFluentFontIcon("ChannelDismissFilled", "", 2, undefined));
export const ChannelDismissRegular = ( /*#__PURE__*/createFluentFontIcon("ChannelDismissRegular", "", 2, undefined));
export const ChannelDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss16Regular", "", 1, 16));
export const ChannelDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss16Filled", "", 0, 16));
export const ChannelDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss20Regular", "", 1, 20));
export const ChannelDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss20Filled", "", 0, 20));
export const ChannelDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss24Regular", "", 1, 24));
export const ChannelDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss24Filled", "", 0, 24));
export const ChannelDismiss28Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss28Regular", "", 1, 28));
export const ChannelDismiss28Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss28Filled", "", 0, 28));
export const ChannelDismiss48Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss48Regular", "", 1, 48));
export const ChannelDismiss48Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelDismiss48Filled", "", 0, 48));
