"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChannelAlertFilled = ( /*#__PURE__*/createFluentFontIcon("ChannelAlertFilled", "", 2, undefined));
export const ChannelAlertRegular = ( /*#__PURE__*/createFluentFontIcon("ChannelAlertRegular", "", 2, undefined));
export const ChannelAlert16Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert16Regular", "", 1, 16));
export const ChannelAlert16Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert16Filled", "", 0, 16));
export const ChannelAlert20Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert20Regular", "", 1, 20));
export const ChannelAlert20Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert20Filled", "", 0, 20));
export const ChannelAlert24Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert24Regular", "", 1, 24));
export const ChannelAlert24Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert24Filled", "", 0, 24));
export const ChannelAlert28Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert28Regular", "", 1, 28));
export const ChannelAlert28Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert28Filled", "", 0, 28));
export const ChannelAlert48Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert48Regular", "", 1, 48));
export const ChannelAlert48Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelAlert48Filled", "", 0, 48));
