"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChannelShareFilled = ( /*#__PURE__*/createFluentFontIcon("ChannelShareFilled", "", 2, undefined));
export const ChannelShareRegular = ( /*#__PURE__*/createFluentFontIcon("ChannelShareRegular", "", 2, undefined));
export const ChannelShare12Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelShare12Regular", "", 1, 12));
export const ChannelShare12Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelShare12Filled", "", 0, 12));
export const ChannelShare16Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelShare16Regular", "", 1, 16));
export const ChannelShare16Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelShare16Filled", "", 0, 16));
export const ChannelShare20Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelShare20Regular", "", 1, 20));
export const ChannelShare20Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelShare20Filled", "", 0, 20));
export const ChannelShare24Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelShare24Regular", "", 1, 24));
export const ChannelShare24Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelShare24Filled", "", 0, 24));
export const ChannelShare28Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelShare28Regular", "", 1, 28));
export const ChannelShare28Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelShare28Filled", "", 0, 28));
export const ChannelShare48Regular = ( /*#__PURE__*/createFluentFontIcon("ChannelShare48Regular", "", 1, 48));
export const ChannelShare48Filled = ( /*#__PURE__*/createFluentFontIcon("ChannelShare48Filled", "", 0, 48));
