"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChatEmptyFilled = ( /*#__PURE__*/createFluentFontIcon("ChatEmptyFilled", "", 2, undefined));
export const ChatEmptyRegular = ( /*#__PURE__*/createFluentFontIcon("ChatEmptyRegular", "", 2, undefined));
export const ChatEmpty12Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty12Regular", "", 1, 12));
export const ChatEmpty12Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty12Filled", "", 0, 12));
export const ChatEmpty16Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty16Regular", "", 1, 16));
export const ChatEmpty16Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty16Filled", "", 0, 16));
export const ChatEmpty20Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty20Regular", "", 1, 20));
export const ChatEmpty20Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty20Filled", "", 0, 20));
export const ChatEmpty24Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty24Regular", "", 1, 24));
export const ChatEmpty24Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty24Filled", "", 0, 24));
export const ChatEmpty28Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty28Regular", "", 1, 28));
export const ChatEmpty28Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty28Filled", "", 0, 28));
export const ChatEmpty32Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty32Regular", "", 1, 32));
export const ChatEmpty32Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty32Filled", "", 0, 32));
export const ChatEmpty48Regular = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty48Regular", "", 1, 48));
export const ChatEmpty48Filled = ( /*#__PURE__*/createFluentFontIcon("ChatEmpty48Filled", "", 0, 48));
