"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChatFilled = ( /*#__PURE__*/createFluentFontIcon("ChatFilled", "", 2, undefined));
export const ChatRegular = ( /*#__PURE__*/createFluentFontIcon("ChatRegular", "", 2, undefined));
export const Chat12Regular = ( /*#__PURE__*/createFluentFontIcon("Chat12Regular", "", 1, 12));
export const Chat12Filled = ( /*#__PURE__*/createFluentFontIcon("Chat12Filled", "", 0, 12));
export const Chat16Regular = ( /*#__PURE__*/createFluentFontIcon("Chat16Regular", "", 1, 16));
export const Chat16Filled = ( /*#__PURE__*/createFluentFontIcon("Chat16Filled", "", 0, 16));
export const Chat20Regular = ( /*#__PURE__*/createFluentFontIcon("Chat20Regular", "", 1, 20));
export const Chat20Filled = ( /*#__PURE__*/createFluentFontIcon("Chat20Filled", "", 0, 20));
export const Chat24Regular = ( /*#__PURE__*/createFluentFontIcon("Chat24Regular", "", 1, 24));
export const Chat24Filled = ( /*#__PURE__*/createFluentFontIcon("Chat24Filled", "", 0, 24));
export const Chat28Regular = ( /*#__PURE__*/createFluentFontIcon("Chat28Regular", "", 1, 28));
export const Chat28Filled = ( /*#__PURE__*/createFluentFontIcon("Chat28Filled", "", 0, 28));
export const Chat32Regular = ( /*#__PURE__*/createFluentFontIcon("Chat32Regular", "", 1, 32));
export const Chat32Filled = ( /*#__PURE__*/createFluentFontIcon("Chat32Filled", "", 0, 32));
export const Chat32Light = ( /*#__PURE__*/createFluentFontIcon("Chat32Light", "", 3, 32));
export const Chat48Regular = ( /*#__PURE__*/createFluentFontIcon("Chat48Regular", "", 1, 48));
export const Chat48Filled = ( /*#__PURE__*/createFluentFontIcon("Chat48Filled", "", 0, 48));
