"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChatLockFilled = ( /*#__PURE__*/createFluentFontIcon("ChatLockFilled", "", 2, undefined));
export const ChatLockRegular = ( /*#__PURE__*/createFluentFontIcon("ChatLockRegular", "", 2, undefined));
export const ChatLock16Regular = ( /*#__PURE__*/createFluentFontIcon("ChatLock16Regular", "󰎱", 1, 16));
export const ChatLock16Filled = ( /*#__PURE__*/createFluentFontIcon("ChatLock16Filled", "󰏄", 0, 16));
export const ChatLock20Regular = ( /*#__PURE__*/createFluentFontIcon("ChatLock20Regular", "󰎲", 1, 20));
export const ChatLock20Filled = ( /*#__PURE__*/createFluentFontIcon("ChatLock20Filled", "󰏅", 0, 20));
export const ChatLock24Regular = ( /*#__PURE__*/createFluentFontIcon("ChatLock24Regular", "󰎳", 1, 24));
export const ChatLock24Filled = ( /*#__PURE__*/createFluentFontIcon("ChatLock24Filled", "󰏆", 0, 24));
export const ChatLock28Regular = ( /*#__PURE__*/createFluentFontIcon("ChatLock28Regular", "󰎴", 1, 28));
export const ChatLock28Filled = ( /*#__PURE__*/createFluentFontIcon("ChatLock28Filled", "󰏇", 0, 28));
