"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChatSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkleFilled", "", 2, undefined));
export const ChatSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkleRegular", "", 2, undefined));
export const ChatSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle16Regular", "", 1, 16));
export const ChatSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle16Filled", "", 0, 16));
export const ChatSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle20Regular", "", 1, 20));
export const ChatSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle20Filled", "", 0, 20));
export const ChatSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle24Regular", "", 1, 24));
export const ChatSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle24Filled", "", 0, 24));
export const ChatSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle28Regular", "", 1, 28));
export const ChatSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle28Filled", "", 0, 28));
export const ChatSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle32Regular", "", 1, 32));
export const ChatSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle32Filled", "", 0, 32));
export const ChatSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle48Regular", "", 1, 48));
export const ChatSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon("ChatSparkle48Filled", "", 0, 48));
