"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChatDismissFilled = ( /*#__PURE__*/createFluentFontIcon("ChatDismissFilled", "", 2, undefined));
export const ChatDismissRegular = ( /*#__PURE__*/createFluentFontIcon("ChatDismissRegular", "", 2, undefined));
export const ChatDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("ChatDismiss16Regular", "", 1, 16));
export const ChatDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("ChatDismiss16Filled", "", 0, 16));
export const ChatDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("ChatDismiss20Regular", "", 1, 20));
export const ChatDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("ChatDismiss20Filled", "", 0, 20));
export const ChatDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("ChatDismiss24Regular", "", 1, 24));
export const ChatDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("ChatDismiss24Filled", "", 0, 24));
