"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CheckmarkFilled = ( /*#__PURE__*/createFluentFontIcon("CheckmarkFilled", "", 2, undefined));
export const CheckmarkRegular = ( /*#__PURE__*/createFluentFontIcon("CheckmarkRegular", "", 2, undefined));
export const Checkmark12Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark12Regular", "", 1, 12));
export const Checkmark12Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark12Filled", "", 0, 12));
export const Checkmark16Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark16Regular", "", 1, 16));
export const Checkmark16Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark16Filled", "", 0, 16));
export const Checkmark20Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark20Regular", "", 1, 20));
export const Checkmark20Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark20Filled", "", 0, 20));
export const Checkmark24Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark24Regular", "", 1, 24));
export const Checkmark24Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark24Filled", "", 0, 24));
export const Checkmark28Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark28Regular", "", 1, 28));
export const Checkmark28Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark28Filled", "", 0, 28));
export const Checkmark32Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark32Regular", "", 1, 32));
export const Checkmark32Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark32Filled", "", 0, 32));
export const Checkmark32Light = ( /*#__PURE__*/createFluentFontIcon("Checkmark32Light", "", 3, 32));
export const Checkmark48Regular = ( /*#__PURE__*/createFluentFontIcon("Checkmark48Regular", "", 1, 48));
export const Checkmark48Filled = ( /*#__PURE__*/createFluentFontIcon("Checkmark48Filled", "", 0, 48));
