"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CheckmarkLockFilled = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLockFilled", "", 2, undefined));
export const CheckmarkLockRegular = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLockRegular", "", 2, undefined));
export const CheckmarkLock16Regular = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLock16Regular", "", 1, 16));
export const CheckmarkLock16Filled = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLock16Filled", "", 0, 16));
export const CheckmarkLock20Regular = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLock20Regular", "", 1, 20));
export const CheckmarkLock20Filled = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLock20Filled", "", 0, 20));
export const CheckmarkLock24Regular = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLock24Regular", "", 1, 24));
export const CheckmarkLock24Filled = ( /*#__PURE__*/createFluentFontIcon("CheckmarkLock24Filled", "", 0, 24));
