"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const Checkbox1Regular = ( /*#__PURE__*/createFluentFontIcon("Checkbox1Regular", "", 2, undefined));
export const Checkbox1Filled = ( /*#__PURE__*/createFluentFontIcon("Checkbox1Filled", "", 2, undefined));
export const Checkbox2Regular = ( /*#__PURE__*/createFluentFontIcon("Checkbox2Regular", "", 2, undefined));
export const Checkbox2Filled = ( /*#__PURE__*/createFluentFontIcon("Checkbox2Filled", "", 2, undefined));
export const Checkbox120Regular = ( /*#__PURE__*/createFluentFontIcon("Checkbox120Regular", "", 1, 20));
export const Checkbox120Filled = ( /*#__PURE__*/createFluentFontIcon("Checkbox120Filled", "", 0, 20));
export const Checkbox124Regular = ( /*#__PURE__*/createFluentFontIcon("Checkbox124Regular", "", 1, 24));
export const Checkbox124Filled = ( /*#__PURE__*/createFluentFontIcon("Checkbox124Filled", "", 0, 24));
export const Checkbox220Regular = ( /*#__PURE__*/createFluentFontIcon("Checkbox220Regular", "", 1, 20));
export const Checkbox220Filled = ( /*#__PURE__*/createFluentFontIcon("Checkbox220Filled", "", 0, 20));
export const Checkbox224Regular = ( /*#__PURE__*/createFluentFontIcon("Checkbox224Regular", "", 1, 24));
export const Checkbox224Filled = ( /*#__PURE__*/createFluentFontIcon("Checkbox224Filled", "", 0, 24));
