"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChessFilled = ( /*#__PURE__*/createFluentFontIcon("ChessFilled", "", 2, undefined));
export const ChessRegular = ( /*#__PURE__*/createFluentFontIcon("ChessRegular", "", 2, undefined));
export const Chess16Regular = ( /*#__PURE__*/createFluentFontIcon("Chess16Regular", "󰨡", 1, 16));
export const Chess16Filled = ( /*#__PURE__*/createFluentFontIcon("Chess16Filled", "󰪝", 0, 16));
export const Chess20Regular = ( /*#__PURE__*/createFluentFontIcon("Chess20Regular", "", 1, 20));
export const Chess20Filled = ( /*#__PURE__*/createFluentFontIcon("Chess20Filled", "", 0, 20));
export const Chess24Regular = ( /*#__PURE__*/createFluentFontIcon("Chess24Regular", "󰨢", 1, 24));
export const Chess24Filled = ( /*#__PURE__*/createFluentFontIcon("Chess24Filled", "󰪞", 0, 24));
