"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChevronDownUpFilled = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUpFilled", "", 2, undefined));
export const ChevronDownUpRegular = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUpRegular", "", 2, undefined));
export const ChevronDownUp16Regular = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUp16Regular", "󰅫", 1, 16));
export const ChevronDownUp16Filled = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUp16Filled", "󰅫", 0, 16));
export const ChevronDownUp20Regular = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUp20Regular", "󰅬", 1, 20));
export const ChevronDownUp20Filled = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUp20Filled", "󰅬", 0, 20));
export const ChevronDownUp24Regular = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUp24Regular", "󰅭", 1, 24));
export const ChevronDownUp24Filled = ( /*#__PURE__*/createFluentFontIcon("ChevronDownUp24Filled", "󰅭", 0, 24));
