"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ChevronUpDownFilled = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDownFilled", "", 2, undefined));
export const ChevronUpDownRegular = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDownRegular", "", 2, undefined));
export const ChevronUpDown16Regular = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDown16Regular", "", 1, 16));
export const ChevronUpDown16Filled = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDown16Filled", "", 0, 16));
export const ChevronUpDown20Regular = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDown20Regular", "", 1, 20));
export const ChevronUpDown20Filled = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDown20Filled", "", 0, 20));
export const ChevronUpDown24Regular = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDown24Regular", "", 1, 24));
export const ChevronUpDown24Filled = ( /*#__PURE__*/createFluentFontIcon("ChevronUpDown24Filled", "", 0, 24));
