"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CircleFilled = ( /*#__PURE__*/createFluentFontIcon("CircleFilled", "", 2, undefined));
export const CircleRegular = ( /*#__PURE__*/createFluentFontIcon("CircleRegular", "", 2, undefined));
export const Circle12Regular = ( /*#__PURE__*/createFluentFontIcon("Circle12Regular", "", 1, 12));
export const Circle12Filled = ( /*#__PURE__*/createFluentFontIcon("Circle12Filled", "", 0, 12));
export const Circle16Regular = ( /*#__PURE__*/createFluentFontIcon("Circle16Regular", "", 1, 16));
export const Circle16Filled = ( /*#__PURE__*/createFluentFontIcon("Circle16Filled", "", 0, 16));
export const Circle20Regular = ( /*#__PURE__*/createFluentFontIcon("Circle20Regular", "", 1, 20));
export const Circle20Filled = ( /*#__PURE__*/createFluentFontIcon("Circle20Filled", "", 0, 20));
export const Circle24Regular = ( /*#__PURE__*/createFluentFontIcon("Circle24Regular", "", 1, 24));
export const Circle24Filled = ( /*#__PURE__*/createFluentFontIcon("Circle24Filled", "", 0, 24));
export const Circle28Regular = ( /*#__PURE__*/createFluentFontIcon("Circle28Regular", "󰃖", 1, 28));
export const Circle28Filled = ( /*#__PURE__*/createFluentFontIcon("Circle28Filled", "󰃕", 0, 28));
export const Circle32Regular = ( /*#__PURE__*/createFluentFontIcon("Circle32Regular", "", 1, 32));
export const Circle32Filled = ( /*#__PURE__*/createFluentFontIcon("Circle32Filled", "", 0, 32));
export const Circle48Regular = ( /*#__PURE__*/createFluentFontIcon("Circle48Regular", "", 1, 48));
export const Circle48Filled = ( /*#__PURE__*/createFluentFontIcon("Circle48Filled", "", 0, 48));
