"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CircleSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkleFilled", "", 2, undefined));
export const CircleSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkleRegular", "", 2, undefined));
export const CircleSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle16Regular", "󰟏", 1, 16));
export const CircleSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle16Filled", "󰡌", 0, 16));
export const CircleSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle20Regular", "󰟐", 1, 20));
export const CircleSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle20Filled", "󰡍", 0, 20));
export const CircleSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle24Regular", "󰟑", 1, 24));
export const CircleSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle24Filled", "󰡎", 0, 24));
export const CircleSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle28Regular", "󰟒", 1, 28));
export const CircleSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle28Filled", "󰡏", 0, 28));
export const CircleSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle32Regular", "󰟓", 1, 32));
export const CircleSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle32Filled", "󰡐", 0, 32));
export const CircleSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle48Regular", "󰟔", 1, 48));
export const CircleSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon("CircleSparkle48Filled", "󰡑", 0, 48));
