"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CircleImageFilled = ( /*#__PURE__*/createFluentFontIcon("CircleImageFilled", "", 2, undefined));
export const CircleImageRegular = ( /*#__PURE__*/createFluentFontIcon("CircleImageRegular", "", 2, undefined));
export const CircleImage16Regular = ( /*#__PURE__*/createFluentFontIcon("CircleImage16Regular", "", 1, 16));
export const CircleImage16Filled = ( /*#__PURE__*/createFluentFontIcon("CircleImage16Filled", "", 0, 16));
export const CircleImage20Regular = ( /*#__PURE__*/createFluentFontIcon("CircleImage20Regular", "", 1, 20));
export const CircleImage20Filled = ( /*#__PURE__*/createFluentFontIcon("CircleImage20Filled", "", 0, 20));
export const CircleImage24Regular = ( /*#__PURE__*/createFluentFontIcon("CircleImage24Regular", "", 1, 24));
export const CircleImage24Filled = ( /*#__PURE__*/createFluentFontIcon("CircleImage24Filled", "", 0, 24));
export const CircleImage28Regular = ( /*#__PURE__*/createFluentFontIcon("CircleImage28Regular", "", 1, 28));
export const CircleImage28Filled = ( /*#__PURE__*/createFluentFontIcon("CircleImage28Filled", "", 0, 28));
