"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ClassificationFilled = ( /*#__PURE__*/createFluentFontIcon("ClassificationFilled", "", 2, undefined));
export const ClassificationRegular = ( /*#__PURE__*/createFluentFontIcon("ClassificationRegular", "", 2, undefined));
export const Classification16Regular = ( /*#__PURE__*/createFluentFontIcon("Classification16Regular", "", 1, 16));
export const Classification16Filled = ( /*#__PURE__*/createFluentFontIcon("Classification16Filled", "", 0, 16));
export const Classification20Regular = ( /*#__PURE__*/createFluentFontIcon("Classification20Regular", "", 1, 20));
export const Classification20Filled = ( /*#__PURE__*/createFluentFontIcon("Classification20Filled", "", 0, 20));
export const Classification24Regular = ( /*#__PURE__*/createFluentFontIcon("Classification24Regular", "", 1, 24));
export const Classification24Filled = ( /*#__PURE__*/createFluentFontIcon("Classification24Filled", "", 0, 24));
export const Classification28Regular = ( /*#__PURE__*/createFluentFontIcon("Classification28Regular", "󰩮", 1, 28));
export const Classification28Filled = ( /*#__PURE__*/createFluentFontIcon("Classification28Filled", "󰫪", 0, 28));
export const Classification32Regular = ( /*#__PURE__*/createFluentFontIcon("Classification32Regular", "󰖀", 1, 32));
export const Classification32Filled = ( /*#__PURE__*/createFluentFontIcon("Classification32Filled", "󰗹", 0, 32));
export const Classification32Light = ( /*#__PURE__*/createFluentFontIcon("Classification32Light", "", 3, 32));
