"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ClipboardTaskFilled = ( /*#__PURE__*/createFluentFontIcon("ClipboardTaskFilled", "", 2, undefined));
export const ClipboardTaskRegular = ( /*#__PURE__*/createFluentFontIcon("ClipboardTaskRegular", "", 2, undefined));
export const ClipboardTask16Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardTask16Regular", "", 1, 16));
export const ClipboardTask16Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardTask16Filled", "", 0, 16));
export const ClipboardTask20Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardTask20Regular", "", 1, 20));
export const ClipboardTask20Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardTask20Filled", "", 0, 20));
export const ClipboardTask24Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardTask24Regular", "", 1, 24));
export const ClipboardTask24Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardTask24Filled", "", 0, 24));
