"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ClipboardPasteFilled = ( /*#__PURE__*/createFluentFontIcon("ClipboardPasteFilled", "", 2, undefined));
export const ClipboardPasteRegular = ( /*#__PURE__*/createFluentFontIcon("ClipboardPasteRegular", "", 2, undefined));
export const ClipboardPaste16Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste16Regular", "", 1, 16));
export const ClipboardPaste16Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste16Filled", "", 0, 16));
export const ClipboardPaste20Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste20Regular", "", 1, 20));
export const ClipboardPaste20Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste20Filled", "", 0, 20));
export const ClipboardPaste24Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste24Regular", "", 1, 24));
export const ClipboardPaste24Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste24Filled", "", 0, 24));
export const ClipboardPaste28Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste28Regular", "󰩯", 1, 28));
export const ClipboardPaste28Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste28Filled", "󰫫", 0, 28));
export const ClipboardPaste32Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste32Regular", "󰈋", 1, 32));
export const ClipboardPaste32Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste32Filled", "󰈋", 0, 32));
export const ClipboardPaste32Light = ( /*#__PURE__*/createFluentFontIcon("ClipboardPaste32Light", "", 3, 32));
