"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ClipboardBrushFilled = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrushFilled", "", 2, undefined));
export const ClipboardBrushRegular = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrushRegular", "", 2, undefined));
export const ClipboardBrush16Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush16Regular", "󰑪", 1, 16));
export const ClipboardBrush16Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush16Filled", "󰑽", 0, 16));
export const ClipboardBrush20Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush20Regular", "󰑫", 1, 20));
export const ClipboardBrush20Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush20Filled", "󰑾", 0, 20));
export const ClipboardBrush24Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush24Regular", "󰑬", 1, 24));
export const ClipboardBrush24Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush24Filled", "󰑿", 0, 24));
export const ClipboardBrush28Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush28Regular", "󰑭", 1, 28));
export const ClipboardBrush28Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush28Filled", "󰒀", 0, 28));
export const ClipboardBrush32Regular = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush32Regular", "󰑮", 1, 32));
export const ClipboardBrush32Filled = ( /*#__PURE__*/createFluentFontIcon("ClipboardBrush32Filled", "󰒁", 0, 32));
