"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ClockSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("ClockSparkleFilled", "", 2, undefined));
export const ClockSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("ClockSparkleRegular", "", 2, undefined));
export const ClockSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle16Regular", "󰠡", 1, 16));
export const ClockSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle16Filled", "󰢞", 0, 16));
export const ClockSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle20Regular", "󰠢", 1, 20));
export const ClockSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle20Filled", "󰢟", 0, 20));
export const ClockSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle24Regular", "󰠣", 1, 24));
export const ClockSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle24Filled", "󰢠", 0, 24));
export const ClockSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle32Regular", "󰠤", 1, 32));
export const ClockSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("ClockSparkle32Filled", "󰢡", 0, 32));
