"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ClockWarningFilled = ( /*#__PURE__*/createFluentFontIcon("ClockWarningFilled", "", 2, undefined));
export const ClockWarningRegular = ( /*#__PURE__*/createFluentFontIcon("ClockWarningRegular", "", 2, undefined));
export const ClockWarning16Regular = ( /*#__PURE__*/createFluentFontIcon("ClockWarning16Regular", "󰩱", 1, 16));
export const ClockWarning16Filled = ( /*#__PURE__*/createFluentFontIcon("ClockWarning16Filled", "󰫭", 0, 16));
export const ClockWarning20Regular = ( /*#__PURE__*/createFluentFontIcon("ClockWarning20Regular", "󰩲", 1, 20));
export const ClockWarning20Filled = ( /*#__PURE__*/createFluentFontIcon("ClockWarning20Filled", "󰫮", 0, 20));
export const ClockWarning24Regular = ( /*#__PURE__*/createFluentFontIcon("ClockWarning24Regular", "󰩳", 1, 24));
export const ClockWarning24Filled = ( /*#__PURE__*/createFluentFontIcon("ClockWarning24Filled", "󰫯", 0, 24));
export const ClockWarning28Regular = ( /*#__PURE__*/createFluentFontIcon("ClockWarning28Regular", "󰩴", 1, 28));
export const ClockWarning28Filled = ( /*#__PURE__*/createFluentFontIcon("ClockWarning28Filled", "󰫰", 0, 28));
