"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudEditFilled = ( /*#__PURE__*/createFluentFontIcon("CloudEditFilled", "", 2, undefined));
export const CloudEditRegular = ( /*#__PURE__*/createFluentFontIcon("CloudEditRegular", "", 2, undefined));
export const CloudEdit16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudEdit16Regular", "", 1, 16));
export const CloudEdit16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudEdit16Filled", "", 0, 16));
export const CloudEdit20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudEdit20Regular", "", 1, 20));
export const CloudEdit20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudEdit20Filled", "", 0, 20));
export const CloudEdit24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudEdit24Regular", "", 1, 24));
export const CloudEdit24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudEdit24Filled", "", 0, 24));
