"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudErrorFilled = ( /*#__PURE__*/createFluentFontIcon("CloudErrorFilled", "", 2, undefined));
export const CloudErrorRegular = ( /*#__PURE__*/createFluentFontIcon("CloudErrorRegular", "", 2, undefined));
export const CloudError16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudError16Regular", "", 1, 16));
export const CloudError16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudError16Filled", "", 0, 16));
export const CloudError20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudError20Regular", "", 1, 20));
export const CloudError20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudError20Filled", "", 0, 20));
export const CloudError24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudError24Regular", "", 1, 24));
export const CloudError24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudError24Filled", "", 0, 24));
export const CloudError28Regular = ( /*#__PURE__*/createFluentFontIcon("CloudError28Regular", "", 1, 28));
export const CloudError28Filled = ( /*#__PURE__*/createFluentFontIcon("CloudError28Filled", "", 0, 28));
export const CloudError32Regular = ( /*#__PURE__*/createFluentFontIcon("CloudError32Regular", "", 1, 32));
export const CloudError32Filled = ( /*#__PURE__*/createFluentFontIcon("CloudError32Filled", "", 0, 32));
export const CloudError48Regular = ( /*#__PURE__*/createFluentFontIcon("CloudError48Regular", "", 1, 48));
export const CloudError48Filled = ( /*#__PURE__*/createFluentFontIcon("CloudError48Filled", "", 0, 48));
