"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudSyncFilled = ( /*#__PURE__*/createFluentFontIcon("CloudSyncFilled", "", 2, undefined));
export const CloudSyncRegular = ( /*#__PURE__*/createFluentFontIcon("CloudSyncRegular", "", 2, undefined));
export const CloudSync16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudSync16Regular", "", 1, 16));
export const CloudSync16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudSync16Filled", "", 0, 16));
export const CloudSync20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudSync20Regular", "", 1, 20));
export const CloudSync20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudSync20Filled", "", 0, 20));
export const CloudSync24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudSync24Regular", "", 1, 24));
export const CloudSync24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudSync24Filled", "", 0, 24));
export const CloudSync28Regular = ( /*#__PURE__*/createFluentFontIcon("CloudSync28Regular", "", 1, 28));
export const CloudSync28Filled = ( /*#__PURE__*/createFluentFontIcon("CloudSync28Filled", "", 0, 28));
export const CloudSync32Regular = ( /*#__PURE__*/createFluentFontIcon("CloudSync32Regular", "", 1, 32));
export const CloudSync32Filled = ( /*#__PURE__*/createFluentFontIcon("CloudSync32Filled", "", 0, 32));
export const CloudSync48Regular = ( /*#__PURE__*/createFluentFontIcon("CloudSync48Regular", "", 1, 48));
export const CloudSync48Filled = ( /*#__PURE__*/createFluentFontIcon("CloudSync48Filled", "", 0, 48));
