"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudBeakerFilled = ( /*#__PURE__*/createFluentFontIcon("CloudBeakerFilled", "", 2, undefined));
export const CloudBeakerRegular = ( /*#__PURE__*/createFluentFontIcon("CloudBeakerRegular", "", 2, undefined));
export const CloudBeaker16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker16Regular", "󰑯", 1, 16));
export const CloudBeaker16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker16Filled", "󰒂", 0, 16));
export const CloudBeaker20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker20Regular", "󰑰", 1, 20));
export const CloudBeaker20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker20Filled", "󰒃", 0, 20));
export const CloudBeaker24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker24Regular", "󰑱", 1, 24));
export const CloudBeaker24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker24Filled", "󰒄", 0, 24));
export const CloudBeaker28Regular = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker28Regular", "󰑲", 1, 28));
export const CloudBeaker28Filled = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker28Filled", "󰒅", 0, 28));
export const CloudBeaker32Regular = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker32Regular", "󰑳", 1, 32));
export const CloudBeaker32Filled = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker32Filled", "󰒆", 0, 32));
export const CloudBeaker48Regular = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker48Regular", "󰑴", 1, 48));
export const CloudBeaker48Filled = ( /*#__PURE__*/createFluentFontIcon("CloudBeaker48Filled", "󰒇", 0, 48));
