"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudFilled = ( /*#__PURE__*/createFluentFontIcon("CloudFilled", "", 2, undefined));
export const CloudRegular = ( /*#__PURE__*/createFluentFontIcon("CloudRegular", "", 2, undefined));
export const Cloud16Regular = ( /*#__PURE__*/createFluentFontIcon("Cloud16Regular", "", 1, 16));
export const Cloud16Filled = ( /*#__PURE__*/createFluentFontIcon("Cloud16Filled", "", 0, 16));
export const Cloud20Regular = ( /*#__PURE__*/createFluentFontIcon("Cloud20Regular", "", 1, 20));
export const Cloud20Filled = ( /*#__PURE__*/createFluentFontIcon("Cloud20Filled", "", 0, 20));
export const Cloud24Regular = ( /*#__PURE__*/createFluentFontIcon("Cloud24Regular", "", 1, 24));
export const Cloud24Filled = ( /*#__PURE__*/createFluentFontIcon("Cloud24Filled", "", 0, 24));
export const Cloud28Regular = ( /*#__PURE__*/createFluentFontIcon("Cloud28Regular", "", 1, 28));
export const Cloud28Filled = ( /*#__PURE__*/createFluentFontIcon("Cloud28Filled", "", 0, 28));
export const Cloud32Regular = ( /*#__PURE__*/createFluentFontIcon("Cloud32Regular", "", 1, 32));
export const Cloud32Filled = ( /*#__PURE__*/createFluentFontIcon("Cloud32Filled", "", 0, 32));
export const Cloud48Regular = ( /*#__PURE__*/createFluentFontIcon("Cloud48Regular", "", 1, 48));
export const Cloud48Filled = ( /*#__PURE__*/createFluentFontIcon("Cloud48Filled", "", 0, 48));
