"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudCubeFilled = ( /*#__PURE__*/createFluentFontIcon("CloudCubeFilled", "", 2, undefined));
export const CloudCubeRegular = ( /*#__PURE__*/createFluentFontIcon("CloudCubeRegular", "", 2, undefined));
export const CloudCube16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudCube16Regular", "󰑵", 1, 16));
export const CloudCube16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudCube16Filled", "󰒈", 0, 16));
export const CloudCube20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudCube20Regular", "󰑶", 1, 20));
export const CloudCube20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudCube20Filled", "󰒉", 0, 20));
export const CloudCube24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudCube24Regular", "󰑷", 1, 24));
export const CloudCube24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudCube24Filled", "󰒊", 0, 24));
export const CloudCube28Regular = ( /*#__PURE__*/createFluentFontIcon("CloudCube28Regular", "󰑸", 1, 28));
export const CloudCube28Filled = ( /*#__PURE__*/createFluentFontIcon("CloudCube28Filled", "󰒋", 0, 28));
export const CloudCube32Regular = ( /*#__PURE__*/createFluentFontIcon("CloudCube32Regular", "󰑹", 1, 32));
export const CloudCube32Filled = ( /*#__PURE__*/createFluentFontIcon("CloudCube32Filled", "󰒌", 0, 32));
export const CloudCube48Regular = ( /*#__PURE__*/createFluentFontIcon("CloudCube48Regular", "󰑺", 1, 48));
export const CloudCube48Filled = ( /*#__PURE__*/createFluentFontIcon("CloudCube48Filled", "󰒍", 0, 48));
