"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudLinkFilled = ( /*#__PURE__*/createFluentFontIcon("CloudLinkFilled", "", 2, undefined));
export const CloudLinkRegular = ( /*#__PURE__*/createFluentFontIcon("CloudLinkRegular", "", 2, undefined));
export const CloudLink16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudLink16Regular", "", 1, 16));
export const CloudLink16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudLink16Filled", "", 0, 16));
export const CloudLink20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudLink20Regular", "", 1, 20));
export const CloudLink20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudLink20Filled", "", 0, 20));
export const CloudLink24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudLink24Regular", "", 1, 24));
export const CloudLink24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudLink24Filled", "", 0, 24));
