"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloudAddFilled = ( /*#__PURE__*/createFluentFontIcon("CloudAddFilled", "", 2, undefined));
export const CloudAddRegular = ( /*#__PURE__*/createFluentFontIcon("CloudAddRegular", "", 2, undefined));
export const CloudAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("CloudAdd16Regular", "", 1, 16));
export const CloudAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("CloudAdd16Filled", "", 0, 16));
export const CloudAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("CloudAdd20Regular", "", 1, 20));
export const CloudAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("CloudAdd20Filled", "", 0, 20));
export const CloudAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("CloudAdd24Regular", "", 1, 24));
export const CloudAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("CloudAdd24Filled", "", 0, 24));
