"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CloverFilled = ( /*#__PURE__*/createFluentFontIcon("CloverFilled", "", 2, undefined));
export const CloverRegular = ( /*#__PURE__*/createFluentFontIcon("CloverRegular", "", 2, undefined));
export const Clover16Regular = ( /*#__PURE__*/createFluentFontIcon("Clover16Regular", "", 1, 16));
export const Clover16Filled = ( /*#__PURE__*/createFluentFontIcon("Clover16Filled", "", 0, 16));
export const Clover20Regular = ( /*#__PURE__*/createFluentFontIcon("Clover20Regular", "", 1, 20));
export const Clover20Filled = ( /*#__PURE__*/createFluentFontIcon("Clover20Filled", "󰀀", 0, 20));
export const Clover24Regular = ( /*#__PURE__*/createFluentFontIcon("Clover24Regular", "", 1, 24));
export const Clover24Filled = ( /*#__PURE__*/createFluentFontIcon("Clover24Filled", "󰀁", 0, 24));
export const Clover28Regular = ( /*#__PURE__*/createFluentFontIcon("Clover28Regular", "", 1, 28));
export const Clover28Filled = ( /*#__PURE__*/createFluentFontIcon("Clover28Filled", "󰀂", 0, 28));
export const Clover32Regular = ( /*#__PURE__*/createFluentFontIcon("Clover32Regular", "", 1, 32));
export const Clover32Filled = ( /*#__PURE__*/createFluentFontIcon("Clover32Filled", "󰀃", 0, 32));
export const Clover48Regular = ( /*#__PURE__*/createFluentFontIcon("Clover48Regular", "󰀀", 1, 48));
export const Clover48Filled = ( /*#__PURE__*/createFluentFontIcon("Clover48Filled", "󰀄", 0, 48));
