"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CodeCircleFilled = ( /*#__PURE__*/createFluentFontIcon("CodeCircleFilled", "", 2, undefined));
export const CodeCircleRegular = ( /*#__PURE__*/createFluentFontIcon("CodeCircleRegular", "", 2, undefined));
export const CodeCircle20Regular = ( /*#__PURE__*/createFluentFontIcon("CodeCircle20Regular", "", 1, 20));
export const CodeCircle20Filled = ( /*#__PURE__*/createFluentFontIcon("CodeCircle20Filled", "", 0, 20));
export const CodeCircle24Regular = ( /*#__PURE__*/createFluentFontIcon("CodeCircle24Regular", "󰄔", 1, 24));
export const CodeCircle24Filled = ( /*#__PURE__*/createFluentFontIcon("CodeCircle24Filled", "󰄓", 0, 24));
export const CodeCircle32Regular = ( /*#__PURE__*/createFluentFontIcon("CodeCircle32Regular", "󰄕", 1, 32));
export const CodeCircle32Filled = ( /*#__PURE__*/createFluentFontIcon("CodeCircle32Filled", "󰄔", 0, 32));
