"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CoinStackFilled = ( /*#__PURE__*/createFluentFontIcon("CoinStackFilled", "", 2, undefined));
export const CoinStackRegular = ( /*#__PURE__*/createFluentFontIcon("CoinStackRegular", "", 2, undefined));
export const CoinStack16Regular = ( /*#__PURE__*/createFluentFontIcon("CoinStack16Regular", "󰙣", 1, 16));
export const CoinStack16Filled = ( /*#__PURE__*/createFluentFontIcon("CoinStack16Filled", "󰛟", 0, 16));
export const CoinStack20Regular = ( /*#__PURE__*/createFluentFontIcon("CoinStack20Regular", "󰙤", 1, 20));
export const CoinStack20Filled = ( /*#__PURE__*/createFluentFontIcon("CoinStack20Filled", "󰛠", 0, 20));
export const CoinStack24Regular = ( /*#__PURE__*/createFluentFontIcon("CoinStack24Regular", "󰙥", 1, 24));
export const CoinStack24Filled = ( /*#__PURE__*/createFluentFontIcon("CoinStack24Filled", "󰛡", 0, 24));
