"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CollectionsEmptyFilled = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmptyFilled", "", 2, undefined));
export const CollectionsEmptyRegular = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmptyRegular", "", 2, undefined));
export const CollectionsEmpty16Regular = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmpty16Regular", "󰠨", 1, 16));
export const CollectionsEmpty16Filled = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmpty16Filled", "󰢥", 0, 16));
export const CollectionsEmpty20Regular = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmpty20Regular", "󰠩", 1, 20));
export const CollectionsEmpty20Filled = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmpty20Filled", "󰢦", 0, 20));
export const CollectionsEmpty24Regular = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmpty24Regular", "󰠪", 1, 24));
export const CollectionsEmpty24Filled = ( /*#__PURE__*/createFluentFontIcon("CollectionsEmpty24Filled", "󰢧", 0, 24));
