"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ColorLineFilled = ( /*#__PURE__*/createFluentFontIcon("ColorLineFilled", "", 2, undefined));
export const ColorLineRegular = ( /*#__PURE__*/createFluentFontIcon("ColorLineRegular", "", 2, undefined));
export const ColorLine16Regular = ( /*#__PURE__*/createFluentFontIcon("ColorLine16Regular", "", 1, 16));
export const ColorLine16Filled = ( /*#__PURE__*/createFluentFontIcon("ColorLine16Filled", "", 0, 16));
export const ColorLine20Regular = ( /*#__PURE__*/createFluentFontIcon("ColorLine20Regular", "", 1, 20));
export const ColorLine20Filled = ( /*#__PURE__*/createFluentFontIcon("ColorLine20Filled", "", 0, 20));
export const ColorLine24Regular = ( /*#__PURE__*/createFluentFontIcon("ColorLine24Regular", "", 1, 24));
export const ColorLine24Filled = ( /*#__PURE__*/createFluentFontIcon("ColorLine24Filled", "", 0, 24));
