"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CommentOffFilled = ( /*#__PURE__*/createFluentFontIcon("CommentOffFilled", "", 2, undefined, { flipInRtl: true }));
export const CommentOffRegular = ( /*#__PURE__*/createFluentFontIcon("CommentOffRegular", "", 2, undefined, { flipInRtl: true }));
export const CommentOff16Regular = ( /*#__PURE__*/createFluentFontIcon("CommentOff16Regular", "", 1, 16, { flipInRtl: true }));
export const CommentOff16Filled = ( /*#__PURE__*/createFluentFontIcon("CommentOff16Filled", "", 0, 16, { flipInRtl: true }));
export const CommentOff20Regular = ( /*#__PURE__*/createFluentFontIcon("CommentOff20Regular", "", 1, 20, { flipInRtl: true }));
export const CommentOff20Filled = ( /*#__PURE__*/createFluentFontIcon("CommentOff20Filled", "", 0, 20, { flipInRtl: true }));
export const CommentOff24Regular = ( /*#__PURE__*/createFluentFontIcon("CommentOff24Regular", "", 1, 24, { flipInRtl: true }));
export const CommentOff24Filled = ( /*#__PURE__*/createFluentFontIcon("CommentOff24Filled", "", 0, 24, { flipInRtl: true }));
export const CommentOff28Regular = ( /*#__PURE__*/createFluentFontIcon("CommentOff28Regular", "", 1, 28, { flipInRtl: true }));
export const CommentOff28Filled = ( /*#__PURE__*/createFluentFontIcon("CommentOff28Filled", "", 0, 28, { flipInRtl: true }));
export const CommentOff48Regular = ( /*#__PURE__*/createFluentFontIcon("CommentOff48Regular", "", 1, 48, { flipInRtl: true }));
export const CommentOff48Filled = ( /*#__PURE__*/createFluentFontIcon("CommentOff48Filled", "", 0, 48, { flipInRtl: true }));
