"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CommentQuoteFilled = ( /*#__PURE__*/createFluentFontIcon("CommentQuoteFilled", "", 2, undefined));
export const CommentQuoteRegular = ( /*#__PURE__*/createFluentFontIcon("CommentQuoteRegular", "", 2, undefined));
export const CommentQuote16Regular = ( /*#__PURE__*/createFluentFontIcon("CommentQuote16Regular", "󰛫", 1, 16));
export const CommentQuote16Filled = ( /*#__PURE__*/createFluentFontIcon("CommentQuote16Filled", "󰝨", 0, 16));
export const CommentQuote20Regular = ( /*#__PURE__*/createFluentFontIcon("CommentQuote20Regular", "󰛬", 1, 20));
export const CommentQuote20Filled = ( /*#__PURE__*/createFluentFontIcon("CommentQuote20Filled", "󰝩", 0, 20));
export const CommentQuote24Regular = ( /*#__PURE__*/createFluentFontIcon("CommentQuote24Regular", "󰛭", 1, 24));
export const CommentQuote24Filled = ( /*#__PURE__*/createFluentFontIcon("CommentQuote24Filled", "󰝪", 0, 24));
export const CommentQuote28Regular = ( /*#__PURE__*/createFluentFontIcon("CommentQuote28Regular", "󰛮", 1, 28));
export const CommentQuote28Filled = ( /*#__PURE__*/createFluentFontIcon("CommentQuote28Filled", "󰝫", 0, 28));
