"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CommentFilled = ( /*#__PURE__*/createFluentFontIcon("CommentFilled", "", 2, undefined, { flipInRtl: true }));
export const CommentRegular = ( /*#__PURE__*/createFluentFontIcon("CommentRegular", "", 2, undefined, { flipInRtl: true }));
export const Comment12Regular = ( /*#__PURE__*/createFluentFontIcon("Comment12Regular", "", 1, 12, { flipInRtl: true }));
export const Comment12Filled = ( /*#__PURE__*/createFluentFontIcon("Comment12Filled", "", 0, 12, { flipInRtl: true }));
export const Comment16Regular = ( /*#__PURE__*/createFluentFontIcon("Comment16Regular", "", 1, 16, { flipInRtl: true }));
export const Comment16Filled = ( /*#__PURE__*/createFluentFontIcon("Comment16Filled", "", 0, 16, { flipInRtl: true }));
export const Comment20Regular = ( /*#__PURE__*/createFluentFontIcon("Comment20Regular", "", 1, 20, { flipInRtl: true }));
export const Comment20Filled = ( /*#__PURE__*/createFluentFontIcon("Comment20Filled", "", 0, 20, { flipInRtl: true }));
export const Comment24Regular = ( /*#__PURE__*/createFluentFontIcon("Comment24Regular", "", 1, 24, { flipInRtl: true }));
export const Comment24Filled = ( /*#__PURE__*/createFluentFontIcon("Comment24Filled", "", 0, 24, { flipInRtl: true }));
export const Comment28Regular = ( /*#__PURE__*/createFluentFontIcon("Comment28Regular", "", 1, 28, { flipInRtl: true }));
export const Comment28Filled = ( /*#__PURE__*/createFluentFontIcon("Comment28Filled", "", 0, 28, { flipInRtl: true }));
export const Comment32Regular = ( /*#__PURE__*/createFluentFontIcon("Comment32Regular", "󰗦", 1, 32, { flipInRtl: true }));
export const Comment32Filled = ( /*#__PURE__*/createFluentFontIcon("Comment32Filled", "󰙢", 0, 32, { flipInRtl: true }));
export const Comment32Light = ( /*#__PURE__*/createFluentFontIcon("Comment32Light", "", 3, 32));
export const Comment48Regular = ( /*#__PURE__*/createFluentFontIcon("Comment48Regular", "", 1, 48, { flipInRtl: true }));
export const Comment48Filled = ( /*#__PURE__*/createFluentFontIcon("Comment48Filled", "", 0, 48, { flipInRtl: true }));
