"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CommentAddFilled = ( /*#__PURE__*/createFluentFontIcon("CommentAddFilled", "", 2, undefined, { flipInRtl: true }));
export const CommentAddRegular = ( /*#__PURE__*/createFluentFontIcon("CommentAddRegular", "", 2, undefined, { flipInRtl: true }));
export const CommentAdd12Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd12Regular", "", 1, 12, { flipInRtl: true }));
export const CommentAdd12Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd12Filled", "", 0, 12, { flipInRtl: true }));
export const CommentAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd16Regular", "", 1, 16, { flipInRtl: true }));
export const CommentAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd16Filled", "", 0, 16, { flipInRtl: true }));
export const CommentAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd20Regular", "", 1, 20, { flipInRtl: true }));
export const CommentAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd20Filled", "", 0, 20, { flipInRtl: true }));
export const CommentAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd24Regular", "", 1, 24, { flipInRtl: true }));
export const CommentAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd24Filled", "", 0, 24, { flipInRtl: true }));
export const CommentAdd28Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd28Regular", "", 1, 28, { flipInRtl: true }));
export const CommentAdd28Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd28Filled", "", 0, 28, { flipInRtl: true }));
export const CommentAdd32Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd32Regular", "󰗧", 1, 32, { flipInRtl: true }));
export const CommentAdd32Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd32Filled", "󰙣", 0, 32, { flipInRtl: true }));
export const CommentAdd32Light = ( /*#__PURE__*/createFluentFontIcon("CommentAdd32Light", "", 3, 32));
export const CommentAdd48Regular = ( /*#__PURE__*/createFluentFontIcon("CommentAdd48Regular", "", 1, 48, { flipInRtl: true }));
export const CommentAdd48Filled = ( /*#__PURE__*/createFluentFontIcon("CommentAdd48Filled", "", 0, 48, { flipInRtl: true }));
