"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CommentEditFilled = ( /*#__PURE__*/createFluentFontIcon("CommentEditFilled", "", 2, undefined, { flipInRtl: true }));
export const CommentEditRegular = ( /*#__PURE__*/createFluentFontIcon("CommentEditRegular", "", 2, undefined, { flipInRtl: true }));
export const CommentEdit16Regular = ( /*#__PURE__*/createFluentFontIcon("CommentEdit16Regular", "󰈎", 1, 16, { flipInRtl: true }));
export const CommentEdit16Filled = ( /*#__PURE__*/createFluentFontIcon("CommentEdit16Filled", "󰈎", 0, 16, { flipInRtl: true }));
export const CommentEdit20Regular = ( /*#__PURE__*/createFluentFontIcon("CommentEdit20Regular", "", 1, 20, { flipInRtl: true }));
export const CommentEdit20Filled = ( /*#__PURE__*/createFluentFontIcon("CommentEdit20Filled", "", 0, 20, { flipInRtl: true }));
export const CommentEdit24Regular = ( /*#__PURE__*/createFluentFontIcon("CommentEdit24Regular", "", 1, 24, { flipInRtl: true }));
export const CommentEdit24Filled = ( /*#__PURE__*/createFluentFontIcon("CommentEdit24Filled", "", 0, 24, { flipInRtl: true }));
