"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CommentMentionFilled = ( /*#__PURE__*/createFluentFontIcon("CommentMentionFilled", "", 2, undefined, { flipInRtl: true }));
export const CommentMentionRegular = ( /*#__PURE__*/createFluentFontIcon("CommentMentionRegular", "", 2, undefined, { flipInRtl: true }));
export const CommentMention16Regular = ( /*#__PURE__*/createFluentFontIcon("CommentMention16Regular", "", 1, 16, { flipInRtl: true }));
export const CommentMention16Filled = ( /*#__PURE__*/createFluentFontIcon("CommentMention16Filled", "", 0, 16, { flipInRtl: true }));
export const CommentMention20Regular = ( /*#__PURE__*/createFluentFontIcon("CommentMention20Regular", "", 1, 20, { flipInRtl: true }));
export const CommentMention20Filled = ( /*#__PURE__*/createFluentFontIcon("CommentMention20Filled", "", 0, 20, { flipInRtl: true }));
export const CommentMention24Regular = ( /*#__PURE__*/createFluentFontIcon("CommentMention24Regular", "", 1, 24, { flipInRtl: true }));
export const CommentMention24Filled = ( /*#__PURE__*/createFluentFontIcon("CommentMention24Filled", "", 0, 24, { flipInRtl: true }));
