"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ComposeFilled = ( /*#__PURE__*/createFluentFontIcon("ComposeFilled", "", 2, undefined));
export const ComposeRegular = ( /*#__PURE__*/createFluentFontIcon("ComposeRegular", "", 2, undefined));
export const Compose12Regular = ( /*#__PURE__*/createFluentFontIcon("Compose12Regular", "󰔊", 1, 12));
export const Compose12Filled = ( /*#__PURE__*/createFluentFontIcon("Compose12Filled", "󰖃", 0, 12));
export const Compose16Regular = ( /*#__PURE__*/createFluentFontIcon("Compose16Regular", "", 1, 16));
export const Compose16Filled = ( /*#__PURE__*/createFluentFontIcon("Compose16Filled", "", 0, 16));
export const Compose20Regular = ( /*#__PURE__*/createFluentFontIcon("Compose20Regular", "", 1, 20));
export const Compose20Filled = ( /*#__PURE__*/createFluentFontIcon("Compose20Filled", "", 0, 20));
export const Compose24Regular = ( /*#__PURE__*/createFluentFontIcon("Compose24Regular", "", 1, 24));
export const Compose24Filled = ( /*#__PURE__*/createFluentFontIcon("Compose24Filled", "", 0, 24));
export const Compose28Regular = ( /*#__PURE__*/createFluentFontIcon("Compose28Regular", "", 1, 28));
export const Compose28Filled = ( /*#__PURE__*/createFluentFontIcon("Compose28Filled", "", 0, 28));
export const Compose32Regular = ( /*#__PURE__*/createFluentFontIcon("Compose32Regular", "󰔋", 1, 32));
export const Compose32Filled = ( /*#__PURE__*/createFluentFontIcon("Compose32Filled", "󰖄", 0, 32));
export const Compose32Light = ( /*#__PURE__*/createFluentFontIcon("Compose32Light", "", 3, 32));
export const Compose48Regular = ( /*#__PURE__*/createFluentFontIcon("Compose48Regular", "󰔌", 1, 48));
export const Compose48Filled = ( /*#__PURE__*/createFluentFontIcon("Compose48Filled", "󰖅", 0, 48));
