"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CopyFilled = ( /*#__PURE__*/createFluentFontIcon("CopyFilled", "", 2, undefined));
export const CopyRegular = ( /*#__PURE__*/createFluentFontIcon("CopyRegular", "", 2, undefined));
export const Copy16Regular = ( /*#__PURE__*/createFluentFontIcon("Copy16Regular", "", 1, 16));
export const Copy16Filled = ( /*#__PURE__*/createFluentFontIcon("Copy16Filled", "", 0, 16));
export const Copy20Regular = ( /*#__PURE__*/createFluentFontIcon("Copy20Regular", "", 1, 20));
export const Copy20Filled = ( /*#__PURE__*/createFluentFontIcon("Copy20Filled", "", 0, 20));
export const Copy24Regular = ( /*#__PURE__*/createFluentFontIcon("Copy24Regular", "", 1, 24));
export const Copy24Filled = ( /*#__PURE__*/createFluentFontIcon("Copy24Filled", "", 0, 24));
export const Copy28Regular = ( /*#__PURE__*/createFluentFontIcon("Copy28Regular", "󰟕", 1, 28));
export const Copy28Filled = ( /*#__PURE__*/createFluentFontIcon("Copy28Filled", "󰡒", 0, 28));
export const Copy32Regular = ( /*#__PURE__*/createFluentFontIcon("Copy32Regular", "󰀆", 1, 32));
export const Copy32Filled = ( /*#__PURE__*/createFluentFontIcon("Copy32Filled", "󰀊", 0, 32));
export const Copy32Light = ( /*#__PURE__*/createFluentFontIcon("Copy32Light", "", 3, 32));
