"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CouchFilled = ( /*#__PURE__*/createFluentFontIcon("CouchFilled", "", 2, undefined));
export const CouchRegular = ( /*#__PURE__*/createFluentFontIcon("CouchRegular", "", 2, undefined));
export const Couch12Regular = ( /*#__PURE__*/createFluentFontIcon("Couch12Regular", "", 1, 12));
export const Couch12Filled = ( /*#__PURE__*/createFluentFontIcon("Couch12Filled", "", 0, 12));
export const Couch20Regular = ( /*#__PURE__*/createFluentFontIcon("Couch20Regular", "", 1, 20));
export const Couch20Filled = ( /*#__PURE__*/createFluentFontIcon("Couch20Filled", "", 0, 20));
export const Couch24Regular = ( /*#__PURE__*/createFluentFontIcon("Couch24Regular", "", 1, 24));
export const Couch24Filled = ( /*#__PURE__*/createFluentFontIcon("Couch24Filled", "", 0, 24));
export const Couch32Regular = ( /*#__PURE__*/createFluentFontIcon("Couch32Regular", "", 1, 32));
export const Couch32Filled = ( /*#__PURE__*/createFluentFontIcon("Couch32Filled", "", 0, 32));
export const Couch48Regular = ( /*#__PURE__*/createFluentFontIcon("Couch48Regular", "", 1, 48));
export const Couch48Filled = ( /*#__PURE__*/createFluentFontIcon("Couch48Filled", "", 0, 48));
