"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const CubeFilled = ( /*#__PURE__*/createFluentFontIcon("CubeFilled", "", 2, undefined));
export const CubeRegular = ( /*#__PURE__*/createFluentFontIcon("CubeRegular", "", 2, undefined));
export const Cube12Regular = ( /*#__PURE__*/createFluentFontIcon("Cube12Regular", "", 1, 12));
export const Cube12Filled = ( /*#__PURE__*/createFluentFontIcon("Cube12Filled", "", 0, 12));
export const Cube16Regular = ( /*#__PURE__*/createFluentFontIcon("Cube16Regular", "", 1, 16));
export const Cube16Filled = ( /*#__PURE__*/createFluentFontIcon("Cube16Filled", "", 0, 16));
export const Cube20Regular = ( /*#__PURE__*/createFluentFontIcon("Cube20Regular", "", 1, 20));
export const Cube20Filled = ( /*#__PURE__*/createFluentFontIcon("Cube20Filled", "", 0, 20));
export const Cube24Regular = ( /*#__PURE__*/createFluentFontIcon("Cube24Regular", "", 1, 24));
export const Cube24Filled = ( /*#__PURE__*/createFluentFontIcon("Cube24Filled", "", 0, 24));
export const Cube28Regular = ( /*#__PURE__*/createFluentFontIcon("Cube28Regular", "󰠬", 1, 28));
export const Cube28Filled = ( /*#__PURE__*/createFluentFontIcon("Cube28Filled", "󰢩", 0, 28));
export const Cube32Regular = ( /*#__PURE__*/createFluentFontIcon("Cube32Regular", "", 1, 32));
export const Cube32Filled = ( /*#__PURE__*/createFluentFontIcon("Cube32Filled", "", 0, 32));
export const Cube48Regular = ( /*#__PURE__*/createFluentFontIcon("Cube48Regular", "󰉨", 1, 48));
export const Cube48Filled = ( /*#__PURE__*/createFluentFontIcon("Cube48Filled", "󰉻", 0, 48));
