"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DataPieFilled = ( /*#__PURE__*/createFluentFontIcon("DataPieFilled", "", 2, undefined));
export const DataPieRegular = ( /*#__PURE__*/createFluentFontIcon("DataPieRegular", "", 2, undefined));
export const DataPie16Regular = ( /*#__PURE__*/createFluentFontIcon("DataPie16Regular", "󰗖", 1, 16));
export const DataPie16Filled = ( /*#__PURE__*/createFluentFontIcon("DataPie16Filled", "󰙏", 0, 16));
export const DataPie20Regular = ( /*#__PURE__*/createFluentFontIcon("DataPie20Regular", "", 1, 20));
export const DataPie20Filled = ( /*#__PURE__*/createFluentFontIcon("DataPie20Filled", "", 0, 20));
export const DataPie24Regular = ( /*#__PURE__*/createFluentFontIcon("DataPie24Regular", "", 1, 24));
export const DataPie24Filled = ( /*#__PURE__*/createFluentFontIcon("DataPie24Filled", "", 0, 24));
export const DataPie32Regular = ( /*#__PURE__*/createFluentFontIcon("DataPie32Regular", "󰠵", 1, 32));
export const DataPie32Filled = ( /*#__PURE__*/createFluentFontIcon("DataPie32Filled", "󰢲", 0, 32));
