"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DeleteFilled = ( /*#__PURE__*/createFluentFontIcon("DeleteFilled", "", 2, undefined));
export const DeleteRegular = ( /*#__PURE__*/createFluentFontIcon("DeleteRegular", "", 2, undefined));
export const Delete12Regular = ( /*#__PURE__*/createFluentFontIcon("Delete12Regular", "", 1, 12));
export const Delete12Filled = ( /*#__PURE__*/createFluentFontIcon("Delete12Filled", "", 0, 12));
export const Delete16Regular = ( /*#__PURE__*/createFluentFontIcon("Delete16Regular", "", 1, 16));
export const Delete16Filled = ( /*#__PURE__*/createFluentFontIcon("Delete16Filled", "", 0, 16));
export const Delete20Regular = ( /*#__PURE__*/createFluentFontIcon("Delete20Regular", "", 1, 20));
export const Delete20Filled = ( /*#__PURE__*/createFluentFontIcon("Delete20Filled", "", 0, 20));
export const Delete24Regular = ( /*#__PURE__*/createFluentFontIcon("Delete24Regular", "", 1, 24));
export const Delete24Filled = ( /*#__PURE__*/createFluentFontIcon("Delete24Filled", "", 0, 24));
export const Delete28Regular = ( /*#__PURE__*/createFluentFontIcon("Delete28Regular", "", 1, 28));
export const Delete28Filled = ( /*#__PURE__*/createFluentFontIcon("Delete28Filled", "", 0, 28));
export const Delete32Regular = ( /*#__PURE__*/createFluentFontIcon("Delete32Regular", "", 1, 32));
export const Delete32Filled = ( /*#__PURE__*/createFluentFontIcon("Delete32Filled", "", 0, 32));
export const Delete32Light = ( /*#__PURE__*/createFluentFontIcon("Delete32Light", "", 3, 32));
export const Delete48Regular = ( /*#__PURE__*/createFluentFontIcon("Delete48Regular", "", 1, 48));
export const Delete48Filled = ( /*#__PURE__*/createFluentFontIcon("Delete48Filled", "", 0, 48));
