"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DentistFilled = ( /*#__PURE__*/createFluentFontIcon("DentistFilled", "", 2, undefined));
export const DentistRegular = ( /*#__PURE__*/createFluentFontIcon("DentistRegular", "", 2, undefined));
export const Dentist12Regular = ( /*#__PURE__*/createFluentFontIcon("Dentist12Regular", "", 1, 12));
export const Dentist12Filled = ( /*#__PURE__*/createFluentFontIcon("Dentist12Filled", "", 0, 12));
export const Dentist16Regular = ( /*#__PURE__*/createFluentFontIcon("Dentist16Regular", "", 1, 16));
export const Dentist16Filled = ( /*#__PURE__*/createFluentFontIcon("Dentist16Filled", "", 0, 16));
export const Dentist20Regular = ( /*#__PURE__*/createFluentFontIcon("Dentist20Regular", "", 1, 20));
export const Dentist20Filled = ( /*#__PURE__*/createFluentFontIcon("Dentist20Filled", "", 0, 20));
export const Dentist24Regular = ( /*#__PURE__*/createFluentFontIcon("Dentist24Regular", "", 1, 24));
export const Dentist24Filled = ( /*#__PURE__*/createFluentFontIcon("Dentist24Filled", "", 0, 24));
export const Dentist28Regular = ( /*#__PURE__*/createFluentFontIcon("Dentist28Regular", "", 1, 28));
export const Dentist28Filled = ( /*#__PURE__*/createFluentFontIcon("Dentist28Filled", "", 0, 28));
export const Dentist48Regular = ( /*#__PURE__*/createFluentFontIcon("Dentist48Regular", "", 1, 48));
export const Dentist48Filled = ( /*#__PURE__*/createFluentFontIcon("Dentist48Filled", "", 0, 48));
