"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DeskSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("DeskSparkleFilled", "", 2, undefined));
export const DeskSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("DeskSparkleRegular", "", 2, undefined));
export const DeskSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("DeskSparkle16Regular", "󰧳", 1, 16));
export const DeskSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("DeskSparkle16Filled", "󰩰", 0, 16));
export const DeskSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("DeskSparkle20Regular", "󰧗", 1, 20));
export const DeskSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("DeskSparkle20Filled", "󰩔", 0, 20));
export const DeskSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("DeskSparkle24Regular", "󰧘", 1, 24));
export const DeskSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("DeskSparkle24Filled", "󰩕", 0, 24));
