"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DesktopCursorFilled = ( /*#__PURE__*/createFluentFontIcon("DesktopCursorFilled", "", 2, undefined));
export const DesktopCursorRegular = ( /*#__PURE__*/createFluentFontIcon("DesktopCursorRegular", "", 2, undefined));
export const DesktopCursor16Regular = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor16Regular", "", 1, 16));
export const DesktopCursor16Filled = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor16Filled", "", 0, 16));
export const DesktopCursor20Regular = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor20Regular", "", 1, 20));
export const DesktopCursor20Filled = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor20Filled", "", 0, 20));
export const DesktopCursor24Regular = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor24Regular", "", 1, 24));
export const DesktopCursor24Filled = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor24Filled", "", 0, 24));
export const DesktopCursor28Regular = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor28Regular", "", 1, 28));
export const DesktopCursor28Filled = ( /*#__PURE__*/createFluentFontIcon("DesktopCursor28Filled", "", 0, 28));
