"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DeveloperBoardFilled = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoardFilled", "", 2, undefined));
export const DeveloperBoardRegular = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoardRegular", "", 2, undefined));
export const DeveloperBoard16Regular = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoard16Regular", "", 1, 16));
export const DeveloperBoard16Filled = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoard16Filled", "", 0, 16));
export const DeveloperBoard20Regular = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoard20Regular", "", 1, 20));
export const DeveloperBoard20Filled = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoard20Filled", "", 0, 20));
export const DeveloperBoard24Regular = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoard24Regular", "", 1, 24));
export const DeveloperBoard24Filled = ( /*#__PURE__*/createFluentFontIcon("DeveloperBoard24Filled", "", 0, 24));
