"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DeviceEqFilled = ( /*#__PURE__*/createFluentFontIcon("DeviceEqFilled", "", 2, undefined));
export const DeviceEqRegular = ( /*#__PURE__*/createFluentFontIcon("DeviceEqRegular", "", 2, undefined));
export const DeviceEq16Regular = ( /*#__PURE__*/createFluentFontIcon("DeviceEq16Regular", "󰀊", 1, 16));
export const DeviceEq16Filled = ( /*#__PURE__*/createFluentFontIcon("DeviceEq16Filled", "󰀎", 0, 16));
export const DeviceEq20Regular = ( /*#__PURE__*/createFluentFontIcon("DeviceEq20Regular", "", 1, 20));
export const DeviceEq20Filled = ( /*#__PURE__*/createFluentFontIcon("DeviceEq20Filled", "", 0, 20));
export const DeviceEq24Regular = ( /*#__PURE__*/createFluentFontIcon("DeviceEq24Regular", "", 1, 24));
export const DeviceEq24Filled = ( /*#__PURE__*/createFluentFontIcon("DeviceEq24Filled", "", 0, 24));
export const DeviceEq28Regular = ( /*#__PURE__*/createFluentFontIcon("DeviceEq28Regular", "󰫒", 1, 28));
export const DeviceEq28Filled = ( /*#__PURE__*/createFluentFontIcon("DeviceEq28Filled", "󰭐", 0, 28));
export const DeviceEq32Regular = ( /*#__PURE__*/createFluentFontIcon("DeviceEq32Regular", "󰫓", 1, 32));
export const DeviceEq32Filled = ( /*#__PURE__*/createFluentFontIcon("DeviceEq32Filled", "󰭑", 0, 32));
export const DeviceEq48Regular = ( /*#__PURE__*/createFluentFontIcon("DeviceEq48Regular", "󰫔", 1, 48));
export const DeviceEq48Filled = ( /*#__PURE__*/createFluentFontIcon("DeviceEq48Filled", "󰭒", 0, 48));
