"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DiamondLinkFilled = ( /*#__PURE__*/createFluentFontIcon("DiamondLinkFilled", "", 2, undefined));
export const DiamondLinkRegular = ( /*#__PURE__*/createFluentFontIcon("DiamondLinkRegular", "", 2, undefined));
export const DiamondLink16Regular = ( /*#__PURE__*/createFluentFontIcon("DiamondLink16Regular", "󰫕", 1, 16));
export const DiamondLink16Filled = ( /*#__PURE__*/createFluentFontIcon("DiamondLink16Filled", "󰭓", 0, 16));
export const DiamondLink20Regular = ( /*#__PURE__*/createFluentFontIcon("DiamondLink20Regular", "󰫖", 1, 20));
export const DiamondLink20Filled = ( /*#__PURE__*/createFluentFontIcon("DiamondLink20Filled", "󰭔", 0, 20));
export const DiamondLink24Regular = ( /*#__PURE__*/createFluentFontIcon("DiamondLink24Regular", "󰫗", 1, 24));
export const DiamondLink24Filled = ( /*#__PURE__*/createFluentFontIcon("DiamondLink24Filled", "󰭕", 0, 24));
export const DiamondLink28Regular = ( /*#__PURE__*/createFluentFontIcon("DiamondLink28Regular", "󰫘", 1, 28));
export const DiamondLink28Filled = ( /*#__PURE__*/createFluentFontIcon("DiamondLink28Filled", "󰭖", 0, 28));
export const DiamondLink32Regular = ( /*#__PURE__*/createFluentFontIcon("DiamondLink32Regular", "󰫙", 1, 32));
export const DiamondLink32Filled = ( /*#__PURE__*/createFluentFontIcon("DiamondLink32Filled", "󰭗", 0, 32));
export const DiamondLink48Regular = ( /*#__PURE__*/createFluentFontIcon("DiamondLink48Regular", "󰫚", 1, 48));
export const DiamondLink48Filled = ( /*#__PURE__*/createFluentFontIcon("DiamondLink48Filled", "󰭘", 0, 48));
