"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DiamondFilled = ( /*#__PURE__*/createFluentFontIcon("DiamondFilled", "", 2, undefined));
export const DiamondRegular = ( /*#__PURE__*/createFluentFontIcon("DiamondRegular", "", 2, undefined));
export const Diamond16Regular = ( /*#__PURE__*/createFluentFontIcon("Diamond16Regular", "", 1, 16));
export const Diamond16Filled = ( /*#__PURE__*/createFluentFontIcon("Diamond16Filled", "", 0, 16));
export const Diamond20Regular = ( /*#__PURE__*/createFluentFontIcon("Diamond20Regular", "", 1, 20));
export const Diamond20Filled = ( /*#__PURE__*/createFluentFontIcon("Diamond20Filled", "", 0, 20));
export const Diamond24Regular = ( /*#__PURE__*/createFluentFontIcon("Diamond24Regular", "", 1, 24));
export const Diamond24Filled = ( /*#__PURE__*/createFluentFontIcon("Diamond24Filled", "", 0, 24));
export const Diamond28Regular = ( /*#__PURE__*/createFluentFontIcon("Diamond28Regular", "", 1, 28));
export const Diamond28Filled = ( /*#__PURE__*/createFluentFontIcon("Diamond28Filled", "", 0, 28));
export const Diamond32Regular = ( /*#__PURE__*/createFluentFontIcon("Diamond32Regular", "", 1, 32));
export const Diamond32Filled = ( /*#__PURE__*/createFluentFontIcon("Diamond32Filled", "", 0, 32));
export const Diamond48Regular = ( /*#__PURE__*/createFluentFontIcon("Diamond48Regular", "", 1, 48));
export const Diamond48Filled = ( /*#__PURE__*/createFluentFontIcon("Diamond48Filled", "", 0, 48));
