"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DirectionsFilled = ( /*#__PURE__*/createFluentFontIcon("DirectionsFilled", "", 2, undefined));
export const DirectionsRegular = ( /*#__PURE__*/createFluentFontIcon("DirectionsRegular", "", 2, undefined));
export const Directions16Regular = ( /*#__PURE__*/createFluentFontIcon("Directions16Regular", "", 1, 16));
export const Directions16Filled = ( /*#__PURE__*/createFluentFontIcon("Directions16Filled", "", 0, 16));
export const Directions20Regular = ( /*#__PURE__*/createFluentFontIcon("Directions20Regular", "", 1, 20));
export const Directions20Filled = ( /*#__PURE__*/createFluentFontIcon("Directions20Filled", "", 0, 20));
export const Directions24Regular = ( /*#__PURE__*/createFluentFontIcon("Directions24Regular", "", 1, 24));
export const Directions24Filled = ( /*#__PURE__*/createFluentFontIcon("Directions24Filled", "", 0, 24));
export const Directions28Regular = ( /*#__PURE__*/createFluentFontIcon("Directions28Regular", "󰞩", 1, 28));
export const Directions28Filled = ( /*#__PURE__*/createFluentFontIcon("Directions28Filled", "󰠦", 0, 28));
export const Directions32Regular = ( /*#__PURE__*/createFluentFontIcon("Directions32Regular", "󰞪", 1, 32));
export const Directions32Filled = ( /*#__PURE__*/createFluentFontIcon("Directions32Filled", "󰠧", 0, 32));
export const Directions48Regular = ( /*#__PURE__*/createFluentFontIcon("Directions48Regular", "󰞫", 1, 48));
export const Directions48Filled = ( /*#__PURE__*/createFluentFontIcon("Directions48Filled", "󰠨", 0, 48));
