"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DismissCircleFilled = ( /*#__PURE__*/createFluentFontIcon("DismissCircleFilled", "", 2, undefined));
export const DismissCircleRegular = ( /*#__PURE__*/createFluentFontIcon("DismissCircleRegular", "", 2, undefined));
export const DismissCircle12Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle12Regular", "", 1, 12));
export const DismissCircle12Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle12Filled", "", 0, 12));
export const DismissCircle16Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle16Regular", "", 1, 16));
export const DismissCircle16Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle16Filled", "", 0, 16));
export const DismissCircle20Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle20Regular", "", 1, 20));
export const DismissCircle20Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle20Filled", "", 0, 20));
export const DismissCircle24Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle24Regular", "", 1, 24));
export const DismissCircle24Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle24Filled", "", 0, 24));
export const DismissCircle28Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle28Regular", "", 1, 28));
export const DismissCircle28Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle28Filled", "", 0, 28));
export const DismissCircle32Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle32Regular", "", 1, 32));
export const DismissCircle32Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle32Filled", "", 0, 32));
export const DismissCircle32Light = ( /*#__PURE__*/createFluentFontIcon("DismissCircle32Light", "", 3, 32));
export const DismissCircle48Regular = ( /*#__PURE__*/createFluentFontIcon("DismissCircle48Regular", "", 1, 48));
export const DismissCircle48Filled = ( /*#__PURE__*/createFluentFontIcon("DismissCircle48Filled", "", 0, 48));
