"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DiversityFilled = ( /*#__PURE__*/createFluentFontIcon("DiversityFilled", "", 2, undefined));
export const DiversityRegular = ( /*#__PURE__*/createFluentFontIcon("DiversityRegular", "", 2, undefined));
export const Diversity16Regular = ( /*#__PURE__*/createFluentFontIcon("Diversity16Regular", "󰐱", 1, 16));
export const Diversity16Filled = ( /*#__PURE__*/createFluentFontIcon("Diversity16Filled", "󰑄", 0, 16));
export const Diversity20Regular = ( /*#__PURE__*/createFluentFontIcon("Diversity20Regular", "", 1, 20));
export const Diversity20Filled = ( /*#__PURE__*/createFluentFontIcon("Diversity20Filled", "", 0, 20));
export const Diversity24Regular = ( /*#__PURE__*/createFluentFontIcon("Diversity24Regular", "", 1, 24));
export const Diversity24Filled = ( /*#__PURE__*/createFluentFontIcon("Diversity24Filled", "", 0, 24));
export const Diversity28Regular = ( /*#__PURE__*/createFluentFontIcon("Diversity28Regular", "", 1, 28));
export const Diversity28Filled = ( /*#__PURE__*/createFluentFontIcon("Diversity28Filled", "", 0, 28));
export const Diversity48Regular = ( /*#__PURE__*/createFluentFontIcon("Diversity48Regular", "", 1, 48));
export const Diversity48Filled = ( /*#__PURE__*/createFluentFontIcon("Diversity48Filled", "", 0, 48));
