"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DividerShortFilled = ( /*#__PURE__*/createFluentFontIcon("DividerShortFilled", "", 2, undefined));
export const DividerShortRegular = ( /*#__PURE__*/createFluentFontIcon("DividerShortRegular", "", 2, undefined));
export const DividerShort16Regular = ( /*#__PURE__*/createFluentFontIcon("DividerShort16Regular", "", 1, 16));
export const DividerShort16Filled = ( /*#__PURE__*/createFluentFontIcon("DividerShort16Filled", "", 0, 16));
export const DividerShort20Regular = ( /*#__PURE__*/createFluentFontIcon("DividerShort20Regular", "", 1, 20));
export const DividerShort20Filled = ( /*#__PURE__*/createFluentFontIcon("DividerShort20Filled", "", 0, 20));
export const DividerShort24Regular = ( /*#__PURE__*/createFluentFontIcon("DividerShort24Regular", "", 1, 24));
export const DividerShort24Filled = ( /*#__PURE__*/createFluentFontIcon("DividerShort24Filled", "", 0, 24));
