"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DividerTallFilled = ( /*#__PURE__*/createFluentFontIcon("DividerTallFilled", "", 2, undefined));
export const DividerTallRegular = ( /*#__PURE__*/createFluentFontIcon("DividerTallRegular", "", 2, undefined));
export const DividerTall16Regular = ( /*#__PURE__*/createFluentFontIcon("DividerTall16Regular", "", 1, 16));
export const DividerTall16Filled = ( /*#__PURE__*/createFluentFontIcon("DividerTall16Filled", "", 0, 16));
export const DividerTall20Regular = ( /*#__PURE__*/createFluentFontIcon("DividerTall20Regular", "", 1, 20));
export const DividerTall20Filled = ( /*#__PURE__*/createFluentFontIcon("DividerTall20Filled", "", 0, 20));
export const DividerTall24Regular = ( /*#__PURE__*/createFluentFontIcon("DividerTall24Regular", "", 1, 24));
export const DividerTall24Filled = ( /*#__PURE__*/createFluentFontIcon("DividerTall24Filled", "", 0, 24));
