"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DoctorFilled = ( /*#__PURE__*/createFluentFontIcon("DoctorFilled", "", 2, undefined));
export const DoctorRegular = ( /*#__PURE__*/createFluentFontIcon("DoctorRegular", "", 2, undefined));
export const Doctor12Regular = ( /*#__PURE__*/createFluentFontIcon("Doctor12Regular", "", 1, 12));
export const Doctor12Filled = ( /*#__PURE__*/createFluentFontIcon("Doctor12Filled", "", 0, 12));
export const Doctor16Regular = ( /*#__PURE__*/createFluentFontIcon("Doctor16Regular", "", 1, 16));
export const Doctor16Filled = ( /*#__PURE__*/createFluentFontIcon("Doctor16Filled", "", 0, 16));
export const Doctor20Regular = ( /*#__PURE__*/createFluentFontIcon("Doctor20Regular", "", 1, 20));
export const Doctor20Filled = ( /*#__PURE__*/createFluentFontIcon("Doctor20Filled", "", 0, 20));
export const Doctor24Regular = ( /*#__PURE__*/createFluentFontIcon("Doctor24Regular", "", 1, 24));
export const Doctor24Filled = ( /*#__PURE__*/createFluentFontIcon("Doctor24Filled", "", 0, 24));
export const Doctor28Regular = ( /*#__PURE__*/createFluentFontIcon("Doctor28Regular", "", 1, 28));
export const Doctor28Filled = ( /*#__PURE__*/createFluentFontIcon("Doctor28Filled", "", 0, 28));
export const Doctor48Regular = ( /*#__PURE__*/createFluentFontIcon("Doctor48Regular", "", 1, 48));
export const Doctor48Filled = ( /*#__PURE__*/createFluentFontIcon("Doctor48Filled", "", 0, 48));
