"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentTableFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentTableFilled", "", 2, undefined));
export const DocumentTableRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentTableRegular", "", 2, undefined));
export const DocumentTable16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentTable16Regular", "", 1, 16));
export const DocumentTable16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentTable16Filled", "", 0, 16));
export const DocumentTable20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentTable20Regular", "", 1, 20));
export const DocumentTable20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentTable20Filled", "", 0, 20));
export const DocumentTable24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentTable24Regular", "", 1, 24));
export const DocumentTable24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentTable24Filled", "", 0, 24));
