"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentMentionFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentMentionFilled", "", 2, undefined));
export const DocumentMentionRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentMentionRegular", "", 2, undefined));
export const DocumentMention16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentMention16Regular", "", 1, 16));
export const DocumentMention16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentMention16Filled", "", 0, 16));
export const DocumentMention20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentMention20Regular", "", 1, 20));
export const DocumentMention20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentMention20Filled", "", 0, 20));
export const DocumentMention24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentMention24Regular", "", 1, 24));
export const DocumentMention24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentMention24Filled", "", 0, 24));
export const DocumentMention28Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentMention28Regular", "", 1, 28));
export const DocumentMention28Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentMention28Filled", "", 0, 28));
export const DocumentMention48Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentMention48Regular", "", 1, 48));
export const DocumentMention48Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentMention48Filled", "", 0, 48));
