"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentFooterFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentFooterFilled", "", 2, undefined));
export const DocumentFooterRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentFooterRegular", "", 2, undefined));
export const DocumentFooter16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentFooter16Regular", "", 1, 16));
export const DocumentFooter16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentFooter16Filled", "", 0, 16));
export const DocumentFooter20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentFooter20Regular", "", 1, 20));
export const DocumentFooter20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentFooter20Filled", "", 0, 20));
export const DocumentFooter24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentFooter24Regular", "", 1, 24));
export const DocumentFooter24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentFooter24Filled", "", 0, 24));
