"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentSquareFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquareFilled", "", 2, undefined));
export const DocumentSquareRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquareRegular", "", 2, undefined));
export const DocumentSquare16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare16Regular", "󰨁", 1, 16));
export const DocumentSquare16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare16Filled", "󰩾", 0, 16));
export const DocumentSquare20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare20Regular", "󰨂", 1, 20));
export const DocumentSquare20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare20Filled", "󰩿", 0, 20));
export const DocumentSquare24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare24Regular", "󰨃", 1, 24));
export const DocumentSquare24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare24Filled", "󰪀", 0, 24));
export const DocumentSquare28Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare28Regular", "󰨄", 1, 28));
export const DocumentSquare28Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare28Filled", "󰪁", 0, 28));
export const DocumentSquare32Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare32Regular", "󰨅", 1, 32));
export const DocumentSquare32Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare32Filled", "󰪂", 0, 32));
export const DocumentSquare48Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare48Regular", "󰨆", 1, 48));
export const DocumentSquare48Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentSquare48Filled", "󰪃", 0, 48));
