"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentAddFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentAddFilled", "", 2, undefined));
export const DocumentAddRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentAddRegular", "", 2, undefined));
export const DocumentAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd16Regular", "", 1, 16));
export const DocumentAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd16Filled", "", 0, 16));
export const DocumentAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd20Regular", "", 1, 20));
export const DocumentAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd20Filled", "", 0, 20));
export const DocumentAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd24Regular", "", 1, 24));
export const DocumentAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd24Filled", "", 0, 24));
export const DocumentAdd28Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd28Regular", "", 1, 28));
export const DocumentAdd28Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd28Filled", "", 0, 28));
export const DocumentAdd48Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd48Regular", "", 1, 48));
export const DocumentAdd48Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentAdd48Filled", "", 0, 48));
