"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentCopyFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentCopyFilled", "", 2, undefined));
export const DocumentCopyRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentCopyRegular", "", 2, undefined));
export const DocumentCopy16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy16Regular", "", 1, 16));
export const DocumentCopy16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy16Filled", "", 0, 16));
export const DocumentCopy20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy20Regular", "", 1, 20));
export const DocumentCopy20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy20Filled", "", 0, 20));
export const DocumentCopy24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy24Regular", "", 1, 24));
export const DocumentCopy24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy24Filled", "", 0, 24));
export const DocumentCopy48Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy48Regular", "", 1, 48));
export const DocumentCopy48Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCopy48Filled", "", 0, 48));
