"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentCssFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentCssFilled", "", 2, undefined));
export const DocumentCssRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentCssRegular", "", 2, undefined));
export const DocumentCss16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCss16Regular", "", 1, 16));
export const DocumentCss16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCss16Filled", "", 0, 16));
export const DocumentCss20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCss20Regular", "", 1, 20));
export const DocumentCss20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCss20Filled", "", 0, 20));
export const DocumentCss24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentCss24Regular", "", 1, 24));
export const DocumentCss24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentCss24Filled", "", 0, 24));
