"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentTextFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentTextFilled", "", 2, undefined));
export const DocumentTextRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentTextRegular", "", 2, undefined));
export const DocumentText16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentText16Regular", "", 1, 16));
export const DocumentText16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentText16Filled", "", 0, 16));
export const DocumentText20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentText20Regular", "", 1, 20));
export const DocumentText20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentText20Filled", "", 0, 20));
export const DocumentText24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentText24Regular", "", 1, 24));
export const DocumentText24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentText24Filled", "", 0, 24));
export const DocumentText28Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentText28Regular", "󰜱", 1, 28));
export const DocumentText28Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentText28Filled", "󰞮", 0, 28));
export const DocumentText32Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentText32Regular", "󰜲", 1, 32));
export const DocumentText32Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentText32Filled", "󰞯", 0, 32));
export const DocumentText48Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentText48Regular", "󰜳", 1, 48));
export const DocumentText48Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentText48Filled", "󰞰", 0, 48));
