"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentDataFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentDataFilled", "", 2, undefined));
export const DocumentDataRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentDataRegular", "", 2, undefined));
export const DocumentData16Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentData16Regular", "", 1, 16));
export const DocumentData16Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentData16Filled", "", 0, 16));
export const DocumentData20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentData20Regular", "", 1, 20));
export const DocumentData20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentData20Filled", "", 0, 20));
export const DocumentData24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentData24Regular", "", 1, 24));
export const DocumentData24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentData24Filled", "", 0, 24));
export const DocumentData32Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentData32Regular", "", 1, 32));
export const DocumentData32Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentData32Filled", "", 0, 32));
