"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DocumentBorderFilled = ( /*#__PURE__*/createFluentFontIcon("DocumentBorderFilled", "", 2, undefined));
export const DocumentBorderRegular = ( /*#__PURE__*/createFluentFontIcon("DocumentBorderRegular", "", 2, undefined));
export const DocumentBorder20Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentBorder20Regular", "󰀎", 1, 20));
export const DocumentBorder20Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentBorder20Filled", "󰀒", 0, 20));
export const DocumentBorder24Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentBorder24Regular", "󰀏", 1, 24));
export const DocumentBorder24Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentBorder24Filled", "󰀓", 0, 24));
export const DocumentBorder32Regular = ( /*#__PURE__*/createFluentFontIcon("DocumentBorder32Regular", "󰀐", 1, 32));
export const DocumentBorder32Filled = ( /*#__PURE__*/createFluentFontIcon("DocumentBorder32Filled", "󰀔", 0, 32));
