"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DoorFilled = ( /*#__PURE__*/createFluentFontIcon("DoorFilled", "", 2, undefined));
export const DoorRegular = ( /*#__PURE__*/createFluentFontIcon("DoorRegular", "", 2, undefined));
export const Door16Regular = ( /*#__PURE__*/createFluentFontIcon("Door16Regular", "", 1, 16));
export const Door16Filled = ( /*#__PURE__*/createFluentFontIcon("Door16Filled", "", 0, 16));
export const Door20Regular = ( /*#__PURE__*/createFluentFontIcon("Door20Regular", "", 1, 20));
export const Door20Filled = ( /*#__PURE__*/createFluentFontIcon("Door20Filled", "", 0, 20));
export const Door24Regular = ( /*#__PURE__*/createFluentFontIcon("Door24Regular", "󰦺", 1, 24));
export const Door24Filled = ( /*#__PURE__*/createFluentFontIcon("Door24Filled", "󰨷", 0, 24));
export const Door28Regular = ( /*#__PURE__*/createFluentFontIcon("Door28Regular", "", 1, 28));
export const Door28Filled = ( /*#__PURE__*/createFluentFontIcon("Door28Filled", "", 0, 28));
export const Door32Regular = ( /*#__PURE__*/createFluentFontIcon("Door32Regular", "󰦻", 1, 32));
export const Door32Filled = ( /*#__PURE__*/createFluentFontIcon("Door32Filled", "󰨸", 0, 32));
