"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DraftsFilled = ( /*#__PURE__*/createFluentFontIcon("DraftsFilled", "", 2, undefined));
export const DraftsRegular = ( /*#__PURE__*/createFluentFontIcon("DraftsRegular", "", 2, undefined));
export const Drafts16Regular = ( /*#__PURE__*/createFluentFontIcon("Drafts16Regular", "", 1, 16));
export const Drafts16Filled = ( /*#__PURE__*/createFluentFontIcon("Drafts16Filled", "", 0, 16));
export const Drafts20Regular = ( /*#__PURE__*/createFluentFontIcon("Drafts20Regular", "", 1, 20));
export const Drafts20Filled = ( /*#__PURE__*/createFluentFontIcon("Drafts20Filled", "", 0, 20));
export const Drafts24Regular = ( /*#__PURE__*/createFluentFontIcon("Drafts24Regular", "", 1, 24));
export const Drafts24Filled = ( /*#__PURE__*/createFluentFontIcon("Drafts24Filled", "", 0, 24));
export const Drafts28Regular = ( /*#__PURE__*/createFluentFontIcon("Drafts28Regular", "󰨿", 1, 28));
export const Drafts28Filled = ( /*#__PURE__*/createFluentFontIcon("Drafts28Filled", "󰪻", 0, 28));
