"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DrinkBeerFilled = ( /*#__PURE__*/createFluentFontIcon("DrinkBeerFilled", "", 2, undefined));
export const DrinkBeerRegular = ( /*#__PURE__*/createFluentFontIcon("DrinkBeerRegular", "", 2, undefined));
export const DrinkBeer16Regular = ( /*#__PURE__*/createFluentFontIcon("DrinkBeer16Regular", "", 1, 16));
export const DrinkBeer16Filled = ( /*#__PURE__*/createFluentFontIcon("DrinkBeer16Filled", "", 0, 16));
export const DrinkBeer20Regular = ( /*#__PURE__*/createFluentFontIcon("DrinkBeer20Regular", "", 1, 20));
export const DrinkBeer20Filled = ( /*#__PURE__*/createFluentFontIcon("DrinkBeer20Filled", "", 0, 20));
export const DrinkBeer24Regular = ( /*#__PURE__*/createFluentFontIcon("DrinkBeer24Regular", "", 1, 24));
export const DrinkBeer24Filled = ( /*#__PURE__*/createFluentFontIcon("DrinkBeer24Filled", "", 0, 24));
