"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DrinkCoffeeFilled = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffeeFilled", "", 2, undefined));
export const DrinkCoffeeRegular = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffeeRegular", "", 2, undefined));
export const DrinkCoffee16Regular = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffee16Regular", "", 1, 16));
export const DrinkCoffee16Filled = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffee16Filled", "", 0, 16));
export const DrinkCoffee20Regular = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffee20Regular", "", 1, 20));
export const DrinkCoffee20Filled = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffee20Filled", "", 0, 20));
export const DrinkCoffee24Regular = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffee24Regular", "", 1, 24));
export const DrinkCoffee24Filled = ( /*#__PURE__*/createFluentFontIcon("DrinkCoffee24Filled", "", 0, 24));
