"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const DumbbellFilled = ( /*#__PURE__*/createFluentFontIcon("DumbbellFilled", "", 2, undefined));
export const DumbbellRegular = ( /*#__PURE__*/createFluentFontIcon("DumbbellRegular", "", 2, undefined));
export const Dumbbell16Regular = ( /*#__PURE__*/createFluentFontIcon("Dumbbell16Regular", "", 1, 16));
export const Dumbbell16Filled = ( /*#__PURE__*/createFluentFontIcon("Dumbbell16Filled", "", 0, 16));
export const Dumbbell20Regular = ( /*#__PURE__*/createFluentFontIcon("Dumbbell20Regular", "", 1, 20));
export const Dumbbell20Filled = ( /*#__PURE__*/createFluentFontIcon("Dumbbell20Filled", "", 0, 20));
export const Dumbbell24Regular = ( /*#__PURE__*/createFluentFontIcon("Dumbbell24Regular", "", 1, 24));
export const Dumbbell24Filled = ( /*#__PURE__*/createFluentFontIcon("Dumbbell24Filled", "", 0, 24));
export const Dumbbell28Regular = ( /*#__PURE__*/createFluentFontIcon("Dumbbell28Regular", "", 1, 28));
export const Dumbbell28Filled = ( /*#__PURE__*/createFluentFontIcon("Dumbbell28Filled", "", 0, 28));
