"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EarthFilled = ( /*#__PURE__*/createFluentFontIcon("EarthFilled", "", 2, undefined));
export const EarthRegular = ( /*#__PURE__*/createFluentFontIcon("EarthRegular", "", 2, undefined));
export const Earth16Regular = ( /*#__PURE__*/createFluentFontIcon("Earth16Regular", "", 1, 16));
export const Earth16Filled = ( /*#__PURE__*/createFluentFontIcon("Earth16Filled", "", 0, 16));
export const Earth20Regular = ( /*#__PURE__*/createFluentFontIcon("Earth20Regular", "", 1, 20));
export const Earth20Filled = ( /*#__PURE__*/createFluentFontIcon("Earth20Filled", "", 0, 20));
export const Earth24Regular = ( /*#__PURE__*/createFluentFontIcon("Earth24Regular", "", 1, 24));
export const Earth24Filled = ( /*#__PURE__*/createFluentFontIcon("Earth24Filled", "", 0, 24));
export const Earth32Regular = ( /*#__PURE__*/createFluentFontIcon("Earth32Regular", "", 1, 32));
export const Earth32Filled = ( /*#__PURE__*/createFluentFontIcon("Earth32Filled", "", 0, 32));
export const Earth48Regular = ( /*#__PURE__*/createFluentFontIcon("Earth48Regular", "", 1, 48));
export const Earth48Filled = ( /*#__PURE__*/createFluentFontIcon("Earth48Filled", "", 0, 48));
