"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EarthLeafFilled = ( /*#__PURE__*/createFluentFontIcon("EarthLeafFilled", "", 2, undefined));
export const EarthLeafRegular = ( /*#__PURE__*/createFluentFontIcon("EarthLeafRegular", "", 2, undefined));
export const EarthLeaf16Regular = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf16Regular", "", 1, 16));
export const EarthLeaf16Filled = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf16Filled", "", 0, 16));
export const EarthLeaf20Regular = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf20Regular", "", 1, 20));
export const EarthLeaf20Filled = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf20Filled", "", 0, 20));
export const EarthLeaf24Regular = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf24Regular", "", 1, 24));
export const EarthLeaf24Filled = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf24Filled", "", 0, 24));
export const EarthLeaf32Regular = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf32Regular", "", 1, 32));
export const EarthLeaf32Filled = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf32Filled", "", 0, 32));
export const EarthLeaf48Regular = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf48Regular", "", 1, 48));
export const EarthLeaf48Filled = ( /*#__PURE__*/createFluentFontIcon("EarthLeaf48Filled", "", 0, 48));
