"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EditLockFilled = ( /*#__PURE__*/createFluentFontIcon("EditLockFilled", "", 2, undefined));
export const EditLockRegular = ( /*#__PURE__*/createFluentFontIcon("EditLockRegular", "", 2, undefined));
export const EditLock16Regular = ( /*#__PURE__*/createFluentFontIcon("EditLock16Regular", "󰙴", 1, 16));
export const EditLock16Filled = ( /*#__PURE__*/createFluentFontIcon("EditLock16Filled", "󰛴", 0, 16));
export const EditLock20Regular = ( /*#__PURE__*/createFluentFontIcon("EditLock20Regular", "󰙵", 1, 20));
export const EditLock20Filled = ( /*#__PURE__*/createFluentFontIcon("EditLock20Filled", "󰛵", 0, 20));
export const EditLock24Regular = ( /*#__PURE__*/createFluentFontIcon("EditLock24Regular", "󰙶", 1, 24));
export const EditLock24Filled = ( /*#__PURE__*/createFluentFontIcon("EditLock24Filled", "󰛶", 0, 24));
