import type { FluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export declare const EditOffFilled: FluentFontIcon;
export declare const EditOffRegular: FluentFontIcon;
export declare const EditOff16Regular: FluentFontIcon;
export declare const EditOff16Filled: FluentFontIcon;
export declare const EditOff20Regular: FluentFontIcon;
export declare const EditOff20Filled: FluentFontIcon;
export declare const EditOff24Regular: FluentFontIcon;
export declare const EditOff24Filled: FluentFontIcon;
export declare const EditOff28Regular: FluentFontIcon;
export declare const EditOff28Filled: FluentFontIcon;
export declare const EditOff32Regular: FluentFontIcon;
export declare const EditOff32Filled: FluentFontIcon;
export declare const EditOff48Regular: FluentFontIcon;
export declare const EditOff48Filled: FluentFontIcon;
