"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EditFilled = ( /*#__PURE__*/createFluentFontIcon("EditFilled", "", 2, undefined));
export const EditRegular = ( /*#__PURE__*/createFluentFontIcon("EditRegular", "", 2, undefined));
export const Edit12Regular = ( /*#__PURE__*/createFluentFontIcon("Edit12Regular", "󰌪", 1, 12));
export const Edit12Filled = ( /*#__PURE__*/createFluentFontIcon("Edit12Filled", "󰌽", 0, 12));
export const Edit16Regular = ( /*#__PURE__*/createFluentFontIcon("Edit16Regular", "", 1, 16));
export const Edit16Filled = ( /*#__PURE__*/createFluentFontIcon("Edit16Filled", "", 0, 16));
export const Edit20Regular = ( /*#__PURE__*/createFluentFontIcon("Edit20Regular", "", 1, 20));
export const Edit20Filled = ( /*#__PURE__*/createFluentFontIcon("Edit20Filled", "", 0, 20));
export const Edit24Regular = ( /*#__PURE__*/createFluentFontIcon("Edit24Regular", "", 1, 24));
export const Edit24Filled = ( /*#__PURE__*/createFluentFontIcon("Edit24Filled", "", 0, 24));
export const Edit28Regular = ( /*#__PURE__*/createFluentFontIcon("Edit28Regular", "", 1, 28));
export const Edit28Filled = ( /*#__PURE__*/createFluentFontIcon("Edit28Filled", "", 0, 28));
export const Edit32Regular = ( /*#__PURE__*/createFluentFontIcon("Edit32Regular", "", 1, 32));
export const Edit32Filled = ( /*#__PURE__*/createFluentFontIcon("Edit32Filled", "", 0, 32));
export const Edit32Light = ( /*#__PURE__*/createFluentFontIcon("Edit32Light", "", 3, 32));
export const Edit48Regular = ( /*#__PURE__*/createFluentFontIcon("Edit48Regular", "", 1, 48));
export const Edit48Filled = ( /*#__PURE__*/createFluentFontIcon("Edit48Filled", "", 0, 48));
