"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EditOffFilled = ( /*#__PURE__*/createFluentFontIcon("EditOffFilled", "", 2, undefined));
export const EditOffRegular = ( /*#__PURE__*/createFluentFontIcon("EditOffRegular", "", 2, undefined));
export const EditOff16Regular = ( /*#__PURE__*/createFluentFontIcon("EditOff16Regular", "", 1, 16));
export const EditOff16Filled = ( /*#__PURE__*/createFluentFontIcon("EditOff16Filled", "", 0, 16));
export const EditOff20Regular = ( /*#__PURE__*/createFluentFontIcon("EditOff20Regular", "", 1, 20));
export const EditOff20Filled = ( /*#__PURE__*/createFluentFontIcon("EditOff20Filled", "", 0, 20));
export const EditOff24Regular = ( /*#__PURE__*/createFluentFontIcon("EditOff24Regular", "", 1, 24));
export const EditOff24Filled = ( /*#__PURE__*/createFluentFontIcon("EditOff24Filled", "", 0, 24));
export const EditOff28Regular = ( /*#__PURE__*/createFluentFontIcon("EditOff28Regular", "", 1, 28));
export const EditOff28Filled = ( /*#__PURE__*/createFluentFontIcon("EditOff28Filled", "", 0, 28));
export const EditOff32Regular = ( /*#__PURE__*/createFluentFontIcon("EditOff32Regular", "", 1, 32));
export const EditOff32Filled = ( /*#__PURE__*/createFluentFontIcon("EditOff32Filled", "", 0, 32));
export const EditOff48Regular = ( /*#__PURE__*/createFluentFontIcon("EditOff48Regular", "", 1, 48));
export const EditOff48Filled = ( /*#__PURE__*/createFluentFontIcon("EditOff48Filled", "", 0, 48));
