"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EmojiSadFilled = ( /*#__PURE__*/createFluentFontIcon("EmojiSadFilled", "", 2, undefined));
export const EmojiSadRegular = ( /*#__PURE__*/createFluentFontIcon("EmojiSadRegular", "", 2, undefined));
export const EmojiSad16Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiSad16Regular", "", 1, 16));
export const EmojiSad16Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiSad16Filled", "", 0, 16));
export const EmojiSad20Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiSad20Regular", "", 1, 20));
export const EmojiSad20Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiSad20Filled", "", 0, 20));
export const EmojiSad24Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiSad24Regular", "", 1, 24));
export const EmojiSad24Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiSad24Filled", "", 0, 24));
