"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EmojiEditFilled = ( /*#__PURE__*/createFluentFontIcon("EmojiEditFilled", "", 2, undefined));
export const EmojiEditRegular = ( /*#__PURE__*/createFluentFontIcon("EmojiEditRegular", "", 2, undefined));
export const EmojiEdit16Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit16Regular", "", 1, 16));
export const EmojiEdit16Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit16Filled", "", 0, 16));
export const EmojiEdit20Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit20Regular", "", 1, 20));
export const EmojiEdit20Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit20Filled", "", 0, 20));
export const EmojiEdit24Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit24Regular", "", 1, 24));
export const EmojiEdit24Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit24Filled", "", 0, 24));
export const EmojiEdit28Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit28Regular", "", 1, 28));
export const EmojiEdit28Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit28Filled", "", 0, 28));
export const EmojiEdit48Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit48Regular", "", 1, 48));
export const EmojiEdit48Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiEdit48Filled", "", 0, 48));
