"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EmojiLaughFilled = ( /*#__PURE__*/createFluentFontIcon("EmojiLaughFilled", "", 2, undefined));
export const EmojiLaughRegular = ( /*#__PURE__*/createFluentFontIcon("EmojiLaughRegular", "", 2, undefined));
export const EmojiLaugh16Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiLaugh16Regular", "", 1, 16));
export const EmojiLaugh16Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiLaugh16Filled", "", 0, 16));
export const EmojiLaugh20Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiLaugh20Regular", "", 1, 20));
export const EmojiLaugh20Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiLaugh20Filled", "", 0, 20));
export const EmojiLaugh24Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiLaugh24Regular", "", 1, 24));
export const EmojiLaugh24Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiLaugh24Filled", "", 0, 24));
