"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EmojiHandFilled = ( /*#__PURE__*/createFluentFontIcon("EmojiHandFilled", "", 2, undefined));
export const EmojiHandRegular = ( /*#__PURE__*/createFluentFontIcon("EmojiHandRegular", "", 2, undefined));
export const EmojiHand16Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHand16Regular", "󰀴", 1, 16));
export const EmojiHand16Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHand16Filled", "󰀸", 0, 16));
export const EmojiHand20Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHand20Regular", "", 1, 20));
export const EmojiHand20Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHand20Filled", "", 0, 20));
export const EmojiHand24Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHand24Regular", "", 1, 24));
export const EmojiHand24Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHand24Filled", "", 0, 24));
export const EmojiHand28Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHand28Regular", "", 1, 28));
export const EmojiHand28Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHand28Filled", "", 0, 28));
export const EmojiHand32Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHand32Regular", "󰃚", 1, 32));
export const EmojiHand32Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHand32Filled", "󰃙", 0, 32));
export const EmojiHand48Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHand48Regular", "󰃛", 1, 48));
export const EmojiHand48Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHand48Filled", "󰃚", 0, 48));
