"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EmojiHintFilled = ( /*#__PURE__*/createFluentFontIcon("EmojiHintFilled", "", 2, undefined));
export const EmojiHintRegular = ( /*#__PURE__*/createFluentFontIcon("EmojiHintRegular", "", 2, undefined));
export const EmojiHint16Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHint16Regular", "󰄢", 1, 16));
export const EmojiHint16Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHint16Filled", "󰄡", 0, 16));
export const EmojiHint20Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHint20Regular", "󰄣", 1, 20));
export const EmojiHint20Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHint20Filled", "󰄢", 0, 20));
export const EmojiHint24Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHint24Regular", "󰄤", 1, 24));
export const EmojiHint24Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHint24Filled", "󰄣", 0, 24));
export const EmojiHint28Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHint28Regular", "󰄥", 1, 28));
export const EmojiHint28Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHint28Filled", "󰄤", 0, 28));
export const EmojiHint32Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHint32Regular", "󰄦", 1, 32));
export const EmojiHint32Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHint32Filled", "󰄥", 0, 32));
export const EmojiHint48Regular = ( /*#__PURE__*/createFluentFontIcon("EmojiHint48Regular", "󰄧", 1, 48));
export const EmojiHint48Filled = ( /*#__PURE__*/createFluentFontIcon("EmojiHint48Filled", "󰄦", 0, 48));
