"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ErrorCircleFilled = ( /*#__PURE__*/createFluentFontIcon("ErrorCircleFilled", "", 2, undefined));
export const ErrorCircleRegular = ( /*#__PURE__*/createFluentFontIcon("ErrorCircleRegular", "", 2, undefined));
export const ErrorCircle12Regular = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle12Regular", "", 1, 12));
export const ErrorCircle12Filled = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle12Filled", "", 0, 12));
export const ErrorCircle16Regular = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle16Regular", "", 1, 16));
export const ErrorCircle16Filled = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle16Filled", "", 0, 16));
export const ErrorCircle20Regular = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle20Regular", "", 1, 20));
export const ErrorCircle20Filled = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle20Filled", "", 0, 20));
export const ErrorCircle24Regular = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle24Regular", "", 1, 24));
export const ErrorCircle24Filled = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle24Filled", "", 0, 24));
export const ErrorCircle48Regular = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle48Regular", "󰎵", 1, 48));
export const ErrorCircle48Filled = ( /*#__PURE__*/createFluentFontIcon("ErrorCircle48Filled", "󰏈", 0, 48));
