"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ExpandUpLeftFilled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeftFilled", "", 2, undefined));
export const ExpandUpLeftRegular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeftRegular", "", 2, undefined));
export const ExpandUpLeft16Regular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft16Regular", "", 1, 16));
export const ExpandUpLeft16Filled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft16Filled", "", 0, 16));
export const ExpandUpLeft20Regular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft20Regular", "", 1, 20));
export const ExpandUpLeft20Filled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft20Filled", "", 0, 20));
export const ExpandUpLeft24Regular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft24Regular", "", 1, 24));
export const ExpandUpLeft24Filled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft24Filled", "", 0, 24));
export const ExpandUpLeft28Regular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft28Regular", "", 1, 28));
export const ExpandUpLeft28Filled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft28Filled", "", 0, 28));
export const ExpandUpLeft32Regular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft32Regular", "", 1, 32));
export const ExpandUpLeft32Filled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft32Filled", "", 0, 32));
export const ExpandUpLeft48Regular = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft48Regular", "", 1, 48));
export const ExpandUpLeft48Filled = ( /*#__PURE__*/createFluentFontIcon("ExpandUpLeft48Filled", "", 0, 48));
