"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EyeLinesFilled = ( /*#__PURE__*/createFluentFontIcon("EyeLinesFilled", "", 2, undefined));
export const EyeLinesRegular = ( /*#__PURE__*/createFluentFontIcon("EyeLinesRegular", "", 2, undefined));
export const EyeLines20Regular = ( /*#__PURE__*/createFluentFontIcon("EyeLines20Regular", "", 1, 20));
export const EyeLines20Filled = ( /*#__PURE__*/createFluentFontIcon("EyeLines20Filled", "", 0, 20));
export const EyeLines24Regular = ( /*#__PURE__*/createFluentFontIcon("EyeLines24Regular", "", 1, 24));
export const EyeLines24Filled = ( /*#__PURE__*/createFluentFontIcon("EyeLines24Filled", "", 0, 24));
export const EyeLines28Regular = ( /*#__PURE__*/createFluentFontIcon("EyeLines28Regular", "", 1, 28));
export const EyeLines28Filled = ( /*#__PURE__*/createFluentFontIcon("EyeLines28Filled", "", 0, 28));
export const EyeLines32Regular = ( /*#__PURE__*/createFluentFontIcon("EyeLines32Regular", "", 1, 32));
export const EyeLines32Filled = ( /*#__PURE__*/createFluentFontIcon("EyeLines32Filled", "", 0, 32));
export const EyeLines48Regular = ( /*#__PURE__*/createFluentFontIcon("EyeLines48Regular", "", 1, 48));
export const EyeLines48Filled = ( /*#__PURE__*/createFluentFontIcon("EyeLines48Filled", "", 0, 48));
