"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EyeOffFilled = ( /*#__PURE__*/createFluentFontIcon("EyeOffFilled", "", 2, undefined));
export const EyeOffRegular = ( /*#__PURE__*/createFluentFontIcon("EyeOffRegular", "", 2, undefined));
export const EyeOff16Regular = ( /*#__PURE__*/createFluentFontIcon("EyeOff16Regular", "", 1, 16));
export const EyeOff16Filled = ( /*#__PURE__*/createFluentFontIcon("EyeOff16Filled", "", 0, 16));
export const EyeOff20Regular = ( /*#__PURE__*/createFluentFontIcon("EyeOff20Regular", "", 1, 20));
export const EyeOff20Filled = ( /*#__PURE__*/createFluentFontIcon("EyeOff20Filled", "", 0, 20));
export const EyeOff24Regular = ( /*#__PURE__*/createFluentFontIcon("EyeOff24Regular", "", 1, 24));
export const EyeOff24Filled = ( /*#__PURE__*/createFluentFontIcon("EyeOff24Filled", "", 0, 24));
export const EyeOff32Regular = ( /*#__PURE__*/createFluentFontIcon("EyeOff32Regular", "󰛓", 1, 32));
export const EyeOff32Filled = ( /*#__PURE__*/createFluentFontIcon("EyeOff32Filled", "󰝐", 0, 32));
export const EyeOff32Light = ( /*#__PURE__*/createFluentFontIcon("EyeOff32Light", "", 3, 32));
