"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const EyedropperFilled = ( /*#__PURE__*/createFluentFontIcon("EyedropperFilled", "", 2, undefined));
export const EyedropperRegular = ( /*#__PURE__*/createFluentFontIcon("EyedropperRegular", "", 2, undefined));
export const Eyedropper16Regular = ( /*#__PURE__*/createFluentFontIcon("Eyedropper16Regular", "", 1, 16));
export const Eyedropper16Filled = ( /*#__PURE__*/createFluentFontIcon("Eyedropper16Filled", "", 0, 16));
export const Eyedropper20Regular = ( /*#__PURE__*/createFluentFontIcon("Eyedropper20Regular", "", 1, 20));
export const Eyedropper20Filled = ( /*#__PURE__*/createFluentFontIcon("Eyedropper20Filled", "", 0, 20));
export const Eyedropper24Regular = ( /*#__PURE__*/createFluentFontIcon("Eyedropper24Regular", "", 1, 24));
export const Eyedropper24Filled = ( /*#__PURE__*/createFluentFontIcon("Eyedropper24Filled", "", 0, 24));
