"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FastForwardFilled = ( /*#__PURE__*/createFluentFontIcon("FastForwardFilled", "", 2, undefined));
export const FastForwardRegular = ( /*#__PURE__*/createFluentFontIcon("FastForwardRegular", "", 2, undefined));
export const FastForward16Regular = ( /*#__PURE__*/createFluentFontIcon("FastForward16Regular", "", 1, 16));
export const FastForward16Filled = ( /*#__PURE__*/createFluentFontIcon("FastForward16Filled", "", 0, 16));
export const FastForward20Regular = ( /*#__PURE__*/createFluentFontIcon("FastForward20Regular", "", 1, 20));
export const FastForward20Filled = ( /*#__PURE__*/createFluentFontIcon("FastForward20Filled", "", 0, 20));
export const FastForward24Regular = ( /*#__PURE__*/createFluentFontIcon("FastForward24Regular", "", 1, 24));
export const FastForward24Filled = ( /*#__PURE__*/createFluentFontIcon("FastForward24Filled", "", 0, 24));
export const FastForward28Regular = ( /*#__PURE__*/createFluentFontIcon("FastForward28Regular", "", 1, 28));
export const FastForward28Filled = ( /*#__PURE__*/createFluentFontIcon("FastForward28Filled", "", 0, 28));
