"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FilmstripFilled = ( /*#__PURE__*/createFluentFontIcon("FilmstripFilled", "", 2, undefined));
export const FilmstripRegular = ( /*#__PURE__*/createFluentFontIcon("FilmstripRegular", "", 2, undefined));
export const Filmstrip16Regular = ( /*#__PURE__*/createFluentFontIcon("Filmstrip16Regular", "󰀶", 1, 16));
export const Filmstrip16Filled = ( /*#__PURE__*/createFluentFontIcon("Filmstrip16Filled", "󰀺", 0, 16));
export const Filmstrip20Regular = ( /*#__PURE__*/createFluentFontIcon("Filmstrip20Regular", "", 1, 20));
export const Filmstrip20Filled = ( /*#__PURE__*/createFluentFontIcon("Filmstrip20Filled", "", 0, 20));
export const Filmstrip24Regular = ( /*#__PURE__*/createFluentFontIcon("Filmstrip24Regular", "", 1, 24));
export const Filmstrip24Filled = ( /*#__PURE__*/createFluentFontIcon("Filmstrip24Filled", "", 0, 24));
export const Filmstrip32Regular = ( /*#__PURE__*/createFluentFontIcon("Filmstrip32Regular", "󰀷", 1, 32));
export const Filmstrip32Filled = ( /*#__PURE__*/createFluentFontIcon("Filmstrip32Filled", "󰀻", 0, 32));
export const Filmstrip48Regular = ( /*#__PURE__*/createFluentFontIcon("Filmstrip48Regular", "󰇍", 1, 48));
export const Filmstrip48Filled = ( /*#__PURE__*/createFluentFontIcon("Filmstrip48Filled", "󰇍", 0, 48));
