"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FingerprintFilled = ( /*#__PURE__*/createFluentFontIcon("FingerprintFilled", "", 2, undefined));
export const FingerprintRegular = ( /*#__PURE__*/createFluentFontIcon("FingerprintRegular", "", 2, undefined));
export const Fingerprint16Regular = ( /*#__PURE__*/createFluentFontIcon("Fingerprint16Regular", "󰏹", 1, 16));
export const Fingerprint16Filled = ( /*#__PURE__*/createFluentFontIcon("Fingerprint16Filled", "󰐌", 0, 16));
export const Fingerprint20Regular = ( /*#__PURE__*/createFluentFontIcon("Fingerprint20Regular", "", 1, 20));
export const Fingerprint20Filled = ( /*#__PURE__*/createFluentFontIcon("Fingerprint20Filled", "", 0, 20));
export const Fingerprint24Regular = ( /*#__PURE__*/createFluentFontIcon("Fingerprint24Regular", "", 1, 24));
export const Fingerprint24Filled = ( /*#__PURE__*/createFluentFontIcon("Fingerprint24Filled", "", 0, 24));
export const Fingerprint32Regular = ( /*#__PURE__*/createFluentFontIcon("Fingerprint32Regular", "󰏺", 1, 32));
export const Fingerprint32Filled = ( /*#__PURE__*/createFluentFontIcon("Fingerprint32Filled", "󰐍", 0, 32));
export const Fingerprint48Regular = ( /*#__PURE__*/createFluentFontIcon("Fingerprint48Regular", "", 1, 48));
export const Fingerprint48Filled = ( /*#__PURE__*/createFluentFontIcon("Fingerprint48Filled", "", 0, 48));
