"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FireplaceFilled = ( /*#__PURE__*/createFluentFontIcon("FireplaceFilled", "", 2, undefined));
export const FireplaceRegular = ( /*#__PURE__*/createFluentFontIcon("FireplaceRegular", "", 2, undefined));
export const Fireplace20Regular = ( /*#__PURE__*/createFluentFontIcon("Fireplace20Regular", "", 1, 20));
export const Fireplace20Filled = ( /*#__PURE__*/createFluentFontIcon("Fireplace20Filled", "", 0, 20));
export const Fireplace24Regular = ( /*#__PURE__*/createFluentFontIcon("Fireplace24Regular", "", 1, 24));
export const Fireplace24Filled = ( /*#__PURE__*/createFluentFontIcon("Fireplace24Filled", "", 0, 24));
export const Fireplace32Regular = ( /*#__PURE__*/createFluentFontIcon("Fireplace32Regular", "", 1, 32));
export const Fireplace32Filled = ( /*#__PURE__*/createFluentFontIcon("Fireplace32Filled", "", 0, 32));
export const Fireplace48Regular = ( /*#__PURE__*/createFluentFontIcon("Fireplace48Regular", "", 1, 48));
export const Fireplace48Filled = ( /*#__PURE__*/createFluentFontIcon("Fireplace48Filled", "", 0, 48));
