"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FlagClockFilled = ( /*#__PURE__*/createFluentFontIcon("FlagClockFilled", "", 2, undefined));
export const FlagClockRegular = ( /*#__PURE__*/createFluentFontIcon("FlagClockRegular", "", 2, undefined));
export const FlagClock16Regular = ( /*#__PURE__*/createFluentFontIcon("FlagClock16Regular", "󰀽", 1, 16));
export const FlagClock16Filled = ( /*#__PURE__*/createFluentFontIcon("FlagClock16Filled", "󰁁", 0, 16));
export const FlagClock20Regular = ( /*#__PURE__*/createFluentFontIcon("FlagClock20Regular", "󰀾", 1, 20));
export const FlagClock20Filled = ( /*#__PURE__*/createFluentFontIcon("FlagClock20Filled", "󰁂", 0, 20));
export const FlagClock24Regular = ( /*#__PURE__*/createFluentFontIcon("FlagClock24Regular", "󰀿", 1, 24));
export const FlagClock24Filled = ( /*#__PURE__*/createFluentFontIcon("FlagClock24Filled", "󰁃", 0, 24));
export const FlagClock28Regular = ( /*#__PURE__*/createFluentFontIcon("FlagClock28Regular", "󰁀", 1, 28));
export const FlagClock28Filled = ( /*#__PURE__*/createFluentFontIcon("FlagClock28Filled", "󰁄", 0, 28));
export const FlagClock32Regular = ( /*#__PURE__*/createFluentFontIcon("FlagClock32Regular", "󰁁", 1, 32));
export const FlagClock32Filled = ( /*#__PURE__*/createFluentFontIcon("FlagClock32Filled", "󰁅", 0, 32));
export const FlagClock48Regular = ( /*#__PURE__*/createFluentFontIcon("FlagClock48Regular", "󰁂", 1, 48));
export const FlagClock48Filled = ( /*#__PURE__*/createFluentFontIcon("FlagClock48Filled", "󰁆", 0, 48));
