"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FlagOffFilled = ( /*#__PURE__*/createFluentFontIcon("FlagOffFilled", "", 2, undefined));
export const FlagOffRegular = ( /*#__PURE__*/createFluentFontIcon("FlagOffRegular", "", 2, undefined));
export const FlagOff16Regular = ( /*#__PURE__*/createFluentFontIcon("FlagOff16Regular", "", 1, 16));
export const FlagOff16Filled = ( /*#__PURE__*/createFluentFontIcon("FlagOff16Filled", "", 0, 16));
export const FlagOff20Regular = ( /*#__PURE__*/createFluentFontIcon("FlagOff20Regular", "", 1, 20));
export const FlagOff20Filled = ( /*#__PURE__*/createFluentFontIcon("FlagOff20Filled", "", 0, 20));
export const FlagOff24Regular = ( /*#__PURE__*/createFluentFontIcon("FlagOff24Regular", "", 1, 24));
export const FlagOff24Filled = ( /*#__PURE__*/createFluentFontIcon("FlagOff24Filled", "", 0, 24));
export const FlagOff28Regular = ( /*#__PURE__*/createFluentFontIcon("FlagOff28Regular", "", 1, 28));
export const FlagOff28Filled = ( /*#__PURE__*/createFluentFontIcon("FlagOff28Filled", "", 0, 28));
export const FlagOff32Light = ( /*#__PURE__*/createFluentFontIcon("FlagOff32Light", "", 3, 32));
export const FlagOff48Regular = ( /*#__PURE__*/createFluentFontIcon("FlagOff48Regular", "", 1, 48));
export const FlagOff48Filled = ( /*#__PURE__*/createFluentFontIcon("FlagOff48Filled", "", 0, 48));
