"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FlashFlowFilled = ( /*#__PURE__*/createFluentFontIcon("FlashFlowFilled", "", 2, undefined));
export const FlashFlowRegular = ( /*#__PURE__*/createFluentFontIcon("FlashFlowRegular", "", 2, undefined));
export const FlashFlow16Regular = ( /*#__PURE__*/createFluentFontIcon("FlashFlow16Regular", "", 1, 16));
export const FlashFlow16Filled = ( /*#__PURE__*/createFluentFontIcon("FlashFlow16Filled", "", 0, 16));
export const FlashFlow20Regular = ( /*#__PURE__*/createFluentFontIcon("FlashFlow20Regular", "", 1, 20));
export const FlashFlow20Filled = ( /*#__PURE__*/createFluentFontIcon("FlashFlow20Filled", "", 0, 20));
export const FlashFlow24Regular = ( /*#__PURE__*/createFluentFontIcon("FlashFlow24Regular", "", 1, 24));
export const FlashFlow24Filled = ( /*#__PURE__*/createFluentFontIcon("FlashFlow24Filled", "", 0, 24));
