"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FolderSyncFilled = ( /*#__PURE__*/createFluentFontIcon("FolderSyncFilled", "", 2, undefined));
export const FolderSyncRegular = ( /*#__PURE__*/createFluentFontIcon("FolderSyncRegular", "", 2, undefined));
export const FolderSync16Regular = ( /*#__PURE__*/createFluentFontIcon("FolderSync16Regular", "", 1, 16));
export const FolderSync16Filled = ( /*#__PURE__*/createFluentFontIcon("FolderSync16Filled", "", 0, 16));
export const FolderSync20Regular = ( /*#__PURE__*/createFluentFontIcon("FolderSync20Regular", "", 1, 20));
export const FolderSync20Filled = ( /*#__PURE__*/createFluentFontIcon("FolderSync20Filled", "", 0, 20));
export const FolderSync24Regular = ( /*#__PURE__*/createFluentFontIcon("FolderSync24Regular", "", 1, 24));
export const FolderSync24Filled = ( /*#__PURE__*/createFluentFontIcon("FolderSync24Filled", "", 0, 24));
