"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FolderPersonFilled = ( /*#__PURE__*/createFluentFontIcon("FolderPersonFilled", "", 2, undefined));
export const FolderPersonRegular = ( /*#__PURE__*/createFluentFontIcon("FolderPersonRegular", "", 2, undefined));
export const FolderPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("FolderPerson16Regular", "", 1, 16));
export const FolderPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("FolderPerson16Filled", "", 0, 16));
export const FolderPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("FolderPerson20Regular", "", 1, 20));
export const FolderPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("FolderPerson20Filled", "", 0, 20));
export const FolderPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("FolderPerson24Regular", "󰏻", 1, 24));
export const FolderPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("FolderPerson24Filled", "󰐎", 0, 24));
export const FolderPerson28Regular = ( /*#__PURE__*/createFluentFontIcon("FolderPerson28Regular", "󰏼", 1, 28));
export const FolderPerson28Filled = ( /*#__PURE__*/createFluentFontIcon("FolderPerson28Filled", "󰐏", 0, 28));
export const FolderPerson32Regular = ( /*#__PURE__*/createFluentFontIcon("FolderPerson32Regular", "󰏽", 1, 32));
export const FolderPerson32Filled = ( /*#__PURE__*/createFluentFontIcon("FolderPerson32Filled", "󰐐", 0, 32));
export const FolderPerson48Regular = ( /*#__PURE__*/createFluentFontIcon("FolderPerson48Regular", "󰏾", 1, 48));
export const FolderPerson48Filled = ( /*#__PURE__*/createFluentFontIcon("FolderPerson48Filled", "󰐑", 0, 48));
