"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FolderMailFilled = ( /*#__PURE__*/createFluentFontIcon("FolderMailFilled", "", 2, undefined));
export const FolderMailRegular = ( /*#__PURE__*/createFluentFontIcon("FolderMailRegular", "", 2, undefined));
export const FolderMail16Regular = ( /*#__PURE__*/createFluentFontIcon("FolderMail16Regular", "", 1, 16));
export const FolderMail16Filled = ( /*#__PURE__*/createFluentFontIcon("FolderMail16Filled", "", 0, 16));
export const FolderMail20Regular = ( /*#__PURE__*/createFluentFontIcon("FolderMail20Regular", "", 1, 20));
export const FolderMail20Filled = ( /*#__PURE__*/createFluentFontIcon("FolderMail20Filled", "", 0, 20));
export const FolderMail24Regular = ( /*#__PURE__*/createFluentFontIcon("FolderMail24Regular", "", 1, 24));
export const FolderMail24Filled = ( /*#__PURE__*/createFluentFontIcon("FolderMail24Filled", "", 0, 24));
export const FolderMail28Regular = ( /*#__PURE__*/createFluentFontIcon("FolderMail28Regular", "", 1, 28));
export const FolderMail28Filled = ( /*#__PURE__*/createFluentFontIcon("FolderMail28Filled", "", 0, 28));
export const FolderMail32Regular = ( /*#__PURE__*/createFluentFontIcon("FolderMail32Regular", "󰐳", 1, 32));
export const FolderMail32Filled = ( /*#__PURE__*/createFluentFontIcon("FolderMail32Filled", "󰑆", 0, 32));
export const FolderMail32Light = ( /*#__PURE__*/createFluentFontIcon("FolderMail32Light", "", 3, 32));
