"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const FolderZipFilled = ( /*#__PURE__*/createFluentFontIcon("FolderZipFilled", "", 2, undefined));
export const FolderZipRegular = ( /*#__PURE__*/createFluentFontIcon("FolderZipRegular", "", 2, undefined));
export const FolderZip16Regular = ( /*#__PURE__*/createFluentFontIcon("FolderZip16Regular", "", 1, 16));
export const FolderZip16Filled = ( /*#__PURE__*/createFluentFontIcon("FolderZip16Filled", "", 0, 16));
export const FolderZip20Regular = ( /*#__PURE__*/createFluentFontIcon("FolderZip20Regular", "", 1, 20));
export const FolderZip20Filled = ( /*#__PURE__*/createFluentFontIcon("FolderZip20Filled", "", 0, 20));
export const FolderZip24Regular = ( /*#__PURE__*/createFluentFontIcon("FolderZip24Regular", "", 1, 24));
export const FolderZip24Filled = ( /*#__PURE__*/createFluentFontIcon("FolderZip24Filled", "", 0, 24));
