"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GamesFilled = ( /*#__PURE__*/createFluentFontIcon("GamesFilled", "", 2, undefined));
export const GamesRegular = ( /*#__PURE__*/createFluentFontIcon("GamesRegular", "", 2, undefined));
export const Games16Regular = ( /*#__PURE__*/createFluentFontIcon("Games16Regular", "", 1, 16));
export const Games16Filled = ( /*#__PURE__*/createFluentFontIcon("Games16Filled", "", 0, 16));
export const Games20Regular = ( /*#__PURE__*/createFluentFontIcon("Games20Regular", "", 1, 20));
export const Games20Filled = ( /*#__PURE__*/createFluentFontIcon("Games20Filled", "", 0, 20));
export const Games24Regular = ( /*#__PURE__*/createFluentFontIcon("Games24Regular", "", 1, 24));
export const Games24Filled = ( /*#__PURE__*/createFluentFontIcon("Games24Filled", "", 0, 24));
export const Games28Regular = ( /*#__PURE__*/createFluentFontIcon("Games28Regular", "", 1, 28));
export const Games28Filled = ( /*#__PURE__*/createFluentFontIcon("Games28Filled", "", 0, 28));
export const Games32Regular = ( /*#__PURE__*/createFluentFontIcon("Games32Regular", "", 1, 32));
export const Games32Filled = ( /*#__PURE__*/createFluentFontIcon("Games32Filled", "", 0, 32));
export const Games48Regular = ( /*#__PURE__*/createFluentFontIcon("Games48Regular", "", 1, 48));
export const Games48Filled = ( /*#__PURE__*/createFluentFontIcon("Games48Filled", "", 0, 48));
