"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GanttChartFilled = ( /*#__PURE__*/createFluentFontIcon("GanttChartFilled", "", 2, undefined));
export const GanttChartRegular = ( /*#__PURE__*/createFluentFontIcon("GanttChartRegular", "", 2, undefined));
export const GanttChart16Regular = ( /*#__PURE__*/createFluentFontIcon("GanttChart16Regular", "", 1, 16));
export const GanttChart16Filled = ( /*#__PURE__*/createFluentFontIcon("GanttChart16Filled", "", 0, 16));
export const GanttChart20Regular = ( /*#__PURE__*/createFluentFontIcon("GanttChart20Regular", "", 1, 20));
export const GanttChart20Filled = ( /*#__PURE__*/createFluentFontIcon("GanttChart20Filled", "", 0, 20));
export const GanttChart24Regular = ( /*#__PURE__*/createFluentFontIcon("GanttChart24Regular", "", 1, 24));
export const GanttChart24Filled = ( /*#__PURE__*/createFluentFontIcon("GanttChart24Filled", "", 0, 24));
