"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GavelFilled = ( /*#__PURE__*/createFluentFontIcon("GavelFilled", "", 2, undefined));
export const GavelRegular = ( /*#__PURE__*/createFluentFontIcon("GavelRegular", "", 2, undefined));
export const Gavel16Regular = ( /*#__PURE__*/createFluentFontIcon("Gavel16Regular", "󰆅", 1, 16));
export const Gavel16Filled = ( /*#__PURE__*/createFluentFontIcon("Gavel16Filled", "󰆅", 0, 16));
export const Gavel20Regular = ( /*#__PURE__*/createFluentFontIcon("Gavel20Regular", "", 1, 20));
export const Gavel20Filled = ( /*#__PURE__*/createFluentFontIcon("Gavel20Filled", "", 0, 20));
export const Gavel24Regular = ( /*#__PURE__*/createFluentFontIcon("Gavel24Regular", "", 1, 24));
export const Gavel24Filled = ( /*#__PURE__*/createFluentFontIcon("Gavel24Filled", "", 0, 24));
export const Gavel32Regular = ( /*#__PURE__*/createFluentFontIcon("Gavel32Regular", "", 1, 32));
export const Gavel32Filled = ( /*#__PURE__*/createFluentFontIcon("Gavel32Filled", "", 0, 32));
