"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GiftOpenFilled = ( /*#__PURE__*/createFluentFontIcon("GiftOpenFilled", "", 2, undefined));
export const GiftOpenRegular = ( /*#__PURE__*/createFluentFontIcon("GiftOpenRegular", "", 2, undefined));
export const GiftOpen16Regular = ( /*#__PURE__*/createFluentFontIcon("GiftOpen16Regular", "󰆈", 1, 16));
export const GiftOpen16Filled = ( /*#__PURE__*/createFluentFontIcon("GiftOpen16Filled", "󰆈", 0, 16));
export const GiftOpen20Regular = ( /*#__PURE__*/createFluentFontIcon("GiftOpen20Regular", "󰆉", 1, 20));
export const GiftOpen20Filled = ( /*#__PURE__*/createFluentFontIcon("GiftOpen20Filled", "󰆉", 0, 20));
export const GiftOpen24Regular = ( /*#__PURE__*/createFluentFontIcon("GiftOpen24Regular", "󰆊", 1, 24));
export const GiftOpen24Filled = ( /*#__PURE__*/createFluentFontIcon("GiftOpen24Filled", "󰆊", 0, 24));
export const GiftOpen32Regular = ( /*#__PURE__*/createFluentFontIcon("GiftOpen32Regular", "󰘮", 1, 32));
export const GiftOpen32Filled = ( /*#__PURE__*/createFluentFontIcon("GiftOpen32Filled", "󰚪", 0, 32));
