"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GiftCardFilled = ( /*#__PURE__*/createFluentFontIcon("GiftCardFilled", "", 2, undefined));
export const GiftCardRegular = ( /*#__PURE__*/createFluentFontIcon("GiftCardRegular", "", 2, undefined));
export const GiftCard16Regular = ( /*#__PURE__*/createFluentFontIcon("GiftCard16Regular", "", 1, 16));
export const GiftCard16Filled = ( /*#__PURE__*/createFluentFontIcon("GiftCard16Filled", "", 0, 16));
export const GiftCard20Regular = ( /*#__PURE__*/createFluentFontIcon("GiftCard20Regular", "", 1, 20));
export const GiftCard20Filled = ( /*#__PURE__*/createFluentFontIcon("GiftCard20Filled", "", 0, 20));
export const GiftCard24Regular = ( /*#__PURE__*/createFluentFontIcon("GiftCard24Regular", "", 1, 24));
export const GiftCard24Filled = ( /*#__PURE__*/createFluentFontIcon("GiftCard24Filled", "", 0, 24));
