"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GlanceFilled = ( /*#__PURE__*/createFluentFontIcon("GlanceFilled", "", 2, undefined));
export const GlanceRegular = ( /*#__PURE__*/createFluentFontIcon("GlanceRegular", "", 2, undefined));
export const Glance12Regular = ( /*#__PURE__*/createFluentFontIcon("Glance12Regular", "", 1, 12));
export const Glance12Filled = ( /*#__PURE__*/createFluentFontIcon("Glance12Filled", "", 0, 12));
export const Glance16Regular = ( /*#__PURE__*/createFluentFontIcon("Glance16Regular", "󰛵", 1, 16));
export const Glance16Filled = ( /*#__PURE__*/createFluentFontIcon("Glance16Filled", "󰝲", 0, 16));
export const Glance20Regular = ( /*#__PURE__*/createFluentFontIcon("Glance20Regular", "", 1, 20));
export const Glance20Filled = ( /*#__PURE__*/createFluentFontIcon("Glance20Filled", "", 0, 20));
export const Glance24Regular = ( /*#__PURE__*/createFluentFontIcon("Glance24Regular", "", 1, 24));
export const Glance24Filled = ( /*#__PURE__*/createFluentFontIcon("Glance24Filled", "", 0, 24));
export const Glance28Regular = ( /*#__PURE__*/createFluentFontIcon("Glance28Regular", "󰛶", 1, 28));
export const Glance28Filled = ( /*#__PURE__*/createFluentFontIcon("Glance28Filled", "󰝳", 0, 28));
export const Glance32Regular = ( /*#__PURE__*/createFluentFontIcon("Glance32Regular", "󰛷", 1, 32));
export const Glance32Filled = ( /*#__PURE__*/createFluentFontIcon("Glance32Filled", "󰝴", 0, 32));
export const Glance48Regular = ( /*#__PURE__*/createFluentFontIcon("Glance48Regular", "󰛸", 1, 48));
export const Glance48Filled = ( /*#__PURE__*/createFluentFontIcon("Glance48Filled", "󰝵", 0, 48));
