"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GlobeClockFilled = ( /*#__PURE__*/createFluentFontIcon("GlobeClockFilled", "", 2, undefined));
export const GlobeClockRegular = ( /*#__PURE__*/createFluentFontIcon("GlobeClockRegular", "", 2, undefined));
export const GlobeClock16Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeClock16Regular", "", 1, 16));
export const GlobeClock16Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeClock16Filled", "", 0, 16));
export const GlobeClock20Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeClock20Regular", "", 1, 20));
export const GlobeClock20Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeClock20Filled", "", 0, 20));
export const GlobeClock24Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeClock24Regular", "", 1, 24));
export const GlobeClock24Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeClock24Filled", "", 0, 24));
