"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GlobeWarningFilled = ( /*#__PURE__*/createFluentFontIcon("GlobeWarningFilled", "", 2, undefined));
export const GlobeWarningRegular = ( /*#__PURE__*/createFluentFontIcon("GlobeWarningRegular", "", 2, undefined));
export const GlobeWarning16Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeWarning16Regular", "󰑁", 1, 16));
export const GlobeWarning16Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeWarning16Filled", "󰑔", 0, 16));
export const GlobeWarning20Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeWarning20Regular", "󰑂", 1, 20));
export const GlobeWarning20Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeWarning20Filled", "󰑕", 0, 20));
export const GlobeWarning24Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeWarning24Regular", "󰑃", 1, 24));
export const GlobeWarning24Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeWarning24Filled", "󰑖", 0, 24));
