"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GlobeFilled = ( /*#__PURE__*/createFluentFontIcon("GlobeFilled", "", 2, undefined));
export const GlobeRegular = ( /*#__PURE__*/createFluentFontIcon("GlobeRegular", "", 2, undefined));
export const Globe12Regular = ( /*#__PURE__*/createFluentFontIcon("Globe12Regular", "󰆋", 1, 12));
export const Globe12Filled = ( /*#__PURE__*/createFluentFontIcon("Globe12Filled", "󰆋", 0, 12));
export const Globe16Regular = ( /*#__PURE__*/createFluentFontIcon("Globe16Regular", "", 1, 16));
export const Globe16Filled = ( /*#__PURE__*/createFluentFontIcon("Globe16Filled", "", 0, 16));
export const Globe20Regular = ( /*#__PURE__*/createFluentFontIcon("Globe20Regular", "", 1, 20));
export const Globe20Filled = ( /*#__PURE__*/createFluentFontIcon("Globe20Filled", "", 0, 20));
export const Globe24Regular = ( /*#__PURE__*/createFluentFontIcon("Globe24Regular", "", 1, 24));
export const Globe24Filled = ( /*#__PURE__*/createFluentFontIcon("Globe24Filled", "", 0, 24));
export const Globe28Regular = ( /*#__PURE__*/createFluentFontIcon("Globe28Regular", "󰔍", 1, 28));
export const Globe28Filled = ( /*#__PURE__*/createFluentFontIcon("Globe28Filled", "󰖆", 0, 28));
export const Globe32Regular = ( /*#__PURE__*/createFluentFontIcon("Globe32Regular", "", 1, 32));
export const Globe32Filled = ( /*#__PURE__*/createFluentFontIcon("Globe32Filled", "", 0, 32));
export const Globe32Light = ( /*#__PURE__*/createFluentFontIcon("Globe32Light", "", 3, 32));
export const Globe48Regular = ( /*#__PURE__*/createFluentFontIcon("Globe48Regular", "󰉮", 1, 48));
export const Globe48Filled = ( /*#__PURE__*/createFluentFontIcon("Globe48Filled", "󰊁", 0, 48));
