"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GlobeVideoFilled = ( /*#__PURE__*/createFluentFontIcon("GlobeVideoFilled", "", 2, undefined));
export const GlobeVideoRegular = ( /*#__PURE__*/createFluentFontIcon("GlobeVideoRegular", "", 2, undefined));
export const GlobeVideo20Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo20Regular", "", 1, 20));
export const GlobeVideo20Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo20Filled", "", 0, 20));
export const GlobeVideo24Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo24Regular", "", 1, 24));
export const GlobeVideo24Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo24Filled", "", 0, 24));
export const GlobeVideo28Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo28Regular", "", 1, 28));
export const GlobeVideo28Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo28Filled", "", 0, 28));
export const GlobeVideo32Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo32Regular", "", 1, 32));
export const GlobeVideo32Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo32Filled", "", 0, 32));
export const GlobeVideo48Regular = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo48Regular", "", 1, 48));
export const GlobeVideo48Filled = ( /*#__PURE__*/createFluentFontIcon("GlobeVideo48Filled", "", 0, 48));
