"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GridFilled = ( /*#__PURE__*/createFluentFontIcon("GridFilled", "", 2, undefined));
export const GridRegular = ( /*#__PURE__*/createFluentFontIcon("GridRegular", "", 2, undefined));
export const Grid16Regular = ( /*#__PURE__*/createFluentFontIcon("Grid16Regular", "", 1, 16));
export const Grid16Filled = ( /*#__PURE__*/createFluentFontIcon("Grid16Filled", "", 0, 16));
export const Grid20Regular = ( /*#__PURE__*/createFluentFontIcon("Grid20Regular", "", 1, 20));
export const Grid20Filled = ( /*#__PURE__*/createFluentFontIcon("Grid20Filled", "", 0, 20));
export const Grid24Regular = ( /*#__PURE__*/createFluentFontIcon("Grid24Regular", "", 1, 24));
export const Grid24Filled = ( /*#__PURE__*/createFluentFontIcon("Grid24Filled", "", 0, 24));
export const Grid28Regular = ( /*#__PURE__*/createFluentFontIcon("Grid28Regular", "", 1, 28));
export const Grid28Filled = ( /*#__PURE__*/createFluentFontIcon("Grid28Filled", "", 0, 28));
