"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const GuardianFilled = ( /*#__PURE__*/createFluentFontIcon("GuardianFilled", "", 2, undefined));
export const GuardianRegular = ( /*#__PURE__*/createFluentFontIcon("GuardianRegular", "", 2, undefined));
export const Guardian20Regular = ( /*#__PURE__*/createFluentFontIcon("Guardian20Regular", "", 1, 20));
export const Guardian20Filled = ( /*#__PURE__*/createFluentFontIcon("Guardian20Filled", "", 0, 20));
export const Guardian24Regular = ( /*#__PURE__*/createFluentFontIcon("Guardian24Regular", "", 1, 24));
export const Guardian24Filled = ( /*#__PURE__*/createFluentFontIcon("Guardian24Filled", "", 0, 24));
export const Guardian28Regular = ( /*#__PURE__*/createFluentFontIcon("Guardian28Regular", "", 1, 28));
export const Guardian28Filled = ( /*#__PURE__*/createFluentFontIcon("Guardian28Filled", "", 0, 28));
export const Guardian48Regular = ( /*#__PURE__*/createFluentFontIcon("Guardian48Regular", "", 1, 48));
export const Guardian48Filled = ( /*#__PURE__*/createFluentFontIcon("Guardian48Filled", "", 0, 48));
