"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HandRightFilled = ( /*#__PURE__*/createFluentFontIcon("HandRightFilled", "", 2, undefined));
export const HandRightRegular = ( /*#__PURE__*/createFluentFontIcon("HandRightRegular", "", 2, undefined));
export const HandRight16Regular = ( /*#__PURE__*/createFluentFontIcon("HandRight16Regular", "", 1, 16));
export const HandRight16Filled = ( /*#__PURE__*/createFluentFontIcon("HandRight16Filled", "", 0, 16));
export const HandRight20Regular = ( /*#__PURE__*/createFluentFontIcon("HandRight20Regular", "", 1, 20));
export const HandRight20Filled = ( /*#__PURE__*/createFluentFontIcon("HandRight20Filled", "", 0, 20));
export const HandRight24Regular = ( /*#__PURE__*/createFluentFontIcon("HandRight24Regular", "", 1, 24));
export const HandRight24Filled = ( /*#__PURE__*/createFluentFontIcon("HandRight24Filled", "", 0, 24));
export const HandRight28Regular = ( /*#__PURE__*/createFluentFontIcon("HandRight28Regular", "", 1, 28));
export const HandRight28Filled = ( /*#__PURE__*/createFluentFontIcon("HandRight28Filled", "", 0, 28));
