"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HandshakeFilled = ( /*#__PURE__*/createFluentFontIcon("HandshakeFilled", "", 2, undefined));
export const HandshakeRegular = ( /*#__PURE__*/createFluentFontIcon("HandshakeRegular", "", 2, undefined));
export const Handshake16Regular = ( /*#__PURE__*/createFluentFontIcon("Handshake16Regular", "", 1, 16));
export const Handshake16Filled = ( /*#__PURE__*/createFluentFontIcon("Handshake16Filled", "", 0, 16));
export const Handshake20Regular = ( /*#__PURE__*/createFluentFontIcon("Handshake20Regular", "", 1, 20));
export const Handshake20Filled = ( /*#__PURE__*/createFluentFontIcon("Handshake20Filled", "", 0, 20));
export const Handshake24Regular = ( /*#__PURE__*/createFluentFontIcon("Handshake24Regular", "", 1, 24));
export const Handshake24Filled = ( /*#__PURE__*/createFluentFontIcon("Handshake24Filled", "", 0, 24));
export const Handshake32Regular = ( /*#__PURE__*/createFluentFontIcon("Handshake32Regular", "", 1, 32));
export const Handshake32Filled = ( /*#__PURE__*/createFluentFontIcon("Handshake32Filled", "", 0, 32));
