"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HandDrawFilled = ( /*#__PURE__*/createFluentFontIcon("HandDrawFilled", "", 2, undefined));
export const HandDrawRegular = ( /*#__PURE__*/createFluentFontIcon("HandDrawRegular", "", 2, undefined));
export const HandDraw16Regular = ( /*#__PURE__*/createFluentFontIcon("HandDraw16Regular", "", 1, 16));
export const HandDraw16Filled = ( /*#__PURE__*/createFluentFontIcon("HandDraw16Filled", "", 0, 16));
export const HandDraw20Regular = ( /*#__PURE__*/createFluentFontIcon("HandDraw20Regular", "", 1, 20));
export const HandDraw20Filled = ( /*#__PURE__*/createFluentFontIcon("HandDraw20Filled", "", 0, 20));
export const HandDraw24Regular = ( /*#__PURE__*/createFluentFontIcon("HandDraw24Regular", "", 1, 24));
export const HandDraw24Filled = ( /*#__PURE__*/createFluentFontIcon("HandDraw24Filled", "", 0, 24));
export const HandDraw28Regular = ( /*#__PURE__*/createFluentFontIcon("HandDraw28Regular", "", 1, 28));
export const HandDraw28Filled = ( /*#__PURE__*/createFluentFontIcon("HandDraw28Filled", "", 0, 28));
export const HandDraw32Regular = ( /*#__PURE__*/createFluentFontIcon("HandDraw32Regular", "󰩸", 1, 32));
export const HandDraw32Filled = ( /*#__PURE__*/createFluentFontIcon("HandDraw32Filled", "󰫴", 0, 32));
export const HandDraw32Light = ( /*#__PURE__*/createFluentFontIcon("HandDraw32Light", "", 3, 32));
