"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HandPointFilled = ( /*#__PURE__*/createFluentFontIcon("HandPointFilled", "", 2, undefined));
export const HandPointRegular = ( /*#__PURE__*/createFluentFontIcon("HandPointRegular", "", 2, undefined));
export const HandPoint16Regular = ( /*#__PURE__*/createFluentFontIcon("HandPoint16Regular", "󰖇", 1, 16));
export const HandPoint16Filled = ( /*#__PURE__*/createFluentFontIcon("HandPoint16Filled", "󰘀", 0, 16));
export const HandPoint20Regular = ( /*#__PURE__*/createFluentFontIcon("HandPoint20Regular", "󰖈", 1, 20));
export const HandPoint20Filled = ( /*#__PURE__*/createFluentFontIcon("HandPoint20Filled", "󰘁", 0, 20));
export const HandPoint24Regular = ( /*#__PURE__*/createFluentFontIcon("HandPoint24Regular", "󰖉", 1, 24));
export const HandPoint24Filled = ( /*#__PURE__*/createFluentFontIcon("HandPoint24Filled", "󰘂", 0, 24));
export const HandPoint28Regular = ( /*#__PURE__*/createFluentFontIcon("HandPoint28Regular", "󰖊", 1, 28));
export const HandPoint28Filled = ( /*#__PURE__*/createFluentFontIcon("HandPoint28Filled", "󰘃", 0, 28));
export const HandPoint32Regular = ( /*#__PURE__*/createFluentFontIcon("HandPoint32Regular", "󰖋", 1, 32));
export const HandPoint32Filled = ( /*#__PURE__*/createFluentFontIcon("HandPoint32Filled", "󰘄", 0, 32));
export const HandPoint48Regular = ( /*#__PURE__*/createFluentFontIcon("HandPoint48Regular", "󰖌", 1, 48));
export const HandPoint48Filled = ( /*#__PURE__*/createFluentFontIcon("HandPoint48Filled", "󰘅", 0, 48));
