"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HapticStrongFilled = ( /*#__PURE__*/createFluentFontIcon("HapticStrongFilled", "", 2, undefined));
export const HapticStrongRegular = ( /*#__PURE__*/createFluentFontIcon("HapticStrongRegular", "", 2, undefined));
export const HapticStrong16Regular = ( /*#__PURE__*/createFluentFontIcon("HapticStrong16Regular", "󰖥", 1, 16));
export const HapticStrong16Filled = ( /*#__PURE__*/createFluentFontIcon("HapticStrong16Filled", "󰘞", 0, 16));
export const HapticStrong20Regular = ( /*#__PURE__*/createFluentFontIcon("HapticStrong20Regular", "󰖦", 1, 20));
export const HapticStrong20Filled = ( /*#__PURE__*/createFluentFontIcon("HapticStrong20Filled", "󰘟", 0, 20));
export const HapticStrong24Regular = ( /*#__PURE__*/createFluentFontIcon("HapticStrong24Regular", "󰖧", 1, 24));
export const HapticStrong24Filled = ( /*#__PURE__*/createFluentFontIcon("HapticStrong24Filled", "󰘠", 0, 24));
