"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HapticWeakFilled = ( /*#__PURE__*/createFluentFontIcon("HapticWeakFilled", "", 2, undefined));
export const HapticWeakRegular = ( /*#__PURE__*/createFluentFontIcon("HapticWeakRegular", "", 2, undefined));
export const HapticWeak16Regular = ( /*#__PURE__*/createFluentFontIcon("HapticWeak16Regular", "󰖨", 1, 16));
export const HapticWeak16Filled = ( /*#__PURE__*/createFluentFontIcon("HapticWeak16Filled", "󰘡", 0, 16));
export const HapticWeak20Regular = ( /*#__PURE__*/createFluentFontIcon("HapticWeak20Regular", "󰖩", 1, 20));
export const HapticWeak20Filled = ( /*#__PURE__*/createFluentFontIcon("HapticWeak20Filled", "󰘢", 0, 20));
export const HapticWeak24Regular = ( /*#__PURE__*/createFluentFontIcon("HapticWeak24Regular", "󰖪", 1, 24));
export const HapticWeak24Filled = ( /*#__PURE__*/createFluentFontIcon("HapticWeak24Filled", "󰘣", 0, 24));
