"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HdOffFilled = ( /*#__PURE__*/createFluentFontIcon("HdOffFilled", "", 2, undefined));
export const HdOffRegular = ( /*#__PURE__*/createFluentFontIcon("HdOffRegular", "", 2, undefined));
export const HdOff16Regular = ( /*#__PURE__*/createFluentFontIcon("HdOff16Regular", "󰞱", 1, 16));
export const HdOff16Filled = ( /*#__PURE__*/createFluentFontIcon("HdOff16Filled", "󰠮", 0, 16));
export const HdOff20Regular = ( /*#__PURE__*/createFluentFontIcon("HdOff20Regular", "󰞲", 1, 20));
export const HdOff20Filled = ( /*#__PURE__*/createFluentFontIcon("HdOff20Filled", "󰠯", 0, 20));
export const HdOff24Regular = ( /*#__PURE__*/createFluentFontIcon("HdOff24Regular", "󰞳", 1, 24));
export const HdOff24Filled = ( /*#__PURE__*/createFluentFontIcon("HdOff24Filled", "󰠰", 0, 24));
