"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HeadphonesFilled = ( /*#__PURE__*/createFluentFontIcon("HeadphonesFilled", "", 2, undefined));
export const HeadphonesRegular = ( /*#__PURE__*/createFluentFontIcon("HeadphonesRegular", "", 2, undefined));
export const Headphones12Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones12Regular", "󰩹", 1, 12));
export const Headphones12Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones12Filled", "󰫵", 0, 12));
export const Headphones16Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones16Regular", "󰩺", 1, 16));
export const Headphones16Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones16Filled", "󰫶", 0, 16));
export const Headphones20Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones20Regular", "", 1, 20));
export const Headphones20Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones20Filled", "", 0, 20));
export const Headphones24Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones24Regular", "", 1, 24));
export const Headphones24Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones24Filled", "", 0, 24));
export const Headphones28Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones28Regular", "", 1, 28));
export const Headphones28Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones28Filled", "", 0, 28));
export const Headphones32Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones32Regular", "", 1, 32));
export const Headphones32Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones32Filled", "", 0, 32));
export const Headphones48Regular = ( /*#__PURE__*/createFluentFontIcon("Headphones48Regular", "", 1, 48));
export const Headphones48Filled = ( /*#__PURE__*/createFluentFontIcon("Headphones48Filled", "", 0, 48));
