"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HeartPulseFilled = ( /*#__PURE__*/createFluentFontIcon("HeartPulseFilled", "", 2, undefined));
export const HeartPulseRegular = ( /*#__PURE__*/createFluentFontIcon("HeartPulseRegular", "", 2, undefined));
export const HeartPulse20Regular = ( /*#__PURE__*/createFluentFontIcon("HeartPulse20Regular", "", 1, 20));
export const HeartPulse20Filled = ( /*#__PURE__*/createFluentFontIcon("HeartPulse20Filled", "", 0, 20));
export const HeartPulse24Regular = ( /*#__PURE__*/createFluentFontIcon("HeartPulse24Regular", "", 1, 24));
export const HeartPulse24Filled = ( /*#__PURE__*/createFluentFontIcon("HeartPulse24Filled", "", 0, 24));
export const HeartPulse32Regular = ( /*#__PURE__*/createFluentFontIcon("HeartPulse32Regular", "", 1, 32));
export const HeartPulse32Filled = ( /*#__PURE__*/createFluentFontIcon("HeartPulse32Filled", "", 0, 32));
