"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HeartOffFilled = ( /*#__PURE__*/createFluentFontIcon("HeartOffFilled", "", 2, undefined));
export const HeartOffRegular = ( /*#__PURE__*/createFluentFontIcon("HeartOffRegular", "", 2, undefined));
export const HeartOff16Regular = ( /*#__PURE__*/createFluentFontIcon("HeartOff16Regular", "󰊰", 1, 16));
export const HeartOff16Filled = ( /*#__PURE__*/createFluentFontIcon("HeartOff16Filled", "󰋃", 0, 16));
export const HeartOff20Regular = ( /*#__PURE__*/createFluentFontIcon("HeartOff20Regular", "󰊱", 1, 20));
export const HeartOff20Filled = ( /*#__PURE__*/createFluentFontIcon("HeartOff20Filled", "󰋄", 0, 20));
export const HeartOff24Regular = ( /*#__PURE__*/createFluentFontIcon("HeartOff24Regular", "󰊲", 1, 24));
export const HeartOff24Filled = ( /*#__PURE__*/createFluentFontIcon("HeartOff24Filled", "󰋅", 0, 24));
