"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HexagonSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkleFilled", "", 2, undefined));
export const HexagonSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkleRegular", "", 2, undefined));
export const HexagonSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle16Regular", "󰧈", 1, 16));
export const HexagonSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle16Filled", "󰩅", 0, 16));
export const HexagonSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle20Regular", "󰖫", 1, 20));
export const HexagonSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle20Filled", "󰘤", 0, 20));
export const HexagonSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle24Regular", "󰖬", 1, 24));
export const HexagonSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle24Filled", "󰘥", 0, 24));
export const HexagonSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle28Regular", "󰧉", 1, 28));
export const HexagonSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle28Filled", "󰩆", 0, 28));
export const HexagonSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle32Regular", "󰧊", 1, 32));
export const HexagonSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle32Filled", "󰩇", 0, 32));
export const HexagonSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle48Regular", "󰧋", 1, 48));
export const HexagonSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon("HexagonSparkle48Filled", "󰩈", 0, 48));
