"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HighlightFilled = ( /*#__PURE__*/createFluentFontIcon("HighlightFilled", "", 2, undefined));
export const HighlightRegular = ( /*#__PURE__*/createFluentFontIcon("HighlightRegular", "", 2, undefined));
export const Highlight16Regular = ( /*#__PURE__*/createFluentFontIcon("Highlight16Regular", "", 1, 16));
export const Highlight16Filled = ( /*#__PURE__*/createFluentFontIcon("Highlight16Filled", "", 0, 16));
export const Highlight20Regular = ( /*#__PURE__*/createFluentFontIcon("Highlight20Regular", "", 1, 20));
export const Highlight20Filled = ( /*#__PURE__*/createFluentFontIcon("Highlight20Filled", "", 0, 20));
export const Highlight24Regular = ( /*#__PURE__*/createFluentFontIcon("Highlight24Regular", "", 1, 24));
export const Highlight24Filled = ( /*#__PURE__*/createFluentFontIcon("Highlight24Filled", "", 0, 24));
