"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HomeHeartFilled = ( /*#__PURE__*/createFluentFontIcon("HomeHeartFilled", "", 2, undefined));
export const HomeHeartRegular = ( /*#__PURE__*/createFluentFontIcon("HomeHeartRegular", "", 2, undefined));
export const HomeHeart16Regular = ( /*#__PURE__*/createFluentFontIcon("HomeHeart16Regular", "󰇕", 1, 16));
export const HomeHeart16Filled = ( /*#__PURE__*/createFluentFontIcon("HomeHeart16Filled", "󰇕", 0, 16));
export const HomeHeart20Regular = ( /*#__PURE__*/createFluentFontIcon("HomeHeart20Regular", "󰇖", 1, 20));
export const HomeHeart20Filled = ( /*#__PURE__*/createFluentFontIcon("HomeHeart20Filled", "󰇖", 0, 20));
export const HomeHeart24Regular = ( /*#__PURE__*/createFluentFontIcon("HomeHeart24Regular", "󰇗", 1, 24));
export const HomeHeart24Filled = ( /*#__PURE__*/createFluentFontIcon("HomeHeart24Filled", "󰇗", 0, 24));
export const HomeHeart32Regular = ( /*#__PURE__*/createFluentFontIcon("HomeHeart32Regular", "󰇘", 1, 32));
export const HomeHeart32Filled = ( /*#__PURE__*/createFluentFontIcon("HomeHeart32Filled", "󰇘", 0, 32));
