"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const HomeSplitFilled = ( /*#__PURE__*/createFluentFontIcon("HomeSplitFilled", "", 2, undefined));
export const HomeSplitRegular = ( /*#__PURE__*/createFluentFontIcon("HomeSplitRegular", "", 2, undefined));
export const HomeSplit20Regular = ( /*#__PURE__*/createFluentFontIcon("HomeSplit20Regular", "", 1, 20));
export const HomeSplit20Filled = ( /*#__PURE__*/createFluentFontIcon("HomeSplit20Filled", "", 0, 20));
export const HomeSplit24Regular = ( /*#__PURE__*/createFluentFontIcon("HomeSplit24Regular", "", 1, 24));
export const HomeSplit24Filled = ( /*#__PURE__*/createFluentFontIcon("HomeSplit24Filled", "", 0, 24));
export const HomeSplit32Regular = ( /*#__PURE__*/createFluentFontIcon("HomeSplit32Regular", "", 1, 32));
export const HomeSplit32Filled = ( /*#__PURE__*/createFluentFontIcon("HomeSplit32Filled", "", 0, 32));
export const HomeSplit48Regular = ( /*#__PURE__*/createFluentFontIcon("HomeSplit48Regular", "", 1, 48));
export const HomeSplit48Filled = ( /*#__PURE__*/createFluentFontIcon("HomeSplit48Filled", "", 0, 48));
