"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImageBorderFilled = ( /*#__PURE__*/createFluentFontIcon("ImageBorderFilled", "", 2, undefined));
export const ImageBorderRegular = ( /*#__PURE__*/createFluentFontIcon("ImageBorderRegular", "", 2, undefined));
export const ImageBorder16Regular = ( /*#__PURE__*/createFluentFontIcon("ImageBorder16Regular", "󰁇", 1, 16));
export const ImageBorder16Filled = ( /*#__PURE__*/createFluentFontIcon("ImageBorder16Filled", "󰁋", 0, 16));
export const ImageBorder20Regular = ( /*#__PURE__*/createFluentFontIcon("ImageBorder20Regular", "󰁈", 1, 20));
export const ImageBorder20Filled = ( /*#__PURE__*/createFluentFontIcon("ImageBorder20Filled", "󰁌", 0, 20));
export const ImageBorder24Regular = ( /*#__PURE__*/createFluentFontIcon("ImageBorder24Regular", "󰁉", 1, 24));
export const ImageBorder24Filled = ( /*#__PURE__*/createFluentFontIcon("ImageBorder24Filled", "󰁍", 0, 24));
export const ImageBorder28Regular = ( /*#__PURE__*/createFluentFontIcon("ImageBorder28Regular", "󰁊", 1, 28));
export const ImageBorder28Filled = ( /*#__PURE__*/createFluentFontIcon("ImageBorder28Filled", "󰁎", 0, 28));
export const ImageBorder32Regular = ( /*#__PURE__*/createFluentFontIcon("ImageBorder32Regular", "󰁋", 1, 32));
export const ImageBorder32Filled = ( /*#__PURE__*/createFluentFontIcon("ImageBorder32Filled", "󰁏", 0, 32));
export const ImageBorder48Regular = ( /*#__PURE__*/createFluentFontIcon("ImageBorder48Regular", "󰁌", 1, 48));
export const ImageBorder48Filled = ( /*#__PURE__*/createFluentFontIcon("ImageBorder48Filled", "󰁐", 0, 48));
