"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImageOffFilled = ( /*#__PURE__*/createFluentFontIcon("ImageOffFilled", "", 2, undefined));
export const ImageOffRegular = ( /*#__PURE__*/createFluentFontIcon("ImageOffRegular", "", 2, undefined));
export const ImageOff20Regular = ( /*#__PURE__*/createFluentFontIcon("ImageOff20Regular", "", 1, 20));
export const ImageOff20Filled = ( /*#__PURE__*/createFluentFontIcon("ImageOff20Filled", "", 0, 20));
export const ImageOff24Regular = ( /*#__PURE__*/createFluentFontIcon("ImageOff24Regular", "", 1, 24));
export const ImageOff24Filled = ( /*#__PURE__*/createFluentFontIcon("ImageOff24Filled", "", 0, 24));
export const ImageOff28Regular = ( /*#__PURE__*/createFluentFontIcon("ImageOff28Regular", "󰇙", 1, 28));
export const ImageOff28Filled = ( /*#__PURE__*/createFluentFontIcon("ImageOff28Filled", "󰇙", 0, 28));
export const ImageOff32Regular = ( /*#__PURE__*/createFluentFontIcon("ImageOff32Regular", "󰇚", 1, 32));
export const ImageOff32Filled = ( /*#__PURE__*/createFluentFontIcon("ImageOff32Filled", "󰇚", 0, 32));
export const ImageOff48Regular = ( /*#__PURE__*/createFluentFontIcon("ImageOff48Regular", "󰇛", 1, 48));
export const ImageOff48Filled = ( /*#__PURE__*/createFluentFontIcon("ImageOff48Filled", "󰇛", 0, 48));
