"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImageEditFilled = ( /*#__PURE__*/createFluentFontIcon("ImageEditFilled", "", 2, undefined));
export const ImageEditRegular = ( /*#__PURE__*/createFluentFontIcon("ImageEditRegular", "", 2, undefined));
export const ImageEdit16Regular = ( /*#__PURE__*/createFluentFontIcon("ImageEdit16Regular", "", 1, 16));
export const ImageEdit16Filled = ( /*#__PURE__*/createFluentFontIcon("ImageEdit16Filled", "", 0, 16));
export const ImageEdit20Regular = ( /*#__PURE__*/createFluentFontIcon("ImageEdit20Regular", "", 1, 20));
export const ImageEdit20Filled = ( /*#__PURE__*/createFluentFontIcon("ImageEdit20Filled", "", 0, 20));
export const ImageEdit24Regular = ( /*#__PURE__*/createFluentFontIcon("ImageEdit24Regular", "", 1, 24));
export const ImageEdit24Filled = ( /*#__PURE__*/createFluentFontIcon("ImageEdit24Filled", "", 0, 24));
