"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImageCircleFilled = ( /*#__PURE__*/createFluentFontIcon("ImageCircleFilled", "", 2, undefined));
export const ImageCircleRegular = ( /*#__PURE__*/createFluentFontIcon("ImageCircleRegular", "", 2, undefined));
export const ImageCircle16Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCircle16Regular", "󰁍", 1, 16));
export const ImageCircle16Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCircle16Filled", "󰁑", 0, 16));
export const ImageCircle20Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCircle20Regular", "󰁎", 1, 20));
export const ImageCircle20Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCircle20Filled", "󰁒", 0, 20));
export const ImageCircle24Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCircle24Regular", "󰁏", 1, 24));
export const ImageCircle24Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCircle24Filled", "󰁓", 0, 24));
export const ImageCircle28Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCircle28Regular", "󰁐", 1, 28));
export const ImageCircle28Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCircle28Filled", "󰁔", 0, 28));
export const ImageCircle32Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCircle32Regular", "󰁑", 1, 32));
export const ImageCircle32Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCircle32Filled", "󰁕", 0, 32));
export const ImageCircle48Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCircle48Regular", "󰁒", 1, 48));
export const ImageCircle48Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCircle48Filled", "󰁖", 0, 48));
