"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImageCopyFilled = ( /*#__PURE__*/createFluentFontIcon("ImageCopyFilled", "", 2, undefined));
export const ImageCopyRegular = ( /*#__PURE__*/createFluentFontIcon("ImageCopyRegular", "", 2, undefined));
export const ImageCopy20Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCopy20Regular", "", 1, 20));
export const ImageCopy20Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCopy20Filled", "", 0, 20));
export const ImageCopy24Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCopy24Regular", "", 1, 24));
export const ImageCopy24Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCopy24Filled", "", 0, 24));
export const ImageCopy28Regular = ( /*#__PURE__*/createFluentFontIcon("ImageCopy28Regular", "", 1, 28));
export const ImageCopy28Filled = ( /*#__PURE__*/createFluentFontIcon("ImageCopy28Filled", "", 0, 28));
export const ImageCopy32Light = ( /*#__PURE__*/createFluentFontIcon("ImageCopy32Light", "", 3, 32));
