"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImmersiveReaderFilled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReaderFilled", "", 2, undefined));
export const ImmersiveReaderRegular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReaderRegular", "", 2, undefined));
export const ImmersiveReader16Regular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader16Regular", "", 1, 16));
export const ImmersiveReader16Filled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader16Filled", "", 0, 16));
export const ImmersiveReader20Regular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader20Regular", "", 1, 20));
export const ImmersiveReader20Filled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader20Filled", "", 0, 20));
export const ImmersiveReader24Regular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader24Regular", "", 1, 24));
export const ImmersiveReader24Filled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader24Filled", "", 0, 24));
export const ImmersiveReader28Regular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader28Regular", "", 1, 28));
export const ImmersiveReader28Filled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader28Filled", "", 0, 28));
export const ImmersiveReader32Regular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader32Regular", "󰦽", 1, 32));
export const ImmersiveReader32Filled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader32Filled", "󰨺", 0, 32));
export const ImmersiveReader32Light = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader32Light", "", 3, 32));
export const ImmersiveReader48Regular = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader48Regular", "󰦾", 1, 48));
export const ImmersiveReader48Filled = ( /*#__PURE__*/createFluentFontIcon("ImmersiveReader48Filled", "󰨻", 0, 48));
