"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ImportantFilled = ( /*#__PURE__*/createFluentFontIcon("ImportantFilled", "", 2, undefined));
export const ImportantRegular = ( /*#__PURE__*/createFluentFontIcon("ImportantRegular", "", 2, undefined));
export const Important12Regular = ( /*#__PURE__*/createFluentFontIcon("Important12Regular", "", 1, 12));
export const Important12Filled = ( /*#__PURE__*/createFluentFontIcon("Important12Filled", "", 0, 12));
export const Important16Regular = ( /*#__PURE__*/createFluentFontIcon("Important16Regular", "", 1, 16));
export const Important16Filled = ( /*#__PURE__*/createFluentFontIcon("Important16Filled", "", 0, 16));
export const Important20Regular = ( /*#__PURE__*/createFluentFontIcon("Important20Regular", "", 1, 20));
export const Important20Filled = ( /*#__PURE__*/createFluentFontIcon("Important20Filled", "", 0, 20));
export const Important24Regular = ( /*#__PURE__*/createFluentFontIcon("Important24Regular", "", 1, 24));
export const Important24Filled = ( /*#__PURE__*/createFluentFontIcon("Important24Filled", "", 0, 24));
export const Important28Regular = ( /*#__PURE__*/createFluentFontIcon("Important28Regular", "󰩽", 1, 28));
export const Important28Filled = ( /*#__PURE__*/createFluentFontIcon("Important28Filled", "󰫹", 0, 28));
export const Important32Regular = ( /*#__PURE__*/createFluentFontIcon("Important32Regular", "󰑄", 1, 32));
export const Important32Filled = ( /*#__PURE__*/createFluentFontIcon("Important32Filled", "󰑗", 0, 32));
export const Important32Light = ( /*#__PURE__*/createFluentFontIcon("Important32Light", "", 3, 32));
