"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const InfoSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkleFilled", "", 2, undefined));
export const InfoSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkleRegular", "", 2, undefined));
export const InfoSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle16Regular", "󰡖", 1, 16));
export const InfoSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle16Filled", "󰣓", 0, 16));
export const InfoSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle20Regular", "󰡗", 1, 20));
export const InfoSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle20Filled", "󰣔", 0, 20));
export const InfoSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle24Regular", "󰡘", 1, 24));
export const InfoSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle24Filled", "󰣕", 0, 24));
export const InfoSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle28Regular", "󰡙", 1, 28));
export const InfoSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle28Filled", "󰣖", 0, 28));
export const InfoSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle32Regular", "󰡚", 1, 32));
export const InfoSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle32Filled", "󰣗", 0, 32));
export const InfoSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle48Regular", "󰡛", 1, 48));
export const InfoSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon("InfoSparkle48Filled", "󰣘", 0, 48));
