"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const InkingToolFilled = ( /*#__PURE__*/createFluentFontIcon("InkingToolFilled", "", 2, undefined));
export const InkingToolRegular = ( /*#__PURE__*/createFluentFontIcon("InkingToolRegular", "", 2, undefined));
export const InkingTool16Regular = ( /*#__PURE__*/createFluentFontIcon("InkingTool16Regular", "", 1, 16));
export const InkingTool16Filled = ( /*#__PURE__*/createFluentFontIcon("InkingTool16Filled", "", 0, 16));
export const InkingTool20Regular = ( /*#__PURE__*/createFluentFontIcon("InkingTool20Regular", "", 1, 20));
export const InkingTool20Filled = ( /*#__PURE__*/createFluentFontIcon("InkingTool20Filled", "", 0, 20));
export const InkingTool24Regular = ( /*#__PURE__*/createFluentFontIcon("InkingTool24Regular", "", 1, 24));
export const InkingTool24Filled = ( /*#__PURE__*/createFluentFontIcon("InkingTool24Filled", "", 0, 24));
export const InkingTool32Regular = ( /*#__PURE__*/createFluentFontIcon("InkingTool32Regular", "", 1, 32));
export const InkingTool32Filled = ( /*#__PURE__*/createFluentFontIcon("InkingTool32Filled", "", 0, 32));
