"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const IotFilled = ( /*#__PURE__*/createFluentFontIcon("IotFilled", "", 2, undefined));
export const IotRegular = ( /*#__PURE__*/createFluentFontIcon("IotRegular", "", 2, undefined));
export const Iot16Regular = ( /*#__PURE__*/createFluentFontIcon("Iot16Regular", "󰁛", 1, 16));
export const Iot16Filled = ( /*#__PURE__*/createFluentFontIcon("Iot16Filled", "󰁟", 0, 16));
export const Iot20Regular = ( /*#__PURE__*/createFluentFontIcon("Iot20Regular", "", 1, 20));
export const Iot20Filled = ( /*#__PURE__*/createFluentFontIcon("Iot20Filled", "", 0, 20));
export const Iot24Regular = ( /*#__PURE__*/createFluentFontIcon("Iot24Regular", "", 1, 24));
export const Iot24Filled = ( /*#__PURE__*/createFluentFontIcon("Iot24Filled", "", 0, 24));
