"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const KeyFilled = ( /*#__PURE__*/createFluentFontIcon("KeyFilled", "", 2, undefined));
export const KeyRegular = ( /*#__PURE__*/createFluentFontIcon("KeyRegular", "", 2, undefined));
export const Key16Regular = ( /*#__PURE__*/createFluentFontIcon("Key16Regular", "", 1, 16));
export const Key16Filled = ( /*#__PURE__*/createFluentFontIcon("Key16Filled", "", 0, 16));
export const Key20Regular = ( /*#__PURE__*/createFluentFontIcon("Key20Regular", "", 1, 20));
export const Key20Filled = ( /*#__PURE__*/createFluentFontIcon("Key20Filled", "", 0, 20));
export const Key24Regular = ( /*#__PURE__*/createFluentFontIcon("Key24Regular", "", 1, 24));
export const Key24Filled = ( /*#__PURE__*/createFluentFontIcon("Key24Filled", "", 0, 24));
export const Key32Regular = ( /*#__PURE__*/createFluentFontIcon("Key32Regular", "", 1, 32));
export const Key32Filled = ( /*#__PURE__*/createFluentFontIcon("Key32Filled", "", 0, 32));
