"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LeafThreeFilled = ( /*#__PURE__*/createFluentFontIcon("LeafThreeFilled", "", 2, undefined));
export const LeafThreeRegular = ( /*#__PURE__*/createFluentFontIcon("LeafThreeRegular", "", 2, undefined));
export const LeafThree16Regular = ( /*#__PURE__*/createFluentFontIcon("LeafThree16Regular", "", 1, 16));
export const LeafThree16Filled = ( /*#__PURE__*/createFluentFontIcon("LeafThree16Filled", "", 0, 16));
export const LeafThree20Regular = ( /*#__PURE__*/createFluentFontIcon("LeafThree20Regular", "", 1, 20));
export const LeafThree20Filled = ( /*#__PURE__*/createFluentFontIcon("LeafThree20Filled", "", 0, 20));
export const LeafThree24Regular = ( /*#__PURE__*/createFluentFontIcon("LeafThree24Regular", "", 1, 24));
export const LeafThree24Filled = ( /*#__PURE__*/createFluentFontIcon("LeafThree24Filled", "", 0, 24));
