"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LeafOneFilled = ( /*#__PURE__*/createFluentFontIcon("LeafOneFilled", "", 2, undefined));
export const LeafOneRegular = ( /*#__PURE__*/createFluentFontIcon("LeafOneRegular", "", 2, undefined));
export const LeafOne16Regular = ( /*#__PURE__*/createFluentFontIcon("LeafOne16Regular", "", 1, 16));
export const LeafOne16Filled = ( /*#__PURE__*/createFluentFontIcon("LeafOne16Filled", "", 0, 16));
export const LeafOne20Regular = ( /*#__PURE__*/createFluentFontIcon("LeafOne20Regular", "", 1, 20));
export const LeafOne20Filled = ( /*#__PURE__*/createFluentFontIcon("LeafOne20Filled", "", 0, 20));
export const LeafOne24Regular = ( /*#__PURE__*/createFluentFontIcon("LeafOne24Regular", "", 1, 24));
export const LeafOne24Filled = ( /*#__PURE__*/createFluentFontIcon("LeafOne24Filled", "", 0, 24));
export const LeafOne32Regular = ( /*#__PURE__*/createFluentFontIcon("LeafOne32Regular", "", 1, 32));
export const LeafOne32Filled = ( /*#__PURE__*/createFluentFontIcon("LeafOne32Filled", "", 0, 32));
