"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LightbulbFilled = ( /*#__PURE__*/createFluentFontIcon("LightbulbFilled", "", 2, undefined));
export const LightbulbRegular = ( /*#__PURE__*/createFluentFontIcon("LightbulbRegular", "", 2, undefined));
export const Lightbulb16Regular = ( /*#__PURE__*/createFluentFontIcon("Lightbulb16Regular", "", 1, 16));
export const Lightbulb16Filled = ( /*#__PURE__*/createFluentFontIcon("Lightbulb16Filled", "", 0, 16));
export const Lightbulb20Regular = ( /*#__PURE__*/createFluentFontIcon("Lightbulb20Regular", "", 1, 20));
export const Lightbulb20Filled = ( /*#__PURE__*/createFluentFontIcon("Lightbulb20Filled", "", 0, 20));
export const Lightbulb24Regular = ( /*#__PURE__*/createFluentFontIcon("Lightbulb24Regular", "", 1, 24));
export const Lightbulb24Filled = ( /*#__PURE__*/createFluentFontIcon("Lightbulb24Filled", "", 0, 24));
export const Lightbulb28Regular = ( /*#__PURE__*/createFluentFontIcon("Lightbulb28Regular", "", 1, 28));
export const Lightbulb28Filled = ( /*#__PURE__*/createFluentFontIcon("Lightbulb28Filled", "", 0, 28));
export const Lightbulb32Regular = ( /*#__PURE__*/createFluentFontIcon("Lightbulb32Regular", "", 1, 32));
export const Lightbulb32Filled = ( /*#__PURE__*/createFluentFontIcon("Lightbulb32Filled", "", 0, 32));
export const Lightbulb32Light = ( /*#__PURE__*/createFluentFontIcon("Lightbulb32Light", "", 3, 32));
export const Lightbulb48Regular = ( /*#__PURE__*/createFluentFontIcon("Lightbulb48Regular", "", 1, 48));
export const Lightbulb48Filled = ( /*#__PURE__*/createFluentFontIcon("Lightbulb48Filled", "", 0, 48));
