"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LightbulbPersonFilled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPersonFilled", "", 2, undefined));
export const LightbulbPersonRegular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPersonRegular", "", 2, undefined));
export const LightbulbPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson16Regular", "", 1, 16));
export const LightbulbPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson16Filled", "", 0, 16));
export const LightbulbPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson20Regular", "", 1, 20));
export const LightbulbPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson20Filled", "", 0, 20));
export const LightbulbPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson24Regular", "", 1, 24));
export const LightbulbPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson24Filled", "", 0, 24));
export const LightbulbPerson28Regular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson28Regular", "", 1, 28));
export const LightbulbPerson28Filled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson28Filled", "", 0, 28));
export const LightbulbPerson32Regular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson32Regular", "", 1, 32));
export const LightbulbPerson32Filled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson32Filled", "", 0, 32));
export const LightbulbPerson48Regular = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson48Regular", "", 1, 48));
export const LightbulbPerson48Filled = ( /*#__PURE__*/createFluentFontIcon("LightbulbPerson48Filled", "", 0, 48));
