"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LikertFilled = ( /*#__PURE__*/createFluentFontIcon("LikertFilled", "", 2, undefined));
export const LikertRegular = ( /*#__PURE__*/createFluentFontIcon("LikertRegular", "", 2, undefined));
export const Likert16Regular = ( /*#__PURE__*/createFluentFontIcon("Likert16Regular", "", 1, 16));
export const Likert16Filled = ( /*#__PURE__*/createFluentFontIcon("Likert16Filled", "", 0, 16));
export const Likert20Regular = ( /*#__PURE__*/createFluentFontIcon("Likert20Regular", "", 1, 20));
export const Likert20Filled = ( /*#__PURE__*/createFluentFontIcon("Likert20Filled", "", 0, 20));
export const Likert24Regular = ( /*#__PURE__*/createFluentFontIcon("Likert24Regular", "", 1, 24));
export const Likert24Filled = ( /*#__PURE__*/createFluentFontIcon("Likert24Filled", "", 0, 24));
