"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LineFilled = ( /*#__PURE__*/createFluentFontIcon("LineFilled", "", 2, undefined));
export const LineRegular = ( /*#__PURE__*/createFluentFontIcon("LineRegular", "", 2, undefined));
export const Line20Regular = ( /*#__PURE__*/createFluentFontIcon("Line20Regular", "", 1, 20));
export const Line20Filled = ( /*#__PURE__*/createFluentFontIcon("Line20Filled", "", 0, 20));
export const Line24Regular = ( /*#__PURE__*/createFluentFontIcon("Line24Regular", "", 1, 24));
export const Line24Filled = ( /*#__PURE__*/createFluentFontIcon("Line24Filled", "", 0, 24));
export const Line32Regular = ( /*#__PURE__*/createFluentFontIcon("Line32Regular", "", 1, 32));
export const Line32Filled = ( /*#__PURE__*/createFluentFontIcon("Line32Filled", "", 0, 32));
export const Line48Regular = ( /*#__PURE__*/createFluentFontIcon("Line48Regular", "", 1, 48));
export const Line48Filled = ( /*#__PURE__*/createFluentFontIcon("Line48Filled", "", 0, 48));
