"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LinkDismissFilled = ( /*#__PURE__*/createFluentFontIcon("LinkDismissFilled", "", 2, undefined));
export const LinkDismissRegular = ( /*#__PURE__*/createFluentFontIcon("LinkDismissRegular", "", 2, undefined));
export const LinkDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("LinkDismiss16Regular", "", 1, 16));
export const LinkDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("LinkDismiss16Filled", "", 0, 16));
export const LinkDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("LinkDismiss20Regular", "", 1, 20));
export const LinkDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("LinkDismiss20Filled", "", 0, 20));
export const LinkDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("LinkDismiss24Regular", "", 1, 24));
export const LinkDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("LinkDismiss24Filled", "", 0, 24));
