"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LinkAddFilled = ( /*#__PURE__*/createFluentFontIcon("LinkAddFilled", "", 2, undefined));
export const LinkAddRegular = ( /*#__PURE__*/createFluentFontIcon("LinkAddRegular", "", 2, undefined));
export const LinkAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("LinkAdd16Regular", "󰐅", 1, 16));
export const LinkAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("LinkAdd16Filled", "󰐘", 0, 16));
export const LinkAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("LinkAdd20Regular", "󰐆", 1, 20));
export const LinkAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("LinkAdd20Filled", "󰐙", 0, 20));
export const LinkAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("LinkAdd24Regular", "󰈝", 1, 24));
export const LinkAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("LinkAdd24Filled", "󰈰", 0, 24));
