"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LinkPersonFilled = ( /*#__PURE__*/createFluentFontIcon("LinkPersonFilled", "", 2, undefined));
export const LinkPersonRegular = ( /*#__PURE__*/createFluentFontIcon("LinkPersonRegular", "", 2, undefined));
export const LinkPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("LinkPerson16Regular", "󰎺", 1, 16));
export const LinkPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("LinkPerson16Filled", "󰏍", 0, 16));
export const LinkPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("LinkPerson20Regular", "󰎻", 1, 20));
export const LinkPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("LinkPerson20Filled", "󰏎", 0, 20));
export const LinkPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("LinkPerson24Regular", "󰎼", 1, 24));
export const LinkPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("LinkPerson24Filled", "󰏏", 0, 24));
export const LinkPerson32Regular = ( /*#__PURE__*/createFluentFontIcon("LinkPerson32Regular", "󰎽", 1, 32));
export const LinkPerson32Filled = ( /*#__PURE__*/createFluentFontIcon("LinkPerson32Filled", "󰏐", 0, 32));
export const LinkPerson48Regular = ( /*#__PURE__*/createFluentFontIcon("LinkPerson48Regular", "󰎾", 1, 48));
export const LinkPerson48Filled = ( /*#__PURE__*/createFluentFontIcon("LinkPerson48Filled", "󰏑", 0, 48));
