"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ListFilled = ( /*#__PURE__*/createFluentFontIcon("ListFilled", "", 2, undefined));
export const ListRegular = ( /*#__PURE__*/createFluentFontIcon("ListRegular", "", 2, undefined));
export const List16Regular = ( /*#__PURE__*/createFluentFontIcon("List16Regular", "", 1, 16));
export const List16Filled = ( /*#__PURE__*/createFluentFontIcon("List16Filled", "", 0, 16));
export const List20Regular = ( /*#__PURE__*/createFluentFontIcon("List20Regular", "", 1, 20));
export const List20Filled = ( /*#__PURE__*/createFluentFontIcon("List20Filled", "", 0, 20));
export const List24Regular = ( /*#__PURE__*/createFluentFontIcon("List24Regular", "", 1, 24));
export const List24Filled = ( /*#__PURE__*/createFluentFontIcon("List24Filled", "", 0, 24));
export const List28Regular = ( /*#__PURE__*/createFluentFontIcon("List28Regular", "", 1, 28));
export const List28Filled = ( /*#__PURE__*/createFluentFontIcon("List28Filled", "", 0, 28));
