"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ListBarFilled = ( /*#__PURE__*/createFluentFontIcon("ListBarFilled", "", 2, undefined));
export const ListBarRegular = ( /*#__PURE__*/createFluentFontIcon("ListBarRegular", "", 2, undefined));
export const ListBar16Regular = ( /*#__PURE__*/createFluentFontIcon("ListBar16Regular", "󰆑", 1, 16));
export const ListBar16Filled = ( /*#__PURE__*/createFluentFontIcon("ListBar16Filled", "󰆑", 0, 16));
export const ListBar20Regular = ( /*#__PURE__*/createFluentFontIcon("ListBar20Regular", "󰆒", 1, 20));
export const ListBar20Filled = ( /*#__PURE__*/createFluentFontIcon("ListBar20Filled", "󰆒", 0, 20));
export const ListBar24Regular = ( /*#__PURE__*/createFluentFontIcon("ListBar24Regular", "󰡞", 1, 24));
export const ListBar24Filled = ( /*#__PURE__*/createFluentFontIcon("ListBar24Filled", "󰣛", 0, 24));
export const ListBar32Regular = ( /*#__PURE__*/createFluentFontIcon("ListBar32Regular", "󰡟", 1, 32));
export const ListBar32Filled = ( /*#__PURE__*/createFluentFontIcon("ListBar32Filled", "󰣜", 0, 32));
