"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LocationArrowFilled = ( /*#__PURE__*/createFluentFontIcon("LocationArrowFilled", "", 2, undefined));
export const LocationArrowRegular = ( /*#__PURE__*/createFluentFontIcon("LocationArrowRegular", "", 2, undefined));
export const LocationArrow12Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow12Regular", "󰁣", 1, 12));
export const LocationArrow12Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow12Filled", "󰁧", 0, 12));
export const LocationArrow16Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow16Regular", "󰁤", 1, 16));
export const LocationArrow16Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow16Filled", "󰁨", 0, 16));
export const LocationArrow20Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow20Regular", "󰁥", 1, 20));
export const LocationArrow20Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow20Filled", "󰁩", 0, 20));
export const LocationArrow24Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow24Regular", "󰁦", 1, 24));
export const LocationArrow24Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow24Filled", "󰁪", 0, 24));
export const LocationArrow28Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow28Regular", "󰁧", 1, 28));
export const LocationArrow28Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow28Filled", "󰁫", 0, 28));
export const LocationArrow32Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow32Regular", "󰁨", 1, 32));
export const LocationArrow32Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow32Filled", "󰁬", 0, 32));
export const LocationArrow48Regular = ( /*#__PURE__*/createFluentFontIcon("LocationArrow48Regular", "󰁩", 1, 48));
export const LocationArrow48Filled = ( /*#__PURE__*/createFluentFontIcon("LocationArrow48Filled", "󰁭", 0, 48));
