"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LocationFilled = ( /*#__PURE__*/createFluentFontIcon("LocationFilled", "", 2, undefined));
export const LocationRegular = ( /*#__PURE__*/createFluentFontIcon("LocationRegular", "", 2, undefined));
export const Location12Regular = ( /*#__PURE__*/createFluentFontIcon("Location12Regular", "", 1, 12));
export const Location12Filled = ( /*#__PURE__*/createFluentFontIcon("Location12Filled", "", 0, 12));
export const Location16Regular = ( /*#__PURE__*/createFluentFontIcon("Location16Regular", "", 1, 16));
export const Location16Filled = ( /*#__PURE__*/createFluentFontIcon("Location16Filled", "", 0, 16));
export const Location20Regular = ( /*#__PURE__*/createFluentFontIcon("Location20Regular", "", 1, 20));
export const Location20Filled = ( /*#__PURE__*/createFluentFontIcon("Location20Filled", "", 0, 20));
export const Location24Regular = ( /*#__PURE__*/createFluentFontIcon("Location24Regular", "", 1, 24));
export const Location24Filled = ( /*#__PURE__*/createFluentFontIcon("Location24Filled", "", 0, 24));
export const Location28Regular = ( /*#__PURE__*/createFluentFontIcon("Location28Regular", "", 1, 28));
export const Location28Filled = ( /*#__PURE__*/createFluentFontIcon("Location28Filled", "", 0, 28));
export const Location48Regular = ( /*#__PURE__*/createFluentFontIcon("Location48Regular", "", 1, 48));
export const Location48Filled = ( /*#__PURE__*/createFluentFontIcon("Location48Filled", "", 0, 48));
