"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const LuggageFilled = ( /*#__PURE__*/createFluentFontIcon("LuggageFilled", "", 2, undefined));
export const LuggageRegular = ( /*#__PURE__*/createFluentFontIcon("LuggageRegular", "", 2, undefined));
export const Luggage16Regular = ( /*#__PURE__*/createFluentFontIcon("Luggage16Regular", "", 1, 16));
export const Luggage16Filled = ( /*#__PURE__*/createFluentFontIcon("Luggage16Filled", "", 0, 16));
export const Luggage20Regular = ( /*#__PURE__*/createFluentFontIcon("Luggage20Regular", "", 1, 20));
export const Luggage20Filled = ( /*#__PURE__*/createFluentFontIcon("Luggage20Filled", "", 0, 20));
export const Luggage24Regular = ( /*#__PURE__*/createFluentFontIcon("Luggage24Regular", "", 1, 24));
export const Luggage24Filled = ( /*#__PURE__*/createFluentFontIcon("Luggage24Filled", "", 0, 24));
export const Luggage28Regular = ( /*#__PURE__*/createFluentFontIcon("Luggage28Regular", "", 1, 28));
export const Luggage28Filled = ( /*#__PURE__*/createFluentFontIcon("Luggage28Filled", "", 0, 28));
export const Luggage32Regular = ( /*#__PURE__*/createFluentFontIcon("Luggage32Regular", "", 1, 32));
export const Luggage32Filled = ( /*#__PURE__*/createFluentFontIcon("Luggage32Filled", "", 0, 32));
export const Luggage48Regular = ( /*#__PURE__*/createFluentFontIcon("Luggage48Regular", "", 1, 48));
export const Luggage48Filled = ( /*#__PURE__*/createFluentFontIcon("Luggage48Filled", "", 0, 48));
