"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MailErrorFilled = ( /*#__PURE__*/createFluentFontIcon("MailErrorFilled", "", 2, undefined));
export const MailErrorRegular = ( /*#__PURE__*/createFluentFontIcon("MailErrorRegular", "", 2, undefined));
export const MailError16Regular = ( /*#__PURE__*/createFluentFontIcon("MailError16Regular", "", 1, 16));
export const MailError16Filled = ( /*#__PURE__*/createFluentFontIcon("MailError16Filled", "", 0, 16));
export const MailError20Regular = ( /*#__PURE__*/createFluentFontIcon("MailError20Regular", "", 1, 20));
export const MailError20Filled = ( /*#__PURE__*/createFluentFontIcon("MailError20Filled", "", 0, 20));
export const MailError24Regular = ( /*#__PURE__*/createFluentFontIcon("MailError24Regular", "", 1, 24));
export const MailError24Filled = ( /*#__PURE__*/createFluentFontIcon("MailError24Filled", "", 0, 24));
