"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MailDismissFilled = ( /*#__PURE__*/createFluentFontIcon("MailDismissFilled", "", 2, undefined));
export const MailDismissRegular = ( /*#__PURE__*/createFluentFontIcon("MailDismissRegular", "", 2, undefined));
export const MailDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("MailDismiss16Regular", "", 1, 16));
export const MailDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("MailDismiss16Filled", "", 0, 16));
export const MailDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("MailDismiss20Regular", "", 1, 20));
export const MailDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("MailDismiss20Filled", "", 0, 20));
export const MailDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("MailDismiss24Regular", "", 1, 24));
export const MailDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("MailDismiss24Filled", "", 0, 24));
export const MailDismiss28Regular = ( /*#__PURE__*/createFluentFontIcon("MailDismiss28Regular", "", 1, 28));
export const MailDismiss28Filled = ( /*#__PURE__*/createFluentFontIcon("MailDismiss28Filled", "", 0, 28));
