"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MailClockFilled = ( /*#__PURE__*/createFluentFontIcon("MailClockFilled", "", 2, undefined));
export const MailClockRegular = ( /*#__PURE__*/createFluentFontIcon("MailClockRegular", "", 2, undefined));
export const MailClock16Regular = ( /*#__PURE__*/createFluentFontIcon("MailClock16Regular", "", 1, 16));
export const MailClock16Filled = ( /*#__PURE__*/createFluentFontIcon("MailClock16Filled", "", 0, 16));
export const MailClock20Regular = ( /*#__PURE__*/createFluentFontIcon("MailClock20Regular", "", 1, 20));
export const MailClock20Filled = ( /*#__PURE__*/createFluentFontIcon("MailClock20Filled", "", 0, 20));
export const MailClock24Regular = ( /*#__PURE__*/createFluentFontIcon("MailClock24Regular", "", 1, 24));
export const MailClock24Filled = ( /*#__PURE__*/createFluentFontIcon("MailClock24Filled", "", 0, 24));
export const MailClock32Regular = ( /*#__PURE__*/createFluentFontIcon("MailClock32Regular", "󰡪", 1, 32));
export const MailClock32Filled = ( /*#__PURE__*/createFluentFontIcon("MailClock32Filled", "󰣧", 0, 32));
