"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MailWarningFilled = ( /*#__PURE__*/createFluentFontIcon("MailWarningFilled", "", 2, undefined));
export const MailWarningRegular = ( /*#__PURE__*/createFluentFontIcon("MailWarningRegular", "", 2, undefined));
export const MailWarning16Regular = ( /*#__PURE__*/createFluentFontIcon("MailWarning16Regular", "", 1, 16));
export const MailWarning16Filled = ( /*#__PURE__*/createFluentFontIcon("MailWarning16Filled", "", 0, 16));
export const MailWarning20Regular = ( /*#__PURE__*/createFluentFontIcon("MailWarning20Regular", "", 1, 20));
export const MailWarning20Filled = ( /*#__PURE__*/createFluentFontIcon("MailWarning20Filled", "", 0, 20));
export const MailWarning24Regular = ( /*#__PURE__*/createFluentFontIcon("MailWarning24Regular", "", 1, 24));
export const MailWarning24Filled = ( /*#__PURE__*/createFluentFontIcon("MailWarning24Filled", "", 0, 24));
export const MailWarning28Regular = ( /*#__PURE__*/createFluentFontIcon("MailWarning28Regular", "󰪝", 1, 28));
export const MailWarning28Filled = ( /*#__PURE__*/createFluentFontIcon("MailWarning28Filled", "󰬙", 0, 28));
export const MailWarning32Regular = ( /*#__PURE__*/createFluentFontIcon("MailWarning32Regular", "󰪞", 1, 32));
export const MailWarning32Filled = ( /*#__PURE__*/createFluentFontIcon("MailWarning32Filled", "󰬚", 0, 32));
export const MailWarning32Light = ( /*#__PURE__*/createFluentFontIcon("MailWarning32Light", "", 3, 32));
