"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MathSymbolsFilled = ( /*#__PURE__*/createFluentFontIcon("MathSymbolsFilled", "", 2, undefined));
export const MathSymbolsRegular = ( /*#__PURE__*/createFluentFontIcon("MathSymbolsRegular", "", 2, undefined));
export const MathSymbols16Regular = ( /*#__PURE__*/createFluentFontIcon("MathSymbols16Regular", "", 1, 16));
export const MathSymbols16Filled = ( /*#__PURE__*/createFluentFontIcon("MathSymbols16Filled", "", 0, 16));
export const MathSymbols20Regular = ( /*#__PURE__*/createFluentFontIcon("MathSymbols20Regular", "", 1, 20));
export const MathSymbols20Filled = ( /*#__PURE__*/createFluentFontIcon("MathSymbols20Filled", "", 0, 20));
export const MathSymbols24Regular = ( /*#__PURE__*/createFluentFontIcon("MathSymbols24Regular", "", 1, 24));
export const MathSymbols24Filled = ( /*#__PURE__*/createFluentFontIcon("MathSymbols24Filled", "", 0, 24));
export const MathSymbols28Regular = ( /*#__PURE__*/createFluentFontIcon("MathSymbols28Regular", "", 1, 28));
export const MathSymbols28Filled = ( /*#__PURE__*/createFluentFontIcon("MathSymbols28Filled", "", 0, 28));
export const MathSymbols32Regular = ( /*#__PURE__*/createFluentFontIcon("MathSymbols32Regular", "", 1, 32));
export const MathSymbols32Filled = ( /*#__PURE__*/createFluentFontIcon("MathSymbols32Filled", "", 0, 32));
export const MathSymbols48Regular = ( /*#__PURE__*/createFluentFontIcon("MathSymbols48Regular", "", 1, 48));
export const MathSymbols48Filled = ( /*#__PURE__*/createFluentFontIcon("MathSymbols48Filled", "", 0, 48));
