"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MegaphoneOffFilled = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOffFilled", "", 2, undefined));
export const MegaphoneOffRegular = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOffRegular", "", 2, undefined));
export const MegaphoneOff16Regular = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff16Regular", "", 1, 16));
export const MegaphoneOff16Filled = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff16Filled", "", 0, 16));
export const MegaphoneOff20Regular = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff20Regular", "", 1, 20));
export const MegaphoneOff20Filled = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff20Filled", "", 0, 20));
export const MegaphoneOff24Regular = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff24Regular", "", 1, 24));
export const MegaphoneOff24Filled = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff24Filled", "", 0, 24));
export const MegaphoneOff28Regular = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff28Regular", "", 1, 28));
export const MegaphoneOff28Filled = ( /*#__PURE__*/createFluentFontIcon("MegaphoneOff28Filled", "", 0, 28));
