"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MergeFilled = ( /*#__PURE__*/createFluentFontIcon("MergeFilled", "", 2, undefined));
export const MergeRegular = ( /*#__PURE__*/createFluentFontIcon("MergeRegular", "", 2, undefined));
export const Merge16Regular = ( /*#__PURE__*/createFluentFontIcon("Merge16Regular", "", 1, 16));
export const Merge16Filled = ( /*#__PURE__*/createFluentFontIcon("Merge16Filled", "", 0, 16));
export const Merge20Regular = ( /*#__PURE__*/createFluentFontIcon("Merge20Regular", "", 1, 20));
export const Merge20Filled = ( /*#__PURE__*/createFluentFontIcon("Merge20Filled", "", 0, 20));
export const Merge24Regular = ( /*#__PURE__*/createFluentFontIcon("Merge24Regular", "", 1, 24));
export const Merge24Filled = ( /*#__PURE__*/createFluentFontIcon("Merge24Filled", "", 0, 24));
