"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MicSyncFilled = ( /*#__PURE__*/createFluentFontIcon("MicSyncFilled", "", 2, undefined));
export const MicSyncRegular = ( /*#__PURE__*/createFluentFontIcon("MicSyncRegular", "", 2, undefined));
export const MicSync16Regular = ( /*#__PURE__*/createFluentFontIcon("MicSync16Regular", "󰨬", 1, 16));
export const MicSync16Filled = ( /*#__PURE__*/createFluentFontIcon("MicSync16Filled", "󰪨", 0, 16));
export const MicSync20Regular = ( /*#__PURE__*/createFluentFontIcon("MicSync20Regular", "", 1, 20));
export const MicSync20Filled = ( /*#__PURE__*/createFluentFontIcon("MicSync20Filled", "", 0, 20));
export const MicSync24Regular = ( /*#__PURE__*/createFluentFontIcon("MicSync24Regular", "󰨭", 1, 24));
export const MicSync24Filled = ( /*#__PURE__*/createFluentFontIcon("MicSync24Filled", "󰪩", 0, 24));
export const MicSync28Regular = ( /*#__PURE__*/createFluentFontIcon("MicSync28Regular", "󰨮", 1, 28));
export const MicSync28Filled = ( /*#__PURE__*/createFluentFontIcon("MicSync28Filled", "󰪪", 0, 28));
export const MicSync32Regular = ( /*#__PURE__*/createFluentFontIcon("MicSync32Regular", "󰨯", 1, 32));
export const MicSync32Filled = ( /*#__PURE__*/createFluentFontIcon("MicSync32Filled", "󰪫", 0, 32));
export const MicSync48Regular = ( /*#__PURE__*/createFluentFontIcon("MicSync48Regular", "󰨰", 1, 48));
export const MicSync48Filled = ( /*#__PURE__*/createFluentFontIcon("MicSync48Filled", "󰪬", 0, 48));
