"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MicLinkFilled = ( /*#__PURE__*/createFluentFontIcon("MicLinkFilled", "", 2, undefined));
export const MicLinkRegular = ( /*#__PURE__*/createFluentFontIcon("MicLinkRegular", "", 2, undefined));
export const MicLink16Regular = ( /*#__PURE__*/createFluentFontIcon("MicLink16Regular", "󰛼", 1, 16));
export const MicLink16Filled = ( /*#__PURE__*/createFluentFontIcon("MicLink16Filled", "󰝹", 0, 16));
export const MicLink20Regular = ( /*#__PURE__*/createFluentFontIcon("MicLink20Regular", "󰛽", 1, 20));
export const MicLink20Filled = ( /*#__PURE__*/createFluentFontIcon("MicLink20Filled", "󰝺", 0, 20));
export const MicLink24Regular = ( /*#__PURE__*/createFluentFontIcon("MicLink24Regular", "󰛾", 1, 24));
export const MicLink24Filled = ( /*#__PURE__*/createFluentFontIcon("MicLink24Filled", "󰝻", 0, 24));
export const MicLink28Regular = ( /*#__PURE__*/createFluentFontIcon("MicLink28Regular", "󰛿", 1, 28));
export const MicLink28Filled = ( /*#__PURE__*/createFluentFontIcon("MicLink28Filled", "󰝼", 0, 28));
export const MicLink32Regular = ( /*#__PURE__*/createFluentFontIcon("MicLink32Regular", "󰜀", 1, 32));
export const MicLink32Filled = ( /*#__PURE__*/createFluentFontIcon("MicLink32Filled", "󰝽", 0, 32));
export const MicLink48Regular = ( /*#__PURE__*/createFluentFontIcon("MicLink48Regular", "󰜁", 1, 48));
export const MicLink48Filled = ( /*#__PURE__*/createFluentFontIcon("MicLink48Filled", "󰝾", 0, 48));
