"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MicOffFilled = ( /*#__PURE__*/createFluentFontIcon("MicOffFilled", "", 2, undefined));
export const MicOffRegular = ( /*#__PURE__*/createFluentFontIcon("MicOffRegular", "", 2, undefined));
export const MicOff12Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff12Regular", "", 1, 12));
export const MicOff12Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff12Filled", "", 0, 12));
export const MicOff16Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff16Regular", "", 1, 16));
export const MicOff16Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff16Filled", "", 0, 16));
export const MicOff20Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff20Regular", "", 1, 20));
export const MicOff20Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff20Filled", "", 0, 20));
export const MicOff24Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff24Regular", "", 1, 24));
export const MicOff24Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff24Filled", "", 0, 24));
export const MicOff28Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff28Regular", "", 1, 28));
export const MicOff28Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff28Filled", "", 0, 28));
export const MicOff32Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff32Regular", "", 1, 32));
export const MicOff32Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff32Filled", "", 0, 32));
export const MicOff48Regular = ( /*#__PURE__*/createFluentFontIcon("MicOff48Regular", "", 1, 48));
export const MicOff48Filled = ( /*#__PURE__*/createFluentFontIcon("MicOff48Filled", "", 0, 48));
