"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MicFilled = ( /*#__PURE__*/createFluentFontIcon("MicFilled", "", 2, undefined));
export const MicRegular = ( /*#__PURE__*/createFluentFontIcon("MicRegular", "", 2, undefined));
export const Mic16Regular = ( /*#__PURE__*/createFluentFontIcon("Mic16Regular", "", 1, 16));
export const Mic16Filled = ( /*#__PURE__*/createFluentFontIcon("Mic16Filled", "", 0, 16));
export const Mic20Regular = ( /*#__PURE__*/createFluentFontIcon("Mic20Regular", "", 1, 20));
export const Mic20Filled = ( /*#__PURE__*/createFluentFontIcon("Mic20Filled", "", 0, 20));
export const Mic24Regular = ( /*#__PURE__*/createFluentFontIcon("Mic24Regular", "", 1, 24));
export const Mic24Filled = ( /*#__PURE__*/createFluentFontIcon("Mic24Filled", "", 0, 24));
export const Mic28Regular = ( /*#__PURE__*/createFluentFontIcon("Mic28Regular", "", 1, 28));
export const Mic28Filled = ( /*#__PURE__*/createFluentFontIcon("Mic28Filled", "", 0, 28));
export const Mic32Regular = ( /*#__PURE__*/createFluentFontIcon("Mic32Regular", "", 1, 32));
export const Mic32Filled = ( /*#__PURE__*/createFluentFontIcon("Mic32Filled", "", 0, 32));
export const Mic32Light = ( /*#__PURE__*/createFluentFontIcon("Mic32Light", "", 3, 32));
export const Mic48Regular = ( /*#__PURE__*/createFluentFontIcon("Mic48Regular", "", 1, 48));
export const Mic48Filled = ( /*#__PURE__*/createFluentFontIcon("Mic48Filled", "", 0, 48));
