"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MoleculeFilled = ( /*#__PURE__*/createFluentFontIcon("MoleculeFilled", "", 2, undefined));
export const MoleculeRegular = ( /*#__PURE__*/createFluentFontIcon("MoleculeRegular", "", 2, undefined));
export const Molecule16Regular = ( /*#__PURE__*/createFluentFontIcon("Molecule16Regular", "", 1, 16));
export const Molecule16Filled = ( /*#__PURE__*/createFluentFontIcon("Molecule16Filled", "", 0, 16));
export const Molecule20Regular = ( /*#__PURE__*/createFluentFontIcon("Molecule20Regular", "", 1, 20));
export const Molecule20Filled = ( /*#__PURE__*/createFluentFontIcon("Molecule20Filled", "", 0, 20));
export const Molecule24Regular = ( /*#__PURE__*/createFluentFontIcon("Molecule24Regular", "", 1, 24));
export const Molecule24Filled = ( /*#__PURE__*/createFluentFontIcon("Molecule24Filled", "", 0, 24));
export const Molecule28Regular = ( /*#__PURE__*/createFluentFontIcon("Molecule28Regular", "", 1, 28));
export const Molecule28Filled = ( /*#__PURE__*/createFluentFontIcon("Molecule28Filled", "", 0, 28));
export const Molecule32Regular = ( /*#__PURE__*/createFluentFontIcon("Molecule32Regular", "", 1, 32));
export const Molecule32Filled = ( /*#__PURE__*/createFluentFontIcon("Molecule32Filled", "", 0, 32));
export const Molecule32Light = ( /*#__PURE__*/createFluentFontIcon("Molecule32Light", "", 3, 32));
export const Molecule48Regular = ( /*#__PURE__*/createFluentFontIcon("Molecule48Regular", "", 1, 48));
export const Molecule48Filled = ( /*#__PURE__*/createFluentFontIcon("Molecule48Filled", "", 0, 48));
