"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MoneyFilled = ( /*#__PURE__*/createFluentFontIcon("MoneyFilled", "", 2, undefined));
export const MoneyRegular = ( /*#__PURE__*/createFluentFontIcon("MoneyRegular", "", 2, undefined));
export const Money16Regular = ( /*#__PURE__*/createFluentFontIcon("Money16Regular", "", 1, 16));
export const Money16Filled = ( /*#__PURE__*/createFluentFontIcon("Money16Filled", "", 0, 16));
export const Money20Regular = ( /*#__PURE__*/createFluentFontIcon("Money20Regular", "", 1, 20));
export const Money20Filled = ( /*#__PURE__*/createFluentFontIcon("Money20Filled", "", 0, 20));
export const Money24Regular = ( /*#__PURE__*/createFluentFontIcon("Money24Regular", "", 1, 24));
export const Money24Filled = ( /*#__PURE__*/createFluentFontIcon("Money24Filled", "", 0, 24));
