"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MountainTrailFilled = ( /*#__PURE__*/createFluentFontIcon("MountainTrailFilled", "", 2, undefined));
export const MountainTrailRegular = ( /*#__PURE__*/createFluentFontIcon("MountainTrailRegular", "", 2, undefined));
export const MountainTrail20Regular = ( /*#__PURE__*/createFluentFontIcon("MountainTrail20Regular", "󰃨", 1, 20));
export const MountainTrail20Filled = ( /*#__PURE__*/createFluentFontIcon("MountainTrail20Filled", "󰃧", 0, 20));
export const MountainTrail24Regular = ( /*#__PURE__*/createFluentFontIcon("MountainTrail24Regular", "󰃩", 1, 24));
export const MountainTrail24Filled = ( /*#__PURE__*/createFluentFontIcon("MountainTrail24Filled", "󰃨", 0, 24));
export const MountainTrail28Regular = ( /*#__PURE__*/createFluentFontIcon("MountainTrail28Regular", "󰃪", 1, 28));
export const MountainTrail28Filled = ( /*#__PURE__*/createFluentFontIcon("MountainTrail28Filled", "󰃩", 0, 28));
