"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MultiselectLtrFilled = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtrFilled", "", 2, undefined));
export const MultiselectLtrRegular = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtrRegular", "", 2, undefined));
export const MultiselectLtr16Regular = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtr16Regular", "", 1, 16));
export const MultiselectLtr16Filled = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtr16Filled", "", 0, 16));
export const MultiselectLtr20Regular = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtr20Regular", "", 1, 20));
export const MultiselectLtr20Filled = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtr20Filled", "", 0, 20));
export const MultiselectLtr24Regular = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtr24Regular", "", 1, 24));
export const MultiselectLtr24Filled = ( /*#__PURE__*/createFluentFontIcon("MultiselectLtr24Filled", "", 0, 24));
