"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const Multiplier12XFilled = ( /*#__PURE__*/createFluentFontIcon("Multiplier12XFilled", "", 2, undefined));
export const Multiplier12XRegular = ( /*#__PURE__*/createFluentFontIcon("Multiplier12XRegular", "", 2, undefined));
export const Multiplier12X20Regular = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X20Regular", "", 1, 20));
export const Multiplier12X20Filled = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X20Filled", "", 0, 20));
export const Multiplier12X24Regular = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X24Regular", "", 1, 24));
export const Multiplier12X24Filled = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X24Filled", "", 0, 24));
export const Multiplier12X28Regular = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X28Regular", "", 1, 28));
export const Multiplier12X28Filled = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X28Filled", "", 0, 28));
export const Multiplier12X32Regular = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X32Regular", "", 1, 32));
export const Multiplier12X32Filled = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X32Filled", "", 0, 32));
export const Multiplier12X48Regular = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X48Regular", "", 1, 48));
export const Multiplier12X48Filled = ( /*#__PURE__*/createFluentFontIcon("Multiplier12X48Filled", "", 0, 48));
