"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MultiselectRtlFilled = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtlFilled", "", 2, undefined));
export const MultiselectRtlRegular = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtlRegular", "", 2, undefined));
export const MultiselectRtl16Regular = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtl16Regular", "", 1, 16));
export const MultiselectRtl16Filled = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtl16Filled", "", 0, 16));
export const MultiselectRtl20Regular = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtl20Regular", "", 1, 20));
export const MultiselectRtl20Filled = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtl20Filled", "", 0, 20));
export const MultiselectRtl24Regular = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtl24Regular", "", 1, 24));
export const MultiselectRtl24Filled = ( /*#__PURE__*/createFluentFontIcon("MultiselectRtl24Filled", "", 0, 24));
