"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const MusicNote1Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote1Regular", "", 2, undefined));
export const MusicNote1Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote1Filled", "", 2, undefined));
export const MusicNote2Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote2Regular", "", 2, undefined));
export const MusicNote2Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote2Filled", "", 2, undefined));
export const MusicNote120Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote120Regular", "", 1, 20));
export const MusicNote120Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote120Filled", "", 0, 20));
export const MusicNote124Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote124Regular", "", 1, 24));
export const MusicNote124Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote124Filled", "", 0, 24));
export const MusicNote216Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote216Regular", "", 1, 16));
export const MusicNote216Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote216Filled", "", 0, 16));
export const MusicNote220Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote220Regular", "", 1, 20));
export const MusicNote220Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote220Filled", "", 0, 20));
export const MusicNote224Regular = ( /*#__PURE__*/createFluentFontIcon("MusicNote224Regular", "", 1, 24));
export const MusicNote224Filled = ( /*#__PURE__*/createFluentFontIcon("MusicNote224Filled", "", 0, 24));
