"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const NavigationFilled = ( /*#__PURE__*/createFluentFontIcon("NavigationFilled", "", 2, undefined));
export const NavigationRegular = ( /*#__PURE__*/createFluentFontIcon("NavigationRegular", "", 2, undefined));
export const Navigation16Regular = ( /*#__PURE__*/createFluentFontIcon("Navigation16Regular", "", 1, 16));
export const Navigation16Filled = ( /*#__PURE__*/createFluentFontIcon("Navigation16Filled", "", 0, 16));
export const Navigation20Regular = ( /*#__PURE__*/createFluentFontIcon("Navigation20Regular", "", 1, 20));
export const Navigation20Filled = ( /*#__PURE__*/createFluentFontIcon("Navigation20Filled", "", 0, 20));
export const Navigation24Regular = ( /*#__PURE__*/createFluentFontIcon("Navigation24Regular", "", 1, 24));
export const Navigation24Filled = ( /*#__PURE__*/createFluentFontIcon("Navigation24Filled", "", 0, 24));
export const Navigation28Regular = ( /*#__PURE__*/createFluentFontIcon("Navigation28Regular", "󰝩", 1, 28));
export const Navigation28Filled = ( /*#__PURE__*/createFluentFontIcon("Navigation28Filled", "󰟦", 0, 28));
export const Navigation32Regular = ( /*#__PURE__*/createFluentFontIcon("Navigation32Regular", "󰝪", 1, 32));
export const Navigation32Filled = ( /*#__PURE__*/createFluentFontIcon("Navigation32Filled", "󰟧", 0, 32));
export const Navigation48Regular = ( /*#__PURE__*/createFluentFontIcon("Navigation48Regular", "󰝫", 1, 48));
export const Navigation48Filled = ( /*#__PURE__*/createFluentFontIcon("Navigation48Filled", "󰟨", 0, 48));
