"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const NewsFilled = ( /*#__PURE__*/createFluentFontIcon("NewsFilled", "", 2, undefined));
export const NewsRegular = ( /*#__PURE__*/createFluentFontIcon("NewsRegular", "", 2, undefined));
export const News16Regular = ( /*#__PURE__*/createFluentFontIcon("News16Regular", "", 1, 16));
export const News16Filled = ( /*#__PURE__*/createFluentFontIcon("News16Filled", "", 0, 16));
export const News20Regular = ( /*#__PURE__*/createFluentFontIcon("News20Regular", "", 1, 20));
export const News20Filled = ( /*#__PURE__*/createFluentFontIcon("News20Filled", "", 0, 20));
export const News24Regular = ( /*#__PURE__*/createFluentFontIcon("News24Regular", "", 1, 24));
export const News24Filled = ( /*#__PURE__*/createFluentFontIcon("News24Filled", "", 0, 24));
export const News28Regular = ( /*#__PURE__*/createFluentFontIcon("News28Regular", "", 1, 28));
export const News28Filled = ( /*#__PURE__*/createFluentFontIcon("News28Filled", "", 0, 28));
