"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const NextFilled = ( /*#__PURE__*/createFluentFontIcon("NextFilled", "", 2, undefined));
export const NextRegular = ( /*#__PURE__*/createFluentFontIcon("NextRegular", "", 2, undefined));
export const Next16Regular = ( /*#__PURE__*/createFluentFontIcon("Next16Regular", "", 1, 16));
export const Next16Filled = ( /*#__PURE__*/createFluentFontIcon("Next16Filled", "", 0, 16));
export const Next20Regular = ( /*#__PURE__*/createFluentFontIcon("Next20Regular", "", 1, 20));
export const Next20Filled = ( /*#__PURE__*/createFluentFontIcon("Next20Filled", "", 0, 20));
export const Next24Regular = ( /*#__PURE__*/createFluentFontIcon("Next24Regular", "", 1, 24));
export const Next24Filled = ( /*#__PURE__*/createFluentFontIcon("Next24Filled", "", 0, 24));
export const Next28Regular = ( /*#__PURE__*/createFluentFontIcon("Next28Regular", "", 1, 28));
export const Next28Filled = ( /*#__PURE__*/createFluentFontIcon("Next28Filled", "", 0, 28));
export const Next32Regular = ( /*#__PURE__*/createFluentFontIcon("Next32Regular", "", 1, 32));
export const Next32Filled = ( /*#__PURE__*/createFluentFontIcon("Next32Filled", "", 0, 32));
export const Next48Regular = ( /*#__PURE__*/createFluentFontIcon("Next48Regular", "", 1, 48));
export const Next48Filled = ( /*#__PURE__*/createFluentFontIcon("Next48Filled", "", 0, 48));
