"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const OpenFilled = ( /*#__PURE__*/createFluentFontIcon("OpenFilled", "", 2, undefined));
export const OpenRegular = ( /*#__PURE__*/createFluentFontIcon("OpenRegular", "", 2, undefined));
export const Open12Regular = ( /*#__PURE__*/createFluentFontIcon("Open12Regular", "󰋅", 1, 12));
export const Open12Filled = ( /*#__PURE__*/createFluentFontIcon("Open12Filled", "󰋘", 0, 12));
export const Open16Regular = ( /*#__PURE__*/createFluentFontIcon("Open16Regular", "", 1, 16));
export const Open16Filled = ( /*#__PURE__*/createFluentFontIcon("Open16Filled", "", 0, 16));
export const Open20Regular = ( /*#__PURE__*/createFluentFontIcon("Open20Regular", "", 1, 20));
export const Open20Filled = ( /*#__PURE__*/createFluentFontIcon("Open20Filled", "", 0, 20));
export const Open24Regular = ( /*#__PURE__*/createFluentFontIcon("Open24Regular", "", 1, 24));
export const Open24Filled = ( /*#__PURE__*/createFluentFontIcon("Open24Filled", "", 0, 24));
export const Open28Regular = ( /*#__PURE__*/createFluentFontIcon("Open28Regular", "", 1, 28));
export const Open28Filled = ( /*#__PURE__*/createFluentFontIcon("Open28Filled", "", 0, 28));
export const Open32Regular = ( /*#__PURE__*/createFluentFontIcon("Open32Regular", "", 1, 32));
export const Open32Filled = ( /*#__PURE__*/createFluentFontIcon("Open32Filled", "", 0, 32));
export const Open48Regular = ( /*#__PURE__*/createFluentFontIcon("Open48Regular", "", 1, 48));
export const Open48Filled = ( /*#__PURE__*/createFluentFontIcon("Open48Filled", "", 0, 48));
