"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const OvalFilled = ( /*#__PURE__*/createFluentFontIcon("OvalFilled", "", 2, undefined));
export const OvalRegular = ( /*#__PURE__*/createFluentFontIcon("OvalRegular", "", 2, undefined));
export const Oval16Regular = ( /*#__PURE__*/createFluentFontIcon("Oval16Regular", "", 1, 16));
export const Oval16Filled = ( /*#__PURE__*/createFluentFontIcon("Oval16Filled", "", 0, 16));
export const Oval20Regular = ( /*#__PURE__*/createFluentFontIcon("Oval20Regular", "", 1, 20));
export const Oval20Filled = ( /*#__PURE__*/createFluentFontIcon("Oval20Filled", "", 0, 20));
export const Oval24Regular = ( /*#__PURE__*/createFluentFontIcon("Oval24Regular", "", 1, 24));
export const Oval24Filled = ( /*#__PURE__*/createFluentFontIcon("Oval24Filled", "", 0, 24));
export const Oval28Regular = ( /*#__PURE__*/createFluentFontIcon("Oval28Regular", "", 1, 28));
export const Oval28Filled = ( /*#__PURE__*/createFluentFontIcon("Oval28Filled", "", 0, 28));
export const Oval32Regular = ( /*#__PURE__*/createFluentFontIcon("Oval32Regular", "", 1, 32));
export const Oval32Filled = ( /*#__PURE__*/createFluentFontIcon("Oval32Filled", "", 0, 32));
export const Oval48Regular = ( /*#__PURE__*/createFluentFontIcon("Oval48Regular", "", 1, 48));
export const Oval48Filled = ( /*#__PURE__*/createFluentFontIcon("Oval48Filled", "", 0, 48));
