"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PageFitFilled = ( /*#__PURE__*/createFluentFontIcon("PageFitFilled", "", 2, undefined));
export const PageFitRegular = ( /*#__PURE__*/createFluentFontIcon("PageFitRegular", "", 2, undefined));
export const PageFit16Regular = ( /*#__PURE__*/createFluentFontIcon("PageFit16Regular", "", 1, 16));
export const PageFit16Filled = ( /*#__PURE__*/createFluentFontIcon("PageFit16Filled", "", 0, 16));
export const PageFit20Regular = ( /*#__PURE__*/createFluentFontIcon("PageFit20Regular", "", 1, 20));
export const PageFit20Filled = ( /*#__PURE__*/createFluentFontIcon("PageFit20Filled", "", 0, 20));
export const PageFit24Regular = ( /*#__PURE__*/createFluentFontIcon("PageFit24Regular", "", 1, 24));
export const PageFit24Filled = ( /*#__PURE__*/createFluentFontIcon("PageFit24Filled", "", 0, 24));
