"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PatientFilled = ( /*#__PURE__*/createFluentFontIcon("PatientFilled", "", 2, undefined));
export const PatientRegular = ( /*#__PURE__*/createFluentFontIcon("PatientRegular", "", 2, undefined));
export const Patient20Regular = ( /*#__PURE__*/createFluentFontIcon("Patient20Regular", "", 1, 20));
export const Patient20Filled = ( /*#__PURE__*/createFluentFontIcon("Patient20Filled", "", 0, 20));
export const Patient24Regular = ( /*#__PURE__*/createFluentFontIcon("Patient24Regular", "", 1, 24));
export const Patient24Filled = ( /*#__PURE__*/createFluentFontIcon("Patient24Filled", "", 0, 24));
export const Patient32Regular = ( /*#__PURE__*/createFluentFontIcon("Patient32Regular", "", 1, 32));
export const Patient32Filled = ( /*#__PURE__*/createFluentFontIcon("Patient32Filled", "", 0, 32));
