"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PauseFilled = ( /*#__PURE__*/createFluentFontIcon("PauseFilled", "", 2, undefined));
export const PauseRegular = ( /*#__PURE__*/createFluentFontIcon("PauseRegular", "", 2, undefined));
export const Pause12Regular = ( /*#__PURE__*/createFluentFontIcon("Pause12Regular", "", 1, 12));
export const Pause12Filled = ( /*#__PURE__*/createFluentFontIcon("Pause12Filled", "", 0, 12));
export const Pause16Regular = ( /*#__PURE__*/createFluentFontIcon("Pause16Regular", "", 1, 16));
export const Pause16Filled = ( /*#__PURE__*/createFluentFontIcon("Pause16Filled", "", 0, 16));
export const Pause20Regular = ( /*#__PURE__*/createFluentFontIcon("Pause20Regular", "", 1, 20));
export const Pause20Filled = ( /*#__PURE__*/createFluentFontIcon("Pause20Filled", "", 0, 20));
export const Pause24Regular = ( /*#__PURE__*/createFluentFontIcon("Pause24Regular", "", 1, 24));
export const Pause24Filled = ( /*#__PURE__*/createFluentFontIcon("Pause24Filled", "", 0, 24));
export const Pause28Regular = ( /*#__PURE__*/createFluentFontIcon("Pause28Regular", "", 1, 28));
export const Pause28Filled = ( /*#__PURE__*/createFluentFontIcon("Pause28Filled", "", 0, 28));
export const Pause32Regular = ( /*#__PURE__*/createFluentFontIcon("Pause32Regular", "", 1, 32));
export const Pause32Filled = ( /*#__PURE__*/createFluentFontIcon("Pause32Filled", "", 0, 32));
export const Pause48Regular = ( /*#__PURE__*/createFluentFontIcon("Pause48Regular", "", 1, 48));
export const Pause48Filled = ( /*#__PURE__*/createFluentFontIcon("Pause48Filled", "", 0, 48));
