"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PauseCircleFilled = ( /*#__PURE__*/createFluentFontIcon("PauseCircleFilled", "", 2, undefined));
export const PauseCircleRegular = ( /*#__PURE__*/createFluentFontIcon("PauseCircleRegular", "", 2, undefined));
export const PauseCircle12Regular = ( /*#__PURE__*/createFluentFontIcon("PauseCircle12Regular", "󰦙", 1, 12));
export const PauseCircle12Filled = ( /*#__PURE__*/createFluentFontIcon("PauseCircle12Filled", "󰨖", 0, 12));
export const PauseCircle16Regular = ( /*#__PURE__*/createFluentFontIcon("PauseCircle16Regular", "󰝬", 1, 16));
export const PauseCircle16Filled = ( /*#__PURE__*/createFluentFontIcon("PauseCircle16Filled", "󰟩", 0, 16));
export const PauseCircle20Regular = ( /*#__PURE__*/createFluentFontIcon("PauseCircle20Regular", "", 1, 20));
export const PauseCircle20Filled = ( /*#__PURE__*/createFluentFontIcon("PauseCircle20Filled", "", 0, 20));
export const PauseCircle24Regular = ( /*#__PURE__*/createFluentFontIcon("PauseCircle24Regular", "", 1, 24));
export const PauseCircle24Filled = ( /*#__PURE__*/createFluentFontIcon("PauseCircle24Filled", "", 0, 24));
export const PauseCircle32Regular = ( /*#__PURE__*/createFluentFontIcon("PauseCircle32Regular", "󰈥", 1, 32));
export const PauseCircle32Filled = ( /*#__PURE__*/createFluentFontIcon("PauseCircle32Filled", "󰈸", 0, 32));
export const PauseCircle48Regular = ( /*#__PURE__*/createFluentFontIcon("PauseCircle48Regular", "󰈦", 1, 48));
export const PauseCircle48Filled = ( /*#__PURE__*/createFluentFontIcon("PauseCircle48Filled", "󰈹", 0, 48));
