"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PaymentFilled = ( /*#__PURE__*/createFluentFontIcon("PaymentFilled", "", 2, undefined));
export const PaymentRegular = ( /*#__PURE__*/createFluentFontIcon("PaymentRegular", "", 2, undefined));
export const Payment16Regular = ( /*#__PURE__*/createFluentFontIcon("Payment16Regular", "", 1, 16));
export const Payment16Filled = ( /*#__PURE__*/createFluentFontIcon("Payment16Filled", "", 0, 16));
export const Payment20Regular = ( /*#__PURE__*/createFluentFontIcon("Payment20Regular", "", 1, 20));
export const Payment20Filled = ( /*#__PURE__*/createFluentFontIcon("Payment20Filled", "", 0, 20));
export const Payment24Regular = ( /*#__PURE__*/createFluentFontIcon("Payment24Regular", "", 1, 24));
export const Payment24Filled = ( /*#__PURE__*/createFluentFontIcon("Payment24Filled", "", 0, 24));
export const Payment28Regular = ( /*#__PURE__*/createFluentFontIcon("Payment28Regular", "", 1, 28));
export const Payment28Filled = ( /*#__PURE__*/createFluentFontIcon("Payment28Filled", "", 0, 28));
export const Payment32Regular = ( /*#__PURE__*/createFluentFontIcon("Payment32Regular", "", 1, 32));
export const Payment32Filled = ( /*#__PURE__*/createFluentFontIcon("Payment32Filled", "", 0, 32));
export const Payment48Regular = ( /*#__PURE__*/createFluentFontIcon("Payment48Regular", "", 1, 48));
export const Payment48Filled = ( /*#__PURE__*/createFluentFontIcon("Payment48Filled", "", 0, 48));
