"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PenDismissFilled = ( /*#__PURE__*/createFluentFontIcon("PenDismissFilled", "", 2, undefined));
export const PenDismissRegular = ( /*#__PURE__*/createFluentFontIcon("PenDismissRegular", "", 2, undefined));
export const PenDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("PenDismiss16Regular", "󰃫", 1, 16));
export const PenDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("PenDismiss16Filled", "󰃪", 0, 16));
export const PenDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("PenDismiss20Regular", "󰃬", 1, 20));
export const PenDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("PenDismiss20Filled", "󰃫", 0, 20));
export const PenDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("PenDismiss24Regular", "󰃭", 1, 24));
export const PenDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("PenDismiss24Filled", "󰃬", 0, 24));
export const PenDismiss28Regular = ( /*#__PURE__*/createFluentFontIcon("PenDismiss28Regular", "󰃮", 1, 28));
export const PenDismiss28Filled = ( /*#__PURE__*/createFluentFontIcon("PenDismiss28Filled", "󰃭", 0, 28));
export const PenDismiss32Regular = ( /*#__PURE__*/createFluentFontIcon("PenDismiss32Regular", "󰃯", 1, 32));
export const PenDismiss32Filled = ( /*#__PURE__*/createFluentFontIcon("PenDismiss32Filled", "󰃮", 0, 32));
export const PenDismiss48Regular = ( /*#__PURE__*/createFluentFontIcon("PenDismiss48Regular", "󰃰", 1, 48));
export const PenDismiss48Filled = ( /*#__PURE__*/createFluentFontIcon("PenDismiss48Filled", "󰃯", 0, 48));
