"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PenFilled = ( /*#__PURE__*/createFluentFontIcon("PenFilled", "", 2, undefined));
export const PenRegular = ( /*#__PURE__*/createFluentFontIcon("PenRegular", "", 2, undefined));
export const Pen16Regular = ( /*#__PURE__*/createFluentFontIcon("Pen16Regular", "", 1, 16));
export const Pen16Filled = ( /*#__PURE__*/createFluentFontIcon("Pen16Filled", "", 0, 16));
export const Pen20Regular = ( /*#__PURE__*/createFluentFontIcon("Pen20Regular", "", 1, 20));
export const Pen20Filled = ( /*#__PURE__*/createFluentFontIcon("Pen20Filled", "", 0, 20));
export const Pen24Regular = ( /*#__PURE__*/createFluentFontIcon("Pen24Regular", "", 1, 24));
export const Pen24Filled = ( /*#__PURE__*/createFluentFontIcon("Pen24Filled", "", 0, 24));
export const Pen28Regular = ( /*#__PURE__*/createFluentFontIcon("Pen28Regular", "", 1, 28));
export const Pen28Filled = ( /*#__PURE__*/createFluentFontIcon("Pen28Filled", "", 0, 28));
export const Pen32Regular = ( /*#__PURE__*/createFluentFontIcon("Pen32Regular", "", 1, 32));
export const Pen32Filled = ( /*#__PURE__*/createFluentFontIcon("Pen32Filled", "", 0, 32));
export const Pen48Regular = ( /*#__PURE__*/createFluentFontIcon("Pen48Regular", "", 1, 48));
export const Pen48Filled = ( /*#__PURE__*/createFluentFontIcon("Pen48Filled", "", 0, 48));
