"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PentagonFilled = ( /*#__PURE__*/createFluentFontIcon("PentagonFilled", "", 2, undefined));
export const PentagonRegular = ( /*#__PURE__*/createFluentFontIcon("PentagonRegular", "", 2, undefined));
export const Pentagon20Regular = ( /*#__PURE__*/createFluentFontIcon("Pentagon20Regular", "", 1, 20));
export const Pentagon20Filled = ( /*#__PURE__*/createFluentFontIcon("Pentagon20Filled", "", 0, 20));
export const Pentagon32Regular = ( /*#__PURE__*/createFluentFontIcon("Pentagon32Regular", "", 1, 32));
export const Pentagon32Filled = ( /*#__PURE__*/createFluentFontIcon("Pentagon32Filled", "", 0, 32));
export const Pentagon48Regular = ( /*#__PURE__*/createFluentFontIcon("Pentagon48Regular", "", 1, 48));
export const Pentagon48Filled = ( /*#__PURE__*/createFluentFontIcon("Pentagon48Filled", "", 0, 48));
