"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PeopleAddFilled = ( /*#__PURE__*/createFluentFontIcon("PeopleAddFilled", "", 2, undefined));
export const PeopleAddRegular = ( /*#__PURE__*/createFluentFontIcon("PeopleAddRegular", "", 2, undefined));
export const PeopleAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd16Regular", "", 1, 16));
export const PeopleAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd16Filled", "", 0, 16));
export const PeopleAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd20Regular", "", 1, 20));
export const PeopleAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd20Filled", "", 0, 20));
export const PeopleAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd24Regular", "", 1, 24));
export const PeopleAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd24Filled", "", 0, 24));
export const PeopleAdd28Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd28Regular", "", 1, 28));
export const PeopleAdd28Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd28Filled", "", 0, 28));
export const PeopleAdd32Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd32Regular", "󰕵", 1, 32));
export const PeopleAdd32Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd32Filled", "󰗮", 0, 32));
export const PeopleAdd32Light = ( /*#__PURE__*/createFluentFontIcon("PeopleAdd32Light", "", 3, 32));
