"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PeopleQueueFilled = ( /*#__PURE__*/createFluentFontIcon("PeopleQueueFilled", "", 2, undefined));
export const PeopleQueueRegular = ( /*#__PURE__*/createFluentFontIcon("PeopleQueueRegular", "", 2, undefined));
export const PeopleQueue20Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue20Regular", "", 1, 20));
export const PeopleQueue20Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue20Filled", "", 0, 20));
export const PeopleQueue24Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue24Regular", "", 1, 24));
export const PeopleQueue24Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue24Filled", "", 0, 24));
export const PeopleQueue28Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue28Regular", "󰜎", 1, 28));
export const PeopleQueue28Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue28Filled", "󰞋", 0, 28));
export const PeopleQueue32Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue32Regular", "󰜏", 1, 32));
export const PeopleQueue32Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue32Filled", "󰞌", 0, 32));
export const PeopleQueue48Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue48Regular", "󰜐", 1, 48));
export const PeopleQueue48Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleQueue48Filled", "󰞍", 0, 48));
