"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PeopleCallFilled = ( /*#__PURE__*/createFluentFontIcon("PeopleCallFilled", "", 2, undefined));
export const PeopleCallRegular = ( /*#__PURE__*/createFluentFontIcon("PeopleCallRegular", "", 2, undefined));
export const PeopleCall16Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleCall16Regular", "", 1, 16));
export const PeopleCall16Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleCall16Filled", "", 0, 16));
export const PeopleCall20Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleCall20Regular", "", 1, 20));
export const PeopleCall20Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleCall20Filled", "", 0, 20));
export const PeopleCall24Regular = ( /*#__PURE__*/createFluentFontIcon("PeopleCall24Regular", "󰂂", 1, 24));
export const PeopleCall24Filled = ( /*#__PURE__*/createFluentFontIcon("PeopleCall24Filled", "󰂆", 0, 24));
