"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonSquareFilled = ( /*#__PURE__*/createFluentFontIcon("PersonSquareFilled", "", 2, undefined));
export const PersonSquareRegular = ( /*#__PURE__*/createFluentFontIcon("PersonSquareRegular", "", 2, undefined));
export const PersonSquare16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSquare16Regular", "󰑐", 1, 16));
export const PersonSquare16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSquare16Filled", "󰑣", 0, 16));
export const PersonSquare20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSquare20Regular", "", 1, 20));
export const PersonSquare20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSquare20Filled", "", 0, 20));
export const PersonSquare24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSquare24Regular", "", 1, 24));
export const PersonSquare24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSquare24Filled", "", 0, 24));
export const PersonSquare32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSquare32Regular", "󰑑", 1, 32));
export const PersonSquare32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSquare32Filled", "󰑤", 0, 32));
