"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonWarningFilled = ( /*#__PURE__*/createFluentFontIcon("PersonWarningFilled", "", 2, undefined));
export const PersonWarningRegular = ( /*#__PURE__*/createFluentFontIcon("PersonWarningRegular", "", 2, undefined));
export const PersonWarning16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonWarning16Regular", "󰐋", 1, 16));
export const PersonWarning16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonWarning16Filled", "󰐞", 0, 16));
export const PersonWarning20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonWarning20Regular", "󰐌", 1, 20));
export const PersonWarning20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonWarning20Filled", "󰐟", 0, 20));
export const PersonWarning24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonWarning24Regular", "󰐍", 1, 24));
export const PersonWarning24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonWarning24Filled", "󰐠", 0, 24));
export const PersonWarning28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonWarning28Regular", "󰐎", 1, 28));
export const PersonWarning28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonWarning28Filled", "󰐡", 0, 28));
export const PersonWarning32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonWarning32Regular", "󰐏", 1, 32));
export const PersonWarning32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonWarning32Filled", "󰐢", 0, 32));
export const PersonWarning48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonWarning48Regular", "󰐐", 1, 48));
export const PersonWarning48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonWarning48Filled", "󰐣", 0, 48));
