"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonEditFilled = ( /*#__PURE__*/createFluentFontIcon("PersonEditFilled", "", 2, undefined));
export const PersonEditRegular = ( /*#__PURE__*/createFluentFontIcon("PersonEditRegular", "", 2, undefined));
export const PersonEdit16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonEdit16Regular", "󰢀", 1, 16));
export const PersonEdit16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonEdit16Filled", "󰣽", 0, 16));
export const PersonEdit20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonEdit20Regular", "", 1, 20));
export const PersonEdit20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonEdit20Filled", "", 0, 20));
export const PersonEdit24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonEdit24Regular", "", 1, 24));
export const PersonEdit24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonEdit24Filled", "", 0, 24));
export const PersonEdit32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonEdit32Regular", "󰦚", 1, 32));
export const PersonEdit32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonEdit32Filled", "󰨗", 0, 32));
export const PersonEdit48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonEdit48Regular", "󰉺", 1, 48));
export const PersonEdit48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonEdit48Filled", "󰊍", 0, 48));
