"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonHomeFilled = ( /*#__PURE__*/createFluentFontIcon("PersonHomeFilled", "", 2, undefined));
export const PersonHomeRegular = ( /*#__PURE__*/createFluentFontIcon("PersonHomeRegular", "", 2, undefined));
export const PersonHome16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHome16Regular", "󰙭", 1, 16));
export const PersonHome16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHome16Filled", "󰛭", 0, 16));
export const PersonHome20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHome20Regular", "󰙮", 1, 20));
export const PersonHome20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHome20Filled", "󰛮", 0, 20));
export const PersonHome24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHome24Regular", "󰙯", 1, 24));
export const PersonHome24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHome24Filled", "󰛯", 0, 24));
export const PersonHome28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHome28Regular", "󰙰", 1, 28));
export const PersonHome28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHome28Filled", "󰛰", 0, 28));
export const PersonHome32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHome32Regular", "󰙱", 1, 32));
export const PersonHome32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHome32Filled", "󰛱", 0, 32));
export const PersonHome48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHome48Regular", "󰙲", 1, 48));
export const PersonHome48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHome48Filled", "󰛲", 0, 48));
