"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonCallFilled = ( /*#__PURE__*/createFluentFontIcon("PersonCallFilled", "", 2, undefined));
export const PersonCallRegular = ( /*#__PURE__*/createFluentFontIcon("PersonCallRegular", "", 2, undefined));
export const PersonCall16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonCall16Regular", "", 1, 16));
export const PersonCall16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonCall16Filled", "", 0, 16));
export const PersonCall20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonCall20Regular", "", 1, 20));
export const PersonCall20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonCall20Filled", "", 0, 20));
export const PersonCall24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonCall24Regular", "", 1, 24));
export const PersonCall24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonCall24Filled", "", 0, 24));
