"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonHeartFilled = ( /*#__PURE__*/createFluentFontIcon("PersonHeartFilled", "", 2, undefined));
export const PersonHeartRegular = ( /*#__PURE__*/createFluentFontIcon("PersonHeartRegular", "", 2, undefined));
export const PersonHeart20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHeart20Regular", "", 1, 20));
export const PersonHeart20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHeart20Filled", "", 0, 20));
export const PersonHeart24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHeart24Regular", "", 1, 24));
export const PersonHeart24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHeart24Filled", "", 0, 24));
export const PersonHeart28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHeart28Regular", "󰥓", 1, 28));
export const PersonHeart28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHeart28Filled", "󰧐", 0, 28));
export const PersonHeart32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHeart32Regular", "󰢁", 1, 32));
export const PersonHeart32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHeart32Filled", "󰣾", 0, 32));
export const PersonHeart48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonHeart48Regular", "󰥔", 1, 48));
export const PersonHeart48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonHeart48Filled", "󰧑", 0, 48));
