"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonShieldFilled = ( /*#__PURE__*/createFluentFontIcon("PersonShieldFilled", "", 2, undefined));
export const PersonShieldRegular = ( /*#__PURE__*/createFluentFontIcon("PersonShieldRegular", "", 2, undefined));
export const PersonShield16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonShield16Regular", "󰧞", 1, 16));
export const PersonShield16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonShield16Filled", "󰩛", 0, 16));
export const PersonShield20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonShield20Regular", "󰧟", 1, 20));
export const PersonShield20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonShield20Filled", "󰩜", 0, 20));
export const PersonShield24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonShield24Regular", "󰧠", 1, 24));
export const PersonShield24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonShield24Filled", "󰩝", 0, 24));
export const PersonShield28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonShield28Regular", "󰧡", 1, 28));
export const PersonShield28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonShield28Filled", "󰩞", 0, 28));
export const PersonShield32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonShield32Regular", "󰧢", 1, 32));
export const PersonShield32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonShield32Filled", "󰩟", 0, 32));
export const PersonShield48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonShield48Regular", "󰧣", 1, 48));
export const PersonShield48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonShield48Filled", "󰩠", 0, 48));
