"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonNoteFilled = ( /*#__PURE__*/createFluentFontIcon("PersonNoteFilled", "", 2, undefined));
export const PersonNoteRegular = ( /*#__PURE__*/createFluentFontIcon("PersonNoteRegular", "", 2, undefined));
export const PersonNote16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonNote16Regular", "", 1, 16));
export const PersonNote16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonNote16Filled", "", 0, 16));
export const PersonNote20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonNote20Regular", "", 1, 20));
export const PersonNote20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonNote20Filled", "", 0, 20));
export const PersonNote24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonNote24Regular", "", 1, 24));
export const PersonNote24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonNote24Filled", "", 0, 24));
