"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonLinkFilled = ( /*#__PURE__*/createFluentFontIcon("PersonLinkFilled", "", 2, undefined));
export const PersonLinkRegular = ( /*#__PURE__*/createFluentFontIcon("PersonLinkRegular", "", 2, undefined));
export const PersonLink16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonLink16Regular", "", 1, 16));
export const PersonLink16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonLink16Filled", "", 0, 16));
export const PersonLink20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonLink20Regular", "", 1, 20));
export const PersonLink20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonLink20Filled", "", 0, 20));
export const PersonLink24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonLink24Regular", "", 1, 24));
export const PersonLink24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonLink24Filled", "", 0, 24));
export const PersonLink28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonLink28Regular", "", 1, 28));
export const PersonLink28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonLink28Filled", "", 0, 28));
export const PersonLink32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonLink32Regular", "", 1, 32));
export const PersonLink32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonLink32Filled", "", 0, 32));
export const PersonLink48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonLink48Regular", "", 1, 48));
export const PersonLink48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonLink48Filled", "", 0, 48));
