"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonTagFilled = ( /*#__PURE__*/createFluentFontIcon("PersonTagFilled", "", 2, undefined));
export const PersonTagRegular = ( /*#__PURE__*/createFluentFontIcon("PersonTagRegular", "", 2, undefined));
export const PersonTag20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonTag20Regular", "", 1, 20));
export const PersonTag20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonTag20Filled", "", 0, 20));
export const PersonTag24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonTag24Regular", "", 1, 24));
export const PersonTag24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonTag24Filled", "", 0, 24));
export const PersonTag28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonTag28Regular", "", 1, 28));
export const PersonTag28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonTag28Filled", "", 0, 28));
export const PersonTag32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonTag32Regular", "", 1, 32));
export const PersonTag32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonTag32Filled", "", 0, 32));
export const PersonTag48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonTag48Regular", "", 1, 48));
export const PersonTag48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonTag48Filled", "", 0, 48));
