"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonSwapFilled = ( /*#__PURE__*/createFluentFontIcon("PersonSwapFilled", "", 2, undefined));
export const PersonSwapRegular = ( /*#__PURE__*/createFluentFontIcon("PersonSwapRegular", "", 2, undefined));
export const PersonSwap16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSwap16Regular", "", 1, 16));
export const PersonSwap16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSwap16Filled", "", 0, 16));
export const PersonSwap20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSwap20Regular", "", 1, 20));
export const PersonSwap20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSwap20Filled", "", 0, 20));
export const PersonSwap24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSwap24Regular", "", 1, 24));
export const PersonSwap24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSwap24Filled", "", 0, 24));
