"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonDeleteFilled = ( /*#__PURE__*/createFluentFontIcon("PersonDeleteFilled", "", 2, undefined));
export const PersonDeleteRegular = ( /*#__PURE__*/createFluentFontIcon("PersonDeleteRegular", "", 2, undefined));
export const PersonDelete16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonDelete16Regular", "", 1, 16));
export const PersonDelete16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonDelete16Filled", "", 0, 16));
export const PersonDelete20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonDelete20Regular", "", 1, 20));
export const PersonDelete20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonDelete20Filled", "", 0, 20));
export const PersonDelete24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonDelete24Regular", "", 1, 24));
export const PersonDelete24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonDelete24Filled", "", 0, 24));
