"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonSyncFilled = ( /*#__PURE__*/createFluentFontIcon("PersonSyncFilled", "", 2, undefined));
export const PersonSyncRegular = ( /*#__PURE__*/createFluentFontIcon("PersonSyncRegular", "", 2, undefined));
export const PersonSync16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSync16Regular", "", 1, 16));
export const PersonSync16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSync16Filled", "", 0, 16));
export const PersonSync20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSync20Regular", "", 1, 20));
export const PersonSync20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSync20Filled", "", 0, 20));
export const PersonSync24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSync24Regular", "", 1, 24));
export const PersonSync24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSync24Filled", "", 0, 24));
export const PersonSync28Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSync28Regular", "", 1, 28));
export const PersonSync28Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSync28Filled", "", 0, 28));
export const PersonSync32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSync32Regular", "", 1, 32));
export const PersonSync32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSync32Filled", "", 0, 32));
export const PersonSync48Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSync48Regular", "", 1, 48));
export const PersonSync48Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSync48Filled", "", 0, 48));
