"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonSearchFilled = ( /*#__PURE__*/createFluentFontIcon("PersonSearchFilled", "", 2, undefined));
export const PersonSearchRegular = ( /*#__PURE__*/createFluentFontIcon("PersonSearchRegular", "", 2, undefined));
export const PersonSearch16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSearch16Regular", "", 1, 16));
export const PersonSearch16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSearch16Filled", "", 0, 16));
export const PersonSearch20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSearch20Regular", "", 1, 20));
export const PersonSearch20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSearch20Filled", "", 0, 20));
export const PersonSearch24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSearch24Regular", "", 1, 24));
export const PersonSearch24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSearch24Filled", "", 0, 24));
export const PersonSearch32Regular = ( /*#__PURE__*/createFluentFontIcon("PersonSearch32Regular", "", 1, 32));
export const PersonSearch32Filled = ( /*#__PURE__*/createFluentFontIcon("PersonSearch32Filled", "", 0, 32));
