"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PersonClockFilled = ( /*#__PURE__*/createFluentFontIcon("PersonClockFilled", "", 2, undefined));
export const PersonClockRegular = ( /*#__PURE__*/createFluentFontIcon("PersonClockRegular", "", 2, undefined));
export const PersonClock16Regular = ( /*#__PURE__*/createFluentFontIcon("PersonClock16Regular", "", 1, 16));
export const PersonClock16Filled = ( /*#__PURE__*/createFluentFontIcon("PersonClock16Filled", "", 0, 16));
export const PersonClock20Regular = ( /*#__PURE__*/createFluentFontIcon("PersonClock20Regular", "", 1, 20));
export const PersonClock20Filled = ( /*#__PURE__*/createFluentFontIcon("PersonClock20Filled", "", 0, 20));
export const PersonClock24Regular = ( /*#__PURE__*/createFluentFontIcon("PersonClock24Regular", "", 1, 24));
export const PersonClock24Filled = ( /*#__PURE__*/createFluentFontIcon("PersonClock24Filled", "", 0, 24));
