"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PhoneLaptopFilled = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptopFilled", "", 2, undefined));
export const PhoneLaptopRegular = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptopRegular", "", 2, undefined));
export const PhoneLaptop16Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop16Regular", "", 1, 16));
export const PhoneLaptop16Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop16Filled", "", 0, 16));
export const PhoneLaptop20Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop20Regular", "", 1, 20));
export const PhoneLaptop20Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop20Filled", "", 0, 20));
export const PhoneLaptop24Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop24Regular", "", 1, 24));
export const PhoneLaptop24Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop24Filled", "", 0, 24));
export const PhoneLaptop32Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop32Regular", "", 1, 32));
export const PhoneLaptop32Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneLaptop32Filled", "", 0, 32));
