"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PhoneSpanInFilled = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanInFilled", "", 2, undefined));
export const PhoneSpanInRegular = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanInRegular", "", 2, undefined));
export const PhoneSpanIn16Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn16Regular", "", 1, 16));
export const PhoneSpanIn16Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn16Filled", "", 0, 16));
export const PhoneSpanIn20Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn20Regular", "", 1, 20));
export const PhoneSpanIn20Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn20Filled", "", 0, 20));
export const PhoneSpanIn24Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn24Regular", "", 1, 24));
export const PhoneSpanIn24Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn24Filled", "", 0, 24));
export const PhoneSpanIn28Regular = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn28Regular", "", 1, 28));
export const PhoneSpanIn28Filled = ( /*#__PURE__*/createFluentFontIcon("PhoneSpanIn28Filled", "", 0, 28));
