"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PinFilled = ( /*#__PURE__*/createFluentFontIcon("PinFilled", "", 2, undefined));
export const PinRegular = ( /*#__PURE__*/createFluentFontIcon("PinRegular", "", 2, undefined));
export const Pin12Regular = ( /*#__PURE__*/createFluentFontIcon("Pin12Regular", "", 1, 12));
export const Pin12Filled = ( /*#__PURE__*/createFluentFontIcon("Pin12Filled", "", 0, 12));
export const Pin16Regular = ( /*#__PURE__*/createFluentFontIcon("Pin16Regular", "", 1, 16));
export const Pin16Filled = ( /*#__PURE__*/createFluentFontIcon("Pin16Filled", "", 0, 16));
export const Pin20Regular = ( /*#__PURE__*/createFluentFontIcon("Pin20Regular", "", 1, 20));
export const Pin20Filled = ( /*#__PURE__*/createFluentFontIcon("Pin20Filled", "", 0, 20));
export const Pin24Regular = ( /*#__PURE__*/createFluentFontIcon("Pin24Regular", "", 1, 24));
export const Pin24Filled = ( /*#__PURE__*/createFluentFontIcon("Pin24Filled", "", 0, 24));
export const Pin28Regular = ( /*#__PURE__*/createFluentFontIcon("Pin28Regular", "", 1, 28));
export const Pin28Filled = ( /*#__PURE__*/createFluentFontIcon("Pin28Filled", "", 0, 28));
export const Pin32Regular = ( /*#__PURE__*/createFluentFontIcon("Pin32Regular", "", 1, 32));
export const Pin32Filled = ( /*#__PURE__*/createFluentFontIcon("Pin32Filled", "", 0, 32));
export const Pin32Light = ( /*#__PURE__*/createFluentFontIcon("Pin32Light", "", 3, 32));
export const Pin48Regular = ( /*#__PURE__*/createFluentFontIcon("Pin48Regular", "", 1, 48));
export const Pin48Filled = ( /*#__PURE__*/createFluentFontIcon("Pin48Filled", "", 0, 48));
