"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PipelineFilled = ( /*#__PURE__*/createFluentFontIcon("PipelineFilled", "", 2, undefined));
export const PipelineRegular = ( /*#__PURE__*/createFluentFontIcon("PipelineRegular", "", 2, undefined));
export const Pipeline20Regular = ( /*#__PURE__*/createFluentFontIcon("Pipeline20Regular", "", 1, 20));
export const Pipeline20Filled = ( /*#__PURE__*/createFluentFontIcon("Pipeline20Filled", "", 0, 20));
export const Pipeline24Regular = ( /*#__PURE__*/createFluentFontIcon("Pipeline24Regular", "", 1, 24));
export const Pipeline24Filled = ( /*#__PURE__*/createFluentFontIcon("Pipeline24Filled", "", 0, 24));
export const Pipeline32Regular = ( /*#__PURE__*/createFluentFontIcon("Pipeline32Regular", "", 1, 32));
export const Pipeline32Filled = ( /*#__PURE__*/createFluentFontIcon("Pipeline32Filled", "", 0, 32));
