"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PlantGrassFilled = ( /*#__PURE__*/createFluentFontIcon("PlantGrassFilled", "", 2, undefined));
export const PlantGrassRegular = ( /*#__PURE__*/createFluentFontIcon("PlantGrassRegular", "", 2, undefined));
export const PlantGrass20Regular = ( /*#__PURE__*/createFluentFontIcon("PlantGrass20Regular", "󰄶", 1, 20));
export const PlantGrass20Filled = ( /*#__PURE__*/createFluentFontIcon("PlantGrass20Filled", "󰄵", 0, 20));
export const PlantGrass24Regular = ( /*#__PURE__*/createFluentFontIcon("PlantGrass24Regular", "󰄷", 1, 24));
export const PlantGrass24Filled = ( /*#__PURE__*/createFluentFontIcon("PlantGrass24Filled", "󰄶", 0, 24));
export const PlantGrass28Regular = ( /*#__PURE__*/createFluentFontIcon("PlantGrass28Regular", "󰄸", 1, 28));
export const PlantGrass28Filled = ( /*#__PURE__*/createFluentFontIcon("PlantGrass28Filled", "󰄷", 0, 28));
