"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PollFilled = ( /*#__PURE__*/createFluentFontIcon("PollFilled", "", 2, undefined));
export const PollRegular = ( /*#__PURE__*/createFluentFontIcon("PollRegular", "", 2, undefined));
export const Poll16Regular = ( /*#__PURE__*/createFluentFontIcon("Poll16Regular", "", 1, 16));
export const Poll16Filled = ( /*#__PURE__*/createFluentFontIcon("Poll16Filled", "", 0, 16));
export const Poll20Regular = ( /*#__PURE__*/createFluentFontIcon("Poll20Regular", "", 1, 20));
export const Poll20Filled = ( /*#__PURE__*/createFluentFontIcon("Poll20Filled", "", 0, 20));
export const Poll24Regular = ( /*#__PURE__*/createFluentFontIcon("Poll24Regular", "", 1, 24));
export const Poll24Filled = ( /*#__PURE__*/createFluentFontIcon("Poll24Filled", "", 0, 24));
export const Poll28Regular = ( /*#__PURE__*/createFluentFontIcon("Poll28Regular", "󰪁", 1, 28));
export const Poll28Filled = ( /*#__PURE__*/createFluentFontIcon("Poll28Filled", "󰫽", 0, 28));
export const Poll32Regular = ( /*#__PURE__*/createFluentFontIcon("Poll32Regular", "󰑚", 1, 32));
export const Poll32Filled = ( /*#__PURE__*/createFluentFontIcon("Poll32Filled", "󰑭", 0, 32));
export const Poll32Light = ( /*#__PURE__*/createFluentFontIcon("Poll32Light", "", 3, 32));
