"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PowerFilled = ( /*#__PURE__*/createFluentFontIcon("PowerFilled", "", 2, undefined));
export const PowerRegular = ( /*#__PURE__*/createFluentFontIcon("PowerRegular", "", 2, undefined));
export const Power20Regular = ( /*#__PURE__*/createFluentFontIcon("Power20Regular", "", 1, 20));
export const Power20Filled = ( /*#__PURE__*/createFluentFontIcon("Power20Filled", "", 0, 20));
export const Power24Regular = ( /*#__PURE__*/createFluentFontIcon("Power24Regular", "", 1, 24));
export const Power24Filled = ( /*#__PURE__*/createFluentFontIcon("Power24Filled", "", 0, 24));
export const Power28Regular = ( /*#__PURE__*/createFluentFontIcon("Power28Regular", "", 1, 28));
export const Power28Filled = ( /*#__PURE__*/createFluentFontIcon("Power28Filled", "", 0, 28));
