"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PreviousFilled = ( /*#__PURE__*/createFluentFontIcon("PreviousFilled", "", 2, undefined));
export const PreviousRegular = ( /*#__PURE__*/createFluentFontIcon("PreviousRegular", "", 2, undefined));
export const Previous16Regular = ( /*#__PURE__*/createFluentFontIcon("Previous16Regular", "", 1, 16));
export const Previous16Filled = ( /*#__PURE__*/createFluentFontIcon("Previous16Filled", "", 0, 16));
export const Previous20Regular = ( /*#__PURE__*/createFluentFontIcon("Previous20Regular", "", 1, 20));
export const Previous20Filled = ( /*#__PURE__*/createFluentFontIcon("Previous20Filled", "", 0, 20));
export const Previous24Regular = ( /*#__PURE__*/createFluentFontIcon("Previous24Regular", "", 1, 24));
export const Previous24Filled = ( /*#__PURE__*/createFluentFontIcon("Previous24Filled", "", 0, 24));
export const Previous28Regular = ( /*#__PURE__*/createFluentFontIcon("Previous28Regular", "", 1, 28));
export const Previous28Filled = ( /*#__PURE__*/createFluentFontIcon("Previous28Filled", "", 0, 28));
export const Previous32Regular = ( /*#__PURE__*/createFluentFontIcon("Previous32Regular", "", 1, 32));
export const Previous32Filled = ( /*#__PURE__*/createFluentFontIcon("Previous32Filled", "", 0, 32));
export const Previous48Regular = ( /*#__PURE__*/createFluentFontIcon("Previous48Regular", "", 1, 48));
export const Previous48Filled = ( /*#__PURE__*/createFluentFontIcon("Previous48Filled", "", 0, 48));
