"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PreviewLinkFilled = ( /*#__PURE__*/createFluentFontIcon("PreviewLinkFilled", "", 2, undefined));
export const PreviewLinkRegular = ( /*#__PURE__*/createFluentFontIcon("PreviewLinkRegular", "", 2, undefined));
export const PreviewLink16Regular = ( /*#__PURE__*/createFluentFontIcon("PreviewLink16Regular", "", 1, 16));
export const PreviewLink16Filled = ( /*#__PURE__*/createFluentFontIcon("PreviewLink16Filled", "", 0, 16));
export const PreviewLink20Regular = ( /*#__PURE__*/createFluentFontIcon("PreviewLink20Regular", "", 1, 20));
export const PreviewLink20Filled = ( /*#__PURE__*/createFluentFontIcon("PreviewLink20Filled", "", 0, 20));
export const PreviewLink24Regular = ( /*#__PURE__*/createFluentFontIcon("PreviewLink24Regular", "", 1, 24));
export const PreviewLink24Filled = ( /*#__PURE__*/createFluentFontIcon("PreviewLink24Filled", "", 0, 24));
