"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PrintFilled = ( /*#__PURE__*/createFluentFontIcon("PrintFilled", "", 2, undefined));
export const PrintRegular = ( /*#__PURE__*/createFluentFontIcon("PrintRegular", "", 2, undefined));
export const Print16Regular = ( /*#__PURE__*/createFluentFontIcon("Print16Regular", "", 1, 16));
export const Print16Filled = ( /*#__PURE__*/createFluentFontIcon("Print16Filled", "", 0, 16));
export const Print20Regular = ( /*#__PURE__*/createFluentFontIcon("Print20Regular", "", 1, 20));
export const Print20Filled = ( /*#__PURE__*/createFluentFontIcon("Print20Filled", "", 0, 20));
export const Print24Regular = ( /*#__PURE__*/createFluentFontIcon("Print24Regular", "", 1, 24));
export const Print24Filled = ( /*#__PURE__*/createFluentFontIcon("Print24Filled", "", 0, 24));
export const Print28Regular = ( /*#__PURE__*/createFluentFontIcon("Print28Regular", "", 1, 28));
export const Print28Filled = ( /*#__PURE__*/createFluentFontIcon("Print28Filled", "", 0, 28));
export const Print32Regular = ( /*#__PURE__*/createFluentFontIcon("Print32Regular", "", 1, 32));
export const Print32Filled = ( /*#__PURE__*/createFluentFontIcon("Print32Filled", "", 0, 32));
export const Print32Light = ( /*#__PURE__*/createFluentFontIcon("Print32Light", "", 3, 32));
export const Print48Regular = ( /*#__PURE__*/createFluentFontIcon("Print48Regular", "", 1, 48));
export const Print48Filled = ( /*#__PURE__*/createFluentFontIcon("Print48Filled", "", 0, 48));
