"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ProhibitedFilled = ( /*#__PURE__*/createFluentFontIcon("ProhibitedFilled", "", 2, undefined));
export const ProhibitedRegular = ( /*#__PURE__*/createFluentFontIcon("ProhibitedRegular", "", 2, undefined));
export const Prohibited12Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited12Regular", "", 1, 12));
export const Prohibited12Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited12Filled", "", 0, 12));
export const Prohibited16Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited16Regular", "", 1, 16));
export const Prohibited16Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited16Filled", "", 0, 16));
export const Prohibited20Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited20Regular", "", 1, 20));
export const Prohibited20Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited20Filled", "", 0, 20));
export const Prohibited24Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited24Regular", "", 1, 24));
export const Prohibited24Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited24Filled", "", 0, 24));
export const Prohibited28Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited28Regular", "", 1, 28));
export const Prohibited28Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited28Filled", "", 0, 28));
export const Prohibited32Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited32Regular", "󰇵", 1, 32));
export const Prohibited32Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited32Filled", "󰇵", 0, 32));
export const Prohibited48Regular = ( /*#__PURE__*/createFluentFontIcon("Prohibited48Regular", "", 1, 48));
export const Prohibited48Filled = ( /*#__PURE__*/createFluentFontIcon("Prohibited48Filled", "", 0, 48));
