"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ProjectionScreenFilled = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreenFilled", "", 2, undefined));
export const ProjectionScreenRegular = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreenRegular", "", 2, undefined));
export const ProjectionScreen16Regular = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen16Regular", "", 1, 16));
export const ProjectionScreen16Filled = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen16Filled", "", 0, 16));
export const ProjectionScreen20Regular = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen20Regular", "", 1, 20));
export const ProjectionScreen20Filled = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen20Filled", "", 0, 20));
export const ProjectionScreen24Regular = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen24Regular", "", 1, 24));
export const ProjectionScreen24Filled = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen24Filled", "", 0, 24));
export const ProjectionScreen28Regular = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen28Regular", "", 1, 28));
export const ProjectionScreen28Filled = ( /*#__PURE__*/createFluentFontIcon("ProjectionScreen28Filled", "", 0, 28));
