"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ProtocolHandlerFilled = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandlerFilled", "", 2, undefined));
export const ProtocolHandlerRegular = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandlerRegular", "", 2, undefined));
export const ProtocolHandler16Regular = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandler16Regular", "", 1, 16));
export const ProtocolHandler16Filled = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandler16Filled", "", 0, 16));
export const ProtocolHandler20Regular = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandler20Regular", "", 1, 20));
export const ProtocolHandler20Filled = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandler20Filled", "", 0, 20));
export const ProtocolHandler24Regular = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandler24Regular", "", 1, 24));
export const ProtocolHandler24Filled = ( /*#__PURE__*/createFluentFontIcon("ProtocolHandler24Filled", "", 0, 24));
