"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const PuzzleCubeFilled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCubeFilled", "", 2, undefined));
export const PuzzleCubeRegular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCubeRegular", "", 2, undefined));
export const PuzzleCube16Regular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube16Regular", "", 1, 16));
export const PuzzleCube16Filled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube16Filled", "", 0, 16));
export const PuzzleCube20Regular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube20Regular", "", 1, 20));
export const PuzzleCube20Filled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube20Filled", "", 0, 20));
export const PuzzleCube24Regular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube24Regular", "", 1, 24));
export const PuzzleCube24Filled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube24Filled", "", 0, 24));
export const PuzzleCube28Regular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube28Regular", "", 1, 28));
export const PuzzleCube28Filled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube28Filled", "", 0, 28));
export const PuzzleCube32Regular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube32Regular", "󰪂", 1, 32));
export const PuzzleCube32Filled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube32Filled", "󰫾", 0, 32));
export const PuzzleCube48Regular = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube48Regular", "", 1, 48));
export const PuzzleCube48Filled = ( /*#__PURE__*/createFluentFontIcon("PuzzleCube48Filled", "", 0, 48));
