"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const QuizFilled = ( /*#__PURE__*/createFluentFontIcon("QuizFilled", "", 2, undefined));
export const QuizRegular = ( /*#__PURE__*/createFluentFontIcon("QuizRegular", "", 2, undefined));
export const Quiz20Regular = ( /*#__PURE__*/createFluentFontIcon("Quiz20Regular", "󰬍", 1, 20));
export const Quiz20Filled = ( /*#__PURE__*/createFluentFontIcon("Quiz20Filled", "󰮋", 0, 20));
export const Quiz24Regular = ( /*#__PURE__*/createFluentFontIcon("Quiz24Regular", "󰬎", 1, 24));
export const Quiz24Filled = ( /*#__PURE__*/createFluentFontIcon("Quiz24Filled", "󰮌", 0, 24));
export const Quiz28Regular = ( /*#__PURE__*/createFluentFontIcon("Quiz28Regular", "󰬏", 1, 28));
export const Quiz28Filled = ( /*#__PURE__*/createFluentFontIcon("Quiz28Filled", "󰮍", 0, 28));
export const Quiz48Regular = ( /*#__PURE__*/createFluentFontIcon("Quiz48Regular", "󰬐", 1, 48));
export const Quiz48Filled = ( /*#__PURE__*/createFluentFontIcon("Quiz48Filled", "󰮎", 0, 48));
