"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const RatingMatureFilled = ( /*#__PURE__*/createFluentFontIcon("RatingMatureFilled", "", 2, undefined));
export const RatingMatureRegular = ( /*#__PURE__*/createFluentFontIcon("RatingMatureRegular", "", 2, undefined));
export const RatingMature16Regular = ( /*#__PURE__*/createFluentFontIcon("RatingMature16Regular", "", 1, 16));
export const RatingMature16Filled = ( /*#__PURE__*/createFluentFontIcon("RatingMature16Filled", "", 0, 16));
export const RatingMature20Regular = ( /*#__PURE__*/createFluentFontIcon("RatingMature20Regular", "", 1, 20));
export const RatingMature20Filled = ( /*#__PURE__*/createFluentFontIcon("RatingMature20Filled", "", 0, 20));
export const RatingMature24Regular = ( /*#__PURE__*/createFluentFontIcon("RatingMature24Regular", "", 1, 24));
export const RatingMature24Filled = ( /*#__PURE__*/createFluentFontIcon("RatingMature24Filled", "", 0, 24));
