"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ReadAloudFilled = ( /*#__PURE__*/createFluentFontIcon("ReadAloudFilled", "", 2, undefined));
export const ReadAloudRegular = ( /*#__PURE__*/createFluentFontIcon("ReadAloudRegular", "", 2, undefined));
export const ReadAloud16Regular = ( /*#__PURE__*/createFluentFontIcon("ReadAloud16Regular", "", 1, 16));
export const ReadAloud16Filled = ( /*#__PURE__*/createFluentFontIcon("ReadAloud16Filled", "", 0, 16));
export const ReadAloud20Regular = ( /*#__PURE__*/createFluentFontIcon("ReadAloud20Regular", "", 1, 20));
export const ReadAloud20Filled = ( /*#__PURE__*/createFluentFontIcon("ReadAloud20Filled", "", 0, 20));
export const ReadAloud24Regular = ( /*#__PURE__*/createFluentFontIcon("ReadAloud24Regular", "", 1, 24));
export const ReadAloud24Filled = ( /*#__PURE__*/createFluentFontIcon("ReadAloud24Filled", "", 0, 24));
export const ReadAloud28Regular = ( /*#__PURE__*/createFluentFontIcon("ReadAloud28Regular", "", 1, 28));
export const ReadAloud28Filled = ( /*#__PURE__*/createFluentFontIcon("ReadAloud28Filled", "", 0, 28));
export const ReadAloud32Light = ( /*#__PURE__*/createFluentFontIcon("ReadAloud32Light", "", 3, 32));
