"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ReceiptFilled = ( /*#__PURE__*/createFluentFontIcon("ReceiptFilled", "", 2, undefined));
export const ReceiptRegular = ( /*#__PURE__*/createFluentFontIcon("ReceiptRegular", "", 2, undefined));
export const Receipt16Regular = ( /*#__PURE__*/createFluentFontIcon("Receipt16Regular", "", 1, 16));
export const Receipt16Filled = ( /*#__PURE__*/createFluentFontIcon("Receipt16Filled", "", 0, 16));
export const Receipt20Regular = ( /*#__PURE__*/createFluentFontIcon("Receipt20Regular", "", 1, 20));
export const Receipt20Filled = ( /*#__PURE__*/createFluentFontIcon("Receipt20Filled", "", 0, 20));
export const Receipt24Regular = ( /*#__PURE__*/createFluentFontIcon("Receipt24Regular", "", 1, 24));
export const Receipt24Filled = ( /*#__PURE__*/createFluentFontIcon("Receipt24Filled", "", 0, 24));
export const Receipt28Regular = ( /*#__PURE__*/createFluentFontIcon("Receipt28Regular", "", 1, 28));
export const Receipt28Filled = ( /*#__PURE__*/createFluentFontIcon("Receipt28Filled", "", 0, 28));
export const Receipt32Regular = ( /*#__PURE__*/createFluentFontIcon("Receipt32Regular", "󰂖", 1, 32));
export const Receipt32Filled = ( /*#__PURE__*/createFluentFontIcon("Receipt32Filled", "󰂕", 0, 32));
export const Receipt48Regular = ( /*#__PURE__*/createFluentFontIcon("Receipt48Regular", "󰛕", 1, 48));
export const Receipt48Filled = ( /*#__PURE__*/createFluentFontIcon("Receipt48Filled", "󰝒", 0, 48));
