"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ReceiptMoneyFilled = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoneyFilled", "", 2, undefined));
export const ReceiptMoneyRegular = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoneyRegular", "", 2, undefined));
export const ReceiptMoney16Regular = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoney16Regular", "󰂗", 1, 16));
export const ReceiptMoney16Filled = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoney16Filled", "󰂖", 0, 16));
export const ReceiptMoney20Regular = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoney20Regular", "", 1, 20));
export const ReceiptMoney20Filled = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoney20Filled", "", 0, 20));
export const ReceiptMoney24Regular = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoney24Regular", "", 1, 24));
export const ReceiptMoney24Filled = ( /*#__PURE__*/createFluentFontIcon("ReceiptMoney24Filled", "", 0, 24));
