"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const RemixAddFilled = ( /*#__PURE__*/createFluentFontIcon("RemixAddFilled", "", 2, undefined));
export const RemixAddRegular = ( /*#__PURE__*/createFluentFontIcon("RemixAddRegular", "", 2, undefined));
export const RemixAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("RemixAdd16Regular", "󰋆", 1, 16));
export const RemixAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("RemixAdd16Filled", "󰋙", 0, 16));
export const RemixAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("RemixAdd20Regular", "󰋇", 1, 20));
export const RemixAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("RemixAdd20Filled", "󰋚", 0, 20));
export const RemixAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("RemixAdd24Regular", "󰋈", 1, 24));
export const RemixAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("RemixAdd24Filled", "󰋛", 0, 24));
export const RemixAdd32Regular = ( /*#__PURE__*/createFluentFontIcon("RemixAdd32Regular", "󰋉", 1, 32));
export const RemixAdd32Filled = ( /*#__PURE__*/createFluentFontIcon("RemixAdd32Filled", "󰋜", 0, 32));
