"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ResizeFilled = ( /*#__PURE__*/createFluentFontIcon("ResizeFilled", "", 2, undefined));
export const ResizeRegular = ( /*#__PURE__*/createFluentFontIcon("ResizeRegular", "", 2, undefined));
export const Resize16Regular = ( /*#__PURE__*/createFluentFontIcon("Resize16Regular", "󰒴", 1, 16));
export const Resize16Filled = ( /*#__PURE__*/createFluentFontIcon("Resize16Filled", "󰔭", 0, 16));
export const Resize20Regular = ( /*#__PURE__*/createFluentFontIcon("Resize20Regular", "", 1, 20));
export const Resize20Filled = ( /*#__PURE__*/createFluentFontIcon("Resize20Filled", "", 0, 20));
export const Resize24Regular = ( /*#__PURE__*/createFluentFontIcon("Resize24Regular", "", 1, 24));
export const Resize24Filled = ( /*#__PURE__*/createFluentFontIcon("Resize24Filled", "", 0, 24));
export const Resize28Regular = ( /*#__PURE__*/createFluentFontIcon("Resize28Regular", "󰒵", 1, 28));
export const Resize28Filled = ( /*#__PURE__*/createFluentFontIcon("Resize28Filled", "󰔮", 0, 28));
export const Resize32Regular = ( /*#__PURE__*/createFluentFontIcon("Resize32Regular", "󰒶", 1, 32));
export const Resize32Filled = ( /*#__PURE__*/createFluentFontIcon("Resize32Filled", "󰔯", 0, 32));
export const Resize48Regular = ( /*#__PURE__*/createFluentFontIcon("Resize48Regular", "󰒷", 1, 48));
export const Resize48Filled = ( /*#__PURE__*/createFluentFontIcon("Resize48Filled", "󰔰", 0, 48));
