"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ResizeLargeFilled = ( /*#__PURE__*/createFluentFontIcon("ResizeLargeFilled", "", 2, undefined));
export const ResizeLargeRegular = ( /*#__PURE__*/createFluentFontIcon("ResizeLargeRegular", "", 2, undefined));
export const ResizeLarge16Regular = ( /*#__PURE__*/createFluentFontIcon("ResizeLarge16Regular", "", 1, 16));
export const ResizeLarge16Filled = ( /*#__PURE__*/createFluentFontIcon("ResizeLarge16Filled", "", 0, 16));
export const ResizeLarge20Regular = ( /*#__PURE__*/createFluentFontIcon("ResizeLarge20Regular", "", 1, 20));
export const ResizeLarge20Filled = ( /*#__PURE__*/createFluentFontIcon("ResizeLarge20Filled", "", 0, 20));
export const ResizeLarge24Regular = ( /*#__PURE__*/createFluentFontIcon("ResizeLarge24Regular", "", 1, 24));
export const ResizeLarge24Filled = ( /*#__PURE__*/createFluentFontIcon("ResizeLarge24Filled", "", 0, 24));
