"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const RewardFilled = ( /*#__PURE__*/createFluentFontIcon("RewardFilled", "", 2, undefined));
export const RewardRegular = ( /*#__PURE__*/createFluentFontIcon("RewardRegular", "", 2, undefined));
export const Reward12Regular = ( /*#__PURE__*/createFluentFontIcon("Reward12Regular", "", 1, 12));
export const Reward12Filled = ( /*#__PURE__*/createFluentFontIcon("Reward12Filled", "", 0, 12));
export const Reward16Regular = ( /*#__PURE__*/createFluentFontIcon("Reward16Regular", "", 1, 16));
export const Reward16Filled = ( /*#__PURE__*/createFluentFontIcon("Reward16Filled", "", 0, 16));
export const Reward20Regular = ( /*#__PURE__*/createFluentFontIcon("Reward20Regular", "", 1, 20));
export const Reward20Filled = ( /*#__PURE__*/createFluentFontIcon("Reward20Filled", "", 0, 20));
export const Reward24Regular = ( /*#__PURE__*/createFluentFontIcon("Reward24Regular", "", 1, 24));
export const Reward24Filled = ( /*#__PURE__*/createFluentFontIcon("Reward24Filled", "", 0, 24));
export const Reward32Regular = ( /*#__PURE__*/createFluentFontIcon("Reward32Regular", "󰛈", 1, 32));
export const Reward32Filled = ( /*#__PURE__*/createFluentFontIcon("Reward32Filled", "󰝅", 0, 32));
