"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const RowChildFilled = ( /*#__PURE__*/createFluentFontIcon("RowChildFilled", "", 2, undefined));
export const RowChildRegular = ( /*#__PURE__*/createFluentFontIcon("RowChildRegular", "", 2, undefined));
export const RowChild16Regular = ( /*#__PURE__*/createFluentFontIcon("RowChild16Regular", "󰞸", 1, 16));
export const RowChild16Filled = ( /*#__PURE__*/createFluentFontIcon("RowChild16Filled", "󰠵", 0, 16));
export const RowChild20Regular = ( /*#__PURE__*/createFluentFontIcon("RowChild20Regular", "󰞹", 1, 20));
export const RowChild20Filled = ( /*#__PURE__*/createFluentFontIcon("RowChild20Filled", "󰠶", 0, 20));
export const RowChild24Regular = ( /*#__PURE__*/createFluentFontIcon("RowChild24Regular", "󰞺", 1, 24));
export const RowChild24Filled = ( /*#__PURE__*/createFluentFontIcon("RowChild24Filled", "󰠷", 0, 24));
export const RowChild28Regular = ( /*#__PURE__*/createFluentFontIcon("RowChild28Regular", "󰞻", 1, 28));
export const RowChild28Filled = ( /*#__PURE__*/createFluentFontIcon("RowChild28Filled", "󰠸", 0, 28));
export const RowChild32Regular = ( /*#__PURE__*/createFluentFontIcon("RowChild32Regular", "󰞼", 1, 32));
export const RowChild32Filled = ( /*#__PURE__*/createFluentFontIcon("RowChild32Filled", "󰠹", 0, 32));
