"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const RulerFilled = ( /*#__PURE__*/createFluentFontIcon("RulerFilled", "", 2, undefined));
export const RulerRegular = ( /*#__PURE__*/createFluentFontIcon("RulerRegular", "", 2, undefined));
export const Ruler16Regular = ( /*#__PURE__*/createFluentFontIcon("Ruler16Regular", "", 1, 16));
export const Ruler16Filled = ( /*#__PURE__*/createFluentFontIcon("Ruler16Filled", "", 0, 16));
export const Ruler20Regular = ( /*#__PURE__*/createFluentFontIcon("Ruler20Regular", "", 1, 20));
export const Ruler20Filled = ( /*#__PURE__*/createFluentFontIcon("Ruler20Filled", "", 0, 20));
export const Ruler24Regular = ( /*#__PURE__*/createFluentFontIcon("Ruler24Regular", "", 1, 24));
export const Ruler24Filled = ( /*#__PURE__*/createFluentFontIcon("Ruler24Filled", "", 0, 24));
export const Ruler28Regular = ( /*#__PURE__*/createFluentFontIcon("Ruler28Regular", "", 1, 28));
export const Ruler28Filled = ( /*#__PURE__*/createFluentFontIcon("Ruler28Filled", "", 0, 28));
export const Ruler32Regular = ( /*#__PURE__*/createFluentFontIcon("Ruler32Regular", "", 1, 32));
export const Ruler32Filled = ( /*#__PURE__*/createFluentFontIcon("Ruler32Filled", "", 0, 32));
export const Ruler48Regular = ( /*#__PURE__*/createFluentFontIcon("Ruler48Regular", "", 1, 48));
export const Ruler48Filled = ( /*#__PURE__*/createFluentFontIcon("Ruler48Filled", "", 0, 48));
