"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const RunFilled = ( /*#__PURE__*/createFluentFontIcon("RunFilled", "", 2, undefined));
export const RunRegular = ( /*#__PURE__*/createFluentFontIcon("RunRegular", "", 2, undefined));
export const Run16Regular = ( /*#__PURE__*/createFluentFontIcon("Run16Regular", "", 1, 16));
export const Run16Filled = ( /*#__PURE__*/createFluentFontIcon("Run16Filled", "", 0, 16));
export const Run20Regular = ( /*#__PURE__*/createFluentFontIcon("Run20Regular", "", 1, 20));
export const Run20Filled = ( /*#__PURE__*/createFluentFontIcon("Run20Filled", "", 0, 20));
export const Run24Regular = ( /*#__PURE__*/createFluentFontIcon("Run24Regular", "", 1, 24));
export const Run24Filled = ( /*#__PURE__*/createFluentFontIcon("Run24Filled", "", 0, 24));
export const Run28Regular = ( /*#__PURE__*/createFluentFontIcon("Run28Regular", "󰖶", 1, 28));
export const Run28Filled = ( /*#__PURE__*/createFluentFontIcon("Run28Filled", "󰘯", 0, 28));
export const Run32Regular = ( /*#__PURE__*/createFluentFontIcon("Run32Regular", "󰖷", 1, 32));
export const Run32Filled = ( /*#__PURE__*/createFluentFontIcon("Run32Filled", "󰘰", 0, 32));
export const Run48Regular = ( /*#__PURE__*/createFluentFontIcon("Run48Regular", "󰖸", 1, 48));
export const Run48Filled = ( /*#__PURE__*/createFluentFontIcon("Run48Filled", "󰘱", 0, 48));
