"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ScaleFitFilled = ( /*#__PURE__*/createFluentFontIcon("ScaleFitFilled", "", 2, undefined));
export const ScaleFitRegular = ( /*#__PURE__*/createFluentFontIcon("ScaleFitRegular", "", 2, undefined));
export const ScaleFit16Regular = ( /*#__PURE__*/createFluentFontIcon("ScaleFit16Regular", "", 1, 16));
export const ScaleFit16Filled = ( /*#__PURE__*/createFluentFontIcon("ScaleFit16Filled", "", 0, 16));
export const ScaleFit20Regular = ( /*#__PURE__*/createFluentFontIcon("ScaleFit20Regular", "", 1, 20));
export const ScaleFit20Filled = ( /*#__PURE__*/createFluentFontIcon("ScaleFit20Filled", "", 0, 20));
export const ScaleFit24Regular = ( /*#__PURE__*/createFluentFontIcon("ScaleFit24Regular", "", 1, 24));
export const ScaleFit24Filled = ( /*#__PURE__*/createFluentFontIcon("ScaleFit24Filled", "", 0, 24));
