"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ScanPersonFilled = ( /*#__PURE__*/createFluentFontIcon("ScanPersonFilled", "", 2, undefined));
export const ScanPersonRegular = ( /*#__PURE__*/createFluentFontIcon("ScanPersonRegular", "", 2, undefined));
export const ScanPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("ScanPerson16Regular", "󰌚", 1, 16));
export const ScanPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("ScanPerson16Filled", "󰌭", 0, 16));
export const ScanPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("ScanPerson20Regular", "󰌛", 1, 20));
export const ScanPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("ScanPerson20Filled", "󰌮", 0, 20));
export const ScanPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("ScanPerson24Regular", "󰌜", 1, 24));
export const ScanPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("ScanPerson24Filled", "󰌯", 0, 24));
export const ScanPerson28Regular = ( /*#__PURE__*/createFluentFontIcon("ScanPerson28Regular", "󰌝", 1, 28));
export const ScanPerson28Filled = ( /*#__PURE__*/createFluentFontIcon("ScanPerson28Filled", "󰌰", 0, 28));
export const ScanPerson48Regular = ( /*#__PURE__*/createFluentFontIcon("ScanPerson48Regular", "󰌞", 1, 48));
export const ScanPerson48Filled = ( /*#__PURE__*/createFluentFontIcon("ScanPerson48Filled", "󰌱", 0, 48));
