"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SearchSparkleFilled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkleFilled", "", 2, undefined));
export const SearchSparkleRegular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkleRegular", "", 2, undefined));
export const SearchSparkle16Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle16Regular", "󰘵", 1, 16));
export const SearchSparkle16Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle16Filled", "󰚱", 0, 16));
export const SearchSparkle20Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle20Regular", "󰘶", 1, 20));
export const SearchSparkle20Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle20Filled", "󰚲", 0, 20));
export const SearchSparkle24Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle24Regular", "󰘷", 1, 24));
export const SearchSparkle24Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle24Filled", "󰚳", 0, 24));
export const SearchSparkle28Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle28Regular", "󰘸", 1, 28));
export const SearchSparkle28Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle28Filled", "󰚴", 0, 28));
export const SearchSparkle32Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle32Regular", "󰘹", 1, 32));
export const SearchSparkle32Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle32Filled", "󰚵", 0, 32));
export const SearchSparkle32Light = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle32Light", "", 3, 32));
export const SearchSparkle48Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle48Regular", "󰘺", 1, 48));
export const SearchSparkle48Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSparkle48Filled", "󰚶", 0, 48));
