"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SearchSquareFilled = ( /*#__PURE__*/createFluentFontIcon("SearchSquareFilled", "", 2, undefined));
export const SearchSquareRegular = ( /*#__PURE__*/createFluentFontIcon("SearchSquareRegular", "", 2, undefined));
export const SearchSquare16Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSquare16Regular", "󰗌", 1, 16));
export const SearchSquare16Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSquare16Filled", "󰙅", 0, 16));
export const SearchSquare20Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSquare20Regular", "", 1, 20));
export const SearchSquare20Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSquare20Filled", "", 0, 20));
export const SearchSquare24Regular = ( /*#__PURE__*/createFluentFontIcon("SearchSquare24Regular", "", 1, 24));
export const SearchSquare24Filled = ( /*#__PURE__*/createFluentFontIcon("SearchSquare24Filled", "", 0, 24));
