"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SeatFilled = ( /*#__PURE__*/createFluentFontIcon("SeatFilled", "", 2, undefined));
export const SeatRegular = ( /*#__PURE__*/createFluentFontIcon("SeatRegular", "", 2, undefined));
export const Seat16Regular = ( /*#__PURE__*/createFluentFontIcon("Seat16Regular", "󰓙", 1, 16));
export const Seat16Filled = ( /*#__PURE__*/createFluentFontIcon("Seat16Filled", "󰕒", 0, 16));
export const Seat20Regular = ( /*#__PURE__*/createFluentFontIcon("Seat20Regular", "󰓚", 1, 20));
export const Seat20Filled = ( /*#__PURE__*/createFluentFontIcon("Seat20Filled", "󰕓", 0, 20));
export const Seat24Regular = ( /*#__PURE__*/createFluentFontIcon("Seat24Regular", "󰓛", 1, 24));
export const Seat24Filled = ( /*#__PURE__*/createFluentFontIcon("Seat24Filled", "󰕔", 0, 24));
