"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SelectAllOnFilled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOnFilled", "", 2, undefined));
export const SelectAllOnRegular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOnRegular", "", 2, undefined));
export const SelectAllOn16Regular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOn16Regular", "󰒹", 1, 16));
export const SelectAllOn16Filled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOn16Filled", "󰔲", 0, 16));
export const SelectAllOn20Regular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOn20Regular", "", 1, 20));
export const SelectAllOn20Filled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOn20Filled", "", 0, 20));
export const SelectAllOn24Regular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOn24Regular", "", 1, 24));
export const SelectAllOn24Filled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOn24Filled", "", 0, 24));
