"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SelectAllOffFilled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOffFilled", "", 2, undefined));
export const SelectAllOffRegular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOffRegular", "", 2, undefined));
export const SelectAllOff16Regular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOff16Regular", "󰒸", 1, 16));
export const SelectAllOff16Filled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOff16Filled", "󰔱", 0, 16));
export const SelectAllOff20Regular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOff20Regular", "", 1, 20));
export const SelectAllOff20Filled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOff20Filled", "", 0, 20));
export const SelectAllOff24Regular = ( /*#__PURE__*/createFluentFontIcon("SelectAllOff24Regular", "", 1, 24));
export const SelectAllOff24Filled = ( /*#__PURE__*/createFluentFontIcon("SelectAllOff24Filled", "", 0, 24));
