"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SendBeakerFilled = ( /*#__PURE__*/createFluentFontIcon("SendBeakerFilled", "", 2, undefined, { flipInRtl: true }));
export const SendBeakerRegular = ( /*#__PURE__*/createFluentFontIcon("SendBeakerRegular", "", 2, undefined, { flipInRtl: true }));
export const SendBeaker16Regular = ( /*#__PURE__*/createFluentFontIcon("SendBeaker16Regular", "󰃳", 1, 16, { flipInRtl: true }));
export const SendBeaker16Filled = ( /*#__PURE__*/createFluentFontIcon("SendBeaker16Filled", "󰃲", 0, 16, { flipInRtl: true }));
export const SendBeaker20Regular = ( /*#__PURE__*/createFluentFontIcon("SendBeaker20Regular", "󰃴", 1, 20, { flipInRtl: true }));
export const SendBeaker20Filled = ( /*#__PURE__*/createFluentFontIcon("SendBeaker20Filled", "󰃳", 0, 20, { flipInRtl: true }));
export const SendBeaker24Regular = ( /*#__PURE__*/createFluentFontIcon("SendBeaker24Regular", "󰃵", 1, 24, { flipInRtl: true }));
export const SendBeaker24Filled = ( /*#__PURE__*/createFluentFontIcon("SendBeaker24Filled", "󰃴", 0, 24, { flipInRtl: true }));
export const SendBeaker28Regular = ( /*#__PURE__*/createFluentFontIcon("SendBeaker28Regular", "󰃶", 1, 28, { flipInRtl: true }));
export const SendBeaker28Filled = ( /*#__PURE__*/createFluentFontIcon("SendBeaker28Filled", "󰃵", 0, 28, { flipInRtl: true }));
export const SendBeaker32Regular = ( /*#__PURE__*/createFluentFontIcon("SendBeaker32Regular", "󰃷", 1, 32, { flipInRtl: true }));
export const SendBeaker32Filled = ( /*#__PURE__*/createFluentFontIcon("SendBeaker32Filled", "󰃶", 0, 32, { flipInRtl: true }));
export const SendBeaker48Regular = ( /*#__PURE__*/createFluentFontIcon("SendBeaker48Regular", "󰃸", 1, 48, { flipInRtl: true }));
export const SendBeaker48Filled = ( /*#__PURE__*/createFluentFontIcon("SendBeaker48Filled", "󰃷", 0, 48, { flipInRtl: true }));
