"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SendPersonFilled = ( /*#__PURE__*/createFluentFontIcon("SendPersonFilled", "", 2, undefined, { flipInRtl: true }));
export const SendPersonRegular = ( /*#__PURE__*/createFluentFontIcon("SendPersonRegular", "", 2, undefined, { flipInRtl: true }));
export const SendPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("SendPerson16Regular", "󰘒", 1, 16, { flipInRtl: true }));
export const SendPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("SendPerson16Filled", "󰚎", 0, 16, { flipInRtl: true }));
export const SendPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("SendPerson20Regular", "󰘓", 1, 20, { flipInRtl: true }));
export const SendPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("SendPerson20Filled", "󰚏", 0, 20, { flipInRtl: true }));
export const SendPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("SendPerson24Regular", "󰘔", 1, 24, { flipInRtl: true }));
export const SendPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("SendPerson24Filled", "󰚐", 0, 24, { flipInRtl: true }));
