"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SettingsFilled = ( /*#__PURE__*/createFluentFontIcon("SettingsFilled", "", 2, undefined));
export const SettingsRegular = ( /*#__PURE__*/createFluentFontIcon("SettingsRegular", "", 2, undefined));
export const Settings16Regular = ( /*#__PURE__*/createFluentFontIcon("Settings16Regular", "", 1, 16));
export const Settings16Filled = ( /*#__PURE__*/createFluentFontIcon("Settings16Filled", "", 0, 16));
export const Settings20Regular = ( /*#__PURE__*/createFluentFontIcon("Settings20Regular", "", 1, 20));
export const Settings20Filled = ( /*#__PURE__*/createFluentFontIcon("Settings20Filled", "", 0, 20));
export const Settings24Regular = ( /*#__PURE__*/createFluentFontIcon("Settings24Regular", "", 1, 24));
export const Settings24Filled = ( /*#__PURE__*/createFluentFontIcon("Settings24Filled", "", 0, 24));
export const Settings28Regular = ( /*#__PURE__*/createFluentFontIcon("Settings28Regular", "", 1, 28));
export const Settings28Filled = ( /*#__PURE__*/createFluentFontIcon("Settings28Filled", "", 0, 28));
export const Settings32Regular = ( /*#__PURE__*/createFluentFontIcon("Settings32Regular", "", 1, 32));
export const Settings32Filled = ( /*#__PURE__*/createFluentFontIcon("Settings32Filled", "", 0, 32));
export const Settings32Light = ( /*#__PURE__*/createFluentFontIcon("Settings32Light", "", 3, 32));
export const Settings48Regular = ( /*#__PURE__*/createFluentFontIcon("Settings48Regular", "", 1, 48));
export const Settings48Filled = ( /*#__PURE__*/createFluentFontIcon("Settings48Filled", "", 0, 48));
