"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShapesFilled = ( /*#__PURE__*/createFluentFontIcon("ShapesFilled", "", 2, undefined));
export const ShapesRegular = ( /*#__PURE__*/createFluentFontIcon("ShapesRegular", "", 2, undefined));
export const Shapes16Regular = ( /*#__PURE__*/createFluentFontIcon("Shapes16Regular", "", 1, 16));
export const Shapes16Filled = ( /*#__PURE__*/createFluentFontIcon("Shapes16Filled", "", 0, 16));
export const Shapes20Regular = ( /*#__PURE__*/createFluentFontIcon("Shapes20Regular", "", 1, 20));
export const Shapes20Filled = ( /*#__PURE__*/createFluentFontIcon("Shapes20Filled", "", 0, 20));
export const Shapes24Regular = ( /*#__PURE__*/createFluentFontIcon("Shapes24Regular", "", 1, 24));
export const Shapes24Filled = ( /*#__PURE__*/createFluentFontIcon("Shapes24Filled", "", 0, 24));
export const Shapes28Regular = ( /*#__PURE__*/createFluentFontIcon("Shapes28Regular", "", 1, 28));
export const Shapes28Filled = ( /*#__PURE__*/createFluentFontIcon("Shapes28Filled", "", 0, 28));
export const Shapes32Regular = ( /*#__PURE__*/createFluentFontIcon("Shapes32Regular", "󰏃", 1, 32));
export const Shapes32Filled = ( /*#__PURE__*/createFluentFontIcon("Shapes32Filled", "󰏖", 0, 32));
export const Shapes48Regular = ( /*#__PURE__*/createFluentFontIcon("Shapes48Regular", "", 1, 48));
export const Shapes48Filled = ( /*#__PURE__*/createFluentFontIcon("Shapes48Filled", "", 0, 48));
