"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShapeExcludeFilled = ( /*#__PURE__*/createFluentFontIcon("ShapeExcludeFilled", "", 2, undefined));
export const ShapeExcludeRegular = ( /*#__PURE__*/createFluentFontIcon("ShapeExcludeRegular", "", 2, undefined));
export const ShapeExclude16Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeExclude16Regular", "", 1, 16));
export const ShapeExclude16Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeExclude16Filled", "", 0, 16));
export const ShapeExclude20Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeExclude20Regular", "", 1, 20));
export const ShapeExclude20Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeExclude20Filled", "", 0, 20));
export const ShapeExclude24Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeExclude24Regular", "", 1, 24));
export const ShapeExclude24Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeExclude24Filled", "", 0, 24));
