"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShapeOrganicFilled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganicFilled", "", 2, undefined));
export const ShapeOrganicRegular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganicRegular", "", 2, undefined));
export const ShapeOrganic16Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic16Regular", "󰎗", 1, 16));
export const ShapeOrganic16Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic16Filled", "󰎪", 0, 16));
export const ShapeOrganic20Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic20Regular", "󰎘", 1, 20));
export const ShapeOrganic20Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic20Filled", "󰎫", 0, 20));
export const ShapeOrganic24Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic24Regular", "󰎙", 1, 24));
export const ShapeOrganic24Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic24Filled", "󰎬", 0, 24));
export const ShapeOrganic28Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic28Regular", "󰎚", 1, 28));
export const ShapeOrganic28Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic28Filled", "󰎭", 0, 28));
export const ShapeOrganic32Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic32Regular", "󰎛", 1, 32));
export const ShapeOrganic32Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic32Filled", "󰎮", 0, 32));
export const ShapeOrganic48Regular = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic48Regular", "󰎜", 1, 48));
export const ShapeOrganic48Filled = ( /*#__PURE__*/createFluentFontIcon("ShapeOrganic48Filled", "󰎯", 0, 48));
