"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShareIosFilled = ( /*#__PURE__*/createFluentFontIcon("ShareIosFilled", "", 2, undefined));
export const ShareIosRegular = ( /*#__PURE__*/createFluentFontIcon("ShareIosRegular", "", 2, undefined));
export const ShareIos20Regular = ( /*#__PURE__*/createFluentFontIcon("ShareIos20Regular", "", 1, 20));
export const ShareIos20Filled = ( /*#__PURE__*/createFluentFontIcon("ShareIos20Filled", "", 0, 20));
export const ShareIos24Regular = ( /*#__PURE__*/createFluentFontIcon("ShareIos24Regular", "", 1, 24));
export const ShareIos24Filled = ( /*#__PURE__*/createFluentFontIcon("ShareIos24Filled", "", 0, 24));
export const ShareIos28Regular = ( /*#__PURE__*/createFluentFontIcon("ShareIos28Regular", "", 1, 28));
export const ShareIos28Filled = ( /*#__PURE__*/createFluentFontIcon("ShareIos28Filled", "", 0, 28));
export const ShareIos32Regular = ( /*#__PURE__*/createFluentFontIcon("ShareIos32Regular", "󰥕", 1, 32));
export const ShareIos32Filled = ( /*#__PURE__*/createFluentFontIcon("ShareIos32Filled", "󰧒", 0, 32));
export const ShareIos48Regular = ( /*#__PURE__*/createFluentFontIcon("ShareIos48Regular", "", 1, 48));
export const ShareIos48Filled = ( /*#__PURE__*/createFluentFontIcon("ShareIos48Filled", "", 0, 48));
