"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShieldDismissFilled = ( /*#__PURE__*/createFluentFontIcon("ShieldDismissFilled", "", 2, undefined));
export const ShieldDismissRegular = ( /*#__PURE__*/createFluentFontIcon("ShieldDismissRegular", "", 2, undefined));
export const ShieldDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldDismiss16Regular", "", 1, 16));
export const ShieldDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldDismiss16Filled", "", 0, 16));
export const ShieldDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldDismiss20Regular", "", 1, 20));
export const ShieldDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldDismiss20Filled", "", 0, 20));
export const ShieldDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldDismiss24Regular", "", 1, 24));
export const ShieldDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldDismiss24Filled", "", 0, 24));
