"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShieldErrorFilled = ( /*#__PURE__*/createFluentFontIcon("ShieldErrorFilled", "", 2, undefined));
export const ShieldErrorRegular = ( /*#__PURE__*/createFluentFontIcon("ShieldErrorRegular", "", 2, undefined));
export const ShieldError16Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldError16Regular", "", 1, 16));
export const ShieldError16Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldError16Filled", "", 0, 16));
export const ShieldError20Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldError20Regular", "", 1, 20));
export const ShieldError20Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldError20Filled", "", 0, 20));
export const ShieldError24Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldError24Regular", "", 1, 24));
export const ShieldError24Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldError24Filled", "", 0, 24));
export const ShieldError28Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldError28Regular", "󰧦", 1, 28));
export const ShieldError28Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldError28Filled", "󰩣", 0, 28));
export const ShieldError32Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldError32Regular", "󰧧", 1, 32));
export const ShieldError32Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldError32Filled", "󰩤", 0, 32));
export const ShieldError32Light = ( /*#__PURE__*/createFluentFontIcon("ShieldError32Light", "", 3, 32));
export const ShieldError48Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldError48Regular", "󰧨", 1, 48));
export const ShieldError48Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldError48Filled", "󰩥", 0, 48));
