"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShieldTaskFilled = ( /*#__PURE__*/createFluentFontIcon("ShieldTaskFilled", "", 2, undefined));
export const ShieldTaskRegular = ( /*#__PURE__*/createFluentFontIcon("ShieldTaskRegular", "", 2, undefined));
export const ShieldTask16Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldTask16Regular", "", 1, 16));
export const ShieldTask16Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldTask16Filled", "", 0, 16));
export const ShieldTask20Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldTask20Regular", "", 1, 20));
export const ShieldTask20Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldTask20Filled", "", 0, 20));
export const ShieldTask24Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldTask24Regular", "", 1, 24));
export const ShieldTask24Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldTask24Filled", "", 0, 24));
export const ShieldTask28Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldTask28Regular", "", 1, 28));
export const ShieldTask28Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldTask28Filled", "", 0, 28));
export const ShieldTask32Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldTask32Regular", "󰚄", 1, 32));
export const ShieldTask32Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldTask32Filled", "󰛿", 0, 32));
export const ShieldTask48Regular = ( /*#__PURE__*/createFluentFontIcon("ShieldTask48Regular", "", 1, 48));
export const ShieldTask48Filled = ( /*#__PURE__*/createFluentFontIcon("ShieldTask48Filled", "", 0, 48));
