"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShoppingBagAddFilled = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAddFilled", "", 2, undefined));
export const ShoppingBagAddRegular = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAddRegular", "", 2, undefined));
export const ShoppingBagAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAdd16Regular", "󰖕", 1, 16));
export const ShoppingBagAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAdd16Filled", "󰘎", 0, 16));
export const ShoppingBagAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAdd20Regular", "󰓸", 1, 20));
export const ShoppingBagAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAdd20Filled", "󰕱", 0, 20));
export const ShoppingBagAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAdd24Regular", "󰓹", 1, 24));
export const ShoppingBagAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("ShoppingBagAdd24Filled", "󰕲", 0, 24));
