"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ShowerheadFilled = ( /*#__PURE__*/createFluentFontIcon("ShowerheadFilled", "", 2, undefined));
export const ShowerheadRegular = ( /*#__PURE__*/createFluentFontIcon("ShowerheadRegular", "", 2, undefined));
export const Showerhead20Regular = ( /*#__PURE__*/createFluentFontIcon("Showerhead20Regular", "", 1, 20));
export const Showerhead20Filled = ( /*#__PURE__*/createFluentFontIcon("Showerhead20Filled", "", 0, 20));
export const Showerhead24Regular = ( /*#__PURE__*/createFluentFontIcon("Showerhead24Regular", "", 1, 24));
export const Showerhead24Filled = ( /*#__PURE__*/createFluentFontIcon("Showerhead24Filled", "", 0, 24));
export const Showerhead32Regular = ( /*#__PURE__*/createFluentFontIcon("Showerhead32Regular", "", 1, 32));
export const Showerhead32Filled = ( /*#__PURE__*/createFluentFontIcon("Showerhead32Filled", "", 0, 32));
