"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SignatureFilled = ( /*#__PURE__*/createFluentFontIcon("SignatureFilled", "", 2, undefined));
export const SignatureRegular = ( /*#__PURE__*/createFluentFontIcon("SignatureRegular", "", 2, undefined));
export const Signature16Regular = ( /*#__PURE__*/createFluentFontIcon("Signature16Regular", "", 1, 16));
export const Signature16Filled = ( /*#__PURE__*/createFluentFontIcon("Signature16Filled", "", 0, 16));
export const Signature20Regular = ( /*#__PURE__*/createFluentFontIcon("Signature20Regular", "", 1, 20));
export const Signature20Filled = ( /*#__PURE__*/createFluentFontIcon("Signature20Filled", "", 0, 20));
export const Signature24Regular = ( /*#__PURE__*/createFluentFontIcon("Signature24Regular", "", 1, 24));
export const Signature24Filled = ( /*#__PURE__*/createFluentFontIcon("Signature24Filled", "", 0, 24));
export const Signature28Regular = ( /*#__PURE__*/createFluentFontIcon("Signature28Regular", "", 1, 28));
export const Signature28Filled = ( /*#__PURE__*/createFluentFontIcon("Signature28Filled", "", 0, 28));
export const Signature32Regular = ( /*#__PURE__*/createFluentFontIcon("Signature32Regular", "󰈽", 1, 32));
export const Signature32Filled = ( /*#__PURE__*/createFluentFontIcon("Signature32Filled", "󰉐", 0, 32));
export const Signature32Light = ( /*#__PURE__*/createFluentFontIcon("Signature32Light", "", 3, 32));
