"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SlashForwardFilled = ( /*#__PURE__*/createFluentFontIcon("SlashForwardFilled", "", 2, undefined));
export const SlashForwardRegular = ( /*#__PURE__*/createFluentFontIcon("SlashForwardRegular", "", 2, undefined));
export const SlashForward12Regular = ( /*#__PURE__*/createFluentFontIcon("SlashForward12Regular", "󰂜", 1, 12));
export const SlashForward12Filled = ( /*#__PURE__*/createFluentFontIcon("SlashForward12Filled", "󰂛", 0, 12));
export const SlashForward16Regular = ( /*#__PURE__*/createFluentFontIcon("SlashForward16Regular", "󰂝", 1, 16));
export const SlashForward16Filled = ( /*#__PURE__*/createFluentFontIcon("SlashForward16Filled", "󰂜", 0, 16));
export const SlashForward20Regular = ( /*#__PURE__*/createFluentFontIcon("SlashForward20Regular", "󰂞", 1, 20));
export const SlashForward20Filled = ( /*#__PURE__*/createFluentFontIcon("SlashForward20Filled", "󰂝", 0, 20));
export const SlashForward24Regular = ( /*#__PURE__*/createFluentFontIcon("SlashForward24Regular", "󰂟", 1, 24));
export const SlashForward24Filled = ( /*#__PURE__*/createFluentFontIcon("SlashForward24Filled", "󰂞", 0, 24));
