"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SlideSearchFilled = ( /*#__PURE__*/createFluentFontIcon("SlideSearchFilled", "", 2, undefined));
export const SlideSearchRegular = ( /*#__PURE__*/createFluentFontIcon("SlideSearchRegular", "", 2, undefined));
export const SlideSearch16Regular = ( /*#__PURE__*/createFluentFontIcon("SlideSearch16Regular", "󰐖", 1, 16));
export const SlideSearch16Filled = ( /*#__PURE__*/createFluentFontIcon("SlideSearch16Filled", "󰐩", 0, 16));
export const SlideSearch20Regular = ( /*#__PURE__*/createFluentFontIcon("SlideSearch20Regular", "", 1, 20));
export const SlideSearch20Filled = ( /*#__PURE__*/createFluentFontIcon("SlideSearch20Filled", "", 0, 20));
export const SlideSearch24Regular = ( /*#__PURE__*/createFluentFontIcon("SlideSearch24Regular", "", 1, 24));
export const SlideSearch24Filled = ( /*#__PURE__*/createFluentFontIcon("SlideSearch24Filled", "", 0, 24));
export const SlideSearch28Regular = ( /*#__PURE__*/createFluentFontIcon("SlideSearch28Regular", "", 1, 28));
export const SlideSearch28Filled = ( /*#__PURE__*/createFluentFontIcon("SlideSearch28Filled", "", 0, 28));
export const SlideSearch32Regular = ( /*#__PURE__*/createFluentFontIcon("SlideSearch32Regular", "󰐗", 1, 32));
export const SlideSearch32Filled = ( /*#__PURE__*/createFluentFontIcon("SlideSearch32Filled", "󰐪", 0, 32));
