"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SlideEraserFilled = ( /*#__PURE__*/createFluentFontIcon("SlideEraserFilled", "", 2, undefined));
export const SlideEraserRegular = ( /*#__PURE__*/createFluentFontIcon("SlideEraserRegular", "", 2, undefined));
export const SlideEraser16Regular = ( /*#__PURE__*/createFluentFontIcon("SlideEraser16Regular", "", 1, 16));
export const SlideEraser16Filled = ( /*#__PURE__*/createFluentFontIcon("SlideEraser16Filled", "", 0, 16));
export const SlideEraser20Regular = ( /*#__PURE__*/createFluentFontIcon("SlideEraser20Regular", "", 1, 20));
export const SlideEraser20Filled = ( /*#__PURE__*/createFluentFontIcon("SlideEraser20Filled", "", 0, 20));
export const SlideEraser24Regular = ( /*#__PURE__*/createFluentFontIcon("SlideEraser24Regular", "", 1, 24));
export const SlideEraser24Filled = ( /*#__PURE__*/createFluentFontIcon("SlideEraser24Filled", "", 0, 24));
