"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SlideTextFilled = ( /*#__PURE__*/createFluentFontIcon("SlideTextFilled", "", 2, undefined, { flipInRtl: true }));
export const SlideTextRegular = ( /*#__PURE__*/createFluentFontIcon("SlideTextRegular", "", 2, undefined, { flipInRtl: true }));
export const SlideText16Regular = ( /*#__PURE__*/createFluentFontIcon("SlideText16Regular", "", 1, 16, { flipInRtl: true }));
export const SlideText16Filled = ( /*#__PURE__*/createFluentFontIcon("SlideText16Filled", "", 0, 16, { flipInRtl: true }));
export const SlideText20Regular = ( /*#__PURE__*/createFluentFontIcon("SlideText20Regular", "", 1, 20, { flipInRtl: true }));
export const SlideText20Filled = ( /*#__PURE__*/createFluentFontIcon("SlideText20Filled", "", 0, 20, { flipInRtl: true }));
export const SlideText24Regular = ( /*#__PURE__*/createFluentFontIcon("SlideText24Regular", "", 1, 24, { flipInRtl: true }));
export const SlideText24Filled = ( /*#__PURE__*/createFluentFontIcon("SlideText24Filled", "", 0, 24, { flipInRtl: true }));
export const SlideText28Regular = ( /*#__PURE__*/createFluentFontIcon("SlideText28Regular", "", 1, 28, { flipInRtl: true }));
export const SlideText28Filled = ( /*#__PURE__*/createFluentFontIcon("SlideText28Filled", "", 0, 28, { flipInRtl: true }));
export const SlideText48Regular = ( /*#__PURE__*/createFluentFontIcon("SlideText48Regular", "", 1, 48, { flipInRtl: true }));
export const SlideText48Filled = ( /*#__PURE__*/createFluentFontIcon("SlideText48Filled", "", 0, 48, { flipInRtl: true }));
