"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SlideRecordFilled = ( /*#__PURE__*/createFluentFontIcon("SlideRecordFilled", "", 2, undefined));
export const SlideRecordRegular = ( /*#__PURE__*/createFluentFontIcon("SlideRecordRegular", "", 2, undefined));
export const SlideRecord16Regular = ( /*#__PURE__*/createFluentFontIcon("SlideRecord16Regular", "󰄿", 1, 16));
export const SlideRecord16Filled = ( /*#__PURE__*/createFluentFontIcon("SlideRecord16Filled", "󰄾", 0, 16));
export const SlideRecord20Regular = ( /*#__PURE__*/createFluentFontIcon("SlideRecord20Regular", "󰅀", 1, 20));
export const SlideRecord20Filled = ( /*#__PURE__*/createFluentFontIcon("SlideRecord20Filled", "󰄿", 0, 20));
export const SlideRecord24Regular = ( /*#__PURE__*/createFluentFontIcon("SlideRecord24Regular", "󰅁", 1, 24));
export const SlideRecord24Filled = ( /*#__PURE__*/createFluentFontIcon("SlideRecord24Filled", "󰅀", 0, 24));
export const SlideRecord28Regular = ( /*#__PURE__*/createFluentFontIcon("SlideRecord28Regular", "󰅂", 1, 28));
export const SlideRecord28Filled = ( /*#__PURE__*/createFluentFontIcon("SlideRecord28Filled", "󰅁", 0, 28));
export const SlideRecord48Regular = ( /*#__PURE__*/createFluentFontIcon("SlideRecord48Regular", "󰅃", 1, 48));
export const SlideRecord48Filled = ( /*#__PURE__*/createFluentFontIcon("SlideRecord48Filled", "󰅂", 0, 48));
