"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SlideAddFilled = ( /*#__PURE__*/createFluentFontIcon("SlideAddFilled", "", 2, undefined));
export const SlideAddRegular = ( /*#__PURE__*/createFluentFontIcon("SlideAddRegular", "", 2, undefined));
export const SlideAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("SlideAdd16Regular", "", 1, 16));
export const SlideAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("SlideAdd16Filled", "", 0, 16));
export const SlideAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("SlideAdd20Regular", "", 1, 20));
export const SlideAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("SlideAdd20Filled", "", 0, 20));
export const SlideAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("SlideAdd24Regular", "", 1, 24));
export const SlideAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("SlideAdd24Filled", "", 0, 24));
export const SlideAdd28Regular = ( /*#__PURE__*/createFluentFontIcon("SlideAdd28Regular", "", 1, 28));
export const SlideAdd28Filled = ( /*#__PURE__*/createFluentFontIcon("SlideAdd28Filled", "", 0, 28));
export const SlideAdd32Regular = ( /*#__PURE__*/createFluentFontIcon("SlideAdd32Regular", "", 1, 32));
export const SlideAdd32Filled = ( /*#__PURE__*/createFluentFontIcon("SlideAdd32Filled", "", 0, 32));
export const SlideAdd48Regular = ( /*#__PURE__*/createFluentFontIcon("SlideAdd48Regular", "", 1, 48));
export const SlideAdd48Filled = ( /*#__PURE__*/createFluentFontIcon("SlideAdd48Filled", "", 0, 48));
