"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SnoozeFilled = ( /*#__PURE__*/createFluentFontIcon("SnoozeFilled", "", 2, undefined));
export const SnoozeRegular = ( /*#__PURE__*/createFluentFontIcon("SnoozeRegular", "", 2, undefined));
export const Snooze16Regular = ( /*#__PURE__*/createFluentFontIcon("Snooze16Regular", "", 1, 16));
export const Snooze16Filled = ( /*#__PURE__*/createFluentFontIcon("Snooze16Filled", "", 0, 16));
export const Snooze20Regular = ( /*#__PURE__*/createFluentFontIcon("Snooze20Regular", "", 1, 20));
export const Snooze20Filled = ( /*#__PURE__*/createFluentFontIcon("Snooze20Filled", "", 0, 20));
export const Snooze24Regular = ( /*#__PURE__*/createFluentFontIcon("Snooze24Regular", "", 1, 24));
export const Snooze24Filled = ( /*#__PURE__*/createFluentFontIcon("Snooze24Filled", "", 0, 24));
