"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SpeakerOffFilled = ( /*#__PURE__*/createFluentFontIcon("SpeakerOffFilled", "", 2, undefined));
export const SpeakerOffRegular = ( /*#__PURE__*/createFluentFontIcon("SpeakerOffRegular", "", 2, undefined));
export const SpeakerOff16Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff16Regular", "", 1, 16));
export const SpeakerOff16Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff16Filled", "", 0, 16));
export const SpeakerOff20Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff20Regular", "", 1, 20));
export const SpeakerOff20Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff20Filled", "", 0, 20));
export const SpeakerOff24Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff24Regular", "", 1, 24));
export const SpeakerOff24Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff24Filled", "", 0, 24));
export const SpeakerOff28Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff28Regular", "", 1, 28));
export const SpeakerOff28Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff28Filled", "", 0, 28));
export const SpeakerOff48Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff48Regular", "", 1, 48));
export const SpeakerOff48Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerOff48Filled", "", 0, 48));
