"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SpeakerMuteFilled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMuteFilled", "", 2, undefined));
export const SpeakerMuteRegular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMuteRegular", "", 2, undefined));
export const SpeakerMute16Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute16Regular", "", 1, 16));
export const SpeakerMute16Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute16Filled", "", 0, 16));
export const SpeakerMute20Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute20Regular", "", 1, 20));
export const SpeakerMute20Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute20Filled", "", 0, 20));
export const SpeakerMute24Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute24Regular", "", 1, 24));
export const SpeakerMute24Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute24Filled", "", 0, 24));
export const SpeakerMute28Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute28Regular", "", 1, 28));
export const SpeakerMute28Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute28Filled", "", 0, 28));
export const SpeakerMute32Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute32Regular", "󰈾", 1, 32));
export const SpeakerMute32Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute32Filled", "󰉑", 0, 32));
export const SpeakerMute32Light = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute32Light", "", 3, 32));
export const SpeakerMute48Regular = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute48Regular", "", 1, 48));
export const SpeakerMute48Filled = ( /*#__PURE__*/createFluentFontIcon("SpeakerMute48Filled", "", 0, 48));
