"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SquareShadowFilled = ( /*#__PURE__*/createFluentFontIcon("SquareShadowFilled", "", 2, undefined));
export const SquareShadowRegular = ( /*#__PURE__*/createFluentFontIcon("SquareShadowRegular", "", 2, undefined));
export const SquareShadow12Regular = ( /*#__PURE__*/createFluentFontIcon("SquareShadow12Regular", "", 1, 12));
export const SquareShadow12Filled = ( /*#__PURE__*/createFluentFontIcon("SquareShadow12Filled", "", 0, 12));
export const SquareShadow16Regular = ( /*#__PURE__*/createFluentFontIcon("SquareShadow16Regular", "󰪈", 1, 16));
export const SquareShadow16Filled = ( /*#__PURE__*/createFluentFontIcon("SquareShadow16Filled", "󰬄", 0, 16));
export const SquareShadow20Regular = ( /*#__PURE__*/createFluentFontIcon("SquareShadow20Regular", "", 1, 20));
export const SquareShadow20Filled = ( /*#__PURE__*/createFluentFontIcon("SquareShadow20Filled", "", 0, 20));
export const SquareShadow24Regular = ( /*#__PURE__*/createFluentFontIcon("SquareShadow24Regular", "󰪉", 1, 24));
export const SquareShadow24Filled = ( /*#__PURE__*/createFluentFontIcon("SquareShadow24Filled", "󰬅", 0, 24));
