"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SquareHintFilled = ( /*#__PURE__*/createFluentFontIcon("SquareHintFilled", "", 2, undefined));
export const SquareHintRegular = ( /*#__PURE__*/createFluentFontIcon("SquareHintRegular", "", 2, undefined));
export const SquareHint16Regular = ( /*#__PURE__*/createFluentFontIcon("SquareHint16Regular", "", 1, 16));
export const SquareHint16Filled = ( /*#__PURE__*/createFluentFontIcon("SquareHint16Filled", "", 0, 16));
export const SquareHint20Regular = ( /*#__PURE__*/createFluentFontIcon("SquareHint20Regular", "", 1, 20));
export const SquareHint20Filled = ( /*#__PURE__*/createFluentFontIcon("SquareHint20Filled", "", 0, 20));
export const SquareHint24Regular = ( /*#__PURE__*/createFluentFontIcon("SquareHint24Regular", "", 1, 24));
export const SquareHint24Filled = ( /*#__PURE__*/createFluentFontIcon("SquareHint24Filled", "", 0, 24));
export const SquareHint28Regular = ( /*#__PURE__*/createFluentFontIcon("SquareHint28Regular", "", 1, 28));
export const SquareHint28Filled = ( /*#__PURE__*/createFluentFontIcon("SquareHint28Filled", "", 0, 28));
export const SquareHint32Regular = ( /*#__PURE__*/createFluentFontIcon("SquareHint32Regular", "", 1, 32));
export const SquareHint32Filled = ( /*#__PURE__*/createFluentFontIcon("SquareHint32Filled", "", 0, 32));
export const SquareHint48Regular = ( /*#__PURE__*/createFluentFontIcon("SquareHint48Regular", "", 1, 48));
export const SquareHint48Filled = ( /*#__PURE__*/createFluentFontIcon("SquareHint48Filled", "", 0, 48));
