"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const StarHalfFilled = ( /*#__PURE__*/createFluentFontIcon("StarHalfFilled", "", 2, undefined));
export const StarHalfRegular = ( /*#__PURE__*/createFluentFontIcon("StarHalfRegular", "", 2, undefined));
export const StarHalf12Regular = ( /*#__PURE__*/createFluentFontIcon("StarHalf12Regular", "", 1, 12));
export const StarHalf12Filled = ( /*#__PURE__*/createFluentFontIcon("StarHalf12Filled", "", 0, 12));
export const StarHalf16Regular = ( /*#__PURE__*/createFluentFontIcon("StarHalf16Regular", "", 1, 16));
export const StarHalf16Filled = ( /*#__PURE__*/createFluentFontIcon("StarHalf16Filled", "", 0, 16));
export const StarHalf20Regular = ( /*#__PURE__*/createFluentFontIcon("StarHalf20Regular", "", 1, 20));
export const StarHalf20Filled = ( /*#__PURE__*/createFluentFontIcon("StarHalf20Filled", "", 0, 20));
export const StarHalf24Regular = ( /*#__PURE__*/createFluentFontIcon("StarHalf24Regular", "", 1, 24));
export const StarHalf24Filled = ( /*#__PURE__*/createFluentFontIcon("StarHalf24Filled", "", 0, 24));
export const StarHalf28Regular = ( /*#__PURE__*/createFluentFontIcon("StarHalf28Regular", "", 1, 28));
export const StarHalf28Filled = ( /*#__PURE__*/createFluentFontIcon("StarHalf28Filled", "", 0, 28));
