"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const StopFilled = ( /*#__PURE__*/createFluentFontIcon("StopFilled", "", 2, undefined));
export const StopRegular = ( /*#__PURE__*/createFluentFontIcon("StopRegular", "", 2, undefined));
export const Stop16Regular = ( /*#__PURE__*/createFluentFontIcon("Stop16Regular", "", 1, 16));
export const Stop16Filled = ( /*#__PURE__*/createFluentFontIcon("Stop16Filled", "", 0, 16));
export const Stop20Regular = ( /*#__PURE__*/createFluentFontIcon("Stop20Regular", "", 1, 20));
export const Stop20Filled = ( /*#__PURE__*/createFluentFontIcon("Stop20Filled", "", 0, 20));
export const Stop24Regular = ( /*#__PURE__*/createFluentFontIcon("Stop24Regular", "", 1, 24));
export const Stop24Filled = ( /*#__PURE__*/createFluentFontIcon("Stop24Filled", "", 0, 24));
