"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const StorageFilled = ( /*#__PURE__*/createFluentFontIcon("StorageFilled", "", 2, undefined));
export const StorageRegular = ( /*#__PURE__*/createFluentFontIcon("StorageRegular", "", 2, undefined));
export const Storage16Regular = ( /*#__PURE__*/createFluentFontIcon("Storage16Regular", "󰕄", 1, 16));
export const Storage16Filled = ( /*#__PURE__*/createFluentFontIcon("Storage16Filled", "󰖽", 0, 16));
export const Storage20Regular = ( /*#__PURE__*/createFluentFontIcon("Storage20Regular", "", 1, 20));
export const Storage20Filled = ( /*#__PURE__*/createFluentFontIcon("Storage20Filled", "", 0, 20));
export const Storage24Regular = ( /*#__PURE__*/createFluentFontIcon("Storage24Regular", "", 1, 24));
export const Storage24Filled = ( /*#__PURE__*/createFluentFontIcon("Storage24Filled", "", 0, 24));
export const Storage28Regular = ( /*#__PURE__*/createFluentFontIcon("Storage28Regular", "󰕅", 1, 28));
export const Storage28Filled = ( /*#__PURE__*/createFluentFontIcon("Storage28Filled", "󰖾", 0, 28));
export const Storage32Regular = ( /*#__PURE__*/createFluentFontIcon("Storage32Regular", "󰕆", 1, 32));
export const Storage32Filled = ( /*#__PURE__*/createFluentFontIcon("Storage32Filled", "󰖿", 0, 32));
export const Storage48Regular = ( /*#__PURE__*/createFluentFontIcon("Storage48Regular", "󰕇", 1, 48));
export const Storage48Filled = ( /*#__PURE__*/createFluentFontIcon("Storage48Filled", "󰗀", 0, 48));
