"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const StreamFilled = ( /*#__PURE__*/createFluentFontIcon("StreamFilled", "", 2, undefined));
export const StreamRegular = ( /*#__PURE__*/createFluentFontIcon("StreamRegular", "", 2, undefined));
export const Stream20Regular = ( /*#__PURE__*/createFluentFontIcon("Stream20Regular", "", 1, 20));
export const Stream20Filled = ( /*#__PURE__*/createFluentFontIcon("Stream20Filled", "", 0, 20));
export const Stream24Regular = ( /*#__PURE__*/createFluentFontIcon("Stream24Regular", "", 1, 24));
export const Stream24Filled = ( /*#__PURE__*/createFluentFontIcon("Stream24Filled", "", 0, 24));
export const Stream32Regular = ( /*#__PURE__*/createFluentFontIcon("Stream32Regular", "󰅊", 1, 32));
export const Stream32Filled = ( /*#__PURE__*/createFluentFontIcon("Stream32Filled", "󰅉", 0, 32));
export const Stream48Regular = ( /*#__PURE__*/createFluentFontIcon("Stream48Regular", "󰉼", 1, 48));
export const Stream48Filled = ( /*#__PURE__*/createFluentFontIcon("Stream48Filled", "󰊏", 0, 48));
