"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SubtractSquareFilled = ( /*#__PURE__*/createFluentFontIcon("SubtractSquareFilled", "", 2, undefined));
export const SubtractSquareRegular = ( /*#__PURE__*/createFluentFontIcon("SubtractSquareRegular", "", 2, undefined));
export const SubtractSquare16Regular = ( /*#__PURE__*/createFluentFontIcon("SubtractSquare16Regular", "󰅋", 1, 16));
export const SubtractSquare16Filled = ( /*#__PURE__*/createFluentFontIcon("SubtractSquare16Filled", "󰅊", 0, 16));
export const SubtractSquare20Regular = ( /*#__PURE__*/createFluentFontIcon("SubtractSquare20Regular", "", 1, 20));
export const SubtractSquare20Filled = ( /*#__PURE__*/createFluentFontIcon("SubtractSquare20Filled", "", 0, 20));
export const SubtractSquare24Regular = ( /*#__PURE__*/createFluentFontIcon("SubtractSquare24Regular", "", 1, 24));
export const SubtractSquare24Filled = ( /*#__PURE__*/createFluentFontIcon("SubtractSquare24Filled", "", 0, 24));
