"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const SwimmingPoolFilled = ( /*#__PURE__*/createFluentFontIcon("SwimmingPoolFilled", "", 2, undefined));
export const SwimmingPoolRegular = ( /*#__PURE__*/createFluentFontIcon("SwimmingPoolRegular", "", 2, undefined));
export const SwimmingPool20Regular = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool20Regular", "", 1, 20));
export const SwimmingPool20Filled = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool20Filled", "", 0, 20));
export const SwimmingPool24Regular = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool24Regular", "", 1, 24));
export const SwimmingPool24Filled = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool24Filled", "", 0, 24));
export const SwimmingPool32Regular = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool32Regular", "", 1, 32));
export const SwimmingPool32Filled = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool32Filled", "", 0, 32));
export const SwimmingPool48Regular = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool48Regular", "", 1, 48));
export const SwimmingPool48Filled = ( /*#__PURE__*/createFluentFontIcon("SwimmingPool48Filled", "", 0, 48));
