"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TabGroupFilled = ( /*#__PURE__*/createFluentFontIcon("TabGroupFilled", "", 2, undefined));
export const TabGroupRegular = ( /*#__PURE__*/createFluentFontIcon("TabGroupRegular", "", 2, undefined));
export const TabGroup16Regular = ( /*#__PURE__*/createFluentFontIcon("TabGroup16Regular", "󰖹", 1, 16));
export const TabGroup16Filled = ( /*#__PURE__*/createFluentFontIcon("TabGroup16Filled", "󰘲", 0, 16));
export const TabGroup20Regular = ( /*#__PURE__*/createFluentFontIcon("TabGroup20Regular", "󰖺", 1, 20));
export const TabGroup20Filled = ( /*#__PURE__*/createFluentFontIcon("TabGroup20Filled", "󰘳", 0, 20));
export const TabGroup24Regular = ( /*#__PURE__*/createFluentFontIcon("TabGroup24Regular", "󰖻", 1, 24));
export const TabGroup24Filled = ( /*#__PURE__*/createFluentFontIcon("TabGroup24Filled", "󰘴", 0, 24));
