"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TabAddFilled = ( /*#__PURE__*/createFluentFontIcon("TabAddFilled", "", 2, undefined));
export const TabAddRegular = ( /*#__PURE__*/createFluentFontIcon("TabAddRegular", "", 2, undefined));
export const TabAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("TabAdd20Regular", "", 1, 20));
export const TabAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("TabAdd20Filled", "", 0, 20));
export const TabAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("TabAdd24Regular", "", 1, 24));
export const TabAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("TabAdd24Filled", "", 0, 24));
export const TabAdd32Regular = ( /*#__PURE__*/createFluentFontIcon("TabAdd32Regular", "󰛉", 1, 32));
export const TabAdd32Filled = ( /*#__PURE__*/createFluentFontIcon("TabAdd32Filled", "󰝆", 0, 32));
export const TabAdd32Light = ( /*#__PURE__*/createFluentFontIcon("TabAdd32Light", "", 3, 32));
