"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TabDesktopFilled = ( /*#__PURE__*/createFluentFontIcon("TabDesktopFilled", "", 2, undefined));
export const TabDesktopRegular = ( /*#__PURE__*/createFluentFontIcon("TabDesktopRegular", "", 2, undefined));
export const TabDesktop16Regular = ( /*#__PURE__*/createFluentFontIcon("TabDesktop16Regular", "", 1, 16));
export const TabDesktop16Filled = ( /*#__PURE__*/createFluentFontIcon("TabDesktop16Filled", "", 0, 16));
export const TabDesktop20Regular = ( /*#__PURE__*/createFluentFontIcon("TabDesktop20Regular", "", 1, 20));
export const TabDesktop20Filled = ( /*#__PURE__*/createFluentFontIcon("TabDesktop20Filled", "", 0, 20));
export const TabDesktop24Regular = ( /*#__PURE__*/createFluentFontIcon("TabDesktop24Regular", "", 1, 24));
export const TabDesktop24Filled = ( /*#__PURE__*/createFluentFontIcon("TabDesktop24Filled", "", 0, 24));
export const TabDesktop28Regular = ( /*#__PURE__*/createFluentFontIcon("TabDesktop28Regular", "󰈿", 1, 28));
export const TabDesktop28Filled = ( /*#__PURE__*/createFluentFontIcon("TabDesktop28Filled", "󰉒", 0, 28));
