"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TabFilled = ( /*#__PURE__*/createFluentFontIcon("TabFilled", "", 2, undefined));
export const TabRegular = ( /*#__PURE__*/createFluentFontIcon("TabRegular", "", 2, undefined));
export const Tab16Regular = ( /*#__PURE__*/createFluentFontIcon("Tab16Regular", "", 1, 16));
export const Tab16Filled = ( /*#__PURE__*/createFluentFontIcon("Tab16Filled", "", 0, 16));
export const Tab20Regular = ( /*#__PURE__*/createFluentFontIcon("Tab20Regular", "", 1, 20));
export const Tab20Filled = ( /*#__PURE__*/createFluentFontIcon("Tab20Filled", "", 0, 20));
export const Tab24Regular = ( /*#__PURE__*/createFluentFontIcon("Tab24Regular", "", 1, 24));
export const Tab24Filled = ( /*#__PURE__*/createFluentFontIcon("Tab24Filled", "", 0, 24));
export const Tab28Regular = ( /*#__PURE__*/createFluentFontIcon("Tab28Regular", "", 1, 28));
export const Tab28Filled = ( /*#__PURE__*/createFluentFontIcon("Tab28Filled", "", 0, 28));
