"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TableSimpleFilled = ( /*#__PURE__*/createFluentFontIcon("TableSimpleFilled", "", 2, undefined));
export const TableSimpleRegular = ( /*#__PURE__*/createFluentFontIcon("TableSimpleRegular", "", 2, undefined));
export const TableSimple16Regular = ( /*#__PURE__*/createFluentFontIcon("TableSimple16Regular", "", 1, 16));
export const TableSimple16Filled = ( /*#__PURE__*/createFluentFontIcon("TableSimple16Filled", "", 0, 16));
export const TableSimple20Regular = ( /*#__PURE__*/createFluentFontIcon("TableSimple20Regular", "", 1, 20));
export const TableSimple20Filled = ( /*#__PURE__*/createFluentFontIcon("TableSimple20Filled", "", 0, 20));
export const TableSimple24Regular = ( /*#__PURE__*/createFluentFontIcon("TableSimple24Regular", "", 1, 24));
export const TableSimple24Filled = ( /*#__PURE__*/createFluentFontIcon("TableSimple24Filled", "", 0, 24));
export const TableSimple28Regular = ( /*#__PURE__*/createFluentFontIcon("TableSimple28Regular", "", 1, 28));
export const TableSimple28Filled = ( /*#__PURE__*/createFluentFontIcon("TableSimple28Filled", "", 0, 28));
export const TableSimple32Regular = ( /*#__PURE__*/createFluentFontIcon("TableSimple32Regular", "󰅍", 1, 32));
export const TableSimple32Filled = ( /*#__PURE__*/createFluentFontIcon("TableSimple32Filled", "󰅌", 0, 32));
export const TableSimple32Light = ( /*#__PURE__*/createFluentFontIcon("TableSimple32Light", "", 3, 32));
export const TableSimple48Regular = ( /*#__PURE__*/createFluentFontIcon("TableSimple48Regular", "", 1, 48));
export const TableSimple48Filled = ( /*#__PURE__*/createFluentFontIcon("TableSimple48Filled", "", 0, 48));
