"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TableSwitchFilled = ( /*#__PURE__*/createFluentFontIcon("TableSwitchFilled", "", 2, undefined));
export const TableSwitchRegular = ( /*#__PURE__*/createFluentFontIcon("TableSwitchRegular", "", 2, undefined));
export const TableSwitch16Regular = ( /*#__PURE__*/createFluentFontIcon("TableSwitch16Regular", "", 1, 16));
export const TableSwitch16Filled = ( /*#__PURE__*/createFluentFontIcon("TableSwitch16Filled", "", 0, 16));
export const TableSwitch20Regular = ( /*#__PURE__*/createFluentFontIcon("TableSwitch20Regular", "", 1, 20));
export const TableSwitch20Filled = ( /*#__PURE__*/createFluentFontIcon("TableSwitch20Filled", "", 0, 20));
export const TableSwitch24Regular = ( /*#__PURE__*/createFluentFontIcon("TableSwitch24Regular", "", 1, 24));
export const TableSwitch24Filled = ( /*#__PURE__*/createFluentFontIcon("TableSwitch24Filled", "", 0, 24));
export const TableSwitch28Regular = ( /*#__PURE__*/createFluentFontIcon("TableSwitch28Regular", "", 1, 28));
export const TableSwitch28Filled = ( /*#__PURE__*/createFluentFontIcon("TableSwitch28Filled", "", 0, 28));
