"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TableCursorFilled = ( /*#__PURE__*/createFluentFontIcon("TableCursorFilled", "", 2, undefined));
export const TableCursorRegular = ( /*#__PURE__*/createFluentFontIcon("TableCursorRegular", "", 2, undefined));
export const TableCursor16Regular = ( /*#__PURE__*/createFluentFontIcon("TableCursor16Regular", "󰘜", 1, 16));
export const TableCursor16Filled = ( /*#__PURE__*/createFluentFontIcon("TableCursor16Filled", "󰚘", 0, 16));
export const TableCursor20Regular = ( /*#__PURE__*/createFluentFontIcon("TableCursor20Regular", "󰘝", 1, 20));
export const TableCursor20Filled = ( /*#__PURE__*/createFluentFontIcon("TableCursor20Filled", "󰚙", 0, 20));
export const TableCursor24Regular = ( /*#__PURE__*/createFluentFontIcon("TableCursor24Regular", "󰘞", 1, 24));
export const TableCursor24Filled = ( /*#__PURE__*/createFluentFontIcon("TableCursor24Filled", "󰚚", 0, 24));
