"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TableDismissFilled = ( /*#__PURE__*/createFluentFontIcon("TableDismissFilled", "", 2, undefined));
export const TableDismissRegular = ( /*#__PURE__*/createFluentFontIcon("TableDismissRegular", "", 2, undefined));
export const TableDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("TableDismiss16Regular", "", 1, 16));
export const TableDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("TableDismiss16Filled", "", 0, 16));
export const TableDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("TableDismiss20Regular", "", 1, 20));
export const TableDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("TableDismiss20Filled", "", 0, 20));
export const TableDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("TableDismiss24Regular", "", 1, 24));
export const TableDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("TableDismiss24Filled", "", 0, 24));
export const TableDismiss28Regular = ( /*#__PURE__*/createFluentFontIcon("TableDismiss28Regular", "", 1, 28));
export const TableDismiss28Filled = ( /*#__PURE__*/createFluentFontIcon("TableDismiss28Filled", "", 0, 28));
export const TableDismiss32Light = ( /*#__PURE__*/createFluentFontIcon("TableDismiss32Light", "", 3, 32));
