"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TableAddFilled = ( /*#__PURE__*/createFluentFontIcon("TableAddFilled", "", 2, undefined));
export const TableAddRegular = ( /*#__PURE__*/createFluentFontIcon("TableAddRegular", "", 2, undefined));
export const TableAdd16Regular = ( /*#__PURE__*/createFluentFontIcon("TableAdd16Regular", "", 1, 16));
export const TableAdd16Filled = ( /*#__PURE__*/createFluentFontIcon("TableAdd16Filled", "", 0, 16));
export const TableAdd20Regular = ( /*#__PURE__*/createFluentFontIcon("TableAdd20Regular", "", 1, 20));
export const TableAdd20Filled = ( /*#__PURE__*/createFluentFontIcon("TableAdd20Filled", "", 0, 20));
export const TableAdd24Regular = ( /*#__PURE__*/createFluentFontIcon("TableAdd24Regular", "", 1, 24));
export const TableAdd24Filled = ( /*#__PURE__*/createFluentFontIcon("TableAdd24Filled", "", 0, 24));
export const TableAdd28Regular = ( /*#__PURE__*/createFluentFontIcon("TableAdd28Regular", "", 1, 28));
export const TableAdd28Filled = ( /*#__PURE__*/createFluentFontIcon("TableAdd28Filled", "", 0, 28));
