"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TabsFilled = ( /*#__PURE__*/createFluentFontIcon("TabsFilled", "", 2, undefined));
export const TabsRegular = ( /*#__PURE__*/createFluentFontIcon("TabsRegular", "", 2, undefined));
export const Tabs16Regular = ( /*#__PURE__*/createFluentFontIcon("Tabs16Regular", "", 1, 16));
export const Tabs16Filled = ( /*#__PURE__*/createFluentFontIcon("Tabs16Filled", "", 0, 16));
export const Tabs20Regular = ( /*#__PURE__*/createFluentFontIcon("Tabs20Regular", "", 1, 20));
export const Tabs20Filled = ( /*#__PURE__*/createFluentFontIcon("Tabs20Filled", "", 0, 20));
export const Tabs24Regular = ( /*#__PURE__*/createFluentFontIcon("Tabs24Regular", "", 1, 24));
export const Tabs24Filled = ( /*#__PURE__*/createFluentFontIcon("Tabs24Filled", "", 0, 24));
