"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TagPercentFilled = ( /*#__PURE__*/createFluentFontIcon("TagPercentFilled", "", 2, undefined));
export const TagPercentRegular = ( /*#__PURE__*/createFluentFontIcon("TagPercentRegular", "", 2, undefined));
export const TagPercent16Regular = ( /*#__PURE__*/createFluentFontIcon("TagPercent16Regular", "󰤷", 1, 16));
export const TagPercent16Filled = ( /*#__PURE__*/createFluentFontIcon("TagPercent16Filled", "󰦴", 0, 16));
export const TagPercent20Regular = ( /*#__PURE__*/createFluentFontIcon("TagPercent20Regular", "󰤸", 1, 20));
export const TagPercent20Filled = ( /*#__PURE__*/createFluentFontIcon("TagPercent20Filled", "󰦵", 0, 20));
export const TagPercent24Regular = ( /*#__PURE__*/createFluentFontIcon("TagPercent24Regular", "󰤹", 1, 24));
export const TagPercent24Filled = ( /*#__PURE__*/createFluentFontIcon("TagPercent24Filled", "󰦶", 0, 24));
export const TagPercent28Regular = ( /*#__PURE__*/createFluentFontIcon("TagPercent28Regular", "󰤺", 1, 28));
export const TagPercent28Filled = ( /*#__PURE__*/createFluentFontIcon("TagPercent28Filled", "󰦷", 0, 28));
export const TagPercent32Regular = ( /*#__PURE__*/createFluentFontIcon("TagPercent32Regular", "󰤻", 1, 32));
export const TagPercent32Filled = ( /*#__PURE__*/createFluentFontIcon("TagPercent32Filled", "󰦸", 0, 32));
export const TagPercent48Regular = ( /*#__PURE__*/createFluentFontIcon("TagPercent48Regular", "󰤼", 1, 48));
export const TagPercent48Filled = ( /*#__PURE__*/createFluentFontIcon("TagPercent48Filled", "󰦹", 0, 48));
