"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TagDismissFilled = ( /*#__PURE__*/createFluentFontIcon("TagDismissFilled", "", 2, undefined));
export const TagDismissRegular = ( /*#__PURE__*/createFluentFontIcon("TagDismissRegular", "", 2, undefined));
export const TagDismiss16Regular = ( /*#__PURE__*/createFluentFontIcon("TagDismiss16Regular", "", 1, 16));
export const TagDismiss16Filled = ( /*#__PURE__*/createFluentFontIcon("TagDismiss16Filled", "", 0, 16));
export const TagDismiss20Regular = ( /*#__PURE__*/createFluentFontIcon("TagDismiss20Regular", "", 1, 20));
export const TagDismiss20Filled = ( /*#__PURE__*/createFluentFontIcon("TagDismiss20Filled", "", 0, 20));
export const TagDismiss24Regular = ( /*#__PURE__*/createFluentFontIcon("TagDismiss24Regular", "", 1, 24));
export const TagDismiss24Filled = ( /*#__PURE__*/createFluentFontIcon("TagDismiss24Filled", "", 0, 24));
