"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TagOffFilled = ( /*#__PURE__*/createFluentFontIcon("TagOffFilled", "", 2, undefined));
export const TagOffRegular = ( /*#__PURE__*/createFluentFontIcon("TagOffRegular", "", 2, undefined));
export const TagOff16Regular = ( /*#__PURE__*/createFluentFontIcon("TagOff16Regular", "󰗴", 1, 16));
export const TagOff16Filled = ( /*#__PURE__*/createFluentFontIcon("TagOff16Filled", "󰙰", 0, 16));
export const TagOff20Regular = ( /*#__PURE__*/createFluentFontIcon("TagOff20Regular", "", 1, 20));
export const TagOff20Filled = ( /*#__PURE__*/createFluentFontIcon("TagOff20Filled", "", 0, 20));
export const TagOff24Regular = ( /*#__PURE__*/createFluentFontIcon("TagOff24Regular", "", 1, 24));
export const TagOff24Filled = ( /*#__PURE__*/createFluentFontIcon("TagOff24Filled", "", 0, 24));
