"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TargetArrowFilled = ( /*#__PURE__*/createFluentFontIcon("TargetArrowFilled", "", 2, undefined));
export const TargetArrowRegular = ( /*#__PURE__*/createFluentFontIcon("TargetArrowRegular", "", 2, undefined));
export const TargetArrow16Regular = ( /*#__PURE__*/createFluentFontIcon("TargetArrow16Regular", "", 1, 16));
export const TargetArrow16Filled = ( /*#__PURE__*/createFluentFontIcon("TargetArrow16Filled", "", 0, 16));
export const TargetArrow20Regular = ( /*#__PURE__*/createFluentFontIcon("TargetArrow20Regular", "", 1, 20));
export const TargetArrow20Filled = ( /*#__PURE__*/createFluentFontIcon("TargetArrow20Filled", "", 0, 20));
export const TargetArrow24Regular = ( /*#__PURE__*/createFluentFontIcon("TargetArrow24Regular", "", 1, 24));
export const TargetArrow24Filled = ( /*#__PURE__*/createFluentFontIcon("TargetArrow24Filled", "", 0, 24));
