"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TeachingFilled = ( /*#__PURE__*/createFluentFontIcon("TeachingFilled", "", 2, undefined));
export const TeachingRegular = ( /*#__PURE__*/createFluentFontIcon("TeachingRegular", "", 2, undefined));
export const Teaching16Regular = ( /*#__PURE__*/createFluentFontIcon("Teaching16Regular", "󰚥", 1, 16));
export const Teaching16Filled = ( /*#__PURE__*/createFluentFontIcon("Teaching16Filled", "󰜠", 0, 16));
export const Teaching20Regular = ( /*#__PURE__*/createFluentFontIcon("Teaching20Regular", "󰙳", 1, 20));
export const Teaching20Filled = ( /*#__PURE__*/createFluentFontIcon("Teaching20Filled", "󰛳", 0, 20));
export const Teaching24Regular = ( /*#__PURE__*/createFluentFontIcon("Teaching24Regular", "󰚦", 1, 24));
export const Teaching24Filled = ( /*#__PURE__*/createFluentFontIcon("Teaching24Filled", "󰜡", 0, 24));
export const Teaching28Regular = ( /*#__PURE__*/createFluentFontIcon("Teaching28Regular", "󰚧", 1, 28));
export const Teaching28Filled = ( /*#__PURE__*/createFluentFontIcon("Teaching28Filled", "󰜢", 0, 28));
export const Teaching32Regular = ( /*#__PURE__*/createFluentFontIcon("Teaching32Regular", "󰚨", 1, 32));
export const Teaching32Filled = ( /*#__PURE__*/createFluentFontIcon("Teaching32Filled", "󰜣", 0, 32));
export const Teaching48Regular = ( /*#__PURE__*/createFluentFontIcon("Teaching48Regular", "󰚩", 1, 48));
export const Teaching48Filled = ( /*#__PURE__*/createFluentFontIcon("Teaching48Filled", "󰜤", 0, 48));
