"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TemperatureFilled = ( /*#__PURE__*/createFluentFontIcon("TemperatureFilled", "", 2, undefined));
export const TemperatureRegular = ( /*#__PURE__*/createFluentFontIcon("TemperatureRegular", "", 2, undefined));
export const Temperature16Regular = ( /*#__PURE__*/createFluentFontIcon("Temperature16Regular", "", 1, 16));
export const Temperature16Filled = ( /*#__PURE__*/createFluentFontIcon("Temperature16Filled", "", 0, 16));
export const Temperature20Regular = ( /*#__PURE__*/createFluentFontIcon("Temperature20Regular", "", 1, 20));
export const Temperature20Filled = ( /*#__PURE__*/createFluentFontIcon("Temperature20Filled", "", 0, 20));
export const Temperature24Regular = ( /*#__PURE__*/createFluentFontIcon("Temperature24Regular", "", 1, 24));
export const Temperature24Filled = ( /*#__PURE__*/createFluentFontIcon("Temperature24Filled", "", 0, 24));
export const Temperature32Regular = ( /*#__PURE__*/createFluentFontIcon("Temperature32Regular", "", 1, 32));
export const Temperature32Filled = ( /*#__PURE__*/createFluentFontIcon("Temperature32Filled", "", 0, 32));
export const Temperature48Regular = ( /*#__PURE__*/createFluentFontIcon("Temperature48Regular", "", 1, 48));
export const Temperature48Filled = ( /*#__PURE__*/createFluentFontIcon("Temperature48Filled", "", 0, 48));
