"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TentFilled = ( /*#__PURE__*/createFluentFontIcon("TentFilled", "", 2, undefined));
export const TentRegular = ( /*#__PURE__*/createFluentFontIcon("TentRegular", "", 2, undefined));
export const Tent12Regular = ( /*#__PURE__*/createFluentFontIcon("Tent12Regular", "", 1, 12));
export const Tent12Filled = ( /*#__PURE__*/createFluentFontIcon("Tent12Filled", "", 0, 12));
export const Tent16Regular = ( /*#__PURE__*/createFluentFontIcon("Tent16Regular", "", 1, 16));
export const Tent16Filled = ( /*#__PURE__*/createFluentFontIcon("Tent16Filled", "", 0, 16));
export const Tent20Regular = ( /*#__PURE__*/createFluentFontIcon("Tent20Regular", "", 1, 20));
export const Tent20Filled = ( /*#__PURE__*/createFluentFontIcon("Tent20Filled", "", 0, 20));
export const Tent24Regular = ( /*#__PURE__*/createFluentFontIcon("Tent24Regular", "", 1, 24));
export const Tent24Filled = ( /*#__PURE__*/createFluentFontIcon("Tent24Filled", "", 0, 24));
export const Tent28Regular = ( /*#__PURE__*/createFluentFontIcon("Tent28Regular", "", 1, 28));
export const Tent28Filled = ( /*#__PURE__*/createFluentFontIcon("Tent28Filled", "", 0, 28));
export const Tent48Regular = ( /*#__PURE__*/createFluentFontIcon("Tent48Regular", "", 1, 48));
export const Tent48Filled = ( /*#__PURE__*/createFluentFontIcon("Tent48Filled", "", 0, 48));
