"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TextFontFilled = ( /*#__PURE__*/createFluentFontIcon("TextFontFilled", "", 2, undefined));
export const TextFontRegular = ( /*#__PURE__*/createFluentFontIcon("TextFontRegular", "", 2, undefined));
export const TextFont16Regular = ( /*#__PURE__*/createFluentFontIcon("TextFont16Regular", "", 1, 16));
export const TextFont16Filled = ( /*#__PURE__*/createFluentFontIcon("TextFont16Filled", "", 0, 16));
export const TextFont20Regular = ( /*#__PURE__*/createFluentFontIcon("TextFont20Regular", "", 1, 20));
export const TextFont20Filled = ( /*#__PURE__*/createFluentFontIcon("TextFont20Filled", "", 0, 20));
export const TextFont24Regular = ( /*#__PURE__*/createFluentFontIcon("TextFont24Regular", "", 1, 24));
export const TextFont24Filled = ( /*#__PURE__*/createFluentFontIcon("TextFont24Filled", "", 0, 24));
