"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TextColorFilled = ( /*#__PURE__*/createFluentFontIcon("TextColorFilled", "", 2, undefined));
export const TextColorRegular = ( /*#__PURE__*/createFluentFontIcon("TextColorRegular", "", 2, undefined));
export const Text12Regular = ( /*#__PURE__*/createFluentFontIcon("Text12Regular", "", 1, 12));
export const Text12Filled = ( /*#__PURE__*/createFluentFontIcon("Text12Filled", "", 0, 12));
export const Text16Regular = ( /*#__PURE__*/createFluentFontIcon("Text16Regular", "", 1, 16));
export const TextColor16Regular = ( /*#__PURE__*/createFluentFontIcon("TextColor16Regular", "", 1, 16));
export const Text16Filled = ( /*#__PURE__*/createFluentFontIcon("Text16Filled", "", 0, 16));
export const TextColor16Filled = ( /*#__PURE__*/createFluentFontIcon("TextColor16Filled", "", 0, 16));
export const TextColor20Regular = ( /*#__PURE__*/createFluentFontIcon("TextColor20Regular", "", 1, 20));
export const TextColor20Filled = ( /*#__PURE__*/createFluentFontIcon("TextColor20Filled", "", 0, 20));
export const TextColor24Regular = ( /*#__PURE__*/createFluentFontIcon("TextColor24Regular", "", 1, 24));
export const TextColor24Filled = ( /*#__PURE__*/createFluentFontIcon("TextColor24Filled", "", 0, 24));
export const Text32Regular = ( /*#__PURE__*/createFluentFontIcon("Text32Regular", "", 1, 32));
export const Text32Filled = ( /*#__PURE__*/createFluentFontIcon("Text32Filled", "", 0, 32));
export const Text32Light = ( /*#__PURE__*/createFluentFontIcon("Text32Light", "", 3, 32));
