"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TextWrapFilled = ( /*#__PURE__*/createFluentFontIcon("TextWrapFilled", "", 2, undefined));
export const TextWrapRegular = ( /*#__PURE__*/createFluentFontIcon("TextWrapRegular", "", 2, undefined));
export const TextWrap16Regular = ( /*#__PURE__*/createFluentFontIcon("TextWrap16Regular", "", 1, 16));
export const TextWrap16Filled = ( /*#__PURE__*/createFluentFontIcon("TextWrap16Filled", "", 0, 16));
export const TextWrap20Regular = ( /*#__PURE__*/createFluentFontIcon("TextWrap20Regular", "", 1, 20));
export const TextWrap20Filled = ( /*#__PURE__*/createFluentFontIcon("TextWrap20Filled", "", 0, 20));
export const TextWrap24Regular = ( /*#__PURE__*/createFluentFontIcon("TextWrap24Regular", "", 1, 24));
export const TextWrap24Filled = ( /*#__PURE__*/createFluentFontIcon("TextWrap24Filled", "", 0, 24));
