"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TextItalicFilled = ( /*#__PURE__*/createFluentFontIcon("TextItalicFilled", "", 2, undefined));
export const TextItalicRegular = ( /*#__PURE__*/createFluentFontIcon("TextItalicRegular", "", 2, undefined));
export const TextItalic16Regular = ( /*#__PURE__*/createFluentFontIcon("TextItalic16Regular", "", 1, 16));
export const TextItalic16Filled = ( /*#__PURE__*/createFluentFontIcon("TextItalic16Filled", "", 0, 16));
export const TextItalic20Regular = ( /*#__PURE__*/createFluentFontIcon("TextItalic20Regular", "", 1, 20));
export const TextItalic20Filled = ( /*#__PURE__*/createFluentFontIcon("TextItalic20Filled", "", 0, 20));
export const TextItalic24Regular = ( /*#__PURE__*/createFluentFontIcon("TextItalic24Regular", "", 1, 24));
export const TextItalic24Filled = ( /*#__PURE__*/createFluentFontIcon("TextItalic24Filled", "", 0, 24));
