"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ThumbDislikeFilled = ( /*#__PURE__*/createFluentFontIcon("ThumbDislikeFilled", "", 2, undefined));
export const ThumbDislikeRegular = ( /*#__PURE__*/createFluentFontIcon("ThumbDislikeRegular", "", 2, undefined));
export const ThumbDislike16Regular = ( /*#__PURE__*/createFluentFontIcon("ThumbDislike16Regular", "", 1, 16));
export const ThumbDislike16Filled = ( /*#__PURE__*/createFluentFontIcon("ThumbDislike16Filled", "", 0, 16));
export const ThumbDislike20Regular = ( /*#__PURE__*/createFluentFontIcon("ThumbDislike20Regular", "", 1, 20));
export const ThumbDislike20Filled = ( /*#__PURE__*/createFluentFontIcon("ThumbDislike20Filled", "", 0, 20));
export const ThumbDislike24Regular = ( /*#__PURE__*/createFluentFontIcon("ThumbDislike24Regular", "", 1, 24));
export const ThumbDislike24Filled = ( /*#__PURE__*/createFluentFontIcon("ThumbDislike24Filled", "", 0, 24));
