"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TooltipQuoteFilled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuoteFilled", "", 2, undefined));
export const TooltipQuoteRegular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuoteRegular", "", 2, undefined));
export const TooltipQuote12Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote12Regular", "󰨺", 1, 12));
export const TooltipQuote12Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote12Filled", "󰪶", 0, 12));
export const TooltipQuote16Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote16Regular", "󰥿", 1, 16));
export const TooltipQuote16Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote16Filled", "󰧼", 0, 16));
export const TooltipQuote20Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote20Regular", "", 1, 20));
export const TooltipQuote20Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote20Filled", "", 0, 20));
export const TooltipQuote24Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote24Regular", "", 1, 24));
export const TooltipQuote24Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote24Filled", "", 0, 24));
export const TooltipQuote28Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote28Regular", "󰦀", 1, 28));
export const TooltipQuote28Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote28Filled", "󰧽", 0, 28));
export const TooltipQuote32Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote32Regular", "󰦁", 1, 32));
export const TooltipQuote32Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote32Filled", "󰧾", 0, 32));
export const TooltipQuote48Regular = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote48Regular", "󰦂", 1, 48));
export const TooltipQuote48Filled = ( /*#__PURE__*/createFluentFontIcon("TooltipQuote48Filled", "󰧿", 0, 48));
