"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const ToolboxFilled = ( /*#__PURE__*/createFluentFontIcon("ToolboxFilled", "", 2, undefined));
export const ToolboxRegular = ( /*#__PURE__*/createFluentFontIcon("ToolboxRegular", "", 2, undefined));
export const Toolbox12Regular = ( /*#__PURE__*/createFluentFontIcon("Toolbox12Regular", "", 1, 12));
export const Toolbox12Filled = ( /*#__PURE__*/createFluentFontIcon("Toolbox12Filled", "", 0, 12));
export const Toolbox16Regular = ( /*#__PURE__*/createFluentFontIcon("Toolbox16Regular", "", 1, 16));
export const Toolbox16Filled = ( /*#__PURE__*/createFluentFontIcon("Toolbox16Filled", "", 0, 16));
export const Toolbox20Regular = ( /*#__PURE__*/createFluentFontIcon("Toolbox20Regular", "", 1, 20));
export const Toolbox20Filled = ( /*#__PURE__*/createFluentFontIcon("Toolbox20Filled", "", 0, 20));
export const Toolbox24Regular = ( /*#__PURE__*/createFluentFontIcon("Toolbox24Regular", "", 1, 24));
export const Toolbox24Filled = ( /*#__PURE__*/createFluentFontIcon("Toolbox24Filled", "", 0, 24));
export const Toolbox28Regular = ( /*#__PURE__*/createFluentFontIcon("Toolbox28Regular", "", 1, 28));
export const Toolbox28Filled = ( /*#__PURE__*/createFluentFontIcon("Toolbox28Filled", "", 0, 28));
export const Toolbox32Regular = ( /*#__PURE__*/createFluentFontIcon("Toolbox32Regular", "󰚅", 1, 32));
export const Toolbox32Filled = ( /*#__PURE__*/createFluentFontIcon("Toolbox32Filled", "󰜀", 0, 32));
export const Toolbox32Light = ( /*#__PURE__*/createFluentFontIcon("Toolbox32Light", "", 3, 32));
