"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TransparencySquareFilled = ( /*#__PURE__*/createFluentFontIcon("TransparencySquareFilled", "", 2, undefined));
export const TransparencySquareRegular = ( /*#__PURE__*/createFluentFontIcon("TransparencySquareRegular", "", 2, undefined));
export const TransparencySquare16Regular = ( /*#__PURE__*/createFluentFontIcon("TransparencySquare16Regular", "󰨖", 1, 16));
export const TransparencySquare16Filled = ( /*#__PURE__*/createFluentFontIcon("TransparencySquare16Filled", "󰪒", 0, 16));
export const TransparencySquare20Regular = ( /*#__PURE__*/createFluentFontIcon("TransparencySquare20Regular", "󰘟", 1, 20));
export const TransparencySquare20Filled = ( /*#__PURE__*/createFluentFontIcon("TransparencySquare20Filled", "󰚛", 0, 20));
export const TransparencySquare24Regular = ( /*#__PURE__*/createFluentFontIcon("TransparencySquare24Regular", "󰘠", 1, 24));
export const TransparencySquare24Filled = ( /*#__PURE__*/createFluentFontIcon("TransparencySquare24Filled", "󰚜", 0, 24));
