"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TriangleLeftFilled = ( /*#__PURE__*/createFluentFontIcon("TriangleLeftFilled", "", 2, undefined));
export const TriangleLeftRegular = ( /*#__PURE__*/createFluentFontIcon("TriangleLeftRegular", "", 2, undefined));
export const TriangleLeft12Regular = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft12Regular", "", 1, 12));
export const TriangleLeft12Filled = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft12Filled", "", 0, 12));
export const TriangleLeft16Regular = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft16Regular", "", 1, 16));
export const TriangleLeft16Filled = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft16Filled", "", 0, 16));
export const TriangleLeft20Regular = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft20Regular", "", 1, 20));
export const TriangleLeft20Filled = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft20Filled", "", 0, 20));
export const TriangleLeft32Regular = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft32Regular", "", 1, 32));
export const TriangleLeft32Filled = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft32Filled", "", 0, 32));
export const TriangleLeft48Regular = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft48Regular", "", 1, 48));
export const TriangleLeft48Filled = ( /*#__PURE__*/createFluentFontIcon("TriangleLeft48Filled", "", 0, 48));
