"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TriangleFilled = ( /*#__PURE__*/createFluentFontIcon("TriangleFilled", "", 2, undefined));
export const TriangleRegular = ( /*#__PURE__*/createFluentFontIcon("TriangleRegular", "", 2, undefined));
export const Triangle12Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle12Regular", "", 1, 12));
export const Triangle12Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle12Filled", "", 0, 12));
export const Triangle16Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle16Regular", "", 1, 16));
export const Triangle16Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle16Filled", "", 0, 16));
export const Triangle20Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle20Regular", "", 1, 20));
export const Triangle20Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle20Filled", "", 0, 20));
export const Triangle24Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle24Regular", "󰎥", 1, 24));
export const Triangle24Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle24Filled", "󰎸", 0, 24));
export const Triangle28Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle28Regular", "󰎦", 1, 28));
export const Triangle28Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle28Filled", "󰎹", 0, 28));
export const Triangle32Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle32Regular", "", 1, 32));
export const Triangle32Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle32Filled", "", 0, 32));
export const Triangle48Regular = ( /*#__PURE__*/createFluentFontIcon("Triangle48Regular", "", 1, 48));
export const Triangle48Filled = ( /*#__PURE__*/createFluentFontIcon("Triangle48Filled", "", 0, 48));
