"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const TvFilled = ( /*#__PURE__*/createFluentFontIcon("TvFilled", "", 2, undefined));
export const TvRegular = ( /*#__PURE__*/createFluentFontIcon("TvRegular", "", 2, undefined));
export const Tv16Regular = ( /*#__PURE__*/createFluentFontIcon("Tv16Regular", "", 1, 16));
export const Tv16Filled = ( /*#__PURE__*/createFluentFontIcon("Tv16Filled", "", 0, 16));
export const Tv20Regular = ( /*#__PURE__*/createFluentFontIcon("Tv20Regular", "", 1, 20));
export const Tv20Filled = ( /*#__PURE__*/createFluentFontIcon("Tv20Filled", "", 0, 20));
export const Tv24Regular = ( /*#__PURE__*/createFluentFontIcon("Tv24Regular", "", 1, 24));
export const Tv24Filled = ( /*#__PURE__*/createFluentFontIcon("Tv24Filled", "", 0, 24));
export const Tv28Regular = ( /*#__PURE__*/createFluentFontIcon("Tv28Regular", "", 1, 28));
export const Tv28Filled = ( /*#__PURE__*/createFluentFontIcon("Tv28Filled", "", 0, 28));
export const Tv48Regular = ( /*#__PURE__*/createFluentFontIcon("Tv48Regular", "", 1, 48));
export const Tv48Filled = ( /*#__PURE__*/createFluentFontIcon("Tv48Filled", "", 0, 48));
