"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const VehicleShipFilled = ( /*#__PURE__*/createFluentFontIcon("VehicleShipFilled", "", 2, undefined));
export const VehicleShipRegular = ( /*#__PURE__*/createFluentFontIcon("VehicleShipRegular", "", 2, undefined));
export const VehicleShip16Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleShip16Regular", "", 1, 16));
export const VehicleShip16Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleShip16Filled", "", 0, 16));
export const VehicleShip20Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleShip20Regular", "", 1, 20));
export const VehicleShip20Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleShip20Filled", "", 0, 20));
export const VehicleShip24Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleShip24Regular", "", 1, 24));
export const VehicleShip24Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleShip24Filled", "", 0, 24));
