"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const VehicleCarFilled = ( /*#__PURE__*/createFluentFontIcon("VehicleCarFilled", "", 2, undefined));
export const VehicleCarRegular = ( /*#__PURE__*/createFluentFontIcon("VehicleCarRegular", "", 2, undefined));
export const VehicleCar16Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleCar16Regular", "", 1, 16));
export const VehicleCar16Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleCar16Filled", "", 0, 16));
export const VehicleCar20Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleCar20Regular", "", 1, 20));
export const VehicleCar20Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleCar20Filled", "", 0, 20));
export const VehicleCar24Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleCar24Regular", "", 1, 24));
export const VehicleCar24Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleCar24Filled", "", 0, 24));
export const VehicleCar28Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleCar28Regular", "", 1, 28));
export const VehicleCar28Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleCar28Filled", "", 0, 28));
export const VehicleCar32Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleCar32Regular", "", 1, 32));
export const VehicleCar32Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleCar32Filled", "", 0, 32));
export const VehicleCar48Regular = ( /*#__PURE__*/createFluentFontIcon("VehicleCar48Regular", "", 1, 48));
export const VehicleCar48Filled = ( /*#__PURE__*/createFluentFontIcon("VehicleCar48Filled", "", 0, 48));
