"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const VideoOffFilled = ( /*#__PURE__*/createFluentFontIcon("VideoOffFilled", "", 2, undefined));
export const VideoOffRegular = ( /*#__PURE__*/createFluentFontIcon("VideoOffRegular", "", 2, undefined));
export const VideoOff16Regular = ( /*#__PURE__*/createFluentFontIcon("VideoOff16Regular", "󰔠", 1, 16));
export const VideoOff16Filled = ( /*#__PURE__*/createFluentFontIcon("VideoOff16Filled", "󰖙", 0, 16));
export const VideoOff20Regular = ( /*#__PURE__*/createFluentFontIcon("VideoOff20Regular", "", 1, 20));
export const VideoOff20Filled = ( /*#__PURE__*/createFluentFontIcon("VideoOff20Filled", "", 0, 20));
export const VideoOff24Regular = ( /*#__PURE__*/createFluentFontIcon("VideoOff24Regular", "", 1, 24));
export const VideoOff24Filled = ( /*#__PURE__*/createFluentFontIcon("VideoOff24Filled", "", 0, 24));
export const VideoOff28Regular = ( /*#__PURE__*/createFluentFontIcon("VideoOff28Regular", "", 1, 28));
export const VideoOff28Filled = ( /*#__PURE__*/createFluentFontIcon("VideoOff28Filled", "", 0, 28));
export const VideoOff32Regular = ( /*#__PURE__*/createFluentFontIcon("VideoOff32Regular", "", 1, 32));
export const VideoOff32Filled = ( /*#__PURE__*/createFluentFontIcon("VideoOff32Filled", "", 0, 32));
export const VideoOff48Regular = ( /*#__PURE__*/createFluentFontIcon("VideoOff48Regular", "", 1, 48));
export const VideoOff48Filled = ( /*#__PURE__*/createFluentFontIcon("VideoOff48Filled", "", 0, 48));
