"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const VideoPersonFilled = ( /*#__PURE__*/createFluentFontIcon("VideoPersonFilled", "", 2, undefined));
export const VideoPersonRegular = ( /*#__PURE__*/createFluentFontIcon("VideoPersonRegular", "", 2, undefined));
export const VideoPerson12Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson12Regular", "", 1, 12));
export const VideoPerson12Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson12Filled", "", 0, 12));
export const VideoPerson16Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson16Regular", "", 1, 16));
export const VideoPerson16Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson16Filled", "", 0, 16));
export const VideoPerson20Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson20Regular", "", 1, 20));
export const VideoPerson20Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson20Filled", "", 0, 20));
export const VideoPerson24Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson24Regular", "", 1, 24));
export const VideoPerson24Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson24Filled", "", 0, 24));
export const VideoPerson28Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson28Regular", "", 1, 28));
export const VideoPerson28Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson28Filled", "", 0, 28));
export const VideoPerson32Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson32Regular", "", 1, 32));
export const VideoPerson32Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson32Filled", "", 0, 32));
export const VideoPerson48Regular = ( /*#__PURE__*/createFluentFontIcon("VideoPerson48Regular", "", 1, 48));
export const VideoPerson48Filled = ( /*#__PURE__*/createFluentFontIcon("VideoPerson48Filled", "", 0, 48));
