"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const VoicemailFilled = ( /*#__PURE__*/createFluentFontIcon("VoicemailFilled", "", 2, undefined));
export const VoicemailRegular = ( /*#__PURE__*/createFluentFontIcon("VoicemailRegular", "", 2, undefined));
export const Voicemail16Regular = ( /*#__PURE__*/createFluentFontIcon("Voicemail16Regular", "", 1, 16));
export const Voicemail16Filled = ( /*#__PURE__*/createFluentFontIcon("Voicemail16Filled", "", 0, 16));
export const Voicemail20Regular = ( /*#__PURE__*/createFluentFontIcon("Voicemail20Regular", "", 1, 20));
export const Voicemail20Filled = ( /*#__PURE__*/createFluentFontIcon("Voicemail20Filled", "", 0, 20));
export const Voicemail24Regular = ( /*#__PURE__*/createFluentFontIcon("Voicemail24Regular", "", 1, 24));
export const Voicemail24Filled = ( /*#__PURE__*/createFluentFontIcon("Voicemail24Filled", "", 0, 24));
export const Voicemail28Regular = ( /*#__PURE__*/createFluentFontIcon("Voicemail28Regular", "", 1, 28));
export const Voicemail28Filled = ( /*#__PURE__*/createFluentFontIcon("Voicemail28Filled", "", 0, 28));
export const Voicemail32Regular = ( /*#__PURE__*/createFluentFontIcon("Voicemail32Regular", "", 1, 32));
export const Voicemail32Filled = ( /*#__PURE__*/createFluentFontIcon("Voicemail32Filled", "", 0, 32));
export const Voicemail48Regular = ( /*#__PURE__*/createFluentFontIcon("Voicemail48Regular", "󰃍", 1, 48));
export const Voicemail48Filled = ( /*#__PURE__*/createFluentFontIcon("Voicemail48Filled", "󰃌", 0, 48));
