"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WalkieTalkieFilled = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkieFilled", "", 2, undefined));
export const WalkieTalkieRegular = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkieRegular", "", 2, undefined));
export const WalkieTalkie20Regular = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkie20Regular", "", 1, 20));
export const WalkieTalkie20Filled = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkie20Filled", "", 0, 20));
export const WalkieTalkie24Regular = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkie24Regular", "", 1, 24));
export const WalkieTalkie24Filled = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkie24Filled", "", 0, 24));
export const WalkieTalkie28Regular = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkie28Regular", "", 1, 28));
export const WalkieTalkie28Filled = ( /*#__PURE__*/createFluentFontIcon("WalkieTalkie28Filled", "", 0, 28));
