"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WalletFilled = ( /*#__PURE__*/createFluentFontIcon("WalletFilled", "", 2, undefined));
export const WalletRegular = ( /*#__PURE__*/createFluentFontIcon("WalletRegular", "", 2, undefined));
export const Wallet16Regular = ( /*#__PURE__*/createFluentFontIcon("Wallet16Regular", "", 1, 16));
export const Wallet16Filled = ( /*#__PURE__*/createFluentFontIcon("Wallet16Filled", "", 0, 16));
export const Wallet20Regular = ( /*#__PURE__*/createFluentFontIcon("Wallet20Regular", "", 1, 20));
export const Wallet20Filled = ( /*#__PURE__*/createFluentFontIcon("Wallet20Filled", "", 0, 20));
export const Wallet24Regular = ( /*#__PURE__*/createFluentFontIcon("Wallet24Regular", "", 1, 24));
export const Wallet24Filled = ( /*#__PURE__*/createFluentFontIcon("Wallet24Filled", "", 0, 24));
export const Wallet28Regular = ( /*#__PURE__*/createFluentFontIcon("Wallet28Regular", "", 1, 28));
export const Wallet28Filled = ( /*#__PURE__*/createFluentFontIcon("Wallet28Filled", "", 0, 28));
export const Wallet32Regular = ( /*#__PURE__*/createFluentFontIcon("Wallet32Regular", "", 1, 32));
export const Wallet32Filled = ( /*#__PURE__*/createFluentFontIcon("Wallet32Filled", "", 0, 32));
export const Wallet48Regular = ( /*#__PURE__*/createFluentFontIcon("Wallet48Regular", "", 1, 48));
export const Wallet48Filled = ( /*#__PURE__*/createFluentFontIcon("Wallet48Filled", "", 0, 48));
