"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WandFilled = ( /*#__PURE__*/createFluentFontIcon("WandFilled", "", 2, undefined));
export const WandRegular = ( /*#__PURE__*/createFluentFontIcon("WandRegular", "", 2, undefined));
export const Wand16Regular = ( /*#__PURE__*/createFluentFontIcon("Wand16Regular", "", 1, 16));
export const Wand16Filled = ( /*#__PURE__*/createFluentFontIcon("Wand16Filled", "", 0, 16));
export const Wand20Regular = ( /*#__PURE__*/createFluentFontIcon("Wand20Regular", "", 1, 20));
export const Wand20Filled = ( /*#__PURE__*/createFluentFontIcon("Wand20Filled", "", 0, 20));
export const Wand24Regular = ( /*#__PURE__*/createFluentFontIcon("Wand24Regular", "", 1, 24));
export const Wand24Filled = ( /*#__PURE__*/createFluentFontIcon("Wand24Filled", "", 0, 24));
export const Wand28Regular = ( /*#__PURE__*/createFluentFontIcon("Wand28Regular", "", 1, 28));
export const Wand28Filled = ( /*#__PURE__*/createFluentFontIcon("Wand28Filled", "", 0, 28));
export const Wand48Regular = ( /*#__PURE__*/createFluentFontIcon("Wand48Regular", "", 1, 48));
export const Wand48Filled = ( /*#__PURE__*/createFluentFontIcon("Wand48Filled", "", 0, 48));
