"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WarningFilled = ( /*#__PURE__*/createFluentFontIcon("WarningFilled", "", 2, undefined));
export const WarningRegular = ( /*#__PURE__*/createFluentFontIcon("WarningRegular", "", 2, undefined));
export const Warning12Regular = ( /*#__PURE__*/createFluentFontIcon("Warning12Regular", "", 1, 12));
export const Warning12Filled = ( /*#__PURE__*/createFluentFontIcon("Warning12Filled", "", 0, 12));
export const Warning16Regular = ( /*#__PURE__*/createFluentFontIcon("Warning16Regular", "", 1, 16));
export const Warning16Filled = ( /*#__PURE__*/createFluentFontIcon("Warning16Filled", "", 0, 16));
export const Warning20Regular = ( /*#__PURE__*/createFluentFontIcon("Warning20Regular", "", 1, 20));
export const Warning20Filled = ( /*#__PURE__*/createFluentFontIcon("Warning20Filled", "", 0, 20));
export const Warning24Regular = ( /*#__PURE__*/createFluentFontIcon("Warning24Regular", "", 1, 24));
export const Warning24Filled = ( /*#__PURE__*/createFluentFontIcon("Warning24Filled", "", 0, 24));
export const Warning28Regular = ( /*#__PURE__*/createFluentFontIcon("Warning28Regular", "", 1, 28));
export const Warning28Filled = ( /*#__PURE__*/createFluentFontIcon("Warning28Filled", "", 0, 28));
export const Warning32Regular = ( /*#__PURE__*/createFluentFontIcon("Warning32Regular", "󰉊", 1, 32));
export const Warning32Filled = ( /*#__PURE__*/createFluentFontIcon("Warning32Filled", "󰉝", 0, 32));
export const Warning48Regular = ( /*#__PURE__*/createFluentFontIcon("Warning48Regular", "󰏏", 1, 48));
export const Warning48Filled = ( /*#__PURE__*/createFluentFontIcon("Warning48Filled", "󰏢", 0, 48));
