"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WasherFilled = ( /*#__PURE__*/createFluentFontIcon("WasherFilled", "", 2, undefined));
export const WasherRegular = ( /*#__PURE__*/createFluentFontIcon("WasherRegular", "", 2, undefined));
export const Washer20Regular = ( /*#__PURE__*/createFluentFontIcon("Washer20Regular", "", 1, 20));
export const Washer20Filled = ( /*#__PURE__*/createFluentFontIcon("Washer20Filled", "", 0, 20));
export const Washer24Regular = ( /*#__PURE__*/createFluentFontIcon("Washer24Regular", "", 1, 24));
export const Washer24Filled = ( /*#__PURE__*/createFluentFontIcon("Washer24Filled", "", 0, 24));
export const Washer32Regular = ( /*#__PURE__*/createFluentFontIcon("Washer32Regular", "", 1, 32));
export const Washer32Filled = ( /*#__PURE__*/createFluentFontIcon("Washer32Filled", "", 0, 32));
export const Washer48Regular = ( /*#__PURE__*/createFluentFontIcon("Washer48Regular", "", 1, 48));
export const Washer48Filled = ( /*#__PURE__*/createFluentFontIcon("Washer48Filled", "", 0, 48));
