"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WeatherSquallsFilled = ( /*#__PURE__*/createFluentFontIcon("WeatherSquallsFilled", "", 2, undefined));
export const WeatherSquallsRegular = ( /*#__PURE__*/createFluentFontIcon("WeatherSquallsRegular", "", 2, undefined));
export const WeatherSqualls20Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSqualls20Regular", "", 1, 20));
export const WeatherSqualls20Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSqualls20Filled", "", 0, 20));
export const WeatherSqualls24Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSqualls24Regular", "", 1, 24));
export const WeatherSqualls24Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSqualls24Filled", "", 0, 24));
export const WeatherSqualls48Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSqualls48Regular", "", 1, 48));
export const WeatherSqualls48Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSqualls48Filled", "", 0, 48));
