"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WeatherSunnyFilled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunnyFilled", "", 2, undefined));
export const WeatherSunnyRegular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunnyRegular", "", 2, undefined));
export const WeatherSunny16Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny16Regular", "", 1, 16));
export const WeatherSunny16Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny16Filled", "", 0, 16));
export const WeatherSunny20Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny20Regular", "", 1, 20));
export const WeatherSunny20Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny20Filled", "", 0, 20));
export const WeatherSunny24Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny24Regular", "", 1, 24));
export const WeatherSunny24Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny24Filled", "", 0, 24));
export const WeatherSunny28Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny28Regular", "", 1, 28));
export const WeatherSunny28Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny28Filled", "", 0, 28));
export const WeatherSunny32Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny32Regular", "", 1, 32));
export const WeatherSunny32Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny32Filled", "", 0, 32));
export const WeatherSunny32Light = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny32Light", "", 3, 32));
export const WeatherSunny48Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny48Regular", "", 1, 48));
export const WeatherSunny48Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherSunny48Filled", "", 0, 48));
