"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WeatherFogFilled = ( /*#__PURE__*/createFluentFontIcon("WeatherFogFilled", "", 2, undefined));
export const WeatherFogRegular = ( /*#__PURE__*/createFluentFontIcon("WeatherFogRegular", "", 2, undefined));
export const WeatherFog20Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherFog20Regular", "", 1, 20));
export const WeatherFog20Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherFog20Filled", "", 0, 20));
export const WeatherFog24Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherFog24Regular", "", 1, 24));
export const WeatherFog24Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherFog24Filled", "", 0, 24));
export const WeatherFog48Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherFog48Regular", "", 1, 48));
export const WeatherFog48Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherFog48Filled", "", 0, 48));
