"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WeatherMoonFilled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoonFilled", "", 2, undefined));
export const WeatherMoonRegular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoonRegular", "", 2, undefined));
export const WeatherMoon16Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon16Regular", "", 1, 16));
export const WeatherMoon16Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon16Filled", "", 0, 16));
export const WeatherMoon20Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon20Regular", "", 1, 20));
export const WeatherMoon20Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon20Filled", "", 0, 20));
export const WeatherMoon24Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon24Regular", "", 1, 24));
export const WeatherMoon24Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon24Filled", "", 0, 24));
export const WeatherMoon28Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon28Regular", "", 1, 28));
export const WeatherMoon28Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon28Filled", "", 0, 28));
export const WeatherMoon32Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon32Regular", "󰟨", 1, 32));
export const WeatherMoon32Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon32Filled", "󰡥", 0, 32));
export const WeatherMoon32Light = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon32Light", "", 3, 32));
export const WeatherMoon48Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon48Regular", "", 1, 48));
export const WeatherMoon48Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherMoon48Filled", "", 0, 48));
