"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WeatherHazeFilled = ( /*#__PURE__*/createFluentFontIcon("WeatherHazeFilled", "", 2, undefined));
export const WeatherHazeRegular = ( /*#__PURE__*/createFluentFontIcon("WeatherHazeRegular", "", 2, undefined));
export const WeatherHaze20Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherHaze20Regular", "", 1, 20));
export const WeatherHaze20Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherHaze20Filled", "", 0, 20));
export const WeatherHaze24Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherHaze24Regular", "", 1, 24));
export const WeatherHaze24Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherHaze24Filled", "", 0, 24));
export const WeatherHaze48Regular = ( /*#__PURE__*/createFluentFontIcon("WeatherHaze48Regular", "", 1, 48));
export const WeatherHaze48Filled = ( /*#__PURE__*/createFluentFontIcon("WeatherHaze48Filled", "", 0, 48));
