"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WheelchairAccessFilled = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccessFilled", "", 2, undefined));
export const WheelchairAccessRegular = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccessRegular", "", 2, undefined));
export const WheelchairAccess16Regular = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccess16Regular", "󰨼", 1, 16));
export const WheelchairAccess16Filled = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccess16Filled", "󰪸", 0, 16));
export const WheelchairAccess20Regular = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccess20Regular", "󰨽", 1, 20));
export const WheelchairAccess20Filled = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccess20Filled", "󰪹", 0, 20));
export const WheelchairAccess24Regular = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccess24Regular", "󰨾", 1, 24));
export const WheelchairAccess24Filled = ( /*#__PURE__*/createFluentFontIcon("WheelchairAccess24Filled", "󰪺", 0, 24));
