"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WindowWrenchFilled = ( /*#__PURE__*/createFluentFontIcon("WindowWrenchFilled", "", 2, undefined));
export const WindowWrenchRegular = ( /*#__PURE__*/createFluentFontIcon("WindowWrenchRegular", "", 2, undefined));
export const WindowWrench16Regular = ( /*#__PURE__*/createFluentFontIcon("WindowWrench16Regular", "", 1, 16));
export const WindowWrench16Filled = ( /*#__PURE__*/createFluentFontIcon("WindowWrench16Filled", "", 0, 16));
export const WindowWrench20Regular = ( /*#__PURE__*/createFluentFontIcon("WindowWrench20Regular", "", 1, 20));
export const WindowWrench20Filled = ( /*#__PURE__*/createFluentFontIcon("WindowWrench20Filled", "", 0, 20));
export const WindowWrench24Regular = ( /*#__PURE__*/createFluentFontIcon("WindowWrench24Regular", "", 1, 24));
export const WindowWrench24Filled = ( /*#__PURE__*/createFluentFontIcon("WindowWrench24Filled", "", 0, 24));
export const WindowWrench28Regular = ( /*#__PURE__*/createFluentFontIcon("WindowWrench28Regular", "", 1, 28));
export const WindowWrench28Filled = ( /*#__PURE__*/createFluentFontIcon("WindowWrench28Filled", "", 0, 28));
export const WindowWrench32Regular = ( /*#__PURE__*/createFluentFontIcon("WindowWrench32Regular", "", 1, 32));
export const WindowWrench32Filled = ( /*#__PURE__*/createFluentFontIcon("WindowWrench32Filled", "", 0, 32));
export const WindowWrench48Regular = ( /*#__PURE__*/createFluentFontIcon("WindowWrench48Regular", "", 1, 48));
export const WindowWrench48Filled = ( /*#__PURE__*/createFluentFontIcon("WindowWrench48Filled", "", 0, 48));
