"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WindowAppsFilled = ( /*#__PURE__*/createFluentFontIcon("WindowAppsFilled", "", 2, undefined));
export const WindowAppsRegular = ( /*#__PURE__*/createFluentFontIcon("WindowAppsRegular", "", 2, undefined));
export const WindowApps16Regular = ( /*#__PURE__*/createFluentFontIcon("WindowApps16Regular", "", 1, 16));
export const WindowApps16Filled = ( /*#__PURE__*/createFluentFontIcon("WindowApps16Filled", "", 0, 16));
export const WindowApps20Regular = ( /*#__PURE__*/createFluentFontIcon("WindowApps20Regular", "", 1, 20));
export const WindowApps20Filled = ( /*#__PURE__*/createFluentFontIcon("WindowApps20Filled", "", 0, 20));
export const WindowApps24Regular = ( /*#__PURE__*/createFluentFontIcon("WindowApps24Regular", "", 1, 24));
export const WindowApps24Filled = ( /*#__PURE__*/createFluentFontIcon("WindowApps24Filled", "", 0, 24));
export const WindowApps28Regular = ( /*#__PURE__*/createFluentFontIcon("WindowApps28Regular", "", 1, 28));
export const WindowApps28Filled = ( /*#__PURE__*/createFluentFontIcon("WindowApps28Filled", "", 0, 28));
export const WindowApps32Regular = ( /*#__PURE__*/createFluentFontIcon("WindowApps32Regular", "", 1, 32));
export const WindowApps32Filled = ( /*#__PURE__*/createFluentFontIcon("WindowApps32Filled", "", 0, 32));
export const WindowApps48Regular = ( /*#__PURE__*/createFluentFontIcon("WindowApps48Regular", "", 1, 48));
export const WindowApps48Filled = ( /*#__PURE__*/createFluentFontIcon("WindowApps48Filled", "", 0, 48));
