"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WindowFilled = ( /*#__PURE__*/createFluentFontIcon("WindowFilled", "", 2, undefined));
export const WindowRegular = ( /*#__PURE__*/createFluentFontIcon("WindowRegular", "", 2, undefined));
export const Window16Regular = ( /*#__PURE__*/createFluentFontIcon("Window16Regular", "", 1, 16));
export const Window16Filled = ( /*#__PURE__*/createFluentFontIcon("Window16Filled", "", 0, 16));
export const Window20Regular = ( /*#__PURE__*/createFluentFontIcon("Window20Regular", "", 1, 20));
export const Window20Filled = ( /*#__PURE__*/createFluentFontIcon("Window20Filled", "", 0, 20));
export const Window24Regular = ( /*#__PURE__*/createFluentFontIcon("Window24Regular", "", 1, 24));
export const Window24Filled = ( /*#__PURE__*/createFluentFontIcon("Window24Filled", "", 0, 24));
export const Window28Regular = ( /*#__PURE__*/createFluentFontIcon("Window28Regular", "", 1, 28));
export const Window28Filled = ( /*#__PURE__*/createFluentFontIcon("Window28Filled", "", 0, 28));
export const Window32Regular = ( /*#__PURE__*/createFluentFontIcon("Window32Regular", "", 1, 32));
export const Window32Filled = ( /*#__PURE__*/createFluentFontIcon("Window32Filled", "", 0, 32));
export const Window32Light = ( /*#__PURE__*/createFluentFontIcon("Window32Light", "", 3, 32));
export const Window48Regular = ( /*#__PURE__*/createFluentFontIcon("Window48Regular", "", 1, 48));
export const Window48Filled = ( /*#__PURE__*/createFluentFontIcon("Window48Filled", "", 0, 48));
