"use client";
import { createFluentFontIcon } from '../../utils/fonts/createFluentFontIcon';
export const WrenchFilled = ( /*#__PURE__*/createFluentFontIcon("WrenchFilled", "", 2, undefined));
export const WrenchRegular = ( /*#__PURE__*/createFluentFontIcon("WrenchRegular", "", 2, undefined));
export const Wrench16Regular = ( /*#__PURE__*/createFluentFontIcon("Wrench16Regular", "", 1, 16));
export const Wrench16Filled = ( /*#__PURE__*/createFluentFontIcon("Wrench16Filled", "", 0, 16));
export const Wrench20Regular = ( /*#__PURE__*/createFluentFontIcon("Wrench20Regular", "", 1, 20));
export const Wrench20Filled = ( /*#__PURE__*/createFluentFontIcon("Wrench20Filled", "", 0, 20));
export const Wrench24Regular = ( /*#__PURE__*/createFluentFontIcon("Wrench24Regular", "", 1, 24));
export const Wrench24Filled = ( /*#__PURE__*/createFluentFontIcon("Wrench24Filled", "", 0, 24));
